### ISSUE TITLE
[v2] linux: requests keep in pending state if loading the asset fails

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#1003]
**Description**
On darwin a request keeps in pending state if loading of the asset fails, e.g. if the file is not found or another error occurs during loading of the asset.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new v2 template
2. Import a script into index.html which doesn't exist.
3. Start in dev mode and open the dev-tools on darwin.
4. The request keeps in pending state.

**Expected behaviour**
The request should be finished with a 404 status code.

**System Details**
Wails Version: v2.0.0-beta.21
MacOS Version: 12.0.1
Go Version: go1.17.2
Windows Version: Windows 10 20H2

**Additional context**
Returning a 404 or a 500 status code for other errors would also suit to #996, where some improvements were added that `processRequest` behaves more like as static webserver.

**Comment by leaanthony** [comment]
Great stuff! Just a note that I need to look at the Linux port of this

**Comment by stffabi** [comment]
Awesome, thanks for merging and taking a look at the Linux port.

**Comment by leaanthony** [comment]
The linux version of this is deeply frustrating. Both myself and @ianmjones have looked at it and can't work out why it still stays in a pending state despite calling all the right methods to close it.

**Comment by leaanthony** [comment]
I believe this is fixed now.
