### ISSUE TITLE
[v2] runtime.LogInfo calls causing fatal errors in wails build binary, but works fine in wails dev mode

### ISSUE THREAD

**Issue by achhabra2** [wailsapp/wails#1008]
**Description**
I am not 100% sure if this is the intended behavior or not. I have runtime.LogInfo statements in the app for debugging purposes. The app works fine in dev mode with no issues. However, when I build the app using wails build and run the binary it ends up force quitting and I couldn't figure out why. So I ended up going into the app package contents and running the file to see the terminal output. 

Here is the error that I'm getting: 
2021/12/03 15:34:25 cannot call 'github.com/wailsapp/wails/v2/pkg/runtime.LogInfo': Application not initialised

However, the application is clearly initialized and it works perfectly in dev mode. The issue also happens on Windows. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Call runtime.LogInfo within the app
2. Build a binary using wails build 
3. The App Force Quits

**Expected behaviour**
App should not crash? 

**System Details**

Wails CLI v2.0.0-beta.21
OS:		MacOS
Version: 	12.0.1
Go Version:	go1.17
Platform:	darwin
Architecture:	arm64

Also tested on windows and the same issue happens.

**Comment by leaanthony** [comment]
I pushed a fix for this on master.

**Comment by achhabra2** [comment]
Can confirm the issue does not exist on the latest version from the master branch. Thank you!

**Comment by leaanthony** [comment]
> Can confirm the issue does not exist on the latest version from the master branch. Thank you! 

Thank you for finding this 🙏
