### ISSUE TITLE
[v2]The `frontend:dev` is stuck.

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1009]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
After adding `frontend:dev`, there will be some problems.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use template initialization, add `frontend:dev` command in `wails.json` file
2. Run the `wails dev` command
3. See error

**Expected behaviour**
Here should be the first to execute the command in the `frontend:install` field, and then execute the command in the `frontend:dev`.

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/144744872-51d174b0-16b4-436a-be79-bd9bc7e8fa63.png)
![image](https://user-images.githubusercontent.com/28185258/144744890-4c222307-b889-4a79-a98e-4c54861af3e0.png)

**Then it will be stuck here. After I press `Ctrl+c`, the content in the subsequent red box will appear, and then it will automatically exit.**

![image](https://user-images.githubusercontent.com/28185258/144744957-cc5535e2-12da-4879-bf43-d8d25da435ae.png)

**System Details**
![image](https://user-images.githubusercontent.com/28185258/144744975-d9919c05-d81a-4a7c-875e-f504a4f0b1e8.png)

**Additional context**
No.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Is the expectation this would run in a different go routine? Does everything work if you run it in a different terminal?

**Comment by misitebao** [comment]
@leaanthony 
I tried the same operation in powershell and got the same feedback.

**Comment by leaanthony** [comment]
From what I'm seeing here, you have a problem with `vite build -w`. That's the script that's erroring. Does that script error in an external console?

**Comment by misitebao** [comment]
@leaanthony 
That is a front-end build command. If the front-end file is updated, it will be rebuilt automatically. `-w` is the abbreviation of `--watch`.

**Comment by leaanthony** [comment]
What you have copy and pasted above suggests that the vite command is failing because it doesn't work in a terminal

**Comment by misitebao** [comment]
So before that, the `frontend:install` command was not executed first. This should be a sure problem?
