### ISSUE TITLE
[v2] MacOS New feature of tray menu. 

### ISSUE THREAD

**Issue by mostend** [wailsapp/wails#1010]
Hi, I'm sorry to interrupt, but I've looked up a lot of information and I can't find. 

I want to implement a feature where when the user clicks the close button, the program runs in the background and the small icon appears in the right menu bar.

**Comment by stffabi** [comment]
I think the option you are searching for might be 'HideWindowOnClose' https://wails.io/docs/reference/options#hidewindowonclose

Have you tried this option!

**Comment by leaanthony** [comment]
I think they also want a tray menu. V2.1!

**Comment by waini1110** [comment]
> I think the option you are searching for might be 'HideWindowOnClose' https://wails.io/docs/reference/options#hidewindowonclose
> 
> Have you tried this option?

Yes, I have tried. but I found a issue. When closed and the program is running in the background, we have no way to show the main interface by clicking on the icon in the dock, only through other dialog.

**Comment by waini1110** [comment]
> I think they also want a tray menu. V2.1!

Do u have any plan? I think others need this feature as well, thank you very much for your reply.

**Comment by leaanthony** [comment]
It's true, `HideWindowOnClose` is better with the tray feature. That'll come in v2.1.

**Comment by adrianlungu** [comment]
Is it possible to contribute to this ?

I was looking into making https://github.com/getlantern/systray work with Wails but, at least on MacOS, they both seem to import dependencies from the OS and thus make the `linker` complain about duplicate symbols i.e.

> duplicate symbol '_OBJC_CLASS_$_AppDelegate'

Even if there were a simple way to get past this, I think they both want to lock on to the main thread and thus other issues may arise. 

So I've been thinking of adding the needed components directly into Wails and then figuring out a way to lock the main thread while still allowing both the systray and the main window to be able to use it (although it sounds like  it might not be as easy as I imagine it to be)

**Comment by leaanthony** [comment]
Running systray and Wails together is basically impossible. Tray support is coming right after be release. If you want to contribute you can look at how this works on Linux.

**Comment by sebastian0x62** [comment]
> Running systray and Wails together is basically impossible. Tray support is coming right after be release. If you want to contribute you can look at how this works on Linux.

So I do the impossible. :-D Actually currently using a tray menu library together with Wails. Even run Wails only ad-hoc and close it (not hide). I'm sure it's all just a hack. But it works so far quite good.

**Comment by leaanthony** [comment]
You're running 2 different processes for sure 😉

**Comment by sebastian0x62** [comment]
I'm still learning about how Wails work. For my simple app I made a main package only for binding (I don't use any bindings, btw) and a second with my main app. This app runs mostly in background sitting in the tray additionally. Through the tray menu I can open a Wails window, which only starts wails.Run() in a goroutine. The window (it's frameless) is closed via the runtime API.

I also had another setup, where I only used show and hide of the Wails window. But since the process is mostly only in the background, you can save the ressources of the WebView.

**Comment by leaanthony** [comment]
This issue is a mixture of requests. Closing in favour of #1521

**Comment by dvx** [comment]
> I'm still learning about how Wails work. For my simple app I made a main package only for binding (I don't use any bindings, btw) and a second with my main app. This app runs mostly in background sitting in the tray additionally. Through the tray menu I can open a Wails window, which only starts wails.Run() in a goroutine. The window (it's frameless) is closed via the runtime API.
> 
> I also had another setup, where I only used show and hide of the Wails window. But since the process is mostly only in the background, you can save the ressources of the WebView.
> 
> To make that possible, I had to reset the flags before running wails. Or you will get errors of already defined flags.

Heya @sebastian0x62 -- I need this feature and don't mind being a bit hacky (even if running two processes) -- how exactly are you getting `getlantern/systray` to work with `wails` v2? I can't seem to get it to work.

**Comment by sebastian0x62** [comment]
Hey @dvx, Still looking for a solution? I switched from web-based for Desktop development to Flutter. So I'm no longer actively looking into Wails and similar. I still have a tiny demo project for this systray thing.

**Comment by sebastian0x62** [comment]
@dvx, tried to send you the demo via mail. GMail didn't like the attachment. You can find the project for download for two weeks: https://drive.proton.me/urls/WAH0Z5PZCR#NnZZDxHndOGS

**Comment by dvx** [comment]
Thanks @sebastian0x62 -- got it! 🙏

**Comment by leaanthony** [comment]
Turns out you can run `getlantern/systray` with Wails by running it in a goroutine. However, I find systray limited and have got a WIP that already supports proper shutdown and automatic dark/light mode icon switching. More to come 👍

**Comment by dvx** [comment]
@leaanthony I couldn't get the wails app to build (even with `getlantern/systray` in a goroutine) on my M1 (it weirdly hangs). I've been following the [#feature/1521](https://github.com/wailsapp/wails/tree/feature/1521_Support_Tray_Menus) branch and will probably wait for the official solution, seems like it's quite close as-is.

Thanks for your work! 🙏

**Comment by leaanthony** [comment]
You're right, the way the Mac system tray works is a bit different than Windows, which will allow you to run it in a goroutine.

**Comment by lucasXing24** [comment]
Any update of this requests?

**Comment by mostend** [comment]
I'm trying the alpha version of V3, so far systray is working fine.

**Comment by leaanthony** [comment]
@mostend - just be aware it's still in development and there's no API guarantees at this stage. That being said, there's a really awesome feature that's almost done and I think after that it will probably be stable 👍

**Comment by raffolgo** [comment]
> @dvx, tried to send you the demo via mail. GMail didn't like the attachment. You can find the project for download for two weeks: https://drive.proton.me/urls/WAH0Z5PZCR#NnZZDxHndOGS

Hello ! I am also interested by making a systray on my mac OS app, can you resend me the link please ?

**Comment by ysaakpr** [comment]
Any way to add the icon to Top right corner menubar ?

**Comment by munjalpatel** [comment]
@leaanthony Wails is awesome! Any updates on v3 ETA? I really need systray and trying to avoid hacks, if possible.

**Comment by edosssa** [comment]
+1

**Comment by leaanthony** [comment]
Feel free to try out the alpha and see if it works for you: https://v3alpha.wails.io

**Comment by edosssa** [comment]
Thanks @leaanthony, will check it out

**Comment by TCB13** [comment]
> Feel free to try out the alpha and see if it works for you: https://v3alpha.wails.io

> wails3 version
v3.0.0-alpha.53

> wails3 dev
(...)
.\main.go:55:20: app.NewSystemTray undefined (type *application.App has no field or method NewSystemTray)

Maybe not. :(

**Comment by ricaud** [comment]
> > Feel free to try out the alpha and see if it works for you: https://v3alpha.wails.io
> 
> > wails3 version
> > v3.0.0-alpha.53
> 
> > wails3 dev
> > (...)
> > .\main.go:55:20: app.NewSystemTray undefined (type *application.App has no field or method NewSystemTray)
> 
> Maybe not. :(

I was able to get this to work with `systray := app.SystemTray.New()` instead of `app.NewSystemTray()`
