### ISSUE TITLE
unable to access hosted database after running wails build

### ISSUE THREAD

**Issue by bashbunni** [wailsapp/wails#1014]
**Description**

I'm able to access my database just fine when I'm doing wails serve and npm run serve. However, when I go to build then run my project I get an authorization error + seg fault. I don't have any issue connecting to the database when I do `wails serve` or if I do `go run .` with the Wails code commented out of my main.go. I've tried editing my DB connection to set tls=true and GODEBUG=x509ignoreCN=0 to resolve the error message I'm getting, but it broke the connection on all fronts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/bashbunni/habit-tracker
2. Clone repo
3. Run `wails build`
4. Run ./build/habit_tracker
Note: My db connection details are in a .env file which isn't included in the git repo, so you likely won't be able to reproduce the issue

**Expected behaviour**

**Screenshots**
This is the error I get when I run `wails build` then `./build/habit_tracker`
![error message](https://user-images.githubusercontent.com/15822994/145064102-cedad5ae-185c-445b-b603-6eddce0f25fa.png)

this is where I open the database (works fine in wails serve)
![server](https://user-images.githubusercontent.com/15822994/145064355-4195ee01-9619-40ea-8563-dfde5693c651.png)

this is my main.go with commented out sample code which connects to the database no problem
![main.go](https://user-images.githubusercontent.com/15822994/145065389-e79f9134-28c5-4b0f-9dc2-017f6794f6d1.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.8 |
| Go Version    | go1.17.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.3.0 |
| Npm           | 8.1.1 |
| Node          | v14.18.1 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by bashbunni** [comment]
I'm migrating the project to v2, I'll update the issue once I've done so to see if it resolves the issue

**Comment by bashbunni** [comment]
Nevermind, just went to run and realized I missed the part where it said v2 isn't available on Linux until January

**Comment by bashbunni** [comment]
I'm going to try again on a Windows computer, will update the status here!

**Comment by leaanthony** [comment]
Thanks for the detailed report! Really strange that connecting to the db would work in one mode and not the other. Do you know which particular line causes the crash?

**Comment by bashbunni** [comment]
I added a bunch of print statements to try and see where the app was crashing and it looks like it crashes on line 34 of main.go where I call `app.Run()` or at least that's my speculation because it printed fine before that line but not after

**Comment by bashbunni** [comment]
I tried removing the calls to the db on the frontend when the app runs to try and debug. I got this error when I tried to build then run the application. It refers to `main.go:34` which is the `app.Run()` command
![image](https://user-images.githubusercontent.com/15822994/145098424-d15c2424-d70d-4f3d-a6df-2fb3521027c4.png)

**Comment by bashbunni** [comment]
I figured I'd try building one of the template projects and I'm getting the same error which is interesting 
![image](https://user-images.githubusercontent.com/15822994/145100842-e55cd970-7b83-4993-a23d-776b97e14006.png)

**Comment by bashbunni** [comment]
Well I figured out what it is... I was using another user account's terminal with `sudo su soysocks` and didn't clue in that this would be a permissions issue with me trying to execute another user's program file :facepalm:

**Comment by leaanthony** [comment]
Glad you figured it out! 🚀
