### ISSUE TITLE
How to preview in real time？

### ISSUE THREAD

**Issue by ZeronoFreya** [wailsapp/wails#1018]
最近刚接触wails，只考虑windows平台.
前端使用 vite2 + vue3 开发
wails dev 给我的感觉是它只在乎编译后的前端代码（dist里的内容）但现实情况下不可能改一下代码就编译一次，那怎样在vue的开发模式下访问go代码？我没有找到相关说明

## 以下是谷歌翻译：

I have just come into contact with wails recently, and only consider the windows platform.
The front end uses vite2 + vue3 development
Wails dev gives me the feeling that it only cares about the compiled front-end code (content in dist) but in reality it is impossible to change the code and compile it once, so how to access the go code in the Vue development mode? I did not find the relevant instructions

**Comment by leaanthony** [comment]
@misitebao might be able to help withh this

**Comment by liuhaogui** [comment]
package.json

vue2 example
```
    "build-watch": "vue-cli-service build --watch --mode development",
```

**Comment by misitebao** [comment]
@ZeronoFreya 
Look here 👉 https://vitejs.dev/guide/build.html#rebuild-on-files-changes
