### ISSUE TITLE
[v2] `wails build` and `wails dev` fails on MacOS for `beta.21` and `beta.22`

### ISSUE THREAD

**Issue by hkmshb** [wailsapp/wails#1019]
**Description**
Running `wails build` or `wails dev` fails with the error shown in the attached screenshot for `v2.0.0-beta.21` and `v2.0.0-beta.22` on MacOS. However, the same commands work fine for `v2.0.0-beta.20`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Wails `v2.0.0-beta.21` or `v2.0.0-beta.22`
2. run `wails build` or `wails dev`
3. See error

**Expected behaviour**
A successful build or run of the application in development mode.

**Screenshots**
<img width="1221" alt="Screenshot 2021-12-12 at 09 51 57" src="https://user-images.githubusercontent.com/2089370/145706214-cbd98628-6e65-4883-97de-31d8ed2271e8.png">

**System Details**
<img width="617" alt="Screenshot 2021-12-12 at 09 52 40" src="https://user-images.githubusercontent.com/2089370/145706233-347d7fdf-1cf9-43b3-a354-15133d9b4968.png">

**Additional context**
- N/A

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by stffabi** [comment]
I think this has already been fixed on master, could you please give that a try?

See [bleeding egde](https://wails.io/docs/guides/bleeding-edge) for docs how to use the master.

**Comment by leaanthony** [comment]
This whole process got me thinking: As UTI is only available on 11+, those binaries will only work on 11+. Likewise, even though I've now got <11 working by not linking to UTI, it means that those binaries won't run on >11. What do Mac developers normally do in this situation?

**Comment by hkmshb** [comment]
@stffabi @leaanthony Bleeding edge works as expected. Thanks.
