### ISSUE TITLE
[v2] size was reset.

### ISSUE THREAD

**Issue by azwc** [wailsapp/wails#1022]
**Description**
After I moved the window, the size was reset. (Initialize the project without making any changes)

**To Reproduce**
Steps to reproduce the behaviour:
1. Double-click titlebar.
2. moving window.
3. it will be reset.

~~**Expected behaviour**~~

~~**Screenshots**~~

**System Details**
```
Wails CLI v2.0.0-beta.22


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19042)
ID:             20H2
Go Version:     go1.17.1
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       96.0.1054.53
npm             N/A             Installed       7.11.2
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Additional context**
Windows cannot be resized by dragging the mouse

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Sounds like standard Windows 10 behaviour to me. Does this for any window.

**Comment by sinyat** [comment]
> Sounds like standard Windows 10 behaviour to me. Does this for any window. Please reopen if you think this is something else.

I see what you mean. Yes, I was wrong. 

As an additional question I raised in the above issue:
```
Additional context
Windows cannot be resized by dragging the mouse
```
I tried the DisableResize property, I have tried DisableResize as well as width and height. I am not sure how to do it.

**Comment by leaanthony** [comment]
That is for resizing a window in normal circumstances.
