### ISSUE TITLE
wails serve  and npm run serve does not work for angular 8 project

### ISSUE THREAD

**Issue by qingbawindowsdedongxizhengliyixia** [wailsapp/wails#1023]
**Description**
cannot debug the frontend files in hot debugging mode.

- wails version: 1.6.8/1.6.9
- os: ubuntu 20.04
- go version: go1.16.11 linux/amd64
- web browser: chrome Version 96+ & firefox Version 95+

**To Reproduce**
Steps to reproduce the behaviour:
1. use `wails init playground` to create a project
2. cd `playground` folder and use `wails bubild` to build it
3. use `wails serve` to run `playground` in bridge mode, then cd `frontend` folder, use `npm run serve` and then open http://localhost:4200 in the browser (chrome Version 96+ & firefox Version 95+)

### wails serve output below
```
INFO[0000] [App] Starting                               
INFO[0000] [Events] Starting                            
INFO[0000] [IPC] Starting                               
INFO[0000] [Bind] Starting                              
INFO[0000] [Bind] Binding Go Functions/Methods          
INFO[0000] [Bind] Bound Function: main.basic()          
INFO[0000] [Bridge] Bridge mode started.                
INFO[0000] [Bridge] The frontend will connect automatically. 
INFO[0000] [Events] Listening                           
>>>>> To connect, you will need to run 'npm run serve' in the 'frontend' directory <<<<<
```

### npm run serve output below
```
> my-app@0.0.0 serve /tmp/w/playground/frontend
> npx ng serve --poll=2000 --host=0.0.0.0

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
WARNING: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
 10% building 4/4 modules 0 activeℹ ｢wds｣: Project is running at http://0.0.0.0:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
                                                                                              
Date: 2021-12-14T11:29:41.062Z
Hash: 78bac621b4c993c95b20
Time: 9494ms
chunk {main} main.js, main.js.map (main) 13.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 148 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 463 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.97 MB [initial] [rendered]
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
 Compiled successfully.
```

**Screenshots**
it's ok if you run the `build/playground` executable
![image](https://user-images.githubusercontent.com/79832213/145991776-c35a2558-3911-43d3-b8a0-15ad5bcac859.png)

**but you will see nothing in the web browser.**
![image](https://user-images.githubusercontent.com/79832213/145991179-da3eac0e-017a-4f8c-9777-59b378663006.png)

**Comment by rpiscopo-easyweb** [comment]
In project.json in root dir try replacing
 `"serve": "npm run serve"`
with
`npx ng serve --poll=2000`

Then, try again `wails serve`

**Comment by qingbawindowsdedongxizhengliyixia** [comment]
> npx ng serve --poll=2000
Thanks, but it seems not work neither.
![image](https://user-images.githubusercontent.com/79832213/146187307-7fa4606e-ab71-414d-b0c2-adf19be3c86a.png)


by the way, today I tested this again, the `bridge mod` + `hot debugging` ONLY works at the moment you keep all template files changed.

**I changed  template html file `app.component.html`,  added one more `!` ===> `Welcome to {{ title }}!!`**
**the hot debugging mode crashed :(**
![image](https://user-images.githubusercontent.com/79832213/146187734-e12340ab-8571-42ec-b715-5a6f98c34275.png)

**Comment by leaanthony** [comment]
Looks like a bad selector in your code. If you can isolate this as a Wails problem, we will fix it 👍

**Comment by qingbawindowsdedongxizhengliyixia** [comment]
According to the errors shown in the console, It looks like a problem with a bad selector, but I don't changed anything for the default selector, which created by wails from its template code. 
I only changed one line code `Welcome to {{ title }}!!`, one more  `!` added for the file `app.component.html`.

**Comment by leaanthony** [comment]
v1 is on feature/bug freeze. I recommend upgrading to v2 👍
