### ISSUE TITLE
macOS 11.6.1 menu error

### ISSUE THREAD

**Issue by xingcxb** [wailsapp/wails#1026]
**Description**

![4AC946E863BBA14D283E8412D234B212](https://user-images.githubusercontent.com/866409/146636253-1799c45a-4e89-4ef4-979c-8214fcd3cd69.jpg)

* wails version: 2.0.0-beta.23
* os: macOS 11.16.1
* go version: go version go1.17.5 darwin/amd64
* web browser: Edge version 96+
* CLT: 13.2.0.0.1.1637719136

**To Reproduce**
Steps to reproduce the behaviour:
1. use `wails dev`
2. The label of the menu has no text

**Comment by leaanthony** [comment]
Please provide a program to reproduce. Thanks.

**Comment by xingcxb** [comment]
> Please provide a program to reproduce. Thanks.

https://github.com/xingcxb/md

**Comment by leaanthony** [comment]
![image](https://user-images.githubusercontent.com/1943904/147291098-1b8fef41-7a4d-4313-8e2d-07443efd94ae.png)

**Comment by leaanthony** [comment]
Thanks for opening this bug and please let me know how you get on! 👍
