### ISSUE TITLE
[v2]WebView2 not found

### ISSUE THREAD

**Issue by iamxvbaba** [wailsapp/wails#1027]
**Description**
I have installed WebView2, but when I run `wails doctor` it prompts that it is not found.
<img width="593" alt="installed" src="https://user-images.githubusercontent.com/28732408/146646336-525e44aa-cfc0-4b50-a952-928bc4085673.png">

**To Reproduce**
1. wails doctor
2. out
<img width="517" alt="out" src="https://user-images.githubusercontent.com/28732408/146646329-11796563-8435-4fe7-8418-46f4a71ab719.png">

**Comment by leaanthony** [comment]
What vesion did you install?

**Comment by leaanthony** [comment]
What vesion did you install?

**Comment by iamxvbaba** [comment]
> What vesion did you install?

WebView2 version: 96.0.1054.62

**Comment by iamxvbaba** [comment]
use admin.
