### ISSUE TITLE
Allowing 2 Windows to run Asynchronously, or new window opens after first is closed (using v1 on Linux)

### ISSUE THREAD

**Issue by michaelolson1996** [wailsapp/wails#1029]
**Is your feature request related to a problem? Please describe.**
Most desktop frameworks allow for multiple windows open at a time, and the ability to open windows when 1 closes

**Describe the solution you'd like**
The functionality in order to control multiple windows, I have 2 frontend folders and would like to be able to open a main window after user has successfully signed in on the signin window

**Describe alternatives you've considered**
I have been searching online for a solution, tried to start a new wails.App before and after closing the first app via runtime method, with no such luck. It looks like the solution is a bit deeper than what I am capable of with my current wails and go knowledge (first app with wails)

**Additional context**
I am very excited about wails app and thank you!

**Comment by leaanthony** [comment]
Hi @michaelolson1996 😄 We certainly plan on supporting multiple Windows, right after we get Linux v2 done, then tray + context menus. If you'd like to be part of planning that then that would be amazing! I imagine the way it would work is that the runtime will have a `GetWindow()` or something where all of the `Window*` methods would work against. The question then is how do the following things will work:
  * Child windows of the main window or child windows of child windows?
  * When you emit an event is it picked up by all windows?

It's be a significant API change so it would warrant a v3 tag, but that's not a problem. Thoughts?

**Comment by michaelolson1996** [comment]
Hi @leaanthony First of all apologies for the late response, I was with the family for the holidays. I would love to help out with this project in any way that I can, I wanted to let you know I'm using this framework for my school capstone project which I'll be working on for the next 3 months, and am really excited about it. 

I think that having one main window as a controller of other windows makes sense and simplifies control over the application. As far as events within windows, if there is one controller (main window), it should be a sort of middleman between other windows. 

I would love to help with this any way that I can, for the next couple of months I will be busy with my school project but it will give me a chance to keep working with Go and Wails, please let me know if there are any small things I can do in the meantime.

**Comment by leaanthony** [comment]
Thanks for the very detailed report! I'm not sure why this would panic in this way but the vanilla template work. I'll investigate when I get chance. Currently moving house 😱

**Comment by Landmax-Global** [comment]
Hi @leaanthony  @michaelolson1996  this is my first look at Wails and also very excited to migrate away from Electron. I am also looking at building a multi-content sourced main window. Some of the content will be mine, some will be from potentially untrusted sources. I want to use Go to "sanitize"  sites with bloated content. Then just just display the useful content ( no ads, no tracking, no garbage), in a small sub window (frame). The main window can interact with the new sanitized 3rd party content. I would also be able to help, but I am just starting to learn Go, and the authors of training seem to assume us newbies are coming from a C background and not a Javascript background, so the explanation are not very useful. Hopefully I can get up to speed quickly. Cheers.

**Comment by leaanthony** [comment]
@michaelolson1996 - Good luck with the project 👍 Let me know how we can help. I can almost guarantee that multiple windows will not be available within that timeframe, so bear that in mind please. Let us know how we can work around that.

@Landmax-Global - You should be able to do this by fetching the html using Go, cleaning it up, emitting an event with the new html, picking it up in the frontend and using some sort of `innerHTML`-fu to inject it. I'm sure there's better ways 👍

**Comment by michaelolson1996** [comment]
Hey @leaanthony thank you, the project is going well. I just left a issue with my other github account regarding the error "Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal". I am using cognito authentication on the react/redux front end and it works in the browser, seems to have issues in the build. If you have a quick fix for this that would be amazing, otherwise its not important. My project will be done in 5 weeks and look forward to getting more involved with this project afterwards!

**Comment by leaanthony** [comment]
If you can find a way to get rid of that message then amazing. AFAICT it's hardcoded in webkit

**Comment by leaanthony** [comment]
Hey @michaelolson1996 - just wondering where we are with this request? Are you simply wanting multiple windows?

**Comment by michaelolson1996** [comment]
Hey @leaanthony I think it would be a neat feature, other services provide that functionality. I will be done with my capstone in 4 days and would like to see what I can do to help make this happen after I am finished with my capstone.
