### ISSUE TITLE
Windows 32 wails build

### ISSUE THREAD

**Issue by veliev** [wailsapp/wails#103]
Trying to build wails 0.13.3 for 32 bit Windows build

1. set GOARCH = 386
2. wails build

I get the error:

> | Ensuring Dependencies are up to date ... build quotes.exe: cannot load github.com/wailsapp/webview: no Go source files
> 
> ! Ensuring Dependencies are up to date ...
> Error: exit status 1

github.com/wailsapp/webview installed

When adding github.com/wailsapp/webview to mod.go error

> Ensuring Dependencies are up to date...go build github.com/wailsapp/webview: build constraints exclude all Go files in C:\User
> s\IVC-TVeliev\go\pkg\mod\github.com\wailsapp\webview@v0.4.0
> 
> ! Ensuring Dependencies are up to date...
> Error: exit status 1

**Comment by leaanthony** [comment]
Thanks for opening this issue. Officially only 64bit Window 10 is supported but that doesn't mean we don't want to support 32 bit. Are you certain you have GO111MODULE=on set? If you are able to reproduce but run `wails issue` as soon as it happens, then we will be able to capture a lot more information about your setup.

**Comment by veliev** [comment]
@leaanthony Sorry for not answering for so long, the computer on which the project is at work.
GO111MODULE, not sure. I use IDE Golang from jetbrains, I include the vgo (Go Module) parameter in the setup. Without it, my project is not building, swears at other packages besides main.
Wails issue I'm not sure that it will work correctly. Because after upgrading to version 15, **wails init** does not work

> Wails v0.15.0 - Initialising project
> 
> The name of the project (My Project): test2
> Project Name: test2
> The output binary name (test2):
> Output binary Name: test2.exe
> Project directory name (test2):
> Project Directory: test2
> Please select a template:
>   1: Vuetify Basic - Vuetify + Webpack
>   2: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
> Please choose an option [1]: 2
> Template: Vue2/Webpack Basic
> > Generating project...
> panic: The handle is invalid.
> 
> goroutine 1 [running]:
> github.com/leaanthony/spinner.hideCursor(...)
>         C:/Users/IVC-TVeliev/go/src/github.com/leaanthony/spinner/cursor_windows.go:21
> github.com/leaanthony/spinner.(*Spinner).Start(0xc0000e8580, 0x0, 0x0, 0x0)
>         C:/Users/IVC-TVeliev/go/src/github.com/leaanthony/spinner/spinner.go:221 +0x1fe
> github.com/wailsapp/wails/cmd.InstallFrontendDeps(0xc00000ac90, 0x21, 0xc00009a9a0, 0x0, 0x82b45d, 0x5, 0x0, 0x0)
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/helpers.go:209 +0xf5
> main.init.2.func1(0xc00007dea8, 0x4121aa)
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/wails/4_build.go:71 +0x46f
> github.com/wailsapp/wails/cmd.(*Command).Run(0xc00009a6e0, 0xc000004470, 0x0, 0x0, 0xc000056d98, 0x26)
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/cli.go:170 +0xd7
> github.com/wailsapp/wails/cmd.(*Command).Run(0xc00009a2c0, 0xc000004470, 0x1, 0x1, 0xc00007df78, 0x75eb86)
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/cli.go:150 +0x2dc
> github.com/wailsapp/wails/cmd.(*Cli).Run(0xc000004c80, 0x0, 0x0, 0x0, 0xc00007df88, 0xc00004c058)
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/cli.go:47 +0x95
> main.main()
>         C:/Users/IVC-TVeliev/go/src/github.com/wailsapp/wails/cmd/wails/main.go:15 +0x45
> 
> ! exit status 2
> Error: exit status 2

**Comment by leaanthony** [comment]
No worries. Just make sure you are using Go 1.12 and have GO111MODULE=on and it should work.

**Comment by veliev** [comment]
@leaanthony Added to PATH **GO111MODULE=on**, now build without errors. But on a 32 bit Windows error, that different bit systems.
My system: 
Windows 10 64 bit
Golang 1.12.5

**Comment by veliev** [comment]
It meant that the compiled exe file (with the parameter set GOARCH = 386) does not run on 32-bit Windows

**Comment by leaanthony** [comment]
Did you install the 32bit versions of the gcc tools?

**Comment by veliev** [comment]
@leaanthony Installed 64bit version. I will try to reinstall 34bit version and compile wails project

**Comment by veliev** [comment]
Error with 32bit gcc:

> | Ensuring Dependencies are up to date...# herson.exe
> C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
> C:\Users\IVC-TV~1\AppData\Local\Temp\go-link-666902423\go.o: file not recognized: File format not recognized
> collect2.exe: error: ld returned 1 exit status

**Comment by veliev** [comment]
New error

> In file included from C:\Users\IVC-TVeliev\go\src\github.com\wailsapp\webview\webview.go:27:0:
> ./webview.h:64:22: fatal error: mshtmhst.h: No such file or directory
> compilation terminated
Webview does not work with gcc 32bit 
Post [https://github.com/zserge/webview/issues/33#issuecomment-340335908](https://github.com/zserge/webview/issues/33)

**Comment by veliev** [comment]
I will collect the project on webview under 32bit Windows. Let's see what happens

**Comment by leaanthony** [comment]
Thanks for looking at this. Interested to see what you find!

**Comment by veliev** [comment]
In the official documentation:

> GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ go build -ldflags "-H windowsgui"

They use mingw

**Comment by leaanthony** [comment]
Thanks for looking at this. If you use 32bit mingw, does it work? Am happy to add 32bit installer details into the docs if it works 👍

**Comment by leaanthony** [comment]
Any updates @veliev ?

**Comment by veliev** [comment]
@leaanthony just reinstalled golang from 64 to 32 bit, building exe work on windows 32. But arises error script, now I deal with it.
I think it is possible download archive go***.windows-386.zip unpack and change as needed path (gobin, gorobot) from 64 to 32 bit folder.
Mingw dont install to my working PC, because the internet is through a proxy

**Comment by leaanthony** [comment]
Thanks for the update. What do you think we need to do to close this ticket now?

**Comment by veliev** [comment]
@leaanthony i think yes, the problem is solved. Now i can run wails project on windows 32. Thank you for such a wonderful instument (wails) and for its support.

**Comment by leaanthony** [comment]
Hey glad to help! If you thhink the Windows documentation needs to be updated for 32bit, please consider making a PR! Thanks for your time.
