### ISSUE TITLE
[v2]Application not initialised

### ISSUE THREAD

**Issue by iamxvbaba** [wailsapp/wails#1032]
**Description**
Application not initialised.

**Screenshots**
![1{AL`5@5}51{6%@9NE OMWT](https://user-images.githubusercontent.com/28732408/146938476-f59a5682-d2f9-428c-85c4-79d9e302afac.png)
![( B978SQ3BKRW12W)P{ZDA7](https://user-images.githubusercontent.com/28732408/146938498-732fad3f-6b97-4040-8154-d97bcf79b620.png)

**Comment by leaanthony** [comment]
You need the context given in the lifecycle hooks: https://wails.io/docs/reference/runtime/intro
I've updated the error to make it more explicit.
