### ISSUE TITLE
[v2] Cross Compilation Investigation

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1041]
Although there is the options for using xgo, this article suggests it might be possible to cross-compile in a more lightweight way using zig: https://dev.to/kristoff/zig-makes-go-cross-compilation-just-work-29ho

**Comment by tmclane** [comment]
Hey thanks for posting this!

**Comment by tmclane** [comment]
V1 used to work with what was available.. if it isn't working now I would open an issue on that.

**Comment by tmclane** [comment]
Didn't mean to be harsh.

**Comment by leaanthony** [comment]
Cross compilation for v2 works for all scenarios apart from when the target is Mac and the compilation host isn't.

**Comment by leaanthony** [comment]
> V1 used to work with what was available.. if it isn't working now I would open an issue on that.

V1 is at bug+feature freeze.

**Comment by leaanthony** [comment]
https://github.com/marcus-crane/october/blob/main/.github/workflows/release.yaml

**Comment by springyboiii** [comment]
Oh okay. But I could not get cross-compiling to Linux working as well. Anyway, Thank you for this awesome project. I'll start looking for alternatives to this compiling issue.
wails build -platform linux
Wails CLI v2.0.0-beta.33


App Type:               desktop
Platforms:              linux
Compiler:               C:\Program Files\Go\bin\go.exe
Build Mode:             Production
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []

Building target: linux
----------------------
Crosscompiling to Linux not currently supported.

**Comment by leaanthony** [comment]
Latest versions should work for you but you need docker

**Comment by leaanthony** [comment]
We may leave "Cross-compilation" for Mac as a github actions task for v2. I will timebox trying to get xgo working to 1 evening and then leave this as a post-v2 task. The majority of people developing for Mac will have a Mac so I'm not sure how many people this really affects.

**Comment by leaanthony** [comment]
Cross compilation will be handled by GitHub actions for v2. Bumping this down the road.

**Comment by leaanthony** [comment]
Another option: https://github.com/goreleaser/goreleaser-cross

**Comment by aadog** [comment]
How to cross compile linux/arm

**Comment by leaanthony** [comment]
Using GitHub actions is the best way

**Comment by zllovesuki** [comment]
Attempting to cross compile to darwin as target using osxcross on linux amd64 host, with 12.3 sdk fails with amd64 target:

```
➜  phantom git:(main) ✗ CGO_CFLAGS="-mmacosx-version-min=10.15" CGO_LDFLAGS="-mmacosx-version-min=10.15 -framework UniformTypeIdentifiers" CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="o64-clang" CXX="o64-clang++" go build -tags desktop,production -buildmode=pie -buildvcs=false -a -o build/bin/Phantom-darwin-amd64
# kon.nect.sh/phantom
/usr/local/go/pkg/tool/linux_amd64/link: running o64-clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[WailsContext OpenFileDialog:::::::::::] in 000026.o
      -[WailsContext SaveFileDialog:::::::] in 000026.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

➜  phantom git:(main) ✗ CGO_CFLAGS="-mmacosx-version-min=11.1" CGO_LDFLAGS="-fuse-ld=lld -mmacosx-version-min=11.1 -framework UniformTypeIdentifiers" CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 CC="o64-clang" CXX="o64-clang++" go build -tags desktop,production -buildmode=pie -buildvcs=false -a -o build/bin/Phantom-darwin-arm64

```

arm64 built is successful, but I don't have an M1 machine right now to test. Do we need something special to enable the usage of `@available` macro?

**Comment by zllovesuki** [comment]
Cross compiling to darwin target works on linux host with osxcross.

Requirements:
1. Package the Xcode SDK from an macOS host. **[Please ensure you have read and understood the Xcode license
   terms before continuing.](https://www.apple.com/legal/sla/docs/xcode.pdf)**
2. Build the toolchain with `./build.sh`
3. Build the runtime library with `./build_compiler_rt.sh`

Examples:
```
CGO_CFLAGS="-mmacosx-version-min=10.15" CGO_LDFLAGS="-fuse-ld=lld -mmacosx-version-min=10.15 -framework UniformTypeIdentifiers" CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="o64-clang" CXX="o64-clang++" go build -tags desktop,production -buildmode=pie -buildvcs=false -ldflags "-s -w" -a -o build/bin/Phantom-darwin-amd64

CGO_CFLAGS="-mmacosx-version-min=11.1" CGO_LDFLAGS="-fuse-ld=lld -mmacosx-version-min=11.1 -framework UniformTypeIdentifiers" CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 CC="o64-clang" CXX="o64-clang++" go build -tags desktop,production -buildmode=pie -buildvcs=false -ldflags "-s -w" -a -o build/bin/Phantom-darwin-arm64
```

Then you can make an universal binary with:
```
lipo -create -output build/bin/Phantom-darwin build/bin/Phantom-darwin-amd64 build/bin/Phantom-darwin-arm64
```

The resulting binary can be packaged into `.app`. Running codesign and notary on an macOS host will work with the cross compiled binary:
```
rachel@rachels-iMac-Pro phantom % ./codesign.sh     
Conducting pre-submission checks for Phantom.app.zip and initiating connection to the Apple notary service...
Submission ID received
  id: (redacted)
Upload progress: 100.00% (11.9 MB of 11.9 MB)   
Successfully uploaded file
  id: (redacted)
  path: /Users/rachel/code/phantom/build/bin/Phantom.app.zip
Waiting for processing to complete.
Current status: Accepted..........
Processing complete
  id: (redacted)
  status: Accepted
Processing: /Users/rachel/code/phantom/build/bin/Phantom.app
Processing: /Users/rachel/code/phantom/build/bin/Phantom.app
The staple and validate action worked!
```

You can try using https://github.com/indygreg/apple-platform-rs for codesigning on Linux, however I haven't tested it yet.

**Comment by abjrcode** [comment]
Hi, until this investigation is concluded I wanted to solve all of the cross compilation and targeting issues for my own project so cooked up a Docker solution inspired by [go-releaser-cross](https://github.com/goreleaser/goreleaser-cross). It is available as [open source here](https://github.com/abjrcode/cross-wails) so feel free to use it.

**Comment by leaanthony** [comment]
Thank you!

**Comment by federico-ntr** [comment]
> Using GitHub actions is the best way

Unfortunately I can't use GitHub actions at work as we don't use GH at all, so not a way for us. Our pipelines run on on-premise machines which are either linux or windows. I'll try to play around with qemu and, in case of success, i'll report here.

**Comment by leaanthony** [comment]
> EDIT: actually I don't think it's legal to setup virtual macos machines, so I guess I'll stick with manual builds for darwin.

Indeed, and it's not legal for us to re-distribute macos sdks so you can use docker to do it (though we may be able to find a way that doesn't involve us redistributing anything)...

**Comment by leaanthony** [comment]
There's been nothing to update on this for a while so I'm closing this for now. Cross-platform compilation is still tricky due to macOS restrictions but if we find a solution, it'll be for v3.

**Comment by JaneX8** [comment]
It seems that as of end 2024 there is no single platform that allows true cross-compilation especially one that includes to and from MacOS. When not using GH. This is just very sad. While golang can, the GUI space is absolutely hopeless. Unfortunately also with great tools like Wails and Tauri.

**Comment by leaanthony** [comment]
It's partly on Apple...

**Comment by JaneX8** [comment]
I'd argue it's entirely on Apple. But good luck explaining that to their users who don't understand why it such a trouble to develop cross-platform for their platform as well.

**Comment by saymon005** [comment]
Crosscompiling to Mac not currently supported. I am trying to build for Mac from linux environment with this command - wails build -platform darwin/universal 
how can I solve that?

**Comment by COD3HUNT3R** [comment]
> Cross compilation for v2 works for all scenarios apart from when the target is Mac and the compilation host isn't. If you really want to cross compile right now you can do so using **GitHub actions**. Both the October app and https://riftshare.app take this approach. I'll update the docs with this information over the weekend 👍
> 
> https://github.com/marcus-crane/october/blob/main/.github/workflows/release.yaml

@saymon005

**Comment by tmclane** [comment]
Honestly I think picking up a real cheap Mac might be your best short term option.
How are you testing it on a Mac?

**Comment by saymon005** [comment]
I used Mac mini

**Comment by JaneX8** [comment]
> Honestly I think picking up a real cheap Mac might be your best short term option.
> How are you testing it on a Mac?  

I did that too. I bought a cheap second hand Mac Mini M1. Clearly take an M1 or newer. Otherwise you will not be able to compile for ARM/Aarch. But from M1 you can compile to older x64 architecture too.
