### ISSUE TITLE
Cannot install wails CLI 2.0 beta24

### ISSUE THREAD

**Issue by pierrejoye** [wailsapp/wails#1043]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
Install b24 wails CLI

**To Reproduce**
Steps to reproduce the behaviour:
1.  go install github.com/wailsapp/wails/v2/cmd/wails@latest
2. See error

**Expected behaviour**
Wails CLI installed

**Screenshots**
`c:\..\development\desktop\app-wails> go install github.com/wailsapp/wails/v2/cmd/wails@latest

go install: github.com/wailsapp/wails/v2/cmd/wails@latest (in github.com/wailsapp/wails/v2@v2.0.0-beta.24):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.`

**System Details**
Can't use wails doctor as its install is the bug I encounter, however here you go:
Win10 21H2, build 19044.1415
go 1.17.5

**Additional context**

I suspect that line to cause this error:

replace github.com/leaanthony/go-webview2 => C:\Users\leaan\Documents\wails-v2-beta\go-webview2

at https://github.com/wailsapp/wails/blob/a03d1e5ac5f39dafe320e840fdba7870b7a424d9/v2/go.mod#L84

as I obviously don't have go-webview2 access to your local folder :)

works fine with v2.0.0-beta23, which does not have the replace line.

- [X] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by pierrejoye** [comment]
I may open another issue but I will need to investigate, I do have (and use) webview2 on Windows:

![image](https://user-images.githubusercontent.com/282408/147413363-aac2b89f-4e2d-48c3-94dd-138df887d102.png)

but go wails CLI does not see it.

**Comment by leaanthony** [comment]
Gah, thanks for this. Fixing this issue fixes the other. I will do a new release in a few hours

**Comment by leaanthony** [comment]
Fixed with v2.0.0-beta.25

**Comment by pierrejoye** [comment]
Thanks for the quick fix (and indeed this awesome project :)

Confirmed, b26 is back on!

`
> C:\apps\go\bin\wails version
v2.0.0-beta.26

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

> C:\apps\go116\bin\wails doctor
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       96.0.1054.62
npm             N/A             Installed       7.13.0
*upx            N/A             Available

*  - Optional Dependency
`

**Comment by leaanthony** [comment]
I'd suggest updating to beta.27 using `wails update -pre` 👍
