### ISSUE TITLE
Loading of 'relative file' linuxdb.yaml results in hardcoded ties to source location

### ISSUE THREAD

**Issue by buddyabaddon** [wailsapp/wails#1044]
**Description**

The current implementation of LoadRelativeFile() in cmd/fs.go leverages 'runtime.Caller(0)' to form the absolute path to a relative file (runtime.Caller(0) + relativeFile). LoadRelativeFile() appears to solely be used by NewLinuxDB() in cmd/linuxdb.go when loading cmd/linuxdb.yaml. The use of runtime.Caller(0) causes the built binary to reference the source location of where the binary was built when loading './linuxdb.yaml' rather than the location of the executing binary.

Example:
Assume wails source is cloned into '/home/foo/wailsapp/wails' and is built running 'go build/install' in cmd/wails. If the resulting binary is deployed to /usr/local/bin on a system, it attempts to load 'linuxdb.yaml' from '/home/foo/wailsapp/wails/cmd/linuxdb.yaml' when run.

Change where this was originally implemented:
wailsapp/wails@af30e5e6ba8d7763ec07fd726bd0e8e918e99929

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone wails source to /home/[user]/wailsapp/wails.
2. Build wails using 'go build/install' from 'cmd/wails'.
3. Copy the resulting wails binary to /usr/local/bin to make it available system wide.
4. Delete /home/[user]/wailsapp.
5. Run /usr/local/bin/wails.

**Expected behaviour**
The resulting binary can be deployed system wide without being tied to the source location where the binary was built. Either linuxdb.yaml is incorporated into the resulting binary or it can be provided along with the binary and loaded as a file relative to the binary.

**Comment by leaanthony** [comment]
Hey there. This was used prior to Go having native `embed`. Happy to accept a PR if you would like to take that on.

**Comment by buddyabaddon** [comment]
If the intention is for this to be an embedded resource and not a runtime accessed 'db' file, yes, I can trivially make these changes.

**Comment by buddyabaddon** [comment]
Here you go. #1046
