### ISSUE TITLE
v2 Mac OpenFileDialog and SaveFileDialog bug

### ISSUE THREAD

**Issue by sealmah** [wailsapp/wails#1047]
Wails Bleeding Edge

OpenFileDialog and SaveFileDialog return filename if file was selected and cancel button clicked

**Comment by leaanthony** [comment]
You mean it's blank?

**Comment by sealmah** [comment]
> You mean it's blank?

Sorry for my english. 
I meant that if you select a file in one of these dialogs, but then click the cancel button, the selected file is returned and an empty value should be returned

**Comment by leaanthony** [comment]
Ah! Thank you for taking the time to clarify. Will fix that 🙏

**Comment by leaanthony** [comment]
Fix on `master` 👍

**Comment by sealmah** [comment]
Thank you for your work!!!
