### ISSUE TITLE
I want to use Wails like a browser, can i set a url in AppConfig?

### ISSUE THREAD

**Issue by Boreals** [wailsapp/wails#1050]
We have a project online ,now we want to make a desktop app for our partner ,so i want to build a wails app from a remote url

**Comment by leaanthony** [comment]
If you just want a limited browser, I'd suggest using [Webview](https://github.com/webview/webview).

**Comment by koddr** [comment]
I understand that this question has already closed, but still, I want to ask @leaanthony: and if there is no way to do without opening webpage inside wails-application, then how could it be done?

I can only think of JS redirect from one page to another:

```js
window.location.replace("https://another-page.com");
```

How counter-productive or even harmful would such a solution be (in your opinion)? 🤔

**Comment by leaanthony** [comment]
My question would be what is your use case? If you just want a lightweight browser for a remote server then webview is your answer

**Comment by koddr** [comment]
> My question would be what is your use case? If you just want a lightweight browser for a remote server then webview is your answer

Yes, without a description of the case, it will be difficult to explain what I would like to build... 😅

I would like to enable users to view corporate websites by clicking to URLs. In this case, on the corporate website itself there will be a button to go to the initial list. 

That is, it is something like a desktop website viewer for corporate users, but without access to the classical browser (in security reasons and so on).

**Comment by gatspy** [comment]
Looking forward to being able to use LoadURL(url)..

**Comment by leaanthony** [comment]
There's currently is no scope for doing this. I would be using [webview](https://github.com/webview/webview) for this.
