### ISSUE TITLE
Try to use  built-in webview2 in Win10

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#1051]
Improve experience on Win10

The electron has great versatility with a huge size
Wails has nice size but webview2 must be installed
Win10 is still the most mainstream Windows OS

A Win10 new user must wait 15-60 seconds to install webview2 before using the Wails program
![w-req](https://user-images.githubusercontent.com/963880/147634807-7bbd1829-4c3b-4542-b7e5-249c19dd581e.png)

Win10 has a built-in webview2 and cannot be uninstalled
![96 0 1054 62](https://user-images.githubusercontent.com/963880/147634819-ad0f3a0b-ae0c-49fd-84c1-199e509a036e.png)

Can Wails try to use that built-in webview2 directly?
If not available then go confirm download or install

**Comment by leaanthony** [comment]
This is against the advice of Microsoft. Most machines will have the webview2 runtime as part of windows update. A user only installs it once (if not already installed), just like .net runtime, vc++ runtime, etc. I'm ok with that.

**Comment by wantg** [comment]
Its a question about perfection

How about this
![image](https://user-images.githubusercontent.com/963880/147658500-b52ef88b-5889-4fc1-bc71-d5ad80159d50.png)

There is no infringement on the current start-up process
