### ISSUE TITLE
[v2, Win10x64] Panic caused by OpenDirectoryDialog when DefaultDirectory is not a valid path

### ISSUE THREAD

**Issue by shaun-wilson** [wailsapp/wails#1052]
**Description**
On Win10, using `runtime.OpenDirectoryDialog` with `runtime.OpenDialogOptions` with `DefaultDirectory` set to a string that doesn't point to a folder causes a panic.

**To Reproduce**
Do the above, and set the `DefaultDirectory` string to something like `foo`.

**Expected behaviour**
At the very minimum, not panic, but return an error instead.

A decision should be made on who (my code, or wails code) should check for path validity, and if done so by wails, how an invalid path is handled (error when invalid, or continue without a default). The decision/process should then be indicated in the docs.

**System Details**

    System
    ------
    OS:             Windows 10 Pro
    Version:        2009 (Build: 19044)
    ID:             21H2
    Go Version:     go1.17
    Platform:       windows
    Architecture:   amd64

    Dependency      Package Name    Status          Version
    ----------      ------------    ------          -------
    WebView2        N/A             Installed       96.0.1054.62
    npm             N/A             Installed       6.14.15
    *upx            N/A             Available

    * - Optional Dependency

    Diagnosis
    ---------
    Your system is ready for Wails development!
    Optional package(s) installation details:
    - upx : Available at https://upx.github.io/

**Additional context**
I haven't tested, but I wouldn't be surprised if a similar issue exists for the other file/folder dialogs when providing default path/filenames.

**Comment by leaanthony** [comment]
Nice catch @shaun-wilson

**Comment by shaun-wilson** [comment]
Yes that works for the folder path.

I wonder if there is a similar problem (unhandled panics) with file paths that either point to non-existent files, or paths with invalid characters?

**Comment by leaanthony** [comment]
Potentially. I'll see if there's a filename checker library

**Comment by pierrejoye** [comment]
I think it is not needed to check the validation of the path,SHGetPathFromIDList will fail if it is not part of the filesystem, symlink or actual path.

**Comment by leaanthony** [comment]
@shaun-wilson - if you can create a sample project that shows a bug, let's open that as a new ticket. Thanks!
