### ISSUE TITLE
v2 typescript bindings.d.ts failed to compile

### ISSUE THREAD

**Issue by ikgo** [wailsapp/wails#1056]
**Description**
 I build react+typescript application. After importing `bindings.d.ts` application failed to build with error
`TS2339: Property 'go' does not exist on type 'Window & typeof globalThis'.` because no export in the script.

I add `export {};` in `internal\binding\generate.go` line 196, after `declare global` block.
The change fix the problem. Now I can install module and use in my app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update react template to typescript
2. Run `wails dev`
3. Failed to compile.

I can create PR if needed.

Best

**Comment by leaanthony** [comment]
Thanks for reporting this. I *did* remove the export line as we exported everything that was generated in the file. Are you using master?

**Comment by jk43** [comment]
@leaanthony I am having the same issue with typescript. 
Wails version v2.0.0-beta.27

**Comment by mcred** [comment]
Looks like this issue also exists with Wails version `v2.0.0-beta.30`. The follow is generated by wails:

bindings.d.ts
```typescript
export interface go {
  "app": {
    "App": {
		Load():Promise<number>
		Save(arg1:number):Promise<void>
    },
  }

}

declare global {
	interface Window {
		go: go;
	}
}

```

index.tsx implementation
```typescript
import go from '../wailsjs/go/bindings'

function loadFile() {
  go.app.App.Load().then((result) => {
  });
  return undefined;
}
```

It has the following error: `TS2339: Property 'app' does not exist on type 'typeof import("/frontend/wailsjs/go/bindings")'.`

**Comment by leaanthony** [comment]
Thanks. On the surface it looks ok. What's the fix?

**Comment by mcred** [comment]
@leaanthony I haven't been able to get it working, yet.

**Comment by Goopil** [comment]
mmm not sur you need to name your import as there is no default export in the bindings file right ? 

Could you try this ?

A: target the interface specifically
```typescript
import {go} from  '../wailsjs/go/bindings'

function loadFile() {
  go.app.App.Load().then((result) => {
  });
  return undefined;
}
```

B: check if you have autocomplete on the window.go object
```typescript
import  '../wailsjs/go/bindings'

function loadFile() {
  window.go.app.App.Load().then((result) => {
  });
  return undefined;
}
```

**Comment by leaanthony** [comment]
Is this still an issue or is it that the docs just aren't up to scratch?
