### ISSUE TITLE
Is there any way to set zoom level?

### ISSUE THREAD

**Issue by e8panse** [wailsapp/wails#1057]
How to achieve the same functionality as web browser, to have native zoom level?
In chromium there is <webview>.setZoomLevel(level) function.

If I just simply use: `document.body.style.zoom = 1.5;` on my frontend side it breaks my internal modules (monaco editor)

Is there any way to do this?

**Comment by leaanthony** [comment]
Hi. Not currently.

**Comment by pierrejoye** [comment]
I will give a PR a try using Get/Put IsZoomControlEnabled 

Idea would be:

- Add an App.run option for it 
- Add API to get/set it
- if there is an API for it, add API to get/set the zoom factor  (could not find so far :)

Thoughts?

**Comment by leaanthony** [comment]
I don't have any thoughts on this. Why not try it out and see how you get on? If you are doing an `App.run` option then you can make it Windows only. If you want to add it to the runtime then it will need to support Linux and MacOS too.

**Comment by pierrejoye** [comment]
> I don't have any thoughts on this. Why not try it out and see how you get on? If you are doing an `App.run` option then you can make it Windows only. If you want to add it to the runtime then it will need to support Linux and MacOS too.

Will do the option today :)

**Comment by leaanthony** [comment]
Merged!

**Comment by janstuemmel** [comment]
why is this only for windows?
