### ISSUE TITLE
[v2]The `download` attribute of the `a` tag of the webpage is invalid!

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1060]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
Downloading files using the `download` attribute of the `a` tag will be invalid.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the command line tool to create a `wails` project.
2. The front-end part records `canvas` animation to generate a video file in `webm` format, and returns the video link.
3. Create the `a` tag with the `download` attribute, and add the above link to the `href` attribute, and then simulate clicking to realize the download.
4. Run project
5. After the recording is complete, the page jumps to a blank page when it is about to download. (As shown in the screenshot below).

You need to wait at least 6 seconds after starting, because you have to wait for the recording to complete.
You can use this code to reproduce the effect: https://github.com/misitebao/demo-code/tree/main/wails-canvas-recorder-and-a-download

**Note: The front-end part can run normally in the local browser. It's just that there will be a jump to a blank page in `wails`.**

**Expected behaviour**
Normally, it should be the same as running in a local browser, recording and downloading files.

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/148287929-8c373254-8b75-4234-97b8-6cf2fae530fd.png)

**System Details**
![image](https://user-images.githubusercontent.com/28185258/148288032-9c573ed1-7bff-4313-9a30-4f172cf39537.png)

**Additional context**
I don’t want to download files in this way, because the downloaded UI style is too different from the native application style, but if you use other methods (such as uploading the recorded video to the Go server, then Go processing and saving it locally) It's too much trouble, so I want to temporarily use this method as a transition, but I didn't expect it to be unavailable.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by taigrr** [comment]
In the master branch, I see a red square moving.
<img width="949" alt="Screen Shot 2022-01-09 at 1 28 22 AM" src="https://user-images.githubusercontent.com/8261498/148676781-018be4ea-0f3a-4afa-9216-ba804f85f8f9.png">

I do not see a way to trigger a recording or download a video. Can you provide better instructions on how to reproduce?

**Comment by taigrr** [comment]
Notably, it's also not possible to use MediaRecorder in Safari, therefore in Wails built for macOS. A blank video file is created.

**Comment by misitebao** [comment]
@taigrr 
Oh never mind, this is just an app built for windows.

**Comment by leaanthony** [comment]
I would be looking on the webview2feedback repo for answers on this.

**Comment by misitebao** [comment]
@leaanthony 
I just tested it again with the previous code and it works successfully.🤣

**Comment by leaanthony** [comment]
Which code?

**Comment by misitebao** [comment]
@leaanthony 
=> https://github.com/misitebao/demo-code/tree/main/wails-canvas-recorder-and-a-download
