### ISSUE TITLE
[v2, CLI] Output shows only the flags that were manually entered

### ISSUE THREAD

**Issue by koddr** [wailsapp/wails#1061]
**Description**

Hi,

I noticed an implicit output of default values when working with `wails build`. 
As stated in your documentation for V2, the default values are like this:

<img width="899" alt="Screenshot 2022-01-07 at 10 02 28" src="https://user-images.githubusercontent.com/11155743/148505048-931e6e6e-5ab6-4e55-8cc1-aa6eaf613871.png">

But the output shows only the flags that were manually entered.

**To Reproduce**

1. Run `wails build -upx`:

```bash
Wails CLI v2.0.0-beta.27

App Type:               desktop
Platform:               darwin
Arch:                   amd64
Compiler:               /usr/local/Cellar/go/1.17.5/libexec/bin/go
Skip Frontend:          false
Compress:               true   # <-- okay, it's right because flag
Package:                true
Clean Build Dir:        false
LDFlags:                ""     # <-- empty value to output or just no defaults applied?
Tags:                   []     # <-- empty value to output or just no defaults applied?
```

2. But if you run it with manual flagging `wails build -upx -ldflags "-w -s" -tags desktop,production`:

```bash
Wails CLI v2.0.0-beta.27

App Type:               desktop
Platform:               darwin
Arch:                   amd64
Compiler:               /usr/local/Cellar/go/1.17.5/libexec/bin/go
Skip Frontend:          false
Compress:               true                   # <-- okay, it's right because flag
Package:                true
Clean Build Dir:        false
LDFlags:                "-w -s"                # <-- so, now you can see it
Tags:                   [desktop,production]   # <-- so, now you can see it
```

**Expected behaviour**

I would like all default values to be output immediately, without manually specifying flags.

**System Details**

Run `wails doctor`:

```bash
Wails CLI v2.0.0-beta.27

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        11.6.2
ID:             199506
Go Version:     go1.17.5
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2384
npm                             N/A             Installed       8.3.0
*upx                            N/A             Installed       upx 3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Additional context**

No.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hey @koddr - this is expected bahaviour (currently). It prints the user flags, not the default ones. To see that, use `-v 2`. I could see some benefit in showing the defaults but then you'd have to explicitly say they are defaults otherwise people will get confused (I didn't pass any ldflags!!!). Thoughts?

**Comment by koddr** [comment]
Thanks for the reply, @leaanthony

You're right, it will indeed be a rare case where someone (_like me_) reads the documentation and is confused when they don't see the default flags. Just because I know how these flags work and what they're for 😉 

In any case, it would be possible to output information on applied flags/options by default. For example, like this:

```bash
Wails CLI v2.0.0-beta.27

App Type:               desktop
Platform:               darwin
Arch:                   amd64
Compiler:               /usr/local/Cellar/go/1.17.5/libexec/bin/go
Skip Frontend:          false
Compress:               true   
Package:                true
Clean Build Dir:        false
LDFlags:                "" (apply defaults, "-w -s")
Tags:                   [] (apply defaults, [desktop,production])
```

**Comment by leaanthony** [comment]
It would mean moving all that logic further up the stack, which I'm not opposed to.
