### ISSUE TITLE
[V2] [Mac] Can't compile

### ISSUE THREAD

**Issue by Newbiedev39** [wailsapp/wails#1064]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
Hi guys! After few months of running Wails V1, I finally decided to tryout V2. I read over the documentation from start to finish but getting a few different errors. I was able to solve most errors by deleting all caches and reinstalling everything fresh, but I'm still left with one error I can't seem to get rid of.

I deleted and reinstalled `xcode command line tools` to make sure it's the latest version, but that doesn't seem to help.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade from Go 1.16 to 1.17.6
2. Upgrade node to v17.3.0 (npm v8.3.0)
3. Run `wails init -n WailsTest`
4. Change `go.mod` module name from "changeme" to "wailstest"
5. Run `wails dev`
6. Get Error

**Expected behaviour**
Program to compile and/or run on dev server

**Screenshots**
![error msg](https://i.imgur.com/GKxVG22.png)

**System Details**
```
Wails CLI v2.0.0-beta.27


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        11.5.2
ID:             199506
Go Version:     go1.17.6
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2384
npm                             N/A             Installed       8.3.0
*upx                            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Looks like you're running MacOS 11 but have the MacOS 12 SDK installed?

**Comment by taigrr** [comment]
[This person](https://stackoverflow.com/questions/70287733/sdl2-doesnt-compile-on-macos-big-sur) had the same issue.

The issue is Apple's, not Wails'.

**Comment by leaanthony** [comment]
Nice find. The fix is [here](https://stackoverflow.com/a/70288548).
