### ISSUE TITLE
how auto updater app

### ISSUE THREAD

**Issue by gatspy** [wailsapp/wails#1065]
client app how auto updater?

**Comment by taigrr** [comment]
Auto updates are not within the scope of Wails.

Please take a look at another library, such as [go-update](https://github.com/inconshreveable/go-update).

**Comment by gatspy** [comment]
@taigrr tks

**Comment by taigrr** [comment]
@leaanthony ok to close

**Comment by leaanthony** [comment]
People have really been asking for this. If we can find a reasonable solution, I'm 100% behind integrating it.
