### ISSUE TITLE
[V2]windows   “wails build”command fails to start client

### ISSUE THREAD

**Issue by jian-guo-s** [wailsapp/wails#1072]
The client can be started normally with the waits run command, but the front-end page of the client using the waits build command cannot be loaded，I don't know what is the reason, can't debug to find the error。

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`

**Comment by jian-guo-s** [comment]
Hello!
wails doctor is:
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.55
npm             N/A             Installed       6.14.12
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
The problem I have is that the client can start normally in the case of wails dev, but after I use wails build to start the client front-end page can't load, I don't know how to debug and find the error after the build windows.

**Comment by jian-guo-s** [comment]
Hello!
wails doctor is:
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.55
npm             N/A             Installed       6.14.12
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
The problem I have is that the client can start normally in the case of wails dev, but after I use wails build to start the client front-end page can't load, I don't know how to debug and find the error after the build windows.

> Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes:
> 
> * Clear, reproducible steps that demonstrates the bug
> * If you are using v1, use `wails issue` to report the issue
> * If you are using v2, please include the output of `wails doctor`

Hello!
wails doctor is:
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.55
npm             N/A             Installed       6.14.12
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

The problem I have is that the client can start normally in the case of wails dev, but after I use wails build to start the client front-end page can't load, I don't know how to debug and find the error after the build windows.

**Comment by leaanthony** [comment]
Clear, reproducible steps that demonstrates the bug
