### ISSUE TITLE
[V2] `wails dev` and `wails build` frontends behave differently

### ISSUE THREAD

**Issue by mohaijiang** [wailsapp/wails#1073]
**Description**
Is there any way to view the front-end console log of the compiled exe execution file? Because I found that wails dev and wails build behave differently. It might be an issue with the frontend referenced js loading, but I'm not sure. My code repository is `https://github.com/mohaijiang/hello-wails.git`. The front-end file is the compiled content of the vue project and has been tested by nginx.

**To Reproduce**
Steps to reproduce the behaviour:
1. `git clone https://github.com/mohaijiang/hello-wails.git`
2. `cd hello-wails`
3. ` wails dev` and see login page
4.  `wails build ` and double click `hello-wails.exe`, then see loading page, not login page 

**Expected behaviour**
`wails build` exe executable should behave the same as `wails dev`。 This case should display the login page.

**Screenshots**
![image](https://user-images.githubusercontent.com/3366709/149487834-96ca4ce7-0401-49c9-a1a6-cd6a9be1056c.png)
This is `wails dev` display.

![image](https://user-images.githubusercontent.com/3366709/149488110-39a6112f-525b-4347-8d25-389daacab079.png)
This is `wails build` display.

**System Details**
V2 users: Please add the output of `wails doctor`.
```
PS C:\Users\gr\IdeaProjects\hello-wails> wails doctor
Wails CLI v2.0.0-beta.28


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.55
npm             N/A             Installed       8.3.0
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Additional context**

- [] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Need Help**
Can I debug the build file and check the frontend http request or console log ?

**Comment by leaanthony** [comment]
You can debug more with `wails build -debug` then right click -> inspect

**Comment by mohaijiang** [comment]
@leaanthony  thanks for reply,  I tried both windows 10 and macos , bug cannot  `right click` on the debug build app.

**Comment by mohaijiang** [comment]
Strangely, under the debug mode build, you still can't right-click to open the menu.
I successfully opened the right-click menu by modifying v2/internal/frontend/desktop/windows/frontend.go L#296~L#303.
The console shows that my `_app.config.js` file could not be loaded, 404 NOT FOUND. But this file is in my `frontend` directory. Is there any reason why this file cannot be loaded after building? 

![tempsnip](https://user-images.githubusercontent.com/3366709/149715276-7e70b38e-293a-4935-b501-7e5ef7e529c1.png)
`_app.config.js` NOT FOUND.

![image](https://user-images.githubusercontent.com/3366709/149716076-c5bf6596-f430-4028-bff1-502a3018b087.png)
`_app.config.js` in project

**Comment by mohaijiang** [comment]
go:embed cannot load file as start with `_` or ` `

change with 
```golang
//go:embed frontend/*
var assets embed.FS
```

and _app.config.js loaded successfully .

**Comment by stffabi** [comment]
Unfortunately that's a restriction of the `embed.FS`. Starting with `Go 1.18` you could embed the following way

```go
```

**Comment by leaanthony** [comment]
> go:embed cannot load file as start with `_` or ` ` as default
> 
> change with
> 
> ```go
> //go:embed frontend/*
> var assets embed.FS
> ```
> 
> and _app.config.js loaded successfully .

I'm glad you got it fixed 👍 `-debug` should absolutely give you a console though.

**Comment by leaanthony** [comment]
If you're interested, I've added `-debug` support for `wails build` on master.
