### ISSUE TITLE
wails v2 with react template

### ISSUE THREAD

**Issue by amlwwalker** [wailsapp/wails#1075]
**Is your feature request related to a problem? Please describe.**
V1 had a react template, any chance that can be ported to v2?

**Describe the solution you'd like**
A v2 react template

**Describe alternatives you've considered**
Perhaps the vanilla template can easily be repurposed?

**Additional context**
N/A

**Comment by leaanthony** [comment]
V2 will only officially support the current templates. There is the option for installing remote templates and there's react templates available: https://wails.io/docs/community/templates

**Comment by elibroftw** [comment]
I looked at the vanilla template. Is there no way to specify a custom port? Why 34115? React uses 3000 by default, so why not just use that. The more agnostic wails is the easier everyone's life will be. For example, Tauri lets you specify a port to use for dev. Then developers don't need to edit their package.json just for wails.

**Comment by elibroftw** [comment]
It's interesting that Wails takes the approach of creating a frontend for a backend whereas Tauri takes the approach backend for frontend but neither provide practical docs for the other way around!

**Comment by elibroftw** [comment]
Add the following to package.json:
`"wails": "cross-env PORT=34115 BROWSER=none react-scripts start",`

**Comment by leaanthony** [comment]
> I looked at the vanilla template. Is there no way to specify a custom port? Why 34115? React uses 3000 by default, so why not just use that. The more agnostic wails is the easier everyone's life will be. For example, Tauri lets you specify a port to use for dev. Then developers don't need to edit their package.json just for wails.

That port is used for the internal dev server, not an external one. The project doesn't officially support an external devserver but it would be good if it did.

> It's interesting that Wails takes the approach of creating a frontend for a backend whereas Tauri takes the approach backend for frontend but neither provide practical docs for the other way around!

What would that look like?
