### ISSUE TITLE
[v2] Select Dropdown doesn't update position when moving window

### ISSUE THREAD

**Issue by MikeSchaap** [wailsapp/wails#1081]
**Description**
When you open a select (dropdown) and move the window, the dropdown stays open at a fixed location. Also after moving the window with the dropdown closed, the dropdown first opens at the old location.

Note: For the workaround i had to make changes to this repo (v2) and also to the following repo:
github.com/leaanthony/go-webview2

**To Reproduce**
Create a new Wails app and insert a html select element. 
Also see this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/780
And also this issue for a video of the problem: https://github.com/tauri-apps/tauri/issues/3089

**Expected behaviour**
Dropdown should close when it's open and you move the window (like it does in Chrome)
Dropdown should open at the correct position after moving the window

**Screenshots**
See video at: https://github.com/tauri-apps/tauri/issues/3089
Broken:
![broken](https://user-images.githubusercontent.com/35368821/149638859-cca3404c-a84b-40ef-adcb-409be64e8895.gif)

Working
![working](https://user-images.githubusercontent.com/35368821/149638921-8136d874-5d95-4f29-a91f-f8b4ce381467.gif)

**System Details**
System
------
OS:             Windows 10 Pro N
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.55
npm             N/A             Installed       8.1.2
*upx            N/A             Available

* - Optional Dependency

**Additional context**
In the WndProc i called the w32.SetFocus(w.Handle()) function on the w32.WM_Moving message. This changes the focus on the webview and closes the dropdown when moving the window.

In the WndProc i called the NotifyParentWindowPositionChanged, this makes it so the webview will know it's position has changed and the dropdown opens in the correct place afterwards.
See this https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller?view=webview2-1.0.774.44#notifyparentwindowpositionchanged

Do you want me to also open a PullRequest on the github.com/leaanthony/go-webview2 repo? I will warn you that the work around is fairly badly coded and was just to make sure i could actually fix the issue.

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hey Mike, nice find! I think let's treat this as 2 separate things: Adding a method in `go-webview2` to expose the `NotifyParentWindowPositionChanged` method, then update Wails to call this in move. How does that sound? And yes, PRs always welcome - especially with my current limited time. Thanks!
