### ISSUE TITLE
[V2] Frameless Window Resize Cursor Not At The Right Position

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1087]
**Description**
As mention in issue #1084 . The resize cursor starting to show near the edge of the window which is not right. It also interfere with any buttons or elements beyond that point.

**Screenshots**
The red line is where the resize cursor shows. Expecting it will show by the edge of the window. Also anything beyond the red line will get interfered.
![149993023-3053f149-7453-4051-9eba-6531b61f1266](https://user-images.githubusercontent.com/28552977/150160854-f42f340b-f3e5-452f-a4bc-734bc29db4cc.png)

**Additional context**
I believe @leaanthony will look into this problem as I open this issue to keep track on it.

**Comment by leaanthony** [comment]
Yeah, this is also relatively easy based on the suggestion by @stffabi

**Comment by leaanthony** [comment]
@KiddoV - I've reduced the border detection width to 6px. Give that a go. @stffabi - I tried EnableFramelessBorder but it didn't work for my test project. Perhaps I broke it?

**Comment by stffabi** [comment]
@leaanthony regarding the `EnableFramelessBorder` did no border show up for you? EnableFramelessBorder has no effect on the resizing, even if that flag is active resizing still has be initiated from the frontend.

**Comment by leaanthony** [comment]
Yeah no border, unless it was dark and I'm using dark mode 😂

**Comment by stffabi** [comment]
Never tried it with dark mode 😄. The effect depends on the windows version and is sometimes very subtile, like a light shadow and a light border. For Windows 11 e.g. the edges will be round.

**Comment by stffabi** [comment]
@KiddoV thank you very much for testing the latest changes.

Regarding the Min/Max constraints there's a bug which allows resizing to less than `MinWidth`/`MinHeight` if `MaxWidth`/`MaxHeight` has not been set. This will be fixed with the fixes for #1094 in leaanthony/winc#14.

**Comment by KiddoV** [comment]
Also I still have a bug using the PR #1085 last time.
When use ``DisableResize: true``, and maximize window by the ``WindowMaximise()`` this will happen:
![Capture](https://user-images.githubusercontent.com/28552977/151988625-36f8cb15-a103-496e-a149-b7a4a0cfc369.PNG)
It will have the white bar covers the Windows taskbar.

**Comment by KiddoV** [comment]
> Regarding the Min/Max constraints there's a bug which allows resizing to less than `MinWidth`/`MinHeight` if `MaxWidth`/`MaxHeight` has not been set. This will be fixed with the fixes for #1094 in [leaanthony/winc#14](https://github.com/leaanthony/winc/pull/14).

Thank you, good to know!

**Comment by stffabi** [comment]
> Also I still have a bug using the PR #1085 last time. When use `DisableResize: true`, and maximize window by the `WindowMaximise()` this will happen: ![Capture](https://user-images.githubusercontent.com/28552977/151988625-36f8cb15-a103-496e-a149-b7a4a0cfc369.PNG) It will have the white bar covers the Windows taskbar.

Could you please give PR leaanthony/winc#14 a try by replacing winc version in your go.mod with `github.com/stffabi/winc v0.0.0-20220127083852-9801ff2555c0` ?

I suspect this might be the same cause like in #1094, if not it would be great if you could open a new issue and include a minimal `main.go` file with all your settings so we could reproduce it? That would be awesome.

**Comment by KiddoV** [comment]
> Could you please give PR [leaanthony/winc#14](https://github.com/leaanthony/winc/pull/14) a try by replacing winc version in your go.mod with `github.com/stffabi/winc v0.0.0-20220127083852-9801ff2555c0` ?

I tested this PR and the resizing seem to be working on my Windows 10 and 7. I cannot resize less than the ``MinWidth`` set or more than the ``MaxWidth`` set anymore (same with Height). But it does not resolve my issue with the "white taskbar" at the end.

**Comment by KiddoV** [comment]
I will create a new issue and close this, since this resolve my issue with the ``cursor``!!

**Comment by KiddoV** [comment]
There is another really really... small bug about the cursor I forgot to mention back then.
When the window in full screen mode (maximize), the mouse cursor should NOT change to ``resize arrow`` when hover the edges of the window.

**Comment by stffabi** [comment]
@KiddoV thanks for reporting this. Would it be possible for you to open a new issue for this? That would be awesome.

**Comment by leaanthony** [comment]
@KiddoV is this ticket still relevant?
