### ISSUE TITLE
[V2][Windows] Make a Toggle WindowMax/Min Method

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1088]
**Describe the solution you'd like**
Correct me if I am wrong. 
As for now we have the ``WindowMaximise()`` and the ``WindowUnmaximise()`` method in the ``runtime`` package. We can use it to maximize and unmaximize the window.
Is there anyway that we can combine them into 1 method (or it is good to just add a new method)? I meant to make a toggle max/min instead. Something like ``WindowToggleMaximise()`` . So that every time the window max out, we can click the button again to make the window go back to default size. (Trying to get the behavior like the default windows title bar maximize button does).
Or maybe there is a work-around for this that I don't know?

**Additional context**
As I mention in issue #1084.

**Comment by leaanthony** [comment]
This isn't too hard but we need to do it on all platforms.

**Comment by leaanthony** [comment]
Workaround: you know whether your app starts minimised or maximised so keep a flag with that in, eg `bool maximised = false`. When you click your toggle button, send a message to the backend and toggle the flag. Call Max/Min function as appropriate.

**Comment by KiddoV** [comment]
@leaanthony That I can do, but I fear sometime users have a different way to maximize the window instead of using the html button (Drag title bar to the top, double click on the title bar...), and the flag will not be toggle by those event, correct me if I'm wrong. I think it is a good idea to make a toggle method in ``runtime``.

Speaking of the ``title bar``. Normal window behavior for Windows title bar should maximize when user double click it. Is it not implemented yet in the ``data-wails-drag`` ?

**Comment by leaanthony** [comment]
@KiddoV if you have frameless then there's no title bar and those scenarios don't exist.

**Comment by KiddoV** [comment]
>@KiddoV if you have frameless then there's no title bar and those scenarios don't exist.

@leaanthony I believed nowadays when a dev use ``frameless window`` it is to build a custom title bar to make it more consistent looking through out all platforms. That being said, title bar still exist in frameless window, but it is a custom title bar now.

>We could add an event when clicked then it would be up to your code to pick those up, determine a double click, and do whatever then.

That would be a nice implementation!

**Comment by leaanthony** [comment]
I think my point was that you can control whether it does those things. You don't have to worry about users performing a maximise via the window manager.

Thinking more about your needs, I'd suggest simply adding a click listener on your title bar element. Doesn't make sense to conflate drag and click 😀

**Comment by KiddoV** [comment]
Just a quick update on this. Are you still planning to add the toggle function?

**Comment by leaanthony** [comment]
Yeah but it's behind a bunch of other work needed. I'll see this week

**Comment by leaanthony** [comment]
@KiddoV - Try this PR 👍

**Comment by leaanthony** [comment]
Maybe needs rebasing on master

**Comment by KiddoV** [comment]
@leaanthony Sorry I didn't get the idea.

**Comment by leaanthony** [comment]
Try pulling the latest master. It's working great here

**Comment by KiddoV** [comment]
@leaanthony 
```txt
> wails dev
Wails CLI v2.0.0-beta.30


Executing: go mod tidy
Executing: wails generate module
Building application for development...
No Install command. Skipping.
No Build command. Skipping.
Generating bundle assets: Done.
Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/desktop/windows
..\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.30\internal\frontend\desktop\windows\window.go:190:26: undefined: winc.ScaleWithDPI
..\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.30\internal\frontend\desktop\windows\window.go:195:27: undefined: winc.ScaleWithDPI

Build error - continuing to run current version
exit status 2
Watching (sub)/directory: C:\MultiTech-Projects\GO Source Code Files\Web-Applications\Wails\XDot-Controller-V2
Using Dev Server URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
```
``go mod tidy`` is executed when ``wails dev``

**Comment by leaanthony** [comment]
Go.mod?

**Comment by KiddoV** [comment]
@leaanthony 
```go
module app

go 1.16

require (
	github.com/wailsapp/wails/v2 v2.0.0-beta.30
	go.bug.st/serial v1.3.4
)

require github.com/spf13/viper v1.10.1

// replace github.com/wailsapp/wails/v2 v2.0.0-beta.27 => C:\Users\vho\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.27
```
Weird. My ``go.mod`` got smaller.
