### ISSUE TITLE
`wails build` fails when using dep

### ISSUE THREAD

**Issue by ocelotsloth** [wailsapp/wails#109]
**Description**

I am looking at whether to use this project or not and ran across this issue while trying to setup a new project with [dep](https://golang.github.io/dep/) dependency tracking.

I'll likely be spending a bit of time looking for why this is happening but just in case the solution is easily identifiable to you I figured opening an issue was a good step to take.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new wails project with `wails init`
2. Initialize dep for dependency vendoring with `dep init`
3. Attempt to rebuild the wails application with `wails build`

**Expected behaviour**
I would expect for the build behavior to remain unchanged when using Godep.

**Screenshots**

Click on the below frame for an Asciinema recorded demonstration of my issue.

[![asciicast](https://asciinema.org/a/248510.svg)](https://asciinema.org/a/248510)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.15.0 |
| Go Version    | go1.12.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by ocelotsloth** [comment]
@leaanthony Where are the `wailsruntimeassets` files loaded at? I can see the `wails-mewn.go` file that includes the file that appears to be missing but cannot find where those files are actually written to disk.

I've been working with a local copy and found the exact command that is returning a failure:
```
~/g/s/git.stengle.in/ocelotsloth/test
❯ wails build     
Wails v0.15.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
⣯ Packing + Compiling project...2019/05/26 21:28:19 open /home/ocelotsloth/go/src/git.stengle.in/ocelotsloth/test/wailsruntimeassets/default/wails.min.js: no such file or directory

✗ Error: exit status 1, Command: `mewn build -o test -ldflags -w -s -X github.com/wailsapp/wails.BuildMode=prod`
Error: exit status 1
```

Can you help me understand what is going on with that call to `mewn build`? I think that it's just passing those arguments to `go build` after packing the static assets (I've worked with packr before so believe I am fairly comfortable with what your mewn library is doing). What is `go build` doing with those ldflags? Specifically the `-X github.com/wailsapp/wails.BuildMode=prod`?

**Comment by leaanthony** [comment]
Hi @ocelotsloth. Thanks for your interest in Wails and your contributions so far! Godep isn't officially supported and it's my understanding that it's now been [deprecated](https://github.com/tools/godep)?  Regarding the building, you are right in what mewn is doing. The build command updates the target project with some runtime assets that are compiled in depending on the build mode (debug, prod, build) - This is what the `-X github.com/wailsapp/wails.BuildMode=prod` is doing. It finds the runtime assets relative to the location of the source of the wails tool itself, so if you build the cli tool outside of the main source tree, it will fail to find the necessary assets. I'll be honest, I'm not sure we'll be supporting anything beyond the standard Go modules as it seems to do the job well enough and there are some higher priorities right now. Happy to accept a PR if you figure it out though! Let me know if I can help you further.

**Comment by ocelotsloth** [comment]
Oh wow my mistake. I definitely meant dep.

**Comment by leaanthony** [comment]
No worries! I don't know dep either so I guess the reply still stands. Out of interest, why do you wish to use dep over what has now been settled on as the standard go module tooling?

**Comment by ocelotsloth** [comment]
The issue with not supporting dep is that it prevents good dependency vendoring in case a project makes breaking changes or deletes their repository.

Dep writes vendored packages to the `vendor` directory in the project. This is actually the direction that Go is taking moving forward with `vgo`, the up and coming replacement for `dep`. This is going to be an issue in the future as they're actually planning on [deprecating $GOPATH alltogether by Go 1.13 (August 2019)](https://blog.golang.org/modules2019#TOC_2.).

**Comment by leaanthony** [comment]
So I've not tested using vendoring as I thought that the move was more towards versioned modules, using go.sum to ensure integrity. So if the concern is things changing under your feet, then there are 2 ways to achieve this (which are not mutually exclusive): 

1. Add the runtime dependency versions to go.mod
2. Support vendoring

The first is a simple update and will solve the main issue you have. The second is a little trickier. I can confirm `go mod vendor` exhibits the same behaviour so there's a possible argument for solving it, but I need to ensure that the Go team aren't dropping vendor support altogether. In the link you provided, it sounds like vendoring is falling out of favour:

`While vendoring will continue to be supported, we’d prefer a solution that works for all modules—not just the ones you’re already using—and that does not require duplicating a dependency into every repository that uses it.`

**Comment by leaanthony** [comment]
What's odd is that this is a compile time error for runtime assets....
So running `go build` after the failure does build the binary, however it's 3M larger which is interesting.

**Comment by leaanthony** [comment]
Although I have found a bug in the packer that only raises its head when using vendor, the real cause for your issues relates to the way the `vendor` works. I did a `go mod vendor` which (I assume) works the same way as `dep` and sure enough, all the non-package directories are missing. There is a thread [here](https://github.com/golang/go/issues/26366) about it. 
Could you please check if the "wailsruntimeassets" directory exists in your vendored copy of Wails? If it's not there then that's a showstopper on the vendoring code. If it is, I'll look at fixing the bug

**Comment by ocelotsloth** [comment]
Ah! That directory was definitely being pruned by `dep`.

It appears I'm a bit behind on the latest tooling and need to do some research into `go mod`. [This comment](https://github.com/golang/go/issues/26366#issuecomment-448557333) pretty much sums it up.

At least for dep it is possible to disable vendor pruning for a given package. For anybody getting here through Google looking for an answer this is how:

```
# Gopkg.toml
[[constraint]]
  name = "github.com/wailsapp/wails"
  version = "0.15.0"

[prune]

  [[prune.project]]
  name = "github.com/wailsapp/wails"
  unused-packages = false
```
> Could you please check if the "wailsruntimeassets" directory exists in your vendored copy of Wails?

After disabling pruning I can confirm that the `wailsruntimeassets` does exist and that the `wails build` command still fails.

```
~/g/s/git.stengle.in/ocelotsloth/test2
❯ ls vendor/github.com/wailsapp/wails/wailsruntimeassets 
bridge  default  wails.js

~/g/s/git.stengle.in/ocelotsloth/test2
❯ wails build
Wails v0.15.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
⣟ Packing + Compiling project...2019/05/27 22:23:41 open /home/ocelotsloth/go/src/git.stengle.in/ocelotsloth/test2/wailsruntimeassets/default/wails.min.js: no such file or directory

✗ Error: exit status 1, Command: `mewn build -o test2 -ldflags -w -s -X github.com/wailsapp/wails.BuildMode=prod`
Error: exit status 1
```

It looks as though it is looking under the project directory instead of under `$(PROJ_DIR)/vendor/github.com/wailsapp/wails/wailsruntimeassets/`.

**Comment by ocelotsloth** [comment]
I think that [this comment](https://github.com/golang/go/issues/26366#issuecomment-459291202) (below) has a good solution to the issue actually.

> > Russ' response about C files applies to template txt files too
>
> Sorry, I replied too hastily there. Russ' comment about C files does not apply to other non-Go or C files. The second part of my response (using go-bindata or similar) should however be correct and considered the right way to fix this.

Could you use go-generate along with either mewn (I'm not sure if it would require some work on your library) or go-bindata to include those static files in the package itself? It seems that would avoid the entire issue around requiring those static files at build-time.

**Comment by leaanthony** [comment]
Thanks for checking and confirming the situation. The path bug is indeed one I need to fix and hopefully will in the next 30 mins. 
Regarding packing the assets, if you check the history of `templates.go` you'll see it went from reading off disk, to packed, to reading off disk :-) I actually don't mind packing them again, but keeping all that in sync was a bit of a pain. Hopefully go-generate might fix that? So yes, I'm totally open to that solution if you fancy working on it 👍

**Comment by leaanthony** [comment]
I've pushed updates to mewn on the path-fix branch. It *should* fix the issue you saw. Let me know how you go 👍

**Comment by leaanthony** [comment]
Hi @ocelotsloth. Just wondering how you were getting on and wondering if I could help in any way?

**Comment by leaanthony** [comment]
Moving this to v0.17.0

**Comment by ocelotsloth** [comment]
Ah thanks for the reminder. I haven't forgotten about this I promise. It's been pretty crazy at work the last couple weeks so I've been spending a little more time not sitting at a computer at home.

**Comment by leaanthony** [comment]
That's a good thing! Will keep the ticket open.

**Comment by leaanthony** [comment]
Removing milestone as this is currently on hold

**Comment by leaanthony** [comment]
Hi @ocelotsloth - I'm going to close this as the whole ecosystem is moving to Go modules. Sorry 😞 Please let me know if I can help with moving to Go modules 👍
