### ISSUE TITLE
[v2] wailsjs/go/bindings.d.ts not properly linting using TypeScript

### ISSUE THREAD

**Issue by albert-sun** [wailsapp/wails#1091]
**Description**
TypeScript interfaces from `wailsjs/go/bindings.d.ts` output aren't properly linted within Visual Studio Code running the TypeScript language server. Accessing of bound function handlers still works properly after compilation but isn't linted (shows error `Property 'go' does not exist on type 'Window & typeof globalThis'. ts(2339)`). Runtime properties aren't affected since the `runtime` interface within `wailsjs/go/runtime.d.ts` is properly exported.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialize a TypeScript project and open within VS Code with the TypeScript language server running
2. Modify the Go source files to include a bound struct which should generate binding types
3. Run `wails dev` to generate the `.d.ts` files within the given `wailsjs` directory
4. Attempt to add `window.go.[...]` within a TypeScript (or in my case, Svelte) file.
5. See linting error: `Property 'go' does not exist on type 'Window & typeof globalThis'. ts(2339)`

**Expected behaviour**
`window.go.[...]` should lint properly, and when hovered should show `(property) Window.go: go`

**System Details**
```
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.62
npm             N/A             Installed       8.1.0
*upx            N/A             Available

* - Optional Dependency
```

**Additional context**
This can be fixed by exporting the `go` interface within `wailsjs/go/bindings.d.ts`.

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Are you able to provide a PR for this? I get mixed reports for this.

**Comment by IrishBruse** [comment]
same thing is happening to me adding an `export {};` fixes the error
![image](https://user-images.githubusercontent.com/14964651/150685615-92fafb09-294b-47db-a963-ae680f1b7644.png)
