### ISSUE TITLE
[V2, vue]  The part covered by data wails drag cannot perform route jump

### ISSUE THREAD

**Issue by YLQZ** [wailsapp/wails#1096]
The part covered by data wails drag cannot perform route jump。
It needs to be explained in the document of data waves drag or in the document of router

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`

**Comment by YLQZ** [comment]
template used https://github.com/codydbentley/wails-vite-vue-the-works
add  data-wails-drag at body
like this   <body data-wails-drag>   
vueRouter can not jump

**Comment by leaanthony** [comment]
Please open a bug on the template page. Thanks.
