### ISSUE TITLE
[v2, windows] DPI Scaling is incorrect for scaling factors other than 100%, 200%, ...

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#1097]
**Description**
DPI Scaling is not applied correctly if the scaling factor is not equal to `n * 100%` where `n` is an integer.

**To Reproduce**
Create a new v2 template. Compile the app for Windows and start it on a windows machine with a scaling of 125%, 150% or 175%. The window is too small and doesn't correctly size itself.

**Expected behaviour**
The scaling should be correct

**Additional context**
The problem is how the scaling of `scaleWithWindowDPI` is implemented in winc here:
https://github.com/leaanthony/winc/blob/fdd739b32c58704d1ff6ff6b44a7e9248b4712fb/controlbase.go#L488-L492

For a scaling factor of 175% the `DPIScaleX` is 1.75 but converting it to an int results in only scaling with 1. Ive provided a PR leaanthony/winc#13 which will fix this issue.

**System Details**
Wails Version: v2.0.0-beta.29
MacOS Version: 12.1.0
Go Version: go1.17.6
Windows Version: Windows 11 21H2

**Comment by leaanthony** [comment]
Merged!
