### ISSUE TITLE
[V2] Execute JavaScript in the frontend from go

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1106]
1. Is there any way that I can call the JavaScript functions in Go?
2. How do I pass my JQuery objects to the backend, to use its functions?
3. Is there a way to make all Go functions private instead of global? I fear that user can get to the browser console and call any Go functions.

**Comment by leaanthony** [comment]
1. Events is the only way
2. Events
3. How would this work?

**Comment by KiddoV** [comment]
@leaanthony Thanks for the reply. 
Can you be more specific on the ``Events``? Is there a Go package for the ``Events`` that I don't know?
Number 3 is just a curiosity. I don't think there is a way to do that. :)

**Comment by leaanthony** [comment]
https://wails.io/docs/reference/runtime/events

Emit an event from Go with any data you want to pass, in JS have a listener for the event and call whatever method from there with the passed data

**Comment by KiddoV** [comment]
@leaanthony Can you provide some example code? This is a little bit confusing for newbie.
For example I have this in JS:
```js
$("#some-id").echo("Hello there!")
```
If I want to call that JQuery function in GO side, how do I do that?

**Comment by leaanthony** [comment]
You can't pass JS instance methods to Go. You can do something like this though:

Backend:
```go 
func echo(text string) {
    runtime.EventsEmit("terminal-echo", text)
}
```
Frontend:
```js
runtime.EventsOn("terminal-echo", instance.echo);
```

**Comment by KiddoV** [comment]
So I have to make one listener for every JS instance method?

**Comment by misitebao** [comment]
> So I have to make one listener for every JS instance method?

You don't need to set a listener for each JS method, just set one and distribute it according to the passed parameters.

**Comment by leaanthony** [comment]
Yeah that's another way

**Comment by KiddoV** [comment]
@misitebao thanks! Could you throw some sample code or a link? The docs doesn't have much to read.

**Comment by pierrejoye** [comment]
Looking for a way to actually call JS functions from go, I was wondering the design decision to do not expose ExecJS?

The core idea O try to achieve here is to keep the FE, as much as possible, the same no matter where it runs (pure web or as desktop app). Having the ability to call the FE app API from go allows a clean, loosely bounded way to interact (f.e. logout user, etc).

It is clear that all of that could be achieved using events however it couples both sides a tat bit too much then. Thoughts?

**Comment by pierrejoye** [comment]
I do not know (yet) about other platform, however on windows WebView2,

**Comment by stffabi** [comment]
Yeah I would also say that's a good extension to wails.
I just briefly taken a look into the apis and it should be possible to get the returning value on all platforms. Maybe we need some trampoline functions to properly returning errors for exceptions.

Maybe we should also take a look into supporting async js methods that can execute a callback to finish the call on the go side?

**Comment by leaanthony** [comment]
Sounds good to me! This has to be the last last feature for v2 right 😉😉😉

**Comment by sidwebworks** [comment]
@leaanthony Does this means it would be possible to run arbitrary JS code in a sandboxed environment?

**Comment by leaanthony** [comment]
Hopefully!

**Comment by stffabi** [comment]
WindowExecJS has been exposed with #1927 and merged.

Currently it is fire and forget, without the possibility to get return values.

**Comment by KiddoV** [comment]
Does ``WindowExecJS`` only execute JS in ``global`` or ``window`` scope?.
I can call ``console.log`` but not my global functions.

**Comment by AlexJujushvili** [comment]
Hello. I am confused. Can you give me one complete example?
![Capture](https://user-images.githubusercontent.com/13392216/218344563-e3d59a1d-ba0a-4bb5-b74f-3b05d4de25ae.PNG)

**Comment by AlexJujushvili** [comment]
> Hello. I am confused. Can you give me one complete example, call to javascript?

**Comment by AlexJujushvili** [comment]
> Does `WindowExecJS` only execute JS in `global` or `window` scope?. It seems like I can only call `console.log` and `alert()`, but not my global functions.
> 
> ```js
> export function myFunc() {
>     console.log("Func called!")
> }
> ```
> 
> Edit: NVM, I should define the function like this to work:
> 
> ```js
> (<any>window).testFunc = (msg: string) => {
>     console.log(msg);
> }
> //or...
> (window as any).testFunc = (msg: string) => {
>     console.log(msg);
> }
> ```

Hello. I am confused. Can you give me one complete example, call to javascript?

**Comment by AlexJujushvili** [comment]
![Capture](https://user-images.githubusercontent.com/13392216/218344756-9ccd6fc5-dfce-4e7d-a042-28fae4dd2e3e.PNG)
Hello. I am confused. Can you give me one complete example, call to javascript?

**Comment by KiddoV** [comment]
Your code shown above is the other way around. The WindowExecJS is for calling JavaScript function or execute JS code directly from Golang without creating any wrapper functions.

**Comment by AlexJujushvili** [comment]
> 

![Capture](https://user-images.githubusercontent.com/13392216/218529176-3cf68bde-e6a3-4dbe-b69a-0869fa75dff1.PNG)
Thank you very much !!! :)

**Comment by RandyWei** [comment]
How to get the result from WindowExecJS which the function return some content。In other words，how to get some content when click hot keys 。 For example, save the content which from frontend to local file

**Comment by RandyWei** [comment]
How to get the result from WindowExecJS which the function return some content。In other words，how to get some content when click hot keys 。 For example, save the content which from frontend to local file

**Comment by KiddoV** [comment]
> Currently it is fire and forget, without the possibility to get return values.

Currently does not support return value from frontend.

**Comment by RandyWei** [comment]
> 

Thks

**Comment by leaanthony** [comment]
> > Currently it is fire and forget, without the possibility to get return values.
> 
> Currently does not support return value from frontend. 

And never can. Limitation of executing JS. The best thing you can do is do an `event.On` with a random number, pass in that number to the call and get the call to emit an event back with the result
