### ISSUE TITLE
Get the wrong content-type: text/tab-separated-values

### ISSUE THREAD

**Issue by Rygopher** [wailsapp/wails#1108]
In my windows 10, I build the frontend by vue3+vite, when 'wails dev' is running, getting some errors:

![1](https://user-images.githubusercontent.com/31070831/151211720-801c6ec7-eb76-4a90-98e5-d76cf70232db.png)

![2](https://user-images.githubusercontent.com/31070831/151212012-05e8f25d-9d5c-4a1b-8d0f-43ea825b21a4.png)

However,it works good in chrome browser or microsoft edge browser.

**Comment by leaanthony** [comment]
Thanks for reporting this. Mime detection is so hit and miss. I'll fix today
