### ISSUE TITLE
KDE (Plasma) installation?

### ISSUE THREAD

**Issue by ankush981** [wailsapp/wails#111]
Hello, I'm using Kubuntu 19.04, which comes with KDE Plasma 5, and was wondering how Wails can be installed there. I absolutely refuse to install GTK libraries! :smile: So, is there an installation path I can explore or should I just give up?

**Comment by leaanthony** [comment]
Well, the only thing the Gtk library does is render an html window. If you feel that it is still a step too far, feel free to send a patch to https://github.com/zserge/webview - the windowing library we use. Or, suggest an alternative, cross platform HTML webview library. It's fairly plug'n'play from that perspective. Good luck!

**Comment by ankush981** [comment]
@leaanthony Damn, I'm not up to the task. Very, very new to GUI systems. I'll close this for now. :sweat_smile:

**Comment by leaanthony** [comment]
Let us know if we can help in any other way!
