### ISSUE TITLE
[V2, vue] data-wails-drag  cannot cover link area

### ISSUE THREAD

**Issue by YLQZ** [wailsapp/wails#1112]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**

If the data-wails-drag covers the Vue routerlink area, the route jump cannot be performed

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init -n "Your Project Name" -t https://github.com/codydbentley/wails-vite-vue-the-works
2.  add data-wails-drag at body like `  <body data-wails-drag>` or at  id="app"  like `<div id="app" data-wails-drag></div>`
3. wails dev
4. click the link  , the create window page  not change

**Expected behaviour**

**Screenshots**

the route jump cannot be performed

**System Details**
V2 users: Please add the output of `wails doctor`.

Wails CLI v2.0.0-beta.27
Scanning system - Please wait (this may take a long time)...Done.
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.17.3
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.69
npm             N/A             Installed       8.3.0
*upx            N/A             Installed       upx 3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!

**Additional context**
Prompt for writing documents
- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Please open this ticket on the template project https://github.com/codydbentley/wails-vite-vue-the-works
