### ISSUE TITLE
[V2][Feature Request] Manually import runtime, access the go API through websocket in External Dev Server

### ISSUE THREAD

**Issue by jummyliu** [wailsapp/wails#1116]
**Is your feature request related to a problem? Please describe.**
1. Where to see the changelog, future development plans.
2. The local websocket server is not enabled when using an External Dev Server.
3. Manually import ipc_websocket.js, runtimedev.js, bindings.js in External Dev Server.
4. Tray, Single Instance Lock, Web Devtools are not supported.

**Describe the solution you'd like**

2. External Dev Server can connect to the wails application through `ws://localhost:34115/wails/ipc`.
    In this way, I can access the go API through websocker under the development server without build( npm run dev ).

3. External Dev Server can import ipc_websocket.js, runtimedev.js, bindings.js without autoinject.
    In this way, I can access the go API through websocker under the development server without build( npm run dev ).

**Describe alternatives you've considered**

2. Add flags to startup the Built in websocket Dev Server，when using other External Dev Server.

3. Auto generate ipc_websocket.js then i can import it by myself.

**Additional context**

2. screenshots
`vite.config.js`  `wails.json`
![image](https://user-images.githubusercontent.com/13114931/151652817-a8117f54-4e7d-4079-909f-4f5e9c6a08e8.png)
`wailsapp/wails/v2/internal/frontend/devserver/devserver.go`
![image](https://user-images.githubusercontent.com/13114931/151652873-73fea86a-510c-4e3a-b9cb-6aa273f8c4cd.png)

3. screenshots
`wailsapp/wails/v2/pkg/commands/build/base.go`
![image](https://user-images.githubusercontent.com/13114931/151653118-59615332-a426-4780-a4cc-8b07eb41a640.png)
Vite + vue server
![image](https://user-images.githubusercontent.com/13114931/151653186-3d1eab67-4afc-4619-aa0f-a4f1da8175ac.png)

**Comment by jummyliu** [comment]
> Manually import ipc_websocket.js, runtimedev.js, bindings.js in External Dev Server.

Alternatively, you can publish `ipc_websocket.js`, `runtimedev.js` to NPM, and I can import it from NPM

**Comment by stffabi** [comment]
PR #1290 is up, which adds support for external dev servers. So you are able to use the `vite dev` server in wails. Would be great if you could give it a try with the following changes in your project.json

```json
  "frontend:dev:watcher": "npm run dev",
  "frontend:dev:serverUrl": "http://localhost:3000",
```
