### ISSUE TITLE
wails doctor on debian suggests already installed packages

### ISSUE THREAD

**Issue by Luit** [wailsapp/wails#1117]
**Description**
I was looking for what's there for wails v2 on Linux already, and noticed the package manager support shelled out to `apt`. I know from experience this'll allways warn you as follows:

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

To verify correct working I installed wails v2.0.0-beta.29 on my Debian 11 (bullseye) and ran `wails doctor`. It seems there's some variance in the output that's not accounted for here. For example, package `build-essential` on my machine outputs the following:

    luit@💻:~$ apt -qq list build-essential
    build-essential/stable,now 12.9 amd64 [installed,automatic]
    build-essential/stable 12.9 i386

Of note is the fact that multi-arch makes the output show two lines instead of one, and that the part in brackets can contain more than simply `installed`.

AFAIK the recommended tools to detect installed and available packages for an apt-based system would be `dpkg-query` and/or `apt-cache`, although I haven't yet fully dug into the best way to use them. If you want I could pick this up and investigate a bit further.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install wails beta on Debian 11
2. Run `wails doctor`
3. See output.

**Expected behaviour**
I have all required dependencies installed, so I'd expect it to note all dependencies as `Installed`. Instead, some are noted `Available`.

**System Details**

    luit@💻:~$ wails doctor
    Wails CLI v2.0.0-beta.29

    Scanning system - Please wait (this may take a long time)...Done.

    System
    ------
    OS:			Debian GNU/Linux
    Version: 		11
    ID:			debian
    Go Version:		go1.17.5
    Platform:		linux
    Architecture:		amd64
    Package Manager: 	apt

    Dependency	Package Name		Status		Version
    ----------	------------		------		-------
    *docker		docker.io		Available	20.10.5+dfsg1-1+deb11u1
    gcc		build-essential		Available	12.9
    libgtk-3	libgtk-3-dev		Installed	3.24.24-4
    libwebkit	libwebkit2gtk-4.0-dev	Available	2.34.4-1~deb11u1
    npm		npm			Installed	7.5.2+ds-2
    pkg-config	pkg-config		Available	0.29.2-1

    * - Optional Dependency

    Diagnosis
    ---------
    Your system has missing dependencies!

    Required package(s) installation details: 
    - gcc: sudo apt install build-essential
    - libwebkit: sudo apt install libwebkit2gtk-4.0-dev
    - pkg-config: sudo apt install pkg-config

    Optional package(s) installation details: 
    - docker: sudo apt install docker.io

    If Wails is useful to you or your company, please consider sponsoring the project:
    https://github.com/sponsors/leaanthony

**Comment by leaanthony** [comment]
Hey @Luit - I did write a lengthy reply but it looks like it got lost somewhere. Thanks for picking up on this. I'm *very* happy for you to run with this! Please let me know how I can help you!

**Comment by leaanthony** [comment]
We're tracking this in #1179 👍
