### ISSUE TITLE
[v2 bug] the wailsjsdir option won't take affect in the wails.json

### ISSUE THREAD

**Issue by terasum** [wailsapp/wails#1119]
**Description**

I specific the `wailsjsdir` option in the wails.json file like this:
```
{
  "name": "abc",
  "frontend:build": "yarn run build:dev",
  "frontend:install": "yarn install",
  "frontend:dev": "yarn run build:dev",
  "wailsjsdir": "./frontend/src",
  ...
  "debounceMS": 100,
  "devserverurl": "http://localhost:34115",
  "appargs": ""
}
```

and wails still generate the `wailsjs` directory in the root directory, and I spend some time tracing this, I found:

`github.com/wailsapp/wails/v2/pkg/commands/build/build.go:108`
```
	// Initialise Builder
	builder.SetProjectData(projectData)
```

the `projectData` has loaded wails.json, however, the `wailsjsdir` is never assigned to `options`.

**To Reproduce**
Steps to reproduce the behaviour:
1. just modify `wails.json` and change `wailsjsdir`
2. `wails build`

**Expected behaviour**
the `wailsjs` directory generate in the `frontend/src`, but not 

**Screenshots**
N/a

**System Details**

Wails CLI v2.0.0-beta.29

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        11.5.1
ID:             199506
Go Version:     go1.17.3
Platform:       darwin
Architecture:   arm64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2384
npm                             N/A             Installed       8.1.3
*upx                            N/A             Installed       upx 3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!

**Additional context**
I've add those code fixes this:

`github.com/wailsapp/wails/v2/pkg/commands/build/build.go:116`
```
	// wails js dir
	if projectData.WailsJSDir != "" {
		options.WailsJSDir = projectData.WailsJSDir
	}
```

**Comment by leaanthony** [comment]
This is fixed on master 👍

**Comment by terasum** [comment]
@leaanthony oh, I installed wails by `go install`, I missed this fixing, closed.

**Comment by leoyoung07** [comment]
@leaanthony I have the same problem. I'm using Wails CLI v2.0.0-beta.34

**Comment by leaanthony** [comment]
Please open a new ticket and fill in the issue template details
