### ISSUE TITLE
[V2][Windows10] TaskBar Bug on Frameless Window with WindowMaximise()

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1120]
**Description**
As mention in #1087. This is a new bug from PR #1085

**To Reproduce**
In ``Frameless`` mode.
Set ``DisableResize`` to ``true``
Use ``WindowMaximise()`` to maximize the window.
This will happends:
![Capture](https://user-images.githubusercontent.com/28552977/152014454-e3800260-65b6-41ad-8dde-ea2503f71631.PNG)

Expecting to see the Windows 10 Task bar at the bottom.

**Additional context**
My ``main.go`` file as @stffabi needed:
```go
package main

import (
	"embed"
	"log"

	"github.com/wailsapp/wails/v2/pkg/options/mac"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/logger"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
)

//go:embed frontend/src
var assets embed.FS

//go:embed build/appicon.png
var icon []byte

func main() {
	// Create an instance of the app structure
	app := NewApp()
	// Create application with options
	err := wails.Run(&options.App{
		Title:             "Untitle",
		MinWidth:          1400,
		MinHeight:         900,
		DisableResize:     true,
		Fullscreen:        false,
		Frameless:         true,
		StartHidden:       false,
		HideWindowOnClose: false,
		RGBA:              &options.RGBA{R: 33, G: 37, B: 43, A: 255},
		Assets:            assets,
		LogLevel:          logger.DEBUG,
		OnStartup:         app.startup,
		OnDomReady:        app.domReady,
		OnShutdown:        app.shutdown,
		Bind: []interface{}{
			app,
		},
		// Windows platform specific options
		Windows: &windows.Options{
			WebviewIsTransparent:  false,
			WindowIsTranslucent:   false,
			DisableWindowIcon:     false,
			EnableFramelessBorder: false,
		},
		Mac: &mac.Options{
			TitleBar:             mac.TitleBarHiddenInset(),
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
			About: &mac.AboutInfo{
				Title:   "Untitle",
				Message: "Part of the Wails projects",
				Icon:    icon,
			},
		},
	})

	if err != nil {
		log.Fatal(err)
	}
}
```
It works fine on Windows 7.

**Comment by stffabi** [comment]
Thanks for the reproduction guide. It seems like something similar happens even if `Frameless` is false, in that case the Window will be maximised over the taskbar and the taskbar is hidden. There's no white cover but still in my opinion the window shouldn't be stretched over the taskbar. So I suspect it wasn't introduced by PR #1085.

The other question is, should a `WindowMaximise()` be possible even if `DisableResize = true`?

The observations have been seen on Windows 11.

**Comment by leaanthony** [comment]
There was discussion around this (there's a ticket somewhere) where the request was "if I ask a window to full screen, it should as constraints should only apply when windowed". Most agreed with this so code was added in to temporarily disable the constraints. So should that apply to maximise? Perhaps flags to override such as "canMaximise" etc? I'm happy to do whatever electron does.

**Comment by stffabi** [comment]
I don't know electron, but I would expect that it's possible to call WindowMaximise and it does maximise even when resizing is disabled. But the default maximise button should be disabled, it should be just possible to maximize from the code.
So it would behave like fullscreen, which is also possible if resizing is disabled.

**Comment by stffabi** [comment]
I can confirm, this happens as soon as `DisableResize:     true` is set and it happens on frameless and framed windows. The difference is that in frameless the white box is shown on the position where the taskbar is, whereas in framed mode webview is full sized and covers the taskbar.

Not disabling the maximize button here, fixes the problem for both framed and frameless: 
https://github.com/wailsapp/wails/blob/aa8a8f80f06feb674820608e53d3a012344bb414/v2/internal/frontend/desktop/windows/window.go#L61 

Fixing seems rather hard by handling `WM_GETMINMAXINFO` and setting `ptMaxSize` which has very strange behaviour on multiscreen causing #1094, see also [How does the window manager adjust ptMaxSize and ptMaxPosition for multiple monitors?](https://devblogs.microsoft.com/oldnewthing/20150501-00/?p=44964)

I was unable to get a real working solution for all cases by adjusting `ptMaxSize`. Maybe the easiest and maintainable solution would be to add a `DisableMaximize` option and if that is set it's even not possible to maximize by code.

There's also another bug regarding taskbar, if `DisableResize:     true` and `DisableMaximize: false` and the taskbar is auto-hidden, it's impossible to get the taskbar unhidden. 😕

**Comment by stffabi** [comment]
We could at least get rid of the white box if `Frameless == true && DisableResize == true` with an easy patch. So at least both frameless and framed would behave the same way if `DisableResize == true`.

**Comment by stffabi** [comment]
Just another side-note: On MacOS `WindowMaximise()` doesn't maximise if `DisableResize == true`.

**Comment by leaanthony** [comment]
So Mac works as expected, windows not?

**Comment by stffabi** [comment]
> So Mac works as expected, windows not?

The question is, what is expected 😄 . Current mac implementation doesn't maximise if resizing is disabled, whereas windows allows it. And this behaviour on windows triggers the bug that the taskbar is covered by the window.

So I think we could define the current behaviour on Mac as expected and adjust Windows to behave the same way, and as a result this bug would not occur anymore.

**Comment by leaanthony** [comment]
I've pushed a fix for this on `master`. Let me know how you go 👍
