### ISSUE TITLE
Preinstall wails

### ISSUE THREAD

**Issue by ratimaisuradze** [wailsapp/wails#1124]
Hello walls! I have one question / idea. could you addition some feature. when customers run application for example (windows 7/10) where is not installed required component e.g WebView2 or some dll library.

Automatically download and install standard libraries instead of making an error. I need two programs now. first one which will test the components and then install it and second the program written in wails.

**Comment by leaanthony** [comment]
Already done! https://wails.io/docs/reference/cli#build - note the webview2 flag. You should be aware that, like Microsoft, we don't support Windows 7. It may work...but we don't support it.

**Comment by ratimaisuradze** [comment]
> Already done! https://wails.io/docs/reference/cli#build - note the webview2 flag. More info https://wails.io/docs/guides/windows
> 
> You should be aware that, like Microsoft, we don't support Windows 7. It may work...but we don't support it.

thanks for link.  <3  
could I use custom script until run wails app ? for example download some library  and then  initializing wails.

**Comment by leaanthony** [comment]
I'd suggest you use an installer like NSIS for that.
