### ISSUE TITLE
V2 - runtime method for getting mode (dev vs production)

### ISSUE THREAD

**Issue by BillBuilt** [wailsapp/wails#1126]
I'd like to use the standard logger in dev mode and the file logger in production but I haven't found a way to determine the currently running mode. Using build tags was proposed as the only real method to achieve this currently but a runtime method that would return the value would be ideal. I am creating this ticket as requested in the discussion listed below. Thanks!

_Originally posted by @BillBuilt in https://github.com/wailsapp/wails/discussions/828#discussioncomment-2105092_

**Comment by leaanthony** [comment]
Have a try of `master` :-) The website should be updated in 5-10 mins: https://wails.io/docs/reference/runtime/intro

**Comment by BillBuilt** [comment]
It appears to be working, but perhaps an unrelated issue has come up or maybe it is related. I can only test this in production mode (`wails build`). Here are the steps to the issue i am having:

1. Delete all things `wailsapp` in my GOPATH to start fresh, including the binary in `bin`.
2. Install `master` -> `go install github.com/wailsapp/wails/v2/cmd/wails@master`. This downloads and installs `$GOPATH/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.29.0.20220203205245-082af614ff28`.... but running `wails version` will report `v2.0.0-beta.29` instead of `v2.0.0-beta.29.0.20220203205245-082af614ff28`
3. I can do `wails build` here and everything's fine. The new `runtime.Environment()` method works fine.
4. When I do `wails dev`, it is changing `go.mod` to use `v2.0.0-beta.29` and now in $GOPATH there is `/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.29` AND `pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.29.0.20220203205245-082af614ff28`. This causes the app to crash since it is missing `runtime.Environment()`. Running `wails version` will report `v2.0.0-beta.29`. 

Am I doing something wrong here?

Thanks again!

**Comment by leaanthony** [comment]
https://wails.io/docs/guides/bleeding-edge 👍

**Comment by BillBuilt** [comment]
Thanks - i knew i had to be overlooking something. I rarely venture out onto the bleeding edge of anything ha!

**Comment by leaanthony** [comment]
Should be doing a release this weekend so you won't need to 👍
