### ISSUE TITLE
V2 - importing models.ts

### ISSUE THREAD

**Issue by BillBuilt** [wailsapp/wails#1132]
**Description**
App crashes when importing from models.ts

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an import line to import a class from `wailsjs/go/models.ts` ( the class isn't even being used yet, just imported )
2. Run: frontend -> `npm run dev` and backend -> `wails dev`
3. App builds, and launches then immediately crashes with the error `FATAL: lstat /Users/billmatlock/web/htdocs/Golang/myapp/frontend/dist/assets: no such file or directory` but the window remains open with just a blank white screen and at no time during the process can/do I see the `assets` dir go away. If it does it gets deleted and re-created so fast that it is not observable.

**Expected behaviour**
Run normally - if i comment out the import line the problems go away

**Screenshots**
Attached is a screenshot of my frontend dir structure
<img width="313" alt="Screen Shot 2022-02-07 at 9 42 40 AM" src="https://user-images.githubusercontent.com/28831382/152813048-959101bd-3b3c-426f-9022-abecb49a4089.png">

**System Details**
```
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        11.6.2
ID:             199506
Go Version:     go1.17.6
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2384
npm                             N/A             Installed       8.3.0
*upx                            N/A             Installed       upx 3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Additional context**
Not sure if this matters but my JS code lives in `src/` which is a sibling of `wailsjs/`. I have tried changing the location of `wailsjs/` to `src/wailsjs` in `wails.json` but this caused other issues so was hoping to remedy this another way, if possible. Therefore the import line looks like this: `import { Account } from "../../../wailsjs/go/models.ts"`

The frontend builds fine without any issues.

I've tried changing the `debounceMS` value as well with no luck.

**Comment by leaanthony** [comment]
Can you confirm that you're using a typescript compiler to build your code?

**Comment by BillBuilt** [comment]
Hey Lea,

I apologize, I usually don't use TypeScript, so I'm not sure how to do that or what you'd need. I used Vite's CLI to scaffold the project with Svelte, and chose YES when asked if I wanted TS support. I would be happy to provide anything you'd need to see though. Everything else has worked fine and I can get by without importing `models.ts` but using it felt, well, like a better idea than not using it, I suppose. The main entry point to the app is `main.ts` and have 0 complaints from any build process about it and I can use `<script lang="ts">` without anything complaints as well.

**Comment by BillBuilt** [comment]
Hi Lea,

Thanks for that hint! I've narrowed the problem down to the fact that we have to use VIte's `build --watch` command when using with Wails since Vite's dev command does not do a build process. I was assuming that the only difference between `build --watch` and the standard `build` was that `build --watch` watches for changes and `build` does not. However, when using the standard `build` command, waiting for it to finish then launching `wails dev`, the error indeed goes away and everything works as expected. Unfortunately, this greatly lengthens the dev time since there is no automatic change watching going on in the frontend with this approach. Not a deal-breaker, just something that would be nice to have in my pocket but I can get by without it.

**Comment by BillBuilt** [comment]
After watching my silly dog try to catch his own tail, once the laughter subsided I realized that this may be what's happening here - although I do not know how to test it, but it makes sense. 
 - Vite's `build --watch` builds for production but then watches for changes.
 - Having the import line that imports `wailsjs/go/models.ts` in the fronted code puts that file (and and possibly anything related) under that watchful eye.
 - So, issuing Vite's `build --watch` builds the frontend and then it starts watching for changes.
 - Then, we run `wails dev` which does it's thing, including (I'm assuming) re-creating `wailsjs/go/models.ts`.
 - This would cause Vite to see a change and issue its own rebuild.
 - And thus, it starts chasing its own tail, which like my dog, can never find a way to catch that elusive thing!

**Comment by leaanthony** [comment]
I think having the option to disable the Wails watcher is one way we could fix that. I'm keen to get the most optimal Vite solution for dev.

**Comment by BillBuilt** [comment]
Yea, that's probably partly what's driving the discussions around using an external server for dev. I've tried playing with the external server option in wails.js config in the past but but unsuccessful.... but don't remember what the issue was.

**Comment by leaanthony** [comment]
Hey @BillBuilt - We have a `frontend:dev:watcher` flag that may be of interest. Please let me know if there's something in this ticket that needs addressing. Thanks 🙏

**Comment by BillBuilt** [comment]
@leaanthony   So far so good! I am no longer getting the errors I was experiencing, and am now able to import models.ts. It's also very nice not to have to initiate the Vite watcher in a separate process. I will definitely be using this more now and will report back here if I run in to any problems. Kudos to all involved in making this happen!

**Comment by leaanthony** [comment]
Brilliant - thanks for the update Bill.

**Comment by BillBuilt** [comment]
Well, I'm not sure what happened. I've been using this new `frontend:dev:watcher` flag for a few days now and I really like it. Today I decided to start importing and using the `models.ts` and it's back to throwing the error `FATAL: lstat /Users/billmatlock/web/htdocs/Golang/myapp/frontend/dist/assets: no such file or directory`. Maybe my initial test was flawed - it was early on a Sunday morning after-all lol. Is ther a way to adjust the amount of time between it running the `frontend:dev:watcher` command and the actual compile step? Maybe it just needs a few more milliseconds for that dir to show up? Again, not a deal-breaker for me but just wanted to correct my last post.

**Comment by BillBuilt** [comment]
Not sure if this is related or not but I've just notice some strange behavior that I had not seen before. So when I use `wails dev` to launch the app, if I close the app the normal way, or use CTRL-C to kill it, some watcher stays running in the background. I cannot find it in my activity monitor, but if I change something and  SAVE, my console will show the process of rebuilding even though nothing was supposed to be running. I don't know how to kill this process either, I basically have to close GoLand and relaunch it. This has never happened before now, as far as I know.

**Comment by leaanthony** [comment]
Ah, the joy of tracking subprocesses in goroutines...  Could you possibly open a new issue for this with the details please? We can probably fix with a context cancel...
