### ISSUE TITLE
[v2] Detect system theme and make CSS selector possible

### ISSUE THREAD

**Issue by TheFranconianCoder** [wailsapp/wails#1133]
Currently the system theme (dark or light mode) is not detected. The title bar stays light and no detection via CSS is possible.

**Comment by leaanthony** [comment]
CSS detection has been possible (tailwind detects it). If this is an enhancement, please present a proposed design of how this would work cross platform. Thanks.

**Comment by sebastian0x62** [comment]
👍 Confirmed. Can use media queries. I guess I was confused because the title bar stays white with dark system theme. CSS selector works as expected. Thanks.
