### ISSUE TITLE
NSIS Support for Windows

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1135]
Create an installer option for Windows builds.

**Comment by misitebao** [comment]
@leaanthony 
Is it better to set the packaging format to `msix` format? I looked at the `msix` related documentation today and it is a future format and backwards compatible.

**Comment by leaanthony** [comment]
We're adding NSIS first. If you want to create a guide on MSIX packaging, feel free. If it's easyish then we can consider adding it. NSIS compiler works on Mac and Linux so much easier for Cross compile situations
