### ISSUE TITLE
Development tooling - cannot find package "gopkg.in/AlecAivazis/survey.v1"

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#114]
**Description**
I am following the [development document's tooling section](https://wails.app/development/#tooling).
When running `go install --tags=dev` I'm getting this error
```
10.1_dev_newtemplate.go:10:2: cannot find package "gopkg.in/AlecAivazis/survey.v1" in any of:
	/usr/local/go/src/gopkg.in/AlecAivazis/survey.v1 (from $GOROOT)
	/home/byron/go/src/gopkg.in/AlecAivazis/survey.v1 (from $GOPATH)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `rm $GOPATH/bin/wails && rm -R $GOPATH/src/github.com/wailsapp`
2. `go get github.com/wailsapp/wails/cmd/wails`
3. `cd $GOPATH/src/github.com/wailsapp/cmd/wails`
4. `go install --tags=dev`
5. See error

**Expected behaviour**
Generate new project template

**System Details**
Ubuntu 18.04, go1.12.3

**Additional context**
runing `go get gopkg.in/AlecAivazis/survey.v1` solved the issue and I was able to generate a new template.

**Comment by leaanthony** [comment]
ThIf you are developing in GOPATH, it may make a difference as I've only ever run it outside of GOPATH. I *would* have thought that go install would have pulled it in. After saying that, I've had this happen before. I'll check it out when I can. BTW, `wails issue` is a better way of opening tickets ;-)
