### ISSUE TITLE
ld: framework not found UniformTypeIdentifiers after wails build

### ISSUE THREAD

**Issue by annikovk** [wailsapp/wails#1140]
**Description**
wails build and wails dev commands return an error about missing UniformTypeIdentifiers library. 
I do not know how to install it explicitly. Only saw that my macOS version (12.1) should have it bundled. 
Moreover, the file is here: 

```
locate UniformTypeIdentifiers | grep -v kotlin
/System/Library/Frameworks/UniformTypeIdentifiers.framework
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Resources
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources/BridgeSupport
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources/BridgeSupport/UniformTypeIdentifiers.arm64e.bridgesupport
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources/BridgeSupport/UniformTypeIdentifiers.bridgesupport
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources/Info.plist
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/Resources/version.plist
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/_CodeSignature
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/_CodeSignature/CodeResources
/System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/Current
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init -n wailsLogAnalyzer`

```
Wails CLI v2.0.0-beta.30


Initialising Project WailsLogAnalyzer
-------------------------------------


Project Name:      wailsLogAnalyzer
Project Directory: /Users/konstantin.annikov/Downloads/wailsLogAnalyzer
Project Template:  vanilla
Template Support:  https://github.com/wailsapp/wails

Initialised project 'wailsLogAnalyzer' in 382ms.
```

2. `cd ./wailsLogAnalyzer/`
3. `wails dev`

```
wails dev
Wails CLI v2.0.0-beta.30


Executing: go mod tidy
Executing: wails generate module
Building application for development...
No Install command. Skipping.
No Build command. Skipping.
Compiling application: # runtime/cgo
ld: framework not found UniformTypeIdentifiers
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Build error - continuing to run current version
exit status 2
Watching (sub)/directory: /Users/konstantin.annikov/Downloads/wailsLogAnalyzer
Using Dev Server URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds

```

**Expected behaviour**
- improved error message, so missing frameworks could be installed by executing a command in console

**Screenshots**

**System Details**

```
wails doctor
Wails CLI v2.0.0-beta.30


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.1
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.4.1
*upx 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
 ```

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by annikovk** [comment]
Reinstallation XCode Command line tools helped. 
Maybe add a hint to the error's text?

**Comment by leaanthony** [comment]
Yeah this is super annoying. I guess we could run the error through a filter and determine if that's the problem? Did you reinstall to the latest? I'm trying to determine the exact steps

**Comment by annikovk** [comment]
Yeah, latest

**Comment by leaanthony** [comment]
Not sure you can retest this, but I've pushed a commit to try and output some help if this happens. Are you able to test it?

**Comment by allcapsc** [comment]
> Not sure you can retest this, but I've pushed a commit to try and output some help if this happens. Are you able to test it?

Any updates? Having same issue on macOS 12.0.1

**Comment by allcapsc** [comment]
> > Not sure you can retest this, but I've pushed a commit to try and output some help if this happens. Are you able to test it?
> 
> Any updates? Having same issue on macOS 12.0.1

Was able to get it working, if anyone has the same issue you can refer to https://mac.install.guide/commandlinetools/6.html to Uninstall Xcode Command Tools and https://mac.install.guide/commandlinetools/7.html to Reinstall Xcode Command Tools

**Comment by stffabi** [comment]
@allcapsc did you test the latest Wails release? It should output a help text user with instructions to reinstall the xcode cli tools in this case.

**Comment by allcapsc** [comment]
> 

I have not, I'm running v2.0.0-beta.32. Would that be latest? I might have skimmed through the error log when that error appeared for me.

**Comment by stffabi** [comment]
'beta.32' should output the instructions. Maybe the detection doesn't yet detect all cases.

**Comment by allcapsc** [comment]
> 'beta.32' should output the instructions. Maybe the detection doesn't yet detect all cases.

Ah maybe but thank you tho! Got it working thankfully 👍

**Comment by jaylin507** [comment]
If someone encounters the same problem and reinstalling **Xcode Command Tools** still fails, you can check the path where the toolkit is located

Run  `xcode-select -p`

If "/Applications/Xcode. app/Contents/Developer" is displayed

Run `sudo xcode-select --switch /Library/Developer/CommandLineTools`

--
My version info
Wails CLI v2.1.0
macOS: 12.5.1-x86_64
CLT: 14.0.0.0.1.1661618636

 it work!

**Comment by leaanthony** [comment]
Thanks for letting us know!. Will update the troubleshooting guide
