### ISSUE TITLE
Support Distribution 'Archcraft'

### ISSUE THREAD

**Issue by MasterBrian99** [wailsapp/wails#1141]
**Description**
Distribution 'archcraft' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.9 |
| Go Version    | go1.17.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | archcraft |
| Distribution Name   | Archcraft |
| Distribution Version   |  |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by MasterBrian99** [comment]
yes.it is based on arch.only difference is the name.
[https://archcraft.io/](https://archcraft.io/)

**Comment by leaanthony** [comment]
v1 is now in feature freeze. v2 should work fine on Archcraft (Pacman?). Let me know how you go 👍
