### ISSUE TITLE
Anonymous struct not supported in auto-generated binding

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#1142]
**Description**
Generating the JS binding, in wails 2, from golang structs that contains anonymous struct, is broken.

**To Reproduce**
1. Return a struct with a nested anonymous struct in the "API" struct

```go
type MoreKittens struct {
    Mother string `json...`
    Father string `json...`
    Furs []struct {
        Pattern string `json...`
        Color string `json...`
    } `json...`
}

func (a *App) ProduceKitten() (*MoreKittens, error) {
	// Doing some fluffy stuff
}
```
2. `wails generate module`
3.  Get broken JS
```typescript
export class  { // No class name
    color: string;
    pattern: number;
   
    // more JS stuff
}
export class MoreKittens {
    mother: string;
    father: string;
    furs: ; // No type

     // more JS stuff
}
```

**Expected behaviour**
No sure what we should do in details, but we could have something working. Or, we should fail to say it's not supported.

**System Details**
```
System
------
OS:		MacOS
Version: 	12.1
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	arm64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.1.2
*upx 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
```

**Comment by leaanthony** [comment]
Nice find. I use a 3rd party library for this. I'll open a bug on the project

**Comment by leaanthony** [comment]
I would just used named structs in the meantime.

**Comment by KiddoV** [comment]
I see `anoynimous nested structs` still not support in current version? ``v2.9.2`` ?

**Comment by phuclh** [comment]
> I see `anoynimous nested structs` still not support in current version `v2.9.2` ?

Yeah, I still get the issue when using anonymous nested structs in v2.9.2

**Comment by leaanthony** [comment]
Yeah we don't support them
