### ISSUE TITLE
`build/appicon.png` not picked up

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#1143]
**Description**
As advertise by the documentation, the `appicon.png` should be located under the `build` folder to be picked up by `wails build`.

It appears to not be the case. It produces an `appicon.png` in the root folder, and doesn't update the app icon.

**To Reproduce**
1. `wails init -n wails-test`
2. `cd wails-test`
3. Replace `build/appicon.png` by another one
4. `wails build`
5. Acknowledge the creation of default icon in the project folder
6. Acknowledge the non-updated icon on the app

**Expected behaviour**
As advertise by the documentation, the `appicon.png` under the `build` folder should be picked up by `wails build`.

**System Details**
```
System
------
OS:		MacOS
Version: 	12.1
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	arm64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.1.2
*upx 				N/A		Available	
```

**Comment by leaanthony** [comment]
Hi, this must be new or everyone would be experiencing it. Will investigate. What version of Wails?

**Comment by ValentinTrinque** [comment]
Thank for your quick response.

**Comment by foreverzmy** [comment]
Happen again，change `appicon.png` not working on Mac Dock.

```
Wails CLI v2.0.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.5.1
ID:		21G83
Go Version:	go1.19.2
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	6.14.10
*upx  				N/A 		Available
*nsis  				N/A 		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by ValentinTrinque** [comment]
@foreverzmy Can you past the tree structure of your `build` folder ?

Mine is like this, and works fine:

```
build
├── appicon.png
├── darwin
│   └── info.plist
└── windows
    ├── Vegawallet.exe.manifest
    └── info.json
```

More details at https://github.com/vegaprotocol/vegawallet-desktop/tree/develop/build

**Comment by ValentinTrinque** [comment]
Also, in embedding happens like this:

https://github.com/vegaprotocol/vegawallet-desktop/blob/43d4fe8fdcb6ece28c2315a43954afed7aa4a3f2/main.go#L22-L23

https://github.com/vegaprotocol/vegawallet-desktop/blob/43d4fe8fdcb6ece28c2315a43954afed7aa4a3f2/main.go#L66-L75

**Comment by foreverzmy** [comment]
> 

Thx for your reply, It's resolved when I restart several times, but i don't know why? maybe cache?

**Comment by saul-data** [comment]
I am experiencing the same. I can't seem to change the default appicon.png

**Comment by zveinn** [comment]
Any fixes for this ? I'm having this problem on windows, appicon.png exists and I even followed the guide to make the inco.ico but it still uses the original wails icon

**Comment by oddcitizenape** [comment]
This issue still persists, I'm running wails 2.6.0 with go 1.21.4 on windows 11. Nothing from above helps to resolve it.

**Comment by antick** [comment]
I can confirm that this problem still persists. Not sure why this issue is closed while this clearly exists for all of us. I have tried deleting the build and dist folder still it generates the default app icon.
