### ISSUE TITLE
V2 - Improved Borderless Windows (shadows and W11 rounded edges)

### ISSUE THREAD

**Issue by maxkunes** [wailsapp/wails#1147]
On Windows 11, when using wails in frameless mode, the window is not correctly rounded and the (aero) shadow is missing. The shadow is also missing on previous windows versions.

As far as I am aware, this is because the API `DwmExtendFrameIntoClientArea` causes any shadow and rounding to disappear from a window regardless of its classes or configuration.

I was working on a different project when I noticed this and found this [blog](https://kubyshkin.name/posts/win32-window-custom-title-bar-caption/) that had already described an alternative solution for frameless windows that seems to require less work and does not need to use `DwmExtendFrameIntoClientArea`.

I've implemented this into a fork of wails and I'm interested in hearing some feedback and whether or not something like this should be made into a pull request. 

[Link to fork/commit](https://github.com/maxkunes/wails/commit/7d57a1af53e5fc6d44037ad66e8a114430f7130f)

**Comment by leaanthony** [comment]
Hey thanks for doing this. Could you raise a PR so it will be easier to test? @stffabi

**Comment by stffabi** [comment]
Thank you very much for opening this issue and providing code with your suggestions.

AFAIK it was intended to have no shadow and no rounded corners in order to give the frontend the full control over the window. If the shadow, borders and the rounded corners (on Windows 11) should be added, the option [EnableFramelessBorder](https://wails.io/docs/reference/options#enableframelessborder) could be used to add them again. @leaanthony should we have the shadow and borders added in all cases for frameless windows?
The `EnableFramelessBorder` option uses the `DwmExtendFrameIntoClientArea` with a margin of -1 to add the glass-effects (aero shadow and rounded corners). If I might ask, did that option work in your case?

I've taken a brief look into your code and tested it against a default `wails init` project. I think maybe I'm doing something wrong, but in my case there was now a small transparent border between the outer border and the webview.

<img width="633" alt="Screenshot 2022-02-14 at 09 36 09" src="https://user-images.githubusercontent.com/9464631/153828502-708978d8-d499-4d96-9267-ab878f06f72d.png">

**Comment by maxkunes** [comment]
> Thank you very much for opening this issue and providing code with your suggestions.
> 
> AFAIK it was intended to have no shadow and no rounded corners in order to give the frontend the full control over the window. If the shadow, borders and the rounded corners (on Windows 11) should be added, the option [EnableFramelessBorder](https://wails.io/docs/reference/options#enableframelessborder) could be used to add them again. @leaanthony should we have the shadow and borders added in all cases for frameless windows? The `EnableFramelessBorder` option uses the `DwmExtendFrameIntoClientArea` with a margin of -1 to add the glass-effects (aero shadow and rounded corners). If I might ask, did that option work in your case?
> 
> I've taken a brief look into your code and tested it against a default `wails init` project. I think maybe I'm doing something wrong, but in my case there was now a small transparent border between the outer border and the webview.
> 
> <img alt="Screenshot 2022-02-14 at 09 36 09" width="633" src="https://user-images.githubusercontent.com/9464631/153828502-708978d8-d499-4d96-9267-ab878f06f72d.png">

Hmm, that is strange, this is the behaviour I get on my PC (Windows 11) and multiple Windows 10 PCs.

![image](https://user-images.githubusercontent.com/11730836/153829226-4cfa5815-61d0-4a3b-85d2-cb3ff061456b.png)

**Comment by leaanthony** [comment]
Thanks for looking at this so quickly @stffabi. I think if we're running on Windows 11, the default should be the Windows 11 style with the option to customise it like we have. I'm not sure if that complicates things?

**Comment by leaanthony** [comment]
I've gotta say, that screenshot looks pretty awesome @maxkunes. What does it look like on Windows 10?

**Comment by stffabi** [comment]
@leaanthony at the moment we have per default no frame styling on all Windows version. So for Windows 11 this means no border, no rounded corners and no shadow. If the `EnableFramelessBorder` option is activated the default styling for border will be activated, which means on Windows 11 (aero shadow, borders and rounded corners).

**Comment by maxkunes** [comment]
My screenshot also describes the expected behavior of this patch, borderless, frameless, rounded, and has shadow.

This is what I would expect from a library that offers frameless windows. At the very least on Windows 10/11 you are missing the window shadow which should appear on all windows and on Windows 11, the default style is rounded so I think these changes make sense.

I'll also clarify that on Windows 10, this change does not cause window rounding as that is only a Windows 11 feature.

I'm not exactly sure what you are referring to regarding the window border, I don't want any sort of window border in a frameless window.

**Comment by stffabi** [comment]
@maxkunes could you please test the `EnableFramelessBorder` option and specify how this differs from your solution just taking into account how the window visually appears?

**Comment by maxkunes** [comment]
@stffabi 

Does V2 have `EnableFramelessBorder`? I don't see that supported in the actual platform code.

**Comment by stffabi** [comment]
@maxkunes yes, v2 has that option. 
https://github.com/wailsapp/wails/blob/f923a431f7ba60953ba196576c6fe12b842bf2af/v2/internal/frontend/desktop/windows/window.go#L154-L158

**Comment by leaanthony** [comment]
@stffabi do you think it might be worth inverting the flag, so that by default it has this functionality? Or perhaps we can have a `FramelessStyle` option which allows either? I mean, that screenshot looks 🔥

**Comment by stffabi** [comment]
Here's a screenshot of the current v2-master with `EnableFramelessBorder` activated on my Windows 11 machine.
<img width="644" alt="Screenshot 2022-02-14 at 09 50 04" src="https://user-images.githubusercontent.com/9464631/153830686-42b1bfc6-5184-41ba-9472-2246a8cbb8c7.png">

**Comment by maxkunes** [comment]
@stffabi I completely missed that. The changes I made seem unnecessary as it's already supported. I will say that the naming here `EnableFramelessBorder` seems a bit odd.

For clarity it seems with the current build of wails:

`EnableFramelessBorder: false` produces a window without rounded corners or shadows. Looks a bit weird on Windows 10/11 in my opinion.

![image](https://user-images.githubusercontent.com/11730836/153830576-1809984c-8961-426c-9142-8a741ee23aec.png)

`EnableFramelessBorder: true` produces a window with correct rounded corners and shadows!  

![image](https://user-images.githubusercontent.com/11730836/153830751-68307dbf-a288-4ccc-8fde-d57a8c82717f.png)

**Comment by stffabi** [comment]
> @stffabi do you think it might be worth inverting the flag, so that by default it has this functionality? Or perhaps we can have a `FramelessStyle` option which allows either? I mean, that screenshot looks 🔥

Yes we could certainly inverting the flag, would be a breaking change for those who want really no borders. But since we are still in beta I think we might do that.

**Comment by maxkunes** [comment]
One question I have is what is the behavior of `EnableFramelessBorder: true` on Windows 10? Is it shadows with no rounded edges (what I would expect?)

**Comment by stffabi** [comment]
> @stffabi I completely missed that. The changes I made seem unnecessary as it's already supported.

Awesome, that it works as expected  🎉 

> I will say that the naming here `EnableFramelessBorder` seems a bit odd.

Yeah I support that, I didn't use a very meaning naming here. 

> `EnableFramelessBorder: false` produces a window without rounded corners or shadows. Looks a bit weird on Windows 10/11 in my opinion.

Yes, that was exactly why the option was added. But looking back it would have been better to make this the default and add an option "NoWindowsStylingForFramelessWindows" or something like this.

> One question I have is what is the behavior of EnableFramelessBorder: true on Windows 10? Is it shadows with no rounded edges? (what I would expect?)

That should be the case on Windows 10, aero shadow with no rounded edges.

**Comment by stffabi** [comment]
@maxkunes @leaanthony in which direction do we wanna go for this flag? Removing it and having the default styling applied per default and adding a flag to remove the styling? Or adding the styling always and not supporting removing it?

**Comment by leaanthony** [comment]
I'm seriously overtired so my brain isn't functioning as it should, but I think the path of least surprise is that the default styling is applied when frameless is set to true. What are your thoughts @stffabi ?

**Comment by stffabi** [comment]
> @stffabi I completely missed that. The changes I made seem unnecessary as it's already supported.

We have to thank you very much for taking your time implementing code and providing it. I'm sorry for all your time you put into this as the functionality already existed. I know how time consuming this windows API things are...

**Comment by maxkunes** [comment]
@stffabi Haha, don't worry about it. I got to write some go for the first time in awhile :)

**Comment by maxkunes** [comment]
> @maxkunes @leaanthony in which direction do we wanna go for this flag? Removing it and having the default styling applied per default and adding a flag to remove the styling? Or adding the styling always and not supporting removing it?

My suggestion is that it should be similar to electron:

Enabling frameless should automatically round edges on windows 11 and provide shadows to all versions that support it. 

I would suggest also the following:

There should be an opt out flag and I would also potentially add a opt out flag specifically for rounding (I believe shadows without rounding is possible in windows 11, there is an msdn page on opt-in and opt-out)



I would be happy to make a pull request to implement these also.

**Comment by leaanthony** [comment]
@stffabi do you know if `EnableFramelessBorder` creates rounded windows on Win11?

**Comment by stffabi** [comment]
> @stffabi do you know if `EnableFramelessBorder` creates rounded windows on Win11?

Yes, that will activate rounded windows on Windows 11. Basically that option applies the default window frame styling.

We should also have a look onto the other platforms to decide what we should do and to have a consistent behaviour, e.g. `Frameless = true` disables rounded corners on MacOS.

**Comment by leaanthony** [comment]
> My suggestion is that it should be similar to electron:
> 
> Enabling frameless should automatically round edges on windows 11 and provide shadows to all versions that support it. 

💯

> I would suggest also the following:
> 
> There should be an opt out flag and I would also potentially add a opt out flag specifically for rounding (I believe shadows without rounding is possible in windows 11, there is an msdn page on opt-in and opt-out)

Yeah, potentially.

> I would be happy to make a pull request to implement these also.

I'll leave you and @stffabi to discuss that. I think the idea has merit

**Comment by stffabi** [comment]
I've created a PR to rename the flag and improve the wording. @maxkunes could you please take a look?
