### ISSUE TITLE
[v2] Add short warning when wails binary is not in PATH

### ISSUE THREAD

**Issue by TheFranconianCoder** [wailsapp/wails#1148]
**Is your feature request related to a problem? Please describe.**

When I started working with Wails, the installed wails binary was not in the PATH. I started wails with its absolute path, as I do with other Go applications as well.

The Wails documentation is clear about that. I just missed that part. But without having Wails in PATH, it will exit without any error. Even verbose mode doesn't print information. It finishes after "wails generate module"

**Describe the solution you'd like**
The documentation is clear and correct. It would be nice to get an additional error message, that Wails binary was not found.

**Additional context**

![image](https://user-images.githubusercontent.com/70367451/153889729-bf70596b-1ae5-44fa-8e87-52f0daab1bb5.png)

**Comment by leaanthony** [comment]
I'm going to close this and say it's not feasible. The docs are pretty clear and I'm ok with manually dealing with the edge cases.

**Comment by sebastian0x62** [comment]
@leaanthony I agree, the docs are clear. I thought about printing the `err` in `dev.go` `runCommand`. Only the output of the process is currently printed. Would that makes sense? Of course I accept your decission.

**Comment by leaanthony** [comment]
I'd accept a PR for that 👍

**Comment by leaanthony** [comment]
@sebastian0x62 can you please try https://github.com/wailsapp/wails/pull/1252

**Comment by sebastian0x62** [comment]
@leaanthony that does not work for me, since I don't set any `GOPATH` environment variable. Maybe it should be read with `go env GOPATH`?

**Comment by leaanthony** [comment]
If GOPATH isn't set then I'm not sure your Go is installed correctly ☹️

**Comment by sebastian0x62** [comment]
I'm pretty sure there changed a lot with beginning of go modules. Never set GOPATH with go modules projects. Go falls back to its default path in such cases.

**Comment by sebastian0x62** [comment]
Somewhere I read, that GOPATH could be completely obsolete with Go 1.18. So maybe we should not use it in any case.

**Comment by leaanthony** [comment]
I've pushed another change. We can use this in the short term.

**Comment by sebastian0x62** [comment]
Tried. My test env.:

- No `GOPATH?  env var, so it's used from `go env GOPATH` (worked)
- !hasPrefix didn't work, because `go install` installed it in default `GOPATH`, but I called `wails` with absolute path

I guess the simplest solution still would be to do something like outputting the error for `runCommand` as well:

![image](https://user-images.githubusercontent.com/70367451/158153832-cd1112ee-c256-4792-9052-4551f132014c.png)

Which outputs:

![image](https://user-images.githubusercontent.com/70367451/158153949-1b2a14a9-24a7-464c-9f96-f3748ac73990.png)

**Comment by leaanthony** [comment]
Pushed this suggestion to master 👍

**Comment by sebastian0x62** [comment]
Works like a charm

**Comment by stffabi** [comment]
What about using `os.args[0]` to run the command instead of "wails" for self starting? Shouldn't that remove the dependency to "wails" in the path?

**Comment by stffabi** [comment]
I've created a draft PR, maybe @sebastian0x62 you could give that a try?

**Comment by sebastian0x62** [comment]
@stffabi Works as well. 👍 Makes it possible to even use different versions (while developing). But both works are very good to me.

**Comment by stffabi** [comment]
Awesome @sebastian0x62 thanks for testing the PR.

**Comment by leaanthony** [comment]
Merged. Thanks @stffabi!
