### ISSUE TITLE
black screen on custom template build

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#115]
**Description**
Following the developers document I created a custom template for React.
I managed to serve both back- and front-end. I also can build the app. 
But when I run the binary instead of react's default screen (the one I am seeing when serve-ing, see screenshot) I get a black window.

**To Reproduce**
Steps to reproduce the behaviour:
1. download the template https://github.com/bh90210/wails-create-react-app
2. place it in wails templates directory
3. initialise a new app `wails init `
4. build it `wails build`

**Expected behaviour**
Render the frontend

**Screenshots**
![test2](https://user-images.githubusercontent.com/22690219/59144905-34ed6500-89e5-11e9-8da0-5be43b3dd95e.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.15.0 |
| Go Version    | go1.12.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment]
Hey there. Thanks for doing this as a react template is super important. For the default Vue template, I use a babel config for packing all the assets into the main bundles. I'm not familiar with the react tooling but had a quick look at the build-non-split.js and I can't work out if it's doing that?

**Comment by bh90210** [comment]
[build-non-split.js](https://github.com/bh90210/wails-create-react-app/blob/master/create-react-app/frontend/scripts/build-non-split.js) is a workaround to the fact React's default behavior is a. chunking-up the final output files, so you end up with multiple .js files, this has to do with caching files faster over the web (server/client scenario), which in wail's case is a kind of irrelevant and b. the actual names of final chunks also have hashes of these files as part of their filenames (ie. `e.chunk.9623423.js`). 
The script all it does is disabling the splitting and also removes hashes from final filenames.
```javascript
const defaults = rewire('react-scripts/scripts/build.js'); // unaltered React's original build script

config.optimization.splitChunks = {
  cacheGroups: {
    default: false, // disabling chunking
  },
};

config.output.filename = 'static/js/main.js'; // final filename without hashes
```

So please have a look here, as this is where the building happens [react-scripts/scripts/build.js](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/build.js)

</br>
</br>

> I use a babel config for packing all the assets into the main bundles.

Can you please elaborate on this?
Are you referring to this file [babel.config.js](https://github.com/wailsapp/wails/blob/master/cmd/templates/vuebasic/frontend/babel.config.js)?

Or maybe this one [vue.config.js](https://github.com/wailsapp/wails/blob/master/cmd/templates/vuebasic/frontend/vue.config.js)?

**Comment by leaanthony** [comment]
So a key part of making sure your binary is portable is to ensure that all assets are bundled so they aren't loaded from external sources at runtime. For the vue template, this is done by configuring Webpack to convert assets to base64 data uris and yes, you are right, that's configured in [vue.config.js](https://github.com/wailsapp/wails/blob/master/cmd/templates/vuebasic/frontend/vue.config.js). According to [this post](https://stackoverflow.com/a/52822528), create-react-app will only bundle images that are less than 10k by default. If you look at the vue.config.js file, you'll see I've set those limits really high so that all (reasonably!) sized images get bundled. 
My guess is that you need to 'eject' the react app, configure webpack for bundling everything and rebuild. The ejected config then becomes part of your template.

**Comment by bh90210** [comment]
hmmmm thanks for the clue, will look in to it asap.
Generally speaking I would the leave the eject option for the user to decide when to use it, so I will try to find a workaround.

**Comment by bh90210** [comment]
some success but overall still black screen am afraid. 

The suggested solution for custom configs without ejecting is forking `react-scripts`, modify the configs or whatever, npm publish. So here it is [npm package](https://www.npmjs.com/settings/bh90210/packages) ([github rep](https://github.com/bh90210/wails-react-scripts)). Now it properly turns images etc to bytes, a question though. If I use ie. a video file with your solution as implemented on Vue Basic I will error right?

Also I am kind of stuck. I literally have tried everything. I can not really figure what it can be.
I am serving over the net the same files that wails is supposed to serve and again it doesn't work. https://xn--jpa-fma.com/

For whatever reason when I serve the project locally is alright. I  have to investigate a bit more the webpack config I guess.  

Also two notes: a. when serving locally I can see wailsbridge splash screen, which is good.
I also get this warning:
```
Compiled with warnings.

./src/wailsbridge.js
  Line 163:  Expected a default case  default-case

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

that's all for now, when I have something new I post the update.

**Comment by bh90210** [comment]
edit: actually serving the build files over the internet it works. https://xn--jpa-fma.com/ 
I realised I had to remove `wailsbridge.js` in order to work. Hence I can at least confirm that the problem is not the build.

Do you think maybe the problem is with wails?

**Comment by leaanthony** [comment]
I can almost guarantee that the reason is still that the bundle doesn't contain all the assets. Have you run it in debug mode then opened the inspector and checked if there are any network requests? BTW, the screenshot looks cool so let's get this working :-)

I'm not familiar with react (at least in the past 4 years) but I'll have a look and see what I see.

**Comment by bh90210** [comment]
yes you were right.

just for future reference what I did with react-scripts was correct. the problem was with how I was rendering reactDOM in App.js

super trivial error 
default Create React App boilerplate looking for `<div id="root">`
```
Bridge.Start(() => {
  ReactDOM.render(<App />, document.getElementById('root'));
});
```

instead of 
```
Bridge.Start(() => {
  ReactDOM.render(<App />, document.getElementById('app'));
});
```
![wails_working](https://user-images.githubusercontent.com/22690219/59394693-56ee3b00-8d89-11e9-83da-8a1d59edee2e.png)
