### ISSUE TITLE
[v2]When EnableFramelessBorder is true, the minimize, maximize and close buttons are invalid

### ISSUE THREAD

**Issue by jwjlly** [wailsapp/wails#1150]
![image](https://user-images.githubusercontent.com/17535968/154014883-5c56f609-0903-4a02-9b40-b4e4de65e7fd.png)

**Comment by stffabi** [comment]
Thanks for your issue. I suspect it might be related to transparency.

Could you please specify the output of `wails doctor` and also provide your `main.go` file with your settings? This would allow us to narrow down the issue. Thanks.

**Comment by lyaf** [comment]
I think it's the Resize that's affecting it, causing it not to respond to the custom button practice on the edge of the form, try DisableResize: true

**Comment by stffabi** [comment]
I've just tried `DisableResize: true` and `EnableFramelessBorder: true` but unfortunately I can't reproduce it. Are you using `WindowIsTranslucent:   true`?

The buttons should never be shown if `Frameless: true`.

**Comment by leaanthony** [comment]
IIRC it looks like this when you remove the window icon + translucency+ transparency

**Comment by stffabi** [comment]
Yeah, it seems like translucency + transparency triggers the buttons to be shown if `Frameless: true`.  Seems like changing the margins for `dwmExtendFrameIntoClientArea` to 1 fixes that.

**Comment by stffabi** [comment]
@layxyer could you please RR #1152 a try? That should fix the problem.

**Comment by layxyer** [comment]
@stffabi After using [#1152](https://github.com/wailsapp/wails/pull/1152), the title button is not displayed

**Comment by stffabi** [comment]
Great, thanks so much for testing the PR.
