### ISSUE TITLE
Single source of truth for manifest data

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#1155]
**Is your feature request related to a problem? Please describe.**
Maintaining OS specific "manifest" (`darwin/Info.plist`, `windows/<project>.exe.manifest`, `windows/info.json`) is a bit tedious, especially because they contain a lot of duplication. And updating them is error prone.

**Describe the solution you'd like**
Having a single source of truth, such as `wails.json`, that will be used to populate the content of these manifests.

This will require the `ProjectData` to be used to generate a default configuration for each OS. If a manifest already exists, and that the common properties are defined then the manifest values takes precedence. Basically, a merge.

So, during packaging:
1. No manifest -> auto-generation from `wails.json`
2. Existing manifest -> merge with priority to the manifest values.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

_Of course, if I can help getting this done..._ :)

**Comment by leaanthony** [comment]
It's a good suggestion. Will happily accept a PR for this 👍
