### ISSUE TITLE
On button click inside form element, the whole app refreshes. 

### ISSUE THREAD

**Issue by annikovk** [wailsapp/wails#1162]
**Description**
I have a form with a button inside, e.g: 

```html
  <form>
    <button>form</button>
  </form>
```

Once I click the button, the App refreshes. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Init a project from sample: 
```bash
wails init -n myproject
```
2. Add form with button to the body of index.html. So, whole body will look like: 
```html
<body data-wails-drag>
  <div class="logo"></div>
  <div class="result" id="result">Please enter your name below 👇</div>
  <div class="input-box" id="input" data-wails-no-drag>
    <input class="input" id="name" type="text" autocomplete="off">
    <button class="btn" onclick="greet()">Greet</button>
  </div>
  <form>
    <button>form</button>
  </form>
  <script src="/main.js"></script>
</body>
```
3. Run the app, enter your name into Greet button
4. You see that the name is displayed as `Hello Konstantin. It's show time`
5. Click on the added button within the form. 
6.  Greet `Hello Konstantin. It's show time` disappears. `Please enter your name below` is shown instead. 

**Expected behaviour**
Greet `Hello Konstantin. It's show time` remains untouched 

**System Details**
```bash
wails doctor
Wails CLI v2.0.0-beta.30


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.2
ID:             199506
Go Version:     go1.17.6
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2392
npm                             N/A             Installed       8.4.1
*upx                            N/A             Available       

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

**Comment by leaanthony** [comment]
Please state how this is a bug. Form submission will refresh the page. Perhaps use a different solution for submitting data?

**Comment by annikovk** [comment]
Wow, such a great response time, thank you. 

Of course, I will use another solution for submitting data now. 
But it is not expected for me (and for any plain HTML page opened in any browser) that form refreshes the page. 

I spent a lot of time to realise that the cause is not my JavaScript or App configuration.

**Comment by leaanthony** [comment]
Yeah, if you use a form tag, the page will refresh after a submit, that's how forms work. More information here: https://stackoverflow.com/questions/27018422/prevent-page-from-reloading-after-form-submit
