### ISSUE TITLE
[v2]An error occurs when creating a new project with a template generated by the Generate Template command

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1165]
**Description**
Using the template generated by the `wails generate template` command to create a new project will cause errors in the generated project file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails generate template wails-template-demo`
2. Run `wails init -n Wails-Demo -t ./wails-template-demo`
3. Run `wails dev`

**Expected behaviour**
It is hoped that the steps of the third step can be optimized so that the program can run the build process correctly.

**Screenshots**
This is the file generated after running the `wails dev` command.
![image](https://user-images.githubusercontent.com/28185258/154869357-a3533dce-2021-4baf-adbc-8ded3779ff60.png)
![动画](https://user-images.githubusercontent.com/28185258/155225649-3b81cb30-d0d2-4d63-afa1-fbe5e1c61258.gif)

**System Details**
```shell
$ wails doctor
Wails CLI v2.0.0-beta.30


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       98.0.1108.56
npm             N/A             Installed       8.5.1
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Additional context**
As to why this error occurs, I'm guessing because running `wails dev` causes the `frontend:install` command in `wails.json` to be run, which is supposed to be in `frontend` directory operation, probably because `wails` does not limit the directory, so this command is run in the project root directory, so unnecessary files (`package-lock.json` and `node_modules` directories) are generated.

There are two suggestions for a solution to this problem:
1. Optimize the `wails dev` and `wails build` commands so that they can correctly identify the directory where the front-end project is located instead of the `package.json` file in all directories. For example, you can set a field to specify the directory where the front-end project is located.
2. The project build script files are uniformly moved to the `scripts` directory in the root directory.

**Comment by bh90210** [comment]
I can not reproduce the problem on linux.
I do
1. `wails generate template -name test`
2. `wails init -n testit -t ./test`
3. `cd testit`
4. `wails dev`

![image](https://user-images.githubusercontent.com/22690219/155207883-afb237b9-65ec-4bf9-842f-e94cf06ae151.png)

**Comment by misitebao** [comment]
@bh90210 
This problem occurs on the windows platform. The reason for the problem is that `wails dev` found a `package.json` file in the root directory, so it ran `npm install`, so this problem will occur, if you try to run in the root directory `npm install`, you will see the content as shown in the figure.

**Comment by misitebao** [comment]
@leaanthony 
Take a look at this question.

**Comment by misitebao** [comment]
@leaanthony 
It should be noted that even if the script is changed from `npm script` to `shell`, the wails cli tool still has an essential problem. It should look for the existence of a `package.json` file in the `frontend` directory and execute the command, instead of in the project root directory.

**Comment by Snider** [comment]
@leaanthony @misitebao 

I don't understand the bug. Does this have an error output or is it developer preference? 

node_module aggregation is the expected behaviour of workspaces, using workspaces creates global  node_modules for better dependency management; 

It should work in `cmd.exe`, not just git bash etc so I'm not sure replacing NPM is an answer, but id loves to talk over some data.

If it's causing an issue id vote to remove the `package.json` as it was meant to "be helpful" to others; within a format, they are already used to; nodejs's package.json

but yea, it all good to remove if it's not helping the majority.

**Comment by leaanthony** [comment]
It's been reported that the cli is trying to run `npm install` on it and failing but I haven't confirmed this yet.

**Comment by misitebao** [comment]
@Snider @leaanthony 
Whether to use `shell script` to replace `npm script` is not the point, even if not, there is no problem. The point of the problem is that `wails dev` should not execute `npm install` in the project directory, but should be in the `frontend` directory

**Comment by leaanthony** [comment]
I think it would have been quicker to just raise a PR that fixed the issue if you know where it is? I'm happy for `wails dev` to not do this, if it's doing it

**Comment by Snider** [comment]
It's how that is meant to work,

A global node_modules is the point of workspaces; it reduces duplicate packages stored on the filesystem, I can see why the folder location can affect some people.

remove it. all good.

**Comment by misitebao** [comment]
@Snider @leaanthony 
Sorry, I see the reason for the problem, it's not a `wails dev` problem.

**Comment by leaanthony** [comment]
What is the problem?

**Comment by misitebao** [comment]
@leaanthony 
As @Snider  said, dependencies installed by projects in the `workspace` directory will be stored in the directory where the `workspace` is defined. So executing `npm install` in the `frontend` directory will save the `node_modules` in the directory where the `workspace` is defined, which is the root directory of the project.
