### ISSUE TITLE
unexpected behavior for "frontend:dev" config option, does not run concurrently

### ISSUE THREAD

**Issue by quinn** [wailsapp/wails#1169]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
The documentation for this field is as follows:

```
"[This command is run in a separate process on `wails dev`. Useful for 3rd party watchers]",
```

To me, this sets up the expectation that this command will run _concurrently_ with `wails dev`. Especially considering the example given is "3rd party watchers".  most watcher scripts will launch and never exit, watching for changes.

I'd be happy to give a PR for this change, if someone can give me a jumping off point in the source code. thank you!

**Comment by misitebao** [comment]
I think it's the same problem(https://github.com/wailsapp/wails/issues/1009), but it hasn't been fixed yet.

**Comment by quinn** [comment]
your issue seems like its about an unrelated problem with vite? But, if the vite command did succeed, it would also run into the problem i've mentioned here.  I have a similar setup, in my case i am using esbuild. @misitebao have you looked into how this could be implemented yet?

**Comment by quinn** [comment]
it looks like the command IS run in a goroutine:

https://github.com/wailsapp/wails/blob/fe224d9ecdec073f16695320535ba6ff78f0abff/v2/cmd/wails/internal/commands/dev/dev.go#L390-L399

so not sure what is missing here. must be something about how that waitgroup is configured:
https://github.com/wailsapp/wails/blob/fe224d9ecdec073f16695320535ba6ff78f0abff/v2/cmd/wails/internal/commands/dev/dev.go#L398

Also, I am running this on Windows. this doesn't seem like it is a windows-only problem, but worth mentioning

**Comment by quinn** [comment]
digging into this more, it seems like this wait group wouldn't block until here: 

https://github.com/wailsapp/wails/blob/fe224d9ecdec073f16695320535ba6ff78f0abff/v2/cmd/wails/internal/commands/dev/dev.go#L419

which is deferred:

https://github.com/wailsapp/wails/blob/fe224d9ecdec073f16695320535ba6ff78f0abff/v2/cmd/wails/internal/commands/dev/dev.go#L157

so yeah, everything seems to indicate that the `frontend:dev` command _wouldn't_ block execution?

**Comment by misitebao** [comment]
@quinn 
Yes, the command shouldn't be blocking, but it is currently blocking, so it needs to be fixed.

**Comment by stffabi** [comment]
I think the problem is later during the build process. During the building of the frontend the same `frontend:dev` command is used. If that's blocking then the compiling of the frontend does block.

https://github.com/wailsapp/wails/blob/91934d1f8e728bc4320058cc07484fbd0c8cd829/v2/pkg/commands/build/base.go#L578-L598

I don't know what was the intention here, maybe there should be another option like `frontend:devbuild` used here or just always `frontend:build`. @leaanthony what do you think?

**Comment by leaanthony** [comment]
It is the equivalent of `frontend:build` but for dev mode. The docs are wrong. I will change this.

**Comment by stffabi** [comment]
Isn't the "watcher" case already supported here, that command is run in a separate goroutine and is also stopped at the end of the "wails dev" command?

https://github.com/wailsapp/wails/blob/91934d1f8e728bc4320058cc07484fbd0c8cd829/v2/cmd/wails/internal/commands/dev/dev.go#L153-L158

**Comment by stffabi** [comment]
@misitebao and @quinn could you please both give PR #1170 a try? There's a new command `frontend:dev:watcher` which is run nonblocking and should work in your cases.
