### ISSUE TITLE
Suggestions for handling when Wails cannot find the `index.html` file

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1175]
**Description**
This is a suggestion for when wails can't find the index.html file. Strictly speaking, it is not a bug, but it does make the program report an error. It can be regarded as a small defect. I think I may need to A better way to avoid it.

I encountered this problem when testing @stffabi 's `PR` about `frontend:dev:watcher`(#1170). The frontend listening and rebuilding will cause the `dist` directory to be empty for a short time (this depends on the efficiency of the frontend build tool). At this time There is no `index.html` file. At this time, the wails window will report an error, indicating that the file cannot be found, but the current resource reconstruction is completed, and the window is still in an error state.

Although this problem can be solved by modifying the `debounceMS` value in the `wails.json` file to a larger value, such as making it larger than when the front-end resources are rebuilt, but I think this is not an elegant way, the most At least it shouldn't report an error when the `index.html` file is not found. Maybe you can use a default page like the website's 404 page to prompt the user if a new `index. html` file, it should return to normal instead of continuing to show window errors.

**To Reproduce**
Steps to reproduce the behaviour:
Pull the code branch mentioned in (https://github.com/wailsapp/wails/pull/1170), compile the cli tool and switch the go mod dependency to this directory.
1. Run `wails init -n wails-demo -t https://github.com/misitebao/wails-template-vue`
2. Add `"frontend:dev:watcher":"npm run build:watch -w js"` to the `wails.json` file.
3. Run `wails dev`
4. Modify any file in the `fontend/JS` directory to trigger a frontend rebuild.

If you change the `debounceMS` value in the `wails.json` file to 3000 to make it greater than the front-end rebuild time, the program will run as usual. (Because this template uses vite to build the front end, the build time is very short. If webpack is used, the value here needs to be set larger to ensure that no errors occur)

**Expected behaviour**
I hope that when the `index.html` file cannot be found, a built-in default page or native UI display (even a solid color without text) can be used, and when the `index.html` file is found, it can be displayed normally, and Instead of showing the error window directly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/155209971-54cc7d65-ea0a-4955-8dcd-8406b04696ef.png)

**System Details**
V2 users: Please add the output of `wails doctor`.
```shell
misitebao@MISITEBAO-BOOK MINGW64 ~
$ wails doctor
Wails CLI v2.0.0-beta.30

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       98.0.1108.56
npm             N/A             Installed       8.5.1
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Additional context**
None.

**Comment by leaanthony** [comment]
I like this idea a lot. I will create a default 404 page that reloads every 1s, how about that?

**Comment by leaanthony** [comment]
Is this for just the browser or the app as well? It gets tricky for the app as we try to infer the directory from the location of the html. Please explain the scenario.

**Comment by misitebao** [comment]
@leaanthony 
It should be noted that this prompt should be built in by wails. It has nothing to do with front-end projects. It should only be displayed when wails cannot find the `index.html` file. The main reason for this is: when `index.html` `When the file reappears, the window can immediately return to the normal state, instead of continuing to stay in a suspended state.

**Comment by misitebao** [comment]
@leaanthony 
By the way, if I do this, will it solve the problem that the `index.html` file must exist in the dist directory when the project is run for the first time?

**Comment by leaanthony** [comment]
When I generate the project, `package.json` seems incorrect: No build script, cp doesn't work on Windows.

**Comment by misitebao** [comment]
> When I generate the project, `package.json` seems incorrect: No build script, cp doesn't work on Windows.

Sorry, I didn't understand what you meant.

**Comment by leaanthony** [comment]
Has the project been updated? Does it work now?

**Comment by misitebao** [comment]
@leaanthony 
The problem still exists, I want to know if there is no `index.html` file, can you not let the program freeze?

**Comment by leaanthony** [comment]
I have a branch for this but it's trickier than you think.

**Comment by leaanthony** [comment]
@misitebao - Please try https://github.com/wailsapp/wails/pull/1229

**Comment by leaanthony** [comment]
I've pushed a small update which means all assets are treated in the same way.
