### ISSUE TITLE
Question: dose it support copy and paste?

### ISSUE THREAD

**Issue by yeqown** [wailsapp/wails#1185]
I tried in my frontend but it takes no effect at all.

|property|value|
|-----|-------|
|wails-version|v2.0.0-beta.30|
|machine|MacOS 12.2.1 (21D62)|
|go|1.17.3|
|vue|v3|
|souce code|https://github.com/yeqown/apollo-synchronizer/tree/feature/gui/cmd/gui|

I searched some keywords like: https://github.com/wailsapp/wails/search?q=paste, but I have no idea about its meaning and what should I do. 

Thanks for your reply.

**Comment by leaanthony** [comment]
If it's in the menu it should work 👍

**Comment by yeqown** [comment]
Should I define the `Ctrl+C` keyboard shortcut in my menu item?

**Comment by leaanthony** [comment]
Try using "edit" menu role: https://wails.io/docs/reference/menus#role

**Comment by yeqown** [comment]
@leaanthony thanks, it's resolved

```go
mymenu := menu.NewMenuFromItems(
		menu.EditMenu(), // this worked
	)
```
