### ISSUE TITLE
[V2] Build not working but dev works

### ISSUE THREAD

**Issue by IrishBruse** [wailsapp/wails#1187]
**Description**
My wails app works fine in dev but when I build it its a white screen and there is no errors to indicate anything went wrong. I even ran it with `wails build -debug`
I'm using angular as my frontend.

**To Reproduce**
https://github.com/IrishBruse/Launcher
Run `wails build`
Then this is the output
![image](https://user-images.githubusercontent.com/14964651/155751383-195c8d64-5cae-43c8-ba41-1a7fd529e018.png)

**Expected behavior**
My app to work the same as in dev mode.

**Screenshots**
Dev is working fine
![image](https://user-images.githubusercontent.com/14964651/155751633-7fb4b078-0eb4-431e-939f-db390c9103ce.png)

**Comment by stffabi** [comment]
I suspect the problem is that in the main.go file the assets are embedded from 'frontend/src' whereas the generated output of the frontend is placed in 'frontend/dist'.

Could you try changing that to 'frontend/dist'?

**Comment by leaanthony** [comment]
Yup, looks about right:  
 ​//go:embed frontend/src

**Comment by IrishBruse** [comment]
Yup that fixed it thanks.
Strange that it works in dev some sort of warning message might be useful if thats even possible or just some sort of doc on it.

**Comment by leaanthony** [comment]
Impossible to warn unless we do static code analysis. Defo can add to a troubleshooting guide though
