### ISSUE TITLE
[V2] Add an Option to Disable the Three Dots Menu When Select Text in WebView2

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1188]
**Is your feature request related to a problem? Please describe.**
Can we have an option to disable the three dots menu in Webview2. It's kind of annoying don't you all agree?

**Describe the solution you'd like**
There are some [discussion ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2191) about it you can look at.
[This](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2140#issuecomment-1033148445) might be the solution here.

**Additional context**
Image show that menu pop up when user select text:
![Untitled](https://user-images.githubusercontent.com/28552977/155767695-bf48e702-974b-497d-92ad-9ecabc58d6e0.png)

**Comment by leaanthony** [comment]
This does not appear to be an issue for production builds: `wails build` -> does not appear

**Comment by KiddoV** [comment]
@leaanthony you are right. It does not appear in the binary version. I thought I was seeing it in the binary, but it was not. False call!
Thanks!
