### ISSUE TITLE
Wails dev not refreshing with code changes (or at all)

### ISSUE THREAD

**Issue by DrGylfin** [wailsapp/wails#1189]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
`wails dev` reports that it's listening to the correct directory, but it doesn't refresh the web page or re-run the app when files change.  No errors are reported by ``wails dev``.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a project
2. Run `wails dev` in the project directly
3. Change any of the files in that directory, e.g. ``main.go`` 

**Expected behaviour**
The app refreshes or re-runs itself

**System Details**
```
System
------
OS:		MacOS
Version: 	12.2.1
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.3.1
*upx 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Cannot reproduce - sorry. Did you try the latest version?

**Comment by DrGylfin** [comment]
As far as I know I am ... I installed it via the CLI (per the steps in the readme), and ``wails update`` says there's no new update.

**Comment by leaanthony** [comment]
Try `wails update -pre`

**Comment by DrGylfin** [comment]
I've updated to beta 33 (and I'm also using go 1.18 now), but the issue remains.
