### ISSUE TITLE
Init fails on Arch linux

### ISSUE THREAD

**Issue by arjanvaneersel** [wailsapp/wails#119]
**Description**

When I run 'wails init' on Arch linux the command fails with the error "Error: unable to check libraries on distribution ''. Please ensure that the 'libgtk-3-dev' equivalent is installed"

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'wails init' on Arch linux. I ran the command in an empty directory for the project
2. See error

**Expected behaviour**
Expected the project to be initialized

**Screenshots**
Sent by slack

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.15.0 |
| Go Version    | go1.12.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Additional context**

**Comment by leaanthony** [comment]
Looking at this now

**Comment by leaanthony** [comment]
This is fixed in the develop branch. The fix will be out in v0.16.0. Thanks for highlighting this! Please close if you are happy that this is fixed.

**Comment by leaanthony** [comment]
v0.16.0 released that should fix this @arjanvaneersel

**Comment by leaanthony** [comment]
Fixed.
