### ISSUE TITLE
Build failing when trying crossplatform (wails build -x windows/amd64)

### ISSUE THREAD

**Issue by NeuralAIO** [wailsapp/wails#1190]
**Description**

I am creating a production build for my application on macOS, however, when attempting to do a crossplatform build as instructed in the wails documentation, I am met with a few errors, including "/build/myappname.rc: No such file or directory" and "x86_64-w64-mingw32-gcc: fatal error: no input files" causing the "preprocessing" to fail. I have Docker installed and I have already pulled the wailsapp/xgo.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a project
2. docker pull wailsapp/xgo
3. Run `wails build -x windows/amd64`
4. Error should be in terminal

**Expected behaviour**
A windows executable should have been outputted from the command

**Screenshots**
<img width="672" alt="image" src="https://user-images.githubusercontent.com/80505318/155813212-d33c7cd1-7a71-48c0-a310-ddc5c6a0ed5f.png">

**System Details**
```
System
------
OS:		MacOS
Version: 	11.6
Go Version:	go1.16.3
Platform:	darwin
Architecture:	amd64
```

**Comment by leaanthony** [comment]
Yes, cross compilation doesn't work for v1 any more. It is highly recommended to use V2 as you wouldn't need to use a cross compiler for Windows 👍

**Comment by NeuralAIO** [comment]
With v2, does it automatically create a production build for all platforms? For example, if I was building on macOS, it would compile for Windows as well?

**Comment by stffabi** [comment]
With v2 you can instruct it to build multiple platforms, e.g. when running on MacOS:

'wails build --platform windows/amd64,darwin/universal'

This will build the project for MacOS and for Windows.

**Comment by leaanthony** [comment]
You can cross compile to host + Windows. Looking at getting full cross-compilation done.
