### ISSUE TITLE
Window Focus API?

### ISSUE THREAD

**Issue by horacehylee** [wailsapp/wails#1193]
**Is your feature request related to a problem? Please describe.**
Could we have an API managing the window's focus?
Such we can have hidden application show and grab the focus directly.

**Describe the solution you'd like**
Want to have WindowSetFocus API to runtime

**Comment by leaanthony** [comment]
Are you saying WindowShow() doesn't focus?

**Comment by horacehylee** [comment]
I am using Windows 10

Yes `WindowShow()` does not focus on the window.

And if I minimize the window, when I called `WindowShow` it does not show the minimized window

**Comment by leaanthony** [comment]
Well, that's a straight out bug. Please open a ticket with steps to reproduce 👍

**Comment by leaanthony** [comment]
@horacehylee - Can you please try this PR to see if that works for you? Thanks.
https://github.com/wailsapp/wails/pull/1212

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by dzpt** [comment]
@leaanthony then how do i know the app is focused or not?

**Comment by leaanthony** [comment]
That's a different question to the original ticket. It's worth opening a new ticket for that enhancement 👍

**Comment by whity** [comment]
Hello @leaanthony ,

I'm still facing this, my use case is, the app/window starts hidden `StartHidden: true` and it's only activated/shown when an hotkey is pressed.
The showning of the app/window works nice, but it's never focused, how can I force that?

Thanks

**Comment by Vaasu-Dhand** [comment]
I'm having the same issue :(
