### ISSUE TITLE
[V2] Add Vue3 JS Template

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1196]
Can you add vue3 js template for wails v2? Not too many templates for v2 atm.

I know we can pull from the third-party templates, but it would be nice to have it built-in.

Thanks!

**Comment by leaanthony** [comment]
Hi @KiddoV - v2 will only have the current templates as maintaining templates takes away from core development. Why not create your own? https://wails.io/docs/guides/templates
