### ISSUE TITLE
集成gin后不能正常请求

### ISSUE THREAD

**Issue by zhangya4548** [wailsapp/wails#1197]
### 集成`gin`后
```
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
)

// App struct
type App struct {
	ctx context.Context
	h *http.Server
}

// NewApp creates a new App application struct
// NewApp 创建一个新的 App 应用程序
func NewApp() *App {
	return &App{}
}

type Home struct {
	Uri string `json:"uri"`
	Dir string `json:"dir"`
}

// startup is called at application startup
// startup 在应用程序启动时调用
func (a *App) startup(ctx context.Context) {
	// Perform your setup here
	// 在这里执行初始化设置
	a.ctx = ctx

	// 实例化gin
	r := gin.New()
	//开启中间件 允许使用跨域请求
	// r.Use(Cors())

	//模型绑定/参数验证 curl -g "http://localhost:9999/login" -H "content-type: application/json" -X POST -d '{ "user": "admin", "password":"123456" }'
	r.POST("/home", func(c *gin.Context) {
		var home Home
		if err := c.ShouldBindJSON(&home); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
			return
		}
		// if home.Uri != "admin" || home.Dir != "123456"{
		// 	c.JSON(http.StatusBadRequest, gin.H{"error":"参数错误"})
		// 	return
		// }
		c.JSON(http.StatusOK, gin.H{"msg":"成功","data":home.Uri})
	})

	srv := &http.Server{
		Addr:    ":9999",
		Handler: r,
	}
	a.h = srv

	go func() {
		if err := a.h.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("gin监听: %s\n", err)
		}
	}()
}

// domReady is called after the front-end dom has been loaded
// domReady 在前端Dom加载完毕后调用
func (a *App) domReady(ctx context.Context) {
	// Add your action here
	// 在这里添加你的操作
}

// beforeClose is called when the application is about to quit,
// either by clicking the window close button or calling runtime.Quit.
// Returning true will cause the application to continue,
// false will continue shutdown as normal.
// beforeClose在单击窗口关闭按钮或调用runtime.Quit即将退出应用程序时被调用.
// 返回 true 将导致应用程序继续，false 将继续正常关闭。
func (a *App) beforeClose(ctx context.Context) (prevent bool) {
	return false
}

// shutdown is called at application termination
// 在应用程序终止时被调用
func (a *App) shutdown(ctx context.Context) {
	// Perform your teardown here
	// 在此处做一些资源释放的操作
	if err := a.h.Shutdown(ctx); err != nil {
		log.Fatal("gin退出异常:", err)
	}
}
```
### 前端直接通过`npm run dev`启动在浏览器调试能正常请求`gin`接口成功
<img width="1020" alt="1111111" src="https://user-images.githubusercontent.com/8876518/156198342-c4cc1ddf-9938-419c-a766-05b427c9e78f.png">

### 但是直接在`wails`程序中调试看到不能请求`gin`接口
<img width="838" alt="33333" src="https://user-images.githubusercontent.com/8876518/156198391-b1cf1563-a490-44f2-a1c9-34dd95efe587.png">
<img width="813" alt="2222222" src="https://user-images.githubusercontent.com/8876518/156198398-fabebcf8-c53f-4dee-a136-dee8d54f347c.png">

### 请问下这时为何

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`

**Comment by crushonyou18** [comment]
Can you provide the output of `axios.post().catch`?
(可以提供`axios.post().catch`的输出结果吗？)

**Comment by zhangya4548** [comment]
我把代码都放github了 https://github.com/zhangya4548/wails_demo

**Comment by leaanthony** [comment]
Hi! There hasn't been enough feedback on this issue which suggests it might not be a problem any more. Please reopen if you still have the time to discuss 👍

**Comment by zhangya4548** [comment]
> Hi! There hasn't been enough feedback on this issue which suggests it might not be a problem any more. Please reopen if you still have the time to discuss 👍

😢

**Comment by crismcn** [comment]
GET IS OK
Others POST PUT... IS FAILS
![image](https://github.com/wailsapp/wails/assets/43445354/154aed0a-cd1b-458c-b80d-d5be772516a7)
![image](https://github.com/wailsapp/wails/assets/43445354/0208f49e-fc1a-4851-86fa-0d8dd1cf7726)

**Comment by crismcn** [comment]
属于用wails机制的问题&nbsp; gin服务单独起个端口&nbsp;


Crism
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月20日(星期三) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wailsapp/wails] 集成gin后不能正常请求 (Issue #1197)














 
解决了吗？估计是Gin阻塞了吧
