### ISSUE TITLE
[v2] App is not running after build.

### ISSUE THREAD

**Issue by jk43** [wailsapp/wails#1202]
Everything works fine on dev mode by "wails dev" but I am getting the following error running app by "wails build"

Last login: Wed Mar  2 17:07:20 on ttys005
/Volumes/Development/Workspaces/go/sestemplatemanager/build/bin/SES\ Template\ Manger.app/Contents/MacOS/SES\ Template\ Manger ; exit;
Now using version go1.17.4
Now using node v16.13.1 (npm v8.1.2)
❯ /Volumes/Development/Workspaces/go/sestemplatemanager/build/bin/SES\ Template\ Manger.app/Contents/MacOS/SES\ Template\ Manger ; exit;
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/fs.FindPathToFile({0x4577cc0, 0x4591140}, {0x44cf2f6, 0xa})
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/fs/fs.go:430 +0x165
github.com/wailsapp/wails/v2/internal/frontend/assetserver.prepareAssetsForServing({0x4577cc0, 0x4591140})
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/assetserver/assetserver_common.go:15 +0x57
github.com/wailsapp/wails/v2/internal/frontend/assetserver.NewDesktopAssetServer({0x4582fe0, 0xc0001ec870}, {0x4577cc0, 0x4591140}, {0xc0001f6500, 0x49a})
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/assetserver/assetserver_desktop.go:29 +0xe5
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.NewFrontend({0x4582fe0, 0xc0001ec870}, 0xc0001342a0, 0xc00000ec00, 0xc0001e40c0, {0x45771c0, 0xc0001ec7e0})
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/desktop/darwin/frontend.go:85 +0x1d0
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/desktop/desktop_darwin.go:19
github.com/wailsapp/wails/v2/internal/appng.CreateApp(0xc0001342a0)
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/appng/app_production.go:91 +0x50b
github.com/wailsapp/wails/v2.Run(0xc0000001a0)
	/Users/hotdev/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/wails.go:19 +0x19
main.main()
	/Users/hotdev/Development/go/sestemplatemanager/main.go:26 +0x38f

Saving session...completed.

===========================
❯ wails doctor
Wails CLI v2.0.0-beta.32

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.0.1
ID:             199506
Go Version:     go1.17.4
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2392
npm                             N/A             Installed       8.1.2
*upx                            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

**Comment by stffabi** [comment]
The current master branch should output a better error message and not panic.

It seems like the index.html file can't be found. Could you please check your main.go file if the correct folder is embedded for the assets? See also https://wails.io/docs/guides/troubleshooting#my-application-is-displaying-a-whiteblank-screen for a more detailed guide.

**Comment by jk43** [comment]
Working well after //go:embed frontend/src to //go:embed frontend/dist on main.go.
