### ISSUE TITLE
[v2 BUG]: Cannot use runtime methods in ondom ready in an application produced by wails build (wails dev is fine)

### ISSUE THREAD

**Issue by KoduIsGreat** [wailsapp/wails#1206]
**Description**
Hi again! 
when running  a program that was compiled with wails build, that uses runtime methods in the ondomready lifecycle hook
the program immediately crashes with the following error:
 14:42:58 cannot call 'github.com/wailsapp/wails/v2/pkg/runtime.LogInfo': An invalid context was passed. This method requires the specific context given in the lifecycle hooks: https://wails.io/docs/reference/runtime/intro
 
from looking at the code it looks like the value from the context is nil, and thus the fatal error. 

important to note, wails dev is OK and no error is reported and application starts.
So i guess the question is why does it fail for build and not dev?

I have tested this with beta.32 
I have tested this with "bleeding edge" as described here : https://wails.io/docs/guides/bleeding-edge
I have tested this on MacOS 12.0.1 (M1 chip) and Windows 10 Pro (AMD)
I have attached a doctor for both cases below

In the case of windows, no error is reported but the window flashes and immediately closes

**To Reproduce**
I have created a repo that reproduces this issue please follow the below steps to see the error
1. git clone https://github.com/KoduIsGreat/wails-runtime-context
2. `cd wails-runtime-context`
3. `wails build -clean -noPackage`
4. `./build/bin/wails-runtime-context`
5. see error

**Expected behaviour**
The application starts and does not crash.

**Screenshots**

**System Details**

# Mac doctor
Wails CLI v2.0.0-beta.32

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.0.1
ID:             199506
Go Version:     go1.17.2
Platform:       darwin
Architecture:   arm64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2392
npm                             N/A             Installed       8.1.0
*upx                            N/A             Available       

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

# Windows doctor
Wails CLI v2.0.0-beta.32

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.3
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       98.0.1108.62
npm             N/A             Installed       6.14.6
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

**Additional context**

**Comment by leaanthony** [comment]
I generated a new app, added a call to message dialog and it works:
![image](https://user-images.githubusercontent.com/1943904/156656079-36a7d46a-a216-4ce5-aa59-78cd0a588789.png)
Is there something else you're doing here? Does the context passed to the method work?

**Comment by KoduIsGreat** [comment]
I did try context passed to method as well as b.ctx and neither worked.

**Comment by KoduIsGreat** [comment]
@leaanthony Okay so it seems like its limited to runtime.LogXXX 

The message dialog works for me but log does not

**Comment by leaanthony** [comment]
Ok, this is because the logger isn't set when building in Production mode (which `wails build` will do). I wouldn't expect a crash, but then I wouldn't expect it to be logging either. Did you mean to log in a production build?

**Comment by leaanthony** [comment]
Fixed by setting the log level to ERROR instead of removing the logger. Change is on master 👍
