### ISSUE TITLE
[v2 linux-arm64] runtime.WindowFullscreen results in tiny window rather than fullscreen window

### ISSUE THREAD

**Issue by ianmjones** [wailsapp/wails#1207]
**Description**

When using the `window.runtime.WindowFullscreen();` JS function on an arm64 machine running Ubuntu 21.10, the window ends up as a tiny slither rather than going fullscreen.

Using the same code on an amd64 machine running either EndeavourOS (Arch Linux) or NixOS does not exhibit the same issue and the window goes fullscreen.

This was found while testing PR #1200, both before and after the changes made to the `Fullscreen` function in `v2/internal/frontend/desktop/linux/window.go`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a demo project with `wails init -t svelte -n oopsadaisy`
2. Edit the `frontend/src/App.svelte` to add a function that calls the `window.runtime.WindowFullscreen()` function, and a button to trigger it. (see diff in screenshots)
3. `wails dev`
4. Click the "Fullscreen" button.
5. The window ends up looking like it has disappeared, until you spot the slither of a window.

**Expected behaviour**

The window should be made fullscreen.

**Screenshots**

![Screenshot from 2022-03-03 21-09-10](https://user-images.githubusercontent.com/4710/156654036-b7da0331-4d95-45bb-a666-84756e18bc4d.png)

![Screenshot from 2022-03-03 21-09-21](https://user-images.githubusercontent.com/4710/156654061-b895027e-eb0e-4323-9ada-72d499d068cc.png)

**System Details**

```
Wails CLI v2.0.0-beta.32

System
------
OS:                     Ubuntu
Version:                21.10
ID:                     ubuntu
Go Version:             go1.17
Platform:               linux
Architecture:           arm64
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Available       20.10.7-0ubuntu5.1
gcc             build-essential         Installed       12.9ubuntu2
libgtk-3        libgtk-3-dev            Installed       3.24.30-1ubuntu1
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.34.6-0ubuntu0.21.10.1
npm             npm                     Installed       7.5.2
pkg-config      pkg-config              Installed       0.29.2-1ubuntu1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - docker: sudo apt install docker.io
```

**Additional context**

To be able to run the demo app a local checkout of the branch for PR #1200 must be used as the replacement in the go.mod file otherwise the app crashes on start.

**Comment by leaanthony** [comment]
+1 for the project name :-) I have a suspicion this is related to MAX_INT and screensize calculation.

**Comment by ianmjones** [comment]
Aye, I wonder if there's some other more "GTK" method of doing it? Maybe something like setting to current screen's max width/height?
