### ISSUE TITLE
[V2] Wails Keep Rolling Back with The Old Version

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1208]
I am not sure why is my ``wails`` just keep rolling back the old version when I do the command ``wails dev``
I did changed the go.mod to:
```go.mod
github.com/wailsapp/wails/v2 v2.0.0-beta.32
```
I also did the ``go mod tidy``.
Every thing looks fine until I run ``wails dev``, it would automatically change back to:
```go.mod
github.com/wailsapp/wails/v2 v2.0.0-beta.29
```

Am I missing something here?

**Comment by leaanthony** [comment]
Dev will set it to whatever the version of the CLI is, which is presumably `.29`. `wails update -pre` to get to `beta.32`. I've also updated the docs. Reopen if this is not the case 👍
