### ISSUE TITLE
react template build error

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#121]
**Description**

can not build react template

**To Reproduce**
download wails 0.16.0:
1. `wails init`
2. select React Js
3. try building the generated hello world `cd projectName && wails build`
4. see error

**Expected behaviour**
Build hello world 

**Screenshots**
![wails_error](https://user-images.githubusercontent.com/22690219/59675406-dfc40700-91cd-11e9-9706-09501d9d0143.png)
![wails_npm_log](https://user-images.githubusercontent.com/22690219/59675635-52cd7d80-91ce-11e9-9e00-96988ea3760f.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.16.0 |
| Go Version    | go1.12.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Additional context**
The fix seems to be removing everything inside production array. Since the "browser" is webview is alright.

https://github.com/wailsapp/wails/blob/master/cmd/templates/create-react-app/frontend/package.json.template
```
"browserslist": {
    "production": [
],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by leaanthony** [comment]
I did mother this on mac

**Comment by bh90210** [comment]
??

**Comment by leaanthony** [comment]
Autocorrect on phone :joy: 
I did not see this on Mac

**Comment by bh90210** [comment]
#122 hopefully fixed the issue

**Comment by bh90210** [comment]
the problem persisted even after the bugfix, mainly cause the fix was for production build and now the problem seems to also be happening in serve mode.

the quick fix again would be to remove everything, this time, from the `development` array
```
"browserslist": {
    "production": [],
    "development": [
    ]
  }
```
I might push that for now, but it certainly doesn't feel right and will investigate more to find a proper solution. 
What do you think?

**Comment by leaanthony** [comment]
Does `wails serve` still work with this fix?

**Comment by bh90210** [comment]
yes, I am using it right now in fact with chromium on ubuntu.

**Comment by leaanthony** [comment]
It's so cool that people are finding this feature useful.

**Comment by bh90210** [comment]
I really don't want to spend much more time on the template. I am pulling one more time and let's hope that will do it for now.

**Comment by bh90210** [comment]
for future reference: in case a similar ticket open in the future see suggested steps as described here #126
