### ISSUE TITLE
[v2] Hiding taskbar item

### ISSUE THREAD

**Issue by TheFranconianCoder** [wailsapp/wails#1213]
I'm using wails with a background application, which sits in the tray. Currently I hide and show the window. In this context the taskbar item is disurbing. Making this optional would be great.

**Comment by waini1110** [comment]
#1010

**Comment by leaanthony** [comment]
I'm not convinced this is possible. The OS generally handles that. If you can find APIs on all 3 platforms then feel free to reopen with the links. Cheers 👍

**Comment by stffabi** [comment]
According to MS in [Managing Taskbar Buttons](https://docs.microsoft.com/en-us/windows/win32/shell/taskbar#managing-taskbar-buttons) it should be possible to hide it by removing the `WS_EX_APPWINDOW` extended styling and adding `WS_EX_TOOLWINDOW`. Adding `WS_EX_TOOLWINDOW` would also affect other properties of the window like title bar height etc (most of them only relevant for a framed window).

**Comment by sebastian0x62** [comment]
For Windows: WS_EX_TOOLWINDOW (Already tried with Wails and works well)

For MacOS: Agent Application (https://www.appcoda.com/macos-status-bar-apps/)

I guess Linux could be a problem. For Electron it seems to be possible only for Windows and MacOS, too.

**Comment by leaanthony** [comment]
Adding it for post-v2 dev

**Comment by Blaconix** [comment]
Hello, I just tried modifying the source code to not have a taskbar icon, but I couldn't get it to work. I applied the `WS_EX_TOOLWINDOW` flag instead of `WS_EX_APPWINDOW` in my `exStyle` var, but nothing seems to happen.

@sebastian0x62 could you maybe tell me whether you've done something more to get it working?

**Comment by hangboss1761** [comment]
@leaanthony Is this feature complete?

**Comment by leaanthony** [comment]
This recently got submitted https://github.com/wailsapp/wails/pull/3507 and I've created a proposal for v3
