### ISSUE TITLE
[v2]Register a custom protocol

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1220]
**Is your feature request related to a problem? Please describe.**
A custom protocol can be registered when the application is installed, so that the application can be invoked using `yourAppName://`.

**Describe the solution you'd like**
Makes the application callable with `appName://`, can carry parameters and get these parameters when the application starts.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by leaanthony** [comment]
Changed the name. This is now on the roadmap 👍
