### ISSUE TITLE
Precompiled Binary

### ISSUE THREAD

**Issue by yudaprama** [wailsapp/wails#1221]
Any idea how to bundle precompiled binary?

thank you

**Comment by leaanthony** [comment]
I don't understand your request - sorry.

**Comment by yudaprama** [comment]
I mean packaging application to include, for example, ffmpeg binary so that go is able to exec via `exec.Command()`

**Comment by leaanthony** [comment]
Yeah, that's a general go question. You can do that using the go embed syntax 👍
