### ISSUE TITLE
the remote html's js code cannot call window.go.main.App.MyMethod/while local embed html's js can do

### ISSUE THREAD

**Issue by lituren99** [wailsapp/wails#1222]
version 2.0.0 beta.
when I test wails/v2, found that, the js code in local embedded html can call my App.Method,while js code in remote html can not.
is this designed for special target or a bug ?

**Description**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Attempted Fixes**
A list of things you have tried to fix the problem, including search engine links.

**System Details**
Please add the output of `wails doctor`.

**Additional context**

**Comment by leaanthony** [comment]
Please fill out the issue template. Thanks.

**Comment by misitebao** [comment]
The reason for this error is that the remote html file has not been injected into the runtime. Please refer to the documentation for the specific solution => https://wails.io/docs/guides/frontend/

**Comment by leaanthony** [comment]
Please reopen if you have time to fill in the issue template 👍
