### ISSUE TITLE
Save dialogs don't have extensions on default filenames [Wails 2]

### ISSUE THREAD

**Issue by amlwwalker** [wailsapp/wails#1225]
**Description**

I have a `runtime.SaveFileDialog` with the `SaveDialogOptions.DefaultFilename` set to the filename. To confirm that the filename is as expected, I print it out prior to creating the dialog and can see that its `save-astron.jpg`

However when I open the dialog, the extension is not included as part of the default filename. This causes a problem because on saving, the computer doesn't know what the default application is and cannot easily open it.

**To Reproduce**

```go
func Download(ctx context.Context, filename) error {
	homeDir, err := os.UserHomeDir()
	fmt.Println("downloading to ", filename)
	filepath, err := runtime.SaveFileDialog(ctx, runtime.SaveDialogOptions{
		DefaultDirectory:           homeDir,
		DefaultFilename:            filename,
		Title:                      "Choose where to save file to",
		Filters:                    nil,
		ShowHiddenFiles:            false,
		CanCreateDirectories:       true,
		TreatPackagesAsDirectories: false,
	})
```
![image](https://user-images.githubusercontent.com/2920180/157102938-26e3398a-a905-4dc0-8ddf-1cffa891e3bf.png)

**Expected behaviour**

![image](https://user-images.githubusercontent.com/2920180/157102985-5b8945d3-2242-487a-ac20-ef59a5e838b0.png)

**Attempted Fixes**

None

**System Details**
```shell

System
------
OS:		MacOS
Version: 	11.5.2
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2384
npm 				N/A		Installed	6.14.9
*upx 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

```

**Comment by leaanthony** [comment]
I will check, but I'm reasonably sure we don't do anything with the filename, just pass it to Cocoa.

**Comment by leaanthony** [comment]
@amlwwalker - Please try the PR and let me know 👍
