### ISSUE TITLE
NSIS Option gives error about WebView2 setup file

### ISSUE THREAD

**Issue by TheFranconianCoder** [wailsapp/wails#1226]
**Description**

I tried the `-nsis` option and got the following error:

```
File: "tmp/MicrosoftEdgeWebview2Setup.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro wails.webview2runtime on macroline 27
Error in script "project.nsi" on line 80 -- aborting creation process
```

I tried several `-webview` options as well, which didn't solve the problem.

**Attempted Fixes**

To were able to create an installer, I changed file `project.nsi` and commented `!insertmacro wails.webview2runtime`. Of course, no solution. Just to try if it works in general.

**System Details**

```
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.7
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.30
npm             N/A             Installed       8.1.0
*upx            N/A             Available
*nsis           N/A             Installed       v3.08
```

NSIS Version: v3.08

**Comment by stffabi** [comment]
Seems like the WebviewBootstrapper is not found `File: "tmp/MicrosoftEdgeWebview2Setup.exe" -> no files found.`. Can you please take a look if the file is placed under `build/windows/installer/tmp`? The file is getting written during `wails build --nsis`

**Comment by stffabi** [comment]
I think the problem might be that you are on windows and the file is referenced with a `/` instead of a `\`, although normally NSIS should take care of that.

**Comment by stffabi** [comment]
@sebastian0x62 can you please give PR #1227 a try?

**Comment by sebastian0x62** [comment]
The Installer is there. But shouldn't this be ignored, when I use something different than `embed`?

**Comment by stffabi** [comment]
The `embed` option is only relevant for how the Bootstrapper is integrated into your app's binary. This is to support Copy-Only installations, which gives a similar experience like on MacOS, just copy the binary and start it. For the installer, this is always integrated per default and the installer takes care that the WebviewRuntime is installed, if it's not installed the installer will trigger the Bootstrapper to install it.
If you don't want to include the bootstrapper, just comment out `!insertmacro wails.webview2runtime` in your `project.nsi` file. But just be aware that this could bring up problems, e.g. in a corporate environment where the user doesn't have the right to install apps. So the IT installs the app with the generated installer and afterwards a user can't run the app if the IT has not installed the WebviewRuntime manually.

**Comment by stffabi** [comment]
If you always generate an installer and distribute that way, you could use an option other than `--webview2 embed` to save some space in your app binary.

**Comment by stffabi** [comment]
> The Installer is there.

Thanks for checking, so the PR #1227 should fix the problem.
