### ISSUE TITLE
not found: module github.com/wailsapp/wails/cmd/wails: no matching versions for query "latest"

### ISSUE THREAD

**Issue by LunckyB** [wailsapp/wails#1233]
**Description**
go install github.com/wailsapp/wails/cmd/wails@latest
go install github.com/wailsapp/wails/cmd/wails@latest: module github.com/wailsapp/wails/cmd/wails: Get "https://proxy.golang.org/github.com/wailsapp/wails/cmd/wails/@v/list": dial tcp 172.217.163.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**System Details**
windows 10
go: 1.16.15
git: 2.27.0
npm: 8.1.2
node: 16.13.2

**Comment by LunckyB** [comment]
request 'https://proxy.golang.org/github.com/wailsapp/wails/cmd/wails/@v/list' throw error not found: module github.com/wailsapp/wails/cmd/wails: no matching versions for query "latest"

**Comment by leaanthony** [comment]
I'm not sure what you're experiencing there, but it's not a Wails issue as that's not a valid project path. Also just tried it and it works fine:
```
PS C:\Users\leaan> go install github.com/wailsapp/wails/cmd/wails@latest
PS C:\Users\leaan>
```

**Comment by LunckyB** [comment]
> 

 my computer CPU is intel by cause?

**Comment by stffabi** [comment]
This looks like a problem with connecting to `proxy.golang.org` does it still occur? Maybe a temporarily problem with the gomod proxy server.

**Comment by LunckyB** [comment]
> 这看起来像是连接到 的问题`proxy.golang.org`，它仍然会发生吗？gomod 代理服务器可能暂时出现问题。
yes

**Comment by LunckyB** [comment]
I found out why: GO has no proxy set up, Because I'm from China.     
Execute the command in CMD：
            1. go env -w GO111MODULE=on  
            2. go env -w GOPROXY=https://goproxy.cn,direct

**Comment by leaanthony** [comment]
I will add this to the troubleshooting guide 👍

**Comment by m4xlmum** [comment]
> I found out why: GO has no proxy set up, Because I'm from China. Execute the command in CMD： 1. go env -w GO111MODULE=on 2. go env -w GOPROXY=https://goproxy.cn,direct

well done

**Comment by youloust** [comment]
goat
