### ISSUE TITLE
[v2]Error in go file watcher

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1236]
**Description**
In "dev" mode, modifying the Go code to trigger an automatic rebuild will fail.

**To Reproduce**
Steps to reproduce the behaviour:

1. Pull the latest code from the master branch
2. Build and generate CLI tools
3. Execute `wails init -n wails-svelte -t svelte` and add `replace`
4. Execute `wails dev`
5. Modify any `.go` file
6. See error...

**Expected behaviour**
Can be rebuilt normally

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/157462386-aba740f0-8317-4e07-a7c8-90dfb39ff9f7.png)
Supplemental gif image presentation 👇
![wails-dev-go-file](https://user-images.githubusercontent.com/28185258/157627990-b707b6c9-ff2b-42cb-953c-56ad358de1a5.gif)

**Attempted Fixes**
None.

**System Details**
```
misitebao@MISITEBAO-BOOK MINGW64 ~/Desktop/wails-svelte (main)
$ wails doctor
Wails CLI v2.0.0-beta.33

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.30
npm             N/A             Installed       8.5.1
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Additional context**
None.

**Comment by leaanthony** [comment]
I followed these exact steps and it worked as expected. Sounds like a race condition. Can you pinpoint exactly what in nil and where? Looks like it's trying to call `ExecJS` on a nil webview?

**Comment by stffabi** [comment]
It would be interesting to narrow down where this `ExecJS` comes from, especially it is executed during `setupChromium`. I wouldn't have expected to see any `ExecJS` so early in the setup process of the Webview and the Window. Would be really interesting to find that one.
@misitebao can you reproduce this or does it only occur occasionally?

**Comment by misitebao** [comment]
@leaanthony @stffabi 
Update any `.go` file will be like this, not occasionally, it will always appear, and it will appear before, just because most of the time before, I was debugging the template and would not change the `.go` file, so I didn't specifically watch it.

**Comment by stffabi** [comment]
Unfortunately I was also unable to reproduce it, but I have one assumption where that `ExecJS` might come from. The only explanation would be, that this comes from the `wails dev` command where a reload is triggered to the internal `dev server` of the app here:

https://github.com/wailsapp/wails/blob/106ff03f2e65e9251212b1aff5ac96c82f4a790a/v2/cmd/wails/internal/commands/dev/dev.go#L619-L625

Depending on the timing it could happen, that this reload is triggered before the WebView2 has been fully initialised.

@misitebao have you tried to increasing the debounceMs setting? Just to see if that solves it and might indicate this is really the problem.

**Comment by leaanthony** [comment]
I'm glad someone reproduced it 👍 We could test that webview2 isn't nil and if so, just do a short sleep until it is?

**Comment by misitebao** [comment]
Maybe we should prohibit developers from setting the value of `debounceMS` too small, I think it is meaningless to set the value to `<1000`, a threshold should be set, once the value set by the user is less than the threshold, the threshold is used, and at the same time Warn the developer, and also give the user a hint in the documentation.

**Comment by leaanthony** [comment]
I'm not sure about this - I can set it to 20ms for this test project and it works fine. I'd rather determine when it's too low and output a message to the UI saying that the debounce is too small and to try a higher value.

**Comment by stffabi** [comment]
It's a highly timing issue and also depends on the time the frontend:dev:watcher also takes for rebuilding. I was also unable to reproduce it with low debounceMS, nevertheless I think it would make sense to check for nil in that case so we don't panic there.

**Comment by misitebao** [comment]
@leaanthony @stffabi 
Has the fix code been merged into the master branch?
