### ISSUE TITLE
[V2] Restricting to Single Instance of Executable File

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1248]
I would like my app to be running only on one instance at a time, that being said, if user click on the app icon again, the running instance should be close, or maybe something to prevent user to open another one.
Not sure if it is possible on multiple platform tho.
On Window, maybe we can use something like:
```go
var (
    kernel32        = syscall.NewLazyDLL("kernel32.dll")
    procCreateMutex = kernel32.NewProc("CreateMutexW")
)
```

**Comment by netrip** [comment]
There is a  simple ways can achieve this by open a fixed tcp port.

**Comment by leaanthony** [comment]
Or write a file to your config dir I guess... TCP is auto cleanup though 👍

**Comment by KiddoV** [comment]
@netrip you mean to set the app server port?
Tbh, I have no idea what you guys are talking about. Can you give me some example, or a docs somewhere?

**Comment by netrip** [comment]
> @netrip you mean to set the app server port?
> Tbh, I have no idea what you guys are talking about. Can you give me some example, or a docs somewhere?

open a tcp port when you start your app, so when try to run another instance of your app there must be port conflict, then you can catch this error , so you can abort(stop) the new started instance

**Comment by leaanthony** [comment]
This is outside of the scope of Wails right now @KiddoV - there's a couple of ways suggested here that should work for you 👍
