### ISSUE TITLE
[V2] Linux build appears to not handle images correctly

### ISSUE THREAD

**Issue by marcus-crane** [wailsapp/wails#1251]
**Description**
Upon generating a Linux build for [October](https://github.com/marcus-crane/october), the static logo doesn't render. Interestingly, the logo does indeed seem to exist in the bundled frontend but the actual image contents are destroyed partway through?

I've attached some screenshots to illustrate.

It's also worth noting that the initial request to the image appears to fail entirely, despite successive requests using fetch succeeding just fine with a 200 (even though the content is not present)

Both builds were generated using `go install github.com/wailsapp/wails/v2/cmd/wails@master`, which would have pointed to [a52d684](https://github.com/wailsapp/wails/commit/a52d68438b66018aff47891b7d7a8aee9d10cf24) at the time of writing

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `wails dev` or `wails build` against https://github.com/marcus-crane/october/tree/459d27a0c9b92f7c6b71292b25c5f1683b637c9f 🤷 

**Expected behaviour**
I would expect that the referenced image is present, as it is on Windows and Linux

**Screenshots**
Linux build where the referenced image is "empty" despite being present on disc
![CleanShot 2022-03-13 at 12 16 49](https://user-images.githubusercontent.com/14816406/158038535-7c716d38-ecdd-4fe2-a941-8a78d85d865f.png)

![CleanShot 2022-03-13 at 12 17 27](https://user-images.githubusercontent.com/14816406/158038453-f845312d-8df7-4bcd-9dbf-2a6be936fd18.png)

macOS build with the expected image content
![CleanShot 2022-03-13 at 12 16 35](https://user-images.githubusercontent.com/14816406/158038434-88d069ce-d8c6-4443-a784-b8fbc13f18b1.png)

**Attempted Fixes**
I tried referencing a different image (the default React logo at /logo192.png) and had no luck with that either. Perhaps it applies to images in general?

**System Details**
```bash
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:			Ubuntu
Version: 		20.04
ID:			ubuntu
Go Version:		go1.17.8
Platform:		linux
Architecture:		amd64
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Available	20.10.7-0ubuntu5~20.04.2
gcc		build-essential		Installed	12.8ubuntu1.1
libgtk-3	libgtk-3-dev		Installed	3.24.20-0ubuntu1.1
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.34.6-0ubuntu0.20.04.1
npm		npm			Installed	8.5.0
*nsis		nsis			Available	3.05-2
pkg-config	pkg-config		Installed	0.29.1-0ubuntu4

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis
```

**Additional context**

**Comment by leaanthony** [comment]
This sounds like it might be fixed by https://github.com/wailsapp/wails/pull/1240

**Comment by leaanthony** [comment]
@marcus-crane - closing as you've confirmed it works 👍
