### ISSUE TITLE
[v2, windows] Add flag to indicate whether to use https://

### ISSUE THREAD

**Issue by stefpap** [wailsapp/wails#1253]
**Is your feature request related to a problem? Please describe.**
The newly merged #1211 PR broke my app because with I cannot load http content anymore, since the current page is considered to be `https://wails.localhost/`
![image](https://user-images.githubusercontent.com/22637722/158064306-ece71344-0b62-4a0a-a6b6-ada301cec6dc.png)

**Describe the solution you'd like**
Do you think it would be possible to add a parameter to indicate `http`, `https` or `file://`, or just a bool flag something like isHTTP ?

**Comment by stffabi** [comment]
Yeah, that's a problem. Maybe we should switch to http. Because in the near future as soon as Webview2 supports custom schemes there's the plan to use wails:// to have it standardised on all platforms. MacOS and Linux already use that custom scheme.
Especially https makes it now inconsistent, because it works on MacOS and Linux but not on Windows.
So I would propose to switch to http.

**Comment by stefpap** [comment]
Would switching to http break the web workers? If not, that would be an easy change

**Comment by stffabi** [comment]
AFAIK web workers should still work, but we would need to check it.

**Comment by stefpap** [comment]
Created a draft PR for this #1255

**Comment by leaanthony** [comment]
@failip420 any chance you could check if this PR breaks your web workers app?

**Comment by Failip420** [comment]
> @Failip420 any chance you could check if this PR breaks your web workers app?

It still seems to work.
No errors or anything so far :)

**Comment by leaanthony** [comment]
That would need testing across all platforms. I'm ok with this PR in the short term and them switch to custom protocol once it's merged in webviews. I believe that'll be in a month

**Comment by stffabi** [comment]
Yeah absolutely my intention was not to use http:// on all platforms, only just for windows until we can use wails://.
With a consistent behaviour I meant that all platforms allow accessing unsecure content.

**Comment by stefpap** [comment]
I'll close the issue since the PR got merged. Thanks everyone for helping out!
