### ISSUE TITLE
Application can respond to system key event

### ISSUE THREAD

**Issue by kcmvp** [wailsapp/wails#1263]
**Is your feature request related to a problem? Please describe.**
it's just a new future

**Describe the solution you'd like**
when the application runs in the backend(eg: shows an icon in the system tray), I would like to bring the application to the forground (shows the normal application window) by double-click key(eg: CTRL).

**Describe alternatives you've considered**
no at present

**Additional context**

**Comment by leaanthony** [comment]
I think this can be done using some other library that hooks into global shortcuts and using the Hide and Show methods of the runtime

**Comment by netrip** [comment]
> I think this can be done using some other library that hooks into global shortcuts and using the Hide and Show methods of the runtime

Thank you very much! I will have a try!

**Comment by netrip** [comment]
> I think this can be done using some other library that hooks into global shortcuts and using the Hide and Show methods of the runtime

Thank you very much! I will do a research. By the way do you have any recommendation?

**Comment by netrip** [comment]
> I think this can be done using some other library that hooks into global shortcuts and using the Hide and Show methods of the runtime

what's a pity ! I can not find any existing library support GLOBAL keyboard event. Some library supports keyboard event only in the applicaton, once the application(window) lose focus it does not work.

**Comment by leaanthony** [comment]
I'm not sure how we'd implement it in Wails TBH.

**Comment by netrip** [comment]
> I'm not sure how we'd implement it in Wails TBH.

I had some VB experience many years ago. There is a built in method support this , but only on windows platform. I guess it might register an os level hook. Back to the question, in order to support multiple platform, not sure it’s feasible or not to call native method of the os?

**Comment by netrip** [comment]
As a desktop application, I think it's a nice feature support global key event. after some time research. seems https://github.com/robotn/gohook supports this.

**Comment by leaanthony** [comment]
Happy for you to raise a PR for this.

**Comment by dzpt** [comment]
@kcmvp gohook will fire even the app is unfocused.
anyway to catch the pressed key while the app is focus?
