### ISSUE TITLE
Redirection not working in default windowed mode. (Working in fullscreen mode) v2.0.0-beta.33 

### ISSUE THREAD

**Issue by springyboiii** [wailsapp/wails#1266]
Description
In the default windowed mode, redirecting to another page is not working. When I launch the app in fullscreen mode, redirections are working fine

To Reproduce

1. Go to 'frontend/src/index.html'
2. Add a button/a tag to perform redirection
3. Use dev mode
5. Change Fullscreen: true in main() at main.go
6. Save main.go
7. Redirection would be working fine in fullscreen mode

Expected behaviour
Redirection to another page should be working fine in windowed mode as well. 

Screenshots
![image](https://user-images.githubusercontent.com/84062751/158941673-cc6d4dd2-3d7a-4353-9d21-9e0ace851134.png)
![image](https://user-images.githubusercontent.com/84062751/158941725-fd21f776-e085-4c36-bd50-edc0002d7241.png)
![image](https://user-images.githubusercontent.com/84062751/158941745-02a89938-1902-464b-9237-6d52fd0024a6.png)

Attempted Fixes
I've tried using many ways to redirect. None of them seem to work. 

System Details
Wails CLI v2.0.0-beta.33

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19042)
ID:             20H2
Go Version:     go1.17.8
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.39
npm             N/A             Installed       6.14.15
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download

**Comment by stffabi** [comment]
Thank you for your creating this issue.

I suspect it's a duplicate of #1201. Are you using the `data-wails-drag` attribute on the body?

**Comment by springyboiii** [comment]
Yeah. That solved the issue. Thanks
