### ISSUE TITLE
 wails dev -platform windows/386 编译win32位 这个参数无效.说没有定义

### ISSUE THREAD

**Issue by luxiaolan6373** [wailsapp/wails#1269]
wails dev -platform windows/386 编译win32位 这个参数无效.说没有定义

PS D:\GoProjects\src\github.com\luxiaolan6373\TFTgo> wails dev -platform windows/386
Error: flag provided but not defined: -platform

Wails CLI v2.0.0-beta.33

Wails dev - Development mode
Flags:

  -appargs string
        arguments to pass to the underlying app (quoted and space searated)
  -assetdir string
        Serve assets from the given directory instead of using the provided asset FS
  -browser
        Open application in browser
  -compiler string
        Use a different go compiler to build, eg go1.15beta1 (default "go")
  -debounce int
        The amount of time to wait to trigger a reload on change (default 100)
  -devserverurl string
        The url of the dev server to use (default "http://localhost:34115")
  -e string
        Extensions to trigger rebuilds (comma separated) eg go (default "go")
  -f    Force build application
  -help
        Get help on the 'wails dev' command.
  -ldflags string
        optional ldflags
  -loglevel string
        Loglevel to use - Trace, Debug, Info, Warning, Error
  -noreload
        Disable reload on asset change
  -reloaddirs string
        Additional directories to trigger reloads (comma separated)
  -tags string
        tags to pass to Go compiler (quoted and space separated)
  -v int
        Verbosity level (0 - silent, 1 - standard, 2 - verbose) (default 1)
  -wailsjsdir string
        Directory to generate the Wails JS modules

ERROR: flag provided but not defined: -platform

**Comment by leaanthony** [comment]
-platform isn't supported by `dev` only `build`.

**Comment by luxiaolan6373** [comment]
i am try  build,buy call back not supported 368 ...win32  not supported

**Comment by luxiaolan6373** [comment]
![E4 8_TL$%5~1G$@58)95E}K](https://user-images.githubusercontent.com/69368155/159104807-f33aa48b-60fc-4aeb-8362-9a96a868de15.png)
