### ISSUE TITLE
Poll: Examples

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#127]
Hi all! I'm thinking of setting up a seperate repo for examples (as it would be quite big). Do you think this would be useful? If so, do you think it should be a 'Kitchen Sink' example with everything, or a list of individual examples aka 'recipes'?

👍= Kitchen Sink!
🚀= Recipes!

**Comment by vladimirschuka** [comment]
Hi, if those examples are small then one project. It would be really helpful thanks!

**Comment by leaanthony** [comment]
When we get time, we will add an examples page in the style of Recipes. Thank you for your feedback! 👍🎉
