### ISSUE TITLE
Can WAILS set properties to hide title boxes?

### ISSUE THREAD

**Issue by LunckyB** [wailsapp/wails#1270]
I'm building an application using WAILS, I hope to use Vue to build an interface similar to wechat
![1647686283(1)](https://user-images.githubusercontent.com/82591823/159117685-752242cd-225c-428c-bef7-c905574740f5.jpg)

**Comment by leaanthony** [comment]
Yes, use frameless mode: https://wails.io/docs/guides/frameless
