### ISSUE TITLE
[Wails 2] Clicking on the close button doesn’t do anything until the mouse moves.

### ISSUE THREAD

**Issue by raguay** [wailsapp/wails#1273]
**Description**

When you click the close icon in the upper left corner (macOS) nothing happens until you move the mouse or click a button again.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open an application compiled with Wails 2
2. Click on the upper left hand close button without moving the mouse or clicking another button.
3. Error: nothing happens at all until the mouse is moved or another button pressed.

**Expected behaviour**
When the close button is pressed, it is expected to close the application right then.

**Screenshots**
NA

**Attempted Fixes**

No attempted fixes since it is internal to the Wails 2 engine.

**System Details**

Wails CLI v2.0.0-beta.33

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.2.1
ID:		199506
Go Version:	go1.17.8
Platform:	darwin
Architecture:	arm64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.5.4
*upx 				N/A		Available
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download

**Additional context**
Nothing more to add.

**Comment by leaanthony** [comment]
@raguay - Can you confirm this is also true if you build your app as a `.app` file and run it like a normal app? I've added a potential fix in the above PR. Seems to work for me but more testing the better.

**Comment by raguay** [comment]
I rebuilt the application and it still has the same issue. But, I'm still running wails 2 v2.0.0-beta.33. Should it be a different beta? The `wails update` doesn't do anything but say there are no keys.

**Comment by leaanthony** [comment]
Ah, to test PRs, use the following guide, but instead of staying on master, change to the PR branch https://wails.io/docs/guides/bleeding-edge

**Comment by raguay** [comment]
I have the lastest pr branch for fixing the mac close #1273 and it still
has the same bug. The build process still show beta.33 even though I
pointed it to the local build directory. Is there a way to check to make
sure I'm using the right version? I made the change in the go.mod file, so
it should be working right.

Richard

**Comment by leaanthony** [comment]
Sounds like it. You sure your replace path points you our local source directory and you've checked out the PR branch? I might just merge to master anyway as it won't do any harm. Really should tag .34 but there's stuff in flight.

**Comment by raguay** [comment]
The git status shows:

```
git status
On branch refs/heads/bugfix/1273_mac_close_event
nothing to commit, working tree clean
```
and the last line in the go.mod is:
```
replace github.com/wailsapp/wails/v2 => /Users/raguay/Documents/wails/V2/
```
Is that right?

**Comment by leaanthony** [comment]
Thanks for the headsup. We are moving away from the dep that uses this so that will go away shortly. It's only used in dev mode.

**Comment by leaanthony** [comment]
Merging this to master as it won't break anything and will be easier to test.

**Comment by raguay** [comment]
I’m using beta-34 and it still has this issue.

**Comment by raguay** [comment]
Using Wails beta.37 and the close button exits directly without having to move the mouse. Thanks.
