### ISSUE TITLE
about TrayMenu function

### ISSUE THREAD

**Issue by LunckyB** [wailsapp/wails#1276]
I see in the source code TrayMenu method(https://github.com/wailsapp/wails/blob/cf8e2ee195f2d167f8e0e78425f3abfc0116cd37/v2/internal/menumanager/traymenu.go), Do these functions work? 
![Uploading 1647918637(1).jpg…]()

**Comment by LunckyB** [comment]
![1647918637(1)](https://user-images.githubusercontent.com/82591823/159400440-a76dfdb5-4b0e-4a15-8571-28f7a884780c.jpg)

**Comment by leaanthony** [comment]
This is old Alpha code that doesn't work now, but will be available in v2.1 👍
