### ISSUE TITLE
Need to import models.ts in bindings.d.ts

### ISSUE THREAD

**Issue by mondy** [wailsapp/wails#1277]
**Description**
When a bound go function returns struct, the type of `bindings.d.ts` is incomplete.

**To Reproduce**

1. Create a new project with `wails init -n foo`.
2. Add the following to `app.go`.
```go
type Foo struct {
	Bar string `json:"bar"`
}

func (b *App) GetFoo() *Foo {
	return &Foo{}
}
```

3. Run `wails dev` and check `bindings.d.ts`.
4. Error `Cannot find name 'Foo' ts(2304)` is output on vscode. 

**Expected behaviour**
`import { Foo } from './models';` has been added to the beginning of `bindings.d.ts`.

**System Details**

```sh
System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.46
npm             N/A             Installed       8.5.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available
```

- wails version v2.0.0-beta.33

**Comment by leaanthony** [comment]
Could we `import *` or does it need to be explicit?

**Comment by mondy** [comment]
The return type of the bound function must be resolved.
To do so, you can use `import { Foo, Bar, Baz } from '. /models';` to expand it.

**Comment by netrip** [comment]
Yes, I ran into the same issue.

**Comment by netrip** [comment]
@leaanthony it seems it's a good issue for newbie. I would like to have a try, I figure out that the binding files are generated by command 'wails generate module'. can you give me a clue how to fix it?

**Comment by leaanthony** [comment]
Hey, thanks for the offer. I'm assuming what needs to be done is get all the generated model names from the model generation phase and pass them into the bindings generation method. Iterate over the models or `strings.Join` and write out the import statement. I'm hoping any models not used will be ignored!!!

**Comment by leaanthony** [comment]
I think this may be fixed by https://github.com/wailsapp/wails/pull/1231/files - It will be in the next release (which I'm currently doing.

**Comment by netrip** [comment]
@leaanthony Thank you very much, once this fix is merged I will have a test.

**Comment by zandercodes** [comment]
Please Close
