### ISSUE TITLE
wails init -l does not work

### ISSUE THREAD

**Issue by kcmvp** [wailsapp/wails#1278]
**Description**

from the link https://wails.io/docs/gettingstarted/firstproject we can use **wails init -l** to list available templates. but it does not work

**To Reproduce**
1:  execute command "wails init -l"
2: get output *Error: flag provided but not defined: -l*

**Expected behaviour**
According to the document, it should list some project template.

**Screenshots**

**Attempted Fixes**

**System Details**
Wails v1.16.9 - Checking for updates...

✓ Checking for updates...

    Current Version : v1.16.9
     Latest Release : v1.16.9
Looks like you're up to date!

OS : Mac OS

**Additional context**

**Comment by leaanthony** [comment]
Those docs are for v2. You are using v1. Please upgrade to v2 👍
