### ISSUE TITLE
When maximize the window there is a twinkling blank(no background)

### ISSUE THREAD

**Issue by kcmvp** [wailsapp/wails#1279]
**Description**

**To Reproduce**
Steps to reproduce the behaviour:
1: follow the https://wails.io/docs/gettingstarted/installation to init a new project
2: run the empty the app
3: click the title bar of the window to resizing the application.

**Expected behaviour**
Ideally there should be no twinkling when resizing the window.

**Screenshots**
Please see the screen record at https://youtu.be/rjJz7DwSFCw

**Attempted Fixes**
A list of things you have tried to fix the problem, including search engine links.

**System Details**
Wails CLI v2.0.0-beta.33

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.3
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.4.1
*upx 				N/A		Available
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download

**Additional context**

**Comment by leaanthony** [comment]
I noticed this in Electron if devtools are open. The fix that's suggested is to use `layerContentsRedrawPolicy = NSViewLayerContentsRedrawDuringViewResize` but that doesn't seem to make much difference to me. Will keep looking....

**Comment by leaanthony** [comment]
@kcmvp this should be fixed in the latest release. Please use the `BackgroundColour` option to mitigate this.

**Comment by kcmvp** [comment]
Thank you very much! it's so happen that there is desktop project kicked off. I will have a try
