### ISSUE TITLE
frontend:dev:watcher not optimal with Vite

### ISSUE THREAD

**Issue by AlexBitsTech** [wailsapp/wails#1283]
**Description**
When setting up a Vite frontend and adding `vite build --watch` to the `frontend:dev:watcher` parameter in wails.json, the program sets up the watcher correctly and starts. However, when making changes to the source code, wails tries to refresh its' GUI before Vite is done recompiling leading to a 404 error display in the GUI (can be fixed by right clicking and refreshing the wails GUI).

**To Reproduce**
Steps to reproduce the behaviour:

1. Set up a Vite frontend in a wails project
2. Add `vite build --watch` to the `frontend:dev:watcher` parameter in wails.json (might need to install Vite globally)
3. run `wails dev`
4. Make a change in the source code
5. Observe a 404 error in the wails GUI (happens 95% of the time. Rarely, Vite manages to recompile before Wails refreshes and then it works fine)

**Expected behaviour**
Wails should only refresh its' interface after Vite is done recompiling to avoid the 404 error.

**System Details**

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.46
npm             N/A             Installed       8.5.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download

**Comment by stffabi** [comment]
We are working on bringing support for external dev servers. Once supported you will be able to let wails use the 'vite dev' dev server. 

Should be ready soon.

**Comment by stffabi** [comment]
PR #1290 is up, would be great if you could give it a try with the following changes in your project.json

```json
  "frontend:dev:watcher": "npm run dev",
  "frontend:dev:serverUrl": "http://localhost:3000",
```

**Comment by AlexBitsTech** [comment]
I just tested the branch.
Everything compiles fine and I then get the wails dev interface that shows up, works but does not reload when making changes to the source code.
The devServer on port 3000 does reload correctly but doesn't have access to the go backend.
And the normal devserurl on port 34115 does not hot reload but it has access to the go backend.

**Comment by stffabi** [comment]
Sorry it didn't work for you. I've just retested the branch with a clean svelte template and everything was working fine. Hopefully we could track that problem down.

Could you please again update to the branch and update your installation according to [Use Bleeding Edge](https://wails.io/docs/guides/bleeding-edge)?

You should then see the following output from `wails dev` directly after starting `Wails CLI v2.0.0-beta.34.frontenddevserver`. This would indicate you are on the correct version for the `wails` binary itself.
Furthermore could you please make sure that the `replace` directive is added in your  `go.mod` which points to the local checkout of the branch.

**Comment by AlexBitsTech** [comment]
The issue is that I can't seem to find the frontenddevserver branch on the official wails repo.
I therefore used `https://github.com/stffabi/wails/tree/feature/frontend-devserver` which gave me the results listed above. Any advice on how to get the frontenddevserver branch of the official wails repo?

**Comment by stffabi** [comment]
Yeah, the branch is not on the official repo. It's on my repo, I suspect either the binary was not the correct one or the replace was somehow wrong.

Please use the following within the default wails repo and with the bleeding edge guide. This allows you to checkout the PR itself.

```bash
git fetch -u origin pull/1290/head:test/pr-1290
git checkout test/pr-1290
cd v2/cmd/wails
go install
```

**Comment by AlexBitsTech** [comment]
I followed your instructions to the letter and it works (almost) perfectly. The dev GUI refreshes without any problem.
The only issue (but I'm not sure if it has anything to do with this PR) is that the wails-data-drag prop on my navbar doesn't work anymore. I can't drag my app.
But other than that everything reloads perfectly!

**Comment by stffabi** [comment]
> I followed your instructions to the letter and it works (almost) perfectly. The dev GUI refreshes without any problem.

Awesome, thanks so much for testing it. 🙏

> The only issue (but I'm not sure if it has anything to do with this PR) is that the wails-data-drag prop on my navbar doesn't work anymore. I can't drag my app.

Yeah, forgot to mention. Thats currently a known issue with the frontend devserver. I have that one on my list.

**Comment by AlexBitsTech** [comment]
In any case thank you a lot for the work!
This is a huge quality of life improvement.
If the data-wails-drag issue is part of another issue/PR, feel free to close this issue.

**Comment by leaanthony** [comment]
Windows 11 22000 AMD64 tested and working great!

**Comment by leaanthony** [comment]
MacOS v12.2.1 M1 - Working 👍

**Comment by stffabi** [comment]
@AlexBitsTech I've updated the PR, it now supports `data-wails-drag` in an external dev server. Would it be possible for you to retest the PR? That would be awesome 🙏 .

The following should update your old branch of the PR to the latest version.
```sh
git fetch -u origin pull/1290/head:test/pr-1290
git checkout test/pr-1290
git reset --hard HEAD
cd v2/cmd/wails
go install
```

**Comment by AlexBitsTech** [comment]
@stffabi Just tested your PR. Everything works perfectly. the `data-wails-drag` works great and the hot reload is also works perfectly.

**Comment by stffabi** [comment]
@AlexBitsTech great news, thanks so much for taking your time and testing the PR 🙏

**Comment by AlexBitsTech** [comment]
Thank you for the time you put into it!
