### ISSUE TITLE
[v2] Issue disabling script injection

### ISSUE THREAD

**Issue by TheFranconianCoder** [wailsapp/wails#1298]
**Description**
The meta tag for disabling script injection must be first meta tag.

**To Reproduce**
Put `<meta name="wails-options" content="noautoinject">` after another meta tag. Scripts will still be injected.

**Expected behaviour**
Meta tag should work on every position in `head`.

**Attempted Fixes**
Fix is in `common.go` -> `extractOptions()`.

I can provide PR.

**Comment by stffabi** [comment]
Interesting timing for this issue 😄.

Would it be possible for you to outline your use case for disabling the injections? We are just in the process of removing these options in PR #1290

**Comment by sebastian0x62** [comment]
#1290 looks pretty cool. Will use this when available. Currently I let WebPack create static files when changes arrive, for my Vue project. Not so smooth.

I disable all Wails script injection, since I'm not going to use any of this integration. Actually, my frontend should be not bound too much on this frontend integration. Did this with Tauri and Electron and was not happy. Without any integration I am very flexible to run it in browser as well. Or thinking even about mobile with Capacitor etc.

Because of that i disabled script injection.

**Comment by stffabi** [comment]
Maybe we could add an AppOption to simply skip all injections instead? 

@leaanthony what do you think?

**Comment by leaanthony** [comment]
I guess I don't understand the use case. If you're disabling the runtime and bindings, why not use webview project?

**Comment by sebastian0x62** [comment]
Wails is much more, what you even mentioned in a WebView ticket there. Icon, styling, packaging, ... I want all of this, just don't want to use the front-end API. It's not big of an issue when I can't disable the injection. I just will not use it. ;-)

**Comment by leaanthony** [comment]
If it's ok with you, maybe just ignore them. This was a hack for a problem which isn't there now and it'd be better from a maintenance point of view to remove them

**Comment by sebastian0x62** [comment]
Maybe there could be a way like in Tauri, where you import the Tauri API where needed in JavaScript. No injection happens automatically there.

**Comment by leaanthony** [comment]
> #1290 looks pretty cool. Will use this when available. Currently I let WebPack create static files when changes arrive, for my Vue project. Not so smooth.
> 
> I disable all Wails script injection, since I'm not going to use any of this integration. Actually, my frontend should be not bound too much on this frontend integration. Did this with Tauri and Electron and was not happy. Without any integration I am very flexible to run it in browser as well. Or thinking even about mobile with Capacitor etc.
> 
> Because of that i disabled script injection.

Based on this use case, I think it's fine to just ignore it 👍
