### ISSUE TITLE
[v2]windows does not show the window

### ISSUE THREAD

**Issue by hxfighting** [wailsapp/wails#1305]
**Description**
All dependencies are installed according to the documentation. Use the command "wails dev" to see the normal page in the browser, but after building the program with "wails build", click the generated exe file, no window appears, use the windows task manager to see that there is a background The program is running, but no window appears, and then debug build is turned on, a window appears, but only the version information of webview2 is printed, and there is no more output.

**To Reproduce**
just follow the documentation.

1. install windows dependencies：webview2、npm
2. install wails2
3. init a project:  wails init -n testui
4. build project: wails build

**Expected behaviour**
Click on the exe file to bring up the interface window。

**Screenshots**
I can't post images due to intranet，sorry。

**Attempted Fixes**
I tried reinstalling webview2, but it didn't work.

**System Details**
Please add the output of `wails doctor`.

os: windows 10 pro for workstations
version: 2009 build: 19042
id: 20H2
goVersion: go1.17.8
platform: windows
Architecture: amd64

dependency   package name     status        version
WebView2       N/A                       Installed     99.0.1150.55
npm                 N/A                       Installed      8.5.0
*upx                N/A                        Available
*nsis               N/A                        Available

**Additional context**

**Comment by leaanthony** [comment]
Please follow the instructions when filing a bug report. Thanks 👍

**Comment by hxfighting** [comment]
> Please follow the instructions when filing a bug report. Thanks 👍

Changed the report, please take a look when you have time.

**Comment by leaanthony** [comment]
I use Windows as my main Dev machine and can say it's working fine. Are you using latest release or master?

**Comment by hxfighting** [comment]
> I use Windows as my main Dev machine and can say it's working fine. Are you using latest release or master?

yes, the latest version: v2.0.0-beta.34

**Comment by oSethoum** [comment]
I use it in windows too and it's working fine.

**Comment by leaanthony** [comment]
Please reopen if you can provide more info 👍

**Comment by lilili87222** [comment]
Yes,the same problem with some windows version. not show error,not show windows . not know why.

**Comment by lilili87222** [comment]
helloworld   display a blank window with nothing

![guierr](https://user-images.githubusercontent.com/2214998/218636936-9694e94e-9581-4a68-824b-1809ab2cf443.png)
![guierr2](https://user-images.githubusercontent.com/2214998/218636941-d2a33545-108c-4f05-8612-112534caa5b9.png)

**Comment by stffabi** [comment]
Have you taken a look into the event viewer? Maybe there are crashes of the webview2 process.
