### ISSUE TITLE
[v2] Add i18n support for webview2 runtime install message

### ISSUE THREAD

**Issue by kylege** [wailsapp/wails#1306]
**Is your feature request related to a problem? Please describe.**
When user have not installed the webview2 windows runtime, wails will alert the user with some message, such as "The WebView2 runtime is required to run this application. Please contact your system administrator."

It's not friendly for users who don't familiar with english.

**Describe the solution you'd like**
Developer can set a different message string, such as  russia or chinese translation.

**Comment by misitebao** [comment]
Maybe the wails library itself needs an i18n module?

**Comment by leaanthony** [comment]
Thanks for opening this. Would a simple string variable work for now?

**Comment by kylege** [comment]
> 

yes, that will work.

**Comment by leaanthony** [comment]
Hey @kylege - I've added some new code on master that might suit your needs: `windows.Options` now has a `Messages` field that allows you to customise the messages used by webview2 installer. Default messages are here: https://github.com/wailsapp/wails/blob/master/v2/pkg/options/windows/windows.go#L74-L86

Let me know how you get on 👍

**Comment by kylege** [comment]
> Hey @kylege - I've added some new code on master that might suit your needs: `windows.Options` now has a `Messages` field that allows you to customise the messages used by webview2 installer. Default messages are here: https://github.com/wailsapp/wails/blob/master/v2/pkg/options/windows/windows.go#L74-L86
> 
> Let me know how you get on 👍

A little bug here:

https://github.com/wailsapp/wails/blob/master/v2/internal/wv2installer/browser.go#L13

need fix messages.DownloadPageMsg to messages.DownloadPage

**Comment by kylege** [comment]
And in the message string, i think it's better to use WebView2 term，with capital W and V，not webview2 or Webview2 。

**Comment by leaanthony** [comment]
Thanks for raising this! Fixed on master 🙏
