### ISSUE TITLE
If the element adds the `data-wails-drag` attribute, how to make it trigger the dbclick or click event.

### ISSUE THREAD

**Issue by jicg** [wailsapp/wails#1313]
### Is your feature request related to a problem? Please describe.

I plan to use html to implement the title bar of windows, the title bar supports dragging, but there is no way to double-click the title to enlarge or reduce the window

### Describe the solution you'd like

If the element adds the `data-rails-drag` attribute,  it can trigger the dbclick event.

**Comment by leaanthony** [comment]
@KiddoV did you do this in your app?

**Comment by leaanthony** [comment]
@jicg I'm not sure what this might look like. If we don't prevent default for the event then there are side effects like page elements getting dragged around too. I'll need to think about it a bit

**Comment by jicg** [comment]
Thank you for your reply. Is it possible to use `timeout` to record the number of clicks and control whether the event is fired or not ?
https://github.com/wailsapp/wails/blob/f192cbd01beeb96b32de45ac11fd9f6a9fa6ca11/v2/internal/frontend/runtime/runtime_dev_desktop.js#L380

**Comment by KiddoV** [comment]
> @KiddoV did you do this in your app?

I didn't know how to make double click work, so I just leave it like that. :)

**Comment by leaanthony** [comment]
> Thank you for your reply. Is it possible to use `timeout` to record the number of clicks and control whether the event is fired or not ?
> 
> https://github.com/wailsapp/wails/blob/f192cbd01beeb96b32de45ac11fd9f6a9fa6ca11/v2/internal/frontend/runtime/runtime_dev_desktop.js#L380

Not a bad suggestion. Do you want to try adding it and see how you go? Just remember to run `npm build` in [this directory](https://github.com/wailsapp/wails/tree/f192cbd01beeb96b32de45ac11fd9f6a9fa6ca11/v2/internal/frontend/runtime) before running `go install` in `v2/cmd/wails`. Also remember to use `replace` to pick up your local changes.

This sounds like a good idea. Let me know how you get on!

**Comment by jicg** [comment]
This is the code I tried to modify and it works for me.  : https://github.com/wailsapp/wails/pull/1317/commits/e994a6f8c4c170900e520e58b820ecee28035650

**Comment by leaanthony** [comment]
Merged this on master. Please feel free to close this 👍

**Comment by ghostiam** [comment]
@jicg , @leaanthony 
After this fix, when [dragging a window using 3 fingers](https://support.apple.com/en-gb/HT204609), the window is not dragged immediately, but after a delay.
When I paste the old code into the console (after 12 seconds in the video), there are no such problems.

https://user-images.githubusercontent.com/12181586/183136483-057d3fb2-767b-4515-921a-c2d505732e2d.mov

**Comment by stffabi** [comment]
@ghostiam yeah, I've already seen that before. @leaanthony and I have talked about it and there's an old feature branch to improve this. AFAIK the feature branch had still some edge cases on Windows, don't know if the other platforms work without any problem on that branch. Unfortunately that went into oblivion when other problems were reported 😞 .

@ghostiam would it be possible for you to open a new issue for this?
