### ISSUE TITLE
wails dev can run but use vue project wails build click no

### ISSUE THREAD

**Issue by hyyky** [wailsapp/wails#1318]
### Description

1.wails init -n
2. delete frontend
3. run vue create frontend
4. cd frontend 
5. npm install
6. npm build
7. assetsdir is frontend/dis
8. wails build
9. click but can not run
10. wails dev show a window

![89709098bd80880d28c15ceb5483a82](https://user-images.githubusercontent.com/50724513/162122368-30054bfa-874a-4a83-a464-e80d2f4be07c.jpg)

### To Reproduce

![89709098bd80880d28c15ceb5483a82](https://user-images.githubusercontent.com/50724513/162122406-bb80b6a4-4957-42fe-8e94-9c806a6df22d.jpg)

### Expected behaviour

use VUE wails build can run

### System Details

```shell
window 10 Home
```

**Comment by leaanthony** [comment]
I've just pushed a PR on master with a default Vue template. This should be your base and it will work for you 👍

**Comment by hyyky** [comment]
I want to know why I can't customize Vue templates

**Comment by hyyky** [comment]
![image](https://user-images.githubusercontent.com/50724513/163669817-91097b2a-29bf-4869-924c-12edaabba8aa.png)
How can I get the latest? Can I use the version of this link

**Comment by leaanthony** [comment]
I believe this is now fixed 👍
