### ISSUE TITLE
wails init won't work

### ISSUE THREAD

**Issue by iceleo-com** [wailsapp/wails#132]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
When I run "wails init" command, It always returns to me an error:
`Error: unable to check libraries on distribution 'Debian'. Please ensure that the 'libgtk-3-dev' equivalent is installed`

but I already install "libgtk-3-dev" package on my PC. Please check the screenshot below for more details.
Thanks

**Expected behaviour**
That I can initialize my first Wails app on my Debian

**Screenshots**
Please check this screenshot https://i.imgur.com/ZPtpkVn.png

**System Details**
OS: Debian 9 - Gnome
Go: Version go1.12.6 linux/amd64

**Comment by leaanthony** [comment]
Hi. Debian isn't an officially supported distro...yet! 😃 We've had quite a few requests from different distros and people are kind enough to submit PRs. Are you in a position, with a little help, to add Debian support? I'm going to add a small wizard to handle this so it pulls most of the info for us when that error happens.

**Comment by iceleo-com** [comment]
Hi @leaanthony,

Thank for your responding.
I just report a problem, I think it will help you to improve your framework. You can fix this problem whenever you have time. I can wait for another day. No rush, no stress!

Your framwork and Proton Native are frameworks that fit my requirement. But both of them are in development process. I'm very ecited for your app.
One more time, thank you for all your work.

**Comment by leaanthony** [comment]
Hey, thanks for the report! We really appreciate feedback and are excited by how many people are taking time to report such issues. As we support Ubuntu, I'm guessing Debian would be almost identical. Is there a correlation between Debian and Ubuntu releases? I'm wondering if the package names are the same.

Your report has inspired me to open [this ticket](https://github.com/wailsapp/wails/issues/133). Keep an eye on it ;-)

**Comment by iceleo-com** [comment]
Hi @leaanthony ,

Ubuntu is built on the top of Debian, but Ubuntu dev team don't provide the version of Debian they are using. I guess they distribute their distro independently, they don't depend on Debian anymore (they have money and resources).

I have tested your framework on another PC (also Debian 9), and I still face this problem (just double test to make sure it doesn't work). And I also test your framework on Windows 10, it works well. I will test more with React. I will let you know if I get a problem.

Have a good day!

**Comment by leaanthony** [comment]
It seems.like the code to extract the disto type segfaults on docker. I've no idea why as it looks totally legit. The good news is that the dependencies are the same so it really.is just a matter of adding Debian to the known distribution list

**Comment by iceleo-com** [comment]
Hi @leaanthony,

That is the good new. You can add the distribution follow the distribution family.

- Debian/Ubuntu/Mint
- Redhat/Fedora/Cent OS
- Arch
- openSUSE

**Comment by leaanthony** [comment]
Hi @iceleo-com. This is going to be easy, but could you possibly do me a favour? I've added the ability to submit distribution support requests. I've tested on a Debian docker image (Debian 10) but would love to know if this works on a live install before adding the support itself. If you have time, the command to update to the preview version is `wails update -pre`. It should upgrade to v0.14.2-pre. If that works, we'll add the support on that ticket 👍

**Comment by leaanthony** [comment]
Superseded by #135
