### ISSUE TITLE
javascript to golang: confusing double casting is necessary for EventsOn callback

### ISSUE THREAD

**Issue by benjamin-thomas** [wailsapp/wails#1324]
### Description

Hello,

I'm testing out your tool (which I find **very** enjoyable to use: congrats), and I've hit a little nail which is possibly a bug or at least would require a little more documentation here: https://wails.io/docs/howdoesitwork#calling-runtime-methods

I'm running on `Wails CLI v2.0.0-beta.34` on Ubuntu 20.04.

I hope the screenshots below will be clear enough for you.

### To Reproduce

Following the demo, I want to report a message from the frontend to the backend as soon as I click on the `Greet` button:

![image](https://user-images.githubusercontent.com/1557738/162619996-022bc43a-7eb7-4950-9386-c17a5537b13c.png)

To do this, I trigger a custom event from the JS side:

![image](https://user-images.githubusercontent.com/1557738/162620116-64501100-36d4-4a3c-a871-d2e3f3712d7c.png)

However, after much fiddling, it seems that I have to double cast the slice of interfaces, which seems very odd

![image](https://user-images.githubusercontent.com/1557738/162620138-62b24d82-791c-4e71-9be3-bbba7054fce6.png)

![image](https://user-images.githubusercontent.com/1557738/162620149-863c24d9-93b2-436c-936b-4978e0d48bb3.png)

### Expected behaviour

Could you please clarify if this is intended behavior?

I would expect line 68 to work.

In order to extract a second argument, I found that I also had to apply the same clunky double casting to it.

So unless I'm misunderstanding something, there seems to be a buggy behavior here: casting the first item of a slice of interfaces to a slice of interfaces in order to retrieve its singular value at index zero does not make sense.

I'm getting back into golang after a few years off so I hope I'm not doing something stupid and this won't be a dumb bug report ;)

### Attempted Fixes

- google search
- search more info in the docs
- tried to find a working example in the wild via sourcegraph (did not find any)
- searched these github issues

### System Details

```shell
Wails CLI v2.0.0-beta.34


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:                     Ubuntu
Version:                20.04
ID:                     ubuntu
Go Version:             go1.18
Platform:               linux
Architecture:           amd64
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Installed       20.10.7-0ubuntu5~20.04.2
gcc             build-essential         Installed       12.8ubuntu1.1
libgtk-3        libgtk-3-dev            Installed       3.24.20-0ubuntu1.1
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.34.6-0ubuntu0.20.04.1
npm             npm                     Installed       8.5.0
*nsis           nsis                    Installed       v3.05-2
pkg-config      pkg-config              Installed       0.29.1-0ubuntu4

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

### Additional context

On a side note, I was confused by not being able to replace any mention of `interface{}` to `any` in the signature, or face a server crash and won't start.

I understood `any` is an alias to `interface{}` in go 1.18 so this is probably something you're already aware of and will fix later?

**Comment by leaanthony** [comment]
Hi Benjamin! Welcome back to Go. 
You've spotted a couple of interesting things here... It looks like the arguments *are* being returned as a `[]interface{}` but back through a variadic method. I will check this out when I have more time, but either way, changing it (even if it's wrong) is a breaking change so it needs thinking about a bit more. Wails has zero telemetry so I've no idea how many people this change would affect.
The second point about `any` is a valid catch. I'll change the reflection code to honour this. 
As a side note: If you are keen on sending structured data back to Go, consider calling a method instead. There is support for structs in calls and the latest code on `master` makes this really easy on the frontend by having TS classes generated for you.

**Comment by leaanthony** [comment]
@benjamin-thomas - I've created a PR to address the double casting issue. If you could test, it would be great to get your feedback. Thanks. https://github.com/wailsapp/wails/pull/1326

**Comment by leaanthony** [comment]
Regarding the `any` issue, Wails doesn't currently mandate go1.18 and apparently that causes a compilation issue, even if you use go1.18: https://stackoverflow.com/questions/71487498/why-do-i-get-undeclared-name-any-requires-version-go1-18-or-later-when-usin

**Comment by leaanthony** [comment]
Follow this guide: https://wails.io/docs/next/guides/bleeding-edge

**Comment by benjamin-thomas** [comment]
@leaanthony I tested [pull/1326](https://github.com/wailsapp/wails/pull/1326) it it looks good to me :+1: 

I would consider one last change: changing the type signature returned from `runtime.d.ts`.

### From this

![image](https://user-images.githubusercontent.com/1557738/163419471-9123c100-09eb-49ee-8e48-af0b162b4723.png)

![image](https://user-images.githubusercontent.com/1557738/163419610-f4eac05d-e1f4-4f37-aa09-12ff189f7334.png)

### To this

(A type hint is necessary to squash a final warning in my IDE obviously)

![image](https://user-images.githubusercontent.com/1557738/163417851-b7e095b8-e680-4b56-a95c-97a196105056.png)

![image](https://user-images.githubusercontent.com/1557738/163419337-87c07e0c-295a-49d5-ac42-d1bf30488643.png)

---

I can then use the args in this manner, which feels natural:

![image](https://user-images.githubusercontent.com/1557738/163420813-d4925025-d318-4883-8a71-1324f4639690.png)

![image](https://user-images.githubusercontent.com/1557738/163420848-bbb9d3a1-7291-4941-af7a-946063bb8243.png)

Although, as you pointed, using a function from the backend would be more appropriate here.

**Comment by leaanthony** [comment]
Thanks for the feedback and glad it works. I'll update the definition file. Part of me feels we could do more and make it work like bound methods but then it only affects JS to Go and we have method binding for that...

**Comment by leaanthony** [comment]
Just merged the PR. The `runtime.d.ts` update will happen in another PR 👍 Please close this if you are happy with the outcome

**Comment by leaanthony** [comment]
@benjamin-thomas - closing this. Please reopen if you think there is more to do.
