### ISSUE TITLE
Support `input type="file"` on Mac

### ISSUE THREAD

**Issue by jicg** [wailsapp/wails#1331]
### Description

When `input` `type` is `file`, the selected file dialog cannot pop up in `mac`, but wins can pop up.

### To Reproduce

frontend >  index.html
``` html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>test</title>
  </head>
  <body >
  <input style="margin-top: 100px" type="file">
  </body>
</html>
```

2. click `choose file`  btn

### Expected behaviour

the selected file dialog can pop up in `mac`

### System Details

```shell
System
------
OS:             MacOS
Version:        11.0.1
ID:             199506
Go Version:     go1.18
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2384
npm                             N/A             Installed       8.3.0
*upx                            N/A             Available       
*nsis                           N/A             Available
```

**Comment by leaanthony** [comment]
Looks like this is related
https://developer.apple.com/documentation/webkit/wkuidelegate/1641952-webview

**Comment by artooro** [comment]
Is this a webview bug or something that needs to be implemented in wails?
For an app I'm working on I can probably get away with the user entering the path to the file to open in a text box but seems like file select is a pretty core GUI function we're missing right now.

**Comment by leaanthony** [comment]
It's actually a Cocoa thing - it needs implementing in Objective-C

**Comment by 758F08FE920B1765** [comment]
Is there a solution?

**Comment by leaanthony** [comment]
it needs implementing in Objective-C

**Comment by KiddoV** [comment]
Now this bug is on Windows as well, as I mentioned in #2075.
Any work-around for this issue?

**Comment by stffabi** [comment]
As long as we can't reproduce it on Windows it will be very hard to investigate it.

**Comment by KiddoV** [comment]
Not sure if it is depends on the Windows version or not.
It works on my home computer:
```txt
Windows 10 Pro
Version: 21H2
OS Build: 19044.2251
```
...and not working on my work computer:
```txt
Windows 10 Enterprise LTSC
Version: 21H2
```
They are all using the same Webview2 version ``107.0.1418.42``.
If you have any idea to try to reproduce this issue, please let me know!

**Comment by leaanthony** [comment]
Maybe your work machine is locked down a bit?

**Comment by KiddoV** [comment]
Not possible, since when open the app in the Edge browser, I can use input file normally. Edge browser and Webview2 runtime should be the same right?

**Comment by KiddoV** [comment]
Found the problem that causing it. When running the app or if in dev mode running VSCode as ``administrator``, input file will not working. 
@stffabi try if you can re-produce this issue.

**Comment by leaanthony** [comment]
Editing this bug to an enhancement request.

**Comment by RichardLindhout** [comment]
Does not work in wails v3
