### ISSUE TITLE
App Proxy

### ISSUE THREAD

**Issue by Humphryyy** [wailsapp/wails#1332]
### Is your feature request related to a problem? Please describe.

When converting from Electron to Wails some users might find they need to set a proxy on the window. 

https://stackoverflow.com/questions/37393248/how-connect-to-proxy-in-electron-webview

### Describe the solution you'd like

Give access to the `CoreWebView2EnvironmentOptions` to allow modification of the `AdditionalBrowserArguments` attribute. Then you can add your own proxy argument. 

https://docs.microsoft.com/en-us/answers/questions/247173/how-to-use-proxy-for-current-version-of-webview2-1.html 

### Describe alternatives you've considered

Using [go-rod](https://github.com/go-rod/rod).

**Comment by leaanthony** [comment]
I believe this will be covered by the solution for #1507 👍
