### ISSUE TITLE
Default window cannot be dragged??

### ISSUE THREAD

**Issue by rleecn** [wailsapp/wails#1333]
### Description

Can't the app window created by wails hold the title bar and drag it like other apps?
Is there something wrong with my configuration?

### System Details

```shell
wails v2.0.0-beta.34
```

**Comment by hongbook** [comment]
I got it, I set TitlebarAppearsTransparent to true, it can only be allowed to be true.

**Comment by leaanthony** [comment]
Glad you figured it out

**Comment by Lokdex** [comment]
I would like to reopen this...
I'm just starting using wails. and in MacOS when the setting TitleBarAppearsTransparent is true as indicated before, I can't drag the window. However when setting it to false it does drag. My question/suggestion is: shouldn't it drag in both settings?

**Comment by leaanthony** [comment]
Is your intent to have a window and see the webview content underneath but still be able to drag it?

**Comment by leaanthony** [comment]
I'm going to close this as working as intended. If `TitleBarAppearsTransparent` is true then it is the equivalent of `HideTitlebar = true && FullSizeContent = true`. 

From Apple's own `NSWindow.h` comments:
```
/* When YES, the titlebar doesn't draw its background, allowing all buttons to show through, and "click through" to happen. In general, this is only useful when NSFullSizeContentViewWindowMask is set.
 */
@property BOOL titlebarAppearsTransparent API_AVAILABLE(macos(10.10));
```
The default template is unfortunately defaulting to a non-drag state. This is fixed on master. See https://github.com/wailsapp/wails/issues/1346 for a workaround. I will update the docs to make these settings clearer 👍

**Comment by Lokdex** [comment]
Regarding your first answer yes, my intent is to see the content underneath and still be able to drag, since the title of the window is still visible. And thanks for the update and extra comment, will check it out!
