### ISSUE TITLE
Use Algolia search

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1338]
### Is your feature request related to a problem? Please describe.

The current search uses local indexes which load slowly on mobile. The initial attempt to use Algolia search due to some index issues with docusaurus.

### Describe the solution you'd like

Use Algolia

**Comment by leaanthony** [comment]
The message I got from support:

> I have checked the shared link, and it looks the following filters applied to your query is causing the empty result.
> By removing them, I could retrieve search results from the wails index.
>  
> "docusaurus_tag:default"
> "docusaurus_tag:docs-default-current"
>
> At this point, I recommend checking the index settings to ensure you have the "docusaurus_tag" attribute in the [attributesForFaceting](https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/) parameter there.
> I also recommend adding it in the [initialIndexSettings](https://www.algolia.com/doc/tools/crawler/apis/configuration/initial-index-settings/) in your Crawler config if you haven't added it.

**Comment by leaanthony** [comment]
Related: https://discourse.algolia.com/t/algolia-searchbar-is-not-working-with-docusaurus-v2/14659/2

**Comment by merlindru** [comment]
I think the search indexing is broken right now. 
![image](https://user-images.githubusercontent.com/85179170/211149708-e64edcc0-75c8-40f4-a197-316502ded4c5.png)

Shouldn't this show me _anything_ about the frameless option? It feels like only the changelog is indexed, the actual docs arent

**Comment by merlindru** [comment]
![image](https://user-images.githubusercontent.com/85179170/211149763-3f196013-5dcc-4b5e-a187-0cf79e4bc60f.png)

![image](https://user-images.githubusercontent.com/85179170/211149793-3f734b2d-784c-4f0c-9629-10305f2b644b.png)


Another couple examples -- "Documentation" really is just the changelog

**Comment by leaanthony** [comment]
Yeah, we never had much luck with algolia. Do you know of any alternatives?

**Comment by merlindru** [comment]
Honestly algolia is awesome IMO, it might just be misconfigured. An alternative is meilisearch which is open source but just got a cloud option

**Comment by leaanthony** [comment]
I'll try having a look at it again. Last time it confused the hell out of me 😓
