### ISSUE TITLE
Some very important features are expected to be supported in the official release.

### ISSUE THREAD

**Issue by rleecn** [wailsapp/wails#1341]
### Describe the solution you'd like

It is hoped that the officially released version can support:
1. Tray.
2. Notice.
3. Power event detection (including screen lock, sleep and shutdown).
4. Network change status and change detection.
5. The event contents at both ends of JS and go are easier to handle. At present, it is very troublesome to parse.
6. Audio playback. I introduced audio into Vue, but it can't be played. I don't know why. Web page access is OK.
7. Multiple windows can be supported.

**Comment by leaanthony** [comment]
There are already tickets for some of these. If you want to open a bug report for audio, feel free to do so. (5) is fixed on master. (3/4) can be done using Go libraries so won't be part of Wails.
