### ISSUE TITLE
Is BrowserOpenURL broken?

### ISSUE THREAD

**Issue by benjamin-thomas** [wailsapp/wails#1342]
### Description

Hello,

I'm trying to open a link from my wails app, in the user's default browser.

I understand the `BrowserOpenURL` JS function would be appropriate here: https://wails.io/docs/next/reference/runtime/browser

So I setup an event listener:

```javascript
document.body.addEventListener("click", function (e) {
            if (e.target && e.target.nodeName === "A") {
                e.preventDefault();
                console.log("Capturing link:", e.target.innerText);
                // window.wails.BrowserOpenURL(e.target.href);
                BrowserOpenURL(e.target.href); // VM118:1 Uncaught TypeError: window.wails.BrowserOpenURL is not a function
            }
        });
```

But the function is undefined

### To Reproduce

Not applicable

### Expected behaviour

Could you document a little more how to use this function? Or did I misunderstand its purpose? Is it possible to open a link with the user's default browser?

Thanks

### System Details

```shell
Wails CLI v2.0.0-beta.34

System
------
OS:                     Ubuntu
Version:                20.04
ID:                     ubuntu
Go Version:             go1.18
Platform:               linux
Architecture:           amd64
Package Manager:        apt
```
```


### Additional context

_No response_

**Comment by leaanthony** [comment]
Hey @benjamin-thomas. You can run all these if you use a `window.runtime` prefix (https://wails.io/docs/next/reference/runtime/intro) but it's easy to miss in the docs (I'll look at fixing that). The Go part of wailsjs got a lot of love recently so I'll look at doing the same for runtime. I'll get a fix up tonight which will allow you to do: 

```js
import {BrowserOpenURL} from "../wailsjs/runtime";
```

**Comment by misitebao** [comment]
This function may need a return value to tell the user the feedback from the call.👀

**Comment by benjamin-thomas** [comment]
Awesome, thanks @leaanthony

I think it's ok to close, hope you don't mind @misitebao :)

**Comment by leaanthony** [comment]
Hey @benjamin-thomas - I just pushed the updates to master. If you install that version, run `wails generate module` in your project directory and your `wailsjs` directory should be updated. You should then be able to use the bindings and runtime accordingly:

![image](https://user-images.githubusercontent.com/1943904/163997902-3114aacf-8952-41de-9d6f-2b796874ecd3.png)

**Comment by benjamin-thomas** [comment]
Thanks @leaanthony  :+1: 

It looks good, though I had a few problems with the latest commit.

I won't bore you with the details though, since I'm probably misunderstanding a few things right now to give valuable feedback.

**Comment by leaanthony** [comment]
No worries. If there's something you're not getting then I consider that a documentation issue. Either open a ticket or have a casual chat on the slack forum 👍
