### ISSUE TITLE
[v2 bug] the wailsjsdir option won't take affect in the wails.json On Winodws

### ISSUE THREAD

**Issue by Baiyuetribe** [wailsapp/wails#1343]
### Description

[v2 bug] the wailsjsdir option won't take affect in the wails.json on windows. same issues on #1119

### To Reproduce

Steps to reproduce the behaviour:

```
1.just modify wails.json and change wailsjsdir
2.wails build
```

### Expected behaviour

 wailsjs directory generate in the `frontend/src`, but not

### System Details

```shell
Wails CLI v2.0.0-beta.34


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro for Workstations
Version:        2009 (Build: 22598)
ID:             22H2
Go Version:     go1.17.8
Platform:       windows
Architecture:   amd64
```

**Comment by leaanthony** [comment]
It actually does as I just tested it. What doesn't happen, is a rebuild of the directory during a `wails build`, but does during `wails dev`. I'm wondering if that's what's needed here.

**Comment by Baiyuetribe** [comment]
`WailsJSDir` is just a temporary file, `dev` mode works fine, `build` mode is buggy.
in the dev.go
```
	if flags.wailsjsdir == "" && projectConfig.WailsJSDir != "" {
		flags.wailsjsdir = projectConfig.WailsJSDir
	}

	if flags.wailsjsdir == "" {
		flags.wailsjsdir = "./frontend"
	}

	if flags.wailsjsdir != projectConfig.WailsJSDir {
		projectConfig.WailsJSDir = filepath.ToSlash(flags.wailsjsdir)
	}
```
but in build.go, Something seems to have been omitted
```
	// wails js dir
	if projectData.WailsJSDir != "" {
		options.WailsJSDir = projectData.WailsJSDir
	}
```
Expect to fix or hide this temporary folder
