### ISSUE TITLE
[v2]MacOS Window can't be moved

### ISSUE THREAD

**Issue by darrenparkinson** [wailsapp/wails#1346]
### Description

On initialising a brand new application and running it, the window/app is not movable.  It cannot be dragged around the screen.

### To Reproduce

1. Run `wails init -n wails-demo`
2. Run `cd wails-demo`
3. Run `wails dev`

### Expected behaviour

I expected the window to behave normally and allow me to drag it around the screen.

### Attempted Fixes

* I tried `wails build` to see if that made a difference.
* I checked the `wails.Run` options to see if anything there might prevent it.
* I quit the `rectangle` app in case that was interfering
* I removed any sizing in the options which allows me to resize the window, but still it can't be moved.

* If I drag another window over the top of it but allow some of the top bar of the wails app to still be visible, then grab it, sometimes it will move.

### System Details

```shell
Wails CLI v2.0.0-beta.34


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.2.1
ID:		199506
Go Version:	go1.18.1
Platform:	darwin
Architecture:	arm64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2392
npm 				N/A		Installed	8.1.2
*upx 				N/A		Available
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by darrenparkinson** [comment]
I did a quick screen recording for reference: https://youtu.be/TdP6MOnp9dE

**Comment by leaanthony** [comment]
Hi! Looks like there was an update to the default template which means the default titlebar config (indirectly) doesn't allow dragging. If you want a titlebar, update the config as below.

```go
Mac: &mac.Options{
            TitleBar: &mac.TitleBar{
                TitlebarAppearsTransparent: true, // Set to false
                HideTitle:                  false,
                HideTitleBar:               false,
                FullSizeContent:            false,
                UseToolbar:                 false,
                HideToolbarSeparator:       true,
            },
```
If you want a transparent titlebar but still want drag, add `data-wails-drag` to any HMTL element you want to act as draggable. This is fixed on `master`. 👍

**Comment by darrenparkinson** [comment]
Great, thanks. I’ll give that a go.
