### ISSUE TITLE
[V2] How to get WindowState?

### ISSUE THREAD

**Issue by zandercodes** [wailsapp/wails#1348]
### Is your feature request related to a problem? Please describe.

I am using a frameless window and want to access the status when the window is minimized, maximized or normal.
I have seen that in the code there is `WindowStartState` which determines how the window is started.
There must be a way to get the state of the window.

### Describe the solution you'd like

There must be a way to retrieve the current status of the window.
It would be good if this could be retrieved under `runtime`.

Thanks a lot.

**Comment by leaanthony** [comment]
Great request and easy to do. Will look at it over the next couple of days

**Comment by leaanthony** [comment]
I think I'll bundle callbacks for window state change in this ticket 👍

**Comment by leaanthony** [comment]
Bumping this to v2.1

**Comment by afocus** [comment]
Custom title bars need this to sync the state of the action buttons
