### ISSUE TITLE
Support Distribution 'Debian'

### ISSUE THREAD

**Issue by iceleo-com** [wailsapp/wails#135]
**Description**
Distribution 'Debian' is curently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.16.1-pre |
| Go Version    | go1.12.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | Debian |
| Distribution Version   | 9.9 |
| Discovered by   | lsb |

Hi,

I'm here. I'm not sure this is your expected or not.
And I also got a warning, if you have time to look at it
`Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"`

Thank you for your work.

**Comment by bh90210** [comment]
hi @iceleo-com actually this is being worked :) Hopefully in a couple of days the debian issue will be resolved.
Please have a look at this #132 similar issue.

**Comment by leaanthony** [comment]
This is fantastic! Thanks for taking the time to try this out!

Regarding the warning, it looks like a local error to do with your browser installation not finding fonts.

I will add Debian support right now.

**Comment by leaanthony** [comment]
`wails update -pre` to v0.16.3-pre for Debian support 👍 Let us know!

**Comment by leaanthony** [comment]
![image](https://user-images.githubusercontent.com/1943904/60084291-9437cd00-977a-11e9-8f46-95dd0d4448a7.png)

**Comment by iceleo-com** [comment]
Hi @leaanthony ,

I have tested the new version. It can initialize a project, but when I ran "wails build", then I ran the binary file. I only saw the blank screen, please see screenshot  https://i.imgur.com/B2Ngdlp.png

I also tried "wails serve" to check JS code on a browser and I got this issue https://i.imgur.com/NMPaxlq.png

**Comment by leaanthony** [comment]
Aaaah the price of bleeding edge! Thanks for reporting this. It's a side effect from another recent commit. It'll be fixed today 👍

**Comment by leaanthony** [comment]
Hi @iceleo-com, could you please paste the contents of `go.mod` in your generated project please? Thanks!

**Comment by leaanthony** [comment]
I think this now has been fixed (I was able to reproduce and fix). Please try `wails update -pre` to get v0.16.4-pre and this should fix the issue 👍

**Comment by iceleo-com** [comment]
Hi @leaanthony ,

I have tested the version v0.16.4-pre. It works well.
I will test more at the end of this week. If I found something wrong, I will let you know.
Thank you. You're doing a great job, sir!
