### ISSUE TITLE
Ignore the ssl certificate verify

### ISSUE THREAD

**Issue by chenxiao1990** [wailsapp/wails#1350]
### Is your feature request related to a problem? Please describe.

in h5  i  wan't  request wss://192.168.xxx.xxx   , no Officially signed ssl certificate.

### Describe the solution you'd like

can set webview to Ignore  ssl certificate verify

**Comment by leaanthony** [comment]
Please add platform you are using

**Comment by chenxiao1990** [comment]
Platform:       windows

**Comment by leaanthony** [comment]
I believe this will covered by whatever solution we use for #1507 👍
