### ISSUE TITLE
Function with no return exported from app.go creates App.js & App.d.ts entries that return a Promise

### ISSUE THREAD

**Issue by ianmjones** [wailsapp/wails#1355]
### Description

In `master` (moved on from `2.0.0-beta.34`) we now have the ability in the frontend JS to `import` functions from `wailsjs/go/main/App.js`, which awesome! :tada: 

For a Go function like follows...

```go
// Ping expects pong or another supplied response from the dbus service.
func (a *App) Ping(expected string) (string, error) {
	return a.serv.Ping(expected)
}
```

... App.js has ...

```js
export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}
```

... and the companion App.d.ts has the expected ...

```ts
export function Ping(arg1:string):Promise<string|Error>;
```

However, for a Go function that has no return ...

```go
// ShowError displays an error message in a desktop dialog.
func (a *App) ShowError(title string, message string) {
	_, _ = runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.ErrorDialog,
		Title:   title,
		Message: message,
	})
}
```

... the App.js looks like ...

```js
export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}
```

... with companion App.d.ts like ...

```ts
export function ShowError(arg1:string,arg2:string):Promise<void>;
```

This means that the function that never returns anything usable has to have a `Promise` handled when called, which feels a bit weird to me.

### To Reproduce

See description.

### Expected behaviour

If an exported Go function bound to the App instance has no return, I would not expect the App.d.ts to specify that a Promise is being returned, and ideally App.js would not use a return at all.

In the generated `wailsjs/runtime/runtime.js` some exported functions do not use a return:

```js
export function LogPrint(message) {
    window.runtime.LogPrint(message);
}
```

The companion `runtime.d.ts` is as expected, and does not specify a return type (well, just `void`):

```ts
// [LogPrint](https://wails.io/docs/reference/runtime/log#logprint)
// logs the given message as a raw message
export function LogPrint(message: string): void;
```

It would be great if `App.go` functions that do not return anything could also have a `void` return in the `App.d.ts` and no actual return in `App.js`.

### System Details

This is probably not very helpful as it's from a custom build of wails on NixOS from commit `75ee36f8ebf484bd91cf2591b00af7ce6cd4e21a`, but here it is anyway...

```shell
Wails CLI v2.0.0-beta.34


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             NixOS
Version:        22.05
ID:             nixos
Go Version:     go1.17.7
Platform:       linux
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.34

Dependency      Package Name    Status  Version
----------      ------------    ------  -------

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Nice find Ian! That should be reasonably easy to fix 👍
