### ISSUE TITLE
Cannot use go binding method[beta.35]

### ISSUE THREAD

**Issue by daoif** [wailsapp/wails#1357]
### Description

The go binding method cannot be used for projects created with vue-ts template

### To Reproduce

wails init -n myproject -t vue-ts
wails dev
open "http://localhost:3000/"
Press F12
click Console
click "greet"
Error message:
Uncaught TypeError: Cannot read properties of undefined (reading 'main')
    at Greet (App.js:6:22)
    at greet (HelloWorld.vue:11:3)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:369:13)

### Expected behaviour

output:Hello %s, It's show time!

### Screenshots

![image](https://user-images.githubusercontent.com/46199660/165749859-5335a45a-fa89-4eb8-aa55-50c3c4190a8d.png)

### System Details

```shell
Wails CLI v2.0.0-beta.35


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2021
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.35

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       100.0.1185.50
npm             N/A             Installed       8.1.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency
```

**Comment by daoif** [comment]
> 
I'm in wails JSON added "devserver":“ http://localhost:34115 "
but i can't open localhost:34115

**Comment by daoif** [comment]
@leaanthony

**Comment by stffabi** [comment]
The devServer property must be of the form 'host:port' since beta.35. So your wails.json should look like this:

```json
"devServer": "localhost:34115",
```

You could also just remove the entire property and Wails will use the default value. Currently wails will only output a log error when the value is wrong, I've created PR #1359 to check the value and prevent starting `wails dev`.

**Comment by daoif** [comment]
@leaanthony  @stffabi  
I use the Vue template: wails dev

I can start the wails window

But I use the Vue TS template: wails dev

Unable to start the wails window
please help me

**Comment by leaanthony** [comment]
Do you know why the lack of skipLibCheck breaks it?

**Comment by daoif** [comment]
@leaanthony 
When there is no "--skipLibCheck"
CLI: wails build
CLI log: "
> vue-tsc --noEmit  && vite build

    node_modules/@babel/parser/typings/babel-parser.d.ts(14,23): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@babel/parser/typings/babel-parser.d.ts(22,23): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(1,57): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(2,45): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(4,33): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(5,37): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(6,37): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.
    node_modules/@vue/compiler-core/dist/compiler-core.d.ts(8,30): error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.


Error: exit status 2


ERROR: exit status 2"

------------------
There is no error in IDE, but vue-tsc will report an error during build, resulting in build failure. Therefore, 34115 cannot be pulled up during wails dev

I don't know exactly what's going on. It may be the conflict between wails and Vue TSC, or the problem of Vue TSC itself

Because I'm in beta The code written in version 34 does not have Vue TSC when using the template to build and can be compiled normally. However, when I use Vue TSC, the vue3 typing template refs I wrote myself does not report an error in the IDE, but Vue TSC reports an error

So in my own code, I directly disabled Vue TSC, and everything worked normally

https://vuejs.org/guide/typescript/composition-api.html#typing-template-refs

**Comment by renhongwu** [comment]
wails dev
等到日志打印出：
To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
