### ISSUE TITLE
Cant not load localhost:34115 in app use wails dev [bate.35]

### ISSUE THREAD

**Issue by daodao97** [wailsapp/wails#1358]
### Description

wails dev get error in webview console

`Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

### To Reproduce

wails init -n myproject
cd myproject
wails dev

### Expected behaviour

load localhost:34115

### Screenshots

![image](https://user-images.githubusercontent.com/15009280/165769831-f6d5e927-d3c8-461d-944e-7d9db0fde90e.png)

### System Details

```shell
Wails CLI v2.0.0-beta.35


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	11.6
ID:		199506
Go Version:	go1.17.2
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.35

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2384
npm 				N/A		Installed	8.0.0
*upx 				N/A		Installed	upx 3.96
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by stffabi** [comment]
Thanks for reporting this issue. I have a couple of questions, which hopefully allows to narrow down the problem.

- Are you able to open `http://localhost:34115` in Safari?
- Could you please provide a screenshot of the DevTools network tab, after triggering a reload?
- Could you also provide a screenshot of the Response Headers of the requests from the DevTools network tab?

Thanks for your help.

**Comment by stffabi** [comment]
Seems like we probably need to make changes to the info.plist, [Fine-tune your App Transport Security settings](https://developer.apple.com/news/?id=jxky8h89)

Interestingly I have never seen that on MacOS 12 during the development of the frontend devserver feature. @leaanthony did you encounter that?

**Comment by leaanthony** [comment]
It would be good to add this to the [TroubleShooting Guide](https://wails.io/docs/guides/troubleshooting)

**Comment by stffabi** [comment]
Thanks @daodao97 for the report of the segfault. Could you please give PR #1362 a try? That should fix the issue.

**Comment by daodao97** [comment]
> Thanks @daodao97 for the report of the segfault. Could you please give PR #1362 a try? That should fix the issue.

Thanks, it is working.

**Comment by stffabi** [comment]
Awesome, thanks for testing.

**Comment by bbaobelief** [comment]
Upgrade from go 1.21 to go 1.22.10 to solve the problem

➜ go version
go version go1.22.10 darwin/arm64
