### ISSUE TITLE
wails update -pre error

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#136]
**Description**
cannot determine module path for source directory (outside GOPATH, no import comments)

**To Reproduce**
Steps to reproduce the behaviour:
1. install & setup wails 0.16.0
2. run `wails update -pre`
3. See error

**Expected behaviour**
Update to latest -pre release

**Screenshots**
```bash
$ wails update -pre
Wails v0.16.0 - Checking for updates...

✓ Checking for updates...

    Current Version : v0.16.0
  Latest Prerelease : v0.16.2-pre

⣽ Installing Wails v0.16.2-prego: cannot determine module path for source directory /home/bh90210 (outside GOPATH, no import comments)

✗ exit status 1
Error: exit status 1
```

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.16.0 |
| Go Version    | go1.12.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | auto |

**Additional context**

**Comment by leaanthony** [comment]
Does this happen if GO111MODULE=on?

**Comment by bh90210** [comment]
yes

**Comment by bh90210** [comment]
`go get` doen't work in general, it seems 100% on my side, I am closing for now, if it turns out wails had anything to do or benefit somehow from ubuntu experience feedback will comment or reopen.

**Comment by bh90210** [comment]
I believe I fixed everything on my part, I get to use go get for other software as expected.
still `wails update -pre` fails me with the same error
```bash
$ wails update -pre
Wails v0.16.0 - Checking for updates...

✓ Checking for updates...

    Current Version : v0.16.0
  Latest Prerelease : v0.16.4-pre

⣽ Installing Wails v0.16.4-prego: cannot determine module path for source directory /home/bh90210 (outside GOPATH, no import comments)

✗ exit status 1
Error: exit status 1
```

I am not opening the ticket as I still believe it might be me, since everybody else seems to be able to use `-pre` normally. 

BUT
```bash
~$ GO111MODULE=on go get github.com/wailsapp/wails/cmd/wails
go: cannot determine module path for source directory /home/bh90210 (outside GOPATH, no import comments)
```
and 
```bash 
$ GO111MODULE=off go get github.com/wailsapp/wails/cmd/wails
```
works!!!! wtf is happening?!
