### ISSUE TITLE
context is nil

### ISSUE THREAD

**Issue by AlexBitsTech** [wailsapp/wails#1364]
### Description

with the v2.0.0-beta.35 on Windows 10, I get a context is nil error whenever I try to access app.ctx in go code. This problem was not present in the v2.0.0-beta.34.

### To Reproduce

1. Make a wails app on Windows 10 with the svelte-ts template.
2. Make any button on the front-end
3. Link that button with any go function that calls a function needing the ctx parameter (`runtime.Quit(a.ctx)` for example)
4. Watch the terminal complain that context is nil

### Expected behaviour

As in the previous versions, I would expect the context to not be nil.

### Attempted Fixes

This can be easily fixed by adding the `OnStartup: app.startup,` struct option in main.go and adding
```
func (a *App) startup(ctx context.Context) {
    a.ctx = ctx
}
```
in the app.go file . 
This option, and many others, were present by default in previous versions but have disappeared from this one.

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.35

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       100.0.1185.50
npm             N/A             Installed       8.5.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment]
Yeah, this isn't a bug and the docs are clear on what to do but yeah, that should be in by default I guess

**Comment by AlexBitsTech** [comment]
This is in no way criticism on my part :) 
The bug label should have been an enhancement label maybe?
If this is a wanted behavior then by all means keep it that way.
I would just suggest that setup (be it startup or onDomReady) on the go side would be very common as the front is limited in some respects (access to OS info or paths for example in my case). Having it by default is helpful. It's easier to delete functions than to add them after reading the docs :P

**Comment by leaanthony** [comment]
I've updated the templates on master 👍
