### ISSUE TITLE
Post build external access

### ISSUE THREAD

**Issue by daoif** [wailsapp/wails#1367]
### Describe the solution you'd like

Can I access it through WebView  of other programs or browser after production build?

**Comment by leaanthony** [comment]
@tmclane

**Comment by NubeDev** [comment]
Ya this would be cool! Saves building a desktop app and browser app

**Comment by tmclane** [comment]
Looking to bring this in during the 2.1 timeframe.  Going to open an MR with the beginnings as soon as I finish cleaning up and arranging my work.  I dislike throwing everything in a single commit.
