### ISSUE TITLE
How to check app window is fullscreen

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#1379]
### Describe the solution you'd like

`
package runtime

func WindowIsFullScreen(ctx context.Context) bool
`

or provide two trigger

`
package options

type App struct {
...
OnFullscreen      func(ctx context.Context)
OnUnfullscreen  func(ctx context.Context)
...
}
`

**Comment by stffabi** [comment]
Thanks for your feature request. That functionality should be coming with PR #1349 , which is currently WIP.

**Comment by leaanthony** [comment]
Hey there 👋 There's a PR open for this that's being worked on. Would appreciate your input into that. Am on mobile so can't link right now. Cheers. 👍

**Comment by leaanthony** [comment]
Would appreciate your input into the PR 👍

**Comment by leaanthony** [comment]
Thanks for the kind feedback. Let us know how we can make it even better 👍

**Comment by kroksys** [comment]
Created my first project with wails - finally some good GUI library for go! Thanks for a good work!
Eager to get ```IsFullscreen``` function.

**Comment by leaanthony** [comment]
This is a duplicate of #1348. There's a draft PR open for this functionality. Please leave comments there. Thanks.
