### ISSUE TITLE
Blazor WebAssembly

### ISSUE THREAD

**Issue by stepro71** [wailsapp/wails#1396]
### Describe the solution you'd like

I wrote a go program where I can host a compiled WebAssembly in one binary (exe on windows). 
like so:
//go:embed wwwroot
//go:embed wwwroot/index.html
//go:embed wwwroot/_framework

var embeddedFiles embed.FS

func main() {

	fsys, err := fs.Sub(embeddedFiles, "wwwroot")
	if err != nil {
		panic(err)
	}

	http.Handle("/", http.FileServer(http.FS(fsys)))
	http.ListenAndServe(":8050", nil)
}
How would I incorporate this in an wails app?

**Comment by stffabi** [comment]
Thanks for opening this issue and using Wails.

You can pass your 'fsys' in [Options.Assets](https://wails.io/docs/reference/options#assets) when starting the App. So the App is going to use your embedded files, you don't need to start a local server to let Wails use your files.

**Comment by stepro71** [comment]
This was very easy, I was able to do this with your explanation, thank you very much!
