### ISSUE TITLE
The generated wailsjs/runtime/runtime.js is not correct.

### ISSUE THREAD

**Issue by huangruncheng** [wailsapp/wails#1397]
### Description

The generated wailsjs/runtime/runtime.js is not correct.

export function EventsOn(eventName, callback) {
    OnMultiple(eventName, callback, -1);
}

The function 'OnMultple' should be 'EventsOnMultiple'.

### To Reproduce

Uncaught ReferenceError: OnMultiple is not defined at EventsOn (runtime.js:44:5)

### Expected behaviour

Listen for events from go in JS, but ReferenceError occurred.

### Attempted Fixes

After modifying 'OnMultiple' to 'EventsOnMultiple' in DevTools, the problem is solved.

### System Details

```shell
Wails CLI v2.0.0-beta.36


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home China
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.18.2
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.36

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.39
npm             N/A             Installed       8.3.1
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by stffabi** [comment]
Thanks for opening this issue and using wails.

This issue has already been fixed on master. Please see the "Bleeding edge" guide in the docs for updating to the latest master version.

**Comment by stffabi** [comment]
@huangruncheng did it work for you and could we close the issue?

**Comment by stffabi** [comment]
This should be fixed with the latest release. Please feel free to reopen the issue if you are still experiencing this issue.
