### ISSUE TITLE
hope add Restart in runtime

### ISSUE THREAD

**Issue by daodao97** [wailsapp/wails#1399]
### Describe the solution you'd like

In some cases we expect the user to be able to restart the app while doing something

so hope can add `runtime.Restart(ctx context.Context)` method

**Comment by leaanthony** [comment]
It depends on what you mean by restart. You could reload the frontend...? What are the scenarios?

**Comment by daodao97** [comment]
sorry,  the mean is reopen app, not `WindowReload`

**Comment by leaanthony** [comment]
Try this https://forum.golangbridge.org/t/how-to-restart-self/5061/2

**Comment by daodao97** [comment]
Thanks!
