### ISSUE TITLE
need NewWindow method

### ISSUE THREAD

**Issue by mymickey** [wailsapp/wails#1401]
### Is your feature request related to a problem? Please describe.
i use v2

sorry,i not found how to create new the webview/window at the API doc in wails.io when i want to pop a new create 
 webview/window go to google auth login,then google login was success, then close it, then back to main window

### Describe the solution you'd like

integration google login https://developers.google.com/identity/sign-in/web/sign-in

### Describe alternatives you've considered
i need a API, such as wails.NewWindow
i need a example such as window event callback
_No response_

**Comment by leaanthony** [comment]
If you search the issue tracker and forums for OAuth, you'll find a solution. We'd like to make this easier though

**Comment by leaanthony** [comment]
If your request is for a new window then please close this and create a new issue. I'm surprised there's not an open ticket for it already as there's been plenty of tickets for this. If you do create the ticket, please state how you think it'll work, including eventing, assets, dialogs, inter-window communication, dev mode and everything that comes with it. It would be great to have someone own this 👍
