### ISSUE TITLE
[V2] void function need to return Promise

### ISSUE THREAD

**Issue by ironpark** [wailsapp/wails#1408]
### Is your feature request related to a problem? Please describe.

``` js
export function A() {
  window['go']['main']['App']['A']();
}
export function B() {
  window['go']['main']['App']['B']();
}
```

If the function does not have a return value, the generated js code has no return value, and the "Promise" object is not exposed, so the scenario of executing function B after function A is complete is impossible.

``` js
await A()
await B()
```
OR
``` js
A().then(()=>{
  B()
})
```

### Describe the solution you'd like

Changed so that the generated js function returns a result even if the binding target (Go function) is void

``` js
export function A() {
  return window['go']['main']['App']['A']();
}
export function B() {
  return window['go']['main']['App']['B']();
}
```

**Comment by leaanthony** [comment]
Thanks for opening this @Ironpark - Can you please test the PR https://github.com/wailsapp/wails/pull/1410
