### ISSUE TITLE
[v2] support for linux/arm

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#1411]
### Is your feature request related to a problem? Please describe.

I have a some Raspberry Pi 3 Model B devices used in "kiosk mode". Currently running programs made with Electron. I would really like to replace Electron with Wails, but Wails V2 only supports linux/arm64.

### Describe the solution you'd like

I would like Wails to support linux/arm out of the box.

### Describe alternatives you've considered

I was able to make linux/arm compile and work, but my solution is not really nice. I'm not really versed in CGO.

How I made it work:

1. "enabled" the linux/arm platform by adding "linux/arm" to the build command.
```
v2/cmd/wails/internal/commands/build/build.go#L232

// Check platform
validPlatformArch := slicer.String([]string{
	...
	"linux",
	"linux/amd64",
	"linux/arm64",
	"linux/arm", <- here
	...
})
```

This resulted in two errors:

```
../../go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/desktop/linux/responsewriter.go:87:79: cannot use _Ctype_long(contentLength) (value of type _Ctype_long) as type _Ctype_longlong in variable declaration

../../go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/desktop/linux/window.go:867:41: cannot use (_Ctype_ulong)(arraySize) (value of type _Ctype_ulong) as type _Ctype_uint in argument to (_Cfunc_allocFileFilterArray)
```

2. Changed the cast of the contentLength variable in the linux/responsewriter

```
v2/internal/frontend/desktop/linux/responsewriter.go#L87

from: 
C.webkit_uri_scheme_request_finish(rw.req, stream, C.long(contentLength), cMimeType)

to:
C.webkit_uri_scheme_request_finish(rw.req, stream, C.int64_t(contentLength), cMimeType)
```

3. Fixed the types for window/OpenFileDialog

```
v2/internal/frontend/desktop/linux/window.go#L867

from:
data.filters = C.allocFileFilterArray((C.ulong)(arraySize))
filters := (*[1 << 30]*C.struct__GtkFileFilter)(unsafe.Pointer(data.filters))

to:
data.filters = C.allocFileFilterArray((C.uint32_t)(arraySize))
filters := (*[1 << 25]*C.struct__GtkFileFilter)(unsafe.Pointer(data.filters))

```

With these modifications I'm able to work with these older devices, but its quite a hack.

The change in the responsewriter works on linux/amd64 without any problem, but the C.allocFileFilterArray() breaks on the same type problem, but the other way around...

### Additional context

go's version is: go1.18.2 / linux-armv6l

```
System
------
OS:		Raspbian GNU/Linux
Version: 	10
ID:		raspbian
Go Version:	go1.18.2
Platform:	linux
Architecture:	arm

Wails
------
Version: 		v2.0.0-beta.36
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Available	18.09.1+dfsg1-7.1+rpi1+rpt1
gcc		build-essential		Installed	12.6
libgtk-3	libgtk-3-dev		Installed	3.24.5-1+rpt2
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.36.0-3~deb10u1+rpi1
npm		npm			Installed	6.14.12
*nsis		nsis			Available	3.04-1
pkg-config	pkg-config		Installed	0.29-6

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis

```

**Comment by leaanthony** [comment]
Thanks for opening this and I'd love to support this architecture. I know @tmclane has a similar requirement but I think the boards he uses are `arm64`. If your changes do enough to get you where you want, I'd be happy to accept a PR and tag it as experimental

**Comment by Lyimmi** [comment]
Thanks, I'll try to make PR without duplicating the whole file for 2 lines.

**Comment by stffabi** [comment]
I think we are using not the exact types as specified by the docs or in the C code.
You should be able to fix those by using 'C.gint64' for the responsewriter and 'C.size_t' in the allocFileFilterArray case.
That should work on all platforms.

**Comment by leaanthony** [comment]
That would be amazing. Thanks @stffabi !

**Comment by Lyimmi** [comment]
Thanks @stffabi, I'll try it as soon as I have time!

**Comment by Lyimmi** [comment]
I tried @stffabi's recommendations, it works on amd64 and arm as well.
However on arm `filters := (*[1 << 30]*C.struct__GtkFileFilter)(unsafe.Pointer(data.filters))` still throws an error:

```
/internal/frontend/desktop/linux/window.go:868:50: type [1073741824]*_Ctype_struct__GtkFileFilter too large
```

If I lower the array's size to [1 << 28] it works on both, but i can't tell if it will cause any problems on amd64, or arm64.

**Comment by stffabi** [comment]
Great the two casts work. 
Oh sorry about the shift one, I have somehow overlooked that. I'll have to take a look into it to support you with a solution for that one...

**Comment by stffabi** [comment]
I assume it could just be [arraySize] instead of the shifting. Using arraySize should also allow go runtime to check the correct boundaries.
I haven't tested it yet, cause I'm currently away from my pc.

**Comment by stffabi** [comment]
`[arraySize]` is not possible in this case since the compiler can't get a slice on top of that native pointer. It can only get an array on top of that and therefore a constant size is needed.

Since go 1.17 there's a new way to get a slice on top of a native pointer, the following would do the trick.
```go
filters := unsafe.Slice((**C.struct__GtkFileFilter)(unsafe.Pointer(data.filters)), arraySize)
```

This needs go 1.17 as minimum build requirement. Since go 1.16 and older aren't supported anymore by the go team, I think we could probably bump the minimum requirement to go 1.17. What do you think @leaanthony ?

**Comment by leaanthony** [comment]
💯!!

**Comment by Lyimmi** [comment]
I tried @stffabi's unsafe.Slice() solution and it works both on linux/amd64 and linux/arm.

**Comment by leaanthony** [comment]
Awesome!

**Comment by stffabi** [comment]
Great, thanks for trying it out. I've also seen we already require Go1.17+ in our docs, so we could go ahead and use this new function.

**Comment by Badboyboom** [comment]
https://github.com/wailsapp/wails/issues/new/choose
