### ISSUE TITLE
I want an option to not run `wails generate module` when running `wails dev`.

### ISSUE THREAD

**Issue by mondy** [wailsapp/wails#1412]
### Is your feature request related to a problem? Please describe.

I want to run `wails generate module` only when there is an update of the relevant files.
However, when you run `wails dev`, it always runs `wails generate module`.

### Describe the solution you'd like

I would like an option to not run `wails generate module`.

**Comment by leaanthony** [comment]
Thanks for opening this. Very happy to accept a PR if you want to add it. Perhaps using a `-nogen` flag?

**Comment by stffabi** [comment]
PR has been merged.
