### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by PungYoung** [wailsapp/wails#1422]
### Description

OS: windows10
wails: v2.0.0-beta.35
run "wails dev" error：The process cannot access the file because it is being used by another process.
run "wails build" is ok，other computer run "wails dev" also ok.

### To Reproduce

1. wails dev

### Expected behaviour

running "wails dev"

### System Details

```shell
output:
`
E:\atools>wails dev
Wails CLI v2.0.0-beta.36


Executing: go mod tidy -compat=1.17
Executing: wails generate module


ERROR: remove C:\Users\ADMINI~1\AppData\Local\Temp\wailsbindings.exe: The process cannot access the file because it is being used by another process.

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony


exit status 1
`
```

**Comment by yangpeng1994** [comment]
I cleaned up the computer's cache and `wails dev` worked normally.

**Comment by chenxiao1990** [comment]
我也有这个问题。

**Comment by sentangle** [comment]
I also have this problem!
how to solve this bug?

`PS F:\root-go\oclient> wails doctor
Wails CLI v2.0.0-beta.37


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.18.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.53
npm             N/A             Installed       6.14.14
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

PS F:\root-go\oclient> wails dev
Wails CLI v2.0.0-beta.37


Executing: go mod tidy -compat=1.17
Executing: C:\Users\Administrator\go\bin\wails.exe generate module
Converting type application.RespResult
- simple field RespResult.Status
- simple field RespResult.Message`

**Comment by stffabi** [comment]
@sentangle are you using an antivirus tool, which might block the file?

I think we could probably just change the deletion of that temp file to a best effort case. If it could be deleted, that's fine otherwise it will be left in there and overwritten during the next build.

**Comment by leaanthony** [comment]
Weird this seems to be happening only on Windows. I agree with just best effort delete. I'm not 100% sure it will be overwritten though if it's locked. Let's see 👍

**Comment by leaanthony** [comment]
@sentangle @chenxiao1990 @yangpeng1994 - Please try the linked PR and let us know if it fixes this. Thanks 👍

**Comment by leaanthony** [comment]
@sentangle @chenxiao1990 @yangpeng1994 - Any updates?

**Comment by chenxiao1990** [comment]
PS E:\chenxiao\wailsjianfei> wails doctor
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

system : win11

ERROR: remove C:\Users\zxj\AppData\Local\Temp\wailsbindings.exe: The process cannot access the file because it is being used by another process.


Update code to the linked PR, work well.
