### ISSUE TITLE
[v2] Add race detector to dev & build commands

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#1425]
### Is your feature request related to a problem? Please describe.

I'd like to run & build my program with go's race detector built in it, however currently its not possible to pass the -race flag to go's build command.

If its possible and I'm just blind, please correct me and close this!

### Describe the solution you'd like

Introduce a new flag `-race` to wails' dev & build commands that passes the `-race` flag to go build. I think its an important feature.

I'd be happy to make a PR for this.

### Additional context

I don't think this would cause any issues on any architecture or operating system.

**Comment by leaanthony** [comment]
Thanks @Lyimmi for requesting this. Feel free to raise a PR 👍
