### ISSUE TITLE
Wails build fails to work with arm64 rockcheap RK3399 boards

### ISSUE THREAD

**Issue by werber** [wailsapp/wails#143]
**Description**
If you run arm64 built binary on rk3399 board (ubuntu 18.04) then it fails on animations with this error: libEGL warning: DRI2: failed to open rockchip (search paths /usr/lib/aarch64-linux-gnu/d
ri:${ORIGIN}/dri:/usr/lib/dri)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '~/go/src/YOUR_PROJECT_NAME'
2. Run this command: `wails build`
3. Run built executable

**Expected behaviour**
Application should work smoothly

**System Details**
uname -a: 
```
Linux qbox 4.4.167 #5 SMP Wed Jun 12 11:21:31 EEST 2019 aarch64 aarch64 aarch64 GNU/Linux
```
go version: `go version go1.12.5 linux/arm64`
PATH: 
```
/home/qbox/.nvm/versions/node/v12.4.0/bin:/opt/gstreamer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/qbox/go/bin
```

**Additional context**
Running on RK3399, ARM64. ROCKCHIP.

App.vue content:
```
<template>
  <div id="app">
    <div class="lds-circle"><div></div></div>
  </div>
</template>

<script>

export default {
  name: "app",
  components: {
  }
};
</script>

<style>
  lds-circle {
    display: inline-block;
    transform: translateZ(1px);
  }
  .lds-circle > div {
    display: inline-block;
    width: 51px;
    height: 51px;
    margin: 6px;
    border-radius: 50%;
    background: #fff;
    animation: lds-circle 2.4s cubic-bezier(0, 0.2, 0.8, 1) infinite;
  }
  @keyframes lds-circle {
    0%, 100% {
      animation-timing-function: cubic-bezier(0.5, 0, 1, 0.5);
    }
    0% {
      transform: rotateY(0deg);
    }
    50% {
      transform: rotateY(1800deg);
      animation-timing-function: cubic-bezier(0, 0.5, 0.5, 1);
    }
    100% {
      transform: rotateY(3600deg);
    }
  }

</style>
```

**Comment by leaanthony** [comment]
Thanks for taking the time to open this issue! I guess officially we don't support ARM but would be nice to. Could you possibly submit another issue via `wails issue` as that will give is a bit more info on your platform?
Does a window appear? Does it crash?

**Comment by leaanthony** [comment]
Any updates? If not, I'll close the issue. Thanks.

**Comment by werber** [comment]
@leaanthony `wails issue` doesn't work on that platform because it cannot use chromium browser (which is installed). It tries to open that link which was prepared using xdg-open but that cannot find any utils. When I install that still doesn't use that one. But that's not a problem, I've identified that the problem is in GPU itself, incorrectly installed Mali drivers for that board. So issues is not with Wails itself. Yes, you can close this issue, thanks!

**Comment by leaanthony** [comment]
Thanks for the feedback and awesome news! Let us know how you get on!
