### ISSUE TITLE
[v2, Windows] default `appicon.png` is used to generate `windows/icon.ico` (after being replaced with different image)

### ISSUE THREAD

**Issue by omriharel** [wailsapp/wails#1431]
### Description

Hello,

I'm playing around with v2.0-beta37 on Windows, and I noticed that replacing `build/appicon.png` with my own image isn't fully propagated down the packaging chain. I used the wails CLI and haven't attempted any sort of manual packaging. Notably:

- My custom icon is correctly being displayed in the taskbar and for the app window itself
- However, the built executable's icon (e.g. in Windows Explorer) retains the default _"W"_ graphic (and `build/windows/icon.ico` seems to be generated from the original version of `appicon.png`).

I saw that in #1143 this was fixed specifically for MacOS - and I also noticed that in 9c5600d a change was made to the Windows-specific icon gen behavior, but I wasn't able to wrap my head around what's happening exactly. I'm guessing it ends up still taking the embedded default version of `appicon.png` that's built into the CLI.

Thanks for taking the time to look at this. Wails is a fantastic project!

### To Reproduce

1. Create a new Wails project using the v2 CLI on a Windows system
2. Replace default `build/appicon.png` with my own custom image (48x48 PNG file), attached
3. Delete `build/windows` completely to make sure icon generation is invoked
4. Run `wails build`
5. Locate resulting executable in `build/bin` - has default _"W"_ icon in Windows Explorer, but uses my custom icon in runtime (in both the taskbar and the window icon)

![appicon](https://user-images.githubusercontent.com/10298151/171067002-287b8662-0335-47ba-80ea-920997392079.png)

### Expected behaviour

Result executable should have the custom icon's appearance everywhere, including in Windows Explorer.

### Screenshots

Here's a screenshot of the app executable in Windows Explorer:
![image](https://user-images.githubusercontent.com/10298151/171067185-da2583ec-1d71-43d9-a9d9-84b929e700db.png)

And here it is running correctly with the custom icon:
![image](https://user-images.githubusercontent.com/10298151/171067217-1f80542e-07bd-4a2a-ac1d-d6cf943e22cb.png)

### System Details

```shell
Wails CLI v2.0.0-beta.37


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Education
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.17.10
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.53
npm             N/A             Installed       8.5.5
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
```


### Additional context

_No response_

**Comment by stffabi** [comment]
Thanks for opening this issue and using Wails.

Unfortunately I was unable to reproduce the issue, at least when cross compiling from MacOS to Windows. Just a couple of questions to hopefully narrow down the problem.
- If you replace `build/appicon.png` and removing `build/windows` does the created `build/windows/icon.ico` contain your new image?
- IIRC windows has some icon caching whicht might interfere.
  - What icon do you see if you right-click on the executable and select properties?
  - Does a reboot help, this should clear the cache?

**Comment by omriharel** [comment]
Hey there @stffabi, thank you so much for taking the time to look at this!

I feel foolish! It was the icon caching mechanism. I somehow never tried to open the generated `.ico` file, or to look at my executable's properties - both of them seemed unchanged in explorer, and I assumed at least the `.ico` display is exempt from this mechanism.

Please accept my apologies for the waste of time. Everything works correctly. Thanks again!

**Comment by stffabi** [comment]
No worries, glad that everything works now for you.
