### ISSUE TITLE
Types with maps of maps are not generated

### ISSUE THREAD

**Issue by kettek** [wailsapp/wails#1434]
### Description

With a type definition similar to the following:

```go
type MyType map[string]map[string]float64
```

The generated typescript mapping will generate an incomplete mapping similar to:

```
{[key: string]: }
```

### To Reproduce

Define any type that is a map of a map.

### Expected behaviour

A proper mapping to be generated, such as

```typescript
{[key: string]: {[key: string]: number}}
```

### Attempted Fixes

Simply splitting the type definition into separate types fixes it:

```go
type MyStruct map[string]MySubStruct

type MySubStruct map[string]float64
```

### System Details

```shell
NOTE: The system is the latest Windows 11, not Windows 10 Pro.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.18.2
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.53
npm             N/A             Installed       8.1.0
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment]
Thanks for opening this! Have you confirmed the data is being sent correctly from the backend to the frontend? I'm wondering if this is 2 bugs for the price of 1 😄

**Comment by leaanthony** [comment]
I've opened a PR that fixes this. If you can think of other more gnarly maps that might break TS generation, please feel free to add some more test cases. Will be more than happy to fix. Let me know how you get on.

**Comment by kettek** [comment]
In response to the first comment, the data was/is being sent correctly, as applying the explicit types without multiple maps in a single type declaration fixed it.

In my case, the key types were generally primitives (int, uint, uint8), with either strings or more complex structs as the end value. The PR looks like it would cover my uses. I'll give it a try with bleeding edge to confirm.

**Comment by kettek** [comment]
I'm not certain why, but by defining the type and including it in a type that I already am using in the frontend, it seems to not be fixed, even with the PR:

```go
type MyType map[string]map[string]int
// ...
type Editor struct {
  // ... other fields
  MyT MyType `json:"MyT"`
}
```

In the typescript model, it is truncated as per before: `MyT: {[key: string]: };`

---

wails doctor reports `ef4819269e0192753a9809d7d53880e1e5fefbf6`, which matches the PR. `go.mod` has `replace github.com/wailsapp/wails/v2 => C:\Users\kts\Devel\wails\v2` before EOF, which is correct.

When splitting it into two type definitions, it is failing to either generate a type definition for MyType2 or convert MyType2 into equivalent `{[key: string]: number}`.

```go
type MyType map[string]MyType2
type MyType2 map[string]float64
// ...
type Editor struct {
  // ... other fields
  MyT MyType `json:"MyT"`
}
```

```
	    MyT: {[key: string]: MyType2}; // MyType2 is never defined in the models file.
```

---

And, as a somewhat separate issue, type aliases have the same problem as the initial issue reported (e.g., `type MyType = map[string]MyType2`)

**Comment by leaanthony** [comment]
Thanks for testing. It looks like the library we use doesn't explicitly support maps like this, but there is a workaround: you can pass `ts_type` as a struct tag to explicitly set the type you want, EG: `ts_type:"{[key: string]: number}"` 

More details here: https://github.com/tkrajina/typescriptify-golang-structs

**Comment by leaanthony** [comment]
I'll be honest, neither did I 😂 I'll add some info in the bindings section of the docs

**Comment by leaanthony** [comment]
@kettek - this ok for you now?

**Comment by kettek** [comment]
I ran into issues with types not being generated if they were only defined as a value with `ts_types`. However, I think that would be a separate issue, and likely an issue tied to the typescriptify-golang-structs projects instead of wails.

I think as long as the documentation notes the `ts_types` field and how it can be used to define more complex types, this issue should be able to be closed.
