### ISSUE TITLE
Bind Struct for read as well

### ISSUE THREAD

**Issue by pierrejoye** [wailsapp/wails#1440]
### Is your feature request related to a problem? Please describe.

Say:

I have a config that contains data required by the Frontend, for example a key or an API URL. This is static and defined using config files in the go side (set via menu and dialogs).

I try to use a function and call it later but the promise nature of it makes it actually available too late. I could modify the FE code accordingly but that's a major change that won't work for other targets like web or PWA

### Describe the solution you'd like

Ability to bind a struct as readonly for example. A pure data structure on the FE side.

Alternatively the same as now, however with a getter as well (right now only a setter is generated).

### Describe alternatives you've considered

I have to do one build per API/Key pair, not scalable :)

I am pretty sure however it is possible already but I may have missed it completely :)

**Comment by leaanthony** [comment]
@pierrejoye could you please provide another example of what you want as it isn't clear to me. Thanks!

**Comment by aadog** [comment]
> 

example：
go:
```
type App struct{
    Data string
}
```
console.log(App.Data)
js:
```

```

**Comment by leaanthony** [comment]
How about a `map[string][string]` in Go that's always available at `window.CustomState` or something?

**Comment by leaanthony** [comment]
Closing due to lack of feedback.
