### ISSUE TITLE
Undocumented/Unobvious behaviour

### ISSUE THREAD

**Issue by NanoNik** [wailsapp/wails#1457]
### Description

Not really a bug, just unobvious behaviour.
When you run the application in development mode (wails dev), and your application requests a file that doesn't exist, the whole application will freeze for 5 seconds as it tries to read the same files 50 times.

https://github.com/wailsapp/wails/blob/1e54eb2eaf7ca20db41de6deb249d5cffa3cad5b/v2/internal/frontend/assetserver/assethandler.go#L114-L122

I'm not sure why this is necessary, but it should be mentioned in documentation or printed in logs.
Sometimes it is very distracting and annoying during development.

### To Reproduce

1. Create new wails app
2. Try to access any resource in your application that doesn't exist
3. See a freeze

### Expected behaviour

The application should not freeze, or at least this should be mentioned somewhere in documentation.

Another way is to print about it in console, something like: "retrying to load file N times because you are in development environment".

### Attempted Fixes

To bypass this behaviour, you can set AssetsHandler for your application:

```
type dummyHandler struct{}

func (d dummyHandler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	log.Printf("responding with 404 for %s", request.RequestURI)
	writer.WriteHeader(404)
}

wails.Run(&options.App{
    AssetsHandler: &dummyHandler{},
})

```

### System Details

```shell
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.18.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       102.0.1245.33
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by stffabi** [comment]
Thanks @NanoNik for bringing up this issue.

It was more of a workaround back in the days, when Wails didn't fully support external development servers like `vite`. See also https://github.com/wailsapp/wails/issues/1380#issuecomment-1118220299

I think that retry logic could now completely be removed, what do you think @leaanthony ?

**Comment by leaanthony** [comment]
💯 I actually thought we had already, maybe we discussed it and never did it. Happy to get rid of it. The only impact is those templates that don't use vite and have some bundling time but I'm ok with that as we have a denounce option

**Comment by stffabi** [comment]
Yeah, we discussed it in #1380, but in the end the PR just skipped it when AssetsHandler are active. Will bring up a PR in the next days to remove it.
