### ISSUE TITLE
Wails doctor failing without error description

### ISSUE THREAD

**Issue by DazedNConfused-** [wailsapp/wails#1458]
### Description

Wails doctor fails to run its diagnostics without any sort of message regarding _what_ caused it to fail:

![image](https://user-images.githubusercontent.com/6098622/174091721-755a1df6-b8c4-47f2-84bb-35e914556349.png)

### To Reproduce

1. Download latest beta build (`v2.0.0-beta.37` at the time of writing this) by means of `go install github.com/wailsapp/wails/v2/cmd/wails@latest`
2. Run `wails doctor`

### Expected behaviour

Expected to see a detailed list of the missing dependencies needed for Wails development.

### System Details

```shell
I cannot properly fill out this section because this is the very command that is failing.
```

### Additional context

I am running Linux Mint 19.3

Here is the output of `uname -vrm`

```text
5.4.0-117-generic #132~18.04.1-Ubuntu SMP Thu Jun 2 23:36:48 UTC 2022 x86_64
```

**Comment by abtin** [comment]
I noticed the same problem on Linux Mint (20.3), but I don't think it's related to Mint. It's just the `apt` command syntax. Basically deep in the code we are running `apt -qq list`  instead of `apt list -qq` and that produces apt usage help and error code 1. I'm going to submit a PR for the fix.

**Comment by leaanthony** [comment]
Thanks for tracking that down. Did that syntax change recently? It was developed on Ubuntu 20.10 and appeared to work at the time.

**Comment by leaanthony** [comment]
@DazedNConfused- please let us know if [master](https://wails.io/docs/guides/bleeding-edge) works for you now 🙏

**Comment by abtin** [comment]
> Thanks for tracking that down. Did that syntax change recently? It was developed on Ubuntu 20.10 and appeared to work at the time.

That was a great question. As per the man page, the command should precede the options but when I checked in ubuntu and debian it appeared they are more lax and accept the command in either ways. However, linux mint seems to be more strict.

**Comment by DazedNConfused-** [comment]
Thanks for the fix @abtin! Indeed, [master](https://wails.io/docs/guides/bleeding-edge/) works flawlessly now 🚀 

![image](https://user-images.githubusercontent.com/6098622/174707289-a92bb0cb-49ed-4cf9-a049-e881262dc2f7.png)

Once again, thank you all for the analysis and the expeditious patch. You may go ahead and close this issue.
