### ISSUE TITLE
vue-ts template project does not work in browser on linux

### ISSUE THREAD

**Issue by robinchm** [wailsapp/wails#1459]
### Description

When I launch the template project for vue-ts, the application works fine, but in browser the "Greet" button does not work.

In the console it says:
```
[Vue warn]: Unhandled error during execution of native event handler 
  at <HelloWorld> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369

Uncaught TypeError: Cannot read properties of undefined (reading 'main')
    at Greet (App.js:6:22)
    at greet (HelloWorld.vue:11:3)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:369:13)
Greet @ App.js:6
greet @ HelloWorld.vue:11
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
```

### To Reproduce

1. Init a vue-ts project: `wails init -n myproject -t vue-ts`
2. start dev mode: `wails dev`
3. open the page in browser (firefox or chrome, same behavior): `http://localhost:3000`
4. type something into the textbox then click "Greet" button

### Expected behaviour

The "Greet" button should work the same way in browser as in app.

### Screenshots

![image](https://user-images.githubusercontent.com/22679145/174279287-641197f3-1f5e-41a1-81c3-e2590b15a8d4.png)
![image](https://user-images.githubusercontent.com/22679145/174279481-9da0c557-a040-44aa-8a8f-e86367d9af46.png)

### Attempted Fixes

Found some old issues complaining about browser errors, but I think they've all been fixed. I am using the latest version.

### System Details

```shell
Wails CLI v2.0.0-beta.37


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Ubuntu
Version: 	20.10
ID:		ubuntu
Go Version:	go1.18.3
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.37
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.2
gcc		build-essential		Installed	12.8ubuntu3
libgtk-3	libgtk-3-dev		Installed	3.24.23-1ubuntu1
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.32.0-0ubuntu0.20.10.1
npm		npm			Installed	7.19.1
*nsis		nsis			Installed	v3.05-4
pkg-config	pkg-config		Installed	0.29.2-1ubuntu1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Did you try after a manual refresh of the browser? Trying to rule out a race condition.

**Comment by leaanthony** [comment]
Just tried and was unable to reproduce.

**Comment by robinchm** [comment]
> Did you try after a manual refresh of the browser? Trying to rule out a race condition.

Refreshing the browser does not work. Tried a different node version (v16.15.1) still the same behavior.

If you cannot reproduce it's ok since the app works without problem. Maybe we can just close this issue.

**Comment by a2htray** [comment]
This problem will be solved by adding `-browser` flag, as follows:
```bash
wails dev -browser
```
