### ISSUE TITLE
Can't show maximised application window on Windows OS

### ISSUE THREAD

**Issue by iceraintj** [wailsapp/wails#1462]
### Description

Can't show maximised application window on Windows OS.

### To Reproduce

1.use below code:

err := wails.Run(&options.App {
    Title:     "demo",
    Width:     800,
    Height:    600,
    MinWidth:  400,
    MinHeight: 300,
    **WindowStartState: options.Maximised,**
    DisableResize: false,
    Frameless: false,
    Fullscreen: false,
    AlwaysOnTop: false,

2.Run below command to build a excutable file:
_wails build -platform windows/amd64_

### Expected behaviour

should show a maximised main window, but the opened main window isn't maximised.

### System Details

```shell
Wails CLI v2.0.0-beta.37


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home China
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.2
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       102.0.1245.44
npm             N/A             Installed       8.11.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Installed       v3.03

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Thanks for reporting this. Can you please test master and let me know if this works now? Thanks!

**Comment by iceraintj** [comment]
”WindowStartState: options.Minimised and options.Maximised“ are OK now.
But "WindowStartState: options.Normal and options.Fullscreen" are not work.
By the way, I can get the latest code via GIT PULL command, but _**_go get -u github.com/wailsapp/wails/v2/cmd/wails@latest_**_ command can't get  the latest code.

**Comment by leaanthony** [comment]
Nice catch. I realised after that the `StartHidden` flag was also not being considered. I've pushed a fix and tested all combinations to master. Would appreciate your feedback 🙏

**Comment by iceraintj** [comment]
Good news for you. It's OK now. Great!
