### ISSUE TITLE
Proxy protocol relative URLs

### ISSUE THREAD

**Issue by badarsebard** [wailsapp/wails#1469]
### Is your feature request related to a problem? Please describe.

I am creating an email client and rendering HTML emails using an iframe. When the HTML content uses a protocol relative URL (e.g. `//fonts.googleapis.com`) the application attempts to use the `wails:` protocol and an error is returned.

### Describe the solution you'd like

Is there some way to proxy requests made to the application? So when the browser code makes the request to `wails://` the app will forward it on to `http://` and then return the correct response?

**Comment by badarsebard** [comment]
This looks like it will work, but when I test it I run into this error
```
2022-06-20 16:44:08.95853383 -0400 EDT assetserver.go:116 ProcessHTTPRequest(): ERROR | [AssetServer] Error processing request 'wails://fonts.googleapis.com/css?family=Google+Sans': Expected host '%!d(string=wails)' in request, but was 'fonts.googleapis.com' (HttpResponse=500)
```

**Comment by badarsebard** [comment]
So in the Windows case, the current behavior ends up being the desired `http://fonts.googleapis.com` (albeit as a consequence of being unable to register the `wails:` scheme). For linux/darwin, specifying a redirect of the protocol is exactly what is needed. I can understand that the intent of the AssetsHandler is to specifically handle the assets served by the wails application and not external ones. 

Given that Wails is designed to utilize web frameworks for its frontend I think it would be useful to have an option or mechanism to control or proxy all requests that come in over the `wails` scheme. Understandably this is a fairly edge case given that URLs that include the http/s scheme will function correctly, and it's only these protocol relative ones that cause a problem.

**Comment by badarsebard** [comment]
> Personally I would opt to internally return a 308-redirect for anything that comes in to `wails:` scheme that is not the `wails` host to `http://host`. We plan to add support for WebKitGTK >= 2.36 in the near future, so we would be able to do those redirects also on Linux. A question to be answered for 2.36 support is, if one should just bump the minimal dependency or pin the binary minimal dependency against the WebKitGTK version that was used to compile it.

Now the #2151 has been merged in the 308 redirect should be possible. This issue got marked stale due to age.

**Comment by stffabi** [comment]
Unfortunately WebKit2GTK 2.36+ still has no support for http redirects.

See also https://github.com/wailsapp/wails/issues/2109#issuecomment-1325740848

**Comment by leaanthony** [comment]
This can now be achieved using `asset server.NewProxyServer`:
```go
package main

import (
	"github.com/wailsapp/wails/v2"
	assetserver2 "github.com/wailsapp/wails/v2/pkg/assetserver"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
)

func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "externalserver",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Handler: assetserver2.NewProxyServer("http://127.0.0.1:54321"),
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}```

**Comment by leaanthony** [comment]
It would be good if this could be tested on a newer version of linux

**Comment by leaanthony** [comment]
Closing for now. Please feel free to reopen if you still want this looked at 👍
