### ISSUE TITLE
Can't make it work with SolidJS-Start as it doesn't produce `index.html`

### ISSUE THREAD

**Issue by nikivdev** [wailsapp/wails#1491]
### Description

Not sure if bug or a feature request. But I have a Wails repo setup here:

https://github.com/learn-anything/learn-anything/tree/main/app

My front end is built from https://github.com/solidjs/solid-start

I modified wails.json to run my `pnpm run ..` commands: https://github.com/learn-anything/learn-anything/blob/main/app/wails.json

I assume the issue is that with Wails-React setup, I need an `index.html` file like [in here](https://github.com/nikitavoloboev/test/blob/main/wails-react/frontend/index.html). That supposedly should call a [file similar to this but for SolidJS](https://github.com/nikitavoloboev/test/blob/main/wails-react/frontend/src/main.tsx). The thing is that Solid-Start uses Vite for bundling. And my output dir (called netlify) doesn't give me any .html files. 😿

<img width="190" alt="image" src="https://user-images.githubusercontent.com/6391776/175515250-59544a59-c3a9-4a68-98cc-863c10e70083.png">

Not sure how to go about solving this.

### To Reproduce

1. Clone https://github.com/learn-anything/learn-anything 
2. `cd app`
3. `wails dev`

See this:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/6391776/175514747-96a4d5b8-7d12-4005-b66e-ad2def2909d1.png">

### Expected behaviour

It works similar to other Svelte/React templates.

### System Details

```shell
wails doctor
Wails CLI v2.0.0-beta.37


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.19beta1
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.37

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.5.5
*upx 				N/A		Available	
*nsis 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment]
Thanks for opening this. All of the standard wails templates also use vite so I'd recommend as a first step to create the react or react-ts projects and look at how they interact with vite. I'm not familiar at all with solid so can't offer more than that right now but let us know how you get on and we will help in any way we can 🙏

**Comment by sidwebworks** [comment]
@nikitavoloboev Hey wassup, I saw your repo. I am not sure if doing SSR like that would make sense https://github.com/learn-anything/learn-anything/blob/main/app/frontend/src/entry-server.tsx

As It looks like solid server is made to run on Node JS. That being said, I will spend some time and create a solid js starter that might help with this.

**Comment by sidwebworks** [comment]
@nikitavoloboev Easy peasy got it working. I didn't go with Solid start instead just cloned their TS template directly 
from https://github.com/solidjs/templates

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58144379/175643391-3d9e6488-d0c7-4f02-b330-bbc7ae225935.png">

After I finished creating the Wails template, it all worked without any problems. One thing to note is I didn't use that solid starter is because all of them had some sort of server dependency like Node, Netlify, Deno etc and TBH didn't make sense to me to use Netlify for building a desktop native app?

Anyways If I am missing something feel free to ping me and I will try to help, for now will publish this template.

**Comment by nikitavoloboev** [comment]
This is super cool @sidwebworks 

My issue is a bit more complex though because I want to make my web app work for both situations, running in browser (SSR + SolidJS) and also running on desktop (no SSR). 

Your template only covers the second case.

**Comment by sidwebworks** [comment]
Ahh what you just mentioned made the most sense lol. 

Yeah I got what you mean, I am already in their discord, will check it out.

**Comment by wallenben** [comment]
Any luck on running SolidJS in-browser with wails? I'm also looking to solve that particular issue - wasn't sure if you guys tackled it already.
