### ISSUE TITLE
"wails" command not working

### ISSUE THREAD

**Issue by aiwaki** [wailsapp/wails#1500]
### Description

When I try to use the "wails" command in my terminal, the terminal displays the following:

"wails" is not internal or external
command, executable program, or batch file.

I have all the necessary things installed:
Go, NPM, WebView2

### To Reproduce

I installed Wails with the command:
"go install github.com/wailsapp/wails/v2/cmd/wails@latest"

### Expected behaviour

I suppose the "wails" command should work, but it doesn't work for me

I followed instructions:
https://wails.io/docs/gettingstarted/installation

### System Details

```shell
I am using Windows 11
```

**Comment by yzqdev** [comment]
1. check if `wails.exe` exists, input `go env GOPATH` in the command line, go into gopath folder(usually `%userprofile%/go), check if `wails.exe` is in the bin folder
2. check if wails.exe in your PATH variable; if not, add it

**Comment by leaanthony** [comment]
Go hasn't been installed correctly. Male sure you follow the Go installation instructions, paying attention to the PATH environment variable

**Comment by Aivaki** [comment]
Thanks. I've already tried everything you said and also reinstalled Go, but it didn't help me. I'll try again today

**Comment by Aivaki** [comment]
> 1. проверьте, `wails.exe`существует ли, `go env GOPATH`введите в командной строке, перейдите в папку gopath (обычно `%userprofile%/go), check if `wails.exe` находится в папке bin
> 2. проверьте, есть ли файл wails.exe в вашей переменной PATH; если нет то добавь

I reinstalled Go again, entered the command
"go install github.com/wailsapp/wails/v2/cmd/wails@latest" in terminal. And nothing.
GOPATH: C:\Users\makse\go

I don't have a "bin" folder and no "wails.exe". Where to get "wails.exe"?

**Comment by leaanthony** [comment]
You just need `C:\Users\makse\go\bin` in your path

**Comment by Aivaki** [comment]
> 

Accept my apologies. Found out that the environment variables were wrong and not only.  Managed to fix everything. Now everything works as it should. Thanks

I spent a lot of time on this. I wonder if others have had the same?  🤔
In any case, at first I thought that nothing should work

**Comment by leaanthony** [comment]
Although this is a local Go issue, I think we could add more troubleshooting in the docs 👍

**Comment by leaanthony** [comment]
Added more to the docs on this.

**Comment by oti-adjei** [comment]
Currently having this issue on my Mac . Installed go on my Mac and have been using it already. Just installed wails using the terminal but im getting the same error. I'm ion go version 1.19.
I'll check to see if there's an executable in my go folder

**Comment by oti-adjei** [comment]
> Currently having this issue on my Mac . Installed go on my Mac and have been using it already. Just installed wails using the terminal but im getting the same error. I'm ion go version 1.19.
> I'll check to see if there's an executable in my go folder

There is a Wails executable in my bin. I'll try a quick restart to see if it does the trick

**Comment by oti-adjei** [comment]
> > Currently having this issue on my Mac . Installed go on my Mac and have been using it already. Just installed wails using the terminal but im getting the same error. I'm ion go version 1.19.
> > I'll check to see if there's an executable in my go folder
> 
> There is a Wails executable in my bin. I'll try a quick restart to see if it does the trick

didn't work .
checked GO111MODULE and its on. Don't know what the issue is
