### ISSUE TITLE
wails.AppConfig.Title set to Chinese window title will appear garbled

### ISSUE THREAD

**Issue by sotoup** [wailsapp/wails#151]
os： windows 8 64bit
golang: 1.12.0
node: 10.9.0
npm: 6.2.0
wails: 0.17.0

### wails.AppConfig.Title set to Chinese will appear garbled

```go
  app := wails.CreateApp(&wails.AppConfig{
    Width:  1024,
    Height: 768,
    Title:  "测试工具",
    JS:     js,
    CSS:    css,
    Colour: "#131313",
  })
```

**Comment by leaanthony** [comment]
Tbhanks for opening this issue. This is likely to be an issue in WebView but will confirm.

**Comment by leaanthony** [comment]
I tried this today and it works as expected.
![image](https://user-images.githubusercontent.com/1943904/64072485-851d5000-ccd2-11e9-96ba-e773401d03c1.png)

**Comment by leaanthony** [comment]
Hey there @sotoup - I believe I closed this in error as a similar issue has come through (referenced above). My test was on Mac not Windows and that seems to be the common issue here.
Could you please test [this workaround](https://github.com/zserge/webview/issues/102) and if it works, I will add this to Wails so you don't need to. 👍

**Comment by leaanthony** [comment]
Hi. I've created a fix that I can't fully test locally. Could you please see if your original code works with this version please?
`wails update -pre` should update you to v0.18.6-pre with the fix 🤞

**Comment by leaanthony** [comment]
Please update to the latest pre-release and let me know if that now works for you:

`wails update -pre`

**Comment by leaanthony** [comment]
Closing until post V1
