### ISSUE TITLE
Preference persistence

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#1515]
### Is your feature request related to a problem? Please describe.

Webview always shows the first view When opening the app again.
If app saved some prefs like user token, current url, window position and size before quit and reload it when starting again.
User can continue the journey.

### Describe the solution you'd like

```
type Prefs struct {
  X, Y, Width, Height int
  MainViewURL string
}

func (b *App) beforeClose(ctx context.Context) (prevent bool) {
  x, y := runtime.WindowGetPosition()
  w, h := runtime.WindowGetSize()
  u := runtime.GetMainViewURL()
  prefs := Prefs{w, y, w, h, u}
  runtime.SavePrefs(prefs)
}

// Prefs data will save to 
// %USERPROFILE%\AppData\Local\%APP_NAME%\prefs.json  (windows)
// $HOME/Library/Preferences/$APP_ID.plist  (macos)
// encrypt whatever

func (b *App) onStartup(ctx context.Context) {
  prefs := runtime.LoadPrefs()
  // restore window position and size
  // restore url
}
```

**Comment by leaanthony** [comment]
Thanks for opening this. I believe you can do all this now in plain Go, so it's unlikely to be something we add to the runtime.
