### ISSUE TITLE
Open URL directly

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#1516]
### Is your feature request related to a problem? Please describe.

1. Open the App
2. Enjoy pronhub

Faster then

1. Start Chrome
2. Open a new Tab
4. Click the location bar
5. Select pronhub.com in the recently history
6. Do lovely things

### Describe the solution you'd like

```
func main() {
    err := wails.Run(&options.App{
        //
        URL: "https://pronhub.com",
        //
    })
    if err != nil {
        log.Fatal(err)
    }
}
```

**Comment by leaanthony** [comment]
Webview is a better project for this use case https://github.com/WebView/webview

**Comment by overrnet** [comment]
I've actually wanted this feature for a while, but for legitimate use cases. Just because wails offers far easier window customisations, so after seeing your feature request and some trail and error I had it working with an external URL I used a custom asset handler, it's not the prettiest solution, but it works for everything I needed it to. Not posting code because I don't know how leaanthony would feel about it, just letting you know it's possible.

**Comment by leaanthony** [comment]
Honestly, if you want to wrap external websites there are more appropriate projects. Wails is for desktop apps, not for light wrappers around websites.

**Comment by overrnet** [comment]
I wouldn't be using it for external sites, I would use it for locally hosted web apps that would benefit from having an easy-to-launch wrapper. Sure there are more practical solutions but none of them offer the extensive window options that I love so much. I can see that this isn't what you want for the project but there are legitimate use cases, Electron even allows opening a URL in the window, I know it wouldn't be that hard to implement a new struct field so you could use a custom "startURL" with no asset handlers or script injections, maybe just think about it?

**Comment by wantg** [comment]
> I wouldn't be using it for external sites, I would use it for locally hosted web apps that would benefit from having an easy-to-launch wrapper. Sure there are more practical solutions but none of them offer the extensive wails window options that I love so much. I can see that this isn't what you want for the project but there are legitimate use cases, Electron even allows opening a URL in the window, I know it wouldn't be that hard to implement a new struct field so you could use a custom "startURL" with no asset handlers or script injections, maybe just think about it?

forget that frontend just put <meta http-equiv="refresh" content="0;url=https://example.com" /> or  <script>window.location='https://example.com'</script> in index.html

**Comment by overrnet** [comment]
> forget that frontend just put `<meta http-equiv="refresh" content="0;url=https://example.com" />` or `<script>window.location='https://example.com'</script>` in index.html

wow, don't I feel stupid

**Comment by wantg** [comment]
> > forget that frontend just put
> > `<meta http-equiv="refresh" content="0;url=https://example.com" />`
> > or
> > `<script>window.location='https://example.com'</script>`
> > in index.html
> 
> wow, don't I feel stupid still, what you originally proposed would be a very nice to have

I know they wouldn't do it, or I would have made a suggestion last year.

**Comment by csterritt** [comment]
I have a desktop app which, in effect, searches a database of links and presents them. I'd like to be able to click a link and have it open in a system browser... is this case possible, and if so how?

For various reasons, Webview is not appropriate for this project.

Thanks!

**Comment by overrnet** [comment]
> I'd like to be able to click a link and have it open in a system browser... is this case possible, and if so how?

Your question should have been in a new discussion but none-the-less, there is an API for this [`BrowserOpenURL`](https://wails.io/docs/reference/runtime/browser/#browseropenurl=)

**Comment by csterritt** [comment]
@overrnet Thanks! That works perfectly, much appreciated.

**Comment by codepiano** [comment]
I want this feature too, but not only open directly. I want to open an url, and inject a javascript file, send data to golang functions to save web contents which load dynamic.

I used electron to implement this feature, inject a js into a webview, and watch DOM events, but this approach does not work in wails.

**Comment by csterritt** [comment]
@codepiano Not sure I understand -- is this a URL on the web? So you might want to open https://www.yahoo.com and inject JS into that HTML? Or is the HTML you want to modify producing with your go code?

And do you want to display this HTML in the Wails app's window, or in the system browser (e.g., Safari or Edge)?

**Comment by wantg** [comment]
@codepiano Leads the user to open a Wails App that contains a modified financial website. that's a good idea.

**Comment by codepiano** [comment]
> @codepiano Not sure I understand -- is this a URL on the web? So you might want to open https://www.yahoo.com and inject JS into that HTML? Or is the HTML you want to modify producing with your go code?
> 
> And do you want to display this HTML in the Wails app's window, or in the system browser (e.g., Safari or Edge)?

actually I want to open an web url like tiktok in wails, then inject a js into it. After use login, the js will fetch information like your favorite videos id... etc, and then send these ids to wails golang backend, download these viedoes and save them to disk.

**Comment by codepiano** [comment]
> 

just want to download some viedoes, 😃

**Comment by codepiano** [comment]
> @codepiano Leads the user to open a Wails App that contains a modified financial website. that's a good idea.

just want to download some viedoes, 😃

**Comment by overrnet** [comment]
@codepiano its not a good idea

**Comment by mediawall** [comment]
I have a case to open another page. Users need token to access web site api and the site requires users to login and set token in cookie or storage. If user open app without token, the app will navigate to the website to login and fetch token. then go back to app.

**Comment by overrnet** [comment]
@mediawall so what is your question? Sounds like you need to implement some sort of OAuth??

**Comment by ZeronoFreya** [comment]
This is a very practical function. For example, when doing an unofficial program on a certain website, the verification code problem is unavoidable. We need to be able to display the verification page. For your own website, it is also good to display an extra page, which can be updated on the server without requiring the user to update the program. Jumping is a solution, but it is not easy to use. For example, my program is a local application, but it needs some Participation in web pages... If this is not a technical issue, I hope to listen to the needs of users and not be limited to local.

**Comment by leaanthony** [comment]
This will be available in v3 👍

**Comment by wantg** [comment]
Make Wails great again

**Comment by Zorgatone** [comment]
I also would like to open external URLs.
My use case would be to keep multiple websites (external URLS) opened in a split-view window (multiple webview in one window), see also #1997 2410

**Comment by c1ngular** [comment]
Any updates on this ?

**Comment by adlion** [comment]
+1

**Comment by DeanPiers** [comment]
+1

**Comment by leaanthony** [comment]
Is fulfilled in v3.

**Comment by vaaski** [comment]
I don't really understand how I can execute JavaScript in the context of a remotely loaded URL.

Here is what I've tried:
- use the https://github.com/wailsapp/wails/tree/v3-alpha/v3/examples/systray example as a baseline
- add `URL: "https://wails.io"` to `app.NewWebviewWindowWithOptions`
- try putting various things into `window.ExecJS`, like `console.log`s or `window.test = 'abc'`
	- here's where I ran into the first weird thing, `window.ExecJS` seems to expect two variables; `(_callID string, js string)` and I have no idea what goes into _callID. I've put random strings, empty strings and the exact same string as for `js`. Nothing worked.
- Then I thought that maybe the window isn't ready or loaded yet. So I've tried this:

	```go
  window.On(events.Common.WindowFocus, func(event *application.WindowEvent) {
    fmt.Println("WindowFocus")
    window.ExecJS("console.log('Hello from Go!')", "console.log('Hello from Go!')")
  })
	```
  ... which also didn't work.

- I also tried putting something into the `JS` property next to `URL`

  ```go
  JS: "window.test = 'Hello from Go!'",
  ```
  but `window.test` was still undefined.

My end goal is to have a small system tray application that loads my homebridge UI which will be modified to be more compact and support automatic login. I don't think an `<iframe>` would work in this context as I want to modify the homebridge UI.

<details>
<summary>Side note</summary>


Thank you for developing Wails! I've been eagerly waiting for a lighter alternative to Electron. When Tauri emerged, it seemed promising, but diving into Rust without any prior experience was daunting.

Recently, I've started dabbling in Go, and I'm loving it. This got me thinking, "Is there a Go equivalent to Tauri?" Enter Wails, which appears to be the perfect blend of lightweight app development and user-friendliness.

Excited to see what v3 has in store and looking forward to building more with Wails!

</details>

**Comment by stffabi** [comment]
> here's where I ran into the first weird thing, window.ExecJS seems to expect two variables; (_callID string, js string) and I have no idea what goes into _callID. I've put random strings, empty strings and the exact same string as for js.

We are aware of this and that interface will hopefully change soon and `callID` will be removed. That argument is currently completely ignored and you can put in whatever you want :)

We are also aware that `window.ExecJS` currently does not work if not at least parts of the Wails runtime are being loaded, which obviously is not possible when opening an external URL.

https://github.com/wailsapp/wails/blob/1ec3b4ecabf6dbd56f0d38b2e568d7a32f2d1b0e/v3/pkg/application/webview_window.go#L505-L509

There are actively discussing about how to solve both of those issues internally by the Core-Team. So please stay tuned :)
