### ISSUE TITLE
Expose screen dimensions

### ISSUE THREAD

**Issue by skamensky** [wailsapp/wails#1518]
### Is your feature request related to a problem? Please describe.

Yes, I would like to position the window relative to the upper right corner. In order to do that, I need the screen size. Maybe I've misunderstood how to do this, but given the current API's I couldn't figure it out.

### Describe the solution you'd like

The ability to access the screen size e.g.
Somethine like

`runtime.WindowGetCurrentMonitorDimensions`

### Describe alternatives you've considered

As of now, I can flash a full screen, get the window dimensions and then reposition as needed. But this is hacky and produces a bad UX.

**Comment by leaanthony** [comment]
Thanks for opening this. A valid request. I'll add it to the Roadmap. Are you willing to try adding this as I think most of the calls should be available to you in the codebase?

**Comment by skamensky** [comment]
Yeah, I'll give it a shot. May take me some time to get to it.

**Comment by leaanthony** [comment]
We certainly have that call on windows to calculate dimensions for the maximise call. That'd be a good place to start.

**Comment by skamensky** [comment]
@leaanthony 

Somehow I managed to work on this today :shrug: 

Her'es the PR so far. https://github.com/wailsapp/wails/pull/1519

It's not complete but I wanted some feedback before I continue.

**Comment by leaanthony** [comment]
Thanks for the amazing work and considered questions. I'll review today and get back to you 🙏

**Comment by leaanthony** [comment]
https://github.com/wailsapp/wails/pull/1519

**Comment by leaanthony** [comment]
Completed by #1519
