### ISSUE TITLE
Support open devtools on app had been builded

### ISSUE THREAD

**Issue by askie** [wailsapp/wails#1523]
### Is your feature request related to a problem? Please describe.

when app have been builded , open the app,sometimes need to open devtools to debug error.

### Describe the solution you'd like

need a method to open devtools

**Comment by leaanthony** [comment]
Compile with `wails build -debug` 👍

**Comment by askie** [comment]
this working, thx

**Comment by garfieldbanks** [comment]
I'm using this on Windows and it when I add -debug it allows me to open devtools but it also opens a command window. Is there an option to disable the command window and only allow opening devtools?

**Comment by leaanthony** [comment]
No I don't think so

**Comment by JSchmidt63** [comment]
Great command! :-)
Is it possible in a production build to toggle: show the devttools debug or no show devtools debug by a command line arguments?

**Comment by davidnewhall** [comment]
> Is there an option to disable the command window and only allow opening devtools?

I need this too. :( The console window is useless and in the way, but the inspector is crucial for troubleshooting in new apps.

**Comment by leaanthony** [comment]
`wails build -debug` will allow you to right click and open the dev tools for a production build.

**Comment by davidnewhall** [comment]
I understand, but it also opens a console window. I want the inspector to be accessible by default, but I do not want a console window.

**Comment by mmghv** [comment]
Same here, It would be useful to enable the devtools without the console window, it's not acceptable to publish the application with the console window.

it would be nice to have a separate `-devtools` flag.

**Comment by leaanthony** [comment]
Do you know if that's even possible?

**Comment by davidnewhall** [comment]
It should be possible. I don't think the console window and blocking context menus are directly related. Are they? 

I'm familiar with the Windows console window. Newer versions of Windows use a "Terminal" window, and it has new problems with Go apps. The age old `-H=windowsgui` ld flag still seems to be the number one way to prevent a GUI app from having a console (or Terminal) window.

Conversely, I have no idea how you're turning off right click on the Windows. I use javascript if I need that feature.
```
  /* Prevent right-click when dev mode is disabled. */
  let allow_console_window = false;
  function blockRightClick(e) { if (!allow_console_window) e.preventDefault() }
  document.removeEventListener("contextmenu", blockRightClick)
  document.addEventListener("contextmenu", blockRightClick)
```

**Comment by mmghv** [comment]
I'm working on a PR right now, you'll be able to do `wails build -devtools`, tested on windows and is working perfectly.

**Comment by mmghv** [comment]
PR: https://github.com/wailsapp/wails/pull/2725, tests needed on `Linux` and `macOS`.
