### ISSUE TITLE
Make content of App.d.ts and App.js sorted in alphabetical order

### ISSUE THREAD

**Issue by kybin** [wailsapp/wails#1531]
### Is your feature request related to a problem? Please describe.

Currently, content of App.d.ts and App.js randomly organized on every build.

Which creates additional git diff results, make me harder to read it.

### Describe the solution you'd like

Make content of App.d.ts and App.js sorted in alphabetical order, per discussion on #1524 .

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by kybin** [comment]
It works well. Thanks!
