### ISSUE TITLE
Support update the front-end data in real time when the variables in Golang change?

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1536]
### Is your feature request related to a problem? Please describe.

Is it possible for the front-end to bind the data in Golang and update the front-end data in real time when the variables in Golang change?

### Describe the solution you'd like

update the front-end data in real time when the variables in Golang change

**Comment by leaanthony** [comment]
Do you have any thoughts on what that would look like?

**Comment by cxt90730** [comment]
Currently, Golang can use 'EventsOn/EventsEmit' to transmit messages to the frontend, and frontend use 'SetInterval' to flush data. But I wanted the frontend to listen directly the variables changes on the Go side instead of events, so that the frontend could update the bound data at any time. I just don't know if it's necessary haha, because I want to use Golang to upload files in my project, and then show the progress in the frontend...

**Comment by leaanthony** [comment]
Events is the best way to do this right now. You can't observe a Go variable natively. Perhaps we will look at how to do this at a later date.

**Comment by cxt90730** [comment]
ok, thx~
