### ISSUE TITLE
Can I load index.html from external disk when I use release mode 

### ISSUE THREAD

**Issue by jiangzhiyu1016** [wailsapp/wails#1537]
### Is your feature request related to a problem? Please describe.

Can I load index.html from external disk when I use release mode 

Now ,Index.html is packaged into a binary file

When the application starts, it will attempt to load index.html from my assets and the frontend will essentially work as a browser from that point on

I'm trying to wrap DLLS for other languages to call, and in fact, it's working pretty well, except that WHENEVER I update index.html, I have to package the binaries 

If I could call index.html from outside, I could just replace the HTML and debug it instantly on other computers without having to configure any environment 

Is there a relevant interface that can implement my idea

### Describe the solution you'd like

I'm trying to wrap DLLS for other languages to call, and in fact, it's working pretty well, except that WHENEVER I update index.html, I have to package the binaries 

If I could call index.html from outside, I could just replace the HTML and debug it instantly on other computers without having to configure any environment 

Is there a relevant interface that can implement my idea

### Describe alternatives you've considered

It might be possible to add a mode to get the HTML from the peer directory if the binary does not exist in index.html

**Comment by leaanthony** [comment]
We don't currently support this. How would you configure this feature?

**Comment by jiangzhiyu1016** [comment]
Only need to load index.html from the local directory, not the Embed resource

**Comment by stffabi** [comment]
@jiangzhiyu1016 What about using a custom 'fs.FS' implementation and pass it as 'options.Assets'? You could wrap the 'embed.FS' and add special handling only for your index.html.
Or if you want to always use a local folder you could use 'os.Dirfs'. With dirfs you must propably make sure to not allow reading outside of the provided folder.

**Comment by jiangzhiyu1016** [comment]
Yes, it is feasible, can you decide which file in wails source code to change

**Comment by jiangzhiyu1016** [comment]
![image](https://user-images.githubusercontent.com/56686900/178111086-13e13fd4-1e73-4e30-8c61-7bd331f7400a.png)
Looks like it's here. I'm not sure

**Comment by stffabi** [comment]
You don't need to change anything in the source code of Wails.
Wails already supports using generic 'fs.FS' implementations as assets https://github.com/wailsapp/wails/blob/7a634649977241d00abc7e4b7fc4779a6a465923/v2/pkg/options/options.go#L47 .

You just need to pass your implementation of the interface in the options when running the app with wails.Run.

**Comment by leaanthony** [comment]
This feels like a documentation issue. I'll see what I can do today 👍

**Comment by jiangzhiyu1016** [comment]
Thanks to all of you, I finally made it, and here I am writing down the specific solution, if it can help others, that would be great 

1.  I use the manual build packaging (details: https://wails.io/docs/guides/manual-builds)
2.In the main.go file, I define the relative directory H5 as the resource directory
`//go:embed h5`
`var assets embed.FS`
3. I then executed the command in the code directory:
`go build  -buildmode=c-shared -o exportgo.dll  -tags  dev   -ldflags "-w -s -H windowsgui"`
4.And then You get a dynamic library that can be called by other languages, and if you write the interface to interact, you just change index.html, and you can easily compile nice ones for other languages

For dev build,  I had success,For production build,I haven't yet,  though it's not clear what the impact will be. I can't wait to try writing nice interfaces in other languages

**Comment by jiangzhiyu1016** [comment]
Thanks to all of you, I finally made it, and here I am writing down the specific solution, if it can help others, that would be great 

1.  I use the manual build packaging (details: https://wails.io/docs/guides/manual-builds)
2.In the main.go file, I define the relative directory H5 as the resource directory
`//go:embed h5`
`var assets embed.FS`
3. I then executed the command in the code directory:
`go build  -buildmode=c-shared -o exportgo.dll  -tags  dev   -ldflags "-w -s -H windowsgui"`
4.And then You get a dynamic library that can be called by other languages, and if you write the interface to interact, you just change index.html, and you can easily compile nice ones for other languages

For dev build,  I had success,For production build,I haven't yet,  though it's not clear what the impact will be. I can't wait to try writing nice interfaces in other languages

**Comment by leaanthony** [comment]
Now that I fully understand what you are doing, this is actually quite amazing! Well done 👏 Are the other programs GUI programs or cli programs? I'm interested in how this might work with the main loop.

**Comment by jiangzhiyu1016** [comment]
GUI programs,
Golang's UI runs in the main thread, which is blocked, so I can create a new thread and process my run logic in the thread before I create wails 
1.I pass a static method pointer to Golang and save the pointer so that when Golang receives a message from H5, the static method to which the pointer points will also receive it
2.In Golang, I save context. context and export the method
in app.go
`func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
	ctx_A = ctx
}`
in main.go
`//export EventsON_jiangzhiyu
func EventsON_aaa(arg1 int) int {
	runtime.EventsEmit(ctx_A , "H5_aaa", "hello,world")
	return dizhi
}`

**Comment by jiangzhiyu1016** [comment]
this should look something like this

in main.go
//export EventsON_aaafunc EventsON_aaa(arg1 int) int { runtime.EventsEmit(ctx_A , "H5_aaa", "hello,world") return dizhi }

**Comment by leaanthony** [comment]
@jiangzhiyu1016 - let us know if there's anything else that needs doing on this and reopen if needed 👍
