### ISSUE TITLE
Transparent window updates at mouse hertz when dragging over other windows (1000Hz == window lag)

### ISSUE THREAD

**Issue by aiwaki** [wailsapp/wails#1542]
### Description

I faced such problem. I need a transparent application, but many people have their mouse refresh rate set to 500-1000Hz

Results of my research:

1000Hz
https://user-images.githubusercontent.com/58384167/178101346-5c0ec821-a37f-4635-8e95-e5cdfd0badc4.mp4

500Hz
https://user-images.githubusercontent.com/58384167/178101417-bd327475-2cfe-448b-83b2-574d232d11d8.mp4

125Hz
https://user-images.githubusercontent.com/58384167/178101508-d51ab0fe-e737-4da1-a234-9949b8474ffa.mp4

My screen is 144Hz, but it doesn't matter

### To Reproduce

Windows: &windows.Options
WebviewIsTransparent: true
WindowIsTranslucent: true

### Expected behaviour

Correct movement and display of the window without bugs

### Attempted Fixes

I tried to fix it in different ways, but in any case, with WebviewIsTransparent and WindowIsTranslucent enabled, the behavior is the same

### System Details

```shell
System
------
OS:             Windows 10 Pro (maybe it's a bug because I have Windows 11)
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.18.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.38

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.49
npm             N/A             Installed       6.14.15
*upx            N/A             Available
*nsis           N/A             Available
```

### Additional context

This problem is not only mine. I sent the app to my friend, and he got the same problem

**Comment by leaanthony** [comment]
It's not clear to me here what the bug is. Flashing? Or is that a video artefact?

**Comment by Aivaki** [comment]
> It's not clear to me here what the bug is. Flashing? Or is that a video artefact? Worth noting there's already a ticket open for transparency. If it's just that you need then lets close this as a duplicate.

As far as I understand, the window conflicts with application shadows and some of their controls

I don't even know how to explain it, but I tried to show it on video. When dragging a transparent window on top of another, it starts to lag strangely, as if its FPS drops below nowhere

**Comment by leaanthony** [comment]
Thanks for the insight. It may well be the fact that this translucent effect is a bit of a hack as win10 doesn't really support it. The next version of win11 does and we already support it, though it needs documenting

**Comment by Aivaki** [comment]
> Thanks for the insight. It may well be the fact that this translucent effect is a bit of a hack as win10 doesn't really support it. The next version of win11 does and we already support it, though it needs documenting

It is noteworthy that the window slows down even without using transparency. It's enough for WebviewIsTransparent and WindowIsTranslucent to be "true"

It is also noteworthy that the lags in the video are almost invisible
So I tried to record it on my phone but it's still hard to see:
(sorry for bad quality)
https://user-images.githubusercontent.com/58384167/178111397-3e6a1ba7-cc67-4673-9fbb-703997f570ed.MP4

**Comment by overrnet** [comment]
I can confirm this isn't a wails specific problem, I have a transparent app built with a different technology and it still does the same thing.

**Comment by leaanthony** [comment]
I suspected as much. Let's close this.

**Comment by Aivaki** [comment]
> I can confirm this isn't a wails specific problem, I have a transparent app built with a different technology and it still does the same thing.

Yes, but it would still be cool to fix it ¯\_(ツ)_/¯

**Comment by Aivaki** [comment]
> Log a ticket with Microsoft I guess 😬

Ok, i'll do it
