### ISSUE TITLE
[V2][Mac] App will not responding when using MessageDialog in `onBeforeClose`

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1552]
### Description

App will not responding when using MessageDialog on `onBeforeClose`

### To Reproduce

when I click `Yes`,  App will not responding 
my code:
```
func (a *App) BeforeClose(ctx context.Context) bool {
	dialog, err := runtime.MessageDialog(ctx, runtime.MessageDialogOptions{
		Type:          runtime.QuestionDialog,
		Title:         "Quit?",
		Message:       "Are you sure you want to quit?",
		Buttons:       []string{"No", "Yes"},
		DefaultButton: "Yes",
	})
	if err != nil {
		return false
	}
	return dialog != "Yes"
}
```

### Expected behaviour

App can close.

### System Details

```shell
when I click `Yes`, console will print:


DEB | [DevWebServer] Starting shutdown
ERR | http: Server closed
DEB | [DevWebServer] Shutdown completed
```
```


### Additional context

_No response_

**Comment by leaanthony** [comment]
Thanks for raising this! I managed to reproduce. Please try the linked PR and let us know how you get on 👍

**Comment by Lyimmi** [comment]
I stumbled into this on linux as well, should I check it out?

**Comment by cxt90730** [comment]
@leaanthony How can I build wails binary...?  I personally think that `Makefile` is necessary

**Comment by leaanthony** [comment]
https://wails.io/docs/guides/bleeding-edge

**Comment by Lyimmi** [comment]
The fix @leaanthony made in PR #1558 fixes the issue on Linux as well, I mean if I copy the changes to the linux file.

**Comment by leaanthony** [comment]
@Lyimmi added the code for linux. Let me know how it goes!

**Comment by Lyimmi** [comment]
@leaanthony it Works nicely!

**Comment by cxt90730** [comment]
hold on... Unfortunately, it still not work... I've install new wails binary.

![image](https://user-images.githubusercontent.com/11382804/179137243-4984aa4c-9c76-4eef-a445-732733cfcfd0.png)

**Comment by leaanthony** [comment]
It's working here. Did you update your project to use `replace`?

**Comment by cxt90730** [comment]
@leaanthony sorry, I forget replace in go.mod. It works, thank you very much. I suggest update wails version as soon as possible :)
