### ISSUE TITLE
[v2] windows about logger

### ISSUE THREAD

**Issue by ChenArno** [wailsapp/wails#1553]
### Is your feature request related to a problem? Please describe.

my question :
When I finished building and opened it in production mode, I found that I could not generate info.log, but the dev environment was fine 

### Describe the solution you'd like

```go
	app := NewApp()
	myLog := logger.NewFileLogger(fmt.Sprintf("logs/wails.log"))
	// Create application with options
	err := wails.Run(&options.App{
		Title:            "ww",
		Width:            800,
		Height:           600,
		Assets:           assets,
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		Logger:           myLog,
		Bind: []interface{}{
			app,
		},
	})
```

**Comment by leaanthony** [comment]
Hi 👋 The log level is set to `ERROR` for production builds. I've added a new option: `LogLevelProduction` where you can configure this. That should fix your issue. This is the PR: #1555. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge)👍

**Comment by ChenArno** [comment]
```
2022/07/13 15:19:21 app.go:115: dev
2022/07/13 15:19:38 app.go:180: 句柄：1964342894416
2022/07/13 15:19:38 app.go:188: CloseDevice：1

```
like this

```go
	multiWriter := io.MultiWriter(os.Stdout, f)
	log.SetOutput(multiWriter)
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)
```

**Comment by leaanthony** [comment]
The logger is an interface. You are free to implement what you proposed in your own logger. We won't be updating the default logger with this.

**Comment by ChenArno** [comment]
ok，thanks
