### ISSUE TITLE
PLEASE READ: Platform Survey

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#156]
Wails is growing quickly and to ensure everyone gets the best experience, we need to ensure we focus our time and efforts on the most beneficial work. This issue is therefore a survey to try and determine how many users we have per platform. This survey will run until weekend, so please take the time to vote! Thank you!

I primarily use:

- 👍MacOS
- 🚀 Linux
- 😄 Windows

**Comment by MostHated** [comment]
:rocket:

**Comment by devsquared** [comment]
👍 at home and 😄 at work

**Comment by apelican** [comment]
I am considering Wails to replace an Adobe AIR application we develop on 👍, and needs to run on customers computers (👍& 😄)

**Comment by leaanthony** [comment]
@apelican Awesome! Let me know how we can help you achieve this! More runtime functionality probably :-)

**Comment by sotoup** [comment]
:+1:  :smile:

**Comment by eaglebush** [comment]
😀

**Comment by jadczakd** [comment]
Considering it for a project that would be on multiple linux machines, so voting both 👍 and 🚀 
Thanks for creating it in the first place, I am having a blast here!

**Comment by pedzed** [comment]
To clarify: this is from a developers perspective. For end users, Wails programs work on all three major platforms (Linux, Windows and macOS).

_Correct me if I am wrong._

**Comment by fishfishfish2104** [comment]
:rocket:

**Comment by conanchen** [comment]
i am using win7 😄 and 👍MacOS

**Comment by leaanthony** [comment]
Thanks all for participating on this!
