### ISSUE TITLE
[v2] MouseEvent.button returns 1 on back button press

### ISSUE THREAD

**Issue by kybin** [wailsapp/wails#1560]
### Description

`window.onclick` fired with unwanted `MouseEvent.button` value on a mouse click.

These are the values I got.

Left: 0
Middle: 1
Right: doesn't fire the event. shows context menu
Back: 1

I need 3 for Back button.

### To Reproduce

1. On anywhere in the app.
2. Back mouse button click.
3. Got 1 from MouseEvent.button.

### Expected behaviour

Get 3 for Back button.

### System Details

```shell
System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18.1
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.38
Revision:	7a634649977241d00abc7e4b7fc4779a6a465923
Modified:	false

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available	
*nsis 				N/A		Available	

* - Optional Dependency
```

**Comment by leaanthony** [comment]
@kybin - any updates?

**Comment by kybin** [comment]
Sorry I was away from my computer a while.

Unfortunately it (onmousedown) gives the same results for me.
