### ISSUE TITLE
v2 wails dev not work

### ISSUE THREAD

**Issue by 93Alliance** [wailsapp/wails#1561]
### Description

It can't work when i used angular template.
The `wails dev` command will be blocking. But `wails build` command can work.
It will continue when press Ctrl + C , but the wails will auto quit.

```
wails init -n projektname -t https://github.com/TAINCER/wails-angular-template
```

### To Reproduce

```
wails init -n projektname -t https://github.com/TAINCER/wails-angular-template
wails dev
```

### Expected behaviour

NA

### Screenshots

![image](https://user-images.githubusercontent.com/33192459/178911150-e7b1de1c-ae89-4a14-b51c-1eee087ad560.png)

![image](https://user-images.githubusercontent.com/33192459/178911434-08635c56-7518-4f84-9d99-2d50f157c723.png)
![image](https://user-images.githubusercontent.com/33192459/178911461-f0a24efd-eb2f-4fbf-8ed2-96efe512c825.png)
![image](https://user-images.githubusercontent.com/33192459/178911480-352e72a1-f31d-4197-9183-70ff67bf7223.png)

### System Details

```shell
Linux mint 19
Wails CLI v2.0.0-beta.38
Template Angular 12
npm 14
```

**Comment by leaanthony** [comment]
Please report this to the template repository. Thanks.
