### ISSUE TITLE
Nothing shown at all on Linux in latest 2.0 beta

### ISSUE THREAD

**Issue by 1player** [wailsapp/wails#1563]
### Description

Installed Wails from scratch on Arch Linux/GNOME Wayland. Created a vanilla project, built it, no window shows up, though I can see that the application is running in the taskbar. But no output whatsoever.

### To Reproduce

1. `go install github.com/wailsapp/wails/v2/cmd/wails@latest`
2. Install `webkit2gtk` dependency
3. `wails init -n testwails -t vanilla`
4. `wails build`
5. `./build/bin/testwails`

### Expected behaviour

Some kind of window to be shown.

### System Details

```shell
Wails CLI v2.0.0-beta.38


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.18.3
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.38
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Available       1:20.10.17-1
gcc             gcc             Installed       12.1.0-2
libgtk-3        gtk3            Installed       1:3.24.34-1
libwebkit       webkit2gtk      Installed       2.36.4-2
npm             npm             Installed       8.13.2-1
pkg-config      pkgconf         Installed       1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - docker: sudo pacman -S docker
```

### Additional context

Output from the application:

```
Gtk-Message: 10:53:45.585: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:53:45.586: Failed to load module "canberra-gtk-module"
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Gtk-Message: 10:53:45.630: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:53:45.630: Failed to load module "canberra-gtk-module"
^C
Ctrl+C detected. Shutting down...

(testwails:563208): Gtk-CRITICAL **: 10:53:54.342: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by leaanthony** [comment]
Hi there 👋 What's with the "canberra-gtk-module" errors? We have plenty of people use Wails on Linux so it's likely some local environment issue. Are you able to fix the above issue and see how that affects things? Thanks 👍

**Comment by leaanthony** [comment]
Do you have HiDPI/scaling set by any chance?

**Comment by 1player** [comment]
> Do you have HiDPI/scaling set by any chance?

I do, running on a 4K screen at 200% scaling.

**Comment by leaanthony** [comment]
I managed to reproduce this and confirmed it was a scaling issue. I've pushed a fix to the PR linked in the other issue. Let me know how you get on.

Oh, also, it looks like when I run the app from goland the app appears behind the IDE so just check that clicking the icon in the sidebar does bring the app forward, even if it's in a broken state. This might need a different fix 👍

**Comment by 1player** [comment]
> Oh, also, it looks like when I run the app from goland the app appears behind the IDE so just check that clicking the icon in the sidebar does bring the app forward, even if it's in a broken state.

I've seen that behaviour a few times. If you're on GNOME w/ Wayland this happens for some reason whenever you start a desktop app that hasn't been activated from the dock, I think it's an upstream bug.

I'll close this issue as it's a duplicate of #1517. I'll add a comment over there whenever I have the chance to try the fix.
