### ISSUE TITLE
[v2] linux - dev command stdoutScanner slice bounds out of range

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#1564]
### Description

With the current master, `wails dev` crashes at seemingly random times, both with an existing project and a clean wails app too.

At `/v2/cmd/wails/internal/commands/dev/stdout_scanner.go#L33` there is `line = strings.TrimSpace(line[index+6:])`

In some cases the index is `-1` and it causes a runtime panic. 
```panic: runtime error: slice bounds out of range [5:0]

goroutine 18 [running]:
github.com/wailsapp/wails/v2/cmd/wails/internal/commands/dev.(*stdoutScanner).Write(0xc00021a000, {0xc00009a000, 0x5a, 0x8000})
        /home/xxx/projects/mywails/v2/cmd/wails/internal/commands/dev/stdout_scanner.go:37 +0x365
io.copyBuffer({0xb263c0, 0xc00021a000}, {0xb26ce0, 0xc00021a010}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:428 +0x204
io.Copy(...)
        /usr/local/go/src/io/io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
        /usr/local/go/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0x0?)
        /usr/local/go/src/os/exec/exec.go:444 +0x25
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:443 +0x795
```

Here is the stdout when it occures (I put two log.Println()s there):

```
Building application for development...
  - Installing frontend dependencies: Done.
  - Compiling frontend: 
> frontend@0.0.0 dev /home/xxx/projects/xxx/frontend
> vite

Port 3000 is in use, trying another one...

  vite v2.9.12 dev server running at:

2022/07/14 12:17:37  line := sc.Text() => '> Local: http://localhost:3001/'
2022/07/14 12:17:37  index := strings.Index(line, "Local:") => '4'
Vite Server URL: http://localhost:3001/
2022/07/14 12:17:37  line := sc.Text() => '> Network: use `--host` to expose'
2022/07/14 12:17:37  index := strings.Index(line, "Local:") => '-1'
Vite Server URL: etwork: use `--host` to expose
2022/07/14 12:17:37  line := sc.Text() => ''
2022/07/14 12:17:37  index := strings.Index(line, "Local:") => '-1'
panic: runtime error: slice bounds out of range [5:0]
```

### To Reproduce

1. create a new wails app
2. run `$ wails dev`
3. run it a few times and the panic will occur

### Expected behaviour

I expect that the program starts in dev mode.

### Attempted Fixes

If we check that `line[index+6:]` is in bounds and if not, set data to an empty string `data = ""` it prevents the panic. However the issue may be somewhere else and this is just the symptom.

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Ubuntu
Version: 	22.04
ID:		ubuntu
Go Version:	go1.18.3
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.38
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.17
gcc		build-essential		Installed	12.9ubuntu3
libgtk-3	libgtk-3-dev		Installed	3.24.33-1ubuntu2
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.36.3-0ubuntu0.22.04.1
npm		npm			Installed	6.14.13
*nsis		nsis			Available	3.08-2
pkg-config	pkg-config		Installed	0.29.2-1ubuntu3

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```

**Comment by Lyimmi** [comment]
As a footnote I'm running a whole bunch of docker containers that are using ports around the 3000 range, so that could be an issue when wails dev works the wite server's port ends up around 3005-ish.

**Comment by leaanthony** [comment]
What's odd about that is we explicitly check for -1 and ignore it.

**Comment by leaanthony** [comment]
@Lyimmi - Please try the linked PR 👍

**Comment by Lyimmi** [comment]
@leaanthony it works fine!

I figured out why it's come out now. Ha have a sync.WaitGroup() that blocks the program's shoutdown. And I lost a wg.Done() somewhere... so Vite (or npm) never shuts down when I exit the program, so some entanglement is happening.

But PR #1566 fixes the panic on the next wails dev runs.

**Comment by leaanthony** [comment]
Thanks for the quick test 👍
