### ISSUE TITLE
[v2] Automatically inject /wails/ipc.js and /wails/runtime.js

### ISSUE THREAD

**Issue by acheong08** [wailsapp/wails#1565]
### Description

When trying to build an application with multiple pages in vanilla js, other than index.html, other pages do not have access to bindings.

### To Reproduce

1. Create a vanilla project template
2. Copy `frontend/index.html` to `frontend/home.html`
3. Add link to home.html in index.html
4. run `wails dev`
5. Open link
6. Press greet

### Expected behaviour

Run properly

### Screenshots

![image](https://user-images.githubusercontent.com/36258159/178967523-1ba39bdb-b010-427c-bbe0-82fbca3bb9e0.png)

### Attempted Fixes

Unsure of where to the issue stems from

### System Details

```shell
System
------
OS:		Ubuntu
Version: 	22.04
ID:		ubuntu
Go Version:	go1.18.1
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.38
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.17
gcc		build-essential		Installed	12.9ubuntu3
libgtk-3	libgtk-3-dev		Installed	3.24.33-1ubuntu2
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.36.3-0ubuntu0.22.04.1
npm		npm			Installed	8.5.1~ds-1
*nsis		nsis			Available	3.08-2
pkg-config	pkg-config		Installed	0.29.2-1ubuntu3

* - Optional Dependency

```
```


### Additional context

_No response_

**Comment by acheong08** [comment]
Same issue when running from http://localhost:3000/

**Comment by acheong08** [comment]
The reason is that the runtime and ipc are not automatically injected

**Comment by leaanthony** [comment]
Perhaps there's a better solution? We don't want to inject these for `*.html`.

**Comment by acheong08** [comment]
Is there a way to automatically inject?

**Comment by acheong08** [comment]
> Perhaps there's a better solution? We don't want to inject these for `*.html`.

Is that due to security considerations? Perhaps inject for `*.html` served by localhost.

**Comment by leaanthony** [comment]
It's not a security concern per-se, more that we can't assume that apps aren't loading html fragments into their documents.
