### ISSUE TITLE
[V2] Windows: can not run on Windows because crashed

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1571]
### Description

The app(exe file) will crashed on windows. I can find a `RuntimeBroker` event which ID is `10016` and source is `DistributedCOM` (from `Windows Events viewer`-> `Windows Log` -> `System`).

![Uploading image.png…]()

### To Reproduce

wails build -platform windows/amd64

and then run myproject.exe

P.S.: I have tried the way of building on windows or building by cross-compile, none of them succeed. 

### Expected behaviour

works on Windows.

### System Details

```shell
C:\Users\cuixiaotian>wails doctor
Wails CLI v2.0.0-beta.38


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.18.4
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.38

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.49
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
Thanks for opening this issue.

Could you please provide a stacktrace? It seems like your image wasn't uploaded.
Without any more information we are unable to help you.

**Comment by stffabi** [comment]
The best would be the console output of a 'wails build --debug'

**Comment by cxt90730** [comment]
the OS is windows10

**Comment by stffabi** [comment]
Thanks, very interesting, never seen that before.

Could you please build with the --debug flag and report the output of the console when the crash occurs? That could give us more information if it's a local problem with your machine or something globaly. 🙏

**Comment by cxt90730** [comment]
After I fix the permission on Windows , app runs well, and app that newer build app on Windows works well too. Then I run app on Windows in another computer, debug mode shows the go panic info, the `gorm` lib shows nil pointer problem . But it's strange that Mac works, the Windows which I fixed permission works,  ** the code is SAME **. I think it may be a problem that is difficult to solve...

<img width="742" alt="image" src="https://user-images.githubusercontent.com/11382804/179195788-e78ad96f-246c-4dfb-9910-1102492b9eec.png">

**Comment by cxt90730** [comment]
I later focus on this problem and thank you for your answer ~ @stffabi
