### ISSUE TITLE
Support pre-build hook with wails dev & wails build 

### ISSUE THREAD

**Issue by SgtPooki** [wailsapp/wails#1577]
### Is your feature request related to a problem? Please describe.

The problem is that my team already has built our front-end assets, and we just need to include it in our desktop app (https://github.com/ipfs/ipfs-desktop).

You can see in the README of https://github.com/SgtPooki/ipfs-desktop-wails, that we don't need a front-end command to run at all, but we do need a command to run to *get* our prebuilt frontend (see https://github.com/SgtPooki/ipfs-desktop-wails#run-a-local-version).

Since we need to get these front-end assets between `wails dev` and `wails generate module`, we get errors unless we run an explicit command prior to running `wails`. I believe it would be wise for wails to offer a solution for the multitude of usecases a preBuildHook could support.

### Describe the solution you'd like

`wails.json` already has `postBuildHooks`, I would like to propose `preBuildHooks`. Essentially an agnostic version of "frontend:*" though not necessarily a replacement.

For my issue, I would only need to run `./get-webui.sh` in the preBuildHook:

`wails.json`
```json
...
    "preBuildHooks": {
        "*/*": "./get-webui.sh"
    }
...
```

### Describe alternatives you've considered

The only two solutions I could think of that allow us to fully bundle our webui in the app (obtaining via runtime is not a viable solution) are:
1. require build process to run our `get-webui.sh` shell script prior to running wails command
2. move .get-webui.sh to `./frontend/get-webui.sh` and set `"frontend:build": "bash ./get-webui.sh",` in `wails.json`

### Solution 1
This works, and is okay, but definitely not ideal, requires build cmd to be:
```bash
./get-webui.sh && wails build # or wails dev
```
at least on the first run. 

### Solution 2

This is currently what I'm using as it's the desired DX I want. See https://github.com/SgtPooki/ipfs-desktop-wails/commit/fab24911d05a16ac0852414ad82086149b24404c

but allows us to have a single canonical wails build command: 
```bash
wails build # or wails dev
```

##### With no `./frontend` folder:

```bash
╰─ ✔ ❯ wails dev -v 2
Wails CLI v2.0.0-beta.38


Executing: go mod tidy -compat=1.17
Executing: wails generate module


ERROR:
main.go:10:12: pattern frontend: no matching files found
```

##### with existing `./frontend/.gitkeep`

```bash
╰─ ✔ ❯ wails dev -v 2
Wails CLI v2.0.0-beta.38


Executing: go mod tidy -compat=1.17
Executing: wails generate module


ERROR:
main.go:10:12: pattern frontend: cannot embed directory frontend: contains no embeddable files

exit status 1

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony


exit status 1
```

##### With empty `./frontend/index.html`

This allows things to work, but I don't like the idea that wails could be modifying/hooking into a file that will be overwritten.

**Comment by leaanthony** [comment]
Thanks for the amazingly detailed enhancement request. Should be trivial to implement this and I can see the need.

**Comment by leaanthony** [comment]
@SgtPooki - Please check the linked PR. Is this what you had in mind?

**Comment by SgtPooki** [comment]
@leaanthony This is amazing. Your PR nails the interface I want. I am not the right person to speak to how you implemented it, but I believe the surface area is absolutely what I needed!
