### ISSUE TITLE
runtime.Dialog.SelectFile support multi-file select and file type filter

### ISSUE THREAD

**Issue by sotoup** [wailsapp/wails#158]

**Comment by leaanthony** [comment]
Hi @sotoup. Thanks for opening this issue. This is currently a limitation of using the underlying WebView library. Replacing this library is becoming a priority now so we'll make sure we keep this in the backlog for our replacement.

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page
