### ISSUE TITLE
possible to support linux

### ISSUE THREAD

**Issue by passerbyo** [wailsapp/wails#1581]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

refer to cef,electron,astilectron

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`
