### ISSUE TITLE
[v2] Not found error in production

### ISSUE THREAD

**Issue by acheong08** [wailsapp/wails#1582]
### Description

Assets cannot be found in production build but can be in `wails dev`. 

### To Reproduce

In `index.html`, I placed a simple <a> tag linking to home.html. I then created home.html in the same directory with random text.

In production, index.html loads. However, when going to the href, it returns `Not found`

This problem does not exist on `wails dev`

### Expected behaviour

Load and show file

### Screenshots

![image](https://user-images.githubusercontent.com/36258159/179395660-87cb987a-a0f0-43bd-ad4d-bb6c2e763d99.png)
![image](https://user-images.githubusercontent.com/36258159/179395671-57381129-dbbb-43b6-b41c-e820ccc0dee8.png)

### Attempted Fixes

Using javascript `window.location.href = ` and putting files in different directories. 

### System Details

```shell
System
------
OS:		Ubuntu
Version: 	22.04
ID:		ubuntu
Go Version:	go1.18.4
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.38
Revision:		764dadc8f44ea47107ca4d91d1df11db6b58bb48
Modified:		true
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.17
gcc		build-essential		Installed	12.9ubuntu3
libgtk-3	libgtk-3-dev		Installed	3.24.33-1ubuntu2
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.36.3-0ubuntu0.22.04.1
npm		npm			Installed	8.5.1~ds-1
*nsis		nsis			Available	3.08-2
pkg-config	pkg-config		Installed	0.29.2-1ubuntu3

```

### Additional context

Using `bugfix/linux_scaling_issues` branch. Latest commits pulled and merged

**Comment by stffabi** [comment]
Thanks for reporting this issue and using Wails.

This might happen if e.g. the embedded folder is not fully populated during the frontend build phase. In your `main.go` you normally have something like this which points to the assets folder `frontend/dist` to be included.

```
//go:embed frontend/dist
var assets embed.FS`
```

Just to be sure could you check if that folder contains both files after you have executed a `wails build`?

**Comment by leaanthony** [comment]
Hmmmm..... This is an interesting point.... Vite is serving files from src not dist. If your build step is not right it could lead to this.

**Comment by acheong08** [comment]
> Thanks for reporting this issue and using Wails.
> 
> This might happen if e.g. the embedded folder is not fully populated during the frontend build phase. In your `main.go` you normally have something like this which points to the assets folder `frontend/dist` to be included.
> 
> ```
> //go:embed frontend/dist
> var assets embed.FS`
> ```
> 
> Just to be sure could you check if that folder contains both files after you have executed a `wails build`?

`var assets embed.FS` is on line 11
strangely, frontend/dist empty except for index.html

**Comment by acheong08** [comment]
Building with `npm run build` returns

```
vite v2.9.12 building for production...
<script src="/wails/ipc.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="/wails/runtime.js"> in "/index.html" can't be bundled without type="module" attribute
✓ 1 modules transformed.
Generated an empty chunk: "index"
dist/index.html   0.53 KiB

```

**Comment by acheong08** [comment]
I am using the vanilla template

**Comment by stffabi** [comment]
Normall you don't need to add `<script src="/wails/ipc.js">` or `<script src="/wails/runtime.js">` to your index.html. That will be injected automatically by Wails, you would only need that if you wan't inject the bindings into another html file other than index.html.

**Comment by acheong08** [comment]
> Normall you don't need to add `<script src="/wails/ipc.js">` or `<script src="/wails/runtime.js">` to your index.html. That will be injected automatically by Wails, you would only need that if you wan't inject the bindings into another html file other than index.html.

That was to fix strange behavior when running `wails dev' and using the browser. I will try to remove that

**Comment by acheong08** [comment]
```
✓ 1 modules transformed.
Generated an empty chunk: "index"
dist/index.html   0.28 KiB
```
Why is index.html the only thing being built?

**Comment by stffabi** [comment]
> That was to fix strange behavior when running `wails dev' and using the browser. I will try after removing that

If you are seeing strange behaviour when using the wails dev server in your browser by accessing `localhost:34115` we are very interested in fixing that. Please keep in mind not to use `localhost:3000`, because that's the devserver of vite itself, which won't inject the bindings.

**Comment by stffabi** [comment]
> ```
> ✓ 1 modules transformed.
> Generated an empty chunk: "index"
> dist/index.html   0.28 KiB
> ```
> 
> Why is index.html the only thing being built?

I'm not very familiar with all the frontend SDK toolings. Maybe @leaanthony has an idea?

**Comment by acheong08** [comment]
I see the issue. `vite build` attempts to optimize by building only resources explicitly used by index.html. However, resources linked but not used are not included in `dist/assets`

**Comment by acheong08** [comment]
https://stackoverflow.com/a/68548046

**Comment by stffabi** [comment]
> https://stackoverflow.com/a/68548046 I suppose this is a feature of their optimizer?

Yeah, seems so.

**Comment by acheong08** [comment]
The solution provided by Vite does not work... https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url
Linking the file in JavaScript still does not get added to assets

**Comment by stffabi** [comment]
You mean it's still not added to the dist folder by vite?

**Comment by acheong08** [comment]
> You mean it's still not added to the dist folder by vite?

yes. I will read up on vite's documentation more, not really an expert in javascript

**Comment by acheong08** [comment]
It seems that a `vite.config.js` file is needed to declare `html` files. CSS, JS, and images are the only ones automatically loaded by vite.

**Comment by acheong08** [comment]
This would be a nice to have in the documentation under frontend -> Multi-page applications or something like that

**Comment by leaanthony** [comment]
@acheong08 - Glad you fixed it. Would you consider writing your findings as a Guide or part of the Troubleshooting page for the docs?

**Comment by acheong08** [comment]
Should I place this in troubleshooting as `Not Found` error or as a Guide for multi page applications?

**Comment by leaanthony** [comment]
Thanks for that! Merged 👍
