### ISSUE TITLE
win10 crash

### ISSUE THREAD

**Issue by BigCatGit** [wailsapp/wails#1584]
### Description

After the front end is overloaded for many times， go server crash

Exception 0xc0000005 0x1 0xc00063c000 0x7fff443b6e60
PC=0x7fff443b6e60
signal arrived during external code execution

runtime.cgocall(0x7ff65dbd65a0, 0x7ff65e7012a0)
        D:/Dev/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000650e10 sp=0xc000650dd8 pc=0x7ff65db74b0a
syscall.SyscallN(0x7fff443b6e40?, {0xc000650ea8?, 0x3?, 0x0?})
        D:/Dev/Go/src/runtime/syscall_windows.go:538 +0x109 fp=0xc000650e88 sp=0xc000650e10 pc=0x7ff65dbd1829
syscall.Syscall(0x7ff65e700fe0?, 0xc00021c000?, 0x7ff65db7e7e5?, 0xd50002010d6389a0?, 0xc000650f28?)
        D:/Dev/Go/src/runtime/syscall_windows.go:476 +0x3b fp=0xc000650ed0 sp=0xc000650e88 pc=0x7ff65dbd143b
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/go-webview2/pkg/edge.ComProc.Call(0x0?, {0xc00021c010?, 0xc000650fc0?, 0x7ff65db7eb47?})
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/go-webview2/pkg/edge/corewebview2.go:81 +0x125 fp=0xc000650f88 sp=0xc000650ed0 pc=0x7ff65df3c985
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/go-webview2/pkg/edge.(*ICoreWebView2HttpHeadersCollectionIterator).MoveNext(0x6c740024e070)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2HttpHeadersCollectionIterator.go:65 +0x79 fp=0xc000650fd0 sp=0xc000650f88 pc=0x7ff65df38079
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.coreWebview2RequestToHttpRequest.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/frontend.go:692 +0x3d2 fp=0xc000651178 sp=0xc000650fd0 pc=0x7ff65df5b0d2
github.com/wailsapp/wails/v2/internal/frontend/assetserver.(*AssetServer).ProcessHTTPRequest(0xc00006b040, {0xc00063bea0, 0xf}, {0x7ff65e42a648?, 0xc00025ed40}, 0xc0003a6730)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/assetserver/assetserver.go:114 +0xd2 fp=0xc000651288 sp=0xc000651178 pc=0x7ff65df2ce32
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processRequest(0xc0001e2200, 0x6c7400238780?, 0x6c7400238780)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/frontend.go:461 +0x2cd fp=0xc000651490 sp=0xc000651288 pc=0x7ff65df594cd
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processRequest-fm(0x6c7400238780?, 0x7ff65db84f8c?)
        <autogenerated>:1 +0x2f fp=0xc0006514b8 sp=0xc000651490 pc=0x7ff65df5dc6f
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/go-webview2/pkg/edge.(*Chromium).WebResourceRequested(0xc000154240, 0xc0006515e8?, 0xc000651560?)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go:301 +0xbd fp=0xc000651528 sp=0xc0006514b8 pc=0x7ff65df3c1dd
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/go-webview2/pkg/edge._ICoreWebView2WebResourceRequestedEventHandlerInvoke(0xc000651570?, 0x7ff65dbd2f1d?, 0x0?)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2WebResourceRequestedEventHandler.go:26 +0x22 fp=0xc000651550 sp=0xc000651528 pc=0x7ff65df38fa2
runtime.call32(0x0, 0x7ff65e38e890, 0xc0006515e8, 0x0, 0x0, 0x18, 0xc000651840)
        D:/Dev/Go/src/runtime/asm_amd64.s:702 +0x50 fp=0xc000651580 sp=0xc000651550 pc=0x7ff65dbd2fb0
runtime.callbackWrap(0x3d3e7fda90)
        D:/Dev/Go/src/runtime/syscall_windows.go:378 +0x134 fp=0xc000651960 sp=0xc000651580 pc=0x7ff65dbc3114
runtime.cgocallbackg1(0x7ff65dbc2fe0, 0xc000651b20?, 0x0)
        D:/Dev/Go/src/runtime/cgocall.go:314 +0x2ca fp=0xc000651a30 sp=0xc000651960 pc=0x7ff65db750aa
runtime.cgocallbackg(0xc000052000?, 0x300000002?, 0xc000052000?)
        D:/Dev/Go/src/runtime/cgocall.go:233 +0x106 fp=0xc000651ac8 sp=0xc000651a30 pc=0x7ff65db74ce6
runtime.cgocallbackg(0x7ff65dbc2fe0, 0x3d3e7fda90, 0x0)
        <autogenerated>:1 +0x36 fp=0xc000651af0 sp=0xc000651ac8 pc=0x7ff65dbd6d16
runtime.cgocallback(0x7ff65db74b6b, 0x7ff65dbd65a0, 0x7ff65e7012a0)
        D:/Dev/Go/src/runtime/asm_amd64.s:971 +0xd7 fp=0xc000651b18 sp=0xc000651af0 pc=0x7ff65dbd4ab7
runtime.systemstack_switch()
        D:/Dev/Go/src/runtime/asm_amd64.s:436 fp=0xc000651b20 sp=0xc000651b18 pc=0x7ff65dbd29a0
runtime.cgocall(0x7ff65dbd65a0, 0x7ff65e7012a0)
        D:/Dev/Go/src/runtime/cgocall.go:167 +0xab fp=0xc000651b58 sp=0xc000651b20 pc=0x7ff65db74b6b
syscall.SyscallN(0x7fff8be7e040?, {0xc00063be58?, 0x1?, 0x7ff65e700fe0?})
        D:/Dev/Go/src/runtime/syscall_windows.go:538 +0x109 fp=0xc000651bd0 sp=0xc000651b58 pc=0x7ff65dbd1829
syscall.(*Proc).Call(0x7ff65db7eb47?, {0xc00063be58?, 0x7ff65e16e7a0?, 0xc000224101?})
        D:/Dev/Go/src/syscall/dll_windows.go:190 +0x25 fp=0xc000651c10 sp=0xc000651bd0 pc=0x7ff65dc18225
syscall.(*LazyProc).Call(0xc0001ead20, {0xc00063be58, 0x1, 0x1})
        D:/Dev/Go/src/syscall/dll_windows.go:310 +0x50 fp=0xc000651c40 sp=0xc000651c10 pc=0x7ff65dc186d0
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc/w32.DispatchMessage(...)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/winc/w32/user32.go:338
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc.RunMainLoop()
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/winc/app.go:83 +0x16e fp=0xc000651cb8 sp=0xc000651c40 pc=0x7ff65df4868e
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Window).Run(0xc0001e2200?)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/window.go:131 +0x1e fp=0xc000651cd0 sp=0xc000651cb8 pc=0x7ff65df5cc1e
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run(0xc0001e2200, {0x7ff65e42a938, 0xc000226180})
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/desktop/windows/frontend.go:173 +0x265 fp=0xc000651d18 sp=0xc000651cd0 pc=0x7ff65df577c5
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run(0xc0001dcbd0, {0x7ff65e42a938?, 0xc000226180})
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/devserver/devserver.go:135 +0x787 fp=0xc000651eb8 sp=0xc000651d18 pc=0x7ff65dfde7e7
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc00006c550)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/appng/app_dev.go:55 +0x31 fp=0xc000651ef0 sp=0xc000651eb8 pc=0x7ff65dfe5e31
github.com/wailsapp/wails/v2.Run(0xc0001fe200)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/wails.go:40 +0xf4 fp=0xc000651f18 sp=0xc000651ef0 pc=0x7ff65dfe8154
main.main()
        D:/Github/D:\Github\Test/GoWails_Version/D:\Github\TestAI/main.go:33 +0x38d fp=0xc000651f80 sp=0xc000651f18 pc=0x7ff65dfe898d
runtime.main()
        D:/Dev/Go/src/runtime/proc.go:250 +0x1fe fp=0xc000651fe0 sp=0xc000651f80 pc=0x7ff65dbaa1be
runtime.goexit()
        D:/Dev/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000651fe8 sp=0xc000651fe0 pc=0x7ff65dbd4d21

goroutine 6 [syscall, 40 minutes]:
os/signal.signal_recv()
        D:/Dev/Go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        D:/Dev/Go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        D:/Dev/Go/src/os/signal/signal.go:151 +0x2a

goroutine 7 [chan receive, 40 minutes]:
github.com/wailsapp/wails/v2/internal/signal.Start.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/signal/signal.go:31 +0x26
created by github.com/wailsapp/wails/v2/internal/signal.Start
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/signal/signal.go:29 +0x91

goroutine 8 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x201343a4ec8, 0x72)
        D:/Dev/Go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x23?, 0xc000065b18?, 0x0)
        D:/Dev/Go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc0002a4018, 0xc000065b20)
        D:/Dev/Go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc0002a4000, 0x8b4, {0xc0002ac0f0?, 0x0?, 0x0?}, 0xc000065d14?)
        D:/Dev/Go/src/internal/poll/fd_windows.go:942 +0x6d
internal/poll.(*FD).Accept(0xc0002a4000, 0xc000065cf8)
        D:/Dev/Go/src/internal/poll/fd_windows.go:976 +0x1d6
net.(*netFD).accept(0xc0002a4000)
        D:/Dev/Go/src/net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc00029c048)
        D:/Dev/Go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).AcceptTCP(0xc00029c048)
        D:/Dev/Go/src/net/tcpsock.go:275 +0x3d
github.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x7ff65dbb25c0?})
        C:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:941 +0x1d
net/http.(*Server).Serve(0xc0001de2a0, {0x7ff65e42a0d8, 0xc00028e008})
        D:/Dev/Go/src/net/http/server.go:3039 +0x385
github.com/labstack/echo/v4.(*Echo).Start(0xc00018ed80, {0xc000022fa8, 0xf})
        C:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:647 +0xce
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func4(0x0?, 0x0?)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/devserver/devserver.go:117 +0x36
created by github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/devserver/devserver.go:116 +0x69b

goroutine 22 [syscall, 40 minutes]:
github.com/robotn/gohook._Cfunc_start_ev()
        _cgo_gotypes.go:118 +0x4e
created by github.com/robotn/gohook.Start
        C:/Users/Administrator/go/pkg/mod/github.com/robotn/gohook@v0.31.3/hook.go:225 +0x51

goroutine 23 [sleep]:
time.Sleep(0x2faf080)
        D:/Dev/Go/src/runtime/time.go:194 +0x133
github.com/robotn/gohook.Start.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/robotn/gohook@v0.31.3/hook.go:235 +0x39
created by github.com/robotn/gohook.Start
        C:/Users/Administrator/go/pkg/mod/github.com/robotn/gohook@v0.31.3/hook.go:228 +0x65

goroutine 21 [chan receive]:
github.com/go-vgo/robotgo.AddEvents({0x7ff65e2173b9, 0x2}, {0x0, 0x0, 0xc0000060d0?})
        C:/Users/Administrator/go/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/hook.go:113 +0x98
TestAI/src/ctlr.(*MainController).KeyboardListen(0x7ff65dbb12a5?, {0x7ff65e2173b9, 0x2}, {0x0, 0x0, 0x0})
        D:/Github/Test/GoWails_Version/TestAI/src/ctlr/MainController.go:61 +0x65
created by TestAI/src/ctlr.(*MainController).RegisterHotKeys
        D:/Github/Test/GoWails_Version/TestAI/src/ctlr/MainController.go:56 +0x56

goroutine 220 [IO wait]:
internal/poll.runtime_pollWait(0x201343a4dd8, 0x72)
        D:/Dev/Go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x18?, 0xc000081400?, 0x0)
        D:/Dev/Go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc0002a4298, 0x7ff65e38ec38)
        D:/Dev/Go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc0002a4280, {0xc00031c000, 0x1000, 0x1000})
        D:/Dev/Go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc0002a4280, {0xc00031c000?, 0x0?, 0xc00064d6c8?})
        D:/Dev/Go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000588010, {0xc00031c000?, 0xc000505520?, 0xc00064d6f8?})
        D:/Dev/Go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc000318780, {0xc00031c000, 0x1000, 0x1000})
        D:/Dev/Go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc0001e4de0)
        D:/Dev/Go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc0001e4de0, 0x0?)
        D:/Dev/Go/src/bufio/bufio.go:371 +0x2f
bufio.(*Reader).ReadLine(0xc0001e4de0)
        D:/Dev/Go/src/bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc000315c50)
        D:/Dev/Go/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
        D:/Dev/Go/src/net/textproto/reader.go:38
net/http.readRequest(0xc000588010?)
        D:/Dev/Go/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc000100000, {0x7ff65e42a890, 0xc000313740})
        D:/Dev/Go/src/net/http/server.go:988 +0x24a
net/http.(*conn).serve(0xc000100000, {0x7ff65e42a938, 0xc00028a210})
        D:/Dev/Go/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
        D:/Dev/Go/src/net/http/server.go:3071 +0x4db
rax     0x1
rbx     0x7ff65e7012a0
rcx     0x6c740024e080
rdi     0x6c740024e070
rsi     0xc00063bffd
rbp     0xc000650e00
rsp     0x3d3e7fd870
r8      0x0
r9      0x0
r10     0x201342d2538
r11     0xc00021c010
r12     0xc000650f50
r13     0x0
r14     0xc000052000
r15     0xffffffffffffffff
rip     0x7fff443b6e60
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
[0718/015738.191:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0

Caught quit
Development mode exited

### To Reproduce

wails dev

### Expected behaviour

go server running

### System Details

```shell
win10
```

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`

**Comment by BigCatGit** [comment]
It is difficult to reproduce this problem. I have used wails for several months, and it occasionally occurs. Sometimes the code does not change, but the go server side will automatically compile overloads, which may be caused by this reason.

### wails doctor output:
Wails CLI v2.0.0-beta.38


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.18.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.38

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.62
npm             N/A             Installed       8.13.2
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Installed       v3.08

**Comment by stffabi** [comment]
Thanks for reporting this issue and using Wails.

I was able to reproduce it with a fast reload using setTimeout and location.reload().

**Comment by BigCatGit** [comment]
thanks

**Comment by BigCatGit** [comment]
thanks

**Comment by stffabi** [comment]
I've reopened the bug until the PR gets merged so people know it's not fixed yet on master.

**Comment by BigCatGit** [comment]
ok

**Comment by leaanthony** [comment]
@BigCatGit merged, but please let us know how you get on 👍

**Comment by BigCatGit** [comment]
I reinstalled wails and used it for several hours. I didn't find any problems for the time being, 
But there are two new problems:

1. mainapp.Shutdown undefined (type *appng.App has no field or method Shutdown)
   ![image](https://user-images.githubusercontent.com/20128656/179550091-b96928a6-1985-4509-a653-14474e684481.png)
2. Wails CLI v2.0.0-beta.38
Executing: go mod tidy -compat=1.17
Executing: C:\Users\Administrator\go\bin\wails.exe generate module

INFO[2022-07-18 23:45:39] 获取项目路径: D:\Github\GoLostArk\GoWails_Version\Test
2022/07/18 23:45:39 cannot call 'github.com/wailsapp/wails/v2/pkg/runtime.EventsEmit': context is nil



ERROR:
INFO[2022-07-18 23:45:39] 获取项目路径: D:\Github\GoLostArk\GoWails_Version\Test
2022/07/18 23:45:39 cannot call 'github.com/wailsapp/wails/v2/pkg/runtime.EventsEmit': context is nil

exit status 1

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

**Comment by BigCatGit** [comment]
I am use Wails CLI v2.0.0-beta.38,
The code is the template code generated by wails cli, and the onshutdown function is consistent with the document, or is this error reported.
This warning is prompted internally by SDK.
![image](https://user-images.githubusercontent.com/20128656/179679528-661aac1a-c46f-40dd-8c4e-3ccd027a0023.png)
![image](https://user-images.githubusercontent.com/20128656/179679717-69c371f0-a4af-4e6a-9521-66161e5aaa53.png)

**Comment by leaanthony** [comment]
Ah apologies. Wails v1 had a CreateApp method and it looked like that :-) Someone reported the Shutdown bug so let's track it there https://github.com/wailsapp/wails/issues/1594.

**Comment by BigCatGit** [comment]
ok
