### ISSUE TITLE
[V2] Mac: Cannot show menus correctly

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1588]
### Description

Cannot show menus correctly on mac. Location and label display is not what I expect. I don't know if the document needs to be updated?  (e.g. runtime.Quit now needs ctx of lifecycle, but document of `Menus` do not show this.)

### To Reproduce

Mycode:

```
        AppMenu := menu.NewMenu()
	FileMenu := AppMenu.AddSubmenu("File")
	FileMenu.AddText("WindowSetTitle", keys.CmdOrCtrl("1"), func(_ *menu.CallbackData) {
		runtime.WindowSetTitle(ctx, time.Now().Local().String())
	})
	FileMenu.AddSeparator()
	FileMenu.AddText("WindowCenter", keys.CmdOrCtrl("2"), func(_ *menu.CallbackData) {
		runtime.WindowCenter(ctx)
	})
	FileMenu.AddSeparator()
	FileMenu.AddText("WindowSetLightTheme", keys.CmdOrCtrl("3"), func(_ *menu.CallbackData) {
		runtime.WindowSetLightTheme(ctx)
	})
	FileMenu.AddText("WindowSetDarkTheme", keys.CmdOrCtrl("4"), func(_ *menu.CallbackData) {
		runtime.WindowSetDarkTheme(ctx)
	})
	FileMenu.AddSeparator()
	FileMenu.AddText("WindowGetSize", keys.CmdOrCtrl("5"), func(_ *menu.CallbackData) {
		fmt.Println(runtime.WindowGetSize(ctx))
	})
	if os_runtime.GOOS == "darwin" {
		AppMenu.Append(menu.AppMenu())
		AppMenu.Append(menu.EditMenu()) // on macos platform, we should append EditMenu to enable Cmd+C,Cmd+V,Cmd+Z... shortcut
	}
	runtime.MenuSetApplicationMenu(ctx, AppMenu)
```

![Uploading image.png…]()

### Expected behaviour

display correct

### System Details

```shell
unnecessary...
```

**Comment by cxt90730** [comment]
![image](https://user-images.githubusercontent.com/11382804/179446719-f037dbd1-d677-4f94-a1ce-8a5c4934fb04.png)

**Comment by cxt90730** [comment]
emmm, I need to add these code before:

```
         AppMenu := menu.NewMenu()
	if os_runtime.GOOS == "darwin" {
		AppMenu.Append(menu.AppMenu())
	}
```

because Mac default occupied the first position of the Menuitem, and cannot change the label name

**Comment by leaanthony** [comment]
So is it that the docs need improving? It's not clear what's happening with this ticket 👍

**Comment by leaanthony** [comment]
Great. Can this be closed then?

**Comment by cxt90730** [comment]
@acheong08 @leaanthony Sorry, I may not express it clearly. According to the document, I cannot show the submenu `File` ,   because Mac default occupied the first position of the Menuitem, and cannot change the menu's label name.  I must write code like this way first :     
```
 AppMenu := menu.NewMenu()
	if os_runtime.GOOS == "darwin" {
		AppMenu.Append(menu.AppMenu())
	}
```

and then, I can add other menu that I customized or `menu.EditMenu()`, otherwise, the display will not be correct.

P.S.  `runtime.Quit()` now is need arg `ctx`, so the example in `Reference > Menus` is wrong...

**Comment by acheong08** [comment]
Confirmed on MacOS 12.4. The first Menu will always be the Application menu on MacOS, documentation needs to be updated.
