### ISSUE TITLE
how to transfer file between frontend and backend?

### ISSUE THREAD

**Issue by SPARON** [wailsapp/wails#1590]
### Is your feature request related to a problem? Please describe.

1. how to transfer file from frontend to backend?
2. how to transfer file from backend to frontend?

### Describe the solution you'd like

I want to trans file between  frontend and backend, but they have different langurage types...

**Comment by leaanthony** [comment]
Try this https://wails.io/docs/next/guides/dynamic-assets

**Comment by SPARON** [comment]
> Try this https://wails.io/docs/next/guides/dynamic-assets

not assets, i want to trans file in func methods

**Comment by layxyer** [comment]
According to my current use of wails, the front-end is mainly responsible for ui, the needs you describe can use the wails Dialog to get the file path, go get the file path after doing anything

**Comment by lsm1103** [comment]
> https://wails.io/docs/next/guides/dynamic-assets
那存储文件怎么做
