### ISSUE TITLE
Native window control (DWM, NS, GTK) + Plugin Architecture

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1592]
### Discussed in https://github.com/wailsapp/wails/discussions/1587

<div type='discussions-op-text'>

<sup>Originally posted by **brys0** July 18, 2022</sup>
I'm not sure if this exists yet but I couldn't find any documentation on the topic. I'd appreciate it if we had the ability to add our own methods or controllers for the window. For example using experimental unreleased DWM flags from Windows would be excellent. Having the ability to also use custom items from NS for Mac and GTK for Linux would be amazing. Following this, the ability to create wails plugins (maybe it call it wailins) would be great for people who don't want to dive head first into golang for everything.</div>

**Comment by sidwebworks** [comment]
@leaanthony Just like 15 mins ago I was thinking about how hard is it to build a plugin architecture for a go application. And what if wails had it 😀 looks like you read my mind lol.

**Comment by sidwebworks** [comment]
Are thinking of something like Webpack or Vite plugin system in terms lf api design? I would seriously love to help out with this if possible though I got zero idea about go plugins package and basically how this will work

**Comment by leaanthony** [comment]
There's different classes of plugin: the one mentioned above (extending windowing functionality) and "routing plugins" that give you a way of hooking into the AssetHandler so you can extend the API.

**Comment by brys0** [comment]
> Are thinking of something like Webpack or Vite plugin system in terms lf api design? I would seriously love to help out with this if possible though I got zero idea about go plugins package and basically how this will work 

Ideally the API would be completely separated beyond importing an API file for the js (WebView) side of things. Having it have to confirm to the webpack/vite plugin architecture, doesn't make sense. Something as simple as importing a function like: "usePlugin" and making it an async callback with returns the data from the go (backend) side would be plenty sufficient

**Comment by brys0** [comment]
If you need any help for implementing this I suggest you look at plugins that tauri has and how the JS side actually does implement functions and so-fourth

**Comment by leaanthony** [comment]
I think this is covered in v3 by the "Services' design + the ability to get the native window handle. Closing this for now.
