### ISSUE TITLE
Possible to load remote url like http://127.0.0.1:80/index.html as gui

### ISSUE THREAD

**Issue by passerbyo** [wailsapp/wails#1601]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

use gin or beego to serve index and wails to serve it

**Comment by stffabi** [comment]
Thanks for opening this request.

The [discussion](https://github.com/wailsapp/wails/discussions/1361#discussioncomment-2660071) here might help you and this [Dynamic Assets](https://wails.io/docs/guides/dynamic-assets).

If you want to use gin or another Go framework you could pass their http.Handler as an [options.AssetsHandler](https://wails.io/docs/reference/options/#assetshandler-) while setting `options.Assets` to nil. Please keep in mind there are some limitations of the AssetsHandlers, especially on Linux.

**Comment by stffabi** [comment]
Unfortunately we haven't heard anything back, so I'll close this issue.

Please feel free to open a new issue if you have any problems with the AssetsHandler or have any further questions.
