### ISSUE TITLE
Feature Request (?): Use Wails with a static (prebuilt) Frontend folder

### ISSUE THREAD

**Issue by cookiengineer** [wailsapp/wails#1603]
### Is your feature request related to a problem? Please describe.

Currently, it seems that the `frontend: {}` section of the `project.json` file assumes that a webpack project is being built, as a lot of integrations in there seem to just build all js and css into a specific file that's then being embedded by go via `// go:embed ./path/to/file.min.js`.

My question is now the following:

Is it possible to use wails without any further build steps? I've got a statically prebuilt `/public` folder inside my project, which contains all assets, is self-contained and can be served statically.

What I was assuming is that Wails runs webview/webview with the given parameters of the `index.html` path. But it somehow seems to enforce also a specific bridge, which is concated together as a path string!?

In my case the project looks like:

- `/public/index.html` is the entry point
- `/public/design/*` is the asset folder for everything
- `/public/source/*` is the ES6 code for the frontend (via `<script type="module">`)

What I tried to do was the following:

I configured my git repo so that there's the following structure:

- `/public/*` as before
- `/server/*` as before (golang server implementation)
- `/main.go` that is the entry point for `wails.CreateApp()`
- `/project.json` points to `dir: "public"` and `bridge: "bridge"`
- Tried out with a `/public/bridge/index.html` with a test content, but it doesn't load either.

Additionally, I wanted to integrate the runtime APIs via an ES6 import in the App's `Client`, so that if run inside the wails runtime it can simply use the local filesystem APIs; and if run via web server it can use the networked APIs. Structs and everything regarding filesystem APIs is prepared for this purpose already.

What I don't understand right now is how the `bridge` works. Is the `bridge` the entry point for the Wails Webview? Because the paths in the `project.json` are different from what the webpack example generates; as there it's in the `frontend/build/index.html` folder.

Is the Webview assuming a `frontend/build/index.html` path? How is the HTML and all assets like webfonts embedded if they're not inside a generated `.min.css` or `.min.js` file? Is there a way to embed all files and point the webview directly to the `/public/index.html`?

Currently, no matter whether I modify the `public/bridge/index.html` file or the `public/build/index.html` file, it doesn't seem to load... so for me it's unclear how to make Wails work without npm or webpack.

I've uploaded the source code of my project to the `wails-test` branch here, in case of reproducibility issues: https://github.com/cookiengineer/agenda/tree/wails-test

### Describe the solution you'd like

It would be awesome if wails.CreateApp() would provide an easy way to simply point to a `/public` folder, and that the `runtime` bindings would be offered without a third-party NPM package, and just via a `global.runtime` property or similar.

**Comment by stffabi** [comment]
Thanks for opening this issue and using Wails.

It seems like you are using Wails v1 which is in feature freeze. We highly recommend you to switch to Wails v2, which should already support what you need. Please take a look onto the new [docs page](https://wails.io/docs/gettingstarted/installation) for any further information.

You could basically create a new plain template with `wails init -t plain -n MyProject` then put all your assets in `frontend/src` and build and run your project.
Afterwards you could go ahead and add the go code and start calling your methods from the frontend if needed.

**Comment by cookiengineer** [comment]
Dang it. I tried out the latest for v2, but it segfaults on my system.

Opened up another bug report: https://github.com/wailsapp/wails/issues/1608
