### ISSUE TITLE
Golang build tags not working with wails build

### ISSUE THREAD

**Issue by monopolly** [wailsapp/wails#1610]
### Description

Hi guys. 
I am stuck.
Wails cli build don't see a packages build's tags for other platforms like "+windows"
But go build works fine. Could you advice me how to solve it?
I am newbie in desktop apps, so maybe I do something wrong?

### To Reproduce

- Init wails project
- Add module: go get github.com/akrylysov/pogreb@v0.10.1
- Run: GOOS=windows GOARCH=amd64 wails build -clean -platform windows
- Got error: ../../../../../pkg/mod/github.com/akrylysov/pogreb@v0.10.1/fs/os_mmap_windows.go:23:13: undeclared name maxMmapSize for array length

### Expected behaviour

Its not an error

### Attempted Fixes

I tried different tags for wails build but no success.

But clean go build works fine
GOOS=windows GOARCH=amd64 go build -tags desktop,production -ldflags "-w -s -H windowsgui" -o example.exe

### System Details

```shell
System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.38

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available	
*nsis 				N/A		Installed	v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
```

**Comment by leaanthony** [comment]
Thanks for opening this @monopolly. You found a genuine bug, though I'm not sure we really saw it as a bug as `-platform` would still work as expected (In your case, `-platform windows/amd64` with no `GOARCH` would work fine). That being said, I think it's reasonable to allow the env vars to override the platform. The attached PR does this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). Let me know how you get on👍

**Comment by leaanthony** [comment]
This is now merged. $GOOS will be used by default if no platform specified. $GOARCH will be used if no arch specified. If these aren't given then runime.GOOS and runtime.GOARCH are used 👍
