### ISSUE TITLE
mac下目前无法创建app

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#1612]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/45232501/179930132-7de6949f-8dd8-499c-a176-9b92acb92a5e.png)
mac什么时候能实现

### Describe the solution you'd like

mac什么时候能实现

**Comment by leaanthony** [comment]
https://wails.io/docs/gettingstarted/building

**Comment by nap-yu** [comment]
https://user-images.githubusercontent.com/45232501/179941847-bff7ebfe-0efe-42e8-a9c3-c1eba53eb014.mp4

build是可以的。但是在开发不是下不行

**Comment by misitebao** [comment]
@nap-yu 
请提供一个可以复现你的错误的最小步骤，否则我们没办法知道发生了什么。

Please provide a minimal step to reproduce your error, otherwise we have no way of knowing what happened.
