### ISSUE TITLE
mac开发模式下无法启动

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#1617]
https://user-images.githubusercontent.com/45232501/179941847-bff7ebfe-0efe-42e8-a9c3-c1eba53eb014.mp4

build是可以的。但是在开发不是下不行

_Originally posted by @nap-yu in https://github.com/wailsapp/wails/issues/1612#issuecomment-1190014992_

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- If you are using v1, use `wails issue` to report the issue
- If you are using v2, please include the output of `wails doctor`

**Comment by nap-yu** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/45232501/179982597-587930f0-ed67-4d83-a862-0fafd46ac0ee.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/45232501/179982693-8edc9da5-81d7-40c2-b1ca-76fc1ce3c940.png">
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/45232501/179983343-91b4ead5-bae8-41ee-9df2-139f57be7546.png">
![7月20日 (2)](https://user-images.githubusercontent.com/45232501/179984509-85f1d098-532e-4910-8051-5112d06b8e68.gif)
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/45232501/179984616-13e487fb-37c9-4630-99d6-778b7f3bda76.png">

**Comment by nap-yu** [comment]
![7月20日 (2)](https://user-images.githubusercontent.com/45232501/179984733-3b74e221-21ba-4b8d-970b-7fc20d6bff43.gif)

**Comment by leaanthony** [comment]
If you want to build using `go build` please follow the guide here: https://wails.io/docs/guides/manual-builds
