### ISSUE TITLE
Error building wails app, unexpected identifier in open module

### ISSUE THREAD

**Issue by Bigmambo** [wailsapp/wails#162]
**Description**

When building my first wails app without changing anything in the default app, it fails to build citing an unexpected identifier in the "open" node module. 

```
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/<USER>/go/src/planetchat/frontend/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! planetchat@ build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the planetchat@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<USER>/.npm/_logs/2019-07-18T12_52_09_037Z-debug.log

✗ Building frontend...
Error: exit status 1
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '~/go/src/YOUR_PROJECT_NAME'
2. Run this command: `wails build`

**Expected behaviour**
Default wails app is built.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.6 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment]
That's odd. I absolutely cannot reproduce this. Did you try removing your node_modules and doing it again? It looks like the error is in a 3rd party module.

**Comment by Bigmambo** [comment]
I've actually just fixed this, it was my node being way out of date even after I thought it had updated. I believe async wasn't supported back then. Thanks for the response.

**Comment by leaanthony** [comment]
Glad you got it fixed! We are going to add node and npm version to `wails issue` to try and catch things like this. Let us know if we can help you going forward 👍
