### ISSUE TITLE
Wails dev mode do not compile front-end command line options

### ISSUE THREAD

**Issue by BigCatGit** [wailsapp/wails#1623]
### Is your feature request related to a problem? Please describe.

Can wails add a function command option that the development mode does not automatically compile the front end? This can speed up the test speed of go. It takes a long time for the wails dev department to recompile the front end every time

### Describe the solution you'd like

demo:
wails dev --without-build-frontend

**Comment by allcapsc** [comment]
A quick fix to doing this while not using the CLI would be by removing the npm install and build options from your wails.json file. This should make Wails skip the install and build process.

For refrence to which lines in the wails.json file:
```go
"frontend:install": "npm install",
"frontend:build": "npm run build",
```

**Comment by BigCatGit** [comment]
It may be that I didn't express it clearly. I mean that if you can start and test the go code every time through the command line, you can run it without compiling the front end. This operation is more convenient in frequent go end tests. Of course, you can also use the unit test of go instead

**Comment by asppj** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/34705276/180184821-1df4b699-0c75-49ac-b021-c7b714e6ead3.png">

**Comment by BigCatGit** [comment]
Oh, thank you. I didn't see this option in wails --help

 ~/Desktop/test > wails --help
Wails CLI v2.0.0-beta.39.2

Available commands:

   build      Builds the application
   init       Initialise a new Wails project
   doctor     Diagnose your environment
   dev        Development mode
   generate   Code Generation Tools
   update     Update the Wails CLI
   version    The Wails CLI version

Flags:

  -help
    	Get help on the 'wails' command.

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by BigCatGit** [comment]
Yes, I mean adding wails dev -s support. PR I tried it and didn't know how to test it, just follow in https://github.com/wailsapp/wails/pull/1632

**Comment by leaanthony** [comment]
I linked the guide on how to test 👍
