### ISSUE TITLE
hope add move window function and Window transparency

### ISSUE THREAD

**Issue by BigCatGit** [wailsapp/wails#1624]
### Is your feature request related to a problem? Please describe.

hope add move window function, Users can customize the position of the window

### Describe the solution you'd like

demo:
&options.App{
    X: 50,
    Y; 50,
}
or:
context.MoveWIndow(x, y, width, height)

trans:
context.SetAlpha(0.5)

**Comment by leaanthony** [comment]
This should do: https://302f748e.wails-website.pages.dev/docs/reference/runtime/window#windowsetposition
Transparency is on the roadmap

**Comment by leaanthony** [comment]
Feel free to reopen this if there's more to be done 👍

**Comment by BigCatGit** [comment]
ok
