### ISSUE TITLE
Wails on frontend compile error: 0xaf5360 0xc00005b5b0

### ISSUE THREAD

**Issue by brys0** [wailsapp/wails#1629]
### Description

I wish I could provide more info than this, but this is all it manages to say before it crashed with the log:

Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.

Error: (0xaf5360,0xc00005b5b0)

### To Reproduce

I don't know how you could reproduce this.. I'm pretty sure it might be a corruption issue?

### Expected behaviour

The build normally does work. Then I get that, tried restarting, tried wails doctor. Everything reports as fine

### Attempted Fixes

Restarting
Wails Doctor
Removing all cache and reinstalling wails completely

### System Details

```shell
Wails CLI v2.0.0-beta.39.2

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 22621)
ID:             22H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.39.2

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.62
npm             N/A             Installed       8.5.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

### Additional context

The reason I believe it may be corruption is because I closed vscode when it was part way through the wails dev command. I believe because of this something may have corrupted (?)

**Comment by stffabi** [comment]
Thanks for reporting this issue.

Could you please attach the complete 'wails dev' console output when this occurs?
Does it also occur with 'wails build' or when running the application?

**Comment by stffabi** [comment]
Could you please use the increased verbose level when adding the log?

**Comment by brys0** [comment]
Hi, yes I did try that.. it seemed it broke when trying to compile the .syso file. I fixed it by deleting the entire directory reinstalling go and all dependencies. The verbose didn't provide anything useful..

**Comment by stffabi** [comment]
Thanks for getting back, glad you got it fixed.
Normaly the .syso file shouldn't be there, maybe we should delete it before building when it exists.
