### ISSUE TITLE
how to get wails.json after build?

### ISSUE THREAD

**Issue by askie** [wailsapp/wails#1647]
### Is your feature request related to a problem? Please describe.

I want to ge the wails.json info when app is running after build?
about app's version, app name,commpany....
Is this api exist?

### Describe the solution you'd like

git a api to provide the wais.js info

**Comment by leaanthony** [comment]
It's unlikely we'd add this information via the API but you can do this yourself quite easily by using Go's `embed` directive and using the native `json` package to decode it. 

Here's a good example on how to do it: http://www.inanzzz.com/index.php/post/1rwm/including-and-reading-static-files-with-embed-directive-at-compile-time-in-golang

Good luck 👍
