### ISSUE TITLE
[Windows] runtime.MessageDialog panics when called from "OnStartup" callback

### ISSUE THREAD

**Issue by emuell** [wailsapp/wails#1660]
### Description

When trying to show a message dialog in the wails app `OnStartup` callback on *Windows*, the app panics while showing the message. 

### To Reproduce

1. Create new wails project on Windows (vanilla, but actually any frontend style will do here)
2. Modify `App.startup` to open a message dialog: see example below
3. Build and run the app (debug or release or live dev mode doesn't matter)
4. The message shortly is visible, then the app panics in `runtime.MessageDialog` and is gone

Example OnStartup callback:
```
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
	messageOptions := runtime.MessageDialogOptions{
		Type:    "info",
		Title:   "Some Title",
		Message: "Some Message",
		Buttons: []string{"Okay"},
	}
	_, err := runtime.MessageDialog(a.ctx, messageOptions)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to show error message: %s\n", err.Error())
	}
}
``` 

Please Note: This  happens on *Windows only*. On macOS and Linux the message is showing up just fine.
Also showing the message in `OnDomReady` works fine on Windows, which I'm currently using as a workaround. 

The crash seems to happen in `func (f *Frontend) MessageDialog(options frontend.MessageDialogOptions) (string, error)` at `internal\frontend\desktop\windows\dialog.go`. 

Only `MessageDialog` seems affected. Save/Open File/Directory Dialogs are working fine.

### Expected behaviour

It should be possible to show a system message dialog on Windows in OnStartup.

### System Details

```shell
Wails CLI v2.0.0-beta.42

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.42

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.71
npm             N/A             Installed       6.14.15
*upx            N/A             Available
*nsis           N/A             Available
```

**Comment by leaanthony** [comment]
Thanks for reporting this. Can you pinpoint it to a particular argument? If you run `go build` with no tags, does a message dialog appear? Thanks!

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by emuell** [comment]
Thanks for the swift reply and fix! https://github.com/wailsapp/wails/pull/1662 works perfectly on my setup too.
