### ISSUE TITLE
The `frontend:dev` configuration is used to both install dev dependencies and build the frontend

### ISSUE THREAD

**Issue by LGiki** [wailsapp/wails#1663]
### Description

PR #1615 introduces the `GetDevInstallerCommand()` method to get the installation command of dev dependencies:
https://github.com/wailsapp/wails/blob/b9882eabe226c9f2cce0acbe910d3e7ebf705378/v2/internal/project/project.go#L87-L92
This method returns the `p.DevCommand` when the `p.DevCommand` is not empty, the corresponding configuration item of the `DevCommand` in wails.json is `frontend:dev`, in the [documentation](https://wails.io/docs/next/reference/project-config) this item is used to build assets in development mode, not for specify the dev mode dependencies installation command.

And in v2/pkg/commands/build/base.go, it use the same `DevCommand` to build frontend:
https://github.com/wailsapp/wails/blob/b9882eabe226c9f2cce0acbe910d3e7ebf705378/v2/pkg/commands/build/base.go#L535-L539

Perhaps we need to add a new configuration item in wails.json called 'frontend:dev:install' to specify the command to install the dev dependencies?

### To Reproduce

Nil

### Expected behaviour

Nil

### System Details

```shell
Nil
```

**Comment by leaanthony** [comment]
Thanks for opening this. You are, of course, 100% correct. Is this something you'd like to try to do?

**Comment by LGiki** [comment]
Yes, I am glad to create a PR to add a `frontend:dev:install` configuration in wails.json to specify the dev dependencies installation command and update the docs.
