### ISSUE TITLE
[V2] Mac: Inexplicable error log printing

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1664]
### Description

Sometimes, when I made http request (first request) on golang side, the log will print a error log:
```
ERR | [AssetServer] Error processing request '': Expected host '%!d(string=wails)' in request, but was '' (HttpResponse=500)
```

this log shows only once, what does it mean ?

### To Reproduce

1. run myApp
2. trigger the event of http request on golang side (this log shows only once).
3. can see the error log.
```
### before request
2022/07/27 16:47:51.740048 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'index.html'
2022/07/27 16:47:51.743070 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/index.0a4c8d96.js'
2022/07/27 16:47:51.746641 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/index.a00cf1be.css'
2022/07/27 16:47:52.078224 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.754e322b.css'
2022/07/27 16:47:52.079254 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.d8ef6ce3.js'
2022/07/27 16:47:52.080383 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/App.860583d8.js'
2022/07/27 16:47:52.081206 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/models.0780836a.js'
2022/07/27 16:47:52.109400 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.d8ef6ce3.js'
2022/07/27 16:47:52.111573 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/App.860583d8.js'
2022/07/27 16:47:52.112509 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/models.0780836a.js'

### after request
2022/07/27 16:47:52.917664 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/MainView.d7fb8862.css'
2022/07/27 16:47:52.918236 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/BucketList.31e3f620.css'
2022/07/27 16:47:52.918548 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/27 16:47:52.918935 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
2022/07/27 16:47:52.919262 [default_logger.go:100 ERR] [AssetServer] Error processing request '': Expected host '%!d(string=wails)' in request, but was '' (HttpResponse=500)

```

### Expected behaviour

no error log print

### System Details

```shell
not necessary
```

**Comment by stffabi** [comment]
Thanks for reporting this issue and using Wails.

Could you please give us a complete list of reproduction steps? E.g. provide us with a link to your application, and what you mean by `trigger the event of http request on golang side (this log shows only once).`

A minimal reproduction guide would be even better than linking to your application, e.g. a minimal `main.go` to reproduce the error.

> ERR | [AssetServer] Error processing request '': Expected host '%!d(string=wails)' in request, but was '' (HttpResponse=500)
> this log shows only once, what does it mean ?

This means a request was handled by our request processor with invalid information. As you can see the `uri` of the request was empty, which we don't know what to do with. This seems very weird as this would mean we get an empty uri request from WKWebView.

**Comment by cxt90730** [comment]
Thank you for your reply ~ 
MyApp `homepage` has a login button. After clicking it, it will send a http request to the LoginAPI on my server, and then jump to the next page if success (I use Vue3 + VueRouter). Even if the request is successful, and page jumped, the Error log also printed. 

In addition, it is very bad that sometimes the page does not jump after requesting LoginAPI, but according to log printing, the request and response are successful on golang side,  and login function which bind on frontend also into `then()`, 
 but there is no rendering of the frontend (or the Vue3router.push method is not executed?). What is worse is that it not appears every time... In the debug mode, right-click page and choose `Reload` to refresh the page can solve this problem

I don't know how to solve this problem now, I really need your help @stffabi

**Comment by leaanthony** [comment]
Sounds like you aren't setting the host in your request. If you can provide a small reproducible program showing the bug, then we can look at it.

**Comment by cxt90730** [comment]
@leaanthony emmm, I test myApp by using public cloud service... reproducible program may need a little time... I tried to captured http request by `wireshark`, no abnormal thing happened... request ok and response is StatusOK. I just received another error log, I even don't know when it happened...and why the URL is HttpHeader... -.-
```
2022/07/27 22:39:07.598880 [default_logger.go:100 ERR] [AssetServer] Error processing request '"Content-Length":"3518","Content-Type":"application/javascript"}': parse "\"Content-Length\":\"3518\",\"Content-Type\":\"application/javascript\"}": first path segment in URL cannot contain colon (HttpResponse=500)
```

**Comment by stffabi** [comment]
Oh I see what's going on... there's a pointer in usage for the `url` which comes from the native part and there's no guarantee that it will point to the correct data when the request is getting processed.

I'm working on a fix...

**Comment by stffabi** [comment]
@cxt90730 thanks again for reporting this. Could you please give PR #1668 a try, that would be awesome? I believe this should fix your issue.

Please see the [Bleeding Edge Guide](https://wails.io/docs/guides/bleeding-edge) for instruction how to use a PR.

**Comment by cxt90730** [comment]
@stffabi Great! The error log is no longer printing anymore. Thank you very much !
But the problem occurred occasionally of no rendering of frontend is still not solved...it seems not the problem of this log shows... (crying...) The current situation is that when this problem occurs, it can be confirmed that the code has executed to the `vuerouter.push("/nextpage")`, but page not jump. What a sad thing is that this problem is not every time appears.  I can understand that it is Vue-Router's problem? (Although I've update to the latest version of Vue-router)

**Comment by cxt90730** [comment]
Forgive me to say something more, the different thing when the problem occurs, `AssetHandler` does not load two picture assets in `nextpage`.  The following is a log comparison. I don’t know if it has reference value

```
### success log
2022/07/28 11:40:04.083438 [default_logger.go:85 INF] Login success.
2022/07/28 11:40:04.083506 [default_logger.go:71 TRA] json call result data: 
2022/07/28 11:40:04.089484 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/28 11:40:04.089905 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
2022/07/28 11:40:04.090262 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/28 11:40:04.091220 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
2022/07/28 11:40:04.112836 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/bear.c712c194.gif'
2022/07/28 11:40:04.113307 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/logo4.1426737f.png'
2022/07/28 11:40:04.249974 [default_logger.go:78 DEB] ListBuckets success.
```

```
### log when problem occurs
2022/07/28 11:43:38.431853 [default_logger.go:85 INF] Login success.
2022/07/28 11:43:38.431922 [default_logger.go:71 TRA] json call result data: {"result":"","error":"","callbackid":"app.App.Login-1245964161"}
2022/07/28 11:43:38.437693 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/28 11:43:38.438093 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
2022/07/28 11:43:38.438426 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/28 11:43:38.439520 [default_logger.go:78 DEB] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
```

`bear.c712c194.gif` and `logo4.1426737f.png` not be loaded, and page does not jump to nextpage

**Comment by stffabi** [comment]
Thanks for letting us know the PR fixes the wrong request uri. I think the next step would be that you take a deeper look into the "dev tools". E.g. investigate if you see any more requests being executed on the "network tab" or if requests or blocked there, or if something in the JavaScript files is wrong.

I'm sorry but without a small reproducible app, there's not much we can do helping you apart from guiding you with hints where you could look next.

**Comment by cxt90730** [comment]
OK, I will do my best to reproduce it later, or maybe modify source code and print something to debug first ... thanks a lot ~ @stffabi

**Comment by stffabi** [comment]
@cxt90730 please let us know if you find anything or if you need any further assistance with the Wails source code. 👍
