### ISSUE TITLE
New lines added to author field in package.json

### ISSUE THREAD

**Issue by pedzed** [wailsapp/wails#167]
**Description**

After receiving the following error:
```
npm ERR! JSON.parse Failed to parse package.json data.
```
I opened the package.json file and saw this:

![image](https://user-images.githubusercontent.com/8146593/61776041-75206f80-adfa-11e9-96f3-095bdc18cc29.png)

The author field should be one line of course.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Additional Details**

The author data was provided during `wails init` using Git Bash.

**Comment by leaanthony** [comment]
I'm guessing they're picked up from the original wails init command and windows line feeds. If you edit `.wails/wails.json` in your home directory then that should fix it

**Comment by pedzed** [comment]
I can confirm that this is a Git Bash issue. `wails setup` works fine using `cmd.exe`.

**Comment by leaanthony** [comment]
Thanks for this update. Windows testing has all been done on `cmd.exe` so that might fix your other issue with the returns. Whilst we try to support as many setups as possible, we don't always have the bandwidth. The most likely scenario in the future is support for [Microsoft's new terminal](https://github.com/microsoft/terminal). Is there a general feeling in the Windows world that this will likely be the de-facto terminal?

**Comment by pedzed** [comment]
> The most likely scenario in the future is support for Microsoft's new terminal. Is there a general feeling in the Windows world that this will likely be the de-facto terminal?

Never heard about that. I only know about cmd and PowerShell.

Cmd is a terrible terminal (or "command prompt") and I don't bother to learn PowerShell because I often switch from macOS to Linux and Windows. They all have bash in common (if Git Bash is installed), so that's what I always use (or zsh, but it is quite similar to bash).

**Comment by leaanthony** [comment]
That's understandable. I had a look at using survey instead of stdlib for input and that fails on git bash too. Do your other go based cli tools work ok in it?

**Comment by pedzed** [comment]
I usually do not mind how the CLI tool is written, as long as it works. So no, unfortunately I do not know any Go-based CLI tool.

An easy fix for this issue would be to remove any `\r` and `\n` during the concatenation process (`name + "<" + email + ">"`).

**Comment by leaanthony** [comment]
Thanks for your feedback @pedzed. I think I have a fairly trivial fix pushed to the latest pre-release for you. Please update using `wails update -pre` and test again. This should also fix your git bash support.

Let us know! 👍

**Comment by pedzed** [comment]
Excellent!

```bash
$ cat ~/.wails/wails.json
{"email":"email@example.com","name":"Ped"}
```
I didn't have to modify anything either (except in already `wails init`-ed projects).

New lines also work (#166):
```bash
$ wails setup
 _       __      _ __
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v0.17.9-pre
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

What is your name (Ped):
What is your email address (email@example.com):
```

Only a minor thing in regards to the generated `frontend/package.json` after running `wails init`, there should be a space after the name and before the left angle bracket.
```bash
$ cat frontend/package.json
{
  "name": "x",
  "author": "Ped<email@example.com>",
```
