### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by wlwatkins** [wailsapp/wails#1678]
### Is your feature request related to a problem? Please describe.

Is it possible to get better error messages with traceback so we know which line of code is posing a problem

![image](https://user-images.githubusercontent.com/8661949/181793691-22396c49-e5f2-4969-a89d-4ad26224c4f6.png)

### Describe the solution you'd like

Show the file and line number that is posing an issue. In big projects this is impossible to deal with. 

Maybe it is something I am doing wrong, but I cannot find any documentation showing how to make the messages more readable

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by willmendil** [comment]
Would it be possible to change the Logger interface so that wails is directly compatible with logrus?
Indeed, currently I get 
```
var Log *logrus.Logger
cannot use Log (variable of type *logrus.Logger) as "github.com/wailsapp/wails/v2/pkg/logger".Logger value in struct literal: *logrus.Logger does not implement "github.com/wailsapp/wails/v2/pkg/logger".Logger (wrong type for method Debug)
		have Debug(args ...interface{})
		want Debug(message string)
```

I'm not sure how to fix this apart from changing the Logger interface mentioned here https://wails.io/docs/reference/runtime/log#using-a-custom-logger

**Comment by leaanthony** [comment]
Hi. We're probably not going to make an API change for this as it would break all projects that use it. It's trivial to write a wrapper for logrus. I actually thought that project was dead 😜
