### ISSUE TITLE
Improve `wails issue`

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#169]
Also include:

- GCC version
- npm version
- node version

**Comment by leaanthony** [comment]
TODO: Windows GCC version

**Comment by pedzed** [comment]
What about Windows 10 version info?

![image](https://user-images.githubusercontent.com/8146593/62166894-33278a00-b322-11e9-9f92-e63a6af50706.png)

**Comment by leaanthony** [comment]
Is there an easy way to get that from Go?

**Comment by bh90210** [comment]
#178

**Comment by leaanthony** [comment]
Closing this. Windows support already added.
