### ISSUE TITLE
No hot reload with react?

### ISSUE THREAD

**Issue by dzpt** [wailsapp/wails#1697]
### Description

I suppose it would reload after changing file in react frontend, but it doesn't
I use [react template](https://github.com/AlienRecall/wails-react-template)

### To Reproduce

1. install [react template](https://github.com/AlienRecall/wails-react-template)
2. compile and run
3. change and press reload
4. nothing changes

### Expected behaviour

It supposed to upate the view

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18.4
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.42

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available
*nsis 				N/A		Available
```

**Comment by stffabi** [comment]
Thanks for opening this issue und using Wails.

The template you are referring to is a community template and is not maintained by the Wails core team. They also list this as a [known issue](https://github.com/AlienRecall/wails-react-template#known-issues) in their readme.

I would recommend you to use one of the official "React + Vite" or "React + Vite (typescript)" templates, which support frontend hot reloading. You can create a new Wails project from those templates by running `wails init -t react -n myproject` or `wails init -t react-ts -n myproject`.

**Comment by dzpt** [comment]
@stffabi thank you, it works now.
