### ISSUE TITLE
Support for initializing a "minimal" application

### ISSUE THREAD

**Issue by tataDan** [wailsapp/wails#1698]
### Is your feature request related to a problem? Please describe.

The `wails init` command generates user interface components that are not always needed and which, therefore, need to be removed when creating a new application.  By "user interface components" I mean the input, button,  "result" div, and logo.

### Describe the solution you'd like

It might desirable to have flags added that would determine the absence or presence of that code.  The flags could be something like `-m` or `-minimal`.  In other words, if one of these flags were used with the `wails init` command, then only a empty window would appear (initially) when the application is run.  Then the developer could add code without the necessity of removing unused code.

### Describe alternatives you've considered

Suppose one is developing a svelte application.  It is possible to remove the Greet function from `app.go` and remove the lines within the script, main, and style sections of `frontend/src/App.svelte`.  The frontend/src/assets/images/logo-universal.png file is also something that might not always be used in an application.

### Additional context

Apparently, the code referred to above might be in the `wails/v2/cmd/wails/internal/commands/initialise/templates/templates/svelte/app.tmpl.go` file and the `wails/v2/cmd/wails/internal/commands/initialise/templates/templates/svelte/frontend/src/App.svelte` file.

To be fair, it should be acknowledged that if this proposal were to be implemented, it should be implemented for all the templates not only svelte and  this could be a time-consuming task.

**Comment by leaanthony** [comment]
Hey Dan 👋 I understand the motivation for this, but it's unlikely to happen any time soon. As an alternative, you are free to use the template builder and host empty versions yourself on github: https://wails.io/docs/guides/templates
