### ISSUE TITLE
`wails dev` panics due to application immediately shutting down

### ISSUE THREAD

**Issue by maxkunes** [wailsapp/wails#1708]
### Description

I'm using wails on an externally built project. In any case, a separate command line builds the files (esbuild and tailwinds watch are used), and they are dumped in `frontend/src`. 

From what I can tell, the application seems to invoke shutdown instantly and then crashes down the callstack (maybe because of the empty `frontend:x` fields in the config?).

This is the result of running `wails dev`:

```
C:\Users\admin\Documents\GitHub\hitta\hittawails>wails dev
Wails CLI v2.0.0-beta.42

Executing: go mod tidy -compat=1.17
Executing: wails generate module
Building application for development...
  - No Install command. Skipping.
  - No Build command. Skipping.
  - Generating bundle assets: Done.
  - Compiling application: Done.

Watching (sub)/directory: C:\Users\admin\Documents\GitHub\hitta\hittawails
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: auto
Using reload debounce setting of 100 milliseconds
INF | Serving assets from frontend DevServer URL: auto
DEB | WebView2 Runtime Version '103.0.1264.77' installed. Minimum version required: 94.0.992.31.
Added new directory to watcher: C:\Users\admin\Documents\GitHub\hitta\hittawails\frontend\wailsjs\go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6bede6]

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Quit(0xc000125f08)
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.42/internal/frontend/desktop/windows/frontend.go:375 +0x46
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Quit(0x8bb0b0)
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.42/internal/frontend/devserver/devserver.go:152 +0x22
github.com/wailsapp/wails/v2/internal/appng.(*App).Shutdown(0xc00019e990)
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.42/internal/appng/app_dev.go:51 +0x44
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc000074460)
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.42/internal/appng/app_dev.go:56 +0x45
github.com/wailsapp/wails/v2.Run(0xc0001be100)
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.42/wails.go:40 +0xf4
main.main()
        C:/Users/admin/Documents/GitHub/hitta/hittawails/main.go:19 +0x1fb
```

### To Reproduce

My wails config is as follows. I have empty strings for install, build and run as these are handled externally:

```
{
  "name": "hitta",
  "outputfilename": "hittawails",
  "frontend:install": "",
  "frontend:build": "",
  "frontend:dev:watcher": "",
  "frontend:dev:serverUrl": "auto",
  "author": {
    "name": "Max Kunes",
    "email": "myemail"
  }
}
```

The only modification I have made to the actual generated go project is embedding frontend/src instead of frontend:

```
//go:embed frontend/src
var assets embed.FS
```

### Expected behaviour

I expect that wails should correctly display my `index.html` without the use of `frontend:X` commands.

### Screenshots

Frontend Directory:
![explorer_5saEB7mNpJ](https://user-images.githubusercontent.com/11730836/183277570-d4b04c16-3687-4865-a5f1-5e7f7c1dea46.png)

Frontend/src Directory:

![image](https://user-images.githubusercontent.com/11730836/183277573-a25f58d4-489e-4e03-bfa3-5a788a6abd5d.png)

### System Details

```shell
PS C:\Users\admin\Documents\GitHub\hitta\hittawails\frontend\src> wails doctor
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.42

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.77
npm             N/A             Installed       8.1.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

PS C:\Users\admin\Documents\GitHub\hitta\hittawails\frontend\src>
```
```


### Additional context

_No response_

**Comment by maxkunes** [comment]
Interestingly enough, debugging the go project directly works fine. Its just running through `wails dev`. Presumably this points further toward a configuration issue.

**Comment by maxkunes** [comment]
Somewhat offtopic: `wails doctor` incorrectly lists my OS as Windows 10. I'm on Windows 11.

**Comment by stffabi** [comment]
Thanks for reporting this issue and using Wails.

Could you please try to either remove the `"frontend:dev:serverUrl": "auto",` or set it to `""`? `auto` there only makes sense if Vite as dev:watcher is used. I'm working on a fix for this 

> Somewhat offtopic: wails doctor incorrectly lists my OS as Windows 10. I'm on Windows 11.

Unfortunately that's what Microsoft internally uses for Windows 11, for MS it's just another build of Windows 10 😄 .

**Comment by stffabi** [comment]
The panic has already been fixed on master, `wails dev` would then gracefully error that the `frontend:dev:serverUrl` is wrong:

> Error: Invalid frontend:dev:serverUrl missing protocol scheme?

**Comment by stffabi** [comment]
But we should give clear error like `auto for serverUrl can't be used without a dev:watcher`. I'll provide a PR for this.

**Comment by leaanthony** [comment]
Regarding the Windows 10 string ID in the registry, I was thinking of overriding this based on the build number, but I'm not sure it's worth the effort

**Comment by maxkunes** [comment]
Confirmed that both an empty string for "frontend:dev:serverUrl" and removing the line entirely fixes the issue. So that solves that issue on the current release (not master). I'm unable to test a pre-release branch though.

Thanks as always for the detailed and quick response!

You guys can close whenever.

**Comment by stffabi** [comment]
@maxkunes thanks for reporting back 🙏 .

The PR to improve this is up and gives now  a clear message when `auto` discovery is used without a dev watcher.
