### ISSUE TITLE
Add Japanese translation to v2 document with crowdin

### ISSUE THREAD

**Issue by RyoTagami** [wailsapp/wails#1709]
### Describe the solution you'd like

I would like to contribute to the translation of v2 documents in Japanese.

**Comment by leaanthony** [comment]
@misitebao

**Comment by leaanthony** [comment]
Thanks for your offer! @misitebao is currently wrangling with Crowdin so he's the best person to ask right now

**Comment by misitebao** [comment]
@RyoTagami 
Thanks for contributing to the documentation.
You can do your translation work on [crowdin](https://crowdin.com/project/wails).

**Comment by leaanthony** [comment]
@RyoTagami Thank you for your offer of translating the website to Japanese. I've sent you an invite to Crowdin 👍

**Comment by RyoTagami** [comment]
Invitation confirmed!
