### ISSUE TITLE
Init fails to detect Arch Linux

### ISSUE THREAD

**Issue by Chronophylos** [wailsapp/wails#171]
**Description**
When I run `wails init` it fails to detect Arch Linux as my distro

**To Reproduce**
1. Run `wails init`
2. Enter `yes`
3. A new issue opens in the browser showing missing values

**Expected behaviour**
The values should not be blank. 
Also I expected Arch Linux to be supported since the [Quick Start](https://wails.app/quick_start.html#prerequisites) referenced Arch Linux.

**Screenshots**
![](https://i.imgur.com/PS42USP.png)

**System Details**
The table from the opened issue

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   |  |
| Distribution Version   |  |
| Discovered by   | lsb |

Pastes:
[`go env`](https://pastebin.com/raw/Q3XAksdP)
[`cat /etc/*-release`](https://pastebin.com/raw/wGA42nX3)
[`lsb_release -a`](http://ix.io/1PI0)

**Comment by bh90210** [comment]
hey @Chronophylos 
I just test-built on arch linux and can not reproduce your bug
```sh
[root@wails-bug-archlinux-test ~]# wails init
Wails v0.17.0 - Initialising project

The name of the project (My Project): test
Project Name: test
The output binary name (test): 
Output binary Name: test
Project directory name (test): 
Project Directory: test
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
✓ Generating project...
✓ Building project (this may take a while)...
Project 'test' built in directory 'test'!
```
also what's weird is that in the error report `Distribution ID` and `Distribution Version` are also missing.

can you please run `cat /etc/*-release` and/or `hostnamectl` and share the output?
for example here is mine

for `cat /etc/*-release` 
```sh
[root@wails-bug-archlinux-test ~]# cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
and `hostnamectl`
```sh
[root@wails-bug-archlinux-test ~]# hostnamectl
   Static hostname: n/a
Transient hostname: wails-bug-archlinux-test
         Icon name: computer-container
           Chassis: container
        Machine ID: 01320fee23eb45789c0aa47ca12cf7b0
           Boot ID: 46ce5b0f098f451bba3be383e46c04e5
    Virtualization: lxc
  Operating System: Arch Linux
            Kernel: Linux 4.18.0-25-generic
      Architecture: x86-64
```

**Comment by bh90210** [comment]
while we are looking in to it can you please give a try to `wails update -pre` and see if this by any chance fix the issue?

**Comment by Chronophylos** [comment]
Nope 0.17.6-pre didn't fix it
![](https://i.imgur.com/SIPKCY9.png)

**Comment by Chronophylos** [comment]
I noticed you always call `CheckDependenciesSilent` maybe you could add a flag so `CheckDependencies` gets called instead?

**Comment by Chronophylos** [comment]
I know whats causing the bug:
For some reason my `lsb_release` prints `-e` infront of everything. This means the switch case [here](https://github.com/wailsapp/wails/blob/master/cmd/linux.go#L59) doesn't do anything.

**Comment by bh90210** [comment]
did you find a solution for the `-e`? or what is causing it?

yes probably it would be a good idea switching to a `/etc/*-release` solution  or `hostnamectl`.
maybe open an issue about it? also pull requests are welcome :+1: :smile: 

I am not sure why we went there in the first place, maybe @leaanthony could weight in on this one?

**Comment by Chronophylos** [comment]
I think it's a bug in `lsb_release`:
`lsb_release` uses `sh` but ![in POSIX sh, echo flags are undefined](https://i.imgur.com/iNO7lEe.png)
Using `bash` fixes this
![](https://i.imgur.com/dPgdTu0.png)

**Comment by leaanthony** [comment]
Thanks for opening this issue @Chronophylos. Is /etc/os-release standard over every distribution? If so, I'm happy to move to that.

**Comment by leaanthony** [comment]
@Chronophylos - Please update to the latest pre-release (v0.17.7-pre) using: `wails update -pre`. Let us know if that fixes Arch support 👍

**Comment by Chronophylos** [comment]
it works
