### ISSUE TITLE
Shouldn't we register exported field during binding ?

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#1721]
### Description

I encounter a problem while generating the binding for response object with nested structure.

```go
type As struct {
  B Bs `json:"b"`
}

type Bs struct {
  Name string `json:"name"`
}
```

It appears the struct `Bs` is not added to the struct to generate for typescript, as we end up with an `any` type in the TS models.

I think the problem comes from these lines:
- https://github.com/wailsapp/wails/blob/4385fea49b571b53b03c9cf57983f2113af383bd/v2/internal/binding/binding.go#L159-L161
- https://github.com/wailsapp/wails/blob/4385fea49b571b53b03c9cf57983f2113af383bd/v2/internal/binding/binding.go#L171-L173

In this case, validating the condition `field.PkgPath == ""` means we found an exported field. So, we are skipping the exported fields, which, I think, is not what we want.

We could use `!field.IsExported()` instead. That would be less cryptic. It has been added recently, AFAIR.

### To Reproduce

Not sure if this is accurate, but _I think_ the example above could reproduce the bug.

```go
type As struct {
  B Bs `json:"b"`
}

type Bs struct {
  Name string `json:"name"`
}
```

### Expected behaviour

The binding process should register nested struct in the TS models, not an `any`.

### Screenshots

![Screenshot 2022-08-09 at 22 51 03](https://user-images.githubusercontent.com/4662842/183764004-0f770ba6-9af3-4c9a-abbb-d44c0f8dc56c.png)

### Attempted Fixes

The following change worked for me. But I don't have the full picture so, it might not be the complete solution.

```diff
- if field.PkgPath == "" {
+ if field.PkgPath != "" {
    continue
}
```

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.5
ID:		199506
Go Version:	go1.18.4
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.42

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.1.2
*upx 				N/A		Available	
*nsis 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```
```


### Additional context

_No response_

**Comment by leaanthony** [comment]
Thanks for raising this detailed insight into the issue. We should build some tests around this for sure as it's really hard to get right all the time. I'm going to get some basic tests working around this, especially the `WriteModels` method. Leave it with me a couple of days to work out how best to do that 👍

**Comment by leaanthony** [comment]
Ok, I've had a quick look and created a simple example for testing TS generation. This is on the `feature/ts-generation-tests` branch: https://github.com/wailsapp/wails/tree/feature/ts-generation-tests

The example test is here: https://github.com/wailsapp/wails/blob/feature/ts-generation-tests/v2/internal/binding/binding_singlefield_test.go

The main test runner uses it here: https://github.com/wailsapp/wails/blob/feature/ts-generation-tests/v2/internal/binding/binding_test.go

This should, at the very least, allow us to reproduce bugs with the smallest examples possible. It will also allow us to debug easily and find out what the issue is. Please let me know how you get on 👍 

I'll also start adding more tests here over time

**Comment by ValentinTrinque** [comment]
I am about to push a PR with a test that highlight the problem, would you mind to look at it ?

**Comment by ValentinTrinque** [comment]
Also my PR contains the fix.
