### ISSUE TITLE
[V2] Windows: cannot use nsis installer when build app

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#1724]
### Description

$ wails build -nsis
Wails CLI v2.0.0-beta.43

App Type:               desktop
Platforms:              windows/amd64
Compiler:               C:\Program Files\Go\bin\go.exe
Build Mode:             Production
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []
Race Detector:          false

Building target: windows/amd64
------------------------------
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.
Built 'C:\Users\cuixiaotian\xBrowser\build\bin\xBrowser.exe' in 16.51s.

ERROR: cannot build nsis installer - no windows targets

### To Reproduce

wails init -n myapp -t vue
cd myapp
wails build -nsis

### Expected behaviour

no error

### System Details

```shell
$ wails doctor
Wails CLI v2.0.0-beta.43

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.18.4
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.43

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       104.0.1293.47
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by Villyli** [comment]
fixed in PR https://github.com/wailsapp/wails/pull/1715, see more at https://github.com/wailsapp/wails/issues/1714

**Comment by stffabi** [comment]
Thanks for reporting this and using Wails.

As @Villyli mentioned this has already been fixed on master.
