### ISSUE TITLE
macOS: FATAL: too many open files

### ISSUE THREAD

**Issue by iansinnott** [wailsapp/wails#1733]
### Description

The build system fails with an error about too many files. The frontend build and wails runtime will continue and you will have to close them manually.

**Solution:** Find out where you have a ton of files and remove them.

This seems to be an issue with the file watcher erroring out when there are many files within the watch path. In my case the path was `frontend/tmp`, which was gitignored but being watched by the wails fs watcher.

### To Reproduce

Put a bunch of files in your frontend directory.

### Expected behaviour

Ideally:

- everything fails at once (i.e. vite process does not continue in the background)
- the error message is more descriptive

Might also be useful to support ignore patterns for the file watcher.

### System Details

```shell
System
------
OS:		MacOS
Version: 	12.5
ID:		21G72
Go Version:	go1.18
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.43

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.5.0
*upx 				N/A		Available
*nsis 				N/A		Available
```

**Comment by iansinnott** [comment]
I only opened this to have a record for anyone else who, like myself, was temporarily mystified by the `too many files` error.

**Comment by leaanthony** [comment]
This might be project specific and related to fsnotify. Investigating 👍

**Comment by leaanthony** [comment]
Many projects have this issue due to the fact that fsnotify uses a file handle per file. The solution is to use FSEvents on Mac. Need time to do it

**Comment by iansinnott** [comment]
Maybe if the watcher would automatically ignore everything in `.gitignore` it would solve 90% of cases? This would have solved my own issue above.

Or perhaps an `-ignore` option for `wails dev`? the `-reloaddirs` flag seems only only allow watching more files. 

A mac-specific solution like `FSEvents` would be great but I suspect would be more involved.

**Comment by leaanthony** [comment]
. Directories should be ignored. If not we should add it. The default open file handle limit on Mac is 256 😬

**Comment by leaanthony** [comment]
Re-opening this. I want it fixed properly without workarounds.

**Comment by leaanthony** [comment]
@iansinnott - [this PR](https://github.com/wailsapp/wails/pull/1827) adds support for reading the default `.gitignore` files and adds them to the paths to be ignored by the watcher. Please let me know how you get on 👍

**Comment by iansinnott** [comment]
Cheers! Thank you for working on this issue and thanks for the ongoing work on Wails

**Comment by leaanthony** [comment]
@Blatman - does [this PR](https://github.com/wailsapp/wails/pull/1827) fix your original problem?

**Comment by Blatman** [comment]
Can't say as I haven't encountered it with WAILS yet (only with nw-builder way back) but it looks a good enhancement to avoid a fatal in WAILS.

**Comment by leaanthony** [comment]
@iansinnott - just wondering if you had any feedback on this. Thank you 🙏

**Comment by leaanthony** [comment]
Please feel free to reopen this if it's still an issue 👍
