### ISSUE TITLE
4th and 5th mouse buttons trigger events with improper button and buttons properties

### ISSUE THREAD

**Issue by kettek** [wailsapp/wails#1737]
### Description

Mouse events can be triggered by the 4th and 5th buttons, but both the `button` and `buttons` properties are 0.

### To Reproduce

1. Add a mousedown/mouseup handler
2. Click with mouse button 4 or 5
3. Receive a mouse event with both the `button` and `buttons` properties set to 0.

### Expected behaviour

`buttons` should be 8 if mouse button 4 or 16 if mouse button 5.
`button` should be 3 if mouse button 4 or 4 if mouse button 5.

### System Details

```shell
Wails CLI v2.0.0-beta.43

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.19
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.43
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Installed       1:20.10.17-1
gcc             gcc             Installed       12.1.1-4
libgtk-3        gtk3            Installed       1:3.24.34-1
libwebkit       webkit2gtk      Installed       2.36.6-1
npm             npm             Installed       8.16.0-1
pkg-config      pkgconf         Installed       1.8.0-1
```

**Comment by leaanthony** [comment]
Thanks for reporting this. Wails doesn't manipulate mouse events so this is almost certainly what WebkitGTK is reporting. Can you do the same test using this link please? https://bug-201445-attachments.webkit.org/attachment.cgi?id=377952

**Comment by kettek** [comment]
It is unfortunately the same, so this is indeed not a wails problem.

**Comment by leaanthony** [comment]
Thanks for letting us know. Do you think updating the bug template to include a link to the webkitGTK bug tracker would have helped you in this instance? I'm also wondering if there's a workaround we could do by capturing the events at the GTK level to "verify" the javascript events, or even just forward mouse events to the frontend for certain events?

**Comment by kettek** [comment]
In my case, I don't think it would've, as it didn't occur to me that it would be tied to a webkitGTK problem. Perhaps there could be some information that it could be related to the backend being used? That might add clutter, however.

Since it is a limit to webkitGTK, it would be nice to be able to use additional mouse buttons, however that would probably open up a can of worms for API design and expectations in regards to mouse events. If there is a way to capture mouse events in GTK, modify the events that are produced on JavaScript's side to have the proper button and buttons properties set, then that would be ideal. However, I am only mildly familiar with writing GTK and not at all familiar with webkit, so I do not know if that would be feasible.

**Comment by leaanthony** [comment]
Thanks for the feedback. As there's not much we can do about this, I'm going to close it for now 👍
