### ISSUE TITLE
`wails init` does not work on centos 7

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#174]
**Description**
while it is supported, when trying to init a new wails project on centos I get this error
```sh
Wails v0.17.6-pre - Initialising project

Error: Library 'webkit2gtk3-devel' not found. Please install with `sudo yum install webkit2gtk3-devel` and try again
```
in Centos there is no such package `webkit2gtk3-devel`
```
[root@wails-centos-test ~]# yum install webkit2gtk3-devel
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.ntua.gr
 * extras: ftp.ntua.gr
 * updates: ftp.ntua.gr
No package webkit2gtk3-devel available.
Error: Nothing to do
```

**To Reproduce**
Steps to reproduce the behaviour:
1. install wails on Centos
2. run `wails init`
3. see the error

**Expected behaviour**
create a new project

**System Details**
Centos 7

**Additional context**
managed to get wails working by installing `webkitgtk3-devel` instead of the proposed prerequisite `webkit2gtk3-devel`  
```sh
[root@wails-centos-test ~]# wails init
Wails v0.17.6-pre - Initialising project

The name of the project (My Project): test
Project Name: test
The output binary name (test): 
Output binary Name: test
Project directory name (test): 
Project Directory: test
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
✓ Generating project...
✓ Building project (this may take a while)...
Project 'test' built in directory 'test'!
```

**Comment by bh90210** [comment]
I am on it, but while I work the PR for centos, should I check the rest of supported distros as well just to 100% sure?

**Comment by leaanthony** [comment]
Looks like we finally have to use the version number from distro detection.

**Comment by bh90210** [comment]
fedora is broken too, and safe to assume redhat as well?
```
[root@wails-fedora-test ~]# yum install webkit2gtk-devel gtk3-devel
Last metadata expiration check: 0:12:29 ago on Mon Jul 29 13:55:58 2019.
No match for argument: webkit2gtk-devel
Error: Unable to find a match
```
did we decide if we will go with `webkitgtk3-devel` or `webkitgtk4-devel` for centos?
fedora needs yet a different package apparently :-p I am trying to find it..

**Comment by bh90210** [comment]
I'm closing the ticket. if needed let's continue the conversation to #175 :+1: :+1:
