### ISSUE TITLE
run wails dev, DevWatcher command exited!

### ISSUE THREAD

**Issue by HumorMrChen** [wailsapp/wails#1752]
### Description

PS \desktop\desktop> wails dev
Wails CLI v2.0.0-beta.43

Executing: go mod tidy -compat=1.17
Executing: D:\workSpace\GoWorkspace\bin\wails.exe generate module
Building frontend for development...
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  - Generating bundle assets: Done.
  - Compiling application: npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> frontend@1.0.0 dev
> vite

  vite v2.9.14 dev server running at:

Vite Server URL: http://localhost:3000/
  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 2175ms.

Done.

INF | Serving assets from frontend DevServer URL: http://localhost:3000
DEB | WebView2 Runtime Version '104.0.1293.54' installed. Minimum version required: 94.0.992.31.
Error: (0x1e3ba60,0xc0003ca8d0)
Watching (sub)/directory: D:\workSpace\GoWorkspace\src\zj-wasc-volunteerComputing\desktop\desktop
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:3000
Using reload debounce setting of 100 milliseconds
Development mode exited
Killing DevWatcher command...
成功: 已终止 PID 14940 (属于 PID 1876 子进程)的进程。
成功: 已终止 PID 1876 (属于 PID 4280 子进程)的进程。
成功: 已终止 PID 4280 (属于 PID 18200 子进程)的进程。
成功: 已终止 PID 18200 (属于 PID 3896 子进程)的进程。
成功: 已终止 PID 3896 (属于 PID 18044 子进程)的进程。
DevWatcher command exited!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### To Reproduce

1. run  wails dev

### Expected behaviour

.

### System Details

```shell
win10
```

**Comment by stffabi** [comment]
Thanks for reporting this and using Wails.

According to `Error: (0x1e3ba60,0xc0003ca8d0)` it seems like your application is directly shutting down with an error. If your main.go files contains something like the following

```go
if err != nil {
	println("Error:", err)
}
```

Please change it into the following to get a better error with a description.

```go
if err != nil {
	println("Error:", err.Error())
}
```

The error message should give us more information what the problem is. Thanks 🙏

**Comment by HumorMrChen** [comment]
Thanks for your answer!

I modified the code and reported this error,

`
Done.

INF | Serving assets from frontend DevServer URL: http://localhost:3000
DEB | WebView2 Runtime Version '104.0.1293.54' installed. Minimum version required: 94.0.992.31.
Error: CreateFile E:\desktop\desktop\frontend\wailsjs\go\main: Access is denied.
Watching (sub)/directory: E:\GoWorkspace\src\zj-wasc-volunteerComputing\desktop\desktop
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:3000
Using reload debounce setting of 100 milliseconds
Development mode exited
Killing DevWatcher command...
成功: 已终止 PID 14332 (属于 PID 17080 子进程)的进程。
成功: 已终止 PID 17080 (属于 PID 2236 子进程)的进程。
成功: 已终止 PID 2236 (属于 PID 11392 子进程)的进程。
成功: 已终止 PID 11392 (属于 PID 12832 子进程)的进程。
成功: 已终止 PID 12832 (属于 PID 2768 子进程)的进程。
DevWatcher command exited!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony`

**Comment by stffabi** [comment]
It tries to create the bindings in a wrong directory

> Error: CreateFile E:\desktop\desktop\frontend\wailsjs\go\main: Access is denied.

Do you have anything special for wailsjsdir in wails.json?

**Comment by leaanthony** [comment]
Perhaps we could check write permissions before trying to write then give a better error message. I'll convert this to a ticket.

**Comment by Maicarons2022** [comment]
I got the same errors
```bash
D:\Gitlab\mccl>wails dev
Wails CLI v2.0.0-beta.42 

Executing: go mod tidy -compat=1.17
Executing: wails generate module 
Installing frontend dependencies... 

> mccl@0.0.0 dev
> vite
 

  vite v2.9.15 dev server running at:
 
Vite Server URL: http://localhost:3000/ 
  > Local: http://localhost:3000/ 
  > Network: use `--host` to expose

  ready in 2370ms.

Running frontend DevWatcher command: 'npm run dev' 
Building application for development...
  - Installing frontend dependencies: Done. 
  - Compiling frontend: Done. 
  - Generating bundle assets: Done. 
  - Compiling application:
Build error - open D:\Gitlab\mccl\frontend\wailsjs\runtime\package.json: Access is denied.
No version running, build will be retriggered as soon as changes have been detected
Watching (sub)/directory: D:\Gitlab\mccl 
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:3000/
Using reload debounce setting of 100 milliseconds
 
 
To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
[Rebuild triggered] files updated 
  - Generating bundle assets: Done. 
  - Compiling application: Done. 

Added new directory to watcher: D:\Gitlab\mccl\frontend\wailsjs\runtime 
INF | Serving assets from frontend DevServer URL: http://localhost:3000/ 
DEB | WebView2 Runtime Version '104.0.1293.47' installed. Minimum version required: 94.0.992.31.
Error: mkdir D:\Gitlab\mccl\frontend\wailsjs\go\main: Access is denied. 
Development mode exited 
DevWatcher command exited!
DevWatcher command killed!


```

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by lytdev** [comment]
> Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

 i try test this ,but it doesn`t work #https://github.com/wailsapp/wails/issues/2171#issue-1472060982

**Comment by taylorlanglopez** [comment]
This is still broken. The runtime folder will always delete itself if you want to inject the runtime into a component for example.

Vue Component (Works but breaks wails dev)
```
<script setup lang="ts">
import * as wailsrt from '../../wailsjs/runtime/runtime'
....
wailsrt.EventsOn("progress", (proginc: string) => {
 //code to update a progress bar
}
...
</script>
```

Vue Component (Doesn't work and throws a compiler error on type-check)
```
<script setup lang="ts">
....
window.runtime.EventsOn("progress", (proginc: string) => {
 //code to update a progress bar
}
...
</script>
```

The second example is "correct" according to the documentation, but it just throws a compiler error.

/src/components/File.vue(48,8): error TS2339: Property 'runtime' does not exist on type 'Window & typeof globalThis'

I'm really lost as to how I get access to the runtime inside a component without breaking wails dev. 

My structure is 
src/components
src/views
App.vue
main.ts

I have not modified main.ts (main.js) at all, I added a router to App.vue and il8n.

My App.vue has a <router-view /> from the standard Vue router in order to host the View for each component.
