### ISSUE TITLE
cannot build nsis installer - no windows targets

### ISSUE THREAD

**Issue by Purple-CSGO** [wailsapp/wails#1753]
### Description

I'm unable to build nsis installer on amd64/windows using latest wails beta releases.
To release my project, I eventually rolled back to beta.36 to avoid some problems.

I've checked related issues. It seems the problem has been fixed in #1714 but I can't get it work using beta.43. Hopefully beta.44 would be released sooner and contain the corresponding fix. Thx.

### To Reproduce

In beta.42 ~ beta.43, using the default vue template

```
wails build -nsis
```

### Expected behaviour

The wails binary is built but the nsis installer is failed to build. 

```
cannot build nsis installer - no windows targets
```

### System Details

```shell
system: windows 11
arch: AMD64
go: latest
nsis are correctly installed
```

**Comment by stffabi** [comment]
Thanks for reporting this issue and using Wails.

As you already mentioned this has been fixed #1714 on master. Have you tried to follow the [Bleeding Edge Guide](https://wails.io/docs/next/guides/bleeding-edge) to use the latest commit?

**Comment by Purple-CSGO** [comment]
Not yet, but I would prefer using released version. Gonna try master codes if I want to experience the latest features. Thx

**Comment by leaanthony** [comment]
Closing this as it's a duplicate, and fixed 😉
