### ISSUE TITLE
The Preact JS template is broken

### ISSUE THREAD

**Issue by avrame** [wailsapp/wails#1759]
### Description

The Preact JS template is broken. The `src/main.jsx` file looks like it belongs to the React template instead. This is what it looks like:
```
import React from 'react'
import {createRoot} from 'react-dom/client'
import './style.css'
import App from './App'

const container = document.getElementById('root')

const root = createRoot(container)

root.render(
    <React.StrictMode>
        <App/>
    </React.StrictMode>
)
```

I fixed the issue by changing it to:
```
import { render } from "preact";

import "./style.css";
import App from "./App";

render(<App />, document.getElementById("app"));
```

### To Reproduce

1. run `wails init -n myproject -t preact` as appears on the [Creating a Project page](https://wails.io/docs/gettingstarted/firstproject)
2. run `wails dev`
3. Note that nothing appears in the application and the browser logs the following error:
```
render.js:66 Uncaught TypeError: Cannot read properties of null (reading '__k')
    at z (render.js:66:6)
    at Object.render (client.mjs:6:4)
    at main.jsx? [sm]:11:3
```

### Expected behaviour

The default app appears without any modification

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.5
ID:		21G72
Go Version:	go1.19
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.43

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available	
*nsis 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by avrame** [comment]
I'm not sure if the Preact template is in a separate repo so sorry if this is the wrong place to file the bug

**Comment by leaanthony** [comment]
Thanks! They are getting updated to using vite 3 so a fix is currently underway

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍
