### ISSUE TITLE
windows 11 arm64 error

### ISSUE THREAD

**Issue by cn-ygf** [wailsapp/wails#1762]
### Description

The target machine

os: windows 11 arm64 pro
version: 10.0.22000

### To Reproduce

wails build -platform windows/arm64

run

### Expected behaviour

not

### Screenshots

<img width="467" alt="image" src="https://user-images.githubusercontent.com/20332876/185358339-d3f0ff3b-ef82-45f8-95e7-552271b6d088.png">

### System Details

```shell
my dev mac



System
------
OS:		MacOS
Version: 	12.5.1
ID:		21G83
Go Version:	go1.18.5
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.43
```

**Comment by leaanthony** [comment]
What's the bug here?

**Comment by misitebao** [comment]
Please read the documentation carefully.

https://wails.io/docs/next/gettingstarted/installation#platform-specific-dependencies
https://wails.io/docs/next/guides/windows/#handling-the-webview2-runtime-dependency

**Comment by layxyer** [comment]
first look at the document upstairs, wails all the content of the document is not a lot, about half an hour to finish the job
