### ISSUE TITLE
undefined: a in v2.0.0-beta.44

### ISSUE THREAD

**Issue by Purple-CSGO** [wailsapp/wails#1769]
### Description

github.com\wailsapp\wails\v2@v2.0.0-beta.44\internal\app\app_production.go:86-92

```go
// Create binding exemptions - Ugly hack. There must be a better way
bindingExemptions := []interface{}{
a.appoptions.OnStartup,
a.appoptions.OnShutdown,
a.appoptions.OnDomReady,
a.appoptions.OnBeforeClose,
}
```

`a.` should be removed, otherwise `undefined: a` error occurs on build/dev.

### To Reproduce

wails build

### Expected behaviour

Building target: windows/amd64
------------------------------
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Generating bundle assets: Done.
  - Compiling application: # github.com/wailsapp/wails/v2/internal/app
C:\Users\Purp1e\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.44\internal\app\app_production.go:88:3: undefined: a
C:\Users\Purp1e\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.44\internal\app\app_production.go:89:3: undefined: a
C:\Users\Purp1e\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.44\internal\app\app_production.go:90:3: undefined: a
C:\Users\Purp1e\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.44\internal\app\app_production.go:91:3: undefined: a
Error: exit status 2

### System Details

```shell
Windows 11 amd64
```

**Comment by leaanthony** [comment]
Gah! I've issued a fix in v2.0.0-beta.44.1

**Comment by Purple-CSGO** [comment]
sorry, but `app_dev.go` seems to have the same problem

there should be some checks before release a new version xd

**Comment by leaanthony** [comment]
Pushed a new version. Happy to accept a PR to improve releases 👍
