### ISSUE TITLE
cannot build vue-ts template based project

### ISSUE THREAD

**Issue by guest6379** [wailsapp/wails#1796]
### Description

cannot build vue-ts template based project

### To Reproduce

1.  create a new project using the command `wails init -n hello -t vue-ts` 
```Wails CLI v2.0.0-beta.44.2

Initialising Project 'hello'
----------------------------

Project Name:      hello
Project Directory: /tmp/hello
Project Template:  vue-ts
Template Support:  https://wails.io

Initialised project 'hello' in 147ms.


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
2. build the project created before using the command 
`cd hello`
`wails build` 

```
Wails CLI v2.0.0-beta.44.2

App Type: 		desktop
Platforms: 		linux/amd64
Compiler: 		/go/bin/go
Build Mode: 		Production
Skip Frontend: 		false
Compress: 		false
Package: 		true
Clean Build Dir: 	false
LDFlags: 		""
Tags: 			[]
Race Detector: 		false

Building target: linux/amd64
----------------------------
  - Installing frontend dependencies: Done.
  - Compiling frontend:     
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build
    
    Please update to v0.35.0 or higher for TypeScript version: 4.8.2
    node_modules/@vue/runtime-core/dist/runtime-core.d.ts(1846,33): error TS2344: Type 'HostElement' does not satisfy the constraint 'RendererElement'.
    
    
Error: exit status 2


ERROR: exit status 2

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Expected behaviour

**it seems that the outdated versions in  "devDependencies" of the original template file causes the compile error.**
[v2/cmd/wails/internal/commands/initialise/templates/templates/vue-ts/frontend/package.json](https://github.com/wailsapp/wails/blob/16581ceff91961a0a0f2eb5f132b6eb98f32b498/v2/cmd/wails/internal/commands/initialise/templates/templates/vue-ts/frontend/package.json)

# I fix this problem by updating the template file as below
```
{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.1",
    "typescript": "~4.7.4",
    "vite": "^3.0.4",
    "vue-tsc": "^0.39.5",
    "@babel/types": "^7.17.10"
  }
}
```

### System Details

```shell
go version: `1.8.3`
wails version: `v2.0.0-beta.44.2`
```

**Comment by liuv3v6** [comment]
is that 
in frontend file : tsconfig.json ， add  in compilerOptions' this : "skipLibCheck": true
like that  
```
{
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": false,
    "esModuleInterop": true,
    "lib": [
      "esnext",
      "dom"
    ],
    "skipLibCheck": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}

```

**Comment by leaanthony** [comment]
Thanks for the info! Have you tried the templates on `master`? Please test using [this guide](https://wails.io/docs/guides/bleeding-edge) 👍

**Comment by guest6379** [comment]
> Thanks for the info! Have you tried the templates on `master`? Please test using [this guide](https://wails.io/docs/guides/bleeding-edge) +1

I've tested `master` branch few minutes before, and got the same compile error, please check the screenshot below:
![image](https://user-images.githubusercontent.com/15060397/187030389-dd291932-74e6-483e-b622-41cde83c2b8d.png)

**Comment by guest6379** [comment]
> I find a way: in frontend file : tsconfig.json ， add in compilerOptions' this : "skipLibCheck": true like that
> 
> ```
> {
>   "compilerOptions": {
>     "target": "esnext",
>     "useDefineForClassFields": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "strict": true,
>     "jsx": "preserve",
>     "sourceMap": true,
>     "resolveJsonModule": true,
>     "isolatedModules": false,
>     "esModuleInterop": true,
>     "lib": [
>       "esnext",
>       "dom"
>     ],
>     "skipLibCheck": true
>   },
>   "include": [
>     "src/**/*.ts",
>     "src/**/*.d.ts",
>     "src/**/*.tsx",
>     "src/**/*.vue"
>   ],
>   "references": [
>     {
>       "path": "./tsconfig.node.json"
>     }
>   ]
> }
> ```

Thanks for the update,  it works, but `skipLibCheck: true` may be an acceptable workaround for testing only

**Comment by leaanthony** [comment]
Thanks for the update. Do you think this is worth adding to the Vue guide? Feel free to raise a PR 👍

**Comment by liuv3v6** [comment]
> 

I't worth.   and raising PR  Is my pleasure, I will try in the next few days.

**Comment by liuv3v6** [comment]
> 

It can using in product ,  because the vue offical template of vite using this config, and the error  just  lib type error, It won't cause any serious problems

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by guest6379** [comment]
![image](https://user-images.githubusercontent.com/15060397/187677247-9e7fb33a-ec33-4a4d-88ed-28bdca5ff0af.png)

I quickly tested this  #1813 , It works as expected, thanks for your nice work. :+1:
