### ISSUE TITLE
Consider making 'EventsOff' accepting a vararg of event names

### ISSUE THREAD

**Issue by brys0** [wailsapp/wails#1797]
### Description

EventsOff (Should probably be called Unregister or UnregisterEvents) should take a variable amount of arguments. This is useful in the case of having multiple events listeners change together, for example, upload:progress, and upload:finished. 

### To Reproduce

N/A

### Expected behaviour

N/A

### Screenshots

N/A

### Attempted Fixes

N/A

### System Details

```shell
N/A
```

**Comment by Lyimmi** [comment]
@brys0 are you working on this? If not @leaanthony I would be happy to pick it up.

**Comment by brys0** [comment]
> @brys0 are you working on this? If not @leaanthony I would be happy to pick it up.

Hi! No, I'm not and don't plan on doing so anytime soon.. starting school soon (literally about 1 day) so feel free to have a crack at it.. I'd love to try and work on it but, my academics are more important

**Comment by leaanthony** [comment]
Nice one @Lyimmi 🙏

**Comment by Lyimmi** [comment]
@leaanthony should both go and js functions change, or just the js side?


```golang
EventsOff(ctx context.Context, eventName string, additionalEventNames ...string)
```

```javascript
EventsOff(eventName, ...additionalEvents)
```

**Comment by leaanthony** [comment]
They should be the same 🙏
