### ISSUE TITLE
Sharp Edges for Frameless App on Mac

### ISSUE THREAD

**Issue by Debdut** [wailsapp/wails#1805]
### Description

The edges of an frameless window in sharp on Mac

<img width="1024" alt="Screen Shot 2022-08-30 at 2 03 23 PM" src="https://user-images.githubusercontent.com/7561070/187389732-5a33d2e8-09b6-47ad-8d3c-ff632fda4ca8.png">

### To Reproduce

Use these options in your wails app

```go
err := wails.Run(&options.App{
    Title:            "codeui",
    Width:            800,
    Height:           600,
    Assets:           assets,
    BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
    OnStartup:        app.startup,
    Bind: []interface{}{
        app,
    },
    Frameless: true,
    Mac: &mac.Options{
        WindowIsTranslucent:  true,
        WebviewIsTransparent: true,
    },
})
```

### Expected behaviour

The borders must be rounded!

### System Details

```shell
System
------
OS:		MacOS
Version: 	12.5
ID:		21G72
Go Version:	go1.18.3
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.44.2

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	8.5.5
*upx  				N/A 		Installed 	upx 3.96
*nsis  				N/A 		Available 	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by raguay** [comment]
On you background color, set it to transparent (A: 0). In the CSS for the body, set the border-radius for the body to the amount of curvature you want with a transparent boarder with 1 px width. It works great for my applications once built, but the dev mode doesn't render the transparency correctly.
<img width="353" alt="CleanShot 2022-08-30 at 15 49 18@2x" src="https://user-images.githubusercontent.com/2487495/187393155-01785eea-a8b2-461c-8b8c-f5a552ad6ee6.png">

**Comment by leaanthony** [comment]
I'm struggling to understand why this would be true only in dev mode 🤔

**Comment by raguay** [comment]
I have no idea. I've tried everything and it never works right in dev mode.
But, that isn't a deal breaker.

**Comment by Debdut** [comment]
Thanks guys 🙏 

@leaanthony should I close this or keep it open? or shall I create a small repo where this thing is replicated?

**Comment by leaanthony** [comment]
Yeah, I'd like to know why!

**Comment by raguay** [comment]
BTW: change this line:

BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},

To:

BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 0},

**Comment by leaanthony** [comment]
That sounds insane 😂 I'll have a look this weekend
