### ISSUE TITLE
Can't disable kinetic scrolling on mac

### ISSUE THREAD

**Issue by dzpt** [wailsapp/wails#1816]
### Description

I follow the instruction for disable kinetic overscrolling 
https://wails.io/docs/guides/overscroll/

by applying
```
body {
    overscroll-behavior: none;
}
```

But it doesn't work while using trackpad
I'm using mac

### To Reproduce

1. Create new app with wails
2. Run and scroll up or down, would see the content has kinetic effect

### Expected behaviour

Kinetic scrolling is needed to be disabled

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18.4
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.42

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available
*nsis 				N/A		Available
```

**Comment by leaanthony** [comment]
Thanks for reporting this. I don't have a trackpad (yet), so perhaps someone else can confirm.

**Comment by leaanthony** [comment]
Confirmed. Appears to be impossible via CSS. I'm not sure where the CSS workaround came from e but I'll add this to the backlog.

**Comment by dzpt** [comment]
@leaanthony i figured out the simplest way to workaround is putting `overflow: hidden;` inside html in css.

**Comment by leaanthony** [comment]
Thanks for letting us know! I'll add that to the default templates and update the docs. There's a way to disable regardless of CSS so I'll keep this open 👍

**Comment by leaanthony** [comment]
@dzpt I've updated the documentation. The only way to disable it in Objective-C is to disable scrolling entirely. I think the CSS option gives more flexibility so let's leave it at that for now 👍
