### ISSUE TITLE
 Access is denied

### ISSUE THREAD

**Issue by 107295472** [wailsapp/wails#1838]
### Description

Error: CreateFile E:\go\work\tsrelease\frontend\wailsjs\go\main: Access is denied.

### To Reproduce

Error: CreateFile E:\go\work\tsrelease\frontend\wailsjs\go\main: Access is denied.

### Expected behaviour

Error: CreateFile E:\go\work\tsrelease\frontend\wailsjs\go\main: Access is denied.

### System Details

```shell
Wails
------
Version:        v2.0.0-beta.44.2

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       105.0.1343.33
npm             N/A             Installed       8.5.0
*upx            N/A             Available
*nsis           N/A             Available
```

**Comment by NULLB8** [comment]
me too,i don't kown quesions

**Comment by 107295472** [comment]
Wait for the official version
