### ISSUE TITLE
Support Distribution 'Archcraft'

### ISSUE THREAD

**Issue by swaroopRajwal** [wailsapp/wails#1845]
**Description**
Distribution 'archcraft' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.9 |
| Go Version    | go1.19.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | archcraft |
| Distribution Name   | Archcraft |
| Distribution Version   |  latest|

**Comment by leaanthony** [comment]
Hey there! It looks like you're using Wails v1. Please use Wails v2 and you should find your distribution is already supported 👍
