### ISSUE TITLE
Provide a JSON schema for Wails' project config

### ISSUE THREAD

**Issue by binyamin** [wailsapp/wails#1851]
### Is your feature request related to a problem? Please describe.

It's difficult to write the config when I need to keep referencing the online documentation. I'd much rather stay in my code-editor.

### Describe the solution you'd like

Provide a JSON schema, which users can link to in order to provide intellisense for the config file. Maybe even link to it directly when running the `wails init` command.

### Additional context

I wrote one last night. I can open a PR.

I'm not sure if it should go on the website (eg. `wails.io/schema-v2.json`), or in https://github.com/schemastore/schemastore/, which houses 500+ other JSON schemas.

**Comment by leaanthony** [comment]
Hey there 👋 I like the idea! Please feel free to open a PR and we'll look at merging it after the v2 release 👍

**Comment by binyamin** [comment]
@leaanthony On the PR, I added a list of additional tasks. They're not strictly necessary, but I think they're good to have. They should also be relatively simple for someone who, unlike me, is familiar with the code :wink:.
