### ISSUE TITLE
BUG: v2.0.0-rc.1.1: Draggable CSS proper doesn't always work

### ISSUE THREAD

**Issue by raguay** [wailsapp/wails#1852]
### Description

This latest version of wails allows you to set the CSS property to define the element that drags the entire window. This only works right now if you click on the drag region from another program that is foremost. If you are using the application, you can't drag the window (at least on my programs).

Macos Monterey 12.6 (21G115)
Macbook pro M1 chip system

### To Reproduce

1. Add the "--wails-draggable: 'drag';" css property to the element in the UI that is to be draggable.
2. Add the code to the main.go file:

```
    CSSDragProperty:   "--wails-draggable",
    CSSDragValue:      "drag",
```
3. Recompile the program and launch

### Expected behaviour

When the draggable area is clicked and dragged, the whole window should be dragged regardless of what was the beginning program.

### Screenshots

![2022-09-14 12 17 24](https://user-images.githubusercontent.com/2487495/190066025-e337a466-15cf-4b8f-8dff-970eb9f63b88.gif)

### Attempted Fixes

I have no idea on how to fix this. It's a puzzle to me.

### System Details

```shell
Wails CLI v2.0.0-rc.1.1

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.6
ID:		21G115
Go Version:	go1.19.1
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-rc.1.1

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	8.19.1
*upx  				N/A 		Available
*nsis  				N/A 		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by raguay** [comment]
Fixed. I had this in the CSS:
```css
—wails-draggable: “drag”;
```

Removing the quotes allows me to drag it all the time. Not sure why the behavior above was found.

**Comment by leaanthony** [comment]
That's mad and I have zero understanding as to why that happens. Glad the official way works 👍
