### ISSUE TITLE
support linux mips64

### ISSUE THREAD

**Issue by zcwgd163** [wailsapp/wails#1856]
### Is your feature request related to a problem? Please describe.

build command flag -platform not support linux/mips64

### Describe the solution you'd like

build command flag -platform support linux/mips64

**Comment by stffabi** [comment]
Thanks for using Wails and opening this enhancement request.

Allowing the platform linux/mips64 for compilation is an easy change, basically just adding it here:
https://github.com/wailsapp/wails/blob/f1dc9eb4ef4f310a222e1c32142030a35cbd40c5/v2/cmd/wails/internal/commands/build/build.go#L255-L256

The main problem for the Wails team is more to have a development environment for testing it. So we could only add unofficial support for it, which means one can use it to build against it but there's no guarantee that future changes won't break it. Supporting the platform would be done by the community and the Wails team won't test changes against it.

If you want to give it a try and have a linux/mips64 development host you could just use `wails build` which would build against the host platform and currently allows building `linux/mips64`.

It would be good to add a warning if one builds with `wails build` and if `platform/arch` can't be found in the validPlatformArch. Maybe we could also mark some of the arches like `windows/386` and `linux/arm` as unofficial/community and print a warning that one uses an unofficial/community supported architecture. @leaanthony what do you think?

**Comment by leaanthony** [comment]
I think that if you are savvy enough to try supporting a new platform, you are savvy enough to bypass the platform check 😄 Also, cross compiling in this way isn't supported right now. The best you could try is disable the check and try to run it on a mips machine and see if the distro has all the necessary libraries to make it work.
