### ISSUE TITLE
wails build  web not displayed

### ISSUE THREAD

**Issue by tiyongliu** [wailsapp/wails#1859]
### Description

My project  `wails dev`  mode Can be displayed normally， `wails build` mode not display

`
package main

import (
	"embed"
	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/logger"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
	"keeper/app/bridge"
	"log"
)

//go:embed frontend/dist
var assets embed.FS

func main() {
	//go app.RunApplication()
	app := bridge.NewApp()
	bridge.Application = app

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "wails",
		Width:  1024,
		Height: 768,
		// MinWidth:          720,
		// MinHeight:         570,
		// MaxWidth:          1280,
		// MaxHeight:         740,
		DisableResize:     false,
		Fullscreen:        false,
		Frameless:         false,
		StartHidden:       false,
		HideWindowOnClose: false,
		RGBA:              &options.RGBA{R: 255, G: 255, B: 255, A: 255},
		Assets:            assets,
		LogLevel:          logger.DEBUG,
		OnStartup:         app.Startup,
		OnDomReady:        app.DomReady,
		OnShutdown:        app.Shutdown,
		OnBeforeClose:     app.OnBeforeClose,
		Bind: []interface{}{
			app,
			app.Connections,
			app.DatabaseConnections,
			app.ServerConnections,
			app.Plugins,
		},
		// Windows platform specific options
		Windows: &windows.Options{
			WebviewIsTransparent: false,
			WindowIsTranslucent:  false,
			DisableWindowIcon:    false,
		},
	})
	if err != nil {
		log.Fatal(err)
	}
}
`

### To Reproduce

1. wails build

### Expected behaviour

build  normal display

### Screenshots

# wails dev
![1663250415213](https://user-images.githubusercontent.com/105840917/190424056-382fc785-e4f3-4f2e-9169-096856a6ffa6.jpg)
![image](https://user-images.githubusercontent.com/105840917/190425396-160806be-ebd2-4015-a34c-b94fc12ea386.png)
![image](https://user-images.githubusercontent.com/105840917/190424476-65734847-d57c-4c46-91e3-10610feb51f6.png)

# wails build
![image](https://user-images.githubusercontent.com/105840917/190424574-4edaffc9-9055-4128-9b97-a77bc88c5af9.png)
![image](https://user-images.githubusercontent.com/105840917/190424838-7de0d874-9a0a-4193-a927-ce2dff2e3982.png)
![image](https://user-images.githubusercontent.com/105840917/190425103-777bae13-0c20-4833-a67e-a8eca7da79ad.png)

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-rc.1.1

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       105.0.1343.33
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

This could happen if the embed directive points to the wrong directory, [My application is displaying a white/blank screen](https://wails.io/docs/next/guides/troubleshooting/#my-application-is-displaying-a-whiteblank-screen)

Also a debug build with `wails build --debug` will help debugging the issue. In such a build you can right click onto the window and open the `webview2 developer tools` where you could see what has been loaded or what goes wrong.

**Comment by tiyongliu** [comment]
thank you。
look like  vue3 404

**Comment by tiyongliu** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by tiyongliu** [comment]
![image](https://user-images.githubusercontent.com/105840917/190458837-2b03b833-0b91-43c1-b3c1-ef817e1bccdd.png)
look like  load vuejs error, how do I see fix

**Comment by tiyongliu** [comment]
![1663304348716](https://user-images.githubusercontent.com/105840917/190560373-f2118bdd-a81c-42ff-83aa-a0165960f549.jpg)
![1663304443293](https://user-images.githubusercontent.com/105840917/190560384-33c83c90-6010-4170-8564-d90846a2527c.jpg)
I'm going to replace the external JS with the internal JS

**Comment by tiyongliu** [comment]
![image](https://user-images.githubusercontent.com/105840917/190560464-334f218b-3d05-470f-ac61-59c4ab699229.png)

**Comment by stffabi** [comment]
The problem is that files which start with '_' or '.' aren't embedded by default.

Changing the embed to

//go:embed all:frontend/dist
var assets embed.FS

See also https://pkg.go.dev/embed

> If a pattern begins with the prefix ‘all:’, then the rule for walking directories is changed to include those files beginning with ‘.’ or ‘_’. For example, ‘all:image’ embeds both ‘image/.tempfile’ and ‘image/dir/.tempfile’.

**Comment by stffabi** [comment]
We should change our templates to include the 'all:' prefix since we now require go 1.18+

**Comment by stffabi** [comment]
PR #1862 updates the templates and the docs.

**Comment by stffabi** [comment]
Thanks for bringing this up @tiyongliu 🙏

**Comment by leaanthony** [comment]
Thanks for raising this @tiyongliu and thanks @stffabi for working out what was going on. PR merged so you should be good 👍👍👍
