### ISSUE TITLE
Frameless + draggable window causes multiple issues on Linux

### ISSUE THREAD

**Issue by lic-8** [wailsapp/wails#1861]
### Description

On Ubuntu, if you set the window to frameless, and set a component to draggable, When you try to drag the window it behaves quite strangly. There is some kind of offset between the mouse position and the window top-left (0,0).
I recorded a video of the main issue: [https://youtu.be/8PwUrPbueMA](https://youtu.be/8PwUrPbueMA)

Sometimes I also experience flickering in the whole window, and sometimes resizing the window is also buggy (these are not demonstrated in the video).

### To Reproduce

1. Create a project with Svelte 
2.  In `main.go` set `Frameless` to `true`
3. Set any component to draggable (`main` for instance) with `<main style="--wails-draggable:drag">`
4. run `wails dev` and try to move the window

### Expected behaviour

The window drags correctly accordingly to the mouse position, and the window can be resized without any issue.

### System Details

```shell
Wails CLI v2.0.0-rc.1.1

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Ubuntu
Version: 	18.04
ID:		ubuntu
Go Version:	go1.18.4
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-rc.1.1
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker 	docker.io 		Installed 	20.10.18
gcc 		build-essential 	Installed 	12.4ubuntu1
libgtk-3 	libgtk-3-dev 		Installed 	3.22.30-1ubuntu4
libwebkit 	libwebkit2gtk-4.0-dev 	Installed 	2.32.4-0ubuntu0.18.04.1
npm 		npm 			Installed 	8.5.5
*nsis 		nsis 			Installed 	v2.51-1
pkg-config 	pkg-config 		Installed 	0.29.1-0ubuntu2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by Lyimmi** [comment]
Hi, there is definitely something wrong here, after the initial first drag, something goes haywire, the mouse changes between drag and pointer about as fast as my screen can handle it and the spotty movement starts.

A few times my whole X session broke.
I'll tries to look into it, but no promises.

FYI: I tired on a Ubuntu 22.04

**Comment by Lyimmi** [comment]
@leaanthony I found the cause of the drag issue.
Surprise surprise it's a WebKit bug/behavior. If you hold down a mouse button than move it the "mouse up" event is not fired...

If we add a check on `mousemove` that the a button is still pressed or not, we can shut off dragging and it fixes the issue.

```javascript
//v2/internal/frontend/runtime/desktop/main.js:124

window.addEventListener('mousemove', function (e) {
    let mousePressed = e.buttons !== undefined ? e.buttons : e.which;
    if(window.wails.flags.shouldDrag && mousePressed <= 0) {
        window.wails.flags.shouldDrag = false;
    }
    ...
});
```

If this look ok, I can make a PR for it.


But as I fixed the drag problem I think I stumbled upon another issue.
If i set the window to framles, I cannot resize. We should be able to resize on linux as well right? 

In `v2/internal/frontend/desktop/linux/frontend.go` there is nothing about resizing. I remember this used to work and can't find anything about it not working on linux in the docs, or maybe I'm imagining things.

**Comment by leaanthony** [comment]
Awesome @Lyimmi ! So yes, PR would be awesome. Secondly, frameless resize on Linux should totally work. If not, let's fix it 👍

**Comment by Lyimmi** [comment]
I made a PR for a fix, I'll create a new issue for the resizing.

**Comment by lic-8** [comment]
@Lyimmi  Thank you kind stranger, you're a good person
