### ISSUE TITLE
wails cli  parse  tags  has bug

### ISSUE THREAD

**Issue by mars79668** [wailsapp/wails#1868]
### Description

has not separator,  strings.Split will split string to  a,b,c

if len(separator) > 0 {
		for _, tag := range strings.Split(tags, separator) {
			thisTag := strings.TrimSpace(tag)
			if thisTag != "" {
				userTags = append(userTags, thisTag)
			}
		}
	} else {
		userTags = append(userTags, tags)
	}

### To Reproduce

-tags  debug,   to go tags  be  d,e,b,u,g

### Expected behaviour

to go tags  be  d,e,b,u,g

### System Details

```shell
windows 11
```

**Comment by leaanthony** [comment]
There's a fix on master if you'd like to try it out 👍

**Comment by stffabi** [comment]
V2 has been released with a fix for this issue.

Please feel free to reopen if you see any more problems with this.

Thanks for reporting 🙏
