### ISSUE TITLE
Creating a Question Dialog That Defaults to Cancel in Windows

### ISSUE THREAD

**Issue by tataDan** [wailsapp/wails#1871]
### Is your feature request related to a problem? Please describe.

When I use the following code on Windows:
```
func (a *App) Confirm() {
	selection, err := runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:          runtime.QuestionDialog,
		Title:         "CONFIRM DELETION",
		Message:       "Are you sure you want to delete these records?",
	})
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(selection)
}
```
the "Yes" button is the default button, and I have no control over this behavior.  (When using Linux, the "No" button is the default).

This makes it more likely that the user might unintentionally do something like delete files or database records just by pressing the `<Enter>` key. It also results in inconsistent behavior between Windows and Linux.

### Describe the solution you'd like

I would like to be able to add a argument when calling the `MessageDialog` function that would cause the "No" button to be the default.

### Describe alternatives you've considered

One alternative that I have used is [gen2brain](https://github.com/gen2brain/dlgs).  The following code displays a question dialog with the "No" button being the default when using Windows:

```
package main

import (
	"fmt"

	"github.com/gen2brain/dlgs"
)

func main() {
	ret, err := dlgs.Question("Question", "Are you sure you want to format this media?", true)
	if err != nil {
		panic(err)
	}
	fmt.Println(ret)
}
```

Another alternative that I have considered is [zenity](https://github.com/ncruces/zenity).  The following code displays a question dialog with the "No" button being the default when using Windows:

```
package main

import "github.com/ncruces/zenity"

func main() {
	zenity.Question("Are you sure you want to proceed?",
		zenity.Title("Question"),
		zenity.DefaultCancel(),
		zenity.QuestionIcon)
}
```

### Additional context

According to [this web page](https://wails.io/docs/reference/runtime/dialog), the `DefaultButton` field is supported as a `MessageDialogOption` for MacOs. Perhaps if support for this field was added for Windows, then the desired results might be achieved. This is conjecture on my part as I do not have access to a Mac to test this.

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by tataDan** [comment]
I tested the PR on Windows 10 and found that it does fix my problem.
