### ISSUE TITLE
Rename `frontend` / modularize project

### ISSUE THREAD

**Issue by carljkempe** [wailsapp/wails#1877]
### Is your feature request related to a problem? Please describe.

Well, I was having trouble combining my freshly initialized `wails` app within my very well split back-end (_BE_).  Had to re-approach it, but the other way around and make my _BE_ fit into the folder structure of the `wails` app instead!  Obviously this isn't too big of a concern, but it still does make a valid suggestion? 😅

Two main questions stemmed from this:

### Describe the solution you'd like

1) Are we, or should we be able to rename the `frontend` directory?

2) Is there currently a way, or should there be a way for us developers to integrate `wails` into our per-existing, neat, folder structures?  (I was initially trying to split my `cmd/` dir into `cmd/client` and `cmd/server`, instead of leaving a "mess" in the root dir for `wails` alone.)

### Describe alternatives you've considered

I'm away from it all, so I won't be entirely specific; but I think that this might be appreciated by many!

### Additional context

![2022-09-25-151636_1920x1080_scrot](https://user-images.githubusercontent.com/110561976/192167984-d0f40f7e-fe68-4d41-9fa8-00a6e2cb27ab.png)

**Comment by olup** [comment]
I am interested by 2 as well. I wanted to build my golang library as one cmd and the app on top of it as another one, but it did not work out, and I ended up creating two repos and go getting my library from github to my wails app.

**Comment by mholt** [comment]
Subscribing, as I'm also integrating into an existing app and having to shuffle files around and refactor was not ideal.

Very similar to https://github.com/wailsapp/wails/issues/615

Basically, it'd be nice to:

- Have go.mod in a parent folder
- Rename "frontend"
- Have "frontend" be somewhere else

**Comment by leaanthony** [comment]
@mholt @olup @carljkempe - Please try the above draft PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by mholt** [comment]
Works well for what I need! Thank you!

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by mholt** [comment]
Awesome! Thank you again!!

**Comment by olup** [comment]
Just refactored https://github.com/olup/lunii-admin to use this, going great ! Thanks a lot 🚀

**Comment by learncodingforweb** [comment]
unable to use nextjs app for frontend. **How to integrate nextjs with wails app?**

**Comment by olup** [comment]
Please do not use existing issues to ask new questions. You can open a new issue for that.

**Comment by firelizzard18** [comment]
@leaanthony Your link to https://wails.io/docs/guides/bleeding-edge is broken. Does that guide still exist?

**Comment by leaanthony** [comment]
It's just the guide for testing PRs: https://wails.io/docs/guides/local-development#testing-a-pr
