### ISSUE TITLE
how to upgrade wails app online!

### ISSUE THREAD

**Issue by wangxing218** [wailsapp/wails#1883]
### Describe the solution you'd like

Hope that the official can provide a solution for self upgrading of applications
Like electric updater
This is just a need

**Comment by stffabi** [comment]
Thanks for reporting this enhancement request and using Wails

We already have a tracking issue for self-updating #1178. We welcome you being part of the discussion over there.

Closing as duplicate of #1178

**Comment by stffabi** [comment]
Duplicate of #1178
