### ISSUE TITLE
Support Printing

### ISSUE THREAD

**Issue by spekary** [wailsapp/wails#1886]
### Describe the solution you'd like

1) Be able to open the native OS print dialog and interact with it, like telling it how many pages are available to be printed, and getting back which pages the user requested.
2) Either send a generated PDF to the print queue, or use the webkit frontend to generate output using html/css/js offscreen.

I realize this is a big ask, but print dialog interaction is critical to many kinds of apps.

**Comment by leaanthony** [comment]
Thanks for opening this. WebView2 on Windows has this built in so should be reasonable to do. We would need to investigate the other platforms.

**Comment by leaanthony** [comment]
Supported in v3
