### ISSUE TITLE
Add Portuguese language

### ISSUE THREAD

**Issue by TheyCallMeErick** [wailsapp/wails#1888]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I want to contribute translating the documentation for portuguese

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by misitebao** [comment]
@Azevedo-Erick 
Thank you, the document translation work of the wails project is done through [Crowdin](https://crowdin.com/project/wails). 
Portuguese has just been added to it. You can join the project and start your translation work. When the translation progress reaches a certain amount, we will Add it to the documentation site.
