### ISSUE TITLE
Support Distribution 'ArcoLinuxB-deepin'

### ISSUE THREAD

**Issue by kelus** [wailsapp/wails#190]
**Description**
Distribution 'ArcoLinuxB-deepin' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | ArcoLinuxB-deepin |
| Distribution Version   | v19.02.4 |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
hello @kelus thank's for opening the ticket :)
give me a few hours to make the necessary changes and please stay around for testing if possible :+1: 

one thing though, can you please paste the output of `cat /etc/os-release` ??

**Comment by kelus** [comment]
Hi @bh90210,
Thank you for your quick response.

**Output os-release:**
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

**Output lsb_release:**
LSB Version:	1.4
Distributor ID:	ArcoLinuxB-deepin
Description:	ArcoLinuxB-deepin
Release:	v19.02.4
Codename:	ArcoLinux

**Comment by bh90210** [comment]
uh this is great news!
lsb output got me scared a little :smile: 
it seems it'll be really easy to support ArcoLinux after all! 
I am preparing a pull request, @leaanthony will give you instructions when things are ready :+1:

**Comment by bh90210** [comment]
actually my bad! can u please try `wails update -pre` ?
I think it should work..

**Comment by kelus** [comment]
Updated the Wails version to v0.17.12-pre. Now it's works like a charm.

**Comment by bh90210** [comment]
amazing! please note that this pre-release has (braking) changes not yet reflected in the documentation! 
we r working on it though, v1 is coming soon. In the mean time if you find something not working please open a ticket or joing our slack channel for 24/7 live support :smile:
