### ISSUE TITLE
Bindings build fail on windows server gh action

### ISSUE THREAD

**Issue by olup** [wailsapp/wails#1905]
### Description

<img width="536" alt="image" src="https://user-images.githubusercontent.com/13785588/192308907-0803a403-f4aa-485d-abb5-b64aa07e1277.png">
https://github.com/olup/lunii-admin/actions/runs/3128686339/jobs/5076837549

I can't be too specific about it, as I don't have a windows machine myself. But build used to be fine in GH pipeline and now fails on the new step to build bindings.

Is there some step I can take to get a clearer picture of what's wrong ?

### To Reproduce

run `wails build` on a windows server github pipeline

### Expected behaviour

To build without error

### System Details

```shell
App Type: 		desktop
Platforms: 		windows/amd64
Compiler: 		C:\hostedtoolcache\windows\go\1.19.1\x64\bin\go.exe
Skip Bindings: 		false
Build Mode: 		Debug
Obfuscated: 		false
Skip Frontend: 		false
Compress: 		false
Package: 		true
Clean Build Dir: 	false
LDFlags: 		"-v '-extldflags=-static -lm' -X main.NR_LICENCE=*** -X main.version=v0.0.12"
Tags: 			[]
Race Detector: 		false
Output File: 		lunii-admin_windows_amd64.exe
```

**Comment by olup** [comment]
This is the code for a DLL not found - so prob. on my end.

**Comment by olup** [comment]
No idea...
I run my build like this:
```
      - name: Build
        run: |
          Set-Item -Path Env:CGO_LDFLAGS -Value "-LD:/a/lunii-admin/lunii-admin/bindings/windows/lib"
          Set-Item -Path Env:CGO_CFLAGS -Value "-ID:/a/lunii-admin/lunii-admin/bindings/windows/include"
          go generate && wails build -debug -o lunii-admin_windows_amd64.exe -ldflags "-v '-extldflags=-static -lm' -X main.NR_LICENCE=${env:NR_LICENCE} -X main.version=$(git describe --tags --abbrev=0)"
```
Any suggestion on what could be wrong ?

**Comment by leaanthony** [comment]
Try setting `CGO_ENABLED` to 1

**Comment by olup** [comment]
That shoudl do teh trick ?
<img width="755" alt="image" src="https://user-images.githubusercontent.com/13785588/192385939-7b6e3aca-7046-42d7-adf3-9438de4b0261.png">
But no luck.

**Comment by leaanthony** [comment]
Without an actual error message this will be hard for us to help you

**Comment by stffabi** [comment]
It seems like you are using CGO with static linking some libraries. IIRC we are currently not passing the specified `ldflags` to the build of the binding generator binary. So maybe it's caused by the missing ldflags, that the generated binding binary doesn't execute properly.

Just pure guessing at the moment 😄

**Comment by olup** [comment]
Hey, thanks for your answer. Indeed I am statically linking `flac` (and `lm` as it's needed by `flac`). I thought it could be something like you described, however I can't make out why it would work on linux and macos, but not on windows ?

**Comment by stffabi** [comment]
Static linking seems only be used on your Windows build according to this: https://github.com/olup/lunii-admin/blob/main/.github/workflows/build-next.yaml

I assume one of the native dependencies (libmp3lame?) is missing on the Windows build agent, whereas on Linux/MacOS it seems to be installed. So it will find the lib on those systems.

**Comment by stffabi** [comment]
Maybe the easiest way for you to go would be to generate the bindings manually, check them in and skip building the bindings during build.

**Comment by olup** [comment]
If I remember correctly the go-flac package is linking the flac library. In both macos and linux, the command is enough to produce statical linking to flac. On mac os you can't statically link everything.
Both don't need more flags as flac is present in the sysroot. On windows I found pre-built binaries that I ship in the repo, and those are pointed to by the compiler flags.
Generateing binding and checking them in sounds a great idea, what's the command to generate them ?

**Comment by stffabi** [comment]
Generate bindings: `wails generate module`
Skip bindings generation during build: `wails build -skipbindings`

**Comment by olup** [comment]
Ok, I'll close this issue because the workaround is working.  (thx @stffabi, @leaanthony )

However I guess the safest play here would be to actually generate bindings with any flags passed on to the main build ?

**Comment by leaanthony** [comment]
It does feel like there should be an action for this. I will discuss with @stffabi 👍
