### ISSUE TITLE
[v2 linux] wails dev command fails on latest

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#1919]
### Description

After the commit b2069c871ddb9dc5a530e927e7559e90731cb152 `wails dev` fails with the following message:

```
Building application for development...
  - Generating bindings: Done.
  - Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/devserver
../mywails/v2/internal/frontend/devserver/devserver.go:86:56: not enough arguments in call to assetserver.NewAssetHandler
	have (context.Context, *options.App)
	want (context.Context, fs.FS, http.Handler)
../mywails/v2/internal/frontend/devserver/devserver.go:338:60: cannot use d (variable of type *DevWebServer) as type frontend.Frontend in argument to d.dispatcher.ProcessMessage:
	*DevWebServer does not implement frontend.Frontend (missing RunMainLoop method)

```

v2/internal/frontend/devserver/devserver.go:86
Looks like the definition of `NewAssetHandler()` changed but the usage didn't.

### To Reproduce

1. create a new project with the latest master
2. run wails dev
3. see the error message

### Expected behaviour

I expect that wails runs in dev mode.

### Screenshots

![Screenshot from 2022-09-29 17-33-58](https://user-images.githubusercontent.com/8627125/193076462-ebc952fe-4665-4320-b40e-bae81b2649e3.png)

### Attempted Fixes

I have not tried to fix this.

### System Details

```shell
System
------
OS:		Ubuntu
Version: 	22.04
ID:		ubuntu
Go Version:	go1.19.1
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker 	docker.io 		Installed 	20.10.18
gcc 		build-essential 	Installed 	12.9ubuntu3
libgtk-3 	libgtk-3-dev 		Installed 	3.24.33-1ubuntu2
libwebkit 	libwebkit2gtk-4.0-dev 	Installed 	2.36.8-0ubuntu0.22.04.1
npm 		npm 			Installed 	6.14.13
*nsis 		nsis 			Available 	3.08-2
pkg-config 	pkg-config 		Installed 	0.29.2-1ubuntu3

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```

**Comment by leaanthony** [comment]
Nice find. I'm going to enable a workflow for master merges that'll pick this up earlier. Thanks 🙏

**Comment by Lyimmi** [comment]
@leaanthony I saw that in one of your commits you fixed the NewAssetHandler(), it works now.
Now the DevWebServer's handleIPCWebSocket() fails with the following:

```
  - Generating bindings: Done.
  - Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/devserver
../mywails/v2/internal/frontend/devserver/devserver.go:338:60: cannot use d (variable of type *DevWebServer) as type frontend.Frontend in argument to d.dispatcher.ProcessMessage:
        *DevWebServer does not implement frontend.Frontend (missing RunMainLoop method)
```

In `/v2/internal/frontend/devserver/devserver.go#L338` the `d.dispatcher.ProcessMessage(string(msg), d)` `d` should implement a frontend.Frontend interface.

But the DevWebServer's desktopFrontend property is unexported.

If it's a known problem please let me know! I'm not trying to annoy you.

**Comment by leaanthony** [comment]
@Lyimmi apologies for being slow on this. I'll get this sorted today thanks to @JulioDRF

**Comment by Lyimmi** [comment]
@leaanthony there's no need for apologies. I could've started a fix my self. So thanks for looking at it @JulioDRF!

**Comment by leaanthony** [comment]
Always feel free to do so! Bug fixes are *always* welcome - no need to wait for anyone 👍 🙏
