### ISSUE TITLE
javascript alert not working on Macos

### ISSUE THREAD

**Issue by sunshine69** [wailsapp/wails#1922]
### Description

Hi,

Is it a known issue that the Alert function not working on MacOS?

I just learnt wails for 2 days, got a repo like this, and in this file https://github.com/sunshine69/check-passwords/blob/main/frontend/src/App.svelte I use the alert function to display the output.

While it is working fine on Ubuntu 22.01.1 but on MacOS I did not see any alert popup.

Put some debuging print at my go file and confirm the request get though and print out the text as result.

Is it something I did wrongly?

Thanks heap

### To Reproduce

Check out my repo https://github.com/sunshine69/check-passwords
on MacOS intel

Install it based on the doc - 
Need to do
mkdir frontend/dist
touch frontend/dist/.txt
wails build

and run the binary.

### Expected behaviour

the running apps should work the same way it works on Ubuntu, that is my alert function should popup.

### System Details

```shell
% wails doctor
Wails CLI v2.0.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.3.1
ID:		21E258
Go Version:	go1.19.1
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	8.19.2
*upx  				N/A 		Available 	
*nsis  				N/A 		Available 	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

steve.kieu@192 check-passwords-main %
```

**Comment by misitebao** [comment]
Is it possible to provide the output of devtool which will help us locate the error.

**Comment by leaanthony** [comment]
Workaround: use a [message dialog](https://wails.io/docs/reference/runtime/dialog#messagedialog) but it would be good to know what `alert` is doing in the dev console (my guess is it's disabled by WkWebkit by default.

**Comment by JulioDRF** [comment]
Looks like `window.alert()` and `window.confirm()` do not work out of the box on WkWebview. They need to be implemented manually:
https://stackoverflow.com/questions/26898941/ios-wkwebview-not-showing-javascript-alert-dialog

The implementation would probably need to live in `v2/internal/frontend/desktop/darwin/WailsContext.m`

**Comment by sunshine69** [comment]
> Workaround: use a [message dialog](https://wails.io/docs/reference/runtime/dialog#messagedialog) but it would be good to know what `alert` is doing in the dev console (my guess is it's disabled by WkWebkit by default.

Yeah I already did it on the day I report this issues, the dialog even looks nicer and works on all platform I tested (MacOS, Windows and Linux)

I also found wails provide several widgets dialogs as well which is nifty.

Thanks.

I think user should use the default dialog implementation so we just need to document it as known bug/limitation of the WkWbview on Macos and advide user to use dialog. Oh hang on, do we have any `list of known limitation` somewhere already I remember. Just add them in there is enough.

**Comment by leaanthony** [comment]
We could consider overriding `window.alert` if that's possible....

**Comment by OlegGulevskyy** [comment]
My 2 cents on this, I am not big fan of overwriting stuff and changing the behaviour silently like this, as this might be unexpected for the developer.
What if we consider slightly less intrusive way - overwrite the `window.alert` with a custom function that detects rendering platform and if it's `WkWebview`, issues a `console.warn` message with text, guiding the developer to the problem solution - which is to use Dialogs.

Here is an example. Snippet below results in a behaviour illustrated on the screenshot.
```js
window.alert = ((alert) => {
  return function (...args) {
    // detect if the app is running inside WkWebview
    const renderer = "WkWebview";
    if (renderer === "WkWebview") {
      console.warn("window.alert is not working within WkWebview");
      console.warn(
        "Consider using Message dialog from Wails - https://wails.io/docs/reference/runtime/dialog/#messagedialog"
      );
    }
    return alert.call(window, ...args);
  };
})(window.alert);

window.alert("HELLO FROM OVERRID 123");
```
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/43781031/202726221-10d4aecd-1093-4790-87b5-6e4df1a75096.png">

**Comment by leaanthony** [comment]
Yeah, that's not a bad approach. Or we could use a similar method to test a flag and run the runtime dialog.

**Comment by misitebao** [comment]
> We could consider overriding `window.alert` if that's possible....

This means we need to override the alert method in the injected script?

**Comment by leaanthony** [comment]
For v3 there's a runtime.js per platform so we could just add it to the macOS one?
