### ISSUE TITLE
[v2 Linux] Transparent window on linux

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#1923]
### Is your feature request related to a problem? Please describe.

Currently in v2 we can use a transparent window on Windows and Mac, but Linux is missing this feature.

I would like to be able to use transparent windows on Linux as well.

### Describe the solution you'd like

I would like to add the transparent window functionality to `internal/frontend/desktop/linux/window.go` and a new option to `linux.Options` to enable it.

I was able achieve window transparency without any blur/frosting effect. (I think blur could be added in GTK4)

If it is ok to add before v2.1.0 (it is not in the road map) I'd be happy to make a PR for it.

### Describe alternatives you've considered

Did not consider anything else.

### Additional context

![Screenshot from 2022-09-30 20-10-17](https://user-images.githubusercontent.com/8627125/193331202-fd73f4fe-01d4-4c8f-8c1a-c216b642f959.png)

**Comment by leaanthony** [comment]
Awesome! Feel free to make a PR for this. Feature parity is important!
