### ISSUE TITLE
Support Distribution 'elementary'

### ISSUE THREAD

**Issue by Winturtle** [wailsapp/wails#193]
**Description**
Distribution 'elementary' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | elementary |
| Distribution Version   | 5.0 |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
hello @Winturtle , elementary is ubuntu based so this will be easy and fast. 
Give me a couple of hours to "fix" it and please stay around for testing :)

**Comment by bh90210** [comment]
ok my bad _again_.

can you please try `wails udapte -pre` 
and then `wails setup` & `wails init`?

**Comment by Winturtle** [comment]
hello 
Today i try use wails update -pre
it is done
Wails v0.17.0 - Checking for updates...

✓ Checking for updates...

    Current Version : v0.17.0
  Latest Prerelease : v0.17.12-pre

✓ Installing Wails v0.17.12-pre

Wails updated to v0.17.12-pre
