### ISSUE TITLE
Add default build flags to wails.json

### ISSUE THREAD

**Issue by bearsh** [wailsapp/wails#1937]
### Describe the solution you'd like

add a way to specify default build flags in wails.json, probably in the similar way as the build hooks work:

```
"defaultBuildArgs": {
        "GOOS/GOARCH": "...",
        "GOOS/*": "...",
        "*/*": ""
},
```

the make things a bit simpler and unlike the build hooks, only the _best match_ would be choosen.

another approach would be to put the build arg themselves in a object and merge it for each matching GOOS/GOARCH match...

**Comment by leaanthony** [comment]
This is something that is addressed in v3. Closing for now.
