### ISSUE TITLE
make frontend code reusable with http server as the backend

### ISSUE THREAD

**Issue by laoshaw** [wailsapp/wails#1940]
### Is your feature request related to a problem? Please describe.

After I am done with a wails project, I hope the frontend code can be used with a https server, e.g. those js-go bindings can act like an ajax call seamlessly, is this possible?

i.e. to make wails to support both a local desktop backend, and a remote http server backend

### Describe the solution you'd like

Not an expert here in the solution but it will be great if wails can support two backends, so the application be either be a local desktop GUI program and a cloud-based solution, one stone two birds.

**Comment by carljkempe** [comment]
Simply leaving [this](https://github.com/wailsapp/wails/issues/1877) here, in hopes of having it closed some day. Didn't explain it well at all (horrible first issue by me).

**Comment by leaanthony** [comment]
We're looking to introduce this feature in the v3 release cycle. Closing this for now.
