### ISSUE TITLE
Improve design on binding package

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#1953]
_Comments from PR #1942_

I think we could significantly improve the design, and its testability by splitting the bindings generation into multiple component (with Single Responsibility Principle, in mind).

Here is just my brain dump on the matter.

Basically, the idea would be:

    A component that parse the go code and build an AST. That already exist AFAIK.
    A component that translate that Go AST into a JS AST
    Another component that translate that Go AST into TS AST
    A component responsible to write the JS AST as JS code
    Another component responsible to write the TS AST as TS code

The binding code would essentially become, as pseudo code:

```go
func main() {
  writer := fileWriter{}

  goAST := GetGoASTFromBoundStructs({}interface{&Handler{}})

  go func() {
    ast := toJavascriptAST(goAST)
    obfuscatedAST := obsfuscateJavascriptAST(ast)
    code := toJavascriptCode(jsAST)
    writer.Write(code, "Handler.js")
  }()

  go func() {
    ast := toTypescriptAST(goAST)
    obfuscatedAST := obsfuscateTypescriptAST(ast)
    code := toTypescriptCode(ast)
    writer.Write(jsCode, "Handler.d.ts")
  }()
}
```

That example doesn't take into account the model generation, UPX and all the nitty gritty details. It's just to convey the idea.

Such design definitely will add more loop interaction but I believe the testability, extensibility (adding specific processing, features, etc) and ability to replace each component will increase dramatically.

Also, this is just a draft thought as I haven't looked in the details. I think I saw that part of the existing code is used for Wails runtime to call the methods and all, so it really needs more thoughts and design.

I am of course open to critics :)

**Comment by ValentinTrinque** [comment]
I will investigate deeper.

**Comment by leaanthony** [comment]
This has been worked on extensively for v3. Closing for now.
