### ISSUE TITLE
Out of the box logs to file

### ISSUE THREAD

**Issue by avengerweb** [wailsapp/wails#1957]
### Is your feature request related to a problem? Please describe.

Right now in order to have logs in file I need to implement own logger. However, logs for most user apps (especially on first stages like beta) is must to have.

### Describe the solution you'd like

Add option to write logs into file in addition to console (user directory or directory from where app was launched) with some basic rotation by size.

**Comment by misitebao** [comment]
Wails supports [custom loggers](https://wails.io/docs/reference/runtime/log#using-a-custom-logger), you just need to implement the `Logger` interface according to the documentation, and pass in a custom struct instance [here](https://wails.io/docs/reference/options#logger).
