### ISSUE TITLE
bash: wails: command not found error on raspberry pi 4

### ISSUE THREAD

**Issue by learncodingforweb** [wailsapp/wails#1975]
### Description

After following installation process as mention on https://wails.io/docs/gettingstarted/installation/ on raspberry pi 4. 

console does not display any error after **go install github.com/wailsapp/wails/v2/cmd/wails@latest**. 
if running wails command on terminal, getting **bash: wails: command not found**

**go version**
go version go1.19.2 linux/arm

**raspberry pi 4 os details**
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### To Reproduce

1 raspberry pi 4 install **10 (buster)** OS
2 install go version 1.19.2
3 go install github.com/wailsapp/wails/v2/cmd/wails@latest
4 type wails doctor on command line terminal
    got **bash: wails: command not found**

### Expected behaviour

Wails should work on raspberry pi 4

### System Details

```shell
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

I suspect go/bin might be missing in your path.

https://wails.io/docs/gettingstarted/installation#go
> Check "~/go/bin" is in your PATH variable: echo $PATH | grep go/bin

**Comment by learncodingforweb** [comment]
**$PATH | grep go/bin** shows

/home/camera/.config/nvm/versions/node/v16.13.2/bin:/home/camera/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:**/usr/local/go/bin**

it shows go/bin in path

**Comment by stffabi** [comment]
You are missing `~/go/bin` which is the `go/bin` folder in your `$HOME`. That's the default location where `go install` installs binaries.

**Comment by learncodingforweb** [comment]
Uninstall golang and installed on $HOME directory, After that problem get resolved, Please mention in install page of documentation to avoid such error and close this bug.

**Comment by leaanthony** [comment]
We have clear instructions on how to check your environment is set up correctly and link to the Go installation instructions which does state how to install Go properly. There was a time when they forgot to have the instructions for putting the Go binary on the path but that's been fixed. Glad you fixed your issue 👍
