### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by ZeronoFreya** [wailsapp/wails#1978]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

https://wails.io/docs/reference/runtime/events#eventsemit

```
JS: EventsEmit(ctx context, optionalData function(optionalData?: any))
```
No ctx context required

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Fixed by #1979
