### ISSUE TITLE
Add SolidJS to built-in templates

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1996]
### Is your feature request related to a problem? Please describe.

Seeing that there are some posts discussing how to use solidjs in wails, I thought we could add it to the built-in template to provide users with a minimal example of using solidjs in wails.

### Describe the solution you'd like

Add SolidJS to built-in templates.

### Additional context

I can complete this feature request.

**Comment by leaanthony** [comment]
I'm not keen on supporting anything that vite doesn't support as that's our dev server solution. The community template is available if people want to use it. If we add anything beyond vite templates then the maintenance burden is on us.

**Comment by leaanthony** [comment]
@misitebao - I do appreciate you bringing this up though.

**Comment by NinoM4ster** [comment]
> I'm not keen on supporting anything that vite doesn't support

But SolidJS uses Vite by default. How does it not support it?
