### ISSUE TITLE
Support bundle for Linux

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#2]
We need to support 'wails bundle' for Linux. Suggestions welcome (snap?).

**Comment by leaanthony** [comment]
I think we'll just use goreleaser to address this issue.

**Comment by bh90210** [comment]
There seems to be a decent amount of solutions that are all valid.

If what we are after is strictly mimic the functionality `wails build -p` offers for macos/windows
the best strategy seems to be using goreleaser with some wails generated `[desktop entry]` [ref](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)
and have native `.deb` `.rpm` files generated that will support icons on system menus.

Having said that, I think the situation is not either/or. Ideally wails should support everything from the linux universe. It is about time-energy for dev.

So here are all the options I see as worth pursuing:
1. using `.desktop` (desktop entry) in builds that produce `.deb` `.rpm` packages [goreleaser ref](https://goreleaser.com/nfpm/)
2. Snaps [ref](https://snapcraft.io/docs/creating-a-snap)
3. Flatpacks [ref](http://docs.flatpak.org/en/latest/first-build.html)
4. Appimages [ref](https://docs.appimage.org/packaging-guide/overview.html)

**Comment by bh90210** [comment]
you can check what the `-p` does [here](https://wails.app/reference/#cli)
and see it in action [here](https://wails.app/tutorials/todo.html#packaging-the-app)

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page
