### ISSUE TITLE
[windows] Go Native WebView2Loader - Feedback

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#2004]
The WebView2Loader is an essential part of the WebView2 runtime while running Wails on Windows. The loader is distributed by Microsoft as a DLL and must be loaded in order to start and use the WebView2 Runtime. It provides helper functions to determine the current version installed or to use a fixed runtime.
In order to have a Go (Single-Binary) experience the WebView2Loader.dll is embedded in the final application binary and
loaded from memory when needed.

There are several drawbacks with this approach:
- Some Anti-Virus software give a Wails Application a higher score or ban them, because the binary contains a DLL signed by Microsoft and also contains "Copyright by Microsoft" strings.
- Windows does not have the possibility to load a DLL from memory but instead always needs the DLL to be on the filesystem.
  To overcome this problem currently an awesome project written by @jchv is used [go-winloader](https://github.com/jchv/go-winloader), which makes it possible to load the library from memory.
  Some drawbacks of the loader are:
  - Some incompatibility when using CGO in the final project with a fixed runtime: https://github.com/wailsapp/wails/issues/1569
  - It heavily relies on internals how Windows loads libraries
  - Some "compatibility hacks" as mentioned [here](https://github.com/jchv/go-winloader#todo)

To overcome those drawbacks the Wails-Team started to implement a Go native WebView2Loader by porting the [OpenWebView2Loader](https://github.com/jchv/OpenWebView2Loader) (also written by @jchv :grinning:) to Go. This new loader allows us to directly interact with the WebView2 runtime straight from Go without having to load another DLL into memory.

The new loader can be activated by adding `exp_gowebview2loader` to your build tags: `wails build --tags exp_gowebview2loader`.

The loader is currently experimental, nevertheless we feel it's in a state where people are invited to try it out and
actively use it.

Please let us know your feedback or problems when using the new loader in this issue. Please also include the output of `wails doctor`.

## Tested
| Windows               | Build Version    | Platform      | Notes                                              | Status |
| ----------------- | --------------- | ----------- | ---------------------------------| ------ |
| 11 Home - 22H2  | 10.0.22621.521  | arm64       | arm64 build running native            | :white_check_mark: |
| 11 Home - 22H2  | 10.0.22621.521  | arm64       | amd64 build running in emulation | :white_check_mark: |
| 11 Home - 22H2  | 10.0.22621.521  | arm64       | x86 build running in emulation      | :white_check_mark: |
| 11 Home - 22H2  | 10.0.22621.674  | amd64      | Native build on AMD Ryzen           | :white_check_mark: |

## Status: Stable

Merged with https://github.com/wailsapp/wails/pull/1974
Released with [v2.3.0](https://github.com/wailsapp/wails/releases/tag/v2.3.0)

**Comment by leaanthony** [comment]
Just pushed a small fix to master.

**Comment by leaanthony** [comment]
Some stats:

|   Build    | Binary Size | UPX Compressed |
| --------- | ------------ | ------------------- |
| dll embedded |   8181760 | 3124736  |
| go native |  8036352 | 3099136 |

**Comment by LonglyCode** [comment]
Nice Job! My team have a web app used WebRTC technology only on a local network without SSL. Is wonderful used wails let it like a desktop app. But we need enabled 'unsafely-treat-insecure-origin-as-secure' on webview2 and setting server's IP address automatic.

**Comment by steowens** [comment]
So I just tried it out and it's a HUGE improvement.  I am now able to compile my wails app with sqlite and not have the compilation fail with the same kind of issue I reported here: https://github.com/golang/go/issues/57455#issuecomment-1364772685

**Comment by ziveni** [comment]
windows11 专业版 22621.1413   编译的exe无法运行

**Comment by onedaycodes** [comment]
windows server 2016操作系统下运行已打包的exe运行提示
![image](https://user-images.githubusercontent.com/94431788/232372522-dfe3cf01-416b-46e3-9bac-1b41efa2c3d0.png)
打包命令
wails build -clean -webview2=embed --tags exp_gowebview2loader
编译环境
OS           | Windows 10 Home
Version      | 2009 (Build: 19045)
ID           | 22H2
Go Version   | go1.18.3
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 112.0.1722.48
npm        | N/A          | Installed | 8.11.0
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

**Comment by stffabi** [comment]
@onedaycodes could you please elaborate what your issue is? This dialog is expected and normal behaviour if the WebView2 is not installed on the target machine where the application is executed.

**Comment by onedaycodes** [comment]
> 你能详细说明你的问题是什么吗？如果未在执行应用程序的目标计算机上安装 WebView2，则此对话框是预期和正常行为。
我的问题是我使用了-webview=embed参数 希望能将webview运行环境嵌入打包后的exe二进制文件中，在其他未安装webview 运行环境的系统下可以直接run

**Comment by stffabi** [comment]
> > 你能详细说明你的问题是什么吗？如果未在执行应用程序的目标计算机上安装 WebView2，则此对话框是预期和正常行为。
> > 我的问题是我使用了-webview=embed参数 希望能将webview运行环境嵌入打包后的exe二进制文件中，在其他未安装webview 运行环境的系统下可以直接run

That's expected behaviour, `embed` only embeds the bootstrapper for installation of the runtime see also [here](https://wails.io/docs/next/guides/windows/#handling-the-webview2-runtime-dependency). It does not auto-install in the background without confirmation from the user.
If you want to bundle the WebView2 Runtime with your app you need to use [Fixed Runtime](https://wails.io/docs/next/guides/windows/#fixed-version-runtime) but bundling and installing it into a folder needs to be done by yourself. Wails does not provide any help for that out of the box.

**Comment by ziveni** [comment]
> 
"Whether using the old one or not, the content cannot be displayed."

**Comment by stffabi** [comment]
> "Whether using the old one or not, the content cannot be displayed."

Could you please open a new specific issue with a reproduction guide? That would be awesome 🙏 .

This issue is only meant for feedbacks/issues with the new webview2loader, but it seems like in your case something else is the problem.

**Comment by stffabi** [comment]
The new WebView2Loader is in a stable state and feedback was overall good. So I'm going to close this issue. If someone encounters a problem with the new loader, please open a new issue with a detailed report.

**Comment by PaleGreenFILE** [comment]
hello i have problem when use the obfuscated flags ,  i have app can be write a file with data and can read it , the permission of file is set , but  when use production mode with obfuscated when try to write file its working i see the file and data is done  but the application not render the  file ,  i have a card for display information and when card is created we have a function for read the file  in dev mode is works but in prod is not displaying  
                                
          Wails Doctor          
                                

                                                                                                                                                                   
# Wails
Version | v2.8.0

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.4                                                                                                                        |
| ID           | 23E214                                                                                                                      |
| Go Version   | go1.22.1                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | arm64                                                                                                                       |
| CPU          | Apple M2 Pro                                                                                                                |
| GPU          | Chipset Model: Apple M2 Pro Type: GPU Bus: Built-In Total Number of Cores: 19 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 16GB                                                                                                                        |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2406    |
| Nodejs                    | N/A          | Installed | 21.7.0  |
| npm                       | N/A          | Installed | 10.5.0  |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Installed | v3.09   |
└─────────────────── * - Optional Dependency ────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/

 SUCCESS  Your system is ready for Wails development!
 and here my function write and read  // WriteAccountToFile writes the account information to a .dat file
func (a *App) WriteAccountToFile(name, login, password, serverIP, platform string) error {
	// Define folder path
	folderPath := filepath.Join(filepath.Dir(a.ExecutablePath), "AccountInfo")

	// Create the folder if it doesn't exist
	if err := os.MkdirAll(folderPath, 0777); err != nil {
		return fmt.Errorf("failed to create folder: %w", err)
	}

	// Construct the file path
	filePath := filepath.Join(folderPath, "account.dat")

	// Open the file in append mode, create it if it doesn't exist
	file, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		return fmt.Errorf("failed to open file for writing: %w", err)
	}
	defer file.Close()

	// Write login, password, and serverIP to file, separated by commas and followed by a newline character
	line := fmt.Sprintf("%s,%s,%s,%s,%s\n", name, login, password, serverIP, platform)
	if _, err := file.WriteString(line); err != nil {
		return fmt.Errorf("failed to write to file: %w", err)
	}

	return nil
}

// Account represents the account information
type Account struct {
	Name     string
	Login    string
	Password string
	ServerIP string
	Platform string
}

// ReadAccountsFromFile reads accounts from a .dat file in the AccountInfo folder and returns them as a slice
func (a *App) ReadAccountsFromFile() ([]Account, error) {
	var accounts []Account

	// Construct the file path
	filePath := filepath.Join(filepath.Dir(a.ExecutablePath), "AccountInfo", "account.dat")

	// Read the entire file content
	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	// Split the content by newline characters
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		// Split the line by ',' to extract login, password, and serverIP
		parts := strings.Split(line, ",")
		if len(parts) == 5 {
			account := Account{
				Name:     parts[0],
				Login:    parts[1],
				Password: parts[2],
				ServerIP: parts[3],
				Platform: parts[4],
			}
			accounts = append(accounts, account)
		}
	}

	return accounts, nil
} thanks all for your help

**Comment by youwen21** [comment]
windows10, WAR |  WebView failed to set AllowExternalDrag to false

```
                 CSSDragProperty: "--wails-draggable",
		CSSDragValue:    "drag",
		DragAndDrop: &options.DragAndDrop{
			EnableFileDrop:     true,
			DisableWebViewDrop: true,
			CSSDropProperty:    "--wails-drop-target",
			CSSDropValue:       "drop",
		},

		Windows: &windows.Options{
			WebviewIsTransparent:              true,
			WindowIsTranslucent:               true,
			BackdropType:                      windows.Mica,
			DisablePinchZoom:                  false,
			DisableWindowIcon:                 false,
			DisableFramelessWindowDecorations: false,
			WebviewUserDataPath:               "",
			WebviewBrowserPath:                "",
			Theme:                             windows.SystemDefault,
			CustomTheme: &windows.ThemeSettings{
				DarkModeTitleBar:   windows.RGB(20, 20, 20),
				DarkModeTitleText:  windows.RGB(200, 200, 200),
				DarkModeBorder:     windows.RGB(20, 0, 20),
				LightModeTitleBar:  windows.RGB(200, 200, 200),
				LightModeTitleText: windows.RGB(20, 20, 20),
				LightModeBorder:    windows.RGB(200, 200, 200),
			},
		},

```

wails build -platform=windows/amd64 -debug -s -m -o=test-amd64.exe

platform: macOS Monterey,   version 12.7.4

**Comment by GoMateoGo** [comment]
![question](https://github.com/user-attachments/assets/2f348e2d-e7d4-4726-8330-fa14e3e8abda)
The program I compiled exits after double-clicking

**Comment by barats** [comment]
> 

Same here.

Is there any update for this?

**Comment by barats** [comment]
> windows10, WAR | WebView failed to set AllowExternalDrag to false
> 
> ```
>                  CSSDragProperty: "--wails-draggable",
> 		CSSDragValue:    "drag",
> 		DragAndDrop: &options.DragAndDrop{
> 			EnableFileDrop:     true,
> 			DisableWebViewDrop: true,
> 			CSSDropProperty:    "--wails-drop-target",
> 			CSSDropValue:       "drop",
> 		},
> 
> 		Windows: &windows.Options{
> 			WebviewIsTransparent:              true,
> 			WindowIsTranslucent:               true,
> 			BackdropType:                      windows.Mica,
> 			DisablePinchZoom:                  false,
> 			DisableWindowIcon:                 false,
> 			DisableFramelessWindowDecorations: false,
> 			WebviewUserDataPath:               "",
> 			WebviewBrowserPath:                "",
> 			Theme:                             windows.SystemDefault,
> 			CustomTheme: &windows.ThemeSettings{
> 				DarkModeTitleBar:   windows.RGB(20, 20, 20),
> 				DarkModeTitleText:  windows.RGB(200, 200, 200),
> 				DarkModeBorder:     windows.RGB(20, 0, 20),
> 				LightModeTitleBar:  windows.RGB(200, 200, 200),
> 				LightModeTitleText: windows.RGB(20, 20, 20),
> 				LightModeBorder:    windows.RGB(200, 200, 200),
> 			},
> 		},
> ```
> 
> wails build -platform=windows/amd64 -debug -s -m -o=test-amd64.exe
> 
> platform: macOS Monterey, version 12.7.4

Same here.

Is there any update for this?

**Comment by xisuo67** [comment]
![image](https://github.com/user-attachments/assets/d35b9bce-037e-4a9d-b997-dce9e4d66f23)
Here is my computer information: I used `wails init -n myproject -t vue-ts` to create the project, then ran `wails dev`, but the program didn't open successfully.
>  wails build --debug --tags exp_gowebview2loader

![image](https://github.com/user-attachments/assets/67bbf7c0-726c-4e6f-b297-a2e10128ddf7)

The program I compiled exits after double-clicking
