### ISSUE TITLE
Build failed in compiling applicaton

### ISSUE THREAD

**Issue by x86cloud** [wailsapp/wails#2006]
### Description

build failed 

### To Reproduce

wails build
Wails CLI v2.1.0

App Type:               desktop
Platforms:              linux/arm64
Compiler:               /usr/local/bin/go
Skip Bindings:          false
Build Mode:             Production
Obfuscated:             false
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []
Race Detector:          false

Building target: linux/arm64
----------------------------
  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/desktop/linux
../go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/gtk.go:26:2: could not determine kind of name for C.free
Error: exit status 2

ERROR: exit status 2

### Expected behaviour

build success

### System Details

```shell
wails doctor
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...^[[ADone.

System
------
OS:             Kylin
Version:        v10
ID:             kylin
Go Version:     go1.19.2
Platform:       linux
Architecture:   arm64

Wails
------
Version:                v2.1.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Installed       18.09.7
gcc             build-essential         Installed       5.4.0
libgtk-3        libgtk-3-dev            Installed       3.18.9-1kord4k7
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.20.5-0kord0.16.04.1k4
npm             npm                     Installed       8.19.2
*nsis           nsis                    Installed       v2.50-1kord
pkg-config      pkg-config              Installed       0.28

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by Dstonecool** [comment]
try to update your gcc. I got  the same error on ubuntu16.04 but no error on ubuntu18.04

**Comment by leaanthony** [comment]
@x86cloud any updates?

**Comment by x86cloud** [comment]
> @x86cloud any updates?
The problem seems to disappear when I change the development environment to Ubuntu.

**Comment by leaanthony** [comment]
I'll close then. Good work
