### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Zhangft-M** [wailsapp/wails#2008]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

when I install , there has a error :
..\..\Go\pkg\mod\github.com\wailsapp\wails\v2@v2.1.0\pkg\templates\templates.go:28:12: pattern all:ides/*: no matching files found

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Thanks for reporting this.l 👍

**Comment by stffabi** [comment]
Thanks for bringing this up.

What version of Go are you using? Could it be that you are using Go 1.17 or older? This could lead to the error message mentioned.

Minimum requirement for v2.1 is Go 1.18+, please see also [dependencies](https://wails.io/docs/gettingstarted/installation#dependencies) for up to date requirements.

**Comment by Micah-Z** [comment]
I see,thanks
