### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#201]
at the moment wails only supports npm.
it would be great if we could support yarn usage too! 

the most obvious solution I see is during the `wails setup` step users also is asked preferred technology (npm/yarn), and then whenever user creates a new project `wails init` an option to bypass the default value set in previous step.

Thoughts?

**Comment by leaanthony** [comment]
My thoughts on this is that if you are using templates, you shouldn't care. We can only support known configurations. Is there a use case for replacing npm with yarn in existing templates?

**Comment by bh90210** [comment]
let's keep `yarn` "officially" not supported for now. If at some point in the future we grow (in devs) and can afford it time-wise let's re-think.
in the mean time I agree to move this issue to a greater FAQ section.
I propose to have a guide in the docs describing the steps needed to make a swift from npm to yarn after a new project is created, for the sake of completeness.  
when the new website is ready I can write the guide..

so maybe close the ticket for now?

**Comment by bh90210** [comment]
closing for now, let's re-open in the future if the need arise..
