### ISSUE TITLE
Stuck in  Executing: go mod tidy

### ISSUE THREAD

**Issue by Web3codexio** [wailsapp/wails#2010]
### Description

When I run "wails dev",its Stuck in Executing: go mod tidy for a long time!

### To Reproduce

1、import alot of module packages
2、run "wails dev"

### Expected behaviour

run "wails dev" successfuly

### Screenshots

![image](https://user-images.githubusercontent.com/50604703/197410715-9f2d35c4-00a1-48ad-a81b-7c2ebc44d995.png)

### Attempted Fixes

when i inited the project ,the structure of the project is still simple,its works well at first!but with the more package i use in the project,it suddenly occur a problem with the "wails dev",i  tried to google the same inssue but theres nothing relative to this!help u guys can help me solve it!tks alot!!!!!!!!

### System Details

```shell
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...Done.

System                             
------                             
OS:             Windows 10 Pro     
Version:        2009 (Build: 19043)
ID:             21H1               
Go Version:     go1.18.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       106.0.1370.52
npm             N/A             Installed       8.15.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment]
What happens if you run `go mod tidy` manually?

**Comment by chuyijia** [comment]
> What happens if you run `go mod tidy` manually?

it works well
![image](https://user-images.githubusercontent.com/50604703/197476665-76858b6d-a678-440b-9e27-8afd1b6b4088.png)

**Comment by chuyijia** [comment]
![image](https://user-images.githubusercontent.com/50604703/197486587-8b70fdbc-34d3-4aa9-8a02-1b8f41336fd4.png)

just like wails dev,it got stuck too

**Comment by leaanthony** [comment]
Without any more information, I'm not sure what to suggest

**Comment by Schmille** [comment]
Adding my two cents:
I came across a similar error and decided to investigate further upon seeing this issue.
@chuyijia, do you have any long blocking code in your main function? 

In my case I was running a command using exec.Cmd that never completed, thus creating the described behavior.

**Comment by Hamcha** [comment]
Was having the same issue, can confirm https://github.com/wailsapp/wails/issues/2010#issuecomment-1298325485 was right on the money for me, I was starting goroutines with http servers and other long running tasks in main() and it made `wails dev` get stuck at the same steps as chuyijia. I wasn't aware that was an issue, I moved most of the login to `app.startup` and now it works fine!
