### ISSUE TITLE
Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by zzj-custom** [wailsapp/wails#2019]
### Description

使用wails+vite+vuetify搭建的环境，使用layout布局的使用，在谷歌浏览器的devServer地址是可以正常显示，但是在wails控制台里面提示【Can't find variable: ResizeObserver】这样的错误。如果去掉vuetify里面的v-layout标签，只保留页面的数据，那么就正常显示。

### To Reproduce

1. yarn build 
2. wails dev

### Expected behaviour

```vue
<!-- layout/index.vue -->
<template>
  <v-layout>
    <Header></Header>

    <Navigation></Navigation>

    <v-main>
      <router-view></router-view>
    </v-main>
  </v-layout>
</template>

<script lang="ts" setup>
import Navigation from "./navigation.vue";
import Header from "./header.vue";
</script>
```

```ts
// router/index.ts
import { createRouter, createWebHistory, RouteRecordRaw } from "vue-router";
import VLayout from '../layout/index.vue'

const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    component: VLayout,
    children:[{
      path: "/images",
      name:"images",
      component: () => import("../views/images/index.vue")
    }]
  }
];

const router = createRouter({
  // history: createWebHistory(process.env.BASE_URL),
  history: createWebHistory(),
  routes,
});

export default router;
```

### System Details

```shell
xcode command line tools        N/A             Installed       2370
npm                             N/A             Installed       8.15.0
*upx                            N/A             Installed       upx 3.96
*nsis                           N/A             Installed       v3.08
```

**Comment by zzj-custom** [comment]
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        10.15.1
ID:             19B88
Go Version:     go1.18.3
Platform:       darwin
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2370
npm                             N/A             Installed       8.15.0
*upx                            N/A             Installed       upx 3.96
*nsis                           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!

**Comment by misitebao** [comment]
@zzj-custom 
It is recommended to use hash routing

**Comment by leaanthony** [comment]
Is this a Wails bug?

**Comment by leaanthony** [comment]
Closing due to lack of response. Feel free to open if this is still an issue for you 👍
