### ISSUE TITLE
runtime.WindowGetSize returns the scaled size when the windows screen set to scale

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#2023]
### Description

runtime.WindowGetSize returns the scaled size when the windows screen set to scale

### To Reproduce

![word-image](https://user-images.githubusercontent.com/963880/198887042-53efb4a4-7019-4d1c-a316-3d6db1961962.png)

``` go
func main() {
	app := NewApp()

	go func() {
		for {
			time.Sleep(time.Second)
			if app.ctx == nil {
				continue
			}
			w, h := runtime.WindowGetSize(app.ctx)
			fmt.Println("runtime.WindowGetSize return", w, h)
		}
	}()

	// set Window Size to 1000, 500
	w, h := 1000, 500
	err := wails.Run(&options.App{
		Width:     w,
		Height:    h,
		MinWidth:  w,
		MinHeight: h,
		Assets:    assets,
		OnStartup: app.startup,
		Bind: []interface{}{
			app,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}
```

### Expected behaviour

WindowGetSize return w,h matched WindowSetSize whatever screen was scaled or not

### Screenshots

![Code_T6rRGETxPn](https://user-images.githubusercontent.com/963880/198887153-e214c9d9-8f74-45b0-96a1-d6fe97c1ebf2.png)

### System Details

```shell
everything is ok
```

**Comment by leaanthony** [comment]
Thanks for reporting this @wantg. Are you willing to make a PR for this? Thanks.

**Comment by wantg** [comment]
> Thanks for reporting this @wantg. Are you willing to make a PR for this? Thanks.

I need to find a stable source of income first.

**Comment by stffabi** [comment]
A fix for this has been merged and will be part of the next release.

Please feel free to reopen if you have any further issues with this.
