### ISSUE TITLE
Trigger reload only when there is an actual delta in the backend code

### ISSUE THREAD

**Issue by slo-loris** [wailsapp/wails#2032]
### Is your feature request related to a problem? Please describe.

Currently, the rebuild behavior is, whenever a backend file is saved irrespective of whether there is an actual delta or not, a backend rebuild is getting triggered.   

### Describe the solution you'd like

Trigger rebuild only when there is an actual delta in the backend file.

**Comment by leaanthony** [comment]
Thanks for opening this. Are you suggesting we track eg the md5 of each file in the project then trigger a rebuild only if the file saved has been changed? How often do you see a file saved with no change? Is there a common scenario for this that perhaps needs a different solution?

**Comment by Slo-Loris** [comment]
Coming from a background where I use excel predominantly (Accountant by profession) and I usually have this tendency to press ctrl + s irrespective of whether or not there is really a delta..😅 As you suggested checking for a md5 change might be the way forward for this request. When I was using JS, I was using ESBuild for transpiling and bundling TS code to JS. In ESBuild, the rebuild behaviour is that, the rebuild gets triggered only when there is an actual change. Not sure as to how this is implemented tn ESBuild. I will check and revert on that shortly.

**Comment by leaanthony** [comment]
I'm confused as to whether you are requesting frontend or backend files to be checked.

**Comment by Slo-Loris** [comment]
> I'm confused as to whether you are requesting frontend or backend files to be checked. 

Backend. 

Just compared ESbuild for the way it works/ its behaviour. Apologies for making the comparison ambiguous.

**Comment by leaanthony** [comment]
Thanks for clarifying.

**Comment by hkeide** [comment]
May I also suggest that _test.go files are ignored?

**Comment by leaanthony** [comment]
This is fully configurable in v3 so closing this for now
