### ISSUE TITLE
Micro Context Menu cann't disable when selected text in webview2

### ISSUE THREAD

**Issue by sufu777** [wailsapp/wails#2036]
### Description

![image](https://user-images.githubusercontent.com/49868196/199540271-60e62d8c-fbf3-43e7-9141-892c817eaca8.png)
As picture shows, when I select text in Wails App, the Micro Context Menu from webview2 is showing here and I can't find a way to close it. I open the Edge Broswer and do the same operation in any document, it shows again. So I comfirm it is a feature from webview, and I want close it so that Wails App is not like webpage. just like blow picture:
![image](https://user-images.githubusercontent.com/49868196/199542265-624d269a-41c3-479e-9a9f-648829b342d3.png)
And, I find way to close it in Edge Broswer Setting like this, just close the button :
![image](https://user-images.githubusercontent.com/49868196/199543383-3efa5d09-6f5d-4570-9e2c-0dfd64f579b0.png)

sorry abount my poor english, Looking forward to your reply ! 😁

### To Reproduce

1. Run Wails Demo App
2. Select Text in ducument

### Expected behaviour

No Micro Context Menu Shows

### System Details

```shell
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22621)
ID:             22H2
Go Version:     go1.19.2
Platform:       windows
Architecture:   amd64

Wails
* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

### Additional context

My operating system is windows 11 pro, I don't know why it is recognized as Windows 10 Pro.
Edge Version 107.0.1418.26

**Comment by leaanthony** [comment]
This used to only show in Dev mode. Are you saying it's there in a production build?
