### ISSUE TITLE
Get pixel from rendered UI

### ISSUE THREAD

**Issue by txbrown** [wailsapp/wails#204]
Hi. This not really an issue but more of a question.

Great job on building this tool. It has a lot of potential as it is.
However, my use case is to be able to write react and take the rendered pixels into an hardware device LCD. I dont want the webview visible or have the option to toggle it.  Do you think this is possible with this tool or possibly am I going the wrong way about this?

Thanks beforehand.

**Comment by leaanthony** [comment]
It sounds like you want a hardware renderer :-) I don't believe that's something we could support internally but would be happy to answer any questions you have if you attempt it. Good luck! 🚀

**Comment by codenakama** [comment]
@leaanthony thanks for replying. I have achieved this before using web-usb api, but it only works in chrome. I wanted to build the UI with wails, not have it visible to the user but get pixels from some sort of canvas or html main element and stream that into the device. the streaming and pixel conversion part is already solved, I just need a way of getting the actual pixels with wails if possible. 
Would wails expose such api? I am happy to contribute if you let me know this is a possibility.
