### ISSUE TITLE
Page is lost in frameless window when unminimise

### ISSUE THREAD

**Issue by RyoTagami** [wailsapp/wails#2042]
### Description

When using frameless window,  minimizing while maximized and then unminimizing will cause the page to be lost.
It remains white over time.
Unmaximize to return to the original state.
This does not occur in normal (without frameless) windows.

May be related to #1319.

### To Reproduce

1. Create a project with a vanilla template.
2. Rewrite 2 files.

main.go
```go
package main

import (
	"embed"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
)

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	app := NewApp()

	wails.Run(&options.App{
		Title:     "test",
		Width:     1024,
		Height:    768,
		Frameless: true,
		Assets:    assets,
		OnStartup: app.startup,
		Bind: []interface{}{
			app,
		},
	})
}
```

main.js
```js
import "./style.css";
import "./app.css";

import logo from "./assets/images/logo-universal.png";
import { WindowToggleMaximise, WindowMinimise } from "../wailsjs/runtime";

document.querySelector("#app").innerHTML = `
    <img id="logo" class="logo">
    <button style="font-size: 30px" class="bth" onclick="toggleMaximise()">WindowToggleMaximise</button>
    <button style="font-size: 30px" class="bth" onclick="minimise()">WindowMinimise</button>
`;
document.getElementById("logo").src = logo;

window.toggleMaximise = function () {
  WindowToggleMaximise();
};

window.minimise = function () {
  WindowMinimise();
};
```

3. Launch the application, maximize it, then minimize it.

### Expected behaviour

The display will be the same as before it was minimized.

### Screenshots

https://user-images.githubusercontent.com/9672589/199640654-fb465870-ee04-4409-92a5-a73716e68735.mp4

### System Details

```shell
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.19.2
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       107.0.1418.26
npm             N/A             Installed       8.1.4
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue. 

We got already another similar report with #1941. Unfortunately I'm unable to reproduce it here on my Windows 11 machine. It seems like both of you are using the same Windows 10 build 19044, so that might be Windows version specific issue. The author over there mentioned it only happens sporadically and only started happening after having updated to 2.0.0 but couldn't tell when it started.

Would it be possible for you to try out some older versions of Wails, so we could narrow that down?

**Comment by stffabi** [comment]
Do you use a multi monitor setup? I was able to reproduce it there, when the app has been started on the secondary monitor.

**Comment by stffabi** [comment]
I've found a similar report on the Webview2Feedback repo https://github.com/MicrosoftEdge/WebView2Feedback/issues/2549 and the workaround there fixed it in my case.

I've put up PR #2043 with that fix, would it be possible for you to give it a try?

You can use [this guide](https://wails.io/docs/next/guides/bleeding-edge#testing-a-pr) to test the PR.

**Comment by RyoTagami** [comment]
@stffabi 

> Do you use a multi monitor setup?

Yes!

> I've put up PR https://github.com/wailsapp/wails/pull/2043 with that fix, would it be possible for you to give it a try?

I have confirmed that the problem has been resolved by trying your PR.
Thank you!

**Comment by stffabi** [comment]
Awesome thanks so much for testing it 👍
