### ISSUE TITLE
"zsh: command not found: wails" on macOS

### ISSUE THREAD

**Issue by veniplex** [wailsapp/wails#2046]
### Description

The `wails` command is not found on macOS.

### To Reproduce

Do the installation steps described at https://wails.io/docs/gettingstarted/installation and https://go.dev/doc/install.

### Expected behaviour

The command should be available.

### Attempted Fixes

I tried to add the ~/go/bin path to the $PATH env, following this instruction: https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/#.Uydjga1dXDg

### System Details

`wails doctor` is not working.

### Additional context

`echo $PATH` outputs the correct paths: [...]`:~/go/bin:/usr/local/go/bin:`[...].
I installed NodeJS, Go and everything else needed. `go install github.com/wailsapp/wails/v2/cmd/wails@latest` is working without any problems.

**Comment by BlazingFire007** [comment]
I'm also having this issue on my macbook just now. But I realized i was keeping my projects in `~/go` so it was causing issues. After renaming the folder and reinstalling it worked like a charm

**Comment by leaanthony** [comment]
Closing this as it's not a Wails issue but a Go setup issue 👍

**Comment by veniplex** [comment]
> I'm also having this issue on my macbook just now. But I realized i was keeping my projects in `~/go` so it was causing issues. After renaming the folder and reinstalling it worked like a charm

Can you explain this a bit further? My projects are stored on the desktop. I tried to reinstall wails, but this does not work for me.

**Comment by qrcdigital** [comment]
On my MacOs Ventura: 
Installed go =>  it is installed to "/usr/local/go"
Installed wails => it is installed in "~go/bin/wails"
Result: "zsh: command not found: wails"
QuickFix for me:  sudo cp ~/go/bin/wails /usr/local/go/bin/

**Comment by leaanthony** [comment]
~go/bin should be in your path as per the go installation instructions.

**Comment by jcucuzza** [comment]
`
 export PATH=$PATH:~/go/bin
`
just add the wails path to path variable. :wink:

**Comment by nurfaizfoat** [comment]
Add a PATH modifier in your ~/.zshrc like so, so zsh recognizes Wails installation directory
# Go Path Modules Configuration
alias wails='/home/{user}/go/bin/wails'

**Comment by naecoo** [comment]
> `export PATH=$PATH:~/go/bin` just add the wails path to path variable. 😉
you save my time, thanks
