### ISSUE TITLE
`wails dev` downgrades wails in go.mod

### ISSUE THREAD

**Issue by mholt** [wailsapp/wails#2057]
### Description

`wails dev` is downgrading wails when running `go mod tidy` (or `go get`? but it's during the output that says running `go mod tidy`), causing compilation to fail.

I think this happens if go.mod is using a newer version than the latest tag (`@latest`), even when the CLI is also built using the same commit that is newer than the latest tag.

### To Reproduce

I am using the latest commit on master because of some recent changes that were merged in that my program relies on.

I cloned wails locally, changed to `v2/cmd/wails` and ran `go install`. I confirmed that `wails doctor` says that the latest commit was built:

```
Wails
------
Version:                v2.1.0
Revision:               928bc75602bb1302ed211d5b08b902c58236192a
Modified:               false
...
```

and then I updated my program's go.mod file to use the same  commit (`go get github.com/wailsapp/wails/v2@928...` (or `@master` at the time).

But curiously, I noticed that my go.mod file was being modified to revert the version of wails to v2.1.0. This causes a compile error because my code requires the latest changes.

I suspect this function (or something around here) is culprit:

https://github.com/wailsapp/wails/blob/55f76a291bc5ee5c92bdedbc6c05c4f4400b85b3/v2/internal/gomod/gomod.go#L86

### Expected behaviour

`wails dev` can run `go mod tidy` and `go get`, but it shouldn't change go.mod if the CLI and code base match, even if they're not on a tagged release.

### Attempted Fixes

I can work around this temporarily by adding a `replace` to my go.mod that points to my locally-cloned copy of the repo.

### System Details

```shell
(see above)
```

### Additional context

Thanks again for Wails!!

**Comment by OlegGulevskyy** [comment]
Thanks for detailed explanation, I am gonna try to repro on my end and see if I can fix it :)
If I manage to fix it, I will send a PR through

**Comment by OlegGulevskyy** [comment]
Sorry for the delay guys, got busy with some stuff
I had some time to check this today, and I am surprised to say that suggested versions by @leaanthony  is actually not being picked up by this.
I tested with this version here:
https://github.com/wailsapp/wails/commit/3474d4e1e1ecc9cc3051a2fd8cb7c8836276d07f

Whenever commit is set - it is not overwritten
Whenever `X.X.X-beta.` is set, it is overwritten to the latest - `2.2.0`
<img width="856" alt="image" src="https://user-images.githubusercontent.com/43781031/206309163-38944cee-c465-4a7f-ba90-66d65db0a89a.png">

Frankly I am surprised as to why, but if it works - it works 🤷

**Comment by stffabi** [comment]
The PR has been merged and will be part of the next release.
