### ISSUE TITLE
Automatically open DevTools in wails dev mode

### ISSUE THREAD

**Issue by TTSKarlsson** [wailsapp/wails#2059]
### Is your feature request related to a problem? Please describe.

I can't find an easy way to open the DevTools.

### Describe the solution you'd like

`EnableDevTools bool` would be nice in in the `wails.Run` `Options`.

### Describe alternatives you've considered

I've tried pressing F12, ctrl+shift+K, ctrl+shift+I, all which normally opens DevTools in browsers, but not in Wails.

I found that I can right click and inspect element to open DevTools, but it opens the inspect view by default so it's not an easy way to open the DevTools console after every reload.

### Additional context

If there are some undocumented way of doing this, I would be happy to know. Also, I love this framework! Thanks for working so hard for us!

**Comment by leaanthony** [comment]
If you can figure out how to do that on all 3 platforms I'd happily accept a PR.

**Comment by wantg** [comment]
> If you can figure out how to do that on all 3 platforms I'd happily accept a PR.

It is precisely because Wails is easy to use and can help many people that such questions arise.

**Comment by leaanthony** [comment]
Yeah, it's great. Need more contributors 😉

**Comment by stffabi** [comment]
I have some code snippets ready to get it working on all 3 platforms. Windows and Linux is pretty straight forward. On macOS it involves calling some private APIs. That shouldn't be a problem as long as we make sure a production build doesn't contain that code and only a dev build.

Wondering where this option should be put. We currently have no debug options on `options.App` so I would see that somewhere else. Maybe a config option in `wails.json`, opinions?

**Comment by stffabi** [comment]
Another question that arises, should the option also be taken into account when using 'wails build --debug'?

**Comment by leaanthony** [comment]
I think it's ok to have the option in `options.App` and just drop it in prod builds.

**Comment by stffabi** [comment]
Then we should probably put it into a `DebugOptions` struct instead of directly onto `options.App`, to be prepared for additional options in the future.

**Comment by stffabi** [comment]
I've pushed PR #2080 which adds this new option. @TTSKarlsson would it be possible for you to test it? That would be awesome. Please use [this guide](https://wails.io/docs/next/guides/bleeding-edge) for testing PRs.

**Comment by TTSKarlsson** [comment]
Sure, I'll check it out tomorrow EU time!

**Comment by TTSKarlsson** [comment]
Fantastic work 👍

Tested on WIn11, `OpenInspectorOnStartup: true` opens DevTools in `wails dev` and `false` does not. No leakage to `wails build`.

One small confusion:
```go
Debug: options.Debug{ ... }
```
breaks the earlier 'convention' to use pointers for the inner structs as with
```
AssetServer: &assetserver.Options{ ... }
Windows: &windows.Options { ... }
```

This PR is a great improvement to convenience during development! Can't thank you enough! 🤗

**Comment by stffabi** [comment]
Awesome thanks so much for testing 🙏 .

> breaks the earlier 'convention' to use pointers for the inner structs as with
Yeah, @leaanthony  and I had a discussion about using non-pointer structs in another PR, where the consensus was to use non-pointer.
What do you think @leaanthony, should we use a pointer again?

**Comment by leaanthony** [comment]
I'd only use a pointer where it is optional. It makes no sense that this would be optional so it's fine by me.
