### ISSUE TITLE
`wails doctor` macOS recommends a Windows dependency

### ISSUE THREAD

**Issue by SheetJSDev** [wailsapp/wails#2064]
### Description

`wails doctor` on an Intel Mac (`darwin` / `amd64`) recommends NSIS.  Relevant lines:

```
Wails CLI v2.0.0-beta.44.2

Dependency			Package Name	Status		Version
----------			------------	------		-------
*nsis  				N/A 		Available 	

Diagnosis
---------
  - nsis : Available at https://nsis.sourceforge.io/Download
```

The linked page has a "Download" link for an exe file for Windows.

Looking at the home page https://nsis.sourceforge.io/Main_Page :

> NSIS (Nullsoft Scriptable Install System) is a professional open source system to create Windows installers.

Is NSIS a Windows-only dependency?  If it is, then `wails doctor` should not check for NSIS support.  If macOS does support NSIS, then `wails doctor` should link to a page that actually references the macOS version (maybe a docs page with platform-specific download links?)

### To Reproduce

run `wails doctor`

### Expected behaviour

`wails doctor` should recommend platform-relevant dependencies

### System Details

```shell
OS:		MacOS
Go Version:	go1.18.4
Platform:	darwin
Architecture:	amd64
```
```


### Additional context

_No response_

**Comment by leaanthony** [comment]
This is intended. You can install NSIS tools on Mac to package up your cross compiled windows app 👍

**Comment by SheetJSDev** [comment]
There are three points of confusion here:

1) (code) `wails doctor` really should point to https://wails.io/docs/guides/windows-installer since it both explains the context (generating Windows installers) and includes the platform-specific steps.  Relevant line https://github.com/wailsapp/wails/blob/master/v2/internal/system/system.go#L94

2) (docs) NSIS should be mentioned in "Optional Dependencies" https://wails.io/docs/gettingstarted/installation#optional-dependencies

3) (search) searching for nsis in the wails docs points to the changelog, not the actual page:

<img width="890" alt="Screen Shot 2022-11-08 at 2 52 14 PM" src="https://user-images.githubusercontent.com/6070939/200661877-12332dbb-6410-43dd-9def-9cb746a54484.png">

**Comment by leaanthony** [comment]
There's definitely some things we can do here 👍

**Comment by stffabi** [comment]
The PR with improvements has been merged. So I think we could close this issue.
