### ISSUE TITLE
MacOSX Top Menu Tray

### ISSUE THREAD

**Issue by matt9mg** [wailsapp/wails#2071]
### Is your feature request related to a problem? Please describe.

Top Menu Tray is not visible when navigating away from app

![Uploading Screenshot 2022-11-09 at 15.11.06.png…]()

### Describe the solution you'd like

It would be fantastic to have the ability to have the top menu tray visible or interactive like the docker mac osx app as an example where this is permanently available.

<img width="264" alt="Screenshot 2022-11-09 at 15 12 23" src="https://user-images.githubusercontent.com/8473296/200867644-5fe7a115-f295-493b-b47b-29a820e5e846.png">

**Comment by leaanthony** [comment]
We don't currently support tray menus in Mac.... 🤔

**Comment by matt9mg** [comment]
Would it be at all possible to request it as a feature?

Love using the framework and would see it as a real enhancement to thsi great offering :)

**Comment by leaanthony** [comment]
Duplicate #1521

**Comment by matt9mg** [comment]
Ah cool it already requested thanks for linking the PR 👍
