### ISSUE TITLE
EventsOn callback function calls itself multiple times depending on how deep in the project it is being called.

### ISSUE THREAD

**Issue by kuchaow** [wailsapp/wails#2072]
### Description

I'm emitting an event from app.go with the intention of sending a message and then console logging it on the frontend, like this: 

Golang: 
```
func (a *App) GetTokenName(tokenAddress string) {
	runtime.EventsEmit(a.ctx, "hello", "message")
}
```
Javascript: 
```
EventsOn('hello', function(optionalData?: any) {
  console.log(optionalData)
})
```
The problem is that the callback function is being called 10 times, I tried to call it from my app.tsx file and then it was called 2 times, which makes me belive that the amount of times the callback is called depends on how deep in the stack its being called.

### To Reproduce

1.- Emit an event from the app.go file with a message you want to console.log on the frontend.
2.- Console.log the message with callback called in a file deep in you project.

### Expected behaviour

I expect the callback to be called only once.

### Screenshots

![Captura de Pantalla 2022-11-09 a la(s) 11 12 33](https://user-images.githubusercontent.com/100165715/200920292-5f56ed31-7ef0-481c-a95a-d55f0fc23acc.png)

### Attempted Fixes

Like I mentioned, I called it from a different parts of my app and it got called different amounts of times, not sure what else to do.

### System Details

```shell
System
------
OS:             MacOS
Version:        12.5
ID:             21G72
Go Version:     go1.19.3
Platform:       darwin
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2395
npm                             N/A             Installed       8.4.1
*upx                            N/A             Installed       upx 3.96
*nsis                           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

### Additional context

Thank you for taking the time to read this :)

**Comment by degengalahad** [comment]
Ok it just started to work fine I don't know why, maybe restarting VsCode fixes it.

**Comment by degengalahad** [comment]
Oh it seems like it happens because I set eventson inside a functional react component, when I call it at the top level everything is good.

**Comment by degengalahad** [comment]
Which is still a problem kek, so I'll reopen the issue looking for a solution.

**Comment by leaanthony** [comment]
This isn't a Wails bug though is it? Can you reproduce it with the default templates?

**Comment by degengalahad** [comment]
I'm using the wails react-typescript template.

**Comment by degengalahad** [comment]
But yeah I guess it can't be called a wails specific bug, more like something that happens with react and wails, is that considered a wails bug?

**Comment by leaanthony** [comment]
Sounds like an application error involving recursion. Please feel free to reopen if you can show that the event methods aren't working as expected 👍

**Comment by degengalahad** [comment]
Yep this wasn't a wails error, it was a react events listener error, the event should be listened to like this: 
```
useEffect(() => {
    EventsOn('hello', function(optionalData?: any) {
      console.log(optionalData)
    })
    return () => EventsOff('hello')
  }, [])
```
That way it is only called once, hope it is useful to someone.

**Comment by leaanthony** [comment]
We could potentially add that to a react guide. Thoughts?

**Comment by onattech** [comment]
I think you definitely should. It took me a while to figure out how to import that EventsOn and EventsOff functions. In case anyone wondering, 
```jsx
import { EventsOn, EventsOff } from '../../../wailsjs/runtime';
```

**Comment by matronator** [comment]
> We could potentially add that to a react guide. Thoughts?

Definitely, I came upon this issue as well and it took me quite a while to fix, using a similar approach like @degengalahad above. Mine looked like this:

```ts
useEffect(() => {
    EventsOff('onSaveFile');
    EventsOff('onLoadFile');
    EventsOn('onSaveFile', () => handleOnSaveFile());
    EventsOn('onLoadFile', () => handleOnLoadFile());
}, [template]);
```

Otherwise the events would get called with each re-render.

**Comment by txbrown** [comment]
I still face this issue even though I am cleaning up the effect so I don't why this happens.

Any pointers?

```ts
  useEffect(() => {
    const cancelConnectedDevices = EventsOn(
      'connected_devices',
      (devices: MIDIDevice[]) => {
        const midiDevices = Object.keys(devices).map<MIDIDevice>((name) => ({
          Name: name,
          Manufacturer: 'Unknown',
          DeviceID: name,
        }));

        updateMIDIDevices(midiDevices);
      }
    );

    const cancelMidiMessages = EventsOn(
      'midi_message',
      (message: MIDIMessage) => {
        console.log("new messages")
        setMidiMessages((messages) => [...messages, message]);
      }
    );

    return () => {
      cancelConnectedDevices();
      cancelMidiMessages();
    };
  });
  ```

**Comment by leaanthony** [comment]
Hey @txbrown 👋 You might have better luck asking on discord as there's more active users there and react is covered a lot.

**Comment by txbrown** [comment]
@leaanthony aaah thanks so much!
