### ISSUE TITLE
Configure vite import alias @ by default

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#2084]
### Discussed in https://github.com/wailsapp/wails/discussions/2074

<div type='discussions-op-text'>

<sup>Originally posted by **tonytony2020** November 10, 2022</sup>
Importing components via `@` alias is very common and convenient in applications based on React and Vue frameworks.

In many cases `@` points to the source root directory, making import references in multiple or deep directories very clear

     imoprt '../../components/foo.vue'

vs

    import '@/components/foo.vue'

This configuration option is added by default in templates, making wails templates out-of-the-box and easier to use.

see also 
 - https://vitejs.dev/config/shared-options.html#resolve-alias
 - https://stackoverflow.com/questions/42749973/what-does-the-mean-inside-an-import-path?rq=1

pr https://github.com/wailsapp/wails/pull/2069</div>

**Comment by misitebao** [comment]
This is the writing method recommended by vue for a long time. 

The vue project generated with the latest version of vite also has this writing method by default. I think it can be added to the default template.

**Comment by misitebao** [comment]
@tonytony2020 Will you follow up on this question?

**Comment by leaanthony** [comment]
I'll review this tonight. I was concerned because the templates we use are basically stock Vite templates and I couldn't understand why they didn't use this already if it was so widely used.

**Comment by misitebao** [comment]
@leaanthony 
I think this Issue can be closed, we only need to maintain the most basic templates according to Vite, and the wording mentioned in this question originally came from the usage habits in the project generated by `vue-cli`, and was later extended to `create-vue `, this style of writing is indeed a habit inherited by Vue developers, but I don’t recommend adding it here, because it will bring us an additional maintenance burden, unless Vite builds it in, what do you think?
