### ISSUE TITLE
Allow Custom Templates

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#209]
It would be great if we could allow 3rd party templates. Example:

```
wails init -t github.com/awesomeuser/mytemplate
```

**Comment by Vaelatern** [comment]
I'd love to do a leiningen cljs template!

**Comment by leaanthony** [comment]
That would be awesome

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page
