### ISSUE TITLE
[linux] Can play audio in wails dev but not in wails build

### ISSUE THREAD

**Issue by cvilsmeier** [wailsapp/wails#2090]
### Description

My wails app must play audio when user clicks a 'play' button. I'm using the following code for setup:

    import alertMp3 from './assets/sounds/alert.mp3';
    let audio = new Audio(alertMp3);

and later, to actually starting the audio:

    audio.play();

The thing is working perfectly well when I use

    wails dev

but the sound could not be loaded (and therefore not played) when using

    wails build

I've created a small sample project for reproducing the error: https://github.com/cvilsmeier/pino

### To Reproduce

1. git clone https://github.com/cvilsmeier/pino
2. cd pino
3. wails dev
4. wails build && build/bin/pino

### Expected behaviour

A sound must be playing both in `wails dev` and in `wails build`

### Attempted Fixes

I've tried it with data URLs, and that works:
Instead of my setup code 

     import alertMp3 from './assets/sounds/alert.mp3';
     let audio = new Audio(alertMp3);

I'm using this code:

    let audio = new Audio("data:audio/mpeg;base64, //uQxAAAAAAAAAA...(long data string)");

Then the audio is loaded and played correctly.

### System Details

```shell
Wails CLI v2.2.0

    Scanning system - Please wait (this may take a long time)...Done.

    System
    ------
    OS:		Debian GNU/Linux
    Version: 	11
    ID:		debian
    Go Version:	go1.19.3
    Platform:	linux
    Architecture:	amd64

    Wails
    ------
    Version: 		v2.2.0
    Package Manager: 	apt

    Dependency	Package Name		Status		Version
    ----------	------------		------		-------
    *docker 	docker.io 		Available 	20.10.5+dfsg1-1+deb11u2
    gcc 		build-essential 	Installed 	12.9
    libgtk-3 	libgtk-3-dev 		Installed 	3.24.24-4+deb11u2
    libwebkit 	libwebkit2gtk-4.0-dev 	Installed 	2.38.2-1~deb11u1
    npm 		npm 			Installed 	8.19.2
    *nsis 		nsis 			Available 	3.06.1-1
    pkg-config 	pkg-config 		Installed 	0.29.2

    * - Optional Dependency

    Diagnosis
    ---------
    Your system is ready for Wails development!
    Optional package(s) installation details: 
    - docker: sudo apt install docker.io
    - nsis: sudo apt install nsis



    If Wails is useful to you or your company, please consider sponsoring the project:
    https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

This seems to me like the same issue as reported for videos in #1568. The `<audio>` tag doesn't call our AssetServer on `wails://` and therefore we can't serve it in production. This seems to be an issue with webkit2gtk on linux.

The mentioned [workaround](https://github.com/wailsapp/wails/issues/1568#issuecomment-1189577115) should also work for audio. Please keep in mind, the workaround will load the whole file into memory, but if your audio file isn't too big that should not be a big issue.

I've successfully tested audio to be working on macOS Ventura and Windows 11.

**Comment by stffabi** [comment]
Awesome, glad it works for you with the workaround.

**Comment by leaanthony** [comment]
I'll add this to the troubleshooting guide. I feel like the information in the site is getting unwieldy!
