### ISSUE TITLE
Add new language - French

### ISSUE THREAD

**Issue by Adaendra** [wailsapp/wails#2092]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Adding documentation in french

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by misitebao** [comment]
@Adaendra Thanks for your willingness to contribute to the documentation, I have added French as a target language in Crowdin, you can [join the project](https://crowdin.com/project/wails) and submit your translations.

**Comment by Adaendra** [comment]
Thanks @misitebao ! I will do my best to help you :)
