### ISSUE TITLE
<video/> tag can not be full screen

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#2099]
### Description

'https://github.com/webview/webview/' 
Use the repository  to display full-screen buttons for full-screen video playback

-------------

But the same code
use `wails` Can not play full screen

### To Reproduce

vue3 html

```
<video controls width="500" >
        <source
          src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm"
          type="video/webm"
        />
        <source
          src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
          type="video/mp4"
        />
      </video>
```

### Expected behaviour

The full-screen button should be displayed for full-screen playback

### System Details

```shell
------
OS:		MacOS
Version: 	12.3.1
ID:		21E258
Go Version:	go1.18.5
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.1.0
```

**Comment by leaanthony** [comment]
Hi 👋 Why are you referencing 'https://github.com/webview/webview/'?

**Comment by 758F08FE920B1765** [comment]
@leaanthony  hi
Because I suspect a browser kernel problem。 

[webview](https://github.com/webview/webview) This is just an example. 
It uses the webkit kernel, which renders `<video />`  perfectly and supports full-screen playback.

but wails webkit kernel， `<video />` Full screen playback， it doesn't work

**Comment by leaanthony** [comment]
AFAIK they use the same engine: WkWebView

**Comment by krishna8421** [comment]
Any update on this?, I want to make a video go full screen but unable to do it.

**Comment by leaanthony** [comment]
@krishna8421 Please can you retry using the latest version. Remember to upgrade the version of Wails in you project's `go.mod`.

**Comment by krishna8421** [comment]
@leaanthony Hey updated to v2.5.1, full screen working on the browser but not in the app. can you give some example codes or reference how to do it, maybe I am doing something wrong.

**Comment by fkhadra** [comment]
@leaanthony  I'm wondering if allowing to set [elementFullscreenEnabled](https://developer.apple.com/documentation/webkit/wkpreferences/3917769-elementfullscreenenabled?language=objc) in the preferences on mac won't address the issue. I'll check

**Comment by fkhadra** [comment]
So just tested and it seems to work as expected :). 
https://github.com/wailsapp/wails/assets/5574267/eb338fe3-437f-4f9f-9155-14d12145a7ba

**Comment by leaanthony** [comment]
@fkhadra the situation with windows is a lot worse: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1834

**Comment by leaanthony** [comment]
I'm not sure why, but this works really well on Windows in v3....

**Comment by ilaziness** [comment]
v2.9.2

I encountered the same problem on Windows 11, not screen full, is window full.

I added event listener to the element:

```
addEventListener('fullscreenchange')
addEventListener('webkitfullscreenchange')
```

use runtime function `WindowFullscreen` and `WindowUnfullscreen` switch fullscreen within event handler.

**Comment by guiyumin** [comment]
> It works well in v3 and looks like there's a workaround for v2. Closing for now.

what v3? 
v2.10.2 is the latest.
