### ISSUE TITLE
Allow user to hook into typescriptfy (Ex: For Enum support)

### ISSUE THREAD

**Issue by sarim** [wailsapp/wails#2104]
### Is your feature request related to a problem? Please describe.

My struct in golang has a status field. I declared it as instructed at [typescriptfy readme](https://github.com/tkrajina/typescriptify-golang-structs#enums). But to convert it to typescript you have to call `AddEnum` of `converter`. Obviously that's internal to wails and user(me) has no access. As seen in typescriptfy readme, other advanced feature of it also requires access to `converter`.

### Describe the solution you'd like

Maybe a option to add a callback to `wails.Run(&options.App{`, that'll receive a typescriptify converter pointer, then user will add their custom enum/types to it from here.

### Describe alternatives you've considered

Something in wails.json? Would be hard to satisfy all use cases in plain json as compared to a callback function in golang.

**Comment by leaanthony** [comment]
Is this something you're willing to have a go at @sarim ?

**Comment by sarim** [comment]
> Is this something you're willing to have a go at @sarim ?

I'm interested, though not sure how much time I can invest on it. Which solution you guys want to pursue? Callback from options or something in wails.json?

**Comment by leaanthony** [comment]
I'd favour the callback route.

**Comment by iDevelopThings** [comment]
So I needed something kinda similar and decided to implement this + another feature:

How does this look for the callback?

```go
mainApp := application.NewWithOptions(&options.App{
	Assets: assets,
	Bind: []interface{}{
		new(MyStruct),
	},
	Experimental: &options.Experimental{
		BindingsHook: options.BindingHook{
			Hook: func(tsify options.ITypeScriptify) error {
				tsify.Add(new(MyStruct))
				tsify.AddEnum(AllWeekdays)
				return nil
			},
		},
	},
})
```


With these bindings:
![CleanShot 2023-01-23 at 05 03 19](https://user-images.githubusercontent.com/4105581/213969001-511a1f81-d40a-4887-8730-48a45402f2b5.png)

This is generated:

```typescript
export namespace Custom {

	export enum Weekday {
	    SUNDAY = 0,
	    MONDAY = 1,
	    TUESDAY = 2,
	    WEDNESDAY = 3,
	    THURSDAY = 4,
	    FRIDAY = 5,
	    SATURDAY = 6,
	}
	export class MyStruct {
	    someProperty: string;
	    static createFrom(source: any = {}) {
	        return new MyStruct(source);
	    }
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.someProperty = source["someProperty"];
	    }
	    getAnother() : Promise<main.AnotherStruct> {
			  return window['go']['main']['MyStruct']['GetAnother']();
	    }
	    getAnotherAgain() : Promise<main.AnotherStruct> {
			  return window['go']['main']['MyStruct']['GetAnotherAgain']();
	    }
	    someFunc() : Promise<[boolean, string]> {
			  return window['go']['main']['MyStruct']['SomeFunc']();
	    }
	    someOtherThing(arg1: string, arg2: string, arg3: boolean) : Promise<[boolean, string]> {
			  return window['go']['main']['MyStruct']['SomeOtherThing'](arg1, arg2, arg3);
	    }
	}
}

export namespace main {
	export class AnotherStruct {
	    someProperty: string;
	    static createFrom(source: any = {}) {
	        return new AnotherStruct(source);
	    }
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.someProperty = source["someProperty"];
	    }
	}

}

```

Some other notes:
- I implemented some hacks to add the struct methods of bindings to the class, just realised i need to make these static 
- I need to implement a proper fix for the namespace, right now it just uses a hardcoded one

**Comment by leaanthony** [comment]
I think for v2 we have a solution in the linked PR. For v3 we have removed the namespace and are generating in its own file. Feel free to reopen if you want to revisit this.
