### ISSUE TITLE
unexpected white border occured in the bottom of window when frameless is set true

### ISSUE THREAD

**Issue by Web3codexio** [wailsapp/wails#2108]
### Description

when i set  the property of Frameless to true,theres comes a unexpected white border in the bottom of window

### To Reproduce

1、set the property of frameless to true

### Expected behaviour

run app in frameless mode sucessfully with no unexpected white border 

### Screenshots

![image](https://user-images.githubusercontent.com/50604703/202776305-32b39b18-82ad-4739-9ff8-06c6dcf92254.png)
![image](https://user-images.githubusercontent.com/50604703/202776464-6ffbf944-0b27-42e8-80c4-ce4fa34565a8.png)

### Attempted Fixes

1、reinited the project,and set the same config,but it  failed again

### System Details

```shell
System
------
OS:             Windows 10 Pro     
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.18.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       107.0.1418.42
npm             N/A             Installed       8.15.0
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download
```

### Additional context

there's a white border too with  my self-defined  components,your help will be highly appreciated!tks alot!

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

I think I have an idea what might cause this issue. Would it be possible for you to test something? Could you please try to resize the Window or minimise and maximise it, does the line disappear then?

**Comment by chuyijia** [comment]
> Thanks for using Wails and reporting this issue.
> 
> I think I have an idea what might cause this issue. Would it be possible for you to test something? Could you please try to resize the Window or minimise and maximise it, does the line disappear then?

i tried as u told but sadly the white border still exist

**Comment by stffabi** [comment]
Thanks for testing 🙏

I might have a draft PR ready for testing. Unfortunately I can't reproduce it here on Windows 11 22H2, but I think I know where the problem is located.
Would be awesome if you could test it, will let you know.

**Comment by chuyijia** [comment]
> 

its so excited to see u guys working on it.tks alot!

**Comment by chuyijia** [comment]
> Thanks for testing 🙏
> 
> I might have a draft PR ready for testing soon. Unfortunately I can't reproduce it here on Windows 11 22H2, but I think I know where the problem is located. Would be awesome if you could test it, will let you know.

its so excited to see u guys working on it.tks alot!

**Comment by stffabi** [comment]
@chuyijia could you please try PR #2111 and see if that fixes your issue? That would be awesome.

**Comment by stffabi** [comment]
Awesome, thanks so much @chuyijia for testing it 🙏
