### ISSUE TITLE
Develop head - bare app shows blank screen

### ISSUE THREAD

**Issue by Vaelatern** [wailsapp/wails#211]
**Description**
With a react app, `wails build` produces a native binary that fails to show anything but the correct background color in a square.

**Expected behaviour**
I expected to see the default page, the same I see with `wails serve`

**Screenshots**
https://files.catbox.moe/i9nxzx.png

**System Details**
Void Linux on the latest develop.

**Comment by leaanthony** [comment]
What template was this?

**Comment by leaanthony** [comment]
Please file bugs using `wails issue`. Thanks.

**Comment by Vaelatern** [comment]
`wails issue` seems to try using links, instead of just giving me a link I can use in my browser.

React.

**Comment by bh90210** [comment]
yeap, I wanted to comment this, it works as expected here :/

**Comment by bh90210** [comment]
have you tried building in debug mode? `wails build -d`

**Comment by bh90210** [comment]
can u please share the code of `index.js` of the react project?
