### ISSUE TITLE
Wails CLI config file supports TOML format

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#2114]
### Is your feature request related to a problem? Please describe.

Currently wails cli only supports configuration files in json format by default, but json does not support comments, which is a drawback. Based on this, I hope wails can support configuration files in toml format.

### Describe the solution you'd like

Now more and more projects use toml as a configuration file, which is very readable. I hope that the wails cli can automatically recognize the configuration file and automatically call the corresponding parsing engine according to different suffixes, just like [Hugo](https://gohugo.io/getting-started/configuration/).

### Additional context

It would be even better if we can implement general support for other files while supporting the toml format, such as: yaml, etc.

**Comment by leaanthony** [comment]
Yeah I'm in favour of this. Having used TOML for other things, it's a regret that the Wails config is not in the same format.

**Comment by leaanthony** [comment]
There's one issue with this: the JSON format has a well supported json schema that IDEs can use to validate your changes are good. AFAIK, there isn't the same for TOML just yet?

**Comment by misitebao** [comment]
@leaanthony For configuration files in different formats, the IDE basically provides corresponding formatting extensions. But does this have anything to do with the wails project?

**Comment by leaanthony** [comment]
Well having the schema in the IDE helps make sure that the config file is correct and you haven't entered bad values. It's a better developer experience. We currently support this with the JSON schema here: https://github.com/wailsapp/wails/blob/master/website/static/schemas/config.v2.json

**Comment by misitebao** [comment]
@leaanthony 
Look at this: https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml

**Comment by leaanthony** [comment]
Oh that's interesting. I wonder if something exists for Goland too

**Comment by misitebao** [comment]
I didn't find any useful information about Goland TOML Schema, but I think whether to support Schema has little impact on developers. It is only an auxiliary function and not necessary, because we have detailed documentation and communities.

**Comment by leaanthony** [comment]
It's a fair call. I think it would be good to have TOML as an alternative otherwise you just take away the usefulness of the json schema we just added.

**Comment by pomdtr** [comment]
Another alternative would be to adopt the `json with comments convention for the config`. VS Code use it for it's config, and it works quite well with json comments.

**Comment by AnubhavUjjawal** [comment]
I think using an open-source tool for configuration management, like [viper](https://github.com/spf13/viper) is a good idea.

Pros of this approach:
- It delegates the parsing of the config file to a battle-tested tool. 
- It allows us to support schemas in as many languages as possible, users can choose what they are most comfortable with.

**Comment by KevinJCross** [comment]
Im looking to contribute ... Ill give this a go.
Using viper should help reduce the support load on the different formats.

**Comment by leaanthony** [comment]
Thanks for the offer of help. I'm not sure this is worth doing as the whole concept of `wails.json` will not be needed in v3 (which is the current focus) and I'm not sure there's much bandwidth to really support TOML in v2. If you're serious about contributing, ping me on discord 👍

**Comment by leaanthony** [comment]
Closing this as migrating to TOML is not going to happen realistically in the v2 lifespan and it's not required for v3.
