### ISSUE TITLE
Expose native window handlers

### ISSUE THREAD

**Issue by davidmanzanares** [wailsapp/wails#2117]
### Is your feature request related to a problem? Please describe.

It would be very useful to support exposing the native window handlers of each platform to allow developers create custom advanced integration with other technologies.

For example, you may want to render part of an application with something other than web technologies. My current needs require to access low-level GPU capabilies (compute shaders), and these are not available yet in the web.

### Describe the solution you'd like

Exposing the native handlers. For example, the X11 Window on Linux, and the HWND window handler on Windows.

### Describe alternatives you've considered

Without the native handlers, the integration is not seamless, and the user can see two windows for the same application.

Without wails or similar technologies (electron), you miss the modern UI development.

Without native access you miss some advanced capabilies, like compute shaders.

With the proposed solution, I think you get the best of both worlds.

### Additional context

For example, exposing these would allow developers to integrate GLFW and OpenGL with a wails application (this is with a custom wails fork):
![image](https://user-images.githubusercontent.com/1692175/203165349-4681bf91-8d89-40f1-9e62-66718fa6ff9b.png)

**Comment by leaanthony** [comment]
Hey there 👋 I'm not against this but I think it makes more sense to be done in the context of the "multiple windows" support that is scheduled. What are your thoughts?

**Comment by davidmanzanares** [comment]
Honestly, I don't have enough context to know if it's better to add this after "multiple windows".

I'm interested about that feature too, so I may update/create the PR if you prefer to wait.

Anyway, right now I don't have much time for polishing the PR, but I'm pretty happy with my fork, and with wails in general, thank you to all the devs!

**Comment by leaanthony** [comment]
To give you some context, the windowing code will go through a refactor to support multiple windows so there'll be a need to also port this.

**Comment by davidmanzanares** [comment]
Let's wait then!

**Comment by leaanthony** [comment]
Supported in v3

**Comment by shahulpm** [comment]
Is this currently available to use ?. I need to set up a live preview window for fingerprints capturing process, where can I find the documentation or example code to set up this ?
