### ISSUE TITLE
Support Distribution 'LinuxMint'

### ISSUE THREAD

**Issue by GavinB-hpe** [wailsapp/wails#212]
**Description**
Distribution 'LinuxMint' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | LinuxMint |
| Distribution Version   | 19.1 |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
Can this be closed now?

**Comment by GavinB-hpe** [comment]
LinuxMint supported in the develop branch - works for me.
