### ISSUE TITLE
Windows build hangs forever on startup

### ISSUE THREAD

**Issue by moonspirit** [wailsapp/wails#2124]
### Description

Uses wails to generate an emtpy project (hello world) and build on windows，i didn't see anything show up after running it. Instead there are sevaral Microsoft Edge WebView2 processes hangs.

### To Reproduce

1. init the project
C:\Go>wails init -n myproject -t vue-ts
Wails CLI v2.2.0

Initialising Project 'myproject'
--------------------------------

Project Name:      myproject
Project Directory: C:\Go\myproject
Project Template:  vue-ts
Template Support:  https://wails.io

Initialised project 'myproject' in 1.65s.

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

2. build it
C:\Go\myproject>wails build -debug -clean
Wails CLI v2.2.0

App Type:               desktop
Platforms:              windows/amd64
Compiler:               C:\Program Files\Go\bin\go.exe
Skip Bindings:          false
Build Mode:             Debug
Frontend Directory:     C:\Go\myproject\frontend
Obfuscated:             false
Skip Frontend:          false
Compress:               false
Package:                true
Clean Bin Dir:          true
LDFlags:                ""
Tags:                   []
Race Detector:          false

Building target: windows/amd64
------------------------------
  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.
  - An experimental Go native WebView2Loader is available. We would love to hear your feedback about it and invite you to test it by building with `-tags exp_gowebview2loader`
Built 'C:\Go\myproject\build\bin\myproject.exe' in 57.594s.

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

3. run it
C:\Go\myproject>C:\Go\myproject\build\bin\myproject.exe

### Expected behaviour

The gui will show up and see the wails Logo as on mac

### Screenshots

![13cd7b13-d1fa-4c43-a9b5-00039e2d9201](https://user-images.githubusercontent.com/1793306/203311973-6c94fe1a-6c7f-4ed2-b829-3c377c266ce5.jpeg)

### System Details

```shell
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.19.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.2.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       107.0.1418.56
npm             N/A             Installed       8.19.2
*upx            N/A             Installed       upx 4.0.1
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by moonspirit** [comment]
Works on another Windows 10 Home， fails on Windows 10 Pro

I installed varlyapp(a showcase in wails.io) and get the same result.

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

We had a similar report in the past #1837  but were never able to reproduce it on our side.

Would it be possible for you to test the following to hopefully narrow this down:
- Init a plain project: `wails init -n myproject -t plain`
- Does it work with `wails dev`? What's the console output there.
- Adjust log level in app options: `LogLevel:         logger.DEBUG,`
- Try a debug build `wails build --debug`. You should see some minimal log output (maybe we need to add more logging to get this fixed)
- Try a debug build with the new WebView2Loader `wails build --debug --tags exp_gowebview2loader`

Thanks for your help.

**Comment by moonspirit** [comment]
I have followed these steps, i think there is no more clues

1. initial a plain project

C:\Go>wails init -n myproject -t plain
Wails CLI v2.2.0

Initialising Project 'myproject'

Project Name:      myproject
Project Directory: C:\Go\myproject
Project Template:  plain
Template Support:  https://github.com/wailsapp/wails

Initialised project 'myproject' in 518ms.

> Thanks for using Wails and reporting this issue.
> 
> We had a similar report in the past #1837 but were never able to reproduce it on our side.
> 
> Would it be possible for you to test the following to hopefully narrow this down:
> 
> * Init a plain project: `wails init -n myproject -t plain`
> * Does it work with `wails dev`? What's the console output there.
> * Adjust log level in app options: `LogLevel:         logger.DEBUG,`
> * Try a debug build `wails build --debug`. You should see some minimal log output (maybe we need to add more logging to get this fixed)
> * Try a debug build with the new WebView2Loader `wails build --debug --tags exp_gowebview2loader`
> 
> Thanks for your help.



2. wails dev output

C:\Go\myproject>wails dev
Wails CLI v2.2.0

Executing: go mod tidy
  - Generating bindings: Done.
  - No Install command. Skipping.
  - No Build command. Skipping.
Building application for development...
  - Generating bindings: Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.
  - An experimental Go native WebView2Loader is available. We would love to hear your feedback about it and invite you to test it by building with `-tags exp_gowebview2loader`

watching: C:\Go\myproject
watching: C:\Go\myproject\build
watching: C:\Go\myproject\build\darwin
watching: C:\Go\myproject\build\windows
watching: C:\Go\myproject\build\windows\installer
watching: C:\Go\myproject\frontend
watching: C:\Go\myproject\frontend\src
watching: C:\Go\myproject\frontend\src\assets
watching: C:\Go\myproject\frontend\src\assets\fonts
watching: C:\Go\myproject\frontend\src\assets\images
watching: C:\Go\myproject\frontend\wailsjs
watching: C:\Go\myproject\frontend\wailsjs\go
watching: C:\Go\myproject\frontend\wailsjs\go\main
watching: C:\Go\myproject\frontend\wailsjs\runtime
Watching (sub)/directory: C:\Go\myproject
Using DevServer URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
INF | Serving assets from disk: C:\Go\myproject\frontend\src
DEB | WebView2 Runtime Version '107.0.1418.56' installed. Minimum version required: 94.0.992.31.
DEB | [DevWebServer] Serving DevServer at http://localhost:34115
DEB | [AssetHandler] Loading file 'index.html'


To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115


3. adjust log level (as you can see, the default opitons is DEBUG log level)，so wails dev produces the result output as above

4. debug build and run it

C:\Go\myproject>wails dev
Wails CLI v2.2.0

Executing: go mod tidy
  - Generating bindings: Done.
  - No Install command. Skipping.
  - No Build command. Skipping.
Building application for development...
  - Generating bindings: Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.
  - An experimental Go native WebView2Loader is available. We would love to hear your feedback about it and invite you to test it by building with `-tags exp_gowebview2loader`

watching: C:\Go\myproject
watching: C:\Go\myproject\build
watching: C:\Go\myproject\build\darwin
watching: C:\Go\myproject\build\windows
watching: C:\Go\myproject\build\windows\installer
watching: C:\Go\myproject\frontend
watching: C:\Go\myproject\frontend\src
watching: C:\Go\myproject\frontend\src\assets
watching: C:\Go\myproject\frontend\src\assets\fonts
watching: C:\Go\myproject\frontend\src\assets\images
watching: C:\Go\myproject\frontend\wailsjs
watching: C:\Go\myproject\frontend\wailsjs\go
watching: C:\Go\myproject\frontend\wailsjs\go\main
watching: C:\Go\myproject\frontend\wailsjs\runtime
Watching (sub)/directory: C:\Go\myproject
Using DevServer URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
INF | Serving assets from disk: C:\Go\myproject\frontend\src
DEB | WebView2 Runtime Version '107.0.1418.56' installed. Minimum version required: 94.0.992.31.
DEB | [DevWebServer] Serving DevServer at http://localhost:34115
DEB | [AssetHandler] Loading file 'index.html'


To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115

C:\Go\myproject>.\build\bin\myproject.exe
DEB | WebView2 Runtime Version '107.0.1418.56' installed. Minimum version required: 94.0.992.31.
DEB | [AssetHandler] Loading file 'index.html'

No more logs, no gui show up


5. debug build with webview2loader
C:\Go\myproject>wails build --debug --tags exp_gowebview2loader -clean
Wails CLI v2.2.0

App Type:               desktop
Platforms:              windows/amd64
Compiler:               C:\Program Files\Go\bin\go.exe
Skip Bindings:          false
Build Mode:             Debug
Frontend Directory:     C:\Go\myproject\frontend
Obfuscated:             false
Skip Frontend:          false
Compress:               false
Package:                true
Clean Bin Dir:          true
LDFlags:                ""
Tags:                   [exp_gowebview2loader]
Race Detector:          false

Building target: windows/amd64
  - Generating bindings: Done.
  - No Install command. Skipping.
  - No Build command. Skipping.
  - Generating bundle assets: Done.
  - Compiling application: Done.
  - Thanks for testing the new experimental Go native WebView2Loader. Please report your feedback and any bugs you think might be related to using the new loader: https://github.com/wailsapp/wails/issues/2004
Built 'C:\Go\myproject\build\bin\myproject.exe' in 15m7.849s.


C:\Go\myproject>.\build\bin\myproject.exe
DEB | Using experimental go webview2loader
DEB | WebView2 Runtime Version '107.0.1418.56' installed. Minimum version required: 94.0.992.31.
DEB | [AssetHandler] Loading file 'index.html'

![image](https://user-images.githubusercontent.com/1793306/203536951-ff814b40-e0b3-478b-8b85-c5f2f436034d.png)

**Comment by stffabi** [comment]
Thanks for testing everything. 

There should be more log output of files that get loaded, like main.css/main.js here:
> DEB | [AssetHandler] Loading file 'index.html'

Because they are missing I suspect the `navigationCompleted` event doesn't get triggered from the WebView and therefore the main window doesn't appear. Because the main window is not shown before the navigation has been completed.
This seems like either Wails is blocking somewhere during the processing of the request or WebView2 does stop loading for some reason.
Could you try updating Wails to the lastest master commit according to [Bleeding Edge](https://wails.io/docs/guides/bleeding-edge). Then add the following to your app options
```go
		Debug: options.Debug{
			OpenInspectorOnStartup: true,
		},
```
Then use  `wails build --debug` and start the binary. You should see the Developer Tools being opened. In there investigate if you see any error on the console or if requests are hanging in the network tab. If you don't see anything, try to reload the page with  `ctrl-r` while being in the network tab. Then you should see at least the request for `index.html`. Try to investigate the other tabs, e.g. console to see if there are any errors.

**Comment by moonspirit** [comment]
> `navigationCompleted`

I believe you are right, I added some logs and Frontend::navigationCompleted never get called. Only  EnvironmentCompleted and CreateCoreWebView2ControllerCompleted has been invoked.

Since the gui now shown, I didn't see any developer tools even after adding the above options.Debug.

Get stucked and can't investigate further.

**Comment by stffabi** [comment]
Strange the developer tools should popup regardless of the main window, since that's a separate window and not in the main window.

That would even more point to a problem or hang in webview itself. Or a blocked main thread on our side but I wouldn't expect that.

Could you try add debug logging to frontend:processRequest to see if it finishes and does not block?

I'm sorry that I can't really help you apart from guidance what to try, because I'm unable to reproduce it.

**Comment by stffabi** [comment]
Just tested what happens when blocking in processRequest. When blocking there it still opens the developer tools when using `OpenInspectorOnStartup: true`. Blocking there basically blocks the main thread, but if the developer tools still open on ma machine I would really expect this to be a problem on the WebView2 side.

Just a thought, could you try disabling `SmartScreen for Edge` in your Windows settings?

**Comment by moonspirit** [comment]
@stffabi Very appreciate, I see microsoft windows codeintegrity error events every time runs myproject.exe

Code Integrity determined that a process (\Device\HarddiskVolume4\Program Files (x86)\Microsoft\EdgeWebView\Application\107.0.1418.56\msedgewebview2.exe) attempted to load \Device\HarddiskVolume4\Windows\System32\winbrohca64.dll that did not meet the Microsoft signing level requirements.


I thinks mircosoft edge doesn't work properly because of these injected dlls, i will try after removing thoses stuffs.

**Comment by leaanthony** [comment]
I've no idea what that DLL is but I'm not convinced it's Wails. Do you have an extension installed for Edge that might be clashing? https://www.freefixer.com/library/file/winbrohca64.dll-313744/

**Comment by stffabi** [comment]
@moonspirit were you able to solve this issue?

Since we haven't heard anything in a while I think we could close this issue. If you still seeing problems with this, please feel free to reopen it.

**Comment by stffabi** [comment]
WebView doesn't work with wrongly signed injected dll, see also https://github.com/MicrosoftEdge/WebView2Feedback/issues/2051

PR #2627 should help in your case by showing the Wails window with a clear message. Furthermore that PR allows you to disable the integrity checks if you really want to.

**Comment by lorypelli** [comment]
I have the same issue

**Comment by lorypelli** [comment]
![image](https://github.com/wailsapp/wails/assets/87276663/84143c13-86cb-4f44-831a-545fef1f0c21)
got it, how can I fix

**Comment by lorypelli** [comment]
![image](https://github.com/wailsapp/wails/assets/87276663/08b6848c-cdee-4b2f-b725-b974f60e4ed8)
Ok, it appears this is needed
