### ISSUE TITLE
编译的Mac版应用存在几个小bug

### ISSUE THREAD

**Issue by Safe3** [wailsapp/wails#2129]
### Description

**1.应用的默认窗口最小化按钮点击不起作用**
**2.html中的input框不能粘贴字符串**
_在window中不存在这些问题_

### To Reproduce

相关代码如下：
err := wails.Run(&options.App{
		Title:         "x",
		Width:         512,
		Height:        384,
		Frameless:     false,
		DisableResize: true,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 0, G: 0, B: 0, A: 0},
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},
		Windows: &windows.Options{
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
			BackdropType:         windows.Acrylic,
		},
		Mac: &mac.Options{
			Appearance: mac.NSAppearanceNameDarkAqua,
			About: &mac.AboutInfo{
				Title:   "x",
				Message: "x",
				Icon:    icon,
			},
		},
		Linux: &linux.Options{
			Icon:                icon,
			WindowIsTranslucent: false,
		},
	})

### Expected behaviour

窗口可以最小化
html中的input框能粘贴字符串

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.5
ID:		21G72
Go Version:	go1.19.3
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.2.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	8.19.2
*upx  				N/A 		Available 	
*nsis  				N/A 		Available 	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by Safe3** [comment]
找到了原因，应用在root提权后出现该现象

**Comment by leaanthony** [comment]
Mac copy and paste won't work unless you add them to the application menu. That's a Mac thing
