### ISSUE TITLE
Support Distribution 'Garuda Linux'

### ISSUE THREAD

**Issue by andrewloz** [wailsapp/wails#2133]
**Description**
Distribution 'garuda' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.9 |
| Go Version    | go1.19.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | garuda |
| Distribution Name   | Garuda Linux |
| Distribution Version   |  |

This is a rolling Arch distribution, so should be supported by arch based checks.  Is there a way to set the distro as arch so that I can use wails?

**Comment by leaanthony** [comment]
Thanks for opening this. Since Wails v2 has been released, we are not accepting any tickets for v1. For help updating your application to v2, please read the [Migration Guide](https://wails.io/docs/guides/migrating).
