### ISSUE TITLE
The wails cli tool fails to install on the windows platform

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#2145]
### Description

An error occurred when executing the `go install` command in the `wails/v2/cmd/wails` directory.

### To Reproduce

1. Clone repo
2. cd `wails/v2/cmd/wails`
3. run `go install`
4. See errors

### Expected behaviour

Successful installation.

### Screenshots

```shell
$ go install
# github.com/wailsapp/wails/v2/cmd/wails/internal/commands/dev
internal\commands\dev\dev_windows.go:28:5: undefined: LogRed

```

### System Details

```shell
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\Downloads\wails\v2\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build4210329325=/tmp/go-build -gno-record-gcc-switches

```

### Additional context

I can fix it myself.

**Comment by stffabi** [comment]
It seems that master is currently also broken for macOS.

**Comment by stffabi** [comment]
Would it be possible for you to also fix that one @misitebao ? That would be awesome.

**Comment by stffabi** [comment]
We should have a way to trigger all tests before able to merge a PR. To ensure we don't break building on master.

**Comment by misitebao** [comment]
@stffabi 
Ok thanks for the reminder, I'll check them out.

**Comment by misitebao** [comment]
@stffabi 
We don't have a command-line test build CI, and I don't have a MacOS environment, can you provide the following error message? 🙏

**Comment by stffabi** [comment]
Yeah I can fix it, I've seen the test failing here https://github.com/wailsapp/wails/actions/runs/3563326195/jobs/5986043511

**Comment by misitebao** [comment]
@stffabi 
@leaanthony  was so responsive, it got merged before I could fix it. 🤪 Sorry I can only trouble you to fix it yourself.

**Comment by leaanthony** [comment]
@misitebao - was the PR a draft PR? If you don't want it merged, make a draft PR 👍 😅
