### ISSUE TITLE
Support Distribution 'Kali'

### ISSUE THREAD

**Issue by adeyinkabadmus** [wailsapp/wails#215]
**Description**
Distribution 'Kali' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.9 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | Kali |
| Distribution Version   | kali-rolling |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
:+1: thanks @adeyinkabadmus 
This will be quick hopefully, please stay around for tesing.

**Comment by leaanthony** [comment]
@adeyinkabadmus This is now ready for testing. Thanks.

**Comment by leaanthony** [comment]
@adeyinkabadmus any updates?

**Comment by adeyinkabadmus** [comment]
Not yet. I did a wails update and then retried wails init but i still get the prompt to send a request for distribution support. Thank you very much.
![Screenshot from 2019-09-02 22-35-37](https://user-images.githubusercontent.com/25610622/64133989-3ce55700-cdd2-11e9-9c30-7fb072ff4089.png)

**Comment by bh90210** [comment]
hey @adeyinkabadmus you should update running `wails update -pre` to get the latest pre-release,
although I think even that won't work cause we haven't yet tagged the PR that added support for kali but give it cause I am not 100% sure, it might actually work! :+1:

**Comment by adeyinkabadmus** [comment]
@bh90210 . Thanks for the suggestion. You're right about it not working though. I got the same result. it got updated to v0.17.13 so i'm assuming it's not been tagged like you said.

**Comment by bh90210** [comment]
we r working on it :) (and by we I mean @leaanthony :-p) thanks for ur patience

**Comment by adeyinkabadmus** [comment]
Thank you for your contributions.

**Comment by leaanthony** [comment]
@adeyinkabadmus Please update to the latest pre-release (v0.17.14-pre) using `wails update -pre`. Let us know how you get on 👍

**Comment by adeyinkabadmus** [comment]
@leaanthony , thanks for the new update. I successuly updated to 0.17.14-pre but i still get the prompt to send a request support for Kali. Thank you very much.

**Comment by bh90210** [comment]
heh, I don't know what it is but it sounds my fault. I am investigating..

**Comment by bh90210** [comment]
can u please share the output of `cat /etc/os-relase`?

**Comment by BluePixel33** [comment]
Hi @bh90210, I think there's a missing switch case here:
https://github.com/bh90210/wails/blob/386ec5e46f89580cfbee6dcfdcba0c4b470083b3/cmd/linux.go#L123

**Comment by bh90210** [comment]
yes! I am fixing it asap, thank you

**Comment by bh90210** [comment]
sorry everyone, fixed it
@adeyinkabadmus can u please check it against my branch before @leaanthony actually does another version bump?
`git clone -b 215-Support-Distribution-Kali https://github.com/bh90210/wails.git && cd wails/cmd/wails && go install && wails setup`

**Comment by adeyinkabadmus** [comment]
Thanks a lot everyone. It works now. I really do appreciate your attention and efforts.
![Screenshot from 2019-09-03 18-24-34](https://user-images.githubusercontent.com/25610622/64195396-470e6080-ce79-11e9-835c-e54e40ad5cce.png)

**Comment by leaanthony** [comment]
Glad it's working @adeyinkabadmus! I'm closing this now. Please reopen if there is a regression 👍
