### ISSUE TITLE
Support Tray Menus (mac)

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#2157]

**Comment by chumobyte** [comment]
i need this too

**Comment by leaanthony** [comment]
Supported in v3

**Comment by 41419142023** [comment]
我非常需要这个功能

**Comment by ricardopolo** [comment]
Ia the v3 in beta or how can we get it?

**Comment by leaanthony** [comment]
Alpha. We are managing this stage via the discord server to reduce noise in GitHub. Feel free to join us!
