### ISSUE TITLE
Error when using wails build -p

### ISSUE THREAD

**Issue by thlinde** [wailsapp/wails#216]
**Description**

wails build -p breaks with the following error: "invalid character ':' after object key:value pair" at the level of "Generating .app"

![wails_message_build_p](https://user-images.githubusercontent.com/46750817/63993115-51ce9b80-caef-11e9-8ffd-2a24f5a8f637.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |

**Comment by leaanthony** [comment]
Hi there. I just tried this and it works fine for MBP 10.14.6 / Wails v0.17.0:
![image](https://user-images.githubusercontent.com/1943904/64002625-d2bc8000-cb4d-11e9-9fb3-ab78b44d19a4.png). I have a feeling it will be to do with your global wails config. What does ~/.wails/wails.json have in it? Censor what you need to censor :-)

**Comment by thlinde** [comment]
Hi, Lea. Sorry for delayed answer, But I wasn’t at the place.
You are right. In the wails.json are email and name with wrong quotation marks. Some quotation was „ and not "
After changing all marks to " the packaging works fine.
The question is, if it is my very special case or could it be that this depends on the language of the system (here german, where the „ is often used as the first quotation mark, for example „citation“). The wails.json file was generated with installation of wails automatically and maybe the system changes some " on generation?

The problem is solved, thank you very much for your help.
Best regards Thomas

**Comment by leaanthony** [comment]
That's weird, but I'm glad that you've sorted it. If you could post the contents of wails.json, that would be great. We should handle that better. Thanks 👍
