### ISSUE TITLE
Disable SmartScreen / FraudulentWebsite detection

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#2163]
### Is your feature request related to a problem? Please describe.

Microsoft uses SmartScreen per default in WebView2 to detect if a user is accessing a phishing or malware website. The same applies to Apple, they use a "FraudulentWebsite" detection service.

Both services send information about the navigation to Microsoft/Apple. It's not clear if this only applies to External Websites or also to custom protocols or what is included.

### Describe the solution you'd like

It would be great to have the possibility to disable this detection. Maybe even better per default disable it and the developer needs to opt-in.

How to disable it:
- Apple [fraudulentWebsiteWarningEnabled](https://developer.apple.com/documentation/webkit/wkpreferences/3335219-fraudulentwebsitewarningenabled?language=objc)  
- Microsoft: https://github.com/MicrosoftEdge/WebView2Feedback/issues/834

**Comment by leaanthony** [comment]
💯

**Comment by stffabi** [comment]
> I believe this would be fixed by the "pass args to webview2" feature that would address a bunch of these options.

Yeah that's a requirement. But I think this should be an option on the app options, to disable this service on all platforms. We would then internally append that to the "args to webview2" in the webview2 case.
