### ISSUE TITLE
Support Multiple Windows (Windows)

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#2165]
Part of https://github.com/wailsapp/wails/issues/1480

**Comment by misitebao** [comment]
I think we need to design the API first, then discuss the API, and then implement it after reaching a consensus, which can reduce and avoid later changes to the API. 🙏

**Comment by leaanthony** [comment]
The initial API is what we have now in the `Window*` methods plus moving the settings from "application" config to a window config. The only unanswered questions right now are:
- What does a "child window" mean vs a "sibling window" - eg are they all independent?
- Can events be picked up between all the windows? Can you target a window?

I don't think there's anything that's a blocker.

**Comment by songdemei** [comment]
This is very important.How long ?

**Comment by leaanthony** [comment]
We don't work to timescales. Sorry. Multiple windows is a pretty big API breaking change so it'll be in v3.

**Comment by songdemei** [comment]
Expect v3.

**Comment by leaanthony** [comment]
Supported in v3
