### ISSUE TITLE
wails build -webview2 embed   error!

### ISSUE THREAD

**Issue by mei2015** [wailsapp/wails#2168]
### Description

 wails build -webview2 embed  

![image](https://user-images.githubusercontent.com/10136065/205024176-a8a6f143-39d0-48af-b4d4-16a219d44edc.png)

### To Reproduce

wails build -webview2 embed  

and  to install  this exe  at other computer

![image](https://user-images.githubusercontent.com/10136065/205024176-a8a6f143-39d0-48af-b4d4-16a219d44edc.png)

### Expected behaviour

wails build -webview2 embed  

and  to install  this exe  at other computer

![image](https://user-images.githubusercontent.com/10136065/205024176-a8a6f143-39d0-48af-b4d4-16a219d44edc.png)

### System Details

```shell
windows 10
```

**Comment by leaanthony** [comment]
Yeah, this is working as intended. The thing that's embedded is the bootstrapper to download the runtime.

**Comment by mei2015** [comment]
> Yeah, this is working as intended. The thing that's embedded is the bootstrapper to download the runtime not the runtime itself.

why   i   "build -webview2 embed" , why  download webview2 , it's not embed the exe?

**Comment by mei2015** [comment]
> 是的，这正在按预期工作。嵌入的东西是用于下载运行时的引导程序，而不是运行时本身.

Can't you just wrap the runtime in there? Downloading can be cumbersome for offline users

**Comment by mei2015** [comment]
> Can't you just wrap the runtime in there? Downloading can be cumbersome for offline users

Can't you just wrap the runtime in there? Downloading can be cumbersome for offline users

**Comment by stffabi** [comment]
That would massively increase the binary size. Wails would also need to include this huge installer somewhere in the repo and possibly update them.

Microsoft distributes the Webview2 runtime through Windows Update, so almost all Windows users should have it already installed.

If you want a true offline experience, I would suggest you the following. Either use a [fixed runtime](https://wails.io/docs/reference/options#webviewuserdatapath) and distribute that by a [nsis installer](https://wails.io/docs/guides/windows-installer) with your app or include the standalone webview2 installer into the nsis installer.
