### ISSUE TITLE
frontend\wailsjs\runtime\package.json: Access is denied.

### ISSUE THREAD

**Issue by lytdev** [wailsapp/wails#2171]
### Description

$ wails dev
Wails CLI v2.2.0

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.

> frontend@0.0.0 dev
> vite

  VITE v3.2.4  ready in 543 ms

Vite Server URL: http://127.0.0.1:5173/
  ➜  Local:   http://127.0.0.1:5173/
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  ➜  Network: use --host to expose
  • Generating bindings: 2022/12/02 06:45:48 Error: open D:\data\work-kit-ui\frontend\wailsjs\runtime\package.json: Access is denied.

Done.
  • Generating application assets: Done.
  • Compiling application:
Build error - open D:\data\work-kit-ui\frontend\wailsjs\runtime\package.json: Access is denied.
No version running, build will be retriggered as soon as changes have been detected

  ERROR   CreateFile D:\data\work-kit-ui\frontend\wailsjs\runtime: Access is denied.
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### To Reproduce

1.wails dev
2. tell me Build error - open D:\data\work-kit-ui\frontend\wailsjs\runtime\package.json: Access is denied.
No version running, build will be retriggered as soon as changes have been detected

### Expected behaviour

do not delete wailsjs\runtime\package.json and it well work ok

### System Details

```shell
$ wails doctor
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Enterprise LTSC 2019
Version      | 1809 (Build: 17763)
ID           |
Go Version   | go1.18.3
Platform     | windows
Architecture | amd64

# Wails

Version  | v2.2.0
Revision | dc209d14626fcbf8bdd33219068731d8069c51d2
Modified | false

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 107.0.1418.62
npm        | N/A          | Installed | 8.1.2
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by lytdev** [comment]
when project is init clear，it work ok.
but i run npm install element-plus --save 
edit frontend/main.js
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'

const app = createApp(App)

app.use(ElementPlus)
app.mount('#app')
now  the project doesn`t work

**Comment by leaanthony** [comment]
You normally wouldn't import from dist. That might be your issue

**Comment by lytdev** [comment]
wouldn't import from dist.
