### ISSUE TITLE
Does a window manage multiple web pages or other windows through tabs?

### ISSUE THREAD

**Issue by moom-en** [wailsapp/wails#2172]
### Is your feature request related to a problem? Please describe.

Does a window manage multiple web pages or other windows through tabs? Similar to Google or edge browser

### Describe the solution you'd like

Similar to Google or edge browser

### Additional context

windows system

**Comment by leaanthony** [comment]
No. It's unlikely to ever support that.

**Comment by moom-en** [comment]
Are there any similar plug-ins or third-party libraries that can be given to me

**Comment by leaanthony** [comment]
I'm not aware of any. Good luck 👍
