### ISSUE TITLE
How to install/update from master, not lastes tag?

### ISSUE THREAD

**Issue by Vai3soh** [wailsapp/wails#2188]
Hello. 
I run cmd (install wails cli):
```go install github.com/wailsapp/wails/v2/cmd/wails@master``` and 
```
wails version
v2.2.0
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
If i run:
```go get -v -u github.com/wailsapp/wails/v2/cmd/wails@master```
this ok, update  go.mod 

And then i run ```wails dev``` this downgrade in go.mod to v2.2.0.

I want this commit (https://github.com/wailsapp/wails/pull/2152), how do I get it?

**Comment by mholt** [comment]
I had this problem too. #2107 apparently fixes it, but I'm having trouble testing it. Could you give it a try??

**Comment by Vai3soh** [comment]
> I had this problem too, in #2057. #2107 apparently fixes it, but I'm having trouble testing it. Could you give it a try??

I test (wails cli with patch), this worked with this commit:

```go get -u -v github.com/wailsapp/wails/v2@0581ad03b1c74ef6419a0f0e74554474ddb1bf19```
if use this version ```  v2.2.1-0.20221207075022-3f077d9bdb2a  ```, app not build, with err::
```imports github.com/wailsapp/wails/v2/internal/platform: build constraints exclude all Go files in /home/user/goproj/pkg/mod/github.com/wailsapp/wails/v2@v2.2.1-0.20221207075022-3f077d9bdb2a/internal/platform```

**Comment by mholt** [comment]
Yeah, same here. I think that's a separate issue.

**Comment by leaanthony** [comment]
The build issue is fixed as part of the right click event fix

**Comment by stffabi** [comment]
The build issues and the downgrade issue has been resolved on master.

Please feel free to reopen if you still encounter any problems with this.
