### ISSUE TITLE
Unable to access windows.runtime.EventsOn

### ISSUE THREAD

**Issue by xlanor** [wailsapp/wails#2193]
### Description

I'm unable to access window.runtime.EventsOn. How am I supposed to import it? console logging window shows no runtime field, and manually importing {EventsOn} or {EventsOnMultiple} from '../../wailsjs/runtime' results in an EventsOnMultiple being undefined.

### To Reproduce

Simply just using a clear template from one of the vue templates (https://github.com/misitebao/wails-template-vue) in this case. I understand that templates are not supported by wails in general, I'm just trying to figure out if I should be speaking to the author of that template or not.

### Expected behaviour

window.runtime should be accessible to utilise EventsOn

### System Details

```shell
Version:                v2.2.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Installed       20.10.17
gcc             build-essential         Installed       12.9ubuntu3
libgtk-3        libgtk-3-dev            Installed       3.24.33-1ubuntu2
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.38.2-0ubuntu0.22.04.2
npm             npm                     Installed       8.17.0
*nsis           nsis                    Installed       v3.08-2
pkg-config      pkg-config              Installed       0.29.2-1ubuntu3

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
You should open a bug on that repo, unless you can reproduce it on a standard Wails template 👍

**Comment by xlanor** [comment]
I've just reinatialised the environment with the latest wails template (`wails init -n intellimouse2 -t vue-ts`) in a new folder and am still seeing the same error.

How is EventsOn supposed to be imported?

**Comment by leaanthony** [comment]
It should be automatically there

**Comment by xlanor** [comment]
I've just initalised a new wails template from scratch via 

` wails init -n intellimouse2 -t vue-ts`

and inspected the window object, I dont see runtime being imported.

![image](https://user-images.githubusercontent.com/29213366/206874288-27d1cf40-aa72-44af-8421-08815249b79c.png)

If I do this
```
import { EventsOn } from '../../wailsjs/runtime'

EventsOn('test', ()=>{console.log('test')})
```

or

```
<script lang="ts" setup>
import * as runtime from '../../wailsjs/runtime'

runtime.EventsOn('test', ()=>{console.log('test')})

</script>
```

![image](https://user-images.githubusercontent.com/29213366/206874349-0452d6a8-c924-4095-9955-9cd6faece6a4.png)

This error occurs

If I do this

```
<script lang="ts" setup>
import {reactive} from 'vue'
import {Greet} from '../../wailsjs/go/main/App'
import {EventsOnMultiple} from '../../wailsjs/runtime'

const data = reactive({
  name: "",
  resultText: "Please enter your name below 👇",
})

function greet() {
  Greet(data.name).then(result => {
    data.resultText = result
  })
}

EventsOnMultiple('test', ()=>{console.log('test')}, -1)

</script>
```

![image](https://user-images.githubusercontent.com/29213366/206874428-4b38332a-3313-45a0-95dd-9e45c4e500a7.png)

The trace changes slightly, but the error is still present.

**Comment by xlanor** [comment]
This works fine in firefox, but not in chrome.

Using 108.0.5359.98 (Official Build) (64-bit)
