### ISSUE TITLE
TypeError: window.wails._.Init is not a function

### ISSUE THREAD

**Issue by grvlle** [wailsapp/wails#220]
**Description**

After running a build version of my app, it displays a blank screen, while the STDOUT logging states an inability to find the wails variable. Running it in the web browser using 'wails serve' works fine. The problem started occuring after updating wails to the pre version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'wails build'
2. Run the binary './binary_file'

**Expected behaviour**
I expect it to run in the same manner as in the web browser.

**Screenshots**
![2019-09-02_](https://user-images.githubusercontent.com/25682690/64127052-7f963780-cdb0-11e9-874f-4facde9a3c61.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.13-pre |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.1.0 |
| Npm           | v8.16.1 |
| Node          | 6.11.2 |

**Additional context**
Running Arch Linux.

**Comment by bh90210** [comment]
hello @grvlle can u please share which template you are using? or it is happening across templates?

**Comment by bh90210** [comment]
also please see this issue #211 as you seem to experiencing the same problem

**Comment by grvlle** [comment]
Hey @bh90210 !

Thanks for the quick reply. I actually resolved it by rebooting the computer. I suspect GTK to be at fault. I noticed that my runtime.Emits has stopped working. 

Js console:
```javascript
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'on' of undefined"

found in ---> <Dashboard> at src/pages/Dashboard.vue
       <DashboardContent> at src/layout/dashboard/Content.vue
         <DashboardLayout> at src/layout/dashboard/DashboardLayout.vue
           <App> at src/App.vue
             <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
callHook @ vue.runtime.esm.js?2b0e:4213
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6340
patch @ vue.runtime.esm.js?2b0e:6559
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
(anonymous) @ main.js?56d7:19
(anonymous) @ main.js?8607:169
Callback @ VM3963:1
Notify @ VM3963:1
(anonymous) @ VM3977:1
addScript @ main.js?8607:111
handleMessage @ main.js?8607:176
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'on' of undefined
    at VueComponent.mounted (Dashboard.vue?98fa:171)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at Object.insert (vue.runtime.esm.js?2b0e:3139)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6340)
    at Vue.patch [as __patch__] (vue.runtime.esm.js?2b0e:6559)
    at Vue._update (vue.runtime.esm.js?2b0e:3939)
    at Vue.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at new Watcher (vue.runtime.esm.js?2b0e:4462)
```

Function in Dashboard.vue:
```javascript
mounted() {
    window.wails.events.on("token", (amount) => {
      this.tokenAmount = amount;
    });
```

Corresponding Go function:
```go
func (w *Wallet) TokenAmount(runtime *wails.Runtime) {
	go func() {
		for {
			w.Balance = rand.Intn(3000000)
			runtime.Events.Emit("token", w.Balance)
			w.UpdateTokenCounter(10, runtime)
			time.Sleep(10 * time.Second)
		}
	}()
}
```

**Comment by grvlle** [comment]
Am I missing some documentation with regards to the latest version?

**Comment by bh90210** [comment]
I am under the impression that u should capitalize the JS function like so:
`window.wails.Events.On("token", (amount) => {`

yes, documentation is not update with latest `-pre` and there were some breaking changes in v0.17.6-pre I belive! (I am not actually sure about the exact tag, if you need we can investigate..) we are working on updating the docs as part of v1 release #208 

but if that doesn't work then @leaanthony has to step in cause my JS knowledge is failing me :)

**Comment by grvlle** [comment]
> I am under the impression that u should capitalize the JS function like so:
> `window.wails.Events.On("token", (amount) => {`

Your JS knowledge just out performed mine. A million thanks!!

**Comment by leaanthony** [comment]
Thanks for your patience @grvlle. I think we need to make a banner at the top of the doc site to indicate it's for the latest stable only. Which gives me an idea... Perhaps we should add a `wails docs` command to open up the docs relevant to the version installed?
