### ISSUE TITLE
Failed to find WebView2 (64bit Windows)

### ISSUE THREAD

**Issue by rahanahu** [wailsapp/wails#2208]
### Description

When only WebView2 runtime(x86) is installed on 64bit Windows. Application made by wails failed to found WebView2 and it only prompts to install webview2 and does not start. 

The user thinks he has installed webview2, and in fact the x86 version is installed, but it does not start because there is no x64.

### To Reproduce

1. install only WebView2 runtime(x86) on 64bit Windows
2. run `wails doctor`
3. Status of WebView2 becomes Available, not Installed.

### Expected behaviour

It would be better to be able to run wails application on 64bit Windows with only WebView(x86) runtime installed.
Current  `func findClientDllInFolder` searches only "EBWebView/x64" directory on amd64. I think it's better to search "EBWebView/x86" also.

If it's hard to use WebView2(x86) on 64bit Windows, I think it need to guide users as to which webview2 Runtime is needed.

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise
Version:        2009 (Build: 19045)
ID:             22H2
Go Version:     go1.19.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.2.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Available
npm             N/A             Installed       8.19.2
*upx            N/A             Installed       upx 4.0.0
*nsis           N/A             Available
```

**Comment by leaanthony** [comment]
This is not possible and not something we can support. If you want to run 64bit apps then you will need the 64bit dependencies 👍

**Comment by stffabi** [comment]
The main issue for this is caused by a Bug from Microsoft. The bootstrapper installer doesn't correctly install the 64bit version if a wrongly installed 32bit version is there. And there was also a time where Windows-Update did install 32bit runtime on a 64bit machine.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2794

**Comment by leaanthony** [comment]
@stffabi I thought he was talking about that too but on re-reading it looks like he wants 64bit Wails apps to work on 32bit Webview that was previously installed.

**Comment by stffabi** [comment]
Oh yeah, it's not very clear. Nevertheless it's good to have the two issues linked somewhere 😄

**Comment by rahanahu** [comment]
@stffabi Thanks. I asked how user installed webview2 and he said he used bootstrapper, so that clears up the cause.
