### ISSUE TITLE
any possible to debug with GoLand?

### ISSUE THREAD

**Issue by RonaldinhoL** [wailsapp/wails#2211]
### Describe the solution you'd like

idk what is it in wails dev, but it would be great if it could debug breakpoint with Goland

**Comment by leaanthony** [comment]
Create project with flags `-ide goland` 👍

**Comment by RonaldinhoL** [comment]
> -ide goland

great, thank you very much! :p

**Comment by RonaldinhoL** [comment]
i know how to debug, just use wails dev, then goland attach to the runing process

**Comment by mainjzb** [comment]
> i know how to debug, just use wails dev, then goland attach to the runing process

set `Go tool arguments` with: `-gcflags "all=-N -l" -tags dev -o build/bin/wailsProject.exe`
