### ISSUE TITLE
install wails on Macos failed.

### ISSUE THREAD

**Issue by conanchen** [wailsapp/wails#222]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**

# github.com/wailsapp/wails/cmd
go/src/github.com/wailsapp/wails/cmd/semver.go:21:3: cannot use semverVersion (type semver.Version) as type *semver.Version in field value
go/src/github.com/wailsapp/wails/cmd/semver.go:48:40: cannot use s.Version (type *semver.Version) as type semver.Version in argument to constraint.Validate
go/src/github.com/wailsapp/wails/cmd/semver.go:64:40: cannot use s.Version (type *semver.Version) as type semver.Version in argument to constraint.Validate
go/src/github.com/wailsapp/wails/cmd/semver.go:91:35: cannot use c[j].Version (type *semver.Version) as type semver.Version in argument to c[i].Version.LessThan

**To Reproduce**
Steps to reproduce the behaviour:
1. $ go version
go version go1.12.9 darwin/amd64
2. $ go get github.com/wailsapp/wails/cmd/wails

**Expected behaviour**

wails command can be installed

**System Details**
Macos 10.14.2

**Comment by leaanthony** [comment]
I can get an old version of wails installed if you don't use GO111MODULE, but apart from that, it seems to work ok?

```
leas-MacBook-Pro:Downloads lea$ go get github.com/wailsapp/wails/cmd/wails
leas-MacBook-Pro:Downloads lea$ wails --help
 _       __      _ __
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v0.15.0
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

Available commands:

   setup    Setup the Wails environment [default]
   init     Initialises a new Wails project
   build    Builds your Wails project
   serve    Run your Wails project in bridge mode
   update   Update to newer [pre]releases or specific versions
   issue    Generates an issue in Github

Flags:

  -help
    	Get help on the 'wails' command.

leas-MacBook-Pro:Downloads lea$ export GO111MODULE=on
leas-MacBook-Pro:Downloads lea$ go get github.com/wailsapp/wails/cmd/wails
go: finding github.com/wailsapp/wails/cmd/wails latest
go: finding github.com/wailsapp/wails/cmd latest
leas-MacBook-Pro:Downloads lea$ wails --help
 _       __      _ __
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v0.17.0
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

Available commands:

   setup    Setup the Wails environment [default]
   init     Initialises a new Wails project
   build    Builds your Wails project
   serve    Run your Wails project in bridge mode
   update   Update to newer [pre]releases or specific versions
   issue    Generates an issue in Github

Flags:

  -help
    	Get help on the 'wails' command.
```

**Comment by leaanthony** [comment]
I've managed to reproduce. This only happens if GO111MODULES is not set. Please install as [per the installation instructions](https://github.com/wailsapp/wails#installation-1) and you should be good. I will get master patched though so thanks for raising it.

**Comment by leaanthony** [comment]
This should now work as before. Please test and let us know 👍

**Comment by conanchen** [comment]
thanks @leaanthony ,

exactly, 
I put " export GO111MODULE=on " in .bash_profile and it works now.

**Comment by leaanthony** [comment]
Nice one. Master is also fixed so happy days 😃
