### ISSUE TITLE
app not startable if using "assetdir"

### ISSUE THREAD

**Issue by LU-386** [wailsapp/wails#2221]
### Description

Hey,

at first: thanks for your great work with wails!

We're using wails with ionic and `wails build` still utilizes the folder "./frontend/dist", even if "assetdir" was set to something different in wails.json. Our app works perfectly for `wails dev`, but does not even start with `wails build` (starting the binary in terminal states `index.html not found`).

Even if not utilized in `wails dev`, the folder "./frontend/dist" was recreated for `wails build` each time.
To proof my theory, I've put `<div>oisfoisjdfoij</div>` in "./frontend/dist/index.html" and build the app.
the app now and looked like this:

<img width="267" alt="Bildschirm­foto 2022-12-19 um 21 52 02" src="https://user-images.githubusercontent.com/85061979/208521689-cf3d2df7-db5b-42b3-8d58-d7053423e9c3.png">

### To Reproduce

1. create new project with `wails init -n github-assetdir-test`
2. `cd github-assetdir-test`
3. remove lines
````
  "frontend:install": "npm install",
  "frontend:build": "npm run build",
  "frontend:dev:watcher": "npm run dev",
  "frontend:dev:serverUrl": "auto",
```` 
and add `"assetdir": "./frontend/build/",` to wails.json

4. delete or rename frontend-folder to clear it up and add folters `build` and `dist` inside of `frontend`
5. put `<div>abc</div>` into `frontend/build/index.html`
6. put `<div>xyz</div>` into `frontend/dist/index.html`
7. check outputs of `wails dev` and `wails build`

### Expected behaviour

to have functional identical outputs for subcommands "build" and "dev"

### System Details

```shell
➜  github-assetdir-test wails doctor
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	13.1
ID:		22C65
Go Version:	go1.19.4
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.2.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2396
npm  				N/A 		Installed 	9.2.0
*upx  				N/A 		Installed 	upx 3.96
*nsis  				N/A 		Available 	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

The `assetdir` in wails.json is only seldom needed and does only affect `wails dev`. Have you tried to adjust your `go:embed` directive in `main.go` to point to your directory?

In your case this should look like this:
```go
//go:embed all:frontend/build
var assets embed.FS
```

Afterwards you can remove the `assetdir` directive and everything should work as expected, also `wails dev`.

**Comment by LU-386** [comment]
Thanks for your awnser.

This actually fixed my problem!

Is this a commonly known go-thing? Maybe you could add this in the docs.
