### ISSUE TITLE
Failing (pre|post)BuildHooks with no `build/bin` dir

### ISSUE THREAD

**Issue by prochac** [wailsapp/wails#2224]
### Description

If the `build/bin` directory is removed, or if the project is cloned, the `wails dev` fails on 
```
ERROR: chdir /.../my-wails-project-dir/build/bin: no such file or directory - 
```
The `build/bin` dir is automatically added to `.gitignore` file, so the directory isn't being pushed to repository. That leads to that the dir is missing if the repo is cloned.

### To Reproduce

```shell
wails init -n some-name
cd some-name
rm -r build
cat wails.json | jq '. + {"preBuildHooks": {"*/*": "echo"}}' | tee wails.json
# or
cat wails.json | jq '. + {"postBuildHooks": {"*/*": "echo"}}' | tee wails.json
wails dev
```

### Expected behaviour

The wails cli could create the directory instead of failing

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.19.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.2.0
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Installed       1:20.10.21-1
gcc             gcc             Installed       12.2.0-1
libgtk-3        gtk3            Installed       1:3.24.35-2
libwebkit       webkit2gtk      Installed       2.38.2-2
npm             npm             Installed       8.19.2-1
pkg-config      pkgconf         Installed       1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

Unfortunately I'm unable to reproduce this on macOS with Wails 2.2.0 by using your provided steps.

```bash
wails init -n some-name
cd some-name
rm -r build
wails dev
```

What version of Wails are you using? You mention something about BuildHooks in the title, but there's nothing mentioned in your repro guide.

**Comment by leaanthony** [comment]
Please provide system details as requested in the template. Thanks.

**Comment by prochac** [comment]
Oh, what a me :facepalm: 
Of course, the hooks has to been added.
I have updated the reproduction scenario, could you retry pls

**Comment by Lyimmi** [comment]
I can reproduce this with the provided steps on popOS.

It fails on `/v2/pkg/commands/build/build.go#L413`:

```golang 
stdout, stderr, err := shell.RunCommand(options.BinDirectory, args[0], args[1:]...)
```

If I check and create the directory in `/v2/pkg/commands/build/build.go#L88` it solves the problem.

```golang 
// Set build directory
options.BinDirectory = filepath.Join(options.ProjectData.GetBuildDir(), "bin")
if !fs.DirExists(options.BinDirectory) {
  if err := fs.MkDirs(options.BinDirectory); err != nil {
    return "", fmt.Errorf("cannot build, target directory missing %w", err)
  }
}
```

**Comment by Lyimmi** [comment]
I'd like to fix this.

Is it ok if I check and or create the directory in [/v2/pkg/commands/build/build.go:L407](https://github.com/wailsapp/wails/blob/c19f6f2502de0189cd44b5e88a64b807361e639a/v2/pkg/commands/build/build.go#L408-L407) before `shell.RunCommand()`
