### ISSUE TITLE
keep [Building project (this may take a while)] forever

### ISSUE THREAD

**Issue by conanchen** [wailsapp/wails#223]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
$ wails init
Wails v0.17.0 - Initialising project

The name of the project (My Project):
Project Name: My Project
The output binary name (my-project):
Output binary Name: my-project
Project directory name (my-project):
Project Directory: my-project
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 4
Template: Vuetify Basic
✓ Generating project...
⣷ Building project (this may take a while)...

**To Reproduce**
Steps to reproduce the behaviour:
1. $ wails init

**Expected behaviour**

init project sucessfully

**System Details**

macos/win7 

----------
What is Wails doing? there is not any detail message , just keep spinning.

**Comment by bh90210** [comment]
hmmm did u let enough time pass? also did u ever get an error or the process stop at `⣷ Building project (this may take a while)...`? if so, please let it finish, this indeed takes a while cause what is happening is wails runs in the background `npm install` which depending on your internet connection/computer cpu power takes some time

**Comment by bh90210** [comment]
can you please confirm that regardless of the hanging a new folder containing the project is created?
and if so can you please `cd new-project/frontend` and run `npm install`?

If the above steps are successful please try building the project with `wails build -d` from inside `new-project` (`cd ..` from `new-project/frontend`)

**Comment by leaanthony** [comment]
The last time someone reported this, it was just their internet connection. It does happen. As @bh90210 says, try running the npm commands manually and see what errors it gives.

**Comment by conanchen** [comment]
thanks @bh90210 @leaanthony , works now :

d:\git\wails-sample\my-project\frontend>npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> yorkie@2.0.0 install d:\git\wails-sample\my-project\frontend\node_modules\yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> core-js@2.6.9 postinstall d:\git\wails-sample\my-project\frontend\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1209 packages from 932 contributors and audited 24367 packages in 220.635s

found 0 vulnerabilities


----------------------------------------
d:\git\wails-sample\my-project>wails build -d
[33mWails[0m [31mv0.17.0[0m - Building Application

> Ensuring frontend dependencies are up to date (This may take a while)
> Building frontend...
> Ensuring Dependencies are up to date...
> Installing Mewn asset packer...
> Packing + Compiling project (Debug Mode)...
Awesome! Project 'My Project' built!

**Comment by conanchen** [comment]
> hmm did u let enough time pass?
> also did u ever get an error or the process stops at `⣷ Building project (this may take a while)...`?
> if so, please let it finish, this indeed takes a while cause what is happening in the background is wails running `npm install && npm run build` which depending on your internet connection/computer cpu power takes some time

I have spent a whole night but no luck to have Wails done.

**Comment by leaanthony** [comment]
Sounds like it's still an issue for you?
