### ISSUE TITLE
Tracking window state

### ISSUE THREAD

**Issue by merlinaudio** [wailsapp/wails#2238]
### Is your feature request related to a problem? Please describe.

https://github.com/wailsapp/wails/pull/1349

### Describe the solution you'd like

Hi y'all! I want to track the WindowState in react, but it seems there is no event for it?

I tried `EventsOn(":wails:window:maximised")` like in the PR, and `EventsOn(":wails:WindowIsMaximised")` but neither of them fire when the WindowState changes.

On a side note: Is there any documentation for the events from the wails runtime? If not, do we need some?
Where can I find these events? (CTRL+F `:wails:` I assume :P)

**Comment by leaanthony** [comment]
Hey thanks for opening this. There's already some window state methods available in the runtime library but I think we could do better here. Fancy a stab at it? 😅

**Comment by merlindru** [comment]
Yes! @leaanthony However, I can't let my frontend know when the window state changed with what's currently available in the runtime, right?

**Comment by merlindru** [comment]
I want to change the state of my maximize button depending on whether the window is currently maximized or not:

**Window is maximised:**
![image](https://user-images.githubusercontent.com/85179170/209438106-32aa48af-e7e3-40ca-9351-cdb5e787b057.png)

**Window is normal**
![image](https://user-images.githubusercontent.com/85179170/209438107-f5c0d415-d003-4323-b21b-0ea4b88af867.png)

**Comment by merlindru** [comment]
This is useful not only for frameless app's title bars, but for changing layout depending on the window state. My app can't know whether it's been maximised after the initial load without polling `WindowIsMaximised`

**Comment by oSethoum** [comment]
> I want to change the state of my maximize button depending on whether the window is currently maximized or not:
> 
> **Window is maximised** ![image](https://user-images.githubusercontent.com/85179170/209438106-32aa48af-e7e3-40ca-9351-cdb5e787b057.png)
> 
> **Window is normal** ![image](https://user-images.githubusercontent.com/85179170/209438107-f5c0d415-d003-4323-b21b-0ea4b88af867.png)

this could easily be achieved by adding an event listener on the resize event for the window and check for the window state after and update the UI accordingly.

**Comment by leaanthony** [comment]
This is now supported in v3 via events and a workaround is available for v2. Closing for now.
