### ISSUE TITLE
v2.2.2 build

### ISSUE THREAD

**Issue by 404669366** [wailsapp/wails#2240]
### Description

![image](https://user-images.githubusercontent.com/27764423/209454131-1f8cc5be-21b0-41ce-b83a-5e907cb788d6.png)

### To Reproduce

wails dev

### Expected behaviour

![image](https://user-images.githubusercontent.com/27764423/209454148-9be9f236-fe33-4a0b-8cdd-6570b72d8ac1.png)

### Screenshots

![b8385139797ce9b2a6f35771cecd566](https://user-images.githubusercontent.com/27764423/209454150-5e179032-8fe1-4f71-aae8-3dd69183cd63.png)

### Attempted Fixes

......

### System Details

```shell
....
```

**Comment by stffabi** [comment]
Wails '2.3.0' has been released which fixes this issue.
