### ISSUE TITLE
If program does not exit, "wails build" freezes forever

### ISSUE THREAD

**Issue by i7tsov** [wailsapp/wails#2249]
### Description

When the program contains code that prevents it from finishing, `wails build` command freezes after printing `Generating bindings` to the console.

I assume that Wails compiles and runs the program in order to generate bindings. `wails build` behavior is probably expected, but confusing nevertheless. 

### To Reproduce

1. Create an empty project: `wails init -n foo`, `cd foo`;
2. Open `main.go` and insert `select{}` statement at the end of the `main` function;
3. Run `wails build`;
4. Observe build process freezes on the `Generating bindings` step.

### Expected behaviour

It would be nice to have some sort of (maybe configurable) timeout on bindings generation command with a clear error message.

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Linux Mint
Version: 	20
ID:		linuxmint
Go Version:	go1.19
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.2.0
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker 	docker.io 		Installed 	20.10.3
gcc 		build-essential 	Installed 	12.8ubuntu1.1
libgtk-3 	libgtk-3-dev 		Installed 	3.24.20-0ubuntu1.1
libwebkit 	libwebkit2gtk-4.0-dev 	Installed 	2.38.2-0ubuntu0.20.04.1
npm 		npm 			Installed 	8.19.2
*nsis 		nsis 			Installed 	v3.05-2
pkg-config 	pkg-config 		Installed 	0.29.1-0ubuntu4

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
I'm not surprised this happens as the bindings generation is just a special build of your app. Are you sure you want an infinite loop in your app?

**Comment by i7tsov** [comment]
I didn't want infinite loop, it just happened due to the bug in the code. One innocent `wg.Add(1)` line suddenly made build process freeze, leaving me scratching the head (I would expect program to freeze, but not the build). 

I can't think of why I'd want to have program that would not exit immediately after `Run` ends, but maybe someone else can?

Anyway, I suppose, it worth at least an update in Troubleshooting section?

**Comment by leaanthony** [comment]
Yeah good point 👍 We'll move to static analysis as soon as we can which will make this problem go away. Are you happy to provide a PR for the troubleshooting section?

**Comment by i7tsov** [comment]
Yeah, sure!
