### ISSUE TITLE
Support WebView Hardware acceleration option

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#2264]
### Is your feature request related to a problem? Please describe.

Sometimes we need to be able to disable Hardware / GPU acceleration in webview.
I'd like to make it an app option, so developers can set it on start from a config (This way an application's users could switch it on and off for themselves theoretically), or baked in.

I have a solution for this on Windows and Linux, I'll make a PR when its ready.

### Describe the solution you'd like

I'd like to add a new WebviewGpuAcceleration property to the app options. With the following structure.

```golang 

// WebviewGpuAcceleration values used for determining the hardware acceleration policy.
//   - WebviewGpuAccelerationOff
//   - WebviewGpuAccelerationOn
//   - WebviewGpuAccelerationOnDemand
type WebviewGpuAcceleration int

const (
	// WebviewGpuAccelerationOn Hardware acceleration is always enabled, even for websites not requesting it.
	WebviewGpuAccelerationOn WebviewGpuAcceleration = 0
	// WebviewGpuAccelerationOnDemand Hardware acceleration is enabled/disabled as request by web contents. (linux only falls back to "on" on windows)
	WebviewGpuAccelerationOnDemand WebviewGpuAcceleration = 1
	// WebviewGpuAccelerationOff Hardware acceleration is always disabled, even for websites requesting it.
	WebviewGpuAccelerationOff WebviewGpuAcceleration = 2
)
```

Usage would look like this:

```golang

err := wails.Run(&options.App{
  Title:            "wailst",
  Width:            1024,
  Height:           768,
  Assets:           assets,
  BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 0},
  OnStartup:        app.startup,
  Frameless:        true,
  CSSDragProperty:  "--wails-draggable",
  CSSDragValue:     "drag",
  Bind: []interface{}{
	  app,
  },
  Windows: &windows.Options{
	  WindowIsTranslucent:  true,
	  WebviewIsTransparent: true,
  },
  WebviewGpuAcceleration: options.WebviewGpuAccelerationOff, // <- it would be set here
})
```

### Additional context

On Windows it can be set via browser flags in chromium.
On Linux it can be set via `webkit_settings_set_hardware_acceleration_policy(s,o)`
On macOs as far as I can tell this is not an option to be set. (Can't find anything about it in the docs.)

**Comment by leaanthony** [comment]
Thanks for opening this and yes, it would be a great option. I'd suggest making it a per platform option as one option may work better for Linux than Windows.

**Comment by Lyimmi** [comment]
Ok.

In that case windows only needs a `WebviewGpuDisabled` bool, because the only option really is to initialize the webview with the `--disable-gpu` flag or not. 

And Linux would have the three constants. (I'd rename them, so it reflects the GTK options better.)

```golang
// WebviewGpuPolicy values used for determining the webview's hardware acceleration policy.
type WebviewGpuPolicy int

const (
	// WebviewGpuPolicyAlways Hardware acceleration is always enabled.
	WebviewGpuPolicyAlways WebviewGpuPolicy = 0
	// WebviewGpuPolicyOnDemand Hardware acceleration is enabled/disabled as request by web contents.
	WebviewGpuPolicyOnDemand WebviewGpuPolicy = 1
	// WebviewGpuPolicyNever Hardware acceleration is always disabled.
	WebviewGpuPolicyNever WebviewGpuPolicy = 2
)

```


The app option would look like this.

```golang
err := wails.Run(&options.App{
		Title:  "wailst",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},
		Windows: &windows.Options{
			WebviewGpuDisabled: true,
		},
		Linux: &linux.Options{
			WebviewGpuPolicy: linux.WebviewGpuPolicyNever,
		},
	})
```

**Comment by leaanthony** [comment]
I think that looks good. Thoughts?

**Comment by Lyimmi** [comment]
If you ask me I'm ok with this.

Linux is already done, windows with the new Go WebView2Loader is done, but some reason I Can't wrap my head around the old webview loader. :)

I was able to make it not crash, but it needs a pointer to an environmentOption for the additionalBrowserArgs but there are package and struct visibility issues...

Is it okay to not support it with the new loader?

**Comment by stffabi** [comment]
Awesome 👍

> Is it okay to not support it with the old loader? (Since it'll be dropped.)

Yeah I'm fine with that.
