### ISSUE TITLE
cannot rebuild binary

### ISSUE THREAD

**Issue by estenssoros** [wailsapp/wails#227]
**Description**

I noticed that new methods I was adding to a bound struct were not showing up during ``wails serve``. I removed the binary from the application folder and attempted ``wails serve``. Now I cannot run ``wails serve`` and am getting a "no such file or directory" error. ``go build`` returns ``./../../../pkg/mod/github.com/!masterminds/sprig@v2.20.0 incompatible/semver.go:4:2: case-insensitive import collision: "github.com/Masterminds/semver" and "github.com/masterminds/semver"``. When I run ``wails build``, the command exits successfully, however, there is no new binary in the directory.

**To Reproduce**
1. add or remove methods from struct
2. delete binary from application
3. run wails serve

**Expected behaviour**
The binary should be rebuilt each time in the project directory. Changes made to the methods on the bound struct should show in the new binary. If wails encounters errors creating a new build, the errors should be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/13590629/64457607-4d3a5200-d0b0-11e9-9f14-aa1ab8c589e0.png)
![image](https://user-images.githubusercontent.com/13590629/64457585-3b58af00-d0b0-11e9-9442-db362da6ba1a.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.6 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |

**Additional context**

**Comment by leaanthony** [comment]
That's odd. I can't reproduce locally. Here's what I tried:

# React Test 1 (GO111MODULE unset)

```
mv ~/go ~/go.backup
# Check GO111MODULE is not set
go get github.com/wailsapp/wails/cmd/wails
wails init
```

Select react and it builds and works. 

Change main.go to:
```
package main

import (
	"github.com/leaanthony/mewn"
	"github.com/wailsapp/wails"
)

// Test is a test struct
type Test struct {
}

// Ping back
func (t *Test) Ping() string {
	return "Pong"
}

func main() {

	js := mewn.String("./frontend/build/static/js/main.js")
	css := mewn.String("./frontend/build/static/css/main.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 768,
		Title:  "reacttest",
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})
	app.Bind(&Test{})
	app.Run()
}
```

and `HelloWorld.js:` to:

```
  handleOpenModal() {
    this.setState({ showModal: true });

    window.backend.Test.Ping().then(result =>
      this.setState({
        result
      })
    );
  }
```

`wails build`. This works fine.

## React Test 2 (GO111MODULE=on)

```
rm -rf ~/go
export GO111MODULES=on
go get github.com/wailsapp/wails/cmd/wails
wails init
```

Select React. This build and works.

Make the same changes as React Test 1. `wails build` and it works.

**Comment by estenssoros** [comment]
After updating to go 1.13 this issues has been resolved.
