### ISSUE TITLE
sveltekit based template not working, generated exe doesn't start.

### ISSUE THREAD

**Issue by jingkang99** [wailsapp/wails#2270]
### Description

try to create a sveltekit based template. 2 available templates on github are broken. 

all commands executed fine, but generated exe doesn't start.

maybe wails doesn't support sveltekit's folder based routing. 

thanks

### To Reproduce

npm create svelte@latest sveltekit-base

wails generate template -name wails-sveltekit-template -frontend ./sveltekit-base/

wails init -n test1-sveltekit -t ./wails-sveltekit-template/
----
tried in dev mode, no response.
npm run dev
wails dev

![image](https://user-images.githubusercontent.com/10793075/210648011-09e54789-c631-41a1-8568-da83f69c02ca.png)

### Expected behaviour

it is better giving an example of how to use routing within sveltekit
https://wails.io/docs/community/templates

### System Details

```shell
$ wails doctor
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Education
Version      | 2009 (Build: 19045)
ID           | 22H2
Go Version   | go1.19.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 108.0.1462.54
npm        | N/A          | Installed | 9.2.0
*upx       | N/A          | Installed | upx 3.96
*nsis      | N/A          | Available |
* - Optional Dependency
```

**Comment by stffabi** [comment]
Thanks for using Wails and creating this issue.

Those are community templates that aren't directly maintained by the Wails Core team. So it would be the best if you open issues on those repositories.

@plihelix created a new template recently https://github.com/plihelix/wails-sveltekit maybe you could give that template a try.

**Comment by stffabi** [comment]
I'm going to close this issue, since there's a new community template for sveltekit.

Please feel free to reopen if you have any further questions related to this issue.
