### ISSUE TITLE
Unexpected code highlighting

### ISSUE THREAD

**Issue by SheetJSDev** [wailsapp/wails#2280]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Some of the code blocks in the docs have changed.  The highlights are specified with line numbers but those were not updated.

For example https://wails.io/docs/howdoesitwork#method-binding 

<img width="740" alt="howdoesitwork" src="https://user-images.githubusercontent.com/6070939/211230609-8391357e-b50e-4968-a79e-9975065ba915.png">

When the highlights were last set (commit dce5fd442fe2d68d0bea68f82f890f6bb9e5a568), the equivalent of lines 17 (`app := &App{}`) and 27 (`app,`) were highlighted.

After that commit, two more commits added lines to the code block without updating the highlights.

It looks like the wails.io is using Docusaurus.  It supports [special comments for highlighting lines](https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-comments).

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Oh nice catch! I'll fix that tonight
