### ISSUE TITLE
wails dev | run main function multiple times

### ISSUE THREAD

**Issue by hanaTsuk1** [wailsapp/wails#2284]
### Description

wails dev run main function multiple times, when the ldflags parameter is included, only the last time ldflags has an initialization value

### To Reproduce

1.git clone https://github.com/hanaTsuk1/wails.git
2.wails dev -ldflags="-X 'main.param=world'"
3.view the output file

### Expected behaviour

Only one line says "helloworld"

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 19044)
ID           | 21H2
Go Version   | go1.19.1
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 108.0.1462.54
npm        | N/A          | Installed | 6.10.0
*upx       | N/A          | Installed | upx 4.0.1
*nsis      | N/A          | Installed | v3.08
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by sebastian0x62** [comment]
During the build, `wails dev` runs your program multiple times with different build tags for binding generation. The wails app exits automatically. The final call actually runs and shows your app.

**Comment by hanaTsuk1** [comment]
I notice that the question of ldflags was answered in another issue(https://github.com/wailsapp/wails/issues/2310)
Since running multiple times is a designed behavior, I will close it
