### ISSUE TITLE
[VueJS] Watched data not being updated upon change in Wails. Browser works fine.

### ISSUE THREAD

**Issue by netrounds-martin** [wailsapp/wails#229]
**Description**

I've set up a function to monitor a .json file for changes. If I manipulate the json file, the browser will immediately update to show the new value. The Wails app will not however. I've attempted to achieve the same thing with multiple implementations, none seem to work in Wails app.

**To Reproduce**

```Vue

<template>
{{table2.data}}
</template>

import TransactionHistory from '../../../JSONdata/tx.json';

<script>
export default {
watch: {
    TransactionHistory: function () {
      this.table2.data = TransactionHistory
    }
},

data() {
table2: {
data: [TransactionHistory]
}
}
}
</script>
```

Steps to reproduce the behaviour:
1. Go to browser and watch TransactionHistory items being displayed.
2. Open tx.json in editor and manipulate the Json object 
3. Observe the webbrowser refreshing to display the new value
4. Build Wails App, watch TransactionHistory items being displayed.
5. Open tx.json in editor and manipulate the JSON object
6. Observe the wails app not refreshing to display the new value

**Expected behaviour**
I would expect the wails app to refresh to show the new value. The same goes when a form is submitted.

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.14-pre |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 7.4.0 |
| Npm           | v12.10.0 |
| Node          | 6.10.3 |

**Additional context**

**Comment by leaanthony** [comment]
Hi. That'll never work as content is compiled into the binary. The reason it works in `serve` mode is that there is a hot-reloader at play. If you really want to do this in the binary, you need to use a file watcher and runtime events to notify the frontend of changes. This is covered in the (TODO tutorial](https://wails.app/tutorials/todo.html), specifically in the [Tracking File Changes](https://wails.app/tutorials/todo.html#tracking-file-changes) section. Hope that helps.

**Comment by netrounds-martin** [comment]
I feel like I've been through it a million times - yet I still missed this part. Thank you, it all makes a lot more sense now.
