### ISSUE TITLE
MacOS: Binary works, but packaged application does crash (cgo?)

### ISSUE THREAD

**Issue by mkohns** [wailsapp/wails#2295]
### Description

HI! I have implemented an application using BLE (BlueTooth Low Energy). 

I am using this golang lib for BLE
-> https://github.com/go-ble/ble
which uses
-> https://github.com/JuulLabs-OSS/cbgo

In dev mode (wails dev) all is FINE. Runs all like a charm.
The packaged version starts up, but when invoking adapter initialization from BLE it crashes and generates report.
When I open the binary (of the package i.e. build/bin/mytime.app/Contents/MacOS/mytime) from within the console. It is working also FINE. No problems.

dev (wails dev) -> OK
build/bin/appname.app/Contents/MacOS/appname -> OK
double click appname.app -> CRASH

I digged deeper and found, that the problem is related with the call.
When I remove this, the package works fine.

```
import "github.com/go-ble/ble/darwin"
d, err := darwin.NewDevice()
```

which itself calls 

```
import ""github.com/JuulLabs-OSS/cbgo""
cbgo.NewCentralManager(nil) // device.go:37
```

From here the code looks like

```
func NewCentralManager(opts *ManagerOpts) CentralManager {
[crash.report.zip](https://github.com/wailsapp/wails/files/10411402/crash.report.zip)

	if opts == nil {
		opts = &DfltManagerOpts
	}

	pwrAlert := C.bool(opts.ShowPowerAlert)

	restoreID := (*C.char)(nil)
	if opts.RestoreIdentifier != "" {
		restoreID = C.CString(opts.RestoreIdentifier)
		defer C.free(unsafe.Pointer(restoreID))
	}

	return CentralManager{
		ptr: unsafe.Pointer(C.cb_alloc_cmgr(pwrAlert, restoreID)),
	}
}
```
I do not understand that dev mode and direct binary is working fine - just my ".app" - is crashing.
I added -debug to the build. But there are no relevant information inside the crash report.
[crash.report.zip](https://github.com/wailsapp/wails/files/10411407/crash.report.zip)

Does anyone have an idea how I could debug this?

### To Reproduce

1. Create fresh wails project (i.e. wails init -n myproject -t vue)
2. go get github.com/go-ble/ble
3. add OnDomReady callback in main.go (or use any other entrypoint you like)
4. add 	
```
func (a *App) domReady(ctx context.Context)  {
	d, err := darwin.NewDevice()
	if err != nil {
		runtime.LogErrorf(ctx, "can't new device : %s", err)
		return 
	}
	ble.SetDefaultDevice(d)
}
```
5. make sure in wails dev it is working
6. run wails build
7. Start the app by double clicking in finder or by installing in "Application"
8. App will crash
9. Start the binary directly from the console i.e. build/bin/myproject.app/Contents/MacOS/myproject
10. This works

### Expected behaviour

App runs

### Attempted Fixes

I tried to move the code block to various places. Triggered by Frontend, Backend and Go routines w/o delay.
I tested different go versions and different cbgo versions

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 12.6.2
ID           | 21G320
Go Version   | go1.19.4
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2395
npm                       | N/A          | Installed | 8.19.2
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by leaanthony** [comment]
Thanks for the detailed report. .app bundles are generally more restricted. It could be that you need to add Bluetooth permissions to your info.plist.

**Comment by mkohns** [comment]
The first time the app started - a popup came up asking me. I Allowed it. But i will google for the right info.plist attribute.

**Comment by mkohns** [comment]
@leaanthony!! Thanks a lot for pointing me to point!
Adding the following to the info.plist did the trick!!

```
        <key>NSBluetoothAlwaysUsageDescription</key>
        <string>This App is using BLE in order to connect your Timeular Device</string>
        <key>NSBluetoothPeripheralUsageDescription</key>
        <string>This App is using BLE in order to connect your Timeular Device</string>        
```

Thank you very much for the quick help!! 
Fantastic!
