### ISSUE TITLE
Can't use "wails" command after install.

### ISSUE THREAD

**Issue by best2000** [wailsapp/wails#231]
im using window i installed it using "go get...." then i use "wails setup" but it say that "wails" is not regcognize
i already installed gcc.

sorry for bad eng.

**Comment by leaanthony** [comment]
Did that fix it?

**Comment by best2000** [comment]
> Did that fix it?

yes, thank you very much 
i just do a fresh install and set everything correctly and it works as it should be.

**Comment by leaanthony** [comment]
Thanks @bh90210 for your help on this! Glad it worked @best2000.
