### ISSUE TITLE
'wails' is undefined when opening app

### ISSUE THREAD

**Issue by Madzahttr** [wailsapp/wails#233]
I'm having an issue with my app.
When served, it works as intended.
When built, the shows no errors during the build, but when opened, it gives an error, see screenshot below

![screenshot](https://i.madzahttr.com/fbd1a.png)

as far as i know, everything is the latest version.

Building the original example app worked fine

**Comment by leaanthony** [comment]
Please provide a link to your source. Thanks.

**Comment by Madzahttr** [comment]
oh yeah, forgot about that link, sorry.
https://github.com/Madzahttr/VueTest

**Comment by Madzahttr** [comment]
I removed the vue router functionality and the app now works, is there a reason why the vue router doesn't work?

**Comment by Madzahttr** [comment]
also, is there any way to use devtools with this? I see the `DisableInspector` in appconfig, but even when setting that to false, pressing f12 or ctrl+shift+i still doesn't seem to work

**Comment by leaanthony** [comment]
Thanks for the updates.

> I removed the vue router functionality and the app now works, is there a reason why the vue router doesn't work?

This has been raised before and honestly, I've no idea. There's a ticket for it [here](https://github.com/wailsapp/wails/issues/150). There are a million and one Javascript frameworks and libraries and for sure not all will work in an environment they weren't intended for (plain webview - not a browser). I'd love to get an answer to this though.

> also, is there any way to use devtools with this? I see the DisableInspector in appconfig, but even when setting that to false, pressing f12 or ctrl+shift+i still doesn't seem to work

Unfortunately, for whatever reason, the underlying [Webview](https://github.com/zserge/webview) library we use doesn't seem to support it. [This ticket](https://github.com/zserge/webview/issues/140) suggests using firebug.

Windows support is admittedly behind the others and WebView is lacking in support and I want to [replace it](https://github.com/wailsapp/wails/issues/235). Any help on that front would be great.

On a side note, we don't have a dedicated Windows support person. If you're interested in improving Windows support, let me know.

**Comment by Madzahttr** [comment]
Cool, thanks.
one last thing, how would i go about building the app for a different OS and what ones are supported?

**Comment by leaanthony** [comment]
Cross compilation isn't something we've looked at. The only solution right now is to compile on each of the OSes you wish to support. This list is in the documentation: Linux, Mac and Windows for now.
