### ISSUE TITLE
White screen after adding sandbox entitlement (MacOS)

### ISSUE THREAD

**Issue by udfalkso** [wailsapp/wails#2349]
### Description

The issue I'm running into is that when running my application in dev or after building it works great.  It is only when I sign it and add the sandbox entitlement that the UI stops working.  The Go backend is still functional after this, and I see log entries from there.  But, the UI will not render.  I just get a blank white screen and can't figure out why.

Am I doing something wrong?  Is wails somehow incompatible with the sandbox environment?  Any help or pointers would be greatly appreciated!  Thanks

### To Reproduce

The attached zip file contains a minimal example that reproduces the issue on my machine.  All of my code has been removed.  It's just a "hello world" react example at this point, along with my set of entitlements.  

To reproduce:
1. Edit `macappstore-build.sh` script to refer to your own certifications / dev identity
2. run `./macappstore-build.sh`
3. run `./build/bin/SearchEm.app/Contents/MacOS/SearchEm` and you'll get a white screen

[CodeSignWhiteScreen.zip](https://github.com/wailsapp/wails/files/10609675/CodeSignWhiteScreen.zip)

### Expected behaviour

When running via `wails dev` or just `wails build` there should be a UI rendered saying "Hello Hi".  

When signing and adding entitlements there is a white screen instead.  

### Screenshots

<img width="828" alt="Screenshot 2023-02-04 at 4 11 48 PM" src="https://user-images.githubusercontent.com/2029383/216789802-8356b86b-b172-4756-854b-2a4c519f5060.png">

<img width="858" alt="Screenshot 2023-02-04 at 4 12 35 PM" src="https://user-images.githubusercontent.com/2029383/216789807-63350d94-6b70-4465-989a-862dd2371afe.png">

### System Details

```shell
(uf_d..dbox)[udi:searchem_go/app]$ wails doctor
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	13.1
ID:		22C65
Go Version:	go1.19.2
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.1.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2396
npm  				N/A 		Installed 	8.15.0
*upx  				N/A 		Available 	
*nsis  				N/A 		Available 	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment]
There are a couple of guides that may help:

https://wails.io/docs/guides/troubleshooting#my-application-is-displaying-a-whiteblank-screen

https://wails.io/docs/guides/mac-appstore

**Comment by udfalkso** [comment]
Thanks @leaanthony I used those guides to get as far as I've gotten, but I'm still running into this issue.  Any ideas?  I'll keep trying but I'm a bit stuck.  Thanks!!

**Comment by udfalkso** [comment]
I've reproduced this with a vanilla project from `wails init`.  

1. `wails init -n myproject -t react`
2. Copied in my entitlements files
3. The UI renders when I run `wails dev`
4. However, running `./macappstore-build.sh` followed by `./build/bin/myproject.app/Contents/MacOS/myproject` I get a white screen only.  

Possibly a bug in wails?  Or am I doing something wrong with the entitlements?  Thx!

**Comment by stffabi** [comment]
Can you try using a debug build `wails build --debug` and take a look into the inspector? Maybe it gives us some hint why the frontend is not showing up.

**Comment by udfalkso** [comment]
Thanks @stffabi  I made a debug build but I didn’t know there’s a way to open the inspector. How do I do that?

**Comment by stffabi** [comment]
Just right click and you should see a context menu with an entry "inspect element".

**Comment by udfalkso** [comment]
Thanks again @stffabi.  Unfortunately no context menu comes up when I right click :(  

Any other ideas?

**Comment by stffabi** [comment]
Hmm strange...

Maybe try the openinspectoronstartup flag, as defined here https://wails.io/docs/reference/options#openinspectoronstartup

That should open the inspector at startup.

You need a debug build 'wails build --debug' for this flag to work.

**Comment by leaanthony** [comment]
Maybe related, maybe not: https://forum.qt.io/topic/141868/macos-catransaction-synchronize-called-within-transaction/3
https://stackoverflow.com/questions/75019134/catransaction-synchronize-called-within-transaction-with-nssavepanel
https://developer.apple.com/forums/thread/722889

**Comment by leaanthony** [comment]
What happens if you double click the .app file rather than running the binary inside the bundle?

**Comment by udfalkso** [comment]
Same result.  White screen, no inspector, no context menu on right click.  

Have you been able to reproduce using the vanilla project I uploaded?  Thx!

**Comment by leaanthony** [comment]
I'd try going through the entitlements and removing some to pinpoint if it's a specific one at this point

**Comment by bofeng** [comment]
I had the same issue yesterday, and I am able to solve it to add these 4 lines in the entitlement file:
```xml
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
```
It has been a year, so I am not sure if @udfalkso you are still having this issue, but in your project file you posted above, I found that you were also missing these 4 lines of code. I guess it is needed because wails is essentially setting up a webserver with go, although it is a local server, the client still needs the network connection permission.
