### ISSUE TITLE
Replace WebView

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#235]
WebView is somewhat unsupported and is missing some features that will be essential moving forward:

- A stable WKWebView engine for Mac
- Edge Support for Windows (including devtools)
- Easy ability to extend it to support native platform features

The leading candidate as an alternative is [Deskgap](https://github.com/patr0nus/DeskGap), although a call for a [C library version](https://github.com/patr0nus/DeskGap/issues/14) has been met with silence, despite the demand.

**Comment by Madzahttr** [comment]
with devtools, it'd be nice to have the ability to install an extention like [Vue Devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) or have it built in

**Comment by leaanthony** [comment]
@Madzahttr you can do this by using `wails serve` which bridges your app to your local browser.

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Comment by leaanthony** [comment]
Looks like WebView is dead so this will be a priority.
https://github.com/zserge/webview/issues/271

**Comment by winwisely99** [comment]
The new Webview is now done. 
Thanks @zserge 

It would be great if wails can support this.
