### ISSUE TITLE
！！！ JavaScript API WindowSetSize return value is null, not promise 

### ISSUE THREAD

**Issue by aishuaikang** [wailsapp/wails#2351]
### Description

 JavaScript API WindowSetSize return value is null, not Promise

### To Reproduce

 Call JavaScript API WindowSetSize directly 

### Expected behaviour

The type signature is Promise, and the printed log is undefined 

### Screenshots

<img width="828" alt="image" src="https://user-images.githubusercontent.com/68257609/216809770-48b5a026-780a-4a09-b785-71635381c68a.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/68257609/216809783-44e43c67-17fa-4c9e-a5c7-5268f9d207aa.png">

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro     
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version      
WebView2   | N/A          | Installed | 109.0.1518.70
npm        | N/A          | Installed | 9.3.1        
*upx       | N/A          | Installed | upx 4.0.2    
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by aishuaikang** [comment]
@leaanthony

**Comment by aishuaikang** [comment]
This problem is caused by a runtime.d.ts generation error generated by wails dev. It has been half a year and has not been solved yet.

**Comment by aishuaikang** [comment]
<img width="1351" alt="image" src="https://github.com/wailsapp/wails/assets/68257609/8b50fb4a-1828-4c9e-b456-13ffdd2683ce">
Is it difficult to achieve this part?

**Comment by aishuaikang** [comment]
And in some cases, I need to wait to modify the window size and execute some logic, but I need to wait asynchronously.

**Comment by leaanthony** [comment]
Feel free to make a PR?

**Comment by leaanthony** [comment]
Updated the definitions in the templates. The setters don't return promises and won't without significant work.
