### ISSUE TITLE
Pass Command Line Arguments to main.go

### ISSUE THREAD

**Issue by akuehnis** [wailsapp/wails#2353]
### Is your feature request related to a problem? Please describe.

My application uses an SQLite database. 

During development (``` wails dev ```) a different database shall be used than in production.

### Describe the solution you'd like

Pass command line arguments through to main.go.

Example:

```wails dev usedevdatabase```

In main.go the usedevdatabase should be available in os.Args

### Describe alternatives you've considered

I have tried to get the environment from the app.ctx (buildtype). However due to my applications layout the database must be initialized before App.Run(). I could not find another way to detect the buildtype.

Currently I am using a text file 'environment.txt' that I modify manually or using a shell script and then embed it. That is an error-prone workaround, of course:

```
//go:embed environment.txt
var environment string

func main.go(){
   if (environment == "dev"){
      // init dev database 
   } else {
     // init prod database
   }
}

```

**Comment by JoiLa** [comment]
You can  try shell example `wails dev -appargs "database_mode=sqlite"`. 

then in main.go file, you should  first call `flag.Parse()` function , then at call `flag.Args` and for each `args`  do someting...

**Comment by akuehnis** [comment]
@JoiLa , thank you very much. This is exactly what I was looking for.
