### ISSUE TITLE
Windows Webview2, Keyboard UK Extended, Typing German Umlaut

### ISSUE THREAD

**Issue by akuehnis** [wailsapp/wails#2359]
### Description

I am using a keyboard 'United Kingdom Extended' on Windows. This allows me to type German Umlaute (ä, ö, ü) as follows:

<kbd>Alt Gr </kbd>+ <kbd>2</kbd>, then <kbd>A</kbd>, <kbd>O</kbd> or <kbd>U</kbd>

Unfortunately this does not work in the Wails/Webview2. Instead, the 'normal' letters are typed (a, o, u).

### To Reproduce

1. Create the default wails app `wails init -n myproject -t vue` and start it
2. Select the keyboard layout 'United Kingdom Extended'
3. As greet-name (input field) type <kbd>Alt Gr </kbd>+ <kbd>2</kbd> followed by <kbd>U</kbd>  which should type ü 

Result: 
The letter entered is a 'u' instead of 'ü'

### Expected behaviour

<kbd>Alt Gr </kbd>+ <kbd>2</kbd> - <kbd>U</kbd> should type 'ü'
<kbd>Alt Gr </kbd> +<kbd> 2</kbd> - <kbd>O</kbd> should type 'ö'
<kbd>Alt Gr </kbd> +<kbd> 2</kbd> - <kbd>A</kbd> should type 'ä'

### Attempted Fixes

- When I connect a keyboard with a german layout, then it is possible to type umlaute using the specific keys.
- Running the standard example from github.com/jchv/go-webview2, I can enter umlaute with a United Kindom Extended keyboard layout as expected. Therefore I assume the problem is something related to wails.

### System Details

```shell
# System

OS           | Windows 10 Home
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.19.5
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 109.0.1518.78
npm        | N/A          | Installed | 8.14.0
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.08
```

**Comment by leaanthony** [comment]
Thanks for opening this. Have a check on the webview2 feedback repo and see if it's a known issue. If not, I'll check to see what the deal is with AltGr

**Comment by akuehnis** [comment]
I have checked these pages:

- https://github.com/MicrosoftEdge/WebView2Feedback/issues
- https://github.com/jchv/go-webview2/issues

Unfortunately I haven't found any feedback or issue related. Thank you for looking into this.

**Comment by leaanthony** [comment]
A fix was added above. Please feel free to reopen if this is still an issue.
