### ISSUE TITLE
Windows NSIS, Shortcuts for Non-Admin Users

### ISSUE THREAD

**Issue by akuehnis** [wailsapp/wails#2365]
### Is your feature request related to a problem? Please describe.

When a Non-Admin user installs the Wails-App using Wail's default NSIS installer file, there are neither desktop nor program links created for the user. 

My understanding of what is happening:

- RequestExecutionLevel is 'admin'.
- SetShellVarContext default value is 'current'. As 'current' is 'admin', only the admin does get program links.

### Describe the solution you'd like

The default NSIS should add `SetShellVarContext all` in the installer section and the uninstaller section, just before 'CreateShortcut' and 'Delete'.

/build/windows/installer/poject.nsi
```
...
Section
    !insertmacro wails.webview2runtime

    SetOutPath $INSTDIR
    
    !insertmacro wails.files
    SetShellVarContext all
    CreateShortcut "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"
    CreateShortCut "$DESKTOP\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"

    !insertmacro wails.writeUninstaller
SectionEnd

Section "uninstall" 
    RMDir /r "$AppData\${PRODUCT_EXECUTABLE}" # Remove the WebView2 DataPath

    RMDir /r $INSTDIR

    SetShellVarContext all
    Delete "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${INFO_PRODUCTNAME}.lnk"

    !insertmacro wails.deleteUninstaller
SectionEnd
```

### Describe alternatives you've considered

I have tried to set 

```
RequestExecutionLevel user
```
However, then the non-admin user could not install the app because of no write access to C:\Program Files.

**Comment by stffabi** [comment]
Sorry, I've misread your issue. Yeah when an non-admin installs it, and does get elevated then it will only install it into the admin locations. So your proposed solution fixes that. It would not work with `RequestExecutionLevel user` but that seems not to work currently as you mentioned.

**Comment by stffabi** [comment]
PR #2373 is up to improve this.
