### ISSUE TITLE
What about WebGL?

### ISSUE THREAD

**Issue by shturnev** [wailsapp/wails#237]
**Description**
I found that the browser wrapper does **not support WebGL**. How to fix this?
**this is critical**, because it is not possible to use such an important tool as a three.js

`THREE.WebGLRenderer: Error creating WebGL context.`

**Screenshots**
![Снимок экрана 2019-09-15 23:03:34](https://user-images.githubusercontent.com/19683461/64926981-13362200-d80d-11e9-9d68-9375bbd1ce66.png)

**System Details**
Ubuntu 19.04, GO 1.13v

**Comment by leaanthony** [comment]
Hi. WebGL isn't supported by the underlying WebView library, however a quick search there reveals [this issue](https://github.com/zserge/webview/issues/144) with some workarounds for Linux. 
We are looking to [replace WebView](https://github.com/wailsapp/wails/issues/235) after the v1 release and implement feature flags. WebGL will definitely be something we look at.

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Comment by domino14** [comment]
the wiki seems to be gone. Is WebGL supported now?
