### ISSUE TITLE
How to get the full path of the file selected by the frontend

### ISSUE THREAD

**Issue by saucer-man** [wailsapp/wails#2375]
### Is your feature request related to a problem? Please describe.

I have some software requirements, that is, select certain files at the front end, and then perform operations on these files at the back end, such as type conversion and the like. So I need to pass the filepath from the frontend to the golang backend, but the wails can't seem to get the full filepath from the frontend

### Describe the solution you'd like

same as https://github.com/wailsapp/wails/discussions/1484，my hope is when I use `<input type="file" id="fileImage" name="fileImage" @change="showImg">`， then I can get full filepath in frontend

### Describe alternatives you've considered

I read the way Electron obtained the file path, just look at this: https://stackoverflow.com/questions/38530293/electron-get-full-path-of-uploaded-file. But in wails，This does not work.

**Comment by lic-8** [comment]
I think you can't get the absolute path of a file uploaded from the front-end and it's for security reasons. 

To get the full path of a file, you must select the file from the back using `github.com/wailsapp/wails/v2/pkg/runtime`.

**Comment by saucer-man** [comment]
Yes, I've searched around and found no feasible solution. But if it can only be obtained from the backend, there is no way to operate on the visual interface, and desktop software has no meaning......

**Comment by leaanthony** [comment]
V3 should have native DnD. It's already working for Mac but will operate at the window level, probably not the webview level.

**Comment by stffabi** [comment]
What about using the [OpenFileDialog](https://wails.io/docs/reference/runtime/dialog#openfiledialog)? That allows you to get the full path of a selected file.

**Comment by saucer-man** [comment]
> What about using the [OpenFileDialog](https://wails.io/docs/reference/runtime/dialog#openfiledialog)? That allows you to get the full path of a selected file.

This is exactly what I need, great, thanks

**Comment by lic-8** [comment]
OpenFileDialog is backend

**Comment by saucer-man** [comment]
> OpenFileDialog is backend

Yes, it is my omission. It is unrealistic to obtain the complete path from the front end. Obtaining from the back end can also achieve the same purpose. I didn't read the complete document of runtime before. Anyway, thank you

**Comment by dunkbing** [comment]
hi @saucer-man, can the file selected by the backend be displayed on the frontend? For example, I want to display a video file on a <video> tag.

**Comment by emeraldls** [comment]
@dunkbing did you find a solution to this? Im trying to display a video file in the frontend also

**Comment by Yogeshhpal** [comment]
@saucer-man , @emeraldls 
Did you find any solution?
The user selects a .txt file, and we need to send the complete network drive path of that file to the Nest backend.
