### ISSUE TITLE
[Question] v3 ?

### ISSUE THREAD

**Issue by lic-8** [wailsapp/wails#2376]
Hi,

Could you give an ETA for the release of the v3 ? Also, will the transition to v3 break v2 projects like the transition between v1 and v2 ?

Thank you

**Comment by leaanthony** [comment]
No and yes 😅

**Comment by lic-8** [comment]
Thanks, I understand better now ! xD

**Comment by leaanthony** [comment]
Of course, if you'd like to contribute....

**Comment by stffabi** [comment]
I think we could close this one.

Please feel free to also join us on discord there's plenty of insights and discussions on v3 in several threads there.

**Comment by istiak101** [comment]
@leaanthony maybe I can send a PR to build RPM package with wails build command. Should I go for v3 or v2?

**Comment by leaanthony** [comment]
That would be awesome 😎 We have a dedicated Wails3 channel on discord where we coordinate development effort. Feel free to join us.

**Comment by istiak101** [comment]
> That would be awesome 😎 We have a dedicated Wails3 channel on discord where we coordinate development effort. Feel free to join us.

Unfortunately I don't use discord.

Also can you add a security policy (https://github.com/wailsapp/wails/security) where to contact in case of security issue? I want to report something I found during development.

**Comment by leaanthony** [comment]
@istiak101 - Thanks for the query. The security button at the top should allow you to report any issues.
WRT rpms, it would be better for v3 for sure but it's up to you!

**Comment by istiak101** [comment]
> @istiak101 - Thanks for the query. The security button at the top should allow you to report any issues. WRT rpms, it would be better for v3 for sure but it's up to you!

I will write up a report short away. I also think v3 is good candidate for new feature. I can't build a binary successfully with built in templates. I will wait for beta/rc stage.

**Comment by leaanthony** [comment]
Wait what? Someone has released a v3 app on the Mac AppStore. How are you not able to build a template?
