### ISSUE TITLE
Support Distribution 'LinuxMint'

### ISSUE THREAD

**Issue by P0NE** [wailsapp/wails#238]
**Description**
Distribution 'LinuxMint' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | LinuxMint |
| Distribution Version   | 18.3 |
| Discovered by   | lsb |

**Comment by bh90210** [comment]
hello @P0NE 
mint is supported in the latest `-pre` release.

U can update via `wails update -pre`

**Comment by P0NE** [comment]
Thanks! I will test it ;)

**Comment by leaanthony** [comment]
Any updates?

**Comment by P0NE** [comment]
Works fine ! Thanks
