### ISSUE TITLE
Local file upload only show fakepath

### ISSUE THREAD

**Issue by longit123** [wailsapp/wails#2383]
### Is your feature request related to a problem? Please describe.

I want to use [input type=file] select a local file, then i only get `c:\fakepath\xxx.csv`

if i want use golang to parse the file, i can't get the real local file path

i saw `electron` can get the real local file path [link](https://github.com/electron/electron/blob/v1.2.8/docs/api/file-object.md)

### Describe the solution you'd like

can you add the api or some way to get the real local path?

**Comment by stffabi** [comment]
Thanks for using Wails and opening this issue.

Have you taken a look into the [OpenFileDialog](https://wails.io/docs/reference/runtime/dialog#openfiledialog)? That opens a file selection dialog and you get the full path.

**Comment by longit123** [comment]
> Thanks for using Wails and opening this issue.
> 
> Have you taken a look into the [OpenFileDialog](https://wails.io/docs/reference/runtime/dialog#openfiledialog)? That opens a file selection dialog and you get the full path.


Thank u very much!!!

There is another small problem: the official document is accessed with the edge browser, often stuck, status: STATUS_BREAKPOINT

**Comment by stffabi** [comment]
> There is another small problem: the official document is accessed with the edge browser, often stuck, status: STATUS_BREAKPOINT

Unfortunately I don't understand what you mean by this. Could you please elaborate in more detail when you see this and what triggers that issue?

**Comment by leaanthony** [comment]
Closing due to lack of feedback,
