### ISSUE TITLE
I hope to support the use of the webview tag in the Vue framework.

### ISSUE THREAD

**Issue by geekroscom** [wailsapp/wails#2387]
### Is your feature request related to a problem? Please describe.

I'm trying to use the webview tag to embed a remote page in Vue, but it seems like it's not supported!

```
[Vue warn]: Failed to resolve component: webview
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <ChatGPTDialog key=3 ref="chatGPTDialog" app= {loading: {…}, return: {…}, account: {…}}  ... > 
  at <Start onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > app= {loading: {…}, return: {…}, account: {…}} > 
  at <RouterView ref="routerView" > 
  at <App>
```

### Describe the solution you'd like

This is an example：

```
<template>
    <webview ref="webviewBox" class="chat-view" src="wails.io"></webview>
</template>

<script lang="ts">
...
```

### Describe alternatives you've considered

No

**Comment by leaanthony** [comment]
Hi. Thanks for opening this. We don't control what webviews support. Have you opened a ticket on the various webview projects themselves?

**Comment by robomentor** [comment]
> Hi. Thanks for opening this. We don't control what webviews support. Have you opened a ticket on the various webview projects themselves?

Previously, it was often used in Electron.

**Comment by leaanthony** [comment]
Wails doesn't embed a browser. That's the trade-off. We can't add functionality that isn't there.

**Comment by leaanthony** [comment]
Closing as we can't support this.
