### ISSUE TITLE
Getting rid of CGO for Linux and MacOS too (now possible)

### ISSUE THREAD

**Issue by tapir** [wailsapp/wails#2388]
### Is your feature request related to a problem? Please describe.

At the moment wails can dynamically load DLLs in windows but not on any other platform.

### Describe the solution you'd like

https://github.com/ebitengine/purego is implemented by the developer of Ebiten (a 2D game engine for Go) and basically allows to do the same for non-windows platforms too.

### Describe alternatives you've considered

I don't believe any alternatives exist at the moment.

**Comment by leaanthony** [comment]
I've tried this for macOS and it was really hard to get working. In fact, I was unable to get the equivalent of "get shared application and run" working. It's like it didn't want to own the run loop. Have you had more success?

**Comment by tapir** [comment]
Unfortunately I only have access to Linux and Windows thus I can't comment on MacOS but maybe @hajimehoshi could.

**Comment by hajimehoshi** [comment]
You should be able to call most of Cocoa APIs. See an example https://github.com/ebitengine/purego/blob/main/examples/objc/main_darwin.go

**Comment by leaanthony** [comment]
I think the difference between this and what I was trying was this is using the objc runtime to build objects whereas what I was trying to do was run the main event loop via `[NSApp run]`. That seemed to exit immediately. I'm very excited about the possibilities here though. An ideal match for this project.

**Comment by tapir** [comment]
I'm glad you find it an ideal match as I believe it really compliments wails philosophy. Hoping it works!

**Comment by leaanthony** [comment]
Thanks for bringing this to our attention. We support the project and look forward to using it in the future when the time is right 👍
