### ISSUE TITLE
unable to open popup

### ISSUE THREAD

**Issue by Albinzr** [wailsapp/wails#2389]
### Description

[Error] [GSI_LOGGER]: Failed to open popup window on url: https://XXXXXXXXXXXX.com. Maybe blocked by the browser?
	(anonymous function) (client:45:213)
	(anonymous function) (client:181)
	Hp (client:250:141)
	(anonymous function) (client:247:359)
	(anonymous function) (client:228:178)
	Wb (client:59:107)

### To Reproduce

try to open a popup or new link

### Expected behaviour

open an internal window or popup

.

### Screenshots

null

### Attempted Fixes

null

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 12.6    
ID           | 21G115  
Go Version   | go1.19.4
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2395   
npm                       | N/A          | Installed | 8.19.2 
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

**Comment by stffabi** [comment]
Thanks for bringing up this issue and using Wails.

Could you please give us a minimal reproduction guide on what you are trying to achieve? And what your frontend code looks like that triggers this?

**Comment by Albinzr** [comment]
Im using react and on click of a button Im opening a popup, Which is causing this issue.

**Comment by stffabi** [comment]
@Albinzr could you please post a minimal reproduction guide with code?

**Comment by misitebao** [comment]
If you want to open another window to view it when you click the URL in the window, we do not recommend this for the time being. v2 does not support multiple windows for the time being, so it is recommended to use the default browser to open it. There are two specific implementation methods. Please refer to [here](https://github.com/wailsapp/wails/discussions/1898).

**Comment by ctkai01** [comment]
I have the same error when using  I clicked login with Google to open a popup choose account Google login (ReactJS)

**Comment by ctkai01** [comment]
` const login = useGoogleLogin({
    onSuccess: (codeResponse) => {
      console.log(codeResponse);
      setUser(codeResponse);
    },
    onError: (error) => console.log("Login Failed:", error),
  });`
  
  Here my code runs when clicking the button login with Google (browser still working) but the application being the above error failed to open the popup window on URL

**Comment by Albinzr** [comment]
I had moved back to Electron since I go stuck in between the development and was not moving anywhere

There should be some simple way to support any kind of sso login like google and to open popups, URL, etc...
Which are the very basic building block
I found it super hard where each corner there is a block and no solution

so I had to move back, I really liked using this but cant take it forward with all missing blocks
