### ISSUE TITLE
[MacOS] `.mjs` files are served as `text/plain`, throwing errors

### ISSUE THREAD

**Issue by aymeric-giraudet** [wailsapp/wails#2390]
### Description

Hi ! 
I'm using SvelteKit's static adapter which outputs `.mjs` files and imports them dynamically via `import`, but the asset server doesn't seem to set the proper `Content-Type` for `.mjs` files which is expected by WebKit to be `text/javascript`, instead we get `text/plain` which causes the following thrown error : 

> `TypeError: 'text/plain' is not a valid JavaScript MIME type.`

### To Reproduce

1. Clone https://github.com/aymeric-giraudet/wails-mjs
2. `wails build -debug`
3. Run built MacOS application
4. Inspect element to open DevTools
5. See the error

### Expected behaviour

`Content-Type` for `.mjs` files should be `text/javascript`

### Attempted Fixes

I'm using a middleware to handle serving `.mjs` files myself because of that but it's a lot of work, I've seen a [PR being merged](https://github.com/wailsapp/wails/pull/2286) which makes it so that `Content-Type` is no longer overridden, but there hasn't been a new build yet.

### System Details

```shell
# System

OS           | MacOS
Version      | 13.2
ID           | 22D49
Go Version   | go1.19.1
Platform     | darwin
Architecture | arm64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2396
npm                       | N/A          | Installed | 8.19.3
*Xcode                    | N/A          | Installed | 14.2 (14C18)
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by stffabi** [comment]
Thanks for using Wails and bringing up this issue.

I've published PR #2391 which fixes this issue.
