### ISSUE TITLE
return multiple values from Go to Js

### ISSUE THREAD

**Issue by dataflowjs** [wailsapp/wails#2395]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Multiple return values is not supported or i do something wrong?

```go
func (a *App) TestReturn() (string, string) {
    return "1", "asdf"
}
```

```js
function test() {
   window.go.main.App.TestReturn().then(function(arg1, arg2) {
       console .log(arg1, arg2) 
   }
}

test();
```

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Use a struct and you'll be good 👍

**Comment by mcosta74** [comment]
> Could someone provide an example to do this?
> 
> I am trying to return a file name to javascript from Go.
> 
> ```go
> type File struct {
> file string  `json:"file"`
> err string `json:"error"`
> }
> 
> func (a *App) SelectFile() File {
> file, err := runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
> 		Title: "Select a file",
> 	})
> return File{file: file, err: err}
> }
> ```
> 
> In the frontend I have function which should get the result
> 
> ```js
> SelectFile().then((data) => {
>       console.log("The data is : ", data)
> })
> ```
> 
> The data is just an empty object in this case. Am I doing something wrong?

You need to have exported fields in the struct otherwise JSON marshalling doesn't work

```go
type File struct {
    File string  `json:"file"`
    Err string `json:"error"`
}
```
