### ISSUE TITLE
[v2][macOS][Catalina] SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.

### ISSUE THREAD

**Issue by zllovesuki** [wailsapp/wails#2396]
### Description

Running `wails dev` will start the frontend correctly, but the app is blank. Opening the Inspector shows `SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.`

Curiously, opening http://localhost:34115 in Safari will load correctly. Please see screenshot below for comparison.

My guess is that the supporting JavaScript in wails uses some features that Safari on Catalina do not support.

### To Reproduce

Clone [zllovesuki/phantom](https://github.com/zllovesuki/phantom) and run wails dev

### Expected behaviour

Frontend should show app content

### Screenshots

<img width="1312" alt="Screen Shot 2023-02-21 at 1 11 29 PM" src="https://user-images.githubusercontent.com/298453/220460102-e8e327ce-6476-4f33-adc7-3b8df0d3d55d.png">

### System Details

```shell
❯ wails doctor
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 10.15.7
ID           | 19H2026
Go Version   | go1.20.1
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2373
npm                       | N/A          | Installed | 9.3.1
*Xcode                    | N/A          | Installed | 12.2 (12B45b)
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Could you open the error and work out which line number it's on please.

**Comment by zllovesuki** [comment]
The issue is that console does not tell me which line the error is from, only saying it is from `promiseReactionJob`

**Comment by zllovesuki** [comment]
Seems like it may be an issue with vuejs and vite. Closing this issue as this is not a problem on wails side

**Comment by pizsd** [comment]
> Seems like it may be an issue with vuejs and vite. Closing this issue as this is not a problem on wails side

Hello, how did you solve this problem, did you use related tools to convert the unsupported syntax into a supported syntax? I have the same problem as you

**Comment by zllovesuki** [comment]
@pizsd in my case it was caused by @headlessui/vue and its default esbuild target to es2019. This was causing errors on Catalina's WebKit. I had to fork the library and rebuild it with esbuild target to es2016.
