### ISSUE TITLE
How to use pipeline or streaming between frontend and backend

### ISSUE THREAD

**Issue by longit123** [wailsapp/wails#2405]
### Is your feature request related to a problem? Please describe.

eg: backend has running a cmd, it needs to show the cmd std output  message to the frontend immediately.

i don't find streaming or pipeling usage in the docs

### Describe the solution you'd like

Any solution to get the backend cmd stdout to the frontend immediately???

**Comment by leaanthony** [comment]
This is a question better suited for discord as it's neither a bug report or an enhancement request 👍 

https://discord.com/invite/JDdSxwjhGf
