### ISSUE TITLE
Asset Server for API call

### ISSUE THREAD

**Issue by sebheitzmann** [wailsapp/wails#2407]
### Description

I've tried to use the asset server to handle some api call. My http Api is already written for another usage. So i've tried to add my Api route on a custom asset server.

It works but with a little problem.
All POST or PUT call are transformed to GET request and I loose the body of the request. 
I can't understand why ?
Is this normal ? Can i write some code to bypass this ?

### To Reproduce

?

### Expected behaviour

asset server should be called with the caller HTTP METHOD

### Attempted Fixes

That my code.

```go
type KiwiLoader struct {
	http.Handler
	router *mux.Router
}

func NewKiwiLoader() *KiwiLoader {
	return &KiwiLoader{router: GetMuxRouter()}
}

func (h *KiwiLoader) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	var match mux.RouteMatch
	fmt.Println("check", req.URL.Path, req.Method)
	if h.router.Match(req, &match) {
		handler := match.Handler

		fmt.Println("ROUTE MATCH", match.Handler, req.URL.Path, req.Method, match.MatchErr)
		handler.ServeHTTP(res, req)
		fmt.Println("END ", req.URL.Path)
		return
	}
	res.WriteHeader(http.StatusBadRequest)
	res.Write([]byte(fmt.Sprintf("Could not load url %s", req.URL.Path)))

}

// guiCmd represents the gui command
var wguiCmd = &cobra.Command{
	Use:   "wgui",
	Short: "Start GUI(wails)",
	Run: func(cmd *cobra.Command, args []string) {
		// Create an instance of the app structure
		app := kiwi.NewApp()
		// Create application with options
		err := wails.Run(&options.App{
			Title:    "Kiwi Backup",
			Width:    1200,
			Height:   900,
			LogLevel: logger.DEBUG,
			AssetServer: &assetserver.Options{
				Handler: NewKiwiLoader(),
			},
			BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
			OnStartup:        app.Startup,
			Debug: options.Debug{
				OpenInspectorOnStartup: true,
			},
		})
``` 

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version   | go1.19.5
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.3.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 20.10.22               
gcc        | build-essential       | Installed | 11.3.0                 
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2       
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.4-0ubuntu0.22.04.1
npm        | npm                   | Installed | 9.2.0                  
*nsis      | nsis                  | Available | 3.08-2                 
pkg-config | pkg-config            | Installed | 0.29.2                 
* - Optional Dependency
```

**Comment by stffabi** [comment]
Thanks for opening this issue and using Wails.

> All POST or PUT call are transformed to GET request 
That's a limitation of older webkit2gtk versions < 2.36.0, you could build against 2.36+ with the build tag `webkit2_36` and you will get the correct http methods. See also this [note](https://wails.io/docs/reference/options#fn-1) and the [assetserver feature matrix](https://wails.io/docs/reference/options#assetserver). 

> and I loose the body of the request. I can't understand why ?

Unfortunately webkit2gtk doesn't provide the ability to get the request body of a request. This is still not possible up to the current latest version stable 2.38 and unstable 2.39 versions. 

So there's nothing we can currently do about this. As soon as webkit2gtk supports this feature, we can add that to the assetserver pretty fast.

**Comment by sebheitzmann** [comment]
That's a very clear explenation. Thank you very much.

I can close this issue
