### ISSUE TITLE
Possible to load remote url like https://www.baidu.com

### ISSUE THREAD

**Issue by InfernalAzazel** [wailsapp/wails#2410]
1. Possible to load remote url like https://www.baidu.com
2. Can I modify the request header?

**Comment by stffabi** [comment]
Thanks for using Wails and opening this issue. 

This is currently not possible, please also see #1516 for a more detailed discussion about this topic. Loading external url will be possible with the upcoming v3, but there's no timeframe for a final release of v3.

**Comment by stffabi** [comment]
Duplicate of #1516
