### ISSUE TITLE
Open Multiple Directories Dialog

### ISSUE THREAD

**Issue by favbox** [wailsapp/wails#2411]
### Describe the solution you'd like

In many file management applications, selecting multiple folders is a common operation.

In the module of wails frontend, we hava already OpenMultipleFilesDialog, but we hava no OpenMultipleDirectoriesDialog.

**Comment by leaanthony** [comment]
This will be supported in v3 👍 
Feel free to reopen if there's anything else to discuss 👍

**Comment by plane55** [comment]
When will v3 be released?

**Comment by PylotLight** [comment]
> When will v3 be released?

when its ready. no eta
