### ISSUE TITLE
Allow to pass custom window style mask on macOS

### ISSUE THREAD

**Issue by aymericbeaumet** [wailsapp/wails#242]
I'm looking to use Wails to open borderless windows on macOS.

This can be done with [NSWindowStyleMask](https://developer.apple.com/documentation/appkit/nswindowstylemask?language=objc) (implemented [here](https://github.com/wailsapp/webview/blob/e4dd88f9833a7ff2915312445546e8f864f8caa9/webview.h#L1939-L1951)).

I like your [flags approach](https://github.com/wailsapp/wails/issues/73#issuecomment-526788750), it's quite flexible. Maybe it could be implemented like this:

```go
app := wails.CreateApp(&wails.AppConfig{
  Flags: wails.Flags{ "NSWindowStyleMask": wails.NSWindowStyleMaskBorderless },
})
```

**Comment by leaanthony** [comment]
Hi @aymericbeaumet - I've actually tried implementing this before in the WebView code an got a degree of success. The problem was that when I created the borderless window, you could not move it (no titlebar) as the clicks were getting picked up by the WebView component. It would require someone with much better knowledge of Obj-C to do this. I'm absolutely up for it though and would like to do it. Thoughts?

**Comment by leaanthony** [comment]
FYI, I left that code in [here](https://github.com/wailsapp/wails/blob/develop/lib/renderer/webview/webview.h#L1948-L1951) if you want to try it out

**Comment by aymericbeaumet** [comment]
> when I created the borderless window, you could not move it (no titlebar) as the clicks were getting picked up by the WebView component

To me this feels like the expected behaviour, hiding the title bar is an advanced move and you should know what you are getting into when using this feature. So what you did was actually in the good direction imo.

For example in [Alacritty](https://github.com/jwilm/alacritty/tree/9a14ca42d35e3b72ca254384ef7e4639aab0e100) when you use the [`decorations: none` option](https://github.com/jwilm/alacritty/blob/9a14ca42d35e3b72ca254384ef7e4639aab0e100/alacritty.yml#L43-L52) you cannot move the window with the mouse anymore.

**Comment by leaanthony** [comment]
If you're ok doing a PR, I'll look at it :-)

**Comment by aymericbeaumet** [comment]
For the moment I have switched to implemented my own ObjC wrapper in Rust, but I keep this issue in mind :)

**Comment by leaanthony** [comment]
Ok. I'm going to close this as an issue as it's already on the TODO list for post V1. Feel free to reopen if needed.
