### ISSUE TITLE
 exit status 1 after wails dev/wails build

### ISSUE THREAD

**Issue by SouJhin** [wailsapp/wails#2420]
### Description

It doesn't start the project

### To Reproduce

cd redis-client
wails dev or wails build
it also doesn't work when i use command 'go build -tags bindings'
![image](https://user-images.githubusercontent.com/117504437/221346534-6be299dd-1898-464d-ac3a-31cb6a05e5d3.png)

### Expected behaviour

I wish it could start the projecy, not log 
`C:\Users\soujhin\go\pkg\mod\github.com\wailsapp\wails\v2@v2.3.1\internal\platform\win32\window.go:70:3: cannot use CW_USEDEFAULT (untyped int constant 2147483648) as int value in argument to CreateWindowEx (overflows)`

### Screenshots

![image](https://user-images.githubusercontent.com/117504437/221346478-90935e88-4397-47cd-8acc-604453acc472.png)

### System Details

```shell
win11
wails doctor

OUTPUT:
# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.50
npm        | N/A          | Installed | 8.19.2
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

what should I do?

**Comment by leaanthony** [comment]
Thanks for opening this. Are you using 32bit?

**Comment by stffabi** [comment]
That's already fixed on master with #2257 and only affects windows on 32bit

**Comment by SouJhin** [comment]
no, I'm using 64bit, does win11 has 32bit version?

**Comment by SouJhin** [comment]
no, I'm using 64bit, does win11 has 32bit version?

**Comment by SouJhin** [comment]
my problem hasn't been resolved, I'm sure win11 only publish 64bit version
