### ISSUE TITLE
compile: version "go1.18.8" does not match go tool version "go1.18.10"

### ISSUE THREAD

**Issue by Hehejie1** [wailsapp/wails#2425]
### Description

The execution of the go install github.com/wailsapp/wails/v2/cmd/wails@latest prompts the compiler error, and no successful installation package

### To Reproduce

1. cd ~
2. go install github.com/wailsapp/wails/v2/cmd/wails@latest

### Expected behaviour

Successful installation

### Screenshots

<img width="501" alt="image" src="https://user-images.githubusercontent.com/33722738/221390485-10b0d7f2-6dda-4955-9974-3135bf41955c.png">

### System Details

```shell
go version go1.18.10 darwin/amd64
```

**Comment by leaanthony** [comment]
Sounds like a local Go installation issue as this isn't a Wails error

**Comment by Hehejie1** [comment]
I used brew to install go locally. At the beginning, go1.19 prompted an error, and then I installed go1.18 version and still got an error. Should I uninstall and reinstall it?

**Comment by Hehejie1** [comment]
I found this installed using go install is placed in $GOPATH/pkg instead of in $GOPATH/bin

**Comment by Hehejie1** [comment]
Solution, I uninstalled go package, and then installed the pkg package
