### ISSUE TITLE
wails CLI recognize my system as 32bit

### ISSUE THREAD

**Issue by SouJhin** [wailsapp/wails#2426]
### Description

I have reported the BUG yesterday,  but it doesn't get my project work, I'm working on win11 which only publish 64bit version, however, wails report win32 BUG on terminal
`wails doctor` report that my system version was win10 21H2
I don't know how to resolve it

### To Reproduce

⬢  D:\codingProjects [12:09:09]❯ > cd .\newTest\
⬢  D:\..\newTest [12:09:14]❯ > npm --version
8.19.2
⬢  D:\..\newTest [12:09:17]❯ > wails doctor
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Home China
Version      | 2009 (Build: 22000)
ID           | 21H2
Go Version   | go1.20
Platform     | windows
Architecture | 386

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.50
npm        | N/A          | Installed | 8.19.2
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
⬢  D:\..\newTest [12:09:39]❯ > wmic os get osarchitecture
OSArchitecture
64 位

⬢  D:\..\newTest [12:09:47]❯ > wails dev
DEB | Using go webview2loader
Wails CLI v2.3.1

Executing: go mod tidy
  • Generating bindings:
  ERROR
          # github.com/wailsapp/wails/v2/internal/platform/win32
          C:\Users\soujhin\go\pkg\mod\github.com\wailsapp\wails\v2@v2.3.1\internal\platform\win32\window.go:69:3: cannot use CW_USEDEFAULT (untyped int constant 2147483648) as int value in argument to CreateWindowEx (overflows)
          C:\Users\soujhin\go\pkg\mod\github.com\wailsapp\wails\v2@v2.3.1\internal\platform\win32\window.go:70:3: cannot use CW_USEDEFAULT (untyped int constant 2147483648) as int value in argument to CreateWindowEx (overflows)
          C:\Users\soujhin\go\pkg\mod\github.com\wailsapp\wails\v2@v2.3.1\internal\platform\win32\window.go:71:3: cannot use CW_USEDEFAULT (untyped int constant 2147483648) as int value in argument to CreateWindowEx (overflows)
          C:\Users\soujhin\go\pkg\mod\github.com\wailsapp\wails\v2@v2.3.1\internal\platform\win32\window.go:72:3: cannot use CW_USEDEFAULT (untyped int constant 2147483648) as int value in argument to CreateWindowEx (overflows)

          exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### Expected behaviour

64bit version

### System Details

```shell
⬢  D:\..\newTest [12:09:17]❯ > wails doctor
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Home China
Version      | 2009 (Build: 22000)
ID           | 21H2
Go Version   | go1.20
Platform     | windows
Architecture | 386

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.50
npm        | N/A          | Installed | 8.19.2
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Fixed on master 👍 
The OS string is what Windows reports. The internet is full of people talking about it.
