### ISSUE TITLE
wails dev in docker

### ISSUE THREAD

**Issue by zuiwuchang** [wailsapp/wails#2432]
### Description

I created a docker for wails image for development. When I execute wails dev in docker, wails reports that everything is normal, but I can’t access devserver. Wails suggests that it is working normally, but I use netsl -ntl to find that there is no Any listener listens on port 34115

### To Reproduce

1. run my wails image, then attach it
  ```
  docker run --name wails -d king011/dev-wails:1.19.5
  docker exec -u dev -it wails bash
  ```

2. create a new project

  ```
  cd ~/project && wails init -n myproject -t svelte-ts && cd myproject 
  ```

3. execute wails  dev

  ```
  wails  dev
  ```

### Expected behaviour

devserver works fine after doing wails dev in docker so that I can use devserver for development

### Screenshots

After executing `wails dev` in the figure below, it prompts that devserver is already working `Using DevServer URL: http://localhost:34115`
![dev](https://user-images.githubusercontent.com/14151213/221892484-d388b12b-cda9-4079-8762-a23162bf82b7.jpg)

In fact, the devserver does not work properly, please see the picture below
![netstat](https://user-images.githubusercontent.com/14151213/221892508-88bb713f-d8eb-4906-8483-a6556c558345.jpg)

### Attempted Fixes

https://www.google.com/search?q=wails+dev+in+docker&rlz=1C1SQJL_zh-CNRU787SG787&oq=wails+dev+in+docker&aqs=chrome..69i57j69i64j69i60l3.6313j0j7&sourceid=chrome&ie=UTF-8

https://www.google.com/search?q=wails+devserver+docker&newwindow=1&rlz=1C1SQJL_zh-CNRU787SG787&sxsrf=AJOqlzUqRBj02WmfzAS5aeJjEvZl-eJxog%3A1677596763544&ei=Wxj-Y_ruIMbM0PEPtJeCwAo&ved=0ahUKEwi6iKv5vrj9AhVGJjQIHbSLAKgQ4dUDCA8&uact=5&oq=wails+devserver+docker&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIHCCEQoAEQCjIHCCEQoAEQCjIHCCEQoAEQCjoKCAAQRxDWBBCwAzoECCMQJzoECAAQQzoFCAAQgARKBAhBGABQ7AFY0j9gyUBoAXABeACAAZ8FiAH6DpIBBTQtMy4xmAEAoAEByAEDwAEB&sclient=gws-wiz-serp

### System Details

```shell
Because the package information is deleted in docker, the wails doctor prompts that the packages are missing, but they are already installed


dev@ubuntu:~$ wails doctor
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Ubuntu
Version      | 22.04
ID           | ubuntu
Go Version   | go1.19.5
Platform     | linux
Architecture | amd64

# Wails

Version         | v2.3.1
Package Manager | apt

# Dependencies

Dependency | Package Name          | Status    | Version
*docker    | Unknown               | Not Found |
gcc        | Unknown               | Not Found | 11.3.0
libgtk-3   | libgtk-3-dev          | Available | 3.24.33-1ubuntu2
libwebkit  | libwebkit2gtk-4.0-dev | Available | 2.38.4-0ubuntu0.22.04.1
npm        | Unknown               | Not Found | 9.5.1
*nsis      | nsis                  | Installed | v3.08-2
pkg-config | pkg-config            | Installed | 0.29.2
* - Optional Dependency

# Diagnosis

Your system has missing dependencies!
Required package(s) installation details:
  - libgtk-3: sudo apt install libgtk-3-dev
  - libwebkit: sudo apt install libwebkit2gtk-4.0-dev

Fatal:
Required dependencies missing: gcc npm
Please read this article on how to resolve this: https://wails.io/guides/resolving-missing-packages
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

The following is the output given by wails doctor after I reinstalled the dependency package (of course the devserver is still not working at this time)

```
dev@ubuntu:~$ wails doctor
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Ubuntu
Version      | 22.04
ID           | ubuntu
Go Version   | go1.19.5
Platform     | linux
Architecture | amd64

# Wails

Version         | v2.3.1
Package Manager | apt

# Dependencies

Dependency | Package Name          | Status    | Version
*docker    | docker.io             | Available | 20.10.12-0ubuntu4
gcc        | build-essential       | Installed | 11.3.0
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.5-0ubuntu0.22.04.1
npm        | npm                   | Installed | 9.5.1
*nsis      | nsis                  | Installed | v3.08-2
pkg-config | pkg-config            | Installed | 0.29.2-1ubuntu3
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - docker: sudo apt install docker.io

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
```


### Additional context

I use windows 10 as the host (because I want to play games at any time), then I start the wsl2 subsystem (ubuntu22.04 also enables systemd support), and then use the 'king011/dev-wails:1.19.5' image in the wsl2 subsystem as the development environment

**Comment by leaanthony** [comment]
You may need to update the "devServer" key in `wails.json` to use `0.0.0.0`: https://wails.io/docs/reference/project-config

**Comment by zuiwuchang** [comment]
> You may need to update the "devServer" key in `wails.json` to use `0.0.0.0`: https://wails.io/docs/reference/project-config

Thank you for your reply, I just tried to modify the settings (wails.json) and it didn't work, and I actually found out about the '-devserver' parameter before. I also tried executing `wails dev -devserver 0.0.0.0:34115`, but the netstat command is still Report that there is no listener listening on tcp 34115 port

**Comment by zuiwuchang** [comment]
> > You may need to update the "devServer" key in `wails.json` to use `0.0.0.0`: https://wails.io/docs/reference/project-config
> 
> Thank you for your reply, I just tried to modify the settings (wails.json) and it didn't work, and I actually found out about the '-devserver' parameter before. I also tried executing `wails dev -devserver 0.0.0.0:34115`, but the netstat command is still Report that there is no listener listening on tcp 34115 port

And I just tested it in linux(4.15.0-204-generic Linux Mint 19.1 Tessa) and it doesn't work, so the problem has nothing to do with the wsl2 subsystem, it should be that executing `wails dev` in docker devserver doesn't work, and wails doesn't report errors so I don't know what to do try to fix

**Comment by gwynforthewyn** [comment]
I tried downloading your container and following your workflow with these commands:

```bash
docker run -d --name wails king011/dev-wails:1.19.5  
docker exec -u dev -it wails bash
cd ~/project && wails init -n myproject -t svelte-ts && cd myproject 
wails  dev
```

I can see a couple of things that are worth investigating. First, Vite starts its own web server. Here's my output:

```bash
Forced re-optimization of dependencies

  VITE v3.2.5  ready in 654 ms

Vite Server URL: http://localhost:5173/
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
```

Netstat sees that just fine:

```bash
dev@3a2b00817009:~$ netstat -ntlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5173          0.0.0.0:*               LISTEN      774/node       #  <---- this one    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      50/node   
```

So network processes are spawning just fine, as you can verify with curl:

```bash
dev@3a2b00817009:~$ curl 127.0.0.1:5173
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="./src/style.css" rel="stylesheet">
    <title>myproject</title>
</head>
<body>
<div id="app"></div>
<script src="./src/main.ts" type="module"></script>
</body>
</html>
```

Second, though, is this bundle of messages:

```bash
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:5173/
Using reload debounce setting of 100 milliseconds

(myproject-dev-linux-amd64:4267): Gtk-WARNING **: 02:13:26.140: cannot open display: 


To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
```

Very specifically, this line `(myproject-dev-linux-amd64:4267): Gtk-WARNING **: 02:13:26.140: cannot open display: ` is an error being reported; remember that wails tries to spawn a window, not just a network server.

Given that you've said this issue exists on native linux, not just inside a container, I can go verify what you're seeing and see what there is to be done.

**Comment by gwynforthewyn** [comment]
Yeah, so my testing on Debian shows wails is spawning applications just fine. @zuiwuchang  when you ran your dev server on linux, did you run it from GNOME or something? I ran it from mate with the gtk libraries and the dependencies listed in `wails doctor` installed, and it worked.

I _think_ what you're trying to do is to run wails to do web development, not to do GUI development, but I don't think wails works unless it can spawn the application window.

**Comment by zuiwuchang** [comment]
> Yeah, so my testing on Debian shows wails is starting GUI applications just fine. @zuiwuchang when you ran your dev server on linux, did you run it from a system with a GUI or from a system without a GUI? I ran it from mate with the gtk libraries and the dependencies listed in `wails doctor` installed, and it worked, but I don't think it'll work without a GUI available.
> 
> I _think_ what you're trying to do is to run wails to do web development, not to do GUI development, but I don't think wails works unless it can spawn the application window.

No it can work under linux, I mean it can't work in linux docker (I originally ran in wsl2 docker, I just want to say that this is a problem that will occur in docker and has nothing to do with whether the host is linux or windows)

I can also access the front-end port (5173), but I cannot access the devserver (34115) of wails. When I develop directly in the linux host with ui, I can use the browser to access the devserver (34115).

The front-end service on port 5173 cannot access the runtime api provided by wails, so there are some problems in using it for development.

The gui window opened by wails is not necessary for me, can I skip it, because my development environment usually does not have gui (for example, I use docker, or I have linux development experience in order to play games but I am in the wsl system run wails)

**Comment by stffabi** [comment]
Are you trying to access the devserver (netstat) from within the docker container or from outside directly in wsl2?

If you are trying to access it from outside of docker you need to first makes sure the devserver is bound to '0.0.0.0:34115` as already mentioned before and you also need to tell docker it should map a port from wsl2 into the container. This is done withe `-p` argument when running the container: `docker run -d -p  34115:34115 --name wails king011/dev-wails:1.19.5 `. See also this [docs](https://docs.docker.com/config/containers/container-networking/) for container networking.

**Comment by zuiwuchang** [comment]
> Are you trying to access the devserver (netstat) from within the docker container or from outside directly in wsl2?
> 
> If you are trying to access it from outside of docker you need to first makes sure the devserver is bound to `0.0.0.0:34115` as already mentioned before and you also need to tell docker it should map a port from wsl2 into the container. This is done withe `-p` argument when running the container: `docker run -d -p 34115:34115 --name wails king011/dev-wails:1.19.5 `. See also this [docs](https://docs.docker.com/config/containers/container-networking/) for container networking.

`curl` and` netstat` are executed in Docker. When I need to visit before Docker, I know that I want to map the port

> Thanks to Gwynforthewyn's reply for helping me find the problem. The GUI window opened by Wails is necessary (although this GUI window is useless to me, I don’t know what it is useful).

I put the '/tmp/.x11-unix/' to the docker. Wails Dev can work normally after starting the GUI window, but this is effective when the host is linux. There is no X-Server when using WSL2. It is still not completely normal. I am trying a way and testing. I currently install VCXSRV in the Windows host to provide X-Server but there are still some problems. If I finally solve these, I will give me a solution in the subsequent reply.

**Comment by zuiwuchang** [comment]
I have solved the problem of using `wails dev` in docker, the following is my solution, I hope it can help people with the same needs.

Mount the host's '/tmp/.x11-unix/' to docker and specify the environment variable DISPLAY=:0 for docker

```
docker run
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY=$DISPLAY \
        ...
```

If the host machine is linux, make sure your linux x-server is working properly (otherwise, specify docker's DISPALY to a remote x-server service, and you don't need to mount /tmp/.X11-unix to docker)

If you use docker in wsl2 of windows, you don’t need to install desktop-related packages for wsl2, but you need to [allow the wsl2 gui program to run](https://learn.microsoft.com/en-US/windows/wsl/wsl-config), but in this way, the gui window cannot be displayed normally when you execute `wails dev` in docker, but it doesn’t matter, you can Visit the devserver via browser to get the development preview, but don't close this blank gui window(Similar to linux, you can also specify your remote x-server service for docker instead of using wsl2 to provide gui)
