### ISSUE TITLE
How to embed the system tray?

### ISSUE THREAD

**Issue by 93Alliance** [wailsapp/wails#2437]
### Is your feature request related to a problem? Please describe.

Can the system tray be supported? As far as I know, the go-astilectron project supports system trays, and since wails does not support system trays, I had to choose other solutions.

### Describe the solution you'd like

Can you embed getlantern/systray to support the system tray?

**Comment by andrewbrey** [comment]
@93Alliance this is a request that's been on the radar for a long time, and you can track progress towards it in https://github.com/wailsapp/wails/issues/1521. A quick search in the issues finds several related issues, and it would be a good idea to start with that before opening a duplicate :)

**Comment by leaanthony** [comment]
Other people have used golantern with Wails but it's not supported in v2 natively. It will be supported in v3 though (if you're ok with not using bindings, you can try it out for Mac right now from the v3 directory.

**Comment by leaanthony** [comment]
Closing as duplicate

**Comment by duolabmeng6** [comment]
> 



> Other people have used golantern with Wails but it's not supported in v2 natively. It will be supported in v3 though (if you're ok with not using bindings, you can try it out for Mac right now from the v3 directory.

May I know who used it successfully? I cannot use it in macos
