### ISSUE TITLE
Context menu not displayed on right-button click in `wails build` app, but is displayed in `wails dev`

### ISSUE THREAD

**Issue by idroz** [wailsapp/wails#2438]
### Description

Context menu behaviour on MacOS appears to be different between `wails dev` and `wails build` versions of the application. In `wails dev` context menu appears as expected on right click. The menu does not appear on right click in .app file generated by `wails build`.

### To Reproduce

Mac OS: 13.1
Go: 1.19.1 darwin/arm64

1. `wails init -n myproject -t preact`
2. `wails dev`
3. Right click on the search field -> context menu appears (as expected)

Now:

1. Exit dev application
2. `wails build`
3. Launch application from `build/bin/myproject.app`
4. Right click on the search field -> context menu does not appear (**not expected**).

### Expected behaviour

Consistent appearance of a context menu on right click between `dev` and `build` application versions.

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 13.1
ID           | 22C65
Go Version   | go1.19.1
Platform     | darwin
Architecture | arm64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2396
npm                       | N/A          | Installed | 9.4.1
*Xcode                    | N/A          | Installed | 14.2 (14C18)
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by leaanthony** [comment]
That's by design. It's only there in Dev so you can access the Dev tools. We don't support the context menu in v2, however we will in v3.

**Comment by idroz** [comment]
Got it - Thanks
