### ISSUE TITLE
The documentation is not perfect about macos development. 

### ISSUE THREAD

**Issue by perlh** [wailsapp/wails#2439]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

The documentation is not perfect. When I wrote the macos App with go wails to create the tun network card, the permission was denied and I could not find any solution in the documentation

I do not know how to apply for tun permission in macos

failed to create tun interface: error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by perlh** [comment]
Hope to add documentation for macos deployment and permissions

**Comment by leaanthony** [comment]
Correct, the documentation is not perfect. If you find a solution to this scenario, feel free to contribute a PR to the documentation 👍
