### ISSUE TITLE
Support Distribution 'LinuxMint'

### ISSUE THREAD

**Issue by rcprcp** [wailsapp/wails#244]
**Description**
Distribution 'LinuxMint' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.13 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | LinuxMint |
| Distribution Version   | 19.1 |
| Discovered by   | lsb |

thank you.

**Comment by bh90210** [comment]
hello @rcprcp 
mint is supported in the latest pre-release
you can update using `wails update -pre`

duplicate of #232 #238

**Comment by rcprcp** [comment]
Thanks, works perfectly.
