### ISSUE TITLE
Obfuscated Binary doesn't open (nothing happens) 

### ISSUE THREAD

**Issue by tarun0** [wailsapp/wails#2442]
### Description

I am making an obfuscated build and it just doesn't run. There is no error message while building with `wails build -obfuscated` but on running the binary, windows show a progress circle for an instant and that's it. 

`wails build` works well.

The binary size difference between normal build and obfuscated build is significant and hence, I feel that obfuscated is doing some job for sure. 

Can someone direct me to right path on how I can pinpoint the issue? It looks more with garble integration or garble itself than specific wails but not sure. Or maybe in my codebase. I did Google but could not find relevant hints.

### To Reproduce

Typical build steps

1. `wails build -obfuscated`

### Expected behaviour

Obfuscated build should also run fine.

### Attempted Fixes

Tried `garbleflags` `-literals` `-tiny` `-seed=random` `-debug` Nothing throws error

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Enterprise
Version      | 2009 (Build: 19045)
ID           | 22H2
Go Version   | go1.20
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.57
npm        | N/A          | Installed | 9.3.1
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.08
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
```

### Additional context

Should I create an issue in garble repo? Looks similar to this issue https://github.com/burrowers/garble/issues/599

**Comment by leaanthony** [comment]
You installed garble right?

**Comment by tarun0** [comment]
> You installed garble right? And it's on your path?

Yes, It's on Path as well. I verified. Like I said, no error is showed and `-debug` flag also showed logs where files are being hashed.

```
C:\>garble
Garble obfuscates Go code by wrapping the Go toolchain.

        garble [garble flags] command [go flags] [go arguments]

For example, to build an obfuscated program:

        garble build ./cmd/foo

Similarly, to combine garble flags and Go build flags:

        garble -literals build -tags=purego ./cmd/foo

The following commands are supported:

        build          replace "go build"
        test           replace "go test"
        reverse        de-obfuscate output such as stack traces
        version        print the version and build settings of the garble binary

To learn more about a command, run "garble help <command>".

garble accepts the following flags before a command:

  -debug
        Print debug logs to stderr
  -debugdir string
        Write the obfuscated source to a directory, e.g. -debugdir=out
  -literals
        Obfuscate literals such as strings
  -seed value
        Provide a base64-encoded seed, e.g. -seed=o9WDTZ4CN4w
        For a random seed, provide -seed=random
  -tiny
        Optimize for binary size, losing some ability to reverse the process

For more information, see https://github.com/burrowers/garble.
```

**Comment by BigCatGit** [comment]
我也遇到 了相同的问题:
# Building target: windows/amd64

  • Generating obfuscated bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Generating application assets: Done.
  • Compiling application: # changeme
cannot get modified linker: expected 2 applied patches, actually 0:

正在检查补丁 cmd/link/internal/ld/pcln.go...
正在检查补丁 cmd/link/internal/ld/pcln.go...
成功应用补丁 cmd/link/internal/ld/pcln.go。
成功应用补丁 cmd/link/internal/ld/pcln.go。

exit status 1
  ERROR   exit status 1

**Comment by tarun0** [comment]
Guys my issue is different than both yours. I can build the binary. No error is thrown throughout the process. When i double click, nothing happens. Maybe entry point etc got corrupted or something? I'm don't possess enough knowledge in that domain.

**Comment by leaanthony** [comment]
Closing this due to lack of feedback. 
Feel free to reopen if there's anything else to discuss 👍

**Comment by lucasXing24** [comment]
i have same issue. On macos. 
after wails build get the binary, then I double click nothing happens. even without the -obfuscated flag

**Comment by lysShub** [comment]
> Guys my issue is different than both yours. I can build the binary. No error is thrown throughout the process. When i double click, nothing happens. Maybe entry point etc got corrupted or something? I'm don't possess enough knowledge in that domain.

don't double-click run the app.exe, on cmd run it, maybe something output

**Comment by lysShub** [comment]
i can't get window.go.main obj when with `-obfuscated -garbleargs "-seed=myrandomseed"`
![image](https://github.com/user-attachments/assets/09e5dcd6-285e-43e1-86f0-d5849c5f5577)


@leaanthony is binding problem?
