### ISSUE TITLE
Mac keyboard buttons having a weird noise

### ISSUE THREAD

**Issue by torabian** [wailsapp/wails#2444]
### Description

Thank you for this project, seems quite promising.

One issue I see is, when I use keyboard within my app, (Most of the keys), on mac, I hear a weird noise. I think this is mac behavior to indicate that those key combination doesn't do anything, or is disabled.

Is there anyway to prevent this issue?

### To Reproduce

1. Use a mac
2. Press any button on the app (Tab key is fine)
3. You will hear a noise from mac ( similar noise comes from some combinations in terminal )

### Expected behaviour

No noise, or a way to prevent that noise

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 12.4    
ID           | 21F79   
Go Version   | go1.19.4
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2395         
npm                       | N/A          | Installed | 9.2.0        
*Xcode                    | N/A          | Installed | 13.4 (13F17a)
*upx                      | N/A          | Available |              
*nsis                     | N/A          | Available |              
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
So I got this working in the v3 codebase but for some weird reason it won't work in v2! Thanks for opening the ticket and raising awareness of this. It's unlikely to get fixed in v2 (already tried a number of different ways to get it to work) but it's totally fixed in v3 👍

**Comment by bonder** [comment]
When is v3 available? Asking for a friend. :)
