### ISSUE TITLE
mac wails build error

### ISSUE THREAD

**Issue by liyz404** [wailsapp/wails#2447]
### Description

wails build error tips：Wails CLI v2.3.1

# Build Options

Platform(s)        | darwin/amd64                                      
Compiler           | /usr/local/go/bin/go                              
Skip Bindings      | false                                             
Build Mode         | production                                        
Frontend Directory | /*******/frontend
Obfuscated         | false                                             
Skip Frontend      | false                                             
Compress           | false                                             
Package            | true                                              
Clean Bin Dir      | false                                             
LDFlags            |                                                   
Tags               | []                                                
Race Detector      | false                                             
Warning: go.mod is using Wails '2.1.0' but the CLI is 'v2.3.1'. Consider updating your project's `go.mod` file.

# Building target: darwin/amd64

  • Generating bindings:   ERROR   
          # algo-benchmark
          /usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
          ld: warning: -no_pie is deprecated when targeting new OS versions
          ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
          ld: file too small (length=0) file '/var/folders/q2/867r3wd554s8dv7bg9gmzf640000gn/T/go-link-3393189677/000000.o' for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
          
          exit status 2

  ERROR   
          # algo-*****
          /usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
          ld: warning: -no_pie is deprecated when targeting new OS versions
          ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
          ld: file too small (length=0) file '/var/folders/q2/867r3wd554s8dv7bg9gmzf640000gn/T/go-link-3393189677/000000.o' for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
          
          exit status 2
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:

### To Reproduce

1. first：sudo wails build -platform   windows/arm64 -o algo.exe  
2. then：tips no platform	
3. sudo wails build -platform windows -o algo.exe

### Expected behaviour

wails build success

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 13.0.1
ID           | 22A400
Go Version   | go1.18.3
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2396
npm                       | N/A          | Installed | 8.11.0
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Sounds like your disk is full. This does not appear to be a Wails error

**Comment by liyz404** [comment]
> Sounds like your disk is full. This does not appear to be a Wails error
There's still over 200G of disk free，and tThis error occurs after “wails build -platform windows -o algo.exe”

**Comment by barats** [comment]
> Sounds like your disk is full. This does not appear to be a Wails error

Had same issue here as well when building windows app( using nsis) on a macOS.

> ld: warning: -no_pie is deprecated when targeting new OS versions
> ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
> ld: file too small (length=0) file '/var/folders/q2/867r3wd554s8dv7bg9gmzf640000gn/T/go-link-3393189677/000000.o' for architecture x86_64

It couldn't be the disk problem.

**Comment by barats** [comment]
Checked `go env` and saw gccflags like this

```
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g9/7sqwd31s7gn8hdkhrkw59czm0000gn/T/go-build3685697298=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by barats** [comment]
Here's the full output when I tried to call `wails build` form command line. 

```
Wails CLI v2.3.1


# Build Options

Platform(s)        | darwin/amd64                              
Compiler           | /Users/barat/.gvm/gos/go1.18/bin/go       
Skip Bindings      | false                                     
Build Mode         | production                                
Frontend Directory | /Users/barat/Codes/GoCodes/wailsd/frontend
Obfuscated         | false                                     
Skip Frontend      | false                                     
Compress           | false                                     
Package            | true                                      
Clean Bin Dir      | false                                     
LDFlags            |                                           
Tags               | []                                        
Race Detector      | false                                     

# Building target: darwin/amd64

  • Generating bindings:   ERROR   
          # wailsd
          /Users/barat/.gvm/gos/go1.18/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
          ld: warning: -no_pie is deprecated when targeting new OS versions
          ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
          ld: file too small (length=0) file '/var/folders/g9/7sqwd31s7gn8hdkhrkw59czm0000gn/T/go-link-4143617517/000000.o' for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
          
          exit status 2

  ERROR   
          # wailsd
          /Users/barat/.gvm/gos/go1.18/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
          ld: warning: -no_pie is deprecated when targeting new OS versions
          ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
          ld: file too small (length=0) file '/var/folders/g9/7sqwd31s7gn8hdkhrkw59czm0000gn/T/go-link-4143617517/000000.o' for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
          
          exit status 2
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by liyz404** [comment]
> Checked `go env` and saw gccflags like this
> 
> ```
> GOVERSION="go1.18"
> GCCGO="gccgo"
> GOAMD64="v1"
> AR="ar"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOWORK=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g9/7sqwd31s7gn8hdkhrkw59czm0000gn/T/go-build3685697298=/tmp/go-build -gno-record-gcc-switches -fno-common"
> ```

`GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/***/GolandProjects/bin"
GOCACHE="/Users/***/Library/Caches/go-build"
GOENV="/Users/***/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/***/GolandProjects/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/***/GolandProjects"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q2/867r3wd554s8dv7bg9gmzf640000gn/T/go-build641295308=/tmp/go-build -gno-record-gcc-switches -fno-common"`

----------
thanks for your answer。so you know how to do solve？

**Comment by stffabi** [comment]
I remember some people had similar issues with a somehow broken xcode tools installation. Have you tried reinstalling the xcode cli tools and maybe also install xcode? Maybe that's going to fix your issue.

**Comment by barats** [comment]
> I remember some people had similar issues with a somehow broken xcode tools installation. Have you tried reinstalling the xcode cli tools and maybe also install xcode? Maybe that's going to fix your issue.

I tried to reinstall xcode tools, hoping that it would fix the problem, but no luck.

The `go build` command could work correctly, I am able to build other app. But `wails build` still is failing...

Apparently,  `walis build` added some other `gcflags` to build process and I couldn't figure it out.

**Comment by stffabi** [comment]
Have you also tried to install the whole xcode not just the cli-tools? Please also make sure to start it after the installation since there are some things that get installed after the startup.

We need to use CGO which needs some additional flags for selecting frameworks and so on.

**Comment by barats** [comment]
> Have you also tried to install the whole xcode not just the cli-tools? Please also make sure to start it after the installation since there are some things that get installed after the startup.
> 
> We need to use CGO which needs some additional flags for selecting frameworks and so on.

REINSTALL WHOLE XCode?

Does it have to be this way? It sounds .... a little bit unacceptable to me since REINSTALL WHOLE XCode will cost me lots of time.... 

Sad....

**Comment by stffabi** [comment]
Sorry I have no other idea right now.

Maybe try a manual go build with the command that you see when doing `wails build -v 2` and then maybe use the `go build -a` to clear the build caches?

**Comment by barats** [comment]
I JUST noticed that after `walis build -clean -platform=windows/amd64`, there's a new file `xxx-res.syso` appended to project root.

I DELETED this new file and tried it again, guess what? 

```
# Building target: windows/amd64

  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Generating application assets: Done.
  • Compiling application: Done.
 INFO  Wails is now using the new Go WebView2Loader. If you encounter any issues with it, please report them to https://github.com/wailsapp/wails/issues/2004. You could also use the old legacy loader with `-tags native_webview2loader`, but keep in mind this will be deprecated in the near future.
Built '/Users/barat/Codes/GoCodes/wailsd/build/bin/wailsd.exe' in 6.305s.
```

**Comment by barats** [comment]
> You could also try to delete the xcode caches `/var/folders/g9/7sqwd31s7gn8hdkhrkw59czm0000gn/T/go-link-4143617517`.

BTW: this file is READ ONLY, can't even delete it with `sudo rm -rf xxx` ....

**Comment by stffabi** [comment]
Oh awesome you got it solved. I think we should then clear that file before building. That's a great finding 🙏 .

**Comment by stffabi** [comment]
@liyz404 do you also have that file in your folder? Does deleting the `xxx-res.syso` solve it for you as well?

**Comment by barats** [comment]
> Oh awesome you got it solved. I think we should then clear that file before building. That's a great finding 🙏 .

Seems like `xxx-res.syso` file will be deleted after `wails build` process ONLY IF the build process is a success. But the build process is interrupted, it remains. Kind of weird. 

Maybe there's something ur team can do about it. 

Thanks for all the amazing job u guys did.

**Comment by stffabi** [comment]
We improve this and delete it after a failed build. But I think we should also remove that file if it exists before doing a build. Just in case someone has it there for some reason.

> Thanks for all the amazing job u guys did.

Thank you so much

**Comment by leaanthony** [comment]
Nice investigation both. Deleting that file before build should be fine, though I'm *amazed* this affects Mac builds to the point where I think it might be a bug in the compiler...

**Comment by liyz404** [comment]
> res.syso

Thank you very much for your discovery. I also have this file here. After delete it, that ok

**Comment by liyz404** [comment]
> @liyz404 do you also have that file in your folder? Does deleting the `xxx-res.syso` solve it for you as well?

Yes, after delete this file, can I continue to build windows app?
