### ISSUE TITLE
Add support for flutter web (hummingbird)

### ISSUE THREAD

**Issue by g5becks** [wailsapp/wails#246]
Hi, thanks for the great project. I'd like to see support added for using flutter for web on the client using wails. I don't mind contributing ( especially on the dart interop side of things ), but I wanted to know how much work this might take upfront and where to start.

Thanks.

**Comment by leaanthony** [comment]
Hi Gary. Glad you like it! We are just about to feature freeze for v1 so
what I'll do is stick it in the post v1 list that will get reviewed and
prioritised in November. Does that work for you?

**Comment by G5Becks** [comment]
Sounds great. Thanks.

**Comment by leaanthony** [comment]
Nice one! Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Comment by moqmar** [comment]
There's also https://github.com/go-flutter-desktop/go-flutter which lets you run flutter apps without the browser step in between, but I guess this could still make sense for some applications.

**Comment by G5Becks** [comment]
@moqmar I tried it. Flutter desktop is highly unstable at this point, and missing a lot of basic features as well.

**Comment by moqmar** [comment]
Oh, good to know - seems like the current non-browser GUI situation with Go is generally quite bad... o.O

**Comment by JAYAMURUGANJ** [comment]
Great!

**Comment by leaanthony** [comment]
I don't know a lot about flutter but it looks like it's not a pure
HTML/js/CSS library? As such, I don't see how it would ever work with Wails.

**Comment by moqmar** [comment]
Flutter itself can be used on a lot of platforms, one of them being HTML/CSS/JS. So, I guess it shouldn't be a problem to get a Flutter app working in Wails, but the interopability between Dart and Go will be the harder part.

**Comment by leaanthony** [comment]
Do you have any links on how to set up the HTML/js part?

**Comment by dzonerzy** [comment]
Any updates on this?

**Comment by leaanthony** [comment]
There are no plans to do this, however anyone is free to create a flutter template https://wails.io/docs/community/templates
