### ISSUE TITLE
After upgrading to version 2.4.0 and using wails dev

### ISSUE THREAD

**Issue by longit123** [wailsapp/wails#2471]
### Description

After upgrading to version 2.4.0 and using wails dev, each click event needs many times to respond

[image](https://live.staticflickr.com/65535/52734159932_afcf00ff2b_b.jpg)

2.3.1 version is normal

### To Reproduce

each click event needs many times to respond

### Expected behaviour

each click event is normal

### Screenshots

[image](https://live.staticflickr.com/65535/52734159932_afcf00ff2b_b.jpg)

### System Details

```shell
wails doctor
DEB | Using go webview2loader
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 19044)
ID           | 21H2
Go Version   | go1.19.6
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.0

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 108.0.1462.46
npm        | N/A          | Installed | 8.19.3
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.08
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
```

**Comment by stffabi** [comment]
Thanks for reporting this.

Can you please provide us a minimal reproduction guide based on `wails init` vanilla project?

**Comment by stffabi** [comment]
Are you probably using `--wails-draggable:drag` on the parent div? If that's the case please make sure to set `--wails-draggable:none` on the buttons.

**Comment by longit123** [comment]
@stffabi only use `--wails-draggable:drag` on 
`<div id="app" style="--wails-draggable:drag"></div>`
it works normal on version 2.3.1

**Comment by longit123** [comment]
@stffabi not noly btns, the icons, vertical navigation bar .... any need click events all need 3-4 or more clicks....

**Comment by longit123** [comment]
I try to add ` style="--wails-draggable:none;"` on the click event element, it is works, but there is too many place to add the attr.....

**Comment by stffabi** [comment]
Awesome, glad you were able to solve this.

**Comment by mholt** [comment]
I'm also hitting this.

@stffabi Can we possibly reopen and come up with another solution? I don't know the implementation, or what changed exactly, but it's a problem that the title bar can't be clicked anymore:

![image](https://user-images.githubusercontent.com/1128849/224512767-d91fa675-8db2-43dc-b838-38ba5bba7397.png)

Even menus that drop down from the title bar can't be clicked:

![image](https://user-images.githubusercontent.com/1128849/224512778-a54cd3ac-1b31-4236-a52d-70221cb11c9c.png)

I actually do expect to be able to drag the window from anywhere on the title bar, but only on drags, not clicks. Clicks should still propogate through to the JS.

**Comment by stffabi** [comment]
I'm afraid that's not easily possible for windows. If we restore the old behaviour there will be lagging or not working drags on windows. Which was very annoying. If you are interested in insights this is the discord channel https://discord.com/channels/1042734330029547630/1063827017121927178

This is IIRC the third iteration on this one for windows, which supports dragging and still double click events on items with that style and no lagging or missing drag events.
So this is the price we unfortunately have to pay for those features.
If you come up with with a fix for all those features above and a simple click, we would be more than happy to merge that one.
I've already put uncountable hours into this one...

If you want to restore the old behaviour and you are okey with lags and sometimes missing drag events on Windows you can set the following JS variable: window.wails.flags.deferDragToMouseMove = true;

**Comment by mholt** [comment]
Oof. Ok. I've never experienced the lag issue on Windows.

I will probably restore the previous behavior then, since the current behavior is unacceptable for my app.

Thanks for your effort.

**Comment by stffabi** [comment]
Yeah that dragging of a frameless window is really a crack nut on Windows. Maybe we come up with a better solution once we change the rendering of WebView2 to composition-based, but that needs another huge effort.

**Comment by stffabi** [comment]
Sorry that we aren't really coming up with a satisfying solution for all cases and for all people.

**Comment by mholt** [comment]
@stffabi Oh, no worries -- I'm not disappointed btw. I really appreciate that there is a way to revert to the previous behavior (I haven't tried it yet, but I'll trust that it works, heh). I know how hard it is to satisfy everyone, definitely been there before.

**Comment by stffabi** [comment]
Just seen that changing the `window.wails.flags.deferDragToMouseMove = true;` doesn't restore the full old behaviour because we also removed some Go code that is needed for the old behaviour on Windows.

I think I'll create a PR to re-add that code so it fully restores the old behaviour.

**Comment by mholt** [comment]
Ah, alrighty -- thank you :) No stress on this btw, I can tell my users to double-click in the meantime.

**Comment by stffabi** [comment]
@mholt would it be possible for you to test PR #2482? That should allow you to revert to the old behaviour on Windows by setting `window.wails.flags.deferDragToMouseMove = true;` I have also the impression that it should also work better than the old one on Windows. At least on my machine I was able to see the lagging behaviour with `2.3.1` but not anymore with this PR and using the `deferDragToMouseMove = true;`. So maybe we have now a 100% solution for all cases 🤷... 

@mholt would you also mind testing it on Linux because it could maybe change the dragging behaviour there. Had no machine ready for testing it on linux.

@oSethoum would it be possible for you to test the PR #2482 while setting `window.wails.flags.deferDragToMouseMove = true` to true on windows in the inspector and check if you are seeing any lagging of the drag? That would be really awesome.

**Comment by leaanthony** [comment]
Thanks for your time on this @stffabi - it's so hard to get right for all cases on all platforms. If the issues continue I'm happy to jump in and have a go.

**Comment by mholt** [comment]
@stffabi 

> would it be possible for you to test PR https://github.com/wailsapp/wails/pull/2482?

Done! Commented briefly on that PR. I added the line of JS while on my main dev workstation which is Linux. Then I ensured I upgraded to the commit and tested, and things still worked... no noticeable differences.

After rebooting into Windows I pulled my changes and also ensured I installed the patched version of Wails (not sure if required, but just in case) and updated go.mod to ensure it wouldn't keep resetting the Wails version during `wails dev` ( :upside_down_face: ) and I was successfully able to click the UI elements in my app bar!

I was also able to drag the window with no lag.

(Note: I have never experienced the lag on Windows in the first place.)

So, I dunno, maybe you just worked a miracle? And if so, maybe it could just be the default without having to set `deferDragToMouseMove`. :man_shrugging: :100: :tada: 

Great job :) And thank you thank you again for working on such a difficult issue!

**Comment by oSethoum** [comment]
@stffabi 
>would it be possible for you to test the PR #2482 while setting `window.wails.flags.deferDragToMouseMove = true` to true on windows in the inspector and check if you are seeing any lagging of the drag? That would be really awesome.

I tested it with and without the PR and I didn't notice any lag in the dragging.

**Comment by stffabi** [comment]
> @stffabi 
> 
> >would it be possible for you to test the PR #2482 while setting `window.wails.flags.deferDragToMouseMove = true` to true on windows in the inspector and check if you are seeing any lagging of the drag? That would be really awesome.
> 
> 
> 
> I tested it with and without the PR and I didn't notice any lag in the dragging. 

Awesome thanks so much for testing 🙏. Just to be 💯 sure, you did change that variable on the inspector to true?

**Comment by oSethoum** [comment]
> you did change that variable on the inspector to true?

Yes I did.

**Comment by stffabi** [comment]
> > you did change that variable on the inspector to true?
> 
> 
> 
> Yes I did. 

Awesome thanks for testing 🙏

I think we could maybe really go back to this enhanced version of the old behaviour.

I'll update the PR to use this as the default and will ping the others (which reported the lagging) in the discord channel if they could test this PR. If it works for them I think there's no reason not to use this new default.

**Comment by stffabi** [comment]
Thanks again both of you @mholt and @oSethoum for taking your time testing the PR. We really appreciate your feedback and testing on this issue 🙏 .

I've updated the PR to use the "defer to mouse move" mode per default. I've also brought the PR up in the discord channel for feedback of the reporters of the "delay/lay" problem.

**Comment by mholt** [comment]
I might have been wrong in my assumption - does v2.4.1 make the `window.wails.flags.deferDragToMouseMove = true;` flag the default?

I just verified that when I remove it from my page, clicks in draggable regions no longer work on Windows (double-click is required).

I'll leave this line in for now as things work with it in, but I wanted to verify my understanding. :slightly_smiling_face:  Thank you!!

**Comment by mholt** [comment]
@stffabi Ok, you're right, that is so weird though. If I don't have that line in my JS then single-clicks on draggable elements on Windows doesn't work :confused:

Anyway, I'm happy as a clam with that line in my code for now. Just wanted to let you know :innocent: Thanks again for all the work you do on Wails!
