### ISSUE TITLE
cannot build project on windows/amd64

### ISSUE THREAD

**Issue by Felamande** [wailsapp/wails#2475]
### Description

build new project and get errors below:
DEB | Using go webview2loader
Wails CLI v2.4.0

# Build Options

Platform(s)        | windows/amd64
Compiler           | D:\dev\go\bin\go.exe
Skip Bindings      | false
Build Mode         | production
Frontend Directory | D:\dev\gopath\src\github.com\Felamande\onekeylog\frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | true
Package            | true
Clean Bin Dir      | false
LDFlags            | -w -s
Tags               | []
Race Detector      | false

# Building target: windows/amd64

  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:
    > frontend@0.0.0 build D:\dev\gopath\src\github.com\Felamande\onekeylog\frontend
    > vue-tsc --noEmit && vite build

    D:\dev\gopath\src\github.com\Felamande\onekeylog\frontend\node_modules\vite\bin\vite.js:2
    import { performance } from 'node:perf_hooks'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at Module._compile (internal/modules/cjs/loader.js:895:18)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
        at internal/main/run_main_module.js:17:11
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! frontend@0.0.0 build: `vue-tsc --noEmit && vite build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the frontend@0.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\tzh\AppData\Roaming\npm-cache\_logs\2023-03-09T03_48_05_289Z-debug.log

  ERROR   exit status 1

  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### To Reproduce

 wails init -n myproject -t vue-ts
cd myproject
wails build -upx -webview2 embed -ldflags "-w -s"

### Expected behaviour

expected to build successfully

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22624)
ID           | 22H2
Go Version   | go1.19.3
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.0

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.63
npm        | N/A          | Installed | 6.13.4
*upx       | N/A          | Installed | upx 3.96
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by misitebao** [comment]
> SyntaxError: Cannot use import statement outside a module

The error message has been pointed out in the log.👆

**Comment by stffabi** [comment]
@Felamande were you able to solve this issue with upgrading your node version?

**Comment by stffabi** [comment]
I'm going to close this, we believe it should be fixed with updating your node version. Please feel free to reopen if you see any further issues.
