### ISSUE TITLE
Set options HideWindowOnClose: true, but windows system tray does not display

### ISSUE THREAD

**Issue by zundaren** [wailsapp/wails#2491]
### Description

Set options HideWindowOnClose: true, close top right corner, windows  system tray does not display
![ApplicationFrameHost_lit5l5A1Cc](https://user-images.githubusercontent.com/44863479/225378383-afb5354b-1fce-4fcc-9618-f2ff58b167b1.png)
![image](https://user-images.githubusercontent.com/44863479/225378475-12dc3155-ccdf-48c5-8c3d-963621438cd8.png)
![image](https://user-images.githubusercontent.com/44863479/225379101-0de114bb-76a5-4592-a93c-9391fa0a4f16.png)

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.19.6
Platform     | windows
# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Please fill in all of the template when submitting a bug report.

**Comment by stffabi** [comment]
We currently have no support for system tray, see also #1521. It should come with v3 (there's no timeframe yet for a release) and then you could add your app to the system tray when hiding.

**Comment by stffabi** [comment]
Duplicate of #1521

**Comment by zundaren** [comment]
> Duplicate of #1521

THANKS
