### ISSUE TITLE
exec.Command("pnpm","i") not run in prod mode and MacOS

### ISSUE THREAD

**Issue by evil171** [wailsapp/wails#2507]
### Description

![image](https://user-images.githubusercontent.com/18542640/226233696-994c6b86-b308-4b71-8ac6-e01fcc82e7cf.png)
I want run pnpm or npm in wails,dev mode is ok. but in prod mode and MacOS not run. print env: node: No such file or directory

### To Reproduce

![image](https://user-images.githubusercontent.com/18542640/226234021-37d8568e-01ec-4466-85b5-479778f78240.png)
![image](https://user-images.githubusercontent.com/18542640/226234039-59b4ce76-d9af-44c8-a0f8-c36ba059f81f.png)

### Expected behaviour

Normal run

### System Details

```shell
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 12.6    
ID           | 21G115  
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.4.0

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2395   
npm                       | N/A          | Installed | 8.5.3  
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by misitebao** [comment]
Please check your Node environment according to [this question](https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory).

**Comment by evil171** [comment]
I don’t think it’s environment problem, because the packaging program I started directly through the terminal can be executed normally, and an error will be reported only when it is executed without terminal

**Comment by mateothegreat** [comment]
Your command is being run in a sub shell and isn't invoking your rc file(s) so it is highly likely that $HOME doesn't have what it needs to find what you want (i.e.: /usr/local/bin which is not a standard default path in most places).

**Comment by leaanthony** [comment]
Closing this as it's an issue external to Wails.
