### ISSUE TITLE
wails build reports incorrect status code; reports success even on build faliure

### ISSUE THREAD

**Issue by mewmew** [wailsapp/wails#251]
**Description**
Running `wails build` to build any code which contains compile time errors should report a non-zero status code to indicate failure. This is important for integration into CI build systems.

Currently, `wails build` reports build error status code by print statements, but even on build failure a zero status code is returned, thus indicating success.

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a minimal project using `wails init`
2. Add invalid code to `main.go` to cause build error.
3. Build using `wails build`
4. Observe status code reported by `wails build` command. If zero this is incorrect, since it should report non-zero to indicate a build error has occurred.

**Expected behaviour**
Non-zero status code reported to indicate build error.

**Screenshots**

```
[u@x1 foo123123123]$ wails init
Wails v0.18.2 - Initialising project

The name of the project (My Project): foo
Project Name: foo
The output binary name (foo): foo
Output binary Name: foo
Project directory name (foo): foo
Project Directory: foo
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: foo
Please choose an option [1]: 
Template: Angular
✓ Generating project...
✓ Building project (this may take a while)...
Project 'foo' built in directory 'foo'!
[u@x1 foo123123123]$ echo broken_code >> foo/main.go
[u@x1 foo123123123]$ cd foo
[u@x1 foo]$ wails build ; echo $?
Wails v0.18.2 - Building Application
...
✗ Building frontend...
Error: exit status 1
0
```

Note that the status code printed to terminal is exit status 2. However, the status code returned from the `wails build` command is 0.

**Edit:** update to wails v0.18.2. issue still present.

**Comment by leaanthony** [comment]
Thanks for this! PR merged. #252
