### ISSUE TITLE
Browser only mode

### ISSUE THREAD

**Issue by alkeryn** [wailsapp/wails#2513]
### Is your feature request related to a problem? Please describe.

Hey, would it be possible to both be able to dev and build in browser only mode ?
in case i want to host it in a server without having to change anything for example ?

### Describe the solution you'd like

just add a --webonly flag to both build and dev.
or maybe add a web platform.

### Describe alternatives you've considered

the alternative would be to put all common functions in a library and call it both from wails and a backend.

**Comment by alkeryn** [comment]
@misitebao kind of yes, we used wails to package some front end and add go function to it, but now we'd like the option to run it remotely with a server + browser as well as just an all in one executable, if there was a built in option it could be nice.

also, just for developpement, being able to disable the gui windows and use the browser only would actually be nicer because having a window pop up each time you change some go code is kind of annoying imo.

**Comment by stffabi** [comment]
Thanks for using Wails and opening this enhancement request.

I think both of your requirements are already covered by the following issues:

> but now we'd like the option to run it remotely with a server + browser as well as just an all in one executable, if there was a built in option it could be nice.

**Comment by stffabi** [comment]
Thanks for using Wails and opening this enhancement request.

I think both of your requirements are already covered by the following issues:

> but now we'd like the option to run it remotely with a server + browser as well as just an all in one executable, if there was a built in option it could be nice.

This is what the hybrid mode of #1652 would allow you to do.

> also, just for developpement, being able to disable the gui windows and use the browser only would actually be nicer because having a window pop up each time you change some go code is kind of annoying imo.

This is covered by issue #1495

I'm going to close this request as I think we already have both of those requests. If you see something missing there, please don't hesitate to bring this up on that issues.
