### ISSUE TITLE
start up fail none  gui displayed on  windows

### ISSUE THREAD

**Issue by lilili87222** [wailsapp/wails#2529]
### Description

this just a wails init -n test -t vue  
wails build -s -debug -windowsconsole

v 2.4.1

test demo app. it works in most windows ,but some fail.
none error log,none gui appear on some windows .
OnStartup was called with none error
OnDomReady was not called.

![demo fail](https://user-images.githubusercontent.com/2214998/227767701-b05699ab-2c84-4baf-8099-0a315aaeeed0.png)

### To Reproduce

I do not know.
some windows fail ,some success

### Expected behaviour

display wails demo gui

### System Details

```shell
wails 2.4.1
windows
```

**Comment by leaanthony** [comment]
When you say some windows fail, do you mean windows computers?

**Comment by stffabi** [comment]
This sounds very similar to issue #2124. Could you take a look into the event viewer on those machines to check if there are errors reported from the WebView2 component?

**Comment by lilili87222** [comment]
Yes windows computers,not display gui. 
OnStartup was called with none error
OnDomReady was not called.
it seems be blocked when load the index.html

how to look into the event viewer on those machines?

**Comment by leaanthony** [comment]
I wonder if Webview2 is picking up edge extensions....

**Comment by stffabi** [comment]
> how to look into the event viewer on those machines?

It is the standard windows [event viewer](https://en.wikipedia.org/wiki/Event_Viewer).

**Comment by stffabi** [comment]
Could you please try PR #2627, it should help in your case.

**Comment by stffabi** [comment]
I'm going to close this, we believe it should be fixed with the linked PR. Please feel free to reopen if you see any further issues.
