### ISSUE TITLE
Menu doc appears out of date

### ISSUE THREAD

**Issue by eft** [wailsapp/wails#2540]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I filed a PR for the runtime.Quit() function call https://github.com/wailsapp/wails/pull/2539

I would appreciate an example of how to write a menu.Callback function and pass the menu.CallbackData to that function.  I could file another PR if someone could provide the syntax here.

Also, I am getting a compiler error on runtime.GOOS;  could I be missing a package?

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by eft** [comment]
I had to alias the golang runtime package to get it working with the Wails runtime package.  I'm sure this isn't the right way to resolve the issue though.


```
	r "runtime"
	"github.com/wailsapp/wails/v2/pkg/runtime"
```

**Comment by leaanthony** [comment]
Thanks for using Wails and opening this. When there are naming clashes in imports, this is exactly the right way 👍
