### ISSUE TITLE
On MacOS, minimizing a Wails program results in longer intervals between data response

### ISSUE THREAD

**Issue by luoshengheng** [wailsapp/wails#2541]
### Description

When I developed a real-time data visualization application based on Wails, I found that minimizing the Wails GUI window for a period of time (about 1 minute) would result in data response intervals far exceeding the budgeted interval. I inserted test code into the most basic demo provided by the official website (see screenshot below) and encountered the same issue, ruling out any problem with my application logic. This may be due to MacOS's CPU scheduling strategy for minimized programs, or it may be a defect in Wails itself. I hope you can investigate this issue. Thank you.

ps: I tested it on Windows and did not encounter this issue.

### To Reproduce

1. Create a new Wails project, for example

`wails init -n myproject -t vue`

2. Insert test code into the main method in main.go, like 
```
counter := 0
go func() {
    for {
        counter++
        fmt.Println(counter)
        time.Sleep(time.Second)
    }
}()
```
3. Run "wails dev".
4. Minimize the Wails program window.
5. Click on other targets with the mouse to make the Wails program lose focus.
6. Observe the time interval between the numbers output in the terminal. After about 1 minute, the output interval will be far beyond the preset 1 second.

### Expected behaviour

Minimizing the window does not affect the interval of data response.

### Screenshots

![image](https://user-images.githubusercontent.com/31942473/229016900-8a9f6f16-eb32-4bfe-b8ed-b8e1a2341305.png)

### Attempted Fixes

1. Keep the Wails window on top（**The issue also exists when the Wails window is blocked by other windows and is not visible on the screen**）.
2. Do not allow the Wails window to be minimized.

### System Details

```shell
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 11.3.1  
ID           | 20E241  
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.4.0

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2384         
npm                       | N/A          | Installed | 8.19.2       
*Xcode                    | N/A          | Installed | 12.5 (12E262)
*upx                      | N/A          | Installed | upx 3.96     
*nsis                     | N/A          | Available |              
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Have you tried this outside of Wails? It would be interesting if this showed the same behaviour in a standard Go program

**Comment by luoshengheng** [comment]
> Have you tried this outside of Wails? It would be interesting if this showed the same behaviour in a standard Go program

I have tried a standard Go program and the issue didn't occur.

**Comment by leaanthony** [comment]
Honestly, it sounds like an OS scheduler issue but I'm not sure why it would be so

**Comment by luoshengheng** [comment]
> Honestly, it sounds like an OS scheduler issue but I'm not sure why it would be so

This looks like a problem with Wails, as I'm running an Electron program on the same MacBook without the same issue.

**Comment by leaanthony** [comment]
Mac has a feature called "App Nap". Are you sure this isn't being triggered? To preserve energy, macOS puts minimised applications to sleep so what you're seeing doesn't surprise me. I'm curious as to how electron is using up that processing even when minimised.

**Comment by luoshengheng** [comment]
> Mac has a feature called "App Nap". Are you sure this isn't being triggered? To preserve energy, macOS puts minimised applications to sleep so what you're seeing doesn't surprise me. I'm curious as to how electron is using up that processing even when minimised.

1. Yes, it's indeed a problem caused by App Nap. Execute the follow commandto disable App Nap, and the problem will no longer exist: 
`defaults write NSGlobalDomain NSAppSleepDisabled -bool YES` 
2. I'm not sure why Electron can maintain processing speed even when App Nap is enabled and the window is minimized. I used setInterval to verify if the problem exists.

Now we can avoid this problem by disabling App Nap through the command. I wonder if you have any plans to solve this problem fundamentally, like what Electron did. Anyway, thank you for your assistance.

**Comment by lysShub** [comment]
recurrent on windows:
```js
    setInterval(function () { console.log("base", new Date()); }, 3000)
```
![image](https://github.com/user-attachments/assets/474344c8-c19a-4f94-bed6-0262fc8a8aa9)

minimize the app and all browser window, recurrent after 1 minute; it's seem webview power strategy.


i fix it by worker:

```js
// index.html

worker = new Worker('worker.js');
worker.onmessage = function (e) { console.log(new Date()); }
worker.postMessage('start')
```

```js
// worker.js

self.onmessage = function (e) {
  setInterval(() => {
    self.postMessage(`signal`);
  }, 3000);
};
```
