### ISSUE TITLE
Weird inner rounded corner

### ISSUE THREAD

**Issue by thoriqadillah** [wailsapp/wails#2549]
### Description

There is weird inner rounded corner when running the app (dev and build is the same). This rounded corners appears when setting the translucency below 1

### To Reproduce

1. Set the translucency < 1
2. Start the `wails dev`
3. You'll get the result

### Expected behaviour

No inner rounded corner 

### Screenshots

![Screenshot_20230402_090953](https://user-images.githubusercontent.com/44075782/229327306-76287940-37e3-4f33-8158-641e53acb78b.png)

### Attempted Fixes

- Setting the border radius to 0 (did not work)
- Setting the background color to white (works)
- Setting the translucency to 1

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Fedora Linux
Version      | 37          
ID           | fedora      
Go Version   | go1.19.6    
Platform     | linux       
Architecture | amd64       

# Wails

Version         | v2.4.1
Package Manager | dnf   

# Dependencies

Dependency | Package Name        | Status    | Version
*docker    | Unknown             | Not Found |        
gcc        | gcc-c++             | Installed | 12.2.1 
libgtk-3   | gtk3-devel          | Installed | 3.24.37
libwebkit  | webkit2gtk4.0-devel | Installed | 2.40.0 
npm        | npm                 | Installed | 9.3.1  
pkg-config | pkgconf-pkg-config  | Installed | 1.8.0  
*upx       | upx                 | Installed | 4.0.2  
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Running on Fedora Linux 37 with KDE Plasma 5.27.3

**Comment by leaanthony** [comment]
@tmclane - have you seen anything like this before?

**Comment by leaanthony** [comment]
@thoriqadillah - is this still an issue? If so, please reopen with latest details. Thanks 🙏
