### ISSUE TITLE
Cannot call backend method from frontend with variadic arguments

### ISSUE THREAD

**Issue by srackhall** [wailsapp/wails#2558]
### Is your feature request related to a problem? Please describe.

I encountered this problem today, When processing in go, need to deconstruct a layer of slices and use it. 
![image](https://user-images.githubusercontent.com/65339064/229584013-39a463d6-25ea-4716-9176-cf67a0f5c9d4.png)

For the front-end, a layer of functions has been added to ensure consistency with the go function when calling.
![image](https://user-images.githubusercontent.com/65339064/229571761-b938f6e0-63b1-4d96-b149-4d8f4a7e6d43.png)

### Describe the solution you'd like

Due to reflection limitations, the usage in go may not be able to be changed.
But for the front-end, can the official package an additional layer to maintain consistency when calling from the front-end as much as possible.
Here are just some suggestions. The framework is already very convenient and does not affect daily use at all. Therefore, the content of this suggestion is actually not important, and it doesn't matter if it's not supported.

**Comment by leaanthony** [comment]
Thanks for opening this ticket.

This is fixed in v3 and there's a workaround here: https://wails.io/docs/guides/troubleshooting#cannot-call-backend-method-from-frontend-with-variadic-arguments

I may backport the fix from v3.
