### ISSUE TITLE
Support showing window in all workspaces on MacOS

### ISSUE THREAD

**Issue by cube2222** [wailsapp/wails#2559]
### Is your feature request related to a problem? Please describe.

Hey!
Just let me start by saying that Wails is incredible!

Anyway, I'd like to create an app on MacOS that works like Spotlight / Alfred, so basically is invokable through a shortcut and shows up on the current workspace (virtual desktop). I couldn't seem to find that in the Wails API.

### Describe the solution you'd like

I took a look at how Electron does it, and it seems they didn't solve it directly (haven't added support for the workspaces API) but one user posted a workaround that just shows the window on all workspaces: https://github.com/electron/electron/issues/8734#issuecomment-350145566

It'd be great to have that API call available. I'm not well-versed in the MacOS-specific APIs, but it seems to be similar to the current API calls like SetAlwaysOnTop.

(the related issue https://github.com/electron/electron/issues/5362 mentions why they didn't add support for the actual workspaces API, btw)

**Comment by leaanthony** [comment]
Thanks for the kind words and using Wails!

We're just working on v3 and there is the ability to determine the current desktop. If we had a global shortcut hook, would that be an acceptable solution?

**Comment by cube2222** [comment]
> the ability to determine the current desktop

@leaanthony Do you mean desktop in the sense of workspace, or desktop in the sense of display? What I mean with my use case is basically that on MacOS I can have many virtual desktops, ones with windows, and ones containing full screen apps. What I'm looking for is the ability for the app window to appear above anything I'm currently viewing (possibly a full screen app) on hotkey. (Just making sure we're understanding each-other correctly)

If with desktop you do in fact mean workspace / virtual desktop, and it works for desktops that contain full-screen apps, then yes, absolutely, that would totally work!

Could you tell me which functions in v3 can be used for that? (I'm aware it's unstable and in development; since what I'm doing is a side-project I'm happy to experiment and play with unstable stuff)

**Comment by leaanthony** [comment]
Ah, there's no way to detect virtual desktops in v3 currently. I'd recommend looking at creating a plugin for that.

**Comment by cube2222** [comment]
A plugin is a separate process though, so I don't think it would be able to manipulate the main processes window, or am I missing something?

Unless you mean it's just the detection of the current virtual desktop / list of them that's not supported, while setting the one that the window should appear on is?

**Comment by leaanthony** [comment]
Plugins in v3 are compiled in so have access to the whole application. It's early days though...

**Comment by cube2222** [comment]
Ah, thanks for the explanation! I might take a look then. Thanks for the help!

**Comment by leaanthony** [comment]
@cube2222 - any thoughts on this?

**Comment by cube2222** [comment]
@leaanthony I didn't further delve into this, happy to close the issue, unless you want to keep it around to track this.

**Comment by leaanthony** [comment]
I think we can come back to it in v3 👍
