### ISSUE TITLE
app does not run in browser (chrome/firefox) on windows 10 - black screen

### ISSUE THREAD

**Issue by khyoz** [wailsapp/wails#256]
**Description**

black screen
when I inspect, I can see "**Uncaught TypeError: Cannot read property '_' of undefined**"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:8080/
2. Black Screen : inspect with chrome
3. See error : Uncaught TypeError: Cannot read property '_' of undefined

**Expected behaviour**
Screen wails logo & press me button

**Screenshots**

**System Details**
Windows 10
fresh install from github, program .exe is built and running, but nothing when "npm run serve" when I check at the url displayed 

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.3 |
| Go Version    | go1.13.1 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | v10.16.3
 |
| Node          | 6.9.0 |

**Additional context**
N/A

**Comment by leaanthony** [comment]
This seems to affect all templates apart from React...

**Comment by leaanthony** [comment]
Ok, this seems ok on mac... which is odd as the code base for serve is not platform dependent... Still investigating.

**Comment by khyoz** [comment]
Absolutely no idea about Angular / React and I don't need Vuetify, sorry
So on Windows/Vue : it does not run
maybe other people could help to check

**Comment by leaanthony** [comment]
Updated table after doing more testing on Linux.

**Comment by grvlle** [comment]
I have the same problem on Ubuntu 18.04 using Vue. This started occurring after the 0.18 update. Building and running it using GTK works fine. Chrome reports the same as stated by OP. FF reports "TypeError: window.wails is undefined"

**Comment by leaanthony** [comment]
Please try v0.19.0-pre2 and let me know. It assumes you will generate a new
project or update your version in go.mod

**Comment by grvlle** [comment]
Yeah, that did it for me. Thanks @leaanthony !

**Comment by khyoz** [comment]
seems ok, thanks !
