### ISSUE TITLE
How to call EventsOn in Javascript.

### ISSUE THREAD

**Issue by termlabx** [wailsapp/wails#2563]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I add this in main.js
```

EventsOn("xxxxx", function(optionalData) {
  console.log(optionalData)
});
```
but give me error 

`Can't find variable: EventsOn`

Is this the right way to call eventsOn?
I am using pure javascript without any framework

I didn't find any example in the document, any place can give me some concrete example ?

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by lic-8** [comment]
`window.runtime.EventsOn`

**Comment by lucasXing24** [comment]
> Does `window.runtime.EventsOn` work ?

Not work..

**Comment by lucasXing24** [comment]
Does wails support pure JS well ? It sounds a like very basical use case to me

**Comment by lucasXing24** [comment]
@leaanthony , any suggestions?

**Comment by ds119** [comment]
you should import first:
import {EventsOn} from "../wailsjs/runtime/runtime";

**Comment by leaanthony** [comment]
Yes, you need to import the method to use it. 
Feel free to reopen if there's anything else to discuss 👍
