### ISSUE TITLE
v3:  open Multiple Windows and then close, then webkit background process not closed

### ISSUE THREAD

**Issue by blacksun1977** [wailsapp/wails#2565]
### Description

use then project examples of window, when the child window opend and then close it, the webkit background process not closed

### To Reproduce

run the example of : go run wails/v3/examples/window/main.go

### Expected behaviour

the background proess while exit when the sub windows exit

### Screenshots

open 10 sub windows
![2023-04-07 16 28 18](https://user-images.githubusercontent.com/34148376/230574444-b5ff6717-7d94-485b-bdfe-ecc26af5e6c3.png)
the background process is:
![2023-04-07 16 28 25](https://user-images.githubusercontent.com/34148376/230574656-095bcf30-3702-4599-aa56-86cecbd396b9.png)
when i closed the sub windows, the background process still exist, not exit with the window.

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.2.1  
ID           | 22D68   
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2396         
npm                       | N/A          | Installed | 9.4.1        
*Xcode                    | N/A          | Installed | 14.1 (14B47b)
*upx                      | N/A          | Installed | upx 3.96     
*nsis                     | N/A          | Installed | v3.08        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Thanks for opening the *FIRST* v3 bug 🎉 
I suspect that Mac windows hide by default so don't clean up. We may need to force that. I guess we need to have an option to indicate whether the close button destroys the window or hides it (looks like it's hiding it now). Will investigate 👍
