### ISSUE TITLE
Allow main package to be in a subdirectory

### ISSUE THREAD

**Issue by firelizzard18** [wailsapp/wails#2568]
As far as I can tell, Wails can't function if the main package is not at the root of the project. This limits my choice as a developer and prevents my from organizing my repository the way I prefer. I am an ardent supporter of the [golang-standards/project-layout](https://github.com/golang-standards/project-layout) (at least the /cmd, /pkg, and /internal part) so I find it very frustrating that Wails forces me to organize my project in a specific way.

**Comment by misitebao** [comment]
If you don't want to develop according to the directory automatically generated by `wails cli`, you can refer to the manual compilation document. https://wails.io/docs/next/guides/manual-builds

**Comment by leaanthony** [comment]
It's an interesting way to ask for help

**Comment by firelizzard18** [comment]
I’m not asking for help, I’m making a request/suggestion to make the tooling more flexible.

**Comment by leaanthony** [comment]
It already does this. Perhaps the docs could be clearer.

**Comment by firelizzard18** [comment]
Do you mean via manual builds or via `wails dev` and `wails build`? I couldn’t find anything in the flags or the schema for wails.json and wails failed (“can’t find wails.json”) when I tried running it in a subdirectory.

**Comment by firelizzard18** [comment]
I let my frustration get the better of me and I apologize. Wails appears to be an ideal solution for implementing Go GUIs with JS/HTML without electron. `wails dev` and `wails build` are very convenient and I would like to use them.

I was able to get it to work something like what I expected by putting `wails.json` in a subdirectory with the main package and prefixing the frontend and build directories with "../". IMHO that's kind of awkward and it would be more intuitive if A) Wails walked up the directory tree to find `wails.json` and/or B) if `wails.json` had an option like "mainpkg:dir".

**Comment by leaanthony** [comment]
This may interest you: https://github.com/wailsapp/wails/pull/2009

**Comment by leaanthony** [comment]
@firelizzard18 - any updates?

**Comment by firelizzard18** [comment]
I worked around this by putting the Wails Go app in its own folder and adding `../../` to build:dir and frontend:dir, and I use `function wails { (cd cmd/my-app; command wails "$@";); }` (more or less) to run commands. That works well enough that I haven't put effort into a cleaner solution.

**Comment by firelizzard18** [comment]
@leaanthony #2009 definitely helps, and that is what I've been doing, but it would be really nice for the Go main package location to be decoupled from the wails.json location. What's the status of v3? I realize it's not ready for GA release but is it usable for someone who's not a developer of Wails?

**Comment by leaanthony** [comment]
Yeah no commitment on v3 release right now. Someone has made an app though so depending on what you want to do it may be ok. https://github.com/duolabmeng6/go-qoq
