### ISSUE TITLE
Allow the app to override how errors are marshalled

### ISSUE THREAD

**Issue by firelizzard18** [wailsapp/wails#2569]
### Is your feature request related to a problem? Please describe.

I am working on an app that uses a JSON-based API, which returns structured errors. The binding generator always calls `err.Error()` if the second return value is an error. That converts the structured errors into a string that is inconvenient to parse.

### Describe the solution you'd like

Change `CallbackMessage.Err` from `string` to `any` (or `json.RawMessage`) and add something like `ErrorFormatter func(error) any` to the app options. That way the behavior of existing apps won't change but apps could choose to specify an error formatter.

### Describe alternatives you've considered

Changing the return value from `(Response, error)` to `(Response, StructuredError)` doesn't work because the structured error implements the error interface and the dispatcher checks `if err, ok := retVal.(error); ok { ... }` instead of checking the declared return type. So the only alternative I can think of is to use a single return value or to wrap the error in something. Either of those options would lead to much less convenient bindings.

### Additional context

Here's a hack that does what I want:

```diff
diff --git a/v2/internal/app/app_production.go b/v2/internal/app/app_production.go
index afb67bdb..85653488 100644
--- a/v2/internal/app/app_production.go
+++ b/v2/internal/app/app_production.go
@@ -80,7 +80,7 @@ func CreateApp(appoptions *options.App) (*App, error) {
 		ctx = context.WithValue(ctx, "buildtype", "production")
 	}
 
-	messageDispatcher := dispatcher.NewDispatcher(ctx, myLogger, appBindings, eventHandler)
+	messageDispatcher := dispatcher.NewDispatcher(ctx, myLogger, appBindings, eventHandler, appoptions.ErrorFormatter)
 	appFrontend := desktop.NewFrontend(ctx, appoptions, myLogger, appBindings, messageDispatcher)
 	eventHandler.AddFrontend(appFrontend)
 
diff --git a/v2/internal/frontend/dispatcher/calls.go b/v2/internal/frontend/dispatcher/calls.go
index ef19c603..ec2cd10e 100644
--- a/v2/internal/frontend/dispatcher/calls.go
+++ b/v2/internal/frontend/dispatcher/calls.go
@@ -3,8 +3,9 @@ package dispatcher
 import (
 	"encoding/json"
 	"fmt"
-	"github.com/wailsapp/wails/v2/internal/frontend"
 	"strings"
+
+	"github.com/wailsapp/wails/v2/internal/frontend"
 )
 
 type callMessage struct {
@@ -49,7 +50,11 @@ func (d *Dispatcher) processCallMessage(message string, sender frontend.Frontend
 		CallbackID: payload.CallbackID,
 	}
 	if err != nil {
-		callbackMessage.Err = err.Error()
+		if d.errfmt != nil {
+			callbackMessage.Err = d.errfmt(err)
+		} else {
+			callbackMessage.Err = err.Error()
+		}
 	} else {
 		callbackMessage.Result = result
 	}
@@ -66,7 +71,7 @@ func (d *Dispatcher) processCallMessage(message string, sender frontend.Frontend
 // CallbackMessage defines a message that contains the result of a call
 type CallbackMessage struct {
 	Result     interface{} `json:"result"`
-	Err        string      `json:"error"`
+	Err        any         `json:"error"`
 	CallbackID string      `json:"callbackid"`
 }
 
diff --git a/v2/internal/frontend/dispatcher/dispatcher.go b/v2/internal/frontend/dispatcher/dispatcher.go
index 44a8886e..56092d37 100644
--- a/v2/internal/frontend/dispatcher/dispatcher.go
+++ b/v2/internal/frontend/dispatcher/dispatcher.go
@@ -7,6 +7,7 @@ import (
 	"github.com/wailsapp/wails/v2/internal/binding"
 	"github.com/wailsapp/wails/v2/internal/frontend"
 	"github.com/wailsapp/wails/v2/internal/logger"
+	"github.com/wailsapp/wails/v2/pkg/options"
 )
 
 type Dispatcher struct {
@@ -15,15 +16,17 @@ type Dispatcher struct {
 	events     frontend.Events
 	bindingsDB *binding.DB
 	ctx        context.Context
+	errfmt     options.ErrorFormatter
 }
 
-func NewDispatcher(ctx context.Context, log *logger.Logger, bindings *binding.Bindings, events frontend.Events) *Dispatcher {
+func NewDispatcher(ctx context.Context, log *logger.Logger, bindings *binding.Bindings, events frontend.Events, errfmt options.ErrorFormatter) *Dispatcher {
 	return &Dispatcher{
 		log:        log,
 		bindings:   bindings,
 		events:     events,
 		bindingsDB: bindings.DB(),
 		ctx:        ctx,
+		errfmt:     errfmt,
 	}
 }
 
diff --git a/v2/pkg/options/options.go b/v2/pkg/options/options.go
index 204a267c..202d53f9 100644
--- a/v2/pkg/options/options.go
+++ b/v2/pkg/options/options.go
@@ -62,6 +62,7 @@ type App struct {
 	OnShutdown         func(ctx context.Context)                `json:"-"`
 	OnBeforeClose      func(ctx context.Context) (prevent bool) `json:"-"`
 	Bind               []interface{}
+	ErrorFormatter     ErrorFormatter
 	WindowStartState   WindowStartState
 
 	// CSS property to test for draggable elements. Default "--wails-draggable"
@@ -86,6 +87,8 @@ type App struct {
 	Debug Debug
 }
 
+type ErrorFormatter func(error) any
+
 type RGBA struct {
 	R uint8 `json:"r"`
 	G uint8 `json:"g"`
```

**Comment by leaanthony** [comment]
We could use something like:

```func isError(value reflect.Value) bool {
	errorInterface := reflect.TypeOf((*error)(nil)).Elem()
	return value.Type().Implements(errorInterface)
}```

The challenge will be structs that happen to implement the error interface but it wasn't an error....

**Comment by firelizzard18** [comment]
> The challenge will be structs that happen to implement the error interface but it wasn't an error....

This is the case I am dealing with, except the struct type actually is an error and I want to treat it like an error. But I want it to be passed to the app as `{ "code": 123, "message": "foo", "data": "bar" }` instead of `"jsonrpc2.Error{Code: 123, Message: \"foo\", Data: \"bar\" }"`. With my patch, processing specific error conditions in the JS side is trivial. But without the patch I have to either parse the stringified version or do the processing on the Go side.

**Comment by leaanthony** [comment]
Out of interest, what's the signature of the method you're binding? Is it still returning an `error`?

**Comment by firelizzard18** [comment]
[Here's app.go](https://gitlab.com/accumulatenetwork/core/wallet/-/blob/wails/cmd/accumulate-app/app.go#L115). The methods are `func (a *App) DoStuff(request *DoStuffRequest) (*DoStuffResponse, error) { return a.jsonRpcClient.DoStuff(a.ctx, request) }`. When this returns a `jsonrpc2.Error` it is truly an error and I would prefer to retain the usual behavior of Wails - I like the fact that the error is not included in the return signature and is turned into a promise rejection.

The JSON-RPC errors are meaningful and I want both the error code and the message on the JS side. Of course I could wrap the JSON-RPC calls in a method that converted the `jsonrpc2.Error` to a simple string error and then parse that on the JS side, but it's a lot more natural to simply pass the structured `jsonrpc2.Error` directly back to the JS caller.

**Comment by leaanthony** [comment]
In the scenario where you use 2 return args, the second should always be an error so we could alter the error check to check for interface compliance rather than an error struct.

**Comment by firelizzard18** [comment]
I don't follow. `jsonrpc2.Error` is an error - `var err error = jsonrpc2.Error{}` compiles. My issue is that `Dispatcher.processCallMessage` converts an error value to a string by calling `err.Error()` which makes it harder than it needs to be to process JSON-RPC errors. Changing the type of `CallbackMessage.Err` to any and including an option to override how that field is assigned completely solves my issue and is fully backwards compatible. CallbackMessage is an internal type so no external code could be depending on its type, and making the change didn't cause any compile failures so presumably no internal code is depending on its type. With the default behavior (without setting the option) the JavaScript side won't see a difference because the value will still be a string.

**Comment by leaanthony** [comment]
@firelizzard18 - any updates?

**Comment by firelizzard18** [comment]
I've been using my own fork and I haven't had much time to work on that project

**Comment by mklnz** [comment]
Are custom error types in go always serialised as a string type error on the frontend using .Error()?
It would be nice to have custom serialized errors on the frontend too

**Comment by firelizzard18** [comment]
@mklnz When the frontend calls a backend method, and that method returns two values, and the second value implements `type error interface{ Error() string }`, the frontend-backend interface code (`processCallMessage` in this case) will always call `Error()` on the second return type. I am suggesting adding a way to override that.

I think that's what you're asking about? You say "in go" and "on the frontend" but the frontend is not written in Go; and you say "custom serialized errors on the frontend" but the serialization we're talking about is at the interface/boundary between the two; so I'm not sure certain that's what you're asking about.

**Comment by mklnz** [comment]
Sorry yes I should've been more specific. Basically even if I have a custom error type in Go with few more fields such error code (it implements the .Error() interface), by the time it reaches the frontend javascript it is a plain error with the output from .Error() but all other fields no longer exist.

This means on the frontend javascript you're limited to string errors only and no other struct fields defined in Go

**Comment by leaanthony** [comment]
Still happy to accept a PR on this.

**Comment by dennypenta** [comment]
thanks a lot guys, very valuable for me, now easy peasy to inject any error tracer here
