### ISSUE TITLE
Need to know when the app is focused or not

### ISSUE THREAD

**Issue by dzpt** [wailsapp/wails#2570]
### Is your feature request related to a problem? Please describe.

Yes.
For example to detect the user key press, the focus state is required to know the user is using the app or not.

### Describe the solution you'd like

Provide app level object which has focus property

**Comment by leaanthony** [comment]
What would this look like? A callback when focussed?

**Comment by leaanthony** [comment]
This is implemented in v3 via events. Feel free to backport to v2 👍
