### ISSUE TITLE
Ability to build the program without any icon

### ISSUE THREAD

**Issue by pluutoon** [wailsapp/wails#2573]
### Is your feature request related to a problem? Please describe.

I found myself unable to build my app without any icon, thus having the default one provided by the OS.

### Describe the solution you'd like

Being able to toggle if we want a specific icon to be set when building the app or not, maybe from a parameter in the _wails.json_ file.

Thus, three main cases are possible:
- The custom icon is enabled but no/invalid icon is provided: set it to the wails' default one.
- The custom icon is enabled and provided: build the program using the provided icon.
- The custom icon is disabled: set the icon to the default one depending on the target OS.

### Describe alternatives you've considered

Not regenerating the wails' default icon when the user deletes it until a specific wails command is executed.

**Comment by leaanthony** [comment]
This is something that will be available in v3. Unlikely to be done in v2.
