### ISSUE TITLE
macOS: Window management shortcuts like Cmd+Ctrl+F don't work

### ISSUE THREAD

**Issue by mholt** [wailsapp/wails#2582]
### Description

Wails windows, both `Frameless: true` and `Frameless: false`, are not able to be controlled by macOS utilities like Magnet (which aligns/tiles windows) and keyboard shortcuts like Cmd+Ctrl+F which full-screens an application.

### To Reproduce

Run (presumably) any Wails app, and try to fullscreen with Cmd+Ctrl+F. Note that this shortcut does work on other applications.

If you have Magnet or other tiling utilities installed, try using those to control the window.

### Expected behaviour

Application should fullscreen. Utilities like Magnet should be able to resize and move the window.

### Attempted Fixes

Tried toggling Frameless, playing with Fullscreen options, and other options.App settings, but no luck.

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.2.1  
ID           | 22D68   
Go Version   | go1.20.1
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.4.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2396   
npm                       | N/A          | Installed | 9.4.0  
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

### Additional context

Thanks for working on a really hard problem (Wails in general I mean) :blush:

**Comment by stffabi** [comment]
> If you have Magnet or other tiling utilities installed, try using those to control the window.

https://rectangleapp.com seems to work fine with a Wails application, the tiling features worked all as expected.

> Cmd+Ctrl+F

Does not work currently and probably needs an internal handler and do a fullscreen.

**Comment by stffabi** [comment]
Can confirm we do need to add a menu item for `Cmd+Ctrl+F` to work, same for `Cmd+M` to support minimize.

But have no idea what's needed for Magnet.

**Comment by stffabi** [comment]
There are also other missing shortcuts
- AppMenu: Hide `Cmd+M`, Hide Others `Option+Cmd+M`
- WindowMenu: Minimize `Cmd+M` and I would put Fullscreen `Cmd+Ctrl+F` in there.

@mholt what other Tiling utilities did you try? Is there some open source one? Where we could get info what's needed.

**Comment by stffabi** [comment]
You could give PR #2586 a try, it adds some of the missing shortcuts. Please be aware, that the Window shortcuts only work if not frameless. You can also use a non frameless window and use `TitleBar: mac.TitleBarHidden()` to get the traffic lights into your webview to get a frameless behaviour with Window shortcuts.

**Comment by mholt** [comment]
Thank you @stffabi -- I haven't tried any tiling utilities myself. I'm not a daily Mac user; it's basically my travel laptop and as-needed for builds, so this report came from another user of my app. I'd imagine other tiling utilities probably use the same Cocoa (?) APIs?

Anyway, I finally had a chance to try your patch and indeed the shortcuts do work. Thank you!

One last question: since the Fullscreen (and Minimize) shortcut doesn't work with `Frameless: true`, do you think it's possible for my app to capture that keystroke and manually call the runtime to do those things?

**Comment by stffabi** [comment]
> I'd imagine other tiling utilities probably use the same Cocoa (?) APIs?

Would be interesting to check another tiling utilities, since rectangle seems to work just fine.

> Anyway, I finally had a chance to try your patch and indeed the shortcuts do work. Thank you!

Awesome, thanks for testing it.

> One last question: since the Fullscreen (and Minimize) shortcut doesn't work with Frameless: true, do you think it's possible for my app to capture that keystroke and manually call the runtime to do those things?

That might be possible but needs another lib to catch shortcuts, I think somewhere someone mentioned one that worked successfully.
If I might ask, is using `TitleBar: mac.TitleBarHidden()` not acceptable for your app? You would still have the freedom to use the whole window but you just have the default "traffic lights (close, minimize, fullscreen)" of macos shown in the transparent titlebar. To be honest I'm currently not aware of any macOS app that I daily use which don't have those, even if they are frameless and draw into the transparent "title bar".

**Comment by leaanthony** [comment]
@mholt - I started integrating https://github.com/robotn/gohook as a plugin, but TBH, mapping the keys between the 2 worlds was too much. It's much easier for you to just import it and use it as you intended. Let us know how you get on 👍

**Comment by mholt** [comment]
@stffabi Interesting! I can probably use `TitleBarHidden()` (or actually `TitleBarHiddenInset()` looks a little nicer) but I'll just need to move some UI elements around on Mac-only. But yeah that actually looks good, I just didn't know about it before.

So on Mac I'll set `Frameless: false` and use `mac.TitleBarHiddenInset()`. Thanks for the pointer. That seems to make the fullscreen shortcut work.

**Comment by leaanthony** [comment]
This PR is relevant :-) https://github.com/wailsapp/wails/pull/2586

**Comment by mholt** [comment]
Yes :) Thanks
