### ISSUE TITLE
[windows11]build project stuck on "Installing frontend dependencies:"

### ISSUE THREAD

**Issue by legiorange** [wailsapp/wails#2583]
### Description

build project stuck on "Installing frontend dependencies:":
Wails CLI v2.4.1
Template: Svelte + TS + Vite

Run command "wails dev":
DEB | Using go webview2loader
Wails CLI v2.4.1

• Generating bindings: Done.
• Installing frontend dependencies: 

**And stuck here .** 

not output.

And run command add Verbosity"wails dev -v 2"

Executing: go mod tidy
  • Generating bindings:  INFO  
Done.
  • Installing frontend dependencies:
 INFO  Install command: 'npm install'

And .... stuck too.
```
npm version
{
  npm: '8.15.0',
  node: '17.0.1',
  v8: '9.5.172.21-node.12',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '102',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.0+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

```

### To Reproduce

wails init -n myproject -t svelte-ts
cd myproject
wails dev

### Expected behaviour

Skip.

### System Details

```shell
OS           | Windows 11 Pro
Version      | 10.0.22621 (Build: 22621)
Go Version   | go1.20.3
Platform     | windows
Architecture | amd64
```

**Comment by leaanthony** [comment]
@legiorange - Any updates?

**Comment by dami-i** [comment]
Exact same issue here. Also using svelte-ts template.

```
OS:           Windows 11 22H2 22621.1848
Terminal:     PowerShell 7.3.4 and Command Prompt
Node version: 18.16.0
Go version:   1.20.4
```

`wails doctor`: Everything fine.

The `node_modules` directory is not even created during `npm install` stage.

**Comment by leaanthony** [comment]
Cool. That's normally the reason. Closing this for now.
