### ISSUE TITLE
Korean characters are displayed abnormally in Title

### ISSUE THREAD

**Issue by scshin0572** [wailsapp/wails#259]
**Description**

Korean characters are displayed abnormally in Title

* Ubuntu 18.04 : normal
* macOS 10.14.6 : normal
* Windows 10 1903 : abnormal

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![2019-10-14-16-01-08](https://user-images.githubusercontent.com/38400424/66734004-7f538680-ee9c-11e9-98c1-3a5b5416ae38.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.3 |
| Go Version    | go1.12.7 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | v12.9.0
 |
| Node          | 6.10.2 |

**Additional context**

**Comment by leaanthony** [comment]
Hi there @scshin0572 - Thanks for opening this and sorry it's taken so long to respond. I had a [previous ticket](https://github.com/wailsapp/wails/issues/151) about Chinese characters that I thought was a local issue but looking back on it, the commonality is Windows. This is directly related to the WebView library that we use and my guess is that it is related to UTF-8 vs UTF-16. 

Looking on the Webview site, it seems that there is a [workaround](https://github.com/zserge/webview/issues/102). If you can confirm this works, I will add this to Wails so you don't need to. 👍

**Comment by leaanthony** [comment]
There is also this which may work better: https://godoc.org/golang.org/x/text/encoding/korean

**Comment by scshin0572** [comment]
This problem was solved by using "golang.org/x/text/encoding/korean". but I hope this is handled internally by "Wails".
Thank you.

**Comment by leaanthony** [comment]
Awesome news! Do you have any code snippets on how you did this? It would really help another ticket for Chinese encoding and help me understand how we *might* be able to handle this automatically. Thanks!

**Comment by scshin0572** [comment]
```Go
package main

import (
	"bytes"
	"runtime"

	"github.com/leaanthony/mewn"
	"github.com/wailsapp/wails"

	"golang.org/x/text/encoding"
	"golang.org/x/text/encoding/korean"
	"golang.org/x/text/transform"
)

func basic() string {
	return "Hello World!"
}

func toMBCS(str string, enc encoding.Encoding) string {
	if runtime.GOOS != "windows" {
		return str
	}

	if len(str) == 0 {
		return ""
	}

	var bufs bytes.Buffer
	wr := transform.NewWriter(&bufs, enc.NewEncoder())
	_, err := wr.Write([]byte(str))
	defer wr.Close()
	if err != nil {
		return ""
	}

	return bufs.String()
}

func main() {

	js := mewn.String("./frontend/dist/app.js")
	css := mewn.String("./frontend/dist/app.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 768,
		Title:  toMBCS("안녕", korean.EUCKR),
		// Title: toMBCS("你好", simplifiedchinese.GBK),    //"golang.org/x/text/encoding/simplifiedchinese"
		// Title: toMBCS("你好", traditionalchinese.Big5),  //"golang.org/x/text/encoding/traditionalchinese"
		// Title: toMBCS("こんにちは", japanese.EUCJP),     //"golang.org/x/text/encoding/japanese"
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})
	app.Bind(basic)
	app.Run()
}

**Comment by sixinyiyu** [comment]
thanks  it's work, with use encoding

**Comment by leaanthony** [comment]
![image](https://user-images.githubusercontent.com/1943904/67382675-99e2d980-f5d9-11e9-84d0-3d26cea7a51a.png)
I can't get Korean fonts displayed correctly on my machine, even with the Korean supplemental fonts installed. However, I'm able to produce the same looking characters as your example so I think I'm getting somewhere :-)

**Comment by leaanthony** [comment]
Hi. I've created a fix that I can't fully test locally. Could you please see if your original code works with this version please?
`wails update -pre` should update you to v0.18.6-pre with the fix 🤞

**Comment by leaanthony** [comment]
Bumped the version to v0.18.7-pre with some linting fixes

**Comment by scshin0572** [comment]
It was tested in v0.18.7-pre

1. Korean Only (안녕) : It works.
![2019-10-25-01](https://user-images.githubusercontent.com/38400424/67543066-8d21cb00-f72a-11e9-8dfc-ebde077a7586.png)

2. Korean + English (안녕-Hello) : It does not work.
![2019-10-25-02](https://user-images.githubusercontent.com/38400424/67543075-96129c80-f72a-11e9-87fe-44f2c8b1d379.png)


3. English + Korean (Hello-안녕) : It does not work.
![2019-10-25-03](https://user-images.githubusercontent.com/38400424/67543087-a0cd3180-f72a-11e9-943b-996f811a7417.png)

**Comment by leaanthony** [comment]
I have added updates to v0.18.10-pre. Could you please check using that version? Thanks!

**Comment by scshin0572** [comment]
I tested in v0.18.10-pre.

1. Korean Only (안녕) 
2. Korean + English (안녕-Hello) 
3. English + Korean (Hello-안녕) 

It works well in all cases.

But, I think you need to addition modification in "webview.h" file
```c++
  WEBVIEW_API void webview_set_title(struct webview *w, const char *title)
  {
  #ifdef UNICODE
    wchar_t *u16title = webview_to_utf16(title);
    if (u16title == NULL)
    {
      return;
    }
    SetWindowText(w->priv.hwnd, u16title);
    GlobalFree(u16title);
  #else
    SetWindowText(w->priv.hwnd, title);
  #endif
  }

**Comment by leaanthony** [comment]
Superb! Thank you for taking the time to test and debug this. I've added in the fixes to `v0.18.12-pre` and added you to the CONTRIBUTORS.MD file :smile: :+1:

**Comment by leaanthony** [comment]
Make that v0.18.13-pre :-)
I actually can't get it to work. It's garbled for me, but I'm going to put that down to some windows locale weirdness...

**Comment by scshin0572** [comment]
Based on version v0.18.3, the Unicode related parts were further modified.

Applying this will also resolve #278.

I have attached the modified files.
[webview.zip](https://github.com/wailsapp/wails/files/3782065/webview.zip)

**Comment by leaanthony** [comment]
Thanks for spending time on this. So with this patch you can generate a project and it works?

**Comment by scshin0572** [comment]
Before applying the patch files: an error occurred.
- Under HKEY_CURRENT_USER, you can see that a garbage key has been created.
![2019-10-31-01](https://user-images.githubusercontent.com/38400424/67919151-84c20800-fbe2-11e9-9cb8-c6ee44c7b6d5.png)

- And also you can see that the wrong value under garbage key.
![2019-10-31-02](https://user-images.githubusercontent.com/38400424/67919168-9a373200-fbe2-11e9-8083-92c4a9290a21.png)


After applying the patch files: no error occurred
- Under HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION,
you can see the same value as your executable file name.
![2019-10-31-03](https://user-images.githubusercontent.com/38400424/67919185-a8854e00-fbe2-11e9-8d96-98a3f5caf0c0.png)


If the error still occurs after applying the patch files, 
check if the value is recorded correctly in the above-mentioned Registry key.

Manually add the same value as your executable file name and run it, after that you should not get any errors.

**Comment by leaanthony** [comment]
Thanks for the update! I'm looking at this on Saturday :+1:

**Comment by leaanthony** [comment]
Hey @scshin0572 - could you please let me know if your patch works against the current develop branch? Thanks.

**Comment by scshin0572** [comment]
v0.18.15-pre: an error occurred.

the latest patch files did not apply to the v0.18.15-pre version.

This is a comparison of the two versions(the latest code and v0.18.15-pre).

webview.h(left: the latest, right: v0.18.15-pre)
1. 
<img width="1101" alt="2019-11-02-webview-h-1" src="https://user-images.githubusercontent.com/38400424/68072013-2eacba80-fdc4-11e9-83ff-75d58ebd009d.png">

2. 
<img width="1507" alt="2019-11-02-webview-h-2" src="https://user-images.githubusercontent.com/38400424/68072024-51d76a00-fdc4-11e9-9fd5-168a4a2b8232.png">

3.
<img width="1526" alt="2019-11-02-webview-h-3" src="https://user-images.githubusercontent.com/38400424/68072033-77fd0a00-fdc4-11e9-8321-51d9469d5bf7.png">

4.
<img width="1446" alt="2019-11-02-webview-h-4" src="https://user-images.githubusercontent.com/38400424/68072038-82b79f00-fdc4-11e9-8d88-97f0ae7c5d9f.png">

webview.go (left: the latest, right: v0.18.15-pre)
1.
<img width="1427" alt="2019-11-02-webview-go-1" src="https://user-images.githubusercontent.com/38400424/68072048-9fec6d80-fdc4-11e9-94e7-e551ccf54263.png">

**Comment by leaanthony** [comment]
I had to take out the Unicode updates for the 0.19 release. I'll look at reapplying them for the next release. What I would like to understand is if the Go updates were necessary (encoding detection), or were the webview updates sufficient? I couldn't get it working either way so a PR would be ideal.

**Comment by leaanthony** [comment]
Fixed in v2

**Comment by audrenbdb** [comment]
Sorry to reopen this; I have trouble compiling to get some UTF8 characters.

Is there a flag to pass to get them to work ? I can't use wails build atm as it's being used as a library.

**Comment by leaanthony** [comment]
Not for v1 I'm afraid. The good news is v2 for Windows is pretty damn close. Can you give me an example and I'll test locally

**Comment by audrenbdb** [comment]
Thanks leaanthony for the time you put into it. Characters I had problem with were standard french characters and also vietnamien ones : é or É for instance are problematic.

**Comment by leaanthony** [comment]
If you open a webpage in IE11 with those characters, does it show them correctly in the titlebar? We spent some time on this and it seemed way harder than it should.

**Comment by audrenbdb** [comment]
Tested now, IE11 renders those characters correctly.

**Comment by audrenbdb** [comment]
Apologize I was wrong, IE seems unable to render them correctly in the title.
![Screenshot_20210823_175740](https://user-images.githubusercontent.com/45963221/130479113-fa637b64-68ca-4347-9bae-cfcd0107f8c9.png)

**Comment by leaanthony** [comment]
That's almost certainly the issue. Check back in a couple of weeks for a fix 😉
