### ISSUE TITLE
Cookies cannot be set on macos

### ISSUE THREAD

**Issue by helloxz** [wailsapp/wails#2590]
### Description

I am on the macos platform. I can normally set cookies in dev mode, but setting cookies after build is invalid.

I did a comparison check with debug mode and found this to be the case.

### To Reproduce

run `wails dev` ok

```js
document.cookie = "username=John Doe; expires=" + new Date(new Date().getTime() + (24 * 60 * 60 * 1000)).toUTCString() + "; path=/";
```

run `wails build -debug` failed

```js
document.cookie = "username=John Doe; expires=" + new Date(new Date().getTime() + (24 * 60 * 60 * 1000)).toUTCString() + "; path=/";
```

### Expected behaviour

Cookies can be set correctly and effectively

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.3.1  
ID           | 22E261  
Go Version   | go1.20.3
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.4.1

# Dependencies

Dependency                | Package Name | Status    | Version  
Xcode command line tools  | N/A          | Installed | 2397     
npm                       | N/A          | Installed | 9.5.0    
*Xcode                    | N/A          | Available |          
*upx                      | N/A          | Installed | upx 4.0.2
*nsis                     | N/A          | Available |          
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Is your expectation that webviews support cookies? Do they?

**Comment by helloxz** [comment]
* `wails dev`(support cookies)
* `wails build`(no suppot cookies)

I hope the wails build can also support setting cookies

**Comment by helloxz** [comment]
Excuse me, have you reproduced this BUG?

**Comment by evorts** [comment]
In my opinion, having no cookie support does not posed a critical issue. Since it can be handled by either LocalStorage (which hadn't been an issue for me) or perhaps by the `golang`/`backend` side of the wails app. Cookie imho much more appropriate for web development which run on full fledge browser. Again, this is just my opinion

**Comment by misitebao** [comment]
It is not recommended to use Wails as a browser. 👀

**Comment by leaanthony** [comment]
Yeah, Wails doesn't bundle a browser.

**Comment by helloxz** [comment]
> Yeah, Wails doesn't bundle a browser.

Oddly enough, cookies is supported in development mode, but cookies is not supported after packaging. What is the reason why this problem does not exist under windows? I temporarily switched to localStorage to circumvent this problem.

**Comment by leaanthony** [comment]
When you say "development mode", do they work in the app (not the browser)?

**Comment by helloxz** [comment]
> When you say "development mode", do they work in the app (not the browser)?

Yes, it works in the application, not in the browser.

**Comment by leaanthony** [comment]
@helloxz - Can you please retest with the latest version. Thanks.

**Comment by adityak368** [comment]
This looks like an issue. I am not able to set cookies even on windows.

**Comment by airtonix** [comment]
yeah responses will show that there are cookies, but it looks like that there is no cookie storage implemented.

![image](https://github.com/user-attachments/assets/6837bf05-a276-4eb2-83d0-4db1580be44f)

![image](https://github.com/user-attachments/assets/cfefa508-6779-4a8c-8069-b7a955409fec)

**Comment by gj1118** [comment]
Same is the case with me.. I am using securetokens to handle authentication. SecureTokens will try to set the cookie, but I am getting the following error 
![image](https://github.com/user-attachments/assets/750dd0fa-e54c-4518-8be2-9e9260d5d679)
I dont see this issue when I visit the url directly in Safari . I am on MacOS

**Comment by leaanthony** [comment]
Moving all cookie related feedback to #3908
