### ISSUE TITLE
StartHidden option not working on Linux

### ISSUE THREAD

**Issue by peterjah** [wailsapp/wails#2605]
### Description

The StartHidden option has no effect on Linux.
Looking at the wails code I see the startHidden option is well handeled for darwin and windows here:
`v2/internal/frontend/desktop/darwin/window.go`
`v2/internal/frontend/desktop/windows/frontend.go`
But the option is not taken into account for Linux.

Is there any technical limitation that prevent this option to work on Linux ?
In that case it would be nice to have the info in the docs.
Or maybe it just something that has been forgotten for Linux ?

### To Reproduce

On linux
1 init new project `wails init -n wailds-starthidden -t react-ts`
2. add `StartHidden: true` in the Run() options
3 run the app, and the windows showing

### Expected behaviour

The windows is actually hidden

### System Details

```shell
# System

OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version   | go1.19.5
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.4.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 23.0.1                 
gcc        | build-essential       | Installed | 12.9ubuntu3            
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2       
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.5-0ubuntu0.22.04.1
npm        | npm                   | Installed | 8.19.2                 
*nsis      | nsis                  | Available | 3.08-2                 
pkg-config | pkg-config            | Installed | 0.29.2
```

**Comment by leaanthony** [comment]
Oh, that might have simply been an oversight but I'm surprised it's not come up before. We'll take a look 👍

**Comment by lrstanley** [comment]
Seeing the same in WSL2/Ubuntu. Details in case it's helpful:

```console
# System

OS           | Ubuntu
Version      | 20.04
ID           | ubuntu
Go Version   | go1.20.3
Platform     | linux
Architecture | amd64

# Wails

Version         | v2.4.1
Package Manager | apt

# Dependencies

Dependency | Package Name          | Status    | Version
*docker    | docker.io             | Installed | 20.10.23
gcc        | build-essential       | Installed | 12.8ubuntu1.1
libgtk-3   | libgtk-3-dev          | Installed | 3.24.20-0ubuntu1.1
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.2-0ubuntu0.20.04.1
npm        | npm                   | Installed | 9.5.1
*nsis      | nsis                  | Installed | v3.05-2
pkg-config | pkg-config            | Installed | 0.29.1-0ubuntu4
```
