### ISSUE TITLE
Cannot build nsis installer - no windows targets on `windows/386`

### ISSUE THREAD

**Issue by kkrypt0nn** [wailsapp/wails#2607]
### Description

When running

```
wails build --platform windows/386 -webview2 download -nsis
```

The file gets successfully built, and is executable as well.

Though the CLI returns

```
Built '[...]/build/bin/myproject.exe' in 3.385s.


  ERROR   cannot build nsis installer - no windows targets
```

Which leads to a GitHub build, from https://github.com/dAppServer/wails-build-action, to fail and not continue execution.

### To Reproduce

1. Create a project with `wails init -n myproject -t react-ts`
2. Execute `wails build --platform windows/386 -webview2 download -nsis`

### Expected behaviour

The CLI should return no error and exit normally.

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.3.1  
ID           | 22E261  
Go Version   | go1.20.3
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.4.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397   
npm                       | N/A          | Installed | 9.6.3  
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

Wails doesn't officially support `windows/386`. That means it's only community maintained and not officially by the Wails core team. As such there are no guarantees that newer releases of Wails will support it or all features will work because no explicit tests are done against that platform.
It would probably be good to output a warning/information that one is using an unofficial community maintained platform.

However we would be happy to accept a PR to add 386 NSIS support.

**Comment by stffabi** [comment]
> By 386 NSIS support you mean entire support or just not erroring once it's built?
> 
> Since technically it's working fine, the CLI just returns an error at the end that shouldn't appear.

Currently there's no installer support for 386. Not outputing an error at the end would mean, either the installer would not exist or it won't install anything or the wrong architecture in the end. So it would need entire support. 
If you have customised your NSIS project that it also works for NSIS I would suggest you to probably run `makensis` manually after the wails build.
