### ISSUE TITLE
Generated TypeScript Functions Should Use Correct Type Instead of ``any``

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#2611]
### Is your feature request related to a problem? Please describe.

This is not a problem. But it is nice to have.

For example I have a ``app.go``
```go
type AppSettings struct {
	General struct {
		IsEnableMaxMinWindow bool `json:"isEnableMaxMinWindow"`
	} `json:"general"`
}

...

func (a *App) GetAppSettings() (*AppSettings, error) {
	return &AppSettings{}, nil
}
```

Wails will automatically generate a ``models.ts`` file with ``class AppSettings`` in ``wailsjs\go\main``.

### Describe the solution you'd like

The ``App.d.ts`` should automatically grab that class and use it as a type like:
```ts
//So instead of
export function GetAppSettings():Promise<any>;
//Do this
export function GetAppSettings():Promise<AppSettings>;
```

**Comment by AlbinoDrought** [comment]
I was experiencing the correct behaviour on 2.3.0 but am now seeing `Promise<any>` on 2.4.1

**Comment by KiddoV** [comment]
@AlbinoDrought is there any open issue for this one in the past?

**Comment by AlbinoDrought** [comment]
@KiddoV I think this is probably the same issue as https://github.com/wailsapp/wails/issues/2489

**Comment by stffabi** [comment]
@KiddoV would it be possible for you to test the current master, because #2489 has been merged?

**Comment by KiddoV** [comment]
I tested. It works now!
Funny, all of that just for 1 line of code:
```go
mapRegex = regexp.MustCompile(`(?:map\[(?:(?P<keyPackage>\w+)\.)?(?P<keyType>\w+)])?(?P<valueArray>\[])?(?:\*?(?P<valuePackage>\w+)\.)?(?P<valueType>.+)`)
```
https://github.com/dominictwlee/wails/blob/7b1ceda414687a007e9b2e96ab2e43ced2882845/v2/internal/binding/generate.go#L26

Thanks,
