### ISSUE TITLE
> windows11 专业版 22621.1413 编译的exe无法正常运行

### ISSUE THREAD

**Issue by ziveni** [wailsapp/wails#2615]
> windows11 专业版 22621.1413 编译的exe无法正常运行

Just to make sure, did you test the old WebView2Loader by using `-tags native_webview2loader`?

_Originally posted by @stffabi in https://github.com/wailsapp/wails/issues/2004#issuecomment-1470067427_
            
![image](https://user-images.githubusercontent.com/48472180/233379791-7e621d53-e19e-4e2a-ae71-240b7842d0b8.png)

**Comment by ziveni** [comment]
> 您能否尝试编译应用程序并为我们提供控制台输出，并查看您在那里看到的内容？`--debug``webinspector`

![image](https://user-images.githubusercontent.com/48472180/233382639-988fde55-1ccc-4636-9829-25b82fe70d86.png)
nothing!

**Comment by stffabi** [comment]
What do you see in the inspector? Right click on the window and select `Inspect`. Then the `console` tab and `network` tab is interesting.

**Comment by ziveni** [comment]
> I have right-clicked on the window, but nothing is displayed.

**Comment by ziveni** [comment]
> What do you see in the inspector? Right click on the window and select `Inspect`. Then the `console` tab and `network` tab is interesting.

"I think there might be an issue with my computer, but I haven't figured out where the problem is yet."

**Comment by stffabi** [comment]
Maybe you find something in the Windows Event-Viewer.

**Comment by stffabi** [comment]
This might be interesting for you: https://github.com/wailsapp/wails/discussions/2621

**Comment by stffabi** [comment]
Could you please try PR #2627, it should help in your case.

**Comment by stffabi** [comment]
I'm going to close this, we believe it should be fixed with the linked PR. Please feel free to reopen if you see any further issues.

**Comment by ziveni** [comment]
> I'm going to close this, we believe it should be fixed with the linked PR. Please feel free to reopen if you see any further issues.

 Unknown message from front end: runtime:ready

I got the following error when running wails dev. I'm not sure if it's related to the desktop not showing up.

**Comment by StormYudi** [comment]
Same problem here.
WebVie2wProcess failed with kind 1

<img width="611" alt="image" src="https://github.com/wailsapp/wails/assets/19419186/b65c4da2-46cc-4cbc-b68e-156da0e93079">
<img width="1001" alt="image" src="https://github.com/wailsapp/wails/assets/19419186/332d8d65-355f-4bb5-996c-4c4690a5e650">

**Comment by StormYudi** [comment]
build 

> 这里同样的问题。 WebVie2wProcess 失败，类型 1
> 
> <img alt="图像" width="611" src="https://user-images.githubusercontent.com/19419186/251611684-b65c4da2-46cc-4cbc-b68e-156da0e93079.png"> <img alt="图像" width="1001" src="https://user-images.githubusercontent.com/19419186/251611722-332d8d65-355f-4bb5-996c-4c4690a5e650.png">

build from macos aarch64, wails v2.5.1, cross build for amd64 windows.

**Comment by StormYudi** [comment]
<img width="477" alt="image" src="https://github.com/wailsapp/wails/assets/19419186/8189b4b4-e129-4afa-aca2-3adebeea05a4">

using `-tags native_webview2loader` getting same result.

**Comment by leaanthony** [comment]
Please open a new ticket and provide everything it asks. Thanks 🙏

**Comment by stffabi** [comment]
@StormYudi please take a look into the event-viewer. I suspect you are running into the same code-integrity problem, where a custom DLL injects itself into the webview2 process, which is detected by Microsoft and prevented by a crash of the webview.

You could try to use the flag to disable code-integrity checks of webview2 and check if that helps: https://github.com/wailsapp/wails/blob/c1a0e1338fa8eda0600d9ce84467fc8ed63f32e5/v2/pkg/options/windows/windows.go#L107-L115
