### ISSUE TITLE
Quit app from within backend

### ISSUE THREAD

**Issue by Pixdigit** [wailsapp/wails#262]
It could very well be that I missed it somewhere but is there a way to programmatically exit the application I mean besides `OS.exit()` which is unclean?

**Comment by leaanthony** [comment]
Hey @Pixdigit. Thanks for opening this. It's true, there isn't a specific runtime call to do this and I think it's a glaring omission. I consider this a bug and will add it this week :+1:

**Comment by leaanthony** [comment]
Technically, runtime.Window.Close() will exit from the app but there is no callback to allow you to shut down your resources, which is what I'm assuming you are wanting.

**Comment by leaanthony** [comment]
Hey there, I did a new release with a bunch of stuff around application shutdown. You can now hook into application shutdown using [WailsShutdown](https://wails.app/reference/#struct-shutdown). This will get called whenever you call `runtime.Window.Close()`, Kill the window or use `ctrl-c` (Windows is tricky on this front).

Example that I used for testing:

```
package main

import (
	"github.com/wailsapp/wails"
)

type Test struct {
	runtime *wails.Runtime
	log     *wails.CustomLogger
}

func NewTest() *Test {
	return &Test{}
}

func (t *Test) Kill() {
	t.runtime.Window.Close()
}

func (t *Test) WailsInit(runtime *wails.Runtime) error {
	t.runtime = runtime
	t.log = runtime.Log.New("Test Struct")
	return nil
}

func (t *Test) WailsShutdown() {
	t.log.Info("WailsShutdown() Called!")
}
```

Calling `window.backend.Test.Kill()` does exactly what you think it should.

Update using `wails update` and let me know how you get on.

**Comment by Pixdigit** [comment]
Yes, that is what I mean. However in my setup (with v0.18.5) WailsShutdown isn't called. Besides in the api reference you return an error but do not declare a return type. So must WailsShutdown return an error? [This](https://pastebin.com/tZFrLzTp) is the code  code I used for the testing. I also tried without returning an error.

**Comment by leaanthony** [comment]
Hi. Where in the reference does it state you need to return an error? I searched codebase plus docs. Also, what OS are you using?

**Comment by leaanthony** [comment]
Running your test app I get:
```
$ ./shutdown 
Bound Runtime
Shutting Down!
```
Running in debug mode and shutting down via js command `window.backend.Runtime.Quit`:
```
$ ./shutdown
Fermion - Debug Build
---------------------
INFO[0000] [App] Starting                               
INFO[0000] [WebView] Initialised                        
INFO[0000] [Events] Starting                            
INFO[0000] [IPC] Starting                               
INFO[0000] [Bind] Starting                              
INFO[0000] [Bind] Binding Go Functions/Methods          
INFO[0000] [Bind] Bound Method: main.Runtime.Quit()     
Bound Runtime
INFO[0000] [Events] Listening                           
INFO[0000] [WebView] Running...                         
Goodbye!
Shutting Down!
```

**Comment by Pixdigit** [comment]
In line 19 you `return nil` even tough no return value is deklared.
![Bildschirmfoto_2019-10-26_18-29-37](https://user-images.githubusercontent.com/9216782/67622833-a310b800-f81e-11e9-905a-3e2d94f37f15.png)


I use Ubuntu. Very weird that it does not invoke it on my system.

And for me the output (without returning an error in WailsShutdown) is:
Fermion - Debug Build
---------------------
INFO[0000] [App] Starting                               
INFO[0000] [WebView] Initialised                        
INFO[0000] [Events] Starting                            
INFO[0000] [Events] Listening                           
INFO[0000] [IPC] Starting                               
INFO[0000] [Bind] Starting                              
INFO[0000] [Bind] Binding Go Functions/Methods          
INFO[0000] [Bind] Bound Method: main.Runtime.Quit()     
INFO[0000] [Bind] Bound Method: main.Runtime.WailsShutdown() 
Bound Runtime
INFO[0000] [WebView] Running...                         
Goodbye!

**Comment by bh90210** [comment]
@Pixdigit  I think the `return nil` it's probably a typo.

**Comment by leaanthony** [comment]
Thanks @Pixdigit. Will fix the docs!

**Comment by leaanthony** [comment]
Also, Please test against the latest pre release `wails update -pre` for the Shutdown issue.

**Comment by Pixdigit** [comment]
I made an empty test project with the code shared in pastebin. In that case everything works as intended.
Turns out I forgot to `wails migrate`. To mitigate this issue maybe execute `wails migrate` automatically after `wails update` since it modifies the project only with consent.

**Comment by leaanthony** [comment]
Ah that's great news. `wails migrate` is really new and I think I'd rather that be a manual process as it's a one-off operation. Really pleased it's working for you and thanks for opening this issue. It's something we really needed to address and the project as a whole is much better for it :+1:
