### ISSUE TITLE
allow MessageDialog set <input/>

### ISSUE THREAD

**Issue by zundaren** [wailsapp/wails#2620]
### Is your feature request related to a problem? Please describe.

Verification is sometimes not safe in js，allow users to enter content to verify whether it is correct, such as entering a password to pass

### Describe the solution you'd like

ok => (input == "123") ?  pass : fail

fail => exit(0) or（Continue to verify）

**Comment by leaanthony** [comment]
This isn't a Wails issue but a concern for your JavaScript.
