### ISSUE TITLE
How to use Go to process the files selected by the frontend?

### ISSUE THREAD

**Issue by devzwy** [wailsapp/wails#2633]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

May I ask how to hand over the files I have selected on the Vue end to the Go code for processing. Vue does not support obtaining file paths.
If the go code actively calls the function of Vue, are there any reference examples.
Thank you for your library.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by LGiki** [comment]
You can write a Go function that uses the [`OpenFileDialog`](https://wails.io/docs/reference/runtime/dialog#openfiledialog) method to open a native file dialog, the return value of this file dialog will be the **absolute path** of the selected file. Then, you can call this Go function in your frontend code to open the file dialog. This way, you can use Go code to process the selected file.

**Comment by devzwy** [comment]
> You can write a Go function that uses the [`OpenFileDialog`](https://wails.io/docs/reference/runtime/dialog#openfiledialog) method to open a native file dialog, the return value of this file dialog will be the **absolute path** of the selected file. Then, you can call this Go function in your frontend code to open the file dialog. This way, you can use Go code to process the selected file.

Thank you very much。
