### ISSUE TITLE
npm package "file-loader" ineffective

### ISSUE THREAD

**Issue by nageslan** [wailsapp/wails#2635]
### Description

file-load works fine in dev mode, but the package fails after build, causing inconsistency between dev mode and build

### To Reproduce

1. wails init -n myproject -t vue
2. npm install vue3-ace-editor 
3. npm install file-loader
4. create vue file
5. import "ace-builds/webpack-resolver";
6. import 'ace-builds/src-noconflict/mode-json';
7. import 'ace-builds/src-noconflict/theme-ambiance';
8. import 'ace-builds/src-noconflict/ext-language_tools';
9. wails dev run (normal)
10. wails build (error)

### Expected behaviour

fix bugs.

### Screenshots

Dev mode
![图片](https://user-images.githubusercontent.com/79894501/235353301-b48645e6-770b-43b1-af42-e4e5ec94abec.png)
Build
![图片](https://user-images.githubusercontent.com/79894501/235353348-1290a8a2-91df-44c5-be48-b43d77319d8a.png)

### Attempted Fixes

dev mode also does not work properly when removing the "file-load" npm package alone

### System Details

```shell
windows/amd64
```

**Comment by nas-cod** [comment]
my question

**Comment by czbczb** [comment]
how to resolve?
