### ISSUE TITLE
[Linux] NPM installed and working but "not found" in wails doctor

### ISSUE THREAD

**Issue by adxlv-co** [wailsapp/wails#2638]
### Description

On Fedora 38, I installed `npm` from its package manager (`sudo dnf install -y npm`), and ran a Wails project with `wails dev` without any issues. Yet, `wails doctor` will output saying NPM package is unknown and not found.

`npm -version` returns `9.6.5`, and `node --version` returns `v18.15.0`. I've restarted my session and ran some local node/npm scripts, everything seems to be working otherwise.

I was intrigued because [wails' `checkNPM`](https://github.com/wailsapp/wails/blob/b64b2a8da163a47c896851236999457ab13e13f6/v2/internal/system/system.go#L60-L80) seems pretty straightforward, checking the output of the `npm -version` command.

Happy to follow-up with any local tests! :bow: 

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Fedora Linux
Version      | 38          
ID           | fedora      
Go Version   | go1.19.7    
Platform     | linux       
Architecture | amd64       

# Wails

Version         | v2.4.1
Package Manager | dnf   

# Dependencies

Dependency | Package Name        | Status    | Version
*docker    | Unknown             | Not Found | 23.0.5 
gcc        | gcc-c++             | Installed | 13.1.1 
libgtk-3   | gtk3-devel          | Installed | 3.24.37
libwebkit  | webkit2gtk4.0-devel | Installed | 2.40.1 
npm        | Unknown             | Not Found | 9.6.5  
pkg-config | pkgconf-pkg-config  | Installed | 1.8.0  
*upx       | upx                 | Installed | 4.0.2  
* - Optional Dependency

# Diagnosis

Your system has missing dependencies!
Fatal:
Required dependencies missing: npm
Please read this article on how to resolve this: https://wails.io/guides/resolving-missing-packages
```

**Comment by leaanthony** [comment]
Thanks for reporting this. I'm assuming the build is working though? It might be that the package name it's looking for has changed in recent fedora releases. There was a very similar issue with zypper recently. Perhaps you could determine if the package names are correct for dnf and if not, update the search code as per this PR: https://github.com/wailsapp/wails/pull/2593/files

**Comment by leaanthony** [comment]
@adxlv-co - any updates?

**Comment by adxlv-co** [comment]
Hello @leaanthony! Sorry for the delay. I just checked, here's what I found:

In Fedora 38 the package is called `nodejs-npm`, not `npm`. You can see it in the [Fedora Packages](https://packages.fedoraproject.org/pkgs/nodejs18/nodejs-npm/) website.

<details>
<summary><code>dnf info installed nodejs-npm</code></summary>
<blockquote>

```
Installed Packages
Name         : nodejs-npm
Epoch        : 1
Version      : 9.5.1
Release      : 1.18.16.0.8.fc38
Architecture : x86_64
Size         : 8.3 M
Source       : nodejs18-18.16.0-8.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : Node.js Package Manager
URL          : http://nodejs.org/
License      : MIT and ASL 2.0 and ISC and BSD
Description  : npm is a package manager for node.js. You can use it to install and publish
             : your node programs. It manages dependencies and does other cool stuff.
```

</blockquote>
</details>

However, checking the same Fedora Packages website, it looks like until Fedora 37 the package was called `npm` in fact: https://packages.fedoraproject.org/pkgs/nodejs/npm/

I could open a PR updating **[packagemanager/dnf.go#L46](https://github.com/wailsapp/wails/blob/master/v2/internal/system/packagemanager/dnf.go#L46)** to `nodejs-npm`, but I'm not familiar if it would cause problems in other distros/versions :thinking:

Thank you!

**Comment by leaanthony** [comment]
You can have multiple entries for the package definitions so you can just add a new one for this package, which would not affect the existing systems. Here is an example: https://github.com/wailsapp/wails/pull/2593/files

**Comment by leaanthony** [comment]
@adxlv-co - any update on this? Did the comment above make sense?

**Comment by marifcelik** [comment]
im facing the same issue. as @adxlv-co said, in fedora npm package name is different, but in my case, i think the reason of problem is `nvm`. dnf doesn't see npm because i dont installed it from fedora repo so `wails doctor` gives error. 
Also same issue with `docker`. its called `docker-ce`

**Comment by leaanthony** [comment]
It's easy to add multiple package names to the doctor command so the second is easy. We could add a default action to perform for not found which uses `exec.LookPath` to find custom installations. Maybe we could just do this anyway and use the package lookup for not found packages... 🤔

**Comment by aranggitoar** [comment]
Hello @leaanthony, I've encountered the same issue on Fedora 38.

I guess adding the alternative `npm` package name would be just like this?

```go
"npm": []*Package{
    {Name: "npm", SystemPackage: true},
    {Name: "nodejs-npm", SystemPackage: true},
},
```

But how about the `docker` package, is it something like this?

```go
"docker": []*Package{
    {
        SystemPackage: false,
        Optional:      true,
        InstallCommand: map[string]string{
            "centos": "Follow the guide: https://docs.docker.com/engine/install/centos/",
            "fedora": "Follow the guide: https://docs.docker.com/engine/install/fedora/",
        },
    },
    {Name: "docker-ce", SystemPackage: true, Optional: true},
},
```

I'll create a PR if this make sense.

**Comment by aranggitoar** [comment]
> Maybe we could just do this anyway and use the package lookup for not found packages... :thinking:

By "package lookup", do you mean functionalities like `dnf provide [string]` to get the "actual" package names?
