### ISSUE TITLE
Proposal: Migrate `master` to `main`

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#2642]
This Issue was raised and tracks changes made to change Wails' default branch to `main`.
GitHub has a guide for [renaming](https://github.com/github/renaming), please refer to it.

- [ ] Rename `master` to `main`
  - Note that (among other things) this will automatically:
    - Re-target any open pull requests.
    - Move any branch protection rules that explicitly reference the old name.
    - Redirect web requests for the old branch name to the new branch name.
  - [See docs](https://github.com/github/renaming#renaming-existing-branches) for instructions and more info.
- [ ] Check and merge the PR corresponding to this Issue.(If the proposal is approved)

**Comment by leaanthony** [comment]
I'm ok with this. Just need to set a date and make it known. How about June 1?

**Comment by misitebao** [comment]
I have no problem, but need to wait for [this](https://github.com/wailsapp/wails/pull/2641) to be completed before submitting a new PR
