### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by waffle-lord** [wailsapp/wails#2649]
### Description

wails install fails to find files

### To Reproduce

1. Install Go
2. Install npm
3. Install webview2
4. Try to install wails

### Expected behaviour

The install completes without issue

### Screenshots

![image](https://user-images.githubusercontent.com/76401815/236242826-3c3743c3-b6a0-482b-a04f-aba44908f438.png)

### Attempted Fixes

- Tried reinstalling Go after clearing out all residual files.
- Tried reinstalling webview2 and npm
- Tried checking system integrity with no issues found (sfc, chkdsk, dism)

I'm not really sure what is causing this, I've not had this happen on any other computer, so I may just reinstall windows :(

### System Details

```shell
Windows 11 Pro
Version	22H2
OS build	22621.1555

Go 1.20.4
NPM 9.6.6
Node 18.16.0 (don't know if this matters, but I'm at a loss here)
```

**Comment by leaanthony** [comment]
Try dropping the @latest

**Comment by waffle-lord** [comment]
It only lets me install inside a module without `@lastest`. So I just made a test module `go mod init test`

I then got an error saying go.sum needed to have the repo added
```
PS C:\Users\----\Desktop\test> go install github.com/wailsapp/wails/v2/cmd/wails
no required module provides package github.com/wailsapp/wails/v2/cmd/wails; to add it:
        go get github.com/wailsapp/wails/v2/cmd/wails
```

after adding it, the same errors persist
```
PS C:\Users\----\Desktop\test> go install github.com/wailsapp/wails/v2/cmd/wails
..\..\go\pkg\mod\github.com\wailsapp\wails\v2@v2.4.1\internal\frontend\runtime\wrapper\wrapper.go:5:12: pattern runtime.js: no matching files found
..\..\go\pkg\mod\github.com\wailsapp\wails\v2@v2.4.1\internal\webview2runtime\webview2installer.go:9:12: pattern MicrosoftEdgeWebview2Setup.exe: no matching files found
```

**Comment by waffle-lord** [comment]
I don't know how this happened (even after clearing out go and it's directory completely) but I was able to install with the `@latest` tag after changing `..\go\pkg\mod\github.com\wailsapp` to `..\go\pkg\mod\github.com\wailsapp_old` and re-installing.

It's like the repo wasn't fully downloaded or something.  My guess is I'm just unlucky and something was going wrong while getting the repo files. So I guess just removing them and retrying a couple times is the fix... very odd
![image](https://user-images.githubusercontent.com/76401815/236319050-c36e96f5-ecb5-4543-a405-683ed16915de.png)

**Comment by leaanthony** [comment]
Glad it worked out for you 👍
