### ISSUE TITLE
Retain Go function signature in JS bindings

### ISSUE THREAD

**Issue by MisterLobo** [wailsapp/wails#2651]
### Is your feature request related to a problem? Please describe.

Retain the function signature from Go to the JS bindings
For example, I have this exposed function:
```go
func Greet(name string, email string)
```
then in the generated JS binding it should be:
```ts
function Greet(name:string, email:string)
```
but currently the generated is like this:
```ts
function Greet(arg1:string,arg2:string)
```
having `arg`s as the name of arguments is a bit confusing or is there a configuration that I could have missed? Thanks. Appreciate any help

### Describe the solution you'd like

Retain the names of arguments from the Go code to the JS bindings

```go
func Greet(name string, email string)
```
The function signature above would be generated like so:
```ts
function Greet(name:string, email:string)
```

**Comment by leaanthony** [comment]
That can't happen in v2 due because it gets generated via reflection and that doesn't retain variable names. V3 uses static analysis so it does do this already.
