### ISSUE TITLE
Build failed in linux/arm64

### ISSUE THREAD

**Issue by 20yyq** [wailsapp/wails#2652]
### Description

build failed

### To Reproduce

wails build
Wails CLI v2.4.1

App Type: desktop
Platforms: linux/arm64

### Expected behaviour

build failed

### System Details

```shell
Wails CLI v2.4.1


# Build Options

Platform(s)        | linux/arm64
Compiler           | /usr/local/go/bin/go
Skip Bindings      | false
Build Mode         | production
Frontend Directory | /mnt/veryark/wails/first/frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | false
LDFlags            |
Tags               | []
Race Detector      | false

# Building target: linux/arm64

  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/desktop/linux
/home/lqm/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.1/internal/frontend/desktop/linux/gtk.go:26:2: could not determine kind of name for C.free
  ERROR   exit status 1

  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
```

**Comment by 20yyq** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

**Comment by leaanthony** [comment]
Please update to latest version of Wails and update your project's go.mod.

**Comment by Nexus26404** [comment]
is this issue fixed? It seems that I got the same problem. 

`Wails CLI v2.6.0

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.

> frontend@0.0.0 dev /home/hzhou/workspace/demo/frontend
> vite


  VITE v3.2.7  ready in 273 ms

Vite Server URL: http://localhost:5173/
  ➜  Local:   http://localhost:5173/
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  ➜  Network: use --host to expose
  • Generating bindings: Done.
  • Compiling application: # github.com/wailsapp/wails/v2/pkg/assetserver/webview
/usr/local/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/assetserver/webview/responsewriter_linux.go:112:2: could not determine kind of name for C.free

Build error - exit status 1`

My Ubuntu system version is "16.04.7 LTS".

**Comment by leaanthony** [comment]
16.04 is far too old for us to support but we should make that clearer in the docs. There were a number of arm64 related PRs since this ticket was opened. Could you please try again and if it's still an issue, feel free to reopen this issue 👍
