### ISSUE TITLE
wails app connet websocket is a bug?

### ISSUE THREAD

**Issue by NiStyle** [wailsapp/wails#2658]
### Description

I tried to debug a wails application with vscode,and connetting websock from frontend,connection failed with `The server did not accept the WebSocket handshake`.but  websocket connection work fined on command `wails build`  `wails build -debug`  `wails dev`.
![buginfo1](https://github.com/wailsapp/wails/assets/121022414/2300f463-fc4a-461f-bab1-40a304d14ea4)

### To Reproduce

1.open a websocket server
2.start debug wails applicatin with vscode
3.open wails application developer tools
4.run `new WebSocket("websocket server address")` in developer tools console

### Expected behaviour

websocket connections success

### Screenshots

this is the information of websocket connectting.
![buginfo2](https://github.com/wailsapp/wails/assets/121022414/3aa5b934-a02f-48eb-9911-fac66f210584)

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Arch Linux
Version      | Unknown   
ID           | arch      
Go Version   | go1.20.2  
Platform     | linux     
Architecture | amd64     

# Wails

Version         | v2.4.1
Package Manager | pacman

# Dependencies

Dependency | Package Name | Status    | Version    
*docker    | docker       | Available | 1:23.0.6-1 
gcc        | gcc          | Installed | 13.1.1-1   
libgtk-3   | gtk3         | Installed | 1:3.24.37-1
libwebkit  | webkit2gtk   | Installed | 2.40.1-2   
npm        | npm          | Installed | 8.19.2-2   
pkg-config | pkgconf      | Installed | 1.8.1-1    
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo pacman -S docker

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Thanks for opening this. We are investigating 👍

**Comment by leaanthony** [comment]
@CeilAI - please try the latest release 🙏

**Comment by CeilAI** [comment]
thanks@leaanthony,it's a bug of vscode maybe,updated to latest release and still failed `The server did not accept the WebSocket handshake` with vscode .it work with vscodium,i tried to vscodium instead.
