### ISSUE TITLE
Tried to install v2 from the tutorial from the docs, but installed v1.16.9

### ISSUE THREAD

**Issue by Sigfied** [wailsapp/wails#2659]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I followed the installation process in the official documentation
`go install github.com/wailsapp/wails/v2/cmd/wails@latest`
but installed v1.16.9
![image](https://github.com/wailsapp/wails/assets/82499314/1cea5a59-0602-43b9-a0b3-0482c1457de4)

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Sounds like your local paths are messed up and you have 2 versions installed.
