### ISSUE TITLE
wails build plugin

### ISSUE THREAD

**Issue by zundaren** [wailsapp/wails#2663]
### Is your feature request related to a problem? Please describe.

for example: after the build, execute tar.gz, upload to server

insert custom actions during lifecycle execution

### Describe the solution you'd like

for example: after the build, execute tar.gz, upload to server

**Comment by JoiLa** [comment]
you can see [link](https://lilogs.com/archives/2273.html)

**Comment by leaanthony** [comment]
This can be done in your own scripts. We are unlikely to add this kind of functionality.
