### ISSUE TITLE
Is it possible to get the full path of a file by dragging uploading it?

### ISSUE THREAD

**Issue by Forgetstarzero** [wailsapp/wails#2665]
Is it possible to get the full path of a file by dragging uploading it?

**Comment by leaanthony** [comment]
If you are talking about native drag and drop, not in v2. But it will be supported in v3 👍

**Comment by Forgetstarzero** [comment]
Thanks, I would like to ask when the v3 plan will be released?

**Comment by rangwea** [comment]
I'm also waiting for the Native Drap feature. In the v2 version, I can only use this way to implement it: [onImagePasted](https://github.com/rangwea/swallow-wails/blob/main/frontend/src/components/ArticleEditor.jsx)
to upload image byte, and backend method [ArticleInsertImageBlob](https://github.com/rangwea/swallow-wails/blob/main/backend/app.go) to save image and return path.
