### ISSUE TITLE
High cpu for Lottie file animations on webview2

### ISSUE THREAD

**Issue by saul-data** [wailsapp/wails#2666]
### Description

This is a screenshot of a compiled Wails app with a Lottie file animation using webview2. We are seeing the same high cpu for both Windows and Mac. We have two different animations on two different routes in the app, the same high CPU usage.

I have tried these two NPM packages:
https://www.npmjs.com/package/lottie-react
https://www.npmjs.com/package/@lottiefiles/react-lottie-player
 
<img width="2049" alt="image" src="https://github.com/wailsapp/wails/assets/63714857/d6127651-4528-463c-b4a1-cfee59ad57ca">

### To Reproduce

Compile below into a Lottie app for Mac or Windows

```shell
npm install --save @lottiefiles/react-lottie-player
```

```
import { Player, Controls } from '@lottiefiles/react-lottie-player';
<Player
  autoplay
  loop
  src="https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json"
  style={{ height: '300px', width: '300px' }}
>
  <Controls visible={true} buttons={['play', 'repeat', 'frame', 'debug']} />
</Player>
```

### Expected behaviour

Low CPU usage

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.3.1  
ID           | 22E261  
Go Version   | go1.19.4
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.4.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397   
npm                       | N/A          | Installed | 7.24.0 
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by leaanthony** [comment]
Thanks for opening the ticket. It's not clear from what you've written whether the slowness is due to the libraries or Webview2. Did you try in a browser and compare?

**Comment by saul-data** [comment]
I think you're right, this is more to do with the Lottie file web player than webview. https://github.com/airbnb/lottie-web/issues/2427 I'll keep following this on the Lottie web issues.
