### ISSUE TITLE
What happend with the grey scroll bar?

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#2680]
### Discussed in https://github.com/wailsapp/wails/discussions/2678

<div type='discussions-op-text'>

<sup>Originally posted by **StormYudi** May 20, 2023</sup>
Hi community, 
I developed a wails app recently, I sent this app to windows users, and they can see a grey scroll bar on the right of the window, but in mac, everything is fine, how can I debug this? idk what is that? 
I open dev tool, it shows me that the scroll bar is not belongs to the webview.

**Windows:**
<img width="1223" alt="image" src="https://github.com/wailsapp/wails/assets/19419186/dd1168f4-ccb0-4c4d-a4ab-b8c497452f50">

**Mac:**
<img width="1054" alt="image" src="https://github.com/wailsapp/wails/assets/19419186/ac4a9136-60d7-4e87-8031-8a8f5eaeffbb">
</div>

**Comment by leaanthony** [comment]
I've seen this myself recently. Does the scrollbar disappear if you resize it by 1 pixel?

**Comment by StormYudi** [comment]
it won't disappear :( here is my config, in this config, I add height from 768 to 769, that is the same :(
```
	err := wails.Run(&options.App{
		Title:  "乔尔的加速器 " + versionNow,
		Width:  1024,
		Height: 769,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		Frameless:  true,
		OnStartup:  app.startup,
		OnShutdown: app.shutdown,
		Bind: []interface{}{
			app,
		},
		BackgroundColour: &options.RGBA{
			R: 255,
			G: 255,
			B: 255,
			A: 255,
		}, Mac: &mac.Options{
			About: &mac.AboutInfo{
				Title:   "乔尔的加速器",
				Message: "© 2023 乔尔 & 雨云",
				Icon:    icon,
			},
		},
	})
```

**Comment by leaanthony** [comment]
If possible, please use `git bisect` to find the commit that changed this. Thank you 👍

**Comment by leaanthony** [comment]
Closing due to lack of feedback
