### ISSUE TITLE
we need to be able to call print() function, window.print()

### ISSUE THREAD

**Issue by webdesktopdev** [wailsapp/wails#2684]
### Description

is there anyway to call window.print() in wails?

### To Reproduce

-
-
-

### Expected behaviour

we expect to get print dialog when we call window.print(), for both macOS and Window.

### Screenshots

-

### Attempted Fixes

-

### System Details

```shell
-
```

### Additional context

-

**Comment by misitebao** [comment]
Sorry, I don't understand what you mean. 
Please open the correct Issue and describe your problem in detail.

**Comment by leaanthony** [comment]
I don't believe there's a way to do this currently. Will look to add it to v3.
