### ISSUE TITLE
Open all links using an external browser 

### ISSUE THREAD

**Issue by codesalley** [wailsapp/wails#2691]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

a well-documented step to prevent the app from opening URL's like a browser but instead, use an external browser. 
I have a pdf previewer where int might include 

```html
<a href="external url "> click </a>
``` 
and this opens the webpage in the app turning it into a browser. 
i came up with this javascript snippet
```jsx
  function addBlankTargetToLinks() {
    document.querySelectorAll('a').forEach(link => {
      const url = link.href
      link.addEventListener('click', (e) => {
        if(!url.startsWith('http://#') && !url.startsWith('file://')){
          OpenURL(link.href)
        }
      })
    });
  }


  useEffect(() => {
    addBlankTargetToLinks()
  }, [])
```

which is not a wise solution. 

any wails go specific instruction to fix this?

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by mmghv** [comment]
I think a better way is to do it like this :

```js
// Open all links externally
document.body.addEventListener("click", function(e) {
  if (e.target && e.target.nodeName == "A" && e.target.href) {
    e.preventDefault();
    window.runtime.BrowserOpenURL(e.target.href);
  }
});
```

But I think there should be a settings for this in wails which is true by default, desktop apps shouldn't browse links internally by default.

**Comment by leaanthony** [comment]
Did  `onclick="OpenURL(external_url)"` not work?

**Comment by mmghv** [comment]
It sure works, but it registers an event listener for each individual `a` tag, so for frontend frameworks you need to keep track for every dynamically created tag, I guess `useEffect` would work for that specific framework but it wouldn't work for others, so a better way is to register only one event listener on the `body` and make use of [event delegation](https://javascript.info/event-delegation).

Is it something that can be implemented on Wails side? I think every desktop app needs this behavior by default for links, if a link is clicked and then you see the app navigate to the website, it breaks the "immersion" , and potentially could cause unsaved data to be lost.

**Comment by leaanthony** [comment]
How do you see that working in an ideal world?

**Comment by mmghv** [comment]
In an ideal world I see Wails by default preventing navigation to external websites and opening them in an external browser, this is what you would find in any desktop application, you wouldn't expect the app to navigate to the website when you click a link.

There could be a setting that is true by default and if a developer want to use his app as a browser would turn it off, but I believe if the asked most of the developers (or the end users) they wouldn't want their app to act like a browser when a link is clicked, it's a cool feature but shouldn't be turned on by default.

**Comment by leaanthony** [comment]
We can consider this for v3. We can't change the default behaviour in v2 and there are 2 options to achieve this in this thread so for now I think we're good.

**Comment by codesalley** [comment]
I would like to be part of the `V3` development process, is there a discord or slack channel for core contributors and people that wants to contribute to wails ?
