### ISSUE TITLE
Problem with setting parameters for ldflags

### ISSUE THREAD

**Issue by Forgetstarzero** [wailsapp/wails#2704]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

wails build -ldflags="-X config.Env=test -X config.Version=v1.1.1" 
Golang backend cannot read parameters
use os.Getenv("Env") cannot read parameters

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Please include the output of `wails doctor`

**Comment by Forgetstarzero** [comment]
My package path was written wrong, which made it impossible to set the ldflags parameter. It has been resolved now, thank you.
However, the parameters set by ldflags cannot be read using os.Getenv("Env").

**Comment by leaanthony** [comment]
Correct, they are linker flags not environment variables

**Comment by stffabi** [comment]
I think we can close this issue, since this is how the ldflags work in go and there's no issue with Wails.
