### ISSUE TITLE
[linux, dev] CSS included with "link"-tag do not work

### ISSUE THREAD

**Issue by esotericman** [wailsapp/wails#2705]
### Description

follow guide
```shell
wails init -n wails-dev -t vue
```
and then run
```shell
wails dev
```
but application shows below
![Screenshot from 2023-06-06 16-48-30](https://github.com/wailsapp/wails/assets/47545727/bfc7bcee-0688-4087-88a0-c8b371b83a22)
as you see,the text not align center,but in  browser ,It's ok
![Screenshot from 2023-06-06 16-51-52](https://github.com/wailsapp/wails/assets/47545727/d5790722-f549-49d4-9304-61d7e0712d33)
and terminal print
![Screenshot from 2023-06-06 16-49-00](https://github.com/wailsapp/wails/assets/47545727/dcd4736e-a28b-4ab3-b994-c0e050eacbb5)
while I use 
```shell
wails build
```
and then use the binary file ,It's fine,Just dev mode It not work.
What's the matter? My OS is Ubuntu 22.04.2 LTS

### To Reproduce

```shell
wails init -n wails-dev -t vue
```
```shell
wails dev
```

### Expected behaviour

display same as browser

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                                                                                                    

# System

OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version   | go1.18.3
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.5.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 24.0.2                 
gcc        | build-essential       | Installed | 12.9ubuntu3            
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2       
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.22.04.1
npm        | npm                   | Installed | 8.19.4                 
*nsis      | nsis                  | Installed | v3.08-2                
pkg-config | pkg-config            | Installed | 0.29.2                 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
This is currently a known issue on Linux since we have consolidated the DevServer to use `wails://` starting with `2.5.0`. If you include the css with an import in `main.js` it will work or you can bump your WebKit2 dependency with the `webkit2_36` build tag with `wails dev -tags webkit2_36`

```js
import './style.css';
```

I think we are going to update all the templates to use an import.

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by esotericman** [comment]
Yes,In My another computer with version  v2.4.1,It's fine,I'll try it in my spare time.Thanks for reply

**Comment by esotericman** [comment]
> Yes,In My another computer with version v2.4.1,It's fine,I'll try it in my spare time.Thanks for reply

It works now,but terminal still print file not found.maybe mistake?
