### ISSUE TITLE
Does wails support wasm

### ISSUE THREAD

**Issue by kcmvp** [wailsapp/wails#2706]
### Is your feature request related to a problem? Please describe.

May be it’s a very simple question, but I can’t find a sample app.

I am using wails build in-house tool, and I want to include a third party library which is a wasm. I want to know does wails support wasm and how to use it? 

### Describe the solution you'd like

Call wasm from wails

**Comment by leaanthony** [comment]
There is a Go library called Wazero that will interest you. You could bind a method and pass through the call to wazero, meaning you could call it from the frontend. I'm looking to build this into v3 as a plugin option
