### ISSUE TITLE
[Error] TypeError: undefined is not an object (evaluating 'window['go']['main']')

### ISSUE THREAD

**Issue by Forgetstarzero** [wailsapp/wails#2710]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Using window.location.reload() in react, the 'window['go'] object cannot be obtained after the page is refreshed, and the wails do not seem to be loaded.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mooijtech** [comment]
The Wails runtime is only injected to "/", references: https://github.com/wailsapp/wails/issues/2262

**Comment by leaanthony** [comment]
Duplicate: https://github.com/wailsapp/wails/issues/2262
