### ISSUE TITLE
Retrieve info.productVersion and other wails.json info

### ISSUE THREAD

**Issue by mmghv** [wailsapp/wails#2712]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to retrieve info from `wails.json` in runtime, I want to show the application version in the frontend and also could be used to check for new updates and such.

Currently I have to keep track of a separate `version` variable and I could forget to update it after bumping the version in `wails.json`, there should be only one place for that info, desktop apps have access to their version info in the runtime.

### Describe the solution you'd like

maybe something like :

```js
runtime.getAppInfo() // {companyName: "", productVersion: "1.0.0", ...}
```

**Comment by leaanthony** [comment]
Did you try `go:embed`?

**Comment by mmghv** [comment]
I'm sorry I've just started learning Go with Wails., I'm mainly a web developer the loves the idea of easily building desktop apps with the powerful UI capabilities of web technologies.

I researched `go:embed`, it seems like it's used to embed and read embedded files in Go, but I can't find anything in Wails documentation on how it embeds the config file or how to retrieve it.

Is it possible to include a function in the runtime to easily retrieve this info? if not, is it something that can be added to the documentation?

**Comment by leaanthony** [comment]
When you use `//go:embed` it embeds the file in the app. You can access the data by declaring a variable right after the comment. In your case, you embed the `wails.json` file, declare a variable like `var wailsJSON []byte` and in your application startup you can use the `json` package to parse it. Now it's a go struct that you can access in any of your bound methods. The alternative to that is using something like gjson:

```
package main

import "github.com/tidwall/gjson"

//go:embed wails.json
var wailsJSON string

func main() {
	version:= gjson.Get(wailsJSON , "info.ProductVersion")
	println(version.String())
}
```
Embed tutorial: https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/

Good luck 👍

**Comment by mmghv** [comment]
Got it, thanks for the info.

I really think that at least the application version is something that should be easily available at runtime though, but thanks anyway.

**Comment by leaanthony** [comment]
We have a solution for this so closing for now 👍

**Comment by dy0gu** [comment]
> We have a solution for this so closing for now 👍

Hi, sorry I'm reviving this, but is the solution the other comment you wrote above? Or is it something that was added to the documentation?

**Comment by leaanthony** [comment]
The main use case stated was retrieving the application version. The suggested work around is to embed the wails.json file into the app for retrieval at runtime of embed a subset of that file with just what you want. Embedding the project config by default is not something we'd do.
