### ISSUE TITLE
About losing focus and automatically hiding a window

### ISSUE THREAD

**Issue by duolabmeng6** [wailsapp/wails#2713]
### Is your feature request related to a problem? Please describe.

Hello, I want to write a message box type window, and the window will be automatically hidden after the mouse clicks off the screen.
I have searched the documents for a long time and have not found any relevant examples. Please consult me sincerely.
I want to implement the effect of losing focus window auto hide

### Describe the solution you'd like

Whether a property can be provided  popFrame

**Comment by leaanthony** [comment]
What platform is this for?

**Comment by leaanthony** [comment]
I think hooking into a window blur event may be best here. I'll see if we support that and if not, I'll add it.

**Comment by yllhwa** [comment]
> I think hooking into a window blur event may be best here. I'll see if we support that and if not, I'll add it.

I meet the same problem and tried using window.onblur. 
```js
window.onblur = () => {
  window.runtime.WindowHide()
}
```
But it seems that when the program first starts, webview will not automatically get focus. 
I have to first click on the webpage, and then click other position outside to trigger it. (under Windows)

**Comment by iamkhalidbashir** [comment]
@duolabmeng6 how did you manage to listen for window blur and focus event?

**Comment by duolabmeng6** [comment]
> @duolabmeng6 how did you manage to listen for window blur and focus event?

https://github.com/duolabmeng6/go-qoq
你这里自己看代码吧
