### ISSUE TITLE
v3 In app.Events.On stuck when adjusting height

### ISSUE THREAD

**Issue by duolabmeng6** [wailsapp/wails#2726]
### Description

In `app.Events.On`, adjusting the window height back causes the interface to be stuck. I am using v3 version.

### To Reproduce

```
package main

import (
	"embed"
	_ "embed"
	"log"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/events"
)

//go:embed assets
var assets embed.FS

func main() {

	app := application.New(application.Options{
		Name:        "Events Demo",
		Description: "A demo of the Events API",
		Mac: application.MacOptions{
			ApplicationShouldTerminateAfterLastWindowClosed: true,
		},
		Assets: application.AssetOptions{
			FS: assets,
		},
	})

	// OS specific application events
	app.On(events.Mac.ApplicationDidFinishLaunching, func() {
		for {
			log.Println("Sending event")
			app.Events.Emit(&application.WailsEvent{
				Name: "myevent",
				Data: "hello",
			})
			time.Sleep(10 * time.Second)
		}
	})

	// Platform agnostic events
	app.On(events.Common.ApplicationStarted, func() {
		println("events.Common.ApplicationStarted fired!")
	})

	window := app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
		Title: "Events Demo",
		Mac: application.MacWindow{
			Backdrop:                application.MacBackdropTranslucent,
			TitleBar:                application.MacTitleBarHiddenInsetUnified,
			InvisibleTitleBarHeight: 50,
		},
	})
	println("window: ", window)
	// Custom event handling
	app.Events.On("myevent", func(e *application.WailsEvent) {
		log.Printf("[Go] WailsEvent received: %+v\n", e)
		window.SetSize(800, 600)
	})
	
	err := app.Run()

	if err != nil {
		log.Fatal(err.Error())
	}
}

```
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>body{ text-align: center; color: white; background-color: rgba(0,0,0,0); user-select: none; -ms-user-select: none; -webkit-user-select: none; }</style>
</head>
<body>
<h1>Events Demo</h1>
<br/>
The main program emits an event every 10s which will be displayed in the section below.
To send an event from this window, click here: <button onclick="wails.Events.Emit({name:'myevent', data:'hello!'})">Send Event</button>
<div id="results"></div>
</body>

<script>
    wails.Events.On("myevent", function(data) {
        let currentHTML = document.getElementById("results").innerHTML;
        document.getElementById("results").innerHTML = currentHTML + "<br/>" + JSON.stringify(data);
    })
</script>

</html>
```
# bug code

```
	app.Events.On("myevent", func(e *application.WailsEvent) {
		log.Printf("[Go] WailsEvent received: %+v\n", e)
		window.SetSize(800, 600)
	})
```

### Expected behaviour

Smooth height adjustment

### System Details

```shell
➜ wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                               

# System

OS           | MacOS   
Version      | 13.4    
ID           | 22F66   
Go Version   | go1.20.3
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version         
Xcode command line tools  | N/A          | Installed | 2397            
Nodejs                    | N/A          | Installed | 16.15.1         
npm                       | N/A          | Installed | 8.11.0          
*Xcode                    | N/A          | Installed | 14.3.1 (14E300c)
*upx                      | N/A          | Available |                 
*nsis                     | N/A          | Available |
```

**Comment by mostend** [comment]
I think there have a lock issue. 
`invokeSyncWithResult(w.impl.isFullscreen)`
Stuck at this position.

![282e43edc52117d96c4f5ada0f3e7642](https://github.com/wailsapp/wails/assets/11625729/6a59dd08-f769-4b3b-9382-cb9e4c2ed2b3)

**Comment by stffabi** [comment]
Thanks for reporting this. V3 is in development stage and it's not near a production level. Things will break, API's might change. 

The problem you are mentioning will be fixed with a greater refactoring of the internal main-thread switching. This refactoring is pending and should land in the near future.

**Comment by stffabi** [comment]
> I solved it using the following method
> 
> `/wails/v3/pkg/application/application.go`
> 
> ```
> 
> func invokeSync(fn func()) {
> 	fn()
> }
> 
> func invokeSyncWithResult[T any](fn func() T) (res T) {
> 	res = fn()
> 	return res
> }
> 
> func invokeSyncWithResultAndError[T any](fn func() (T, error)) (res T, err error) {
> 	res, err = fn()
> 	return res, err
> }
> ```

Just as a side note, with that code change you basically have no guarantee anymore that things are getting called on the main-thread. You might run into very strange error and panics.

**Comment by duolabmeng6** [comment]
> Just as a side note, with that code change you basically have no guarantee anymore that things are getting called on the main-thread. You might run into very strange error and panics.

https://github.com/duolabmeng6/go-qoq I have used v3 to open source the 1 translation software and have not encountered the problems you mentioned. I am looking forward to your new version with smooth operation.

**Comment by leaanthony** [comment]
Good grief is that a v3 app in the wild? You're brave! 😆 As @stffabi commented, you may find that removing that code will make your app go crazy. We're looking at getting that working and look forward to you testing. Nice job on the app 👍

**Comment by duolabmeng6** [comment]
Thank you very much. I have used the latest version. No problem found for the time being
