### ISSUE TITLE
Hello, questions about v3 version window.Position() coordinates returned incorrectly

### ISSUE THREAD

**Issue by duolabmeng6** [wailsapp/wails#2727]
### Description

v3
```
x, y := window.Position()
```
From the bottom left corner of the screen, 0,0 is not logical, usually from the top left corner of the screen is 0,0.

V2 coordinates are starting from the top left corner 0,0 which is correct
```
			x, y := runtime.WindowGetPosition(a.ctx)
			w, h := runtime.WindowGetSize(a.ctx)
```

### To Reproduce

null

### Expected behaviour

null

### System Details

```shell
macos
```

**Comment by duolabmeng6** [comment]
I solved it with the following code

```

func GetWindowPosition(app *application.WebviewWindow) (int, int) {
	screen, err := app.GetScreen()
	if err != nil {
		return 0, 0
	}
	//wwidth := app.Width()
	wheight := app.Height()
	//swidth := screen.Size.Width
	sheight := screen.Size.Height
	x, y := app.Position()
	newX := x
	newY := sheight - wheight - y - 1
	return newX, newY
}
func SetWindowPosition(app *application.WebviewWindow, x int, y int) {

	screen, err := app.GetScreen()
	if err != nil {
		return
	}
	//wwidth := app.Width()
	wheight := app.Height()
	//swidth := screen.Size.Width
	sheight := screen.Size.Height
	newX := x
	newY := sheight - wheight - y - 1
	app.SetPosition(newX, newY)
}
```

**Comment by leaanthony** [comment]
Mac uses those coordinates natively (no kidding!). I think it should be consistent though...

**Comment by leaanthony** [comment]
I pushed a potential fix for this on the alpha branch. Also a fix for the main thread issue. Please let us know how you get on 👍

**Comment by leaanthony** [comment]
@duolabmeng6 - if you want to be involved in v3 development and are willing to test, please join us on the discord server and I can add you to a dedicated v3 testing channel 👍 https://discord.gg/5qyJQEQN

**Comment by duolabmeng6** [comment]
> @duolabmeng6 - if you want to be involved in v3 development and are willing to test, please join us on the discord server and I can add you to a dedicated v3 testing channel 👍 https://discord.gg/5qyJQEQN

Thank you very much for your concern. My development is continuing. I am willing to test the latest version.

https://github.com/duolabmeng6/go-qoq 

I have built in wails. Now you can also test the software. The completion degree is very high. Of course, there are still many details. For example, the window cannot be closed. I have not found the closed event either.

**Comment by duolabmeng6** [comment]
I see your WindowShouldClose is not yet completed. So I have no way to do the callback that closes the window
```		
w.parent.On(events.Mac.WindowShouldClose, func(_ *WindowEventContext) {
			// TODO: Process "should close" callback for user
			w.close()
		})
```

**Comment by duolabmeng6** [comment]
window.Show().Focus() Sometimes it is not displayed correctly at the front.  Need window.SetAlwaysOnTop(true) to be displayed on the front

**Comment by leaanthony** [comment]
> Encountered a problem... how to close the window only hide not destroy the window

Did you try setting `HideOnClose` in the Window options?

**Comment by leaanthony** [comment]
@duolabmeng6 - I have changed this a little and removed `HideOnClose` to provide better flexibility for developers. Please see [this section](https://github.com/wailsapp/wails/blob/v3-alpha/v3/examples/window/main.go#L62-L79) of the Window example for an example of what you want to do 👍

**Comment by duolabmeng6** [comment]
我在最 v3-alpha `68573cdc48344d7548c18a45e640e583356ddecc`上出现了问题 我也不知道如何解决..
```
GOROOT=/Users/chensuilong/go/go1.20.3 #gosetup
GOPATH=/Users/chensuilong/go #gosetup
/Users/chensuilong/go/go1.20.3/bin/go build -o /Users/chensuilong/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_v3fanyi v3fanyi #gosetup
# github.com/go-vgo/robotgo
In file included from ../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/robotgo.go:48:
In file included from ../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/window/goWindow.h:12:
../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/window/window.h:21:6: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/window/window.h:29:6: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
# github.com/wailsapp/wails/v3/pkg/application
wails-v3/v3/pkg/application/webview_window.go:216:11: cannot use newWindowImpl(w) (value of type *macosWebviewWindow) as webviewWindowImpl value in assignment: *macosWebviewWindow does not implement webviewWindowImpl (missing method print)
wails-v3/v3/pkg/application/dialogs_darwin.go:403:14: impossible type assertion: m.dialog.window.impl.(*macosWebviewWindow)
	*macosWebviewWindow does not implement webviewWindowImpl (missing method print)
wails-v3/v3/pkg/application/dialogs_darwin.go:487:14: impossible type assertion: m.dialog.window.impl.(*macosWebviewWindow)
	*macosWebviewWindow does not implement webviewWindowImpl (missing method print)


```

**Comment by leaanthony** [comment]
V3 is unstable. Please report anything like this to discord. For now, checkout a previous commit 👍 this will happen from time to time...

**Comment by duolabmeng6** [comment]
> V3 is unstable. Please report anything like this to discord. For now, checkout a previous commit 👍 this will happen from time to time...

It's okay, looking forward to getting better.
