### ISSUE TITLE
Add `WindowFocus` api

### ISSUE THREAD

**Issue by fzdwx** [wailsapp/wails#2731]
### Is your feature request related to a problem? Please describe.

I have a project at https://github.com/fzdwx/launcher.

I will first call `window hide` and then call `window show` when needed. I hope that after calling `window show`, the input box of this program can be focused.

### Describe the solution you'd like

Provide an api  `window focus`

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- Please include the output of `wails doctor`

**Comment by fzdwx** [comment]
Not a a bug , is a feat request , i think .

**Comment by fzdwx** [comment]
Like this
![image](https://github.com/wailsapp/wails/assets/65269574/34109fe1-f474-4d9c-98dc-d76265eaac14)

**Comment by leaanthony** [comment]
> * Please include the output of `wails doctor`

**Comment by fzdwx** [comment]
> > * Please include the output of `wails doctor`
> 
> The reason I'm asking is because this was working fine for Windows.

```txt
$ wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Arch Linux
Version      | Unknown
ID           | arch
Go Version   | go1.20.5
Platform     | linux
Architecture | amd64

# Wails

Version         | v2.5.1
Package Manager | pacman

# Dependencies

Dependency | Package Name | Status    | Version
*docker    | docker       | Installed | 1:24.0.2-1
gcc        | gcc          | Installed | 13.1.1-1
libgtk-3   | gtk3         | Installed | 1:3.24.38-1
libwebkit  | webkit2gtk   | Installed | 2.40.2-1
npm        | npm          | Installed | 8.19.2-2
pkg-config | pkgconf      | Installed | 1.8.1-1
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
`Show()` should work as focus. Does it not?
