### ISSUE TITLE
Can't run wails commands on windows

### ISSUE THREAD

**Issue by FriendlyUser** [wailsapp/wails#274]
**Description**

When running wails commands I end up getting 'C:\Program' is not recognized as internal or external command. I think it's looking for C:\Program Files.

Of course, I'm using windows 10.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Expected to be able to run wails.

**Screenshots**
![image](https://user-images.githubusercontent.com/13860264/67545494-24950880-f6ae-11e9-8e02-6b3a0f9481a9.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.5 |
| Go Version    | go1.13 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | v10.14.1
 |
| Node          | 6.4.1 |

**Additional context**

**Comment by leaanthony** [comment]
Hi. Are you using tdm-gcc?

**Comment by leaanthony** [comment]
What's really odd about this, is that the NPM command path has spaces too, but that runs fine:

```
PS C:\Users\leaan\projects\shutdown> wails build
Wails v0.18.10-pre - Building Application

> Skipped frontend dependencies (-f to force rebuild)
Executing program: C:\Program Files\nodejs\npm.cmd
args: [npm run build]
dir = '[]'
> Building frontend...
Executing program: C:\Go\bin\go.exe
args: [go get]
dir = '[]'
> Ensuring Dependencies are up to date...
Executing program: C:\TDM GCC-64\bin\windres.exe
args: [windres -o C:\Users\leaan\projects\shutdown\shutdown-res.syso C:\Users\leaan\projects\shutdown\shutdown.rc]
dir = '[]'
'C:\TDM' is not recognized as an internal or external command,
operable program or batch file.
C:\TDM GCC-64\bin\windres.exe: preprocessing failed.
```

**Comment by leaanthony** [comment]
Turns out it's a [Go Bug](https://github.com/golang/go/issues/17149)! Looking to do a workaround..

**Comment by leaanthony** [comment]
This should now be fixed in v0.18.11-pre. Please update to it using `wails update -pre`

**Comment by FriendlyUser** [comment]
Seems to work for me :), Thanks for the help

**Comment by khyoz** [comment]
cool, thanks !
