### ISSUE TITLE
BackgroundColour Can't Be Changed

### ISSUE THREAD

**Issue by waffle-lord** [wailsapp/wails#2742]
### Description

The background doesn't appear to change when using the BackgroundColour option
or
when using `runtime.WindowSetBackgroundColour`

### To Reproduce

1. Create a new wails project
2.1. change the BackgroundColour option
2.2. try to use the runtime.WindowSetBackgroundColour method to set the background color 

### Expected behaviour

The background color should change

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 112.0.1722.68
Nodejs     | N/A          | Installed | 18.16.0
npm        | N/A          | Installed | 9.6.6
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Attached is a test project to show these issues
[wails-background-issue.zip](https://github.com/wailsapp/wails/files/11852938/wails-background-issue.zip)

**Comment by leaanthony** [comment]
Are you saying that the colour you specify isn't seen in transparent areas in your UI? You need to have transparent areas.

**Comment by waffle-lord** [comment]
My apologies, I see now this is a svelte thing and not a wails one. I found that I can set the background of the entire app doing this, which is a start
```
:global(body) {
  background-color: green;
}
```

If there is a better way to set the background color programmatically in Go using wails I'd love to hear about it, but I'll figure something out on the svelte side

**Comment by leaanthony** [comment]
Like I said, the window background colour is really for specifying the colour of the pixels seen through transparent ui. It also is used to reduce flicker when resizing as sometimes the webview takes a short time to catchup
