### ISSUE TITLE
bump svelte and vite to latest versions on the svelte template

### ISSUE THREAD

**Issue by bnjox** [wailsapp/wails#2746]
### Is your feature request related to a problem? Please describe.

Svelte just got v4, _(might be too early to bump it)_ but vite has already been to v4 long since and the @sveltejs/vite-plugin-svelte has already been to v2.

### Describe the solution you'd like

to bump the versions in the package.json for the svelte template.

**Comment by sparrowsl** [comment]
I think so. thanks for bumping it...
