### ISSUE TITLE
whiteblank page when start

### ISSUE THREAD

**Issue by ignorantshr** [wailsapp/wails#2752]
### Description

run a old project in wails get a blank page

### To Reproduce

I was develop a project with wailsV2 about one years ago, it runs well.

Then I reinstall my macbookpro and uninstall wails resently, and I reinstall the last wailsV2 and plan to continue develop the old project, but  I get a whiteblank app and the err when I exeucte the dev command `wails dev` :`ERR | [ExternalAssetHandler] Proxy error: dial tcp [::1]:3000: connect: connection refused`. 

Then I create a template project with command `wails init -n myproject -t svelte`, but it runs well.

I am a noob in js, so I want to know What went wrong, I have try the doc [my-application-is-displaying-a-whiteblank-screen](https://wails.io/docs/guides/troubleshooting/#my-application-is-displaying-a-whiteblank-screen), it's not work for me.

By the way, `wails build` is ok.

### Expected behaviour

`wails dev` starts normally

### Screenshots

<img width="694" alt="image" src="https://github.com/wailsapp/wails/assets/34914892/10680e22-9479-4925-8e50-b04fddb8de36">

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | MacOS
Version      | 13.2.1
ID           | 22D68
Go Version   | go1.20.4
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2396
Nodejs                    | N/A          | Installed | 18.16.1
npm                       | N/A          | Installed | 9.5.1
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by chloyka** [comment]
I also have the same issue yesterday. 
I managed to get around this only by creating a new project, and transferring the code from the old project there

**Comment by stffabi** [comment]
It seems that your @ignorantshr frontenddevserver (vite?) is not running at all or not on port `:3000`. What frontend devserver are you using, vite? What's the output of vite?

**Comment by stffabi** [comment]
It seems like in `wails.json` the wrong port ins configured for vite. Older vite versions used port `:3000` newer use `:5173`. 

You should be able to fix this by adjusting the following property in your `wails.json`, you can either set it to the correct port or use `auto`.

```json
"frontend:dev:serverUrl": "", // URL to a 3rd party dev server to be used to serve assets, EG Vite. \nIf this is set to 'auto' then the devServerUrl will be inferred from the Vite output
```

**Comment by ignorantshr** [comment]
> It seems like in `wails.json` the wrong port is configured for vite. Older vite versions used port `:3000` newer use `:5173`.
> 
> You should be able to fix this by adjusting the following property in your `wails.json`, you can either set it to the correct port or use `auto`.
> 
> ```json
> "frontend:dev:serverUrl": "", // URL to a 3rd party dev server to be used to serve assets, EG Vite. \nIf this is set to 'auto' then the devServerUrl will be inferred from the Vite output
> ```

Thanks a lot! It works now!
