### ISSUE TITLE
provision to upgrade wails app remotely either from our VPS or from github

### ISSUE THREAD

**Issue by learncodingforweb** [wailsapp/wails#2754]
### Is your feature request related to a problem? Please describe.

Yes, unable to upgrade app once deployed. 

### Describe the solution you'd like

There should be a way to upgrade app remotely either using own VPS or github. 

### Describe alternatives you've considered

No alternative available to use

**Comment by leaanthony** [comment]
Duplicate of https://github.com/wailsapp/wails/issues/1178 👍
