### ISSUE TITLE
EventsOn (Frontend) receives inconsistent data

### ISSUE THREAD

**Issue by ramory-l** [wailsapp/wails#2759]
### Description

When trying to read data from file and pass file data to string channel and after that emit event with data from string channel to Frontend, one of the event delivers faster, but sends later (async behavior)

### To Reproduce

1. Read from file and pass data to string channel (I guess that's no matter)
```
for scanner.Scan() {
    text := scanner.Text()
    d.infoStream <- text
}
```
2. Get data from channel and emit event with that data to Frontend
```
go func() {
    for info := range streams.InfoStream {
        fmt.Println("+++", info) // consistent data
	runtime.EventsEmit(*m.ctx, "sensorsData", info)
	// time.Sleep(100 * time.Microsecond) // fixes that (crutch)
    }
}()
```
3. Receive data on Frontend (onclick)
```
const runMeasuringMachine = async () => {
  Run().then(() => {
    EventsOn('sensorsData', (result) => {
      console.log("***", result); // here inconsistent data (in one row!)
      if ((sensorsDataRef.value.length + 1) > 100) {
        sensorsDataRef.value.shift();
      }
      sensorsDataRef.value.push(result)
    })
    isMeasuringMachineRunning.value = true;
  });
}
```
4. In my file, I have data:
```
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
10 10 0 190 190
20 20 0 180 180
30 30 0 170 170
40 40 0 160 160
50 50 0 150 150
60 60 0 140 140
70 70 0 130 130
80 80 0 120 120
90 90 180 110 110
100 100 180 100 100
110 110 180 90 90
120 120 0 80 80
130 130 0 70 70
140 140 0 60 60
150 150 0 50 50
160 160 0 40 40
170 170 0 30 30
180 180 0 20 20
190 190 0 10 10
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
```
but the most of the time, I'm getting on Frontend:
```
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
Weight: 120
0 0 0 0 0 // inconsistent data
Weight: 120 // inconsistent data
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
10 10 0 190 190
20 20 0 180 180
30 30 0 170 170
40 40 0 160 160
50 50 0 150 150
60 60 0 140 140
70 70 0 130 130
80 80 0 120 120
90 90 180 110 110
100 100 180 100 100
110 110 180 90 90
120 120 0 80 80
130 130 0 70 70
140 140 0 60 60
150 150 0 50 50
160 160 0 40 40
170 170 0 30 30
180 180 0 20 20
190 190 0 10 10
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
```

### Expected behaviour

Expected, that I have the same data order like in my file

### System Details

```shell
MacOS Ventura 13.4.1 (Apple M1 Max)
```

**Comment by leaanthony** [comment]
Are you sure this isn't just a race condition with your logging?

**Comment by ramory-l** [comment]
> Are you sure this isn't just a race condition with your logging?

That's the problem, my logging is in `EventOn` callback function. So race condition is going in it.

**Comment by ramory-l** [comment]
It's very strange and important bug, sent data inconsistent...
![Screenshot 2023-07-10 at 18 55 57](https://github.com/wailsapp/wails/assets/48647803/3898297c-a314-4621-b886-63bf01706b05)
But on Frontend...
![Screenshot 2023-07-10 at 18 56 10](https://github.com/wailsapp/wails/assets/48647803/2e557707-c5ee-4819-9fad-b51459c9d099)

**Comment by leaanthony** [comment]
Are you able to create a small program that shows this issue? The event system is asynchronous so that's probably at play here. Perhaps using events isn't the best way to achieve your goal?

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by leaanthony** [comment]
My bad: https://wails.io/docs/guides/local-development#testing-a-pr

**Comment by ramory-l** [comment]
> Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

It didn't help(

My steps:
1. Follow this guide https://wails.io/docs/guides/local-development#testing-a-pr
2. Then run `wails dev -browser`

**Comment by leaanthony** [comment]
You did update your project `go.mod` with the `replace` line yes? If so, then I guess the webview script injection is reordering them :/

**Comment by ramory-l** [comment]
> You did update your project `go.mod` with the `replace` line yes? If so, then I guess the webview script injection is reordering them :/

Oh no, I didn't use replace in go.mod(
How to use it?

**Comment by leaanthony** [comment]
https://wails.io/docs/guides/local-development/#updating-your-project

**Comment by ramory-l** [comment]
> https://wails.io/docs/guides/local-development/#updating-your-project

I modified the end of my go.mod file like that:
from:
```
// replace github.com/wailsapp/wails/v2 v2.5.1 => /Users/ramory-l/go/pkg/mod
```
to:
```
// replace github.com/wailsapp/wails/v2 => /Users/ramory-l/Desktop/test_pr/wails/v2
```

**Comment by leaanthony** [comment]
>  Is there any reason you aren't just sending it in one go?

**Comment by stffabi** [comment]
@ramory-l just out of curiosity, did you try any of the other platforms, Windows or Linux? Would be interesting to know if it also happens there.

**Comment by ramory-l** [comment]
> @ramory-l just out of curiosity, did you try any of the other platforms, Windows or Linux? Would be interesting to know if it also happens there.

Not yet. But I guess that's platform independent.

**Comment by stffabi** [comment]
> Not yet. But I guess that's platform independent.

I have the feeling it might be a platform specific problem.

**Comment by ramory-l** [comment]
> > Not yet. But I guess that's platform independent.
> 
> I have the feeling it might be a platform specific problem.

Why do you feel so?

**Comment by stffabi** [comment]
I tried to reproduce it with a sample program on macOS 13.4.1 and with Wails 2.5.1, but wasn't able to. In my case all events were received with the same order in the frontend as they were sent from the backend.

@ramory-l can you please provide a minimal reproduction guide for this issue? A simple project that shows the issue would be very helpful for us. Thanks so much.

**Comment by ramory-l** [comment]
> I tried to reproduce it with a sample program on macOS 13.4.1 and with Wails 2.5.1, but wasn't able to. In my case all events were received with the same order in the frontend as they were sent from the backend.
> 
> @ramory-l can you please provide a minimal reproduction guide for this issue? A simple project that shows the issue would be very helpful for us. Thanks so much.

Ok, will try to make a simple program!

**Comment by tmclane** [comment]
Did you uncomment the replace line?  When it's commented out it doesn't do anything.

**Comment by leaanthony** [comment]
Closing as it's been too long. Feel free to reopen if you get more information you can share with us.
