### ISSUE TITLE
Blank Screen and Empty #app element on build

### ISSUE THREAD

**Issue by livin41** [wailsapp/wails#277]
**Description**

Using Vue template.

On wails serve, app works perfectly. Once I build the app (wails build) and open it. It displays a blank screen. While looking at the inspector there is no js file or elements within the #app element.

I have been able to work back each process to see that build works correctly before adding vue-pdf. The App works in development mode / wails serve mode, but once i build it, it creates the issue stated above.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Vue-Pdf to App : npm install vue-pdf
2. It returns an error stating that you need the babel-runtime/regenerator and asks for you to install it
3. Run wails build

![DesktopAppError](https://user-images.githubusercontent.com/885733/67574196-e5a89680-f731-11e9-9aa5-c56d0ba692d0.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.13-pre |
| Go Version    | go1.13.1 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | v12.13.0 |
| Node          | 6.12.0 |

: Just noticed that the wails issue produced the above System Details. The auto details of the npm and node versions are incorrect. It's  NPM : 6.12.0 and Node v12.13.0

**Comment by leaanthony** [comment]
Hi. Perhaps vue-pdf isn't compatible with webview? Does it rely on some browser functionality for the pdf?

**Comment by livin41** [comment]
Thanks for the response @leaanthony. 

The Underlying dependency for vue-pdf is pdf.js from Mozilla. Had a look there and firslty it looks like not all browser are completely supported, secondly i think the issues arise because of the necessary browser features (stated here [https://github.com/mozilla/pdf.js/wiki/Required-Browser-Features](url) ). I havent done anything needing Canvas, which i understand has some issues in webview, but cant confirm if thats the case.

I just resolved the issue for my case, which is a workaround embedding Pdf's into browser/webview just using the embed element. <embed src="file.pdf" type="application/pdf" width="100%" height="100%" />

Im just not sure why the #app element with Vue in build mode is empty, i will try upload a sample project as soon as i can.

Probably need to change the title of this issue to something more pdf/pdf.js/canvas related.

**Comment by leaanthony** [comment]
Thanks for the feedback. We may look at creating a white/black list of
compatible libs. Over time this will improve.

**Comment by leaanthony** [comment]
Closing as this is not a Wails issue.

**Comment by leaanthony** [comment]
Ah I just realised you may want to keep this open. Please feel free to reopen if that's the case :+1:
