### ISSUE TITLE
The "wails://wails" process on MacOS seems to have a memory leak.

### ISSUE THREAD

**Issue by luoshengheng** [wailsapp/wails#2772]
### Description

When running a program built with Wails on a Macbook Pro, there seems to be a memory leak in the wails://wails process, and the severity of the leak appears to be related to the complexity of the page. This issue is not easily reproducible and generally does not occur under normal circumstances. It only becomes apparent when I press the power button to put the computer into hibernation mode and let it sit idle for a period of time. I have tried letting it sit overnight, and the next day, the memory has increased from 200-300MB to 1.xGB.

In addition, I also tried removing all UI elements from the application, and the extent of the leak decreased significantly, from 40MB to 100MB.

### To Reproduce

1.Run the application built with Wails on MacOS (preferably with a slightly complex page), without performing any operations, just keep it running.
2.Record the memory usage of the wails://wails process at this time.
3.Put the computer into sleep mode.
4.After a while (approximately 1 hour), wake up the computer and check the memory usage of the wails://wails process at that time.

### Expected behaviour

Due to the fact that the Wails application is in a idle state without any operations, theoretically, the memory usage should remain stable. Even if there is any increase, it should be a short-term fluctuation and it should eventually return to a lower level.

### Screenshots

<img width="848" alt="wecom-temp-502addc8e0a0112ee7d128694e401754" src="https://github.com/wailsapp/wails/assets/31942473/3a5863b3-87f2-49c3-95e5-9ec3087ac1ef">

### Attempted Fixes

I have tested the same operation on Windows, and the memory performance of the msedgewebview2.exe process remains stable. Therefore, it is likely that any potential memory leaks are not caused by the application's business logic. Instead, it could be related to MacOS' memory management when in idle state. It is also possible that there are unknown bugs specific to Wails on MacOS. I am not certain about the exact cause.

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                 

# System

OS           | MacOS   
Version      | 11.3.1  
ID           | 20E241  
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2384         
Nodejs                    | N/A          | Installed | 12.16.3      
npm                       | N/A          | Installed | 6.14.4       
*Xcode                    | N/A          | Installed | 12.5 (12E262)
*upx                      | N/A          | Installed | upx 3.96     
*nsis                     | N/A          | Available |              
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by luoshengheng** [comment]
Weird. The issue cannot be reproduced on MacOS 13.2.1, indicating that there may be a problem on specific versions of MacOS.

**Comment by leaanthony** [comment]
How strange! Do you have exact steps to replicate? We could try out different versions.

**Comment by luoshengheng** [comment]
> How strange! Do you have exact steps to replicate? We could try out different versions.

Yes, it's a very odd issue. I will provide you with a demo. After idling for 14 hours, the memory of this demo rises from 100~200MB to 400+MB. You can try to reproduce the issue by following these steps:
**(Please note, it is crucial to let your MacBook go into the lock screen mode, because this issue cannot be reproduced in a regular working state.)**

1. git clone https://github.com/luoshengheng/WailsLeakDemo.git
2. cd WailsLeakDemo
3. npm install (node version is 16.18.1)
4. wails build
5. Run the App in the bin directory and maximize its window
6. Record the memory usage at this point
7. Lock the Macbook's screen and leave it idle for 10 hours, then wake up the computer
8. Record the memory usage at this point, and compare it with the memory usage before idling.

**Comment by luoshengheng** [comment]
> How strange! Do you have exact steps to replicate? We could try out different versions.
I cannot guarantee that this demo will reliably reproduce the issue on your MacBooks. To increase the chances, I suggest that you simultaneously run the tests on several MacBooks with different system versions, following the steps I've described above.

**Comment by luoshengheng** [comment]
> How strange! Do you have exact steps to replicate? We could try out different versions.

I cannot guarantee that this demo will reliably reproduce the issue on your MacBooks. To increase the chances, I suggest that you simultaneously run the tests on several MacBooks with different system versions, following the steps I've described above.
