### ISSUE TITLE
The same Wails application, when run on MacOS 10.13.6, exhibits particularly high memory usage for the wails://wails process

### ISSUE THREAD

**Issue by luoshengheng** [wailsapp/wails#2777]
### Description

I've tested the same application built with Wails across MacOS versions 10.13.6, 10.14.6, 11.3.1, 12.5.1, and 13.2.1, and found that only when running on 10.13.6 does the wails://wails process consume up to 800+MB of memory; on the other systems, it stays around 200MB.

Here are the system specifications for the MacOS 10.13.6 device:

*MacBook Pro(Retina,13-inch,Early 2015)
*Memory 8GB 1867MHz DDR3
*Intel Iris Graphics 6100 1536MB
*CPU: 2.9GHz Intel Core i5
*Features two versions of the Webkit kernel, versions 13605.3.8 and 13609.3.5.1.5, but I'm uncertain which one Wails depends upon during operation.

### To Reproduce

1.git clone https://github.com/luoshengheng/WailsLeakDemo.git
2.cd WailsLeakDemo
3.npm install (node version is 16.18.1)
4.wails build
5.Run the App in the bin directory
6.Record the memory usage at this point

### Expected behaviour

For the same application, the memory usage of the wails://wails process should not vary significantly when running on different versions of MacOS.

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                 

# System

OS           | MacOS   
Version      | 11.3.1  
ID           | 20E241  
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2384         
Nodejs                    | N/A          | Installed | 16.18.1      
npm                       | N/A          | Installed | 8.19.2       
*Xcode                    | N/A          | Installed | 12.5 (12E262)
*upx                      | N/A          | Installed | upx 3.96     
*nsis                     | N/A          | Available |              
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
I'm not sure what we can do about that as it seems to be specific to the Webview that's released as part of that release.

**Comment by luoshengheng** [comment]
Yes, I believe this issue and [#2772 ](https://github.com/wailsapp/wails/issues/2772)are largely related to specific versions of Webkit. Since developers cannot control the Webkit version used by users, it leads to inconsistency in how the same software performs on different computers. To accommodate this situation, would it be possible to consider providing an alternative solution that allows developers to choose whether to embed a browser core when building, just like Electron embeds Chromium?

**Comment by luoshengheng** [comment]
> I'm not sure what we can do about that as it seems to be specific to the Webview that's released as part of that OS version. Apple provide this component.

Yes, I believe this issue and [#2772](https://github.com/wailsapp/wails/issues/2772) are largely related to specific versions of Webkit. Since developers cannot control the Webkit version used by users, it leads to inconsistency in how the same software performs on different computers. To accommodate this situation, would it be possible to consider providing an alternative solution that allows developers to choose whether to embed a browser core when building, just like Electron embeds Chromium?

**Comment by leaanthony** [comment]
If you are able to find a solution for that then we would consider it.
