### ISSUE TITLE
Error when either running `wails serve` or running executable generated by `wails build`

### ISSUE THREAD

**Issue by psidex** [wailsapp/wails#278]
**Description**

An error message pops up when I try to run the executable generated by `wails build`.

Dismissing this message by either pressing "yes" or "no" closes the error window and the normal window is just a blank white box.

In a similar vein, running `wails serve` gives an error - https://pastebin.com/4JBWNeDY.
Unfortunately the output is not too helpful.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a new project using `wails init`
   - This was tested with both React and Vue project templates
2. `cd` to the project directory and run `wails build`
3. Run the `projectname.exe` file

OR

1. Create a new project using `wails init`
2. `cd` to the project directory
3. Run `wails serve` and the stop it
4. Interestingly enough, the first time `wails serve` is run it works fine. It's only the second time and onward that it breaks, so run `wails serve` again
5. See error

**Expected behaviour**

The app opens and displays the default wails project page.

**Screenshots**

`wails build`:

Error:
https://i.imgur.com/kp1Ff9T.png

After error closed:
https://i.imgur.com/Bxj0G4N.png

`wails serve`:

 https://pastebin.com/4JBWNeDY

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.13-pre |
| Go Version    | go1.13.1 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.8.3 |
| Npm           | v10.16.3 |
| Node          | 6.9.0 |

**Additional context**

This is basically 2 issues in one but I think they are possibly related?

Also just as a side note I have switched over to tdm-gcc and this still happens.

**Comment by leaanthony** [comment]
Hi. Can you please test with the latest prerelease? `wails update -pre`

Thanks!

**Comment by psidex** [comment]
I'm on `wails update -pre` and it says that's the latest prerelease?

**Comment by FriendlyUser** [comment]
I am getting the same error

**Comment by leaanthony** [comment]
Update: I now have serve working correctly, even through IE. However the built app still throws the same error, which is weird as it's the same code going to the same web engine. Still debugging.

**Comment by scshin0572** [comment]
Please check out the file attached to this comment(https://github.com/wailsapp/wails/issues/259#issuecomment-547284087).
webview_fix_ie_compat_mode() and more functions fixed.

**Comment by JHunz** [comment]
I'm also having this issue.  I tried the patch above, and I don't know if I built wails wrong but it didn't seem to resolve the issue for me

**Comment by leaanthony** [comment]
Please let me know if v0.18.15-pre fixes this. `wails update -pre`. Thanks!

**Comment by FriendlyUser** [comment]
Didn't fix it for now

**Comment by leaanthony** [comment]
Are you using Windows 7 or 10? It's working fine for me on Windows 10.

**Comment by psidex** [comment]
Tested on Win 10, `wails serve` is running fine for me.

**Comment by FriendlyUser** [comment]
@leaanthony wails serve has always worked for me, wails build is still failing for me.

**Comment by leaanthony** [comment]
Hi. Please run `wails update -pre` to get `v0.19.0-pre2`. Let me know if this fixes your issue. Thanks

**Comment by FriendlyUser** [comment]
Still failed for me

On Wails v0.19.0-pre2 - Building Application
![image](https://user-images.githubusercontent.com/13860264/68100751-8576ca80-fe7e-11e9-8375-ba3f16149686.png)

**Comment by lukasvosyka** [comment]
Hi Lea,

for me wails 0.190-pre2 now works also with the built .exe on Windows 10. But I had to recreate (wails init) a new project. After that it seems to work. Thanks!

**Comment by leaanthony** [comment]
Awesome. Due to dependency versioning, you will need to either update
go.mod or regenerate.

**Comment by FriendlyUser** [comment]
Worked for me when I reinit the wails project.
