### ISSUE TITLE
[Linux] DisableResize option not working

### ISSUE THREAD

**Issue by ramy100** [wailsapp/wails#2780]
### Description

when adding the `DisableResize = true` option it doesn't work .. and it shrinks the window to the minimum width and height while still being resizable

### To Reproduce

1. create new wails project `wails init -n myproject -t react-ts`
2. add `DisableResize: true` to the app options
3. run the app using `wails dev`

### Expected behaviour

expected the app window to have a fixed size and width

### Screenshots

![1](https://github.com/wailsapp/wails/assets/64619805/b1acee54-f9ff-4a68-afe3-946d395e7641)

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                                                                  

# System

OS           | Zorin OS
Version      | 16      
ID           | zorin   
Go Version   | go1.20.5
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.5.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 24.0.4                 
gcc        | build-essential       | Installed | 12.8ubuntu1.1          
libgtk-3   | libgtk-3-dev          | Installed | 3.24.20-0ubuntu1.1     
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.20.04.1
npm        | npm                   | Installed | 9.6.4                  
*nsis      | nsis                  | Installed | v3.05-2                
pkg-config | pkg-config            | Installed | 0.29.1                 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by zveinn** [comment]
Can confirm this doesn't work on Debian KDE desktop environment

**Comment by leaanthony** [comment]
Have you used `git bisect` to determine if it ever worked in KDE?

**Comment by zveinn** [comment]
I did not, but I just figured I´d add it to the comment since the original author is using zorin OS which only support GNOME and XFACE according to it´s documentation

**Comment by lyimmi** [comment]
I can confirm that the resize disabling is not working on Ubuntu 23.04 either.

I went back to the 2.0.0 release and its broken there too, I think its not a Wails problem. :confused: I'm trying to figure it out.

**Comment by lyimmi** [comment]
I found the problem. I the `NewWindow` function we set the windows initial size with `gtk_window_resize`, if I set the initial size with `gtk_window_set_default_size` everything work as expected.

I'll make a PR for this.

**Comment by lyimmi** [comment]
@zveinn I made a PR could you please test it?
