### ISSUE TITLE
HTML a-tag href does not work on macOS Ventura 13.3 (22E252)

### ISSUE THREAD

**Issue by Wowkoltyy** [wailsapp/wails#2783]
### Description

When you click on a-tag with href="https://example.com" nothing happens

### To Reproduce

1. Put `<a href="https://example.com/" target="_blank">Click me</a>` into your page HTML
2. Open `wails dev` session on macOS
3. Click the link
                

### Expected behaviour

I expected to see a WebBrowser windows of this link opened.

### Attempted Fixes

I tried to use `window.open` instead, but it does't open the browser too.

### System Details

```shell
# System

OS           | MacOS   
Version      | 13.3    
ID           | 22E252  
Go Version   | go1.20.1
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version         
Xcode command line tools  | N/A          | Installed | 2397            
Nodejs                    | N/A          | Installed | 18.13.0         
npm                       | N/A          | Installed | 9.4.0           
*Xcode                    | N/A          | Installed | 14.3.1 (14E300c)
*upx                      | N/A          | Installed | upx 4.0.2       
*nsis                     | N/A          | Installed | v3.09           
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

**Comment by ollytom** [comment]
By default Wails tries to load the content at the URL in the current window.
To launch a web browser, see [BrowserOpenURL].
See also issue #2691 for discussion

[BrowserOpenURL]: https://wails.io/docs/reference/runtime/browser/#browseropenurl
