### ISSUE TITLE
macOS13.3.1 cant't build

### ISSUE THREAD

**Issue by aomsir** [wailsapp/wails#2786]
### Description

I use the init application create a project。I cloud use `wails dev` to run in Browser. But I can't build.
<img width="934" alt="image" src="https://github.com/wailsapp/wails/assets/60360782/0cf7f2cf-3b5c-4cc2-bd41-2617799acc79">

### To Reproduce

wails build
Wails CLI v2.5.0

# Build Options

Platform(s)        | darwin/amd64
Compiler           | /usr/local/go/bin/go
Skip Bindings      | false
Build Mode         | production
Frontend Directory | /Users/aomsir/Downloads/test/myproject/frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | false
LDFlags            |
Tags               | []
Race Detector      | false

# Building target: darwin/amd64

  • Generating bindings:
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:
Done.
  • Compiling application:
# runtime/cgo
In file included from _cgo_export.c:3:
/usr/local/include/stdlib.h:181:5: error: 'TARGET_OS_EMBEDDED' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
  ERROR   exit status 2

  ERROR   exit status 2
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### Expected behaviour

successful build

### System Details

```shell
Wails CLI v2.5.0

 SUCCESS  Done.

# System

OS           | MacOS
Version      | 13.3.1
ID           | 22E261
Go Version   | go1.18.2
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.5.0

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397
Nodejs                    | N/A          | Installed | 20.5.0
npm                       | N/A          | Installed | 9.8.0
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by ivila** [comment]
Can you provide your "go.mod" file? I think the problem is related to repos you are importing in your go files.

**Comment by aomsir** [comment]
```shell
module changeme

go 1.18

require github.com/wailsapp/wails/v2 v2.5.0

require (
	github.com/bep/debounce v1.2.1 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/google/uuid v1.1.2 // indirect
	github.com/jchv/go-winloader v0.0.0-20210711035445-715c2860da7e // indirect
	github.com/labstack/echo/v4 v4.9.0 // indirect
	github.com/labstack/gommon v0.3.1 // indirect
	github.com/leaanthony/go-ansi-parser v1.0.1 // indirect
	github.com/leaanthony/gosod v1.0.3 // indirect
	github.com/leaanthony/slicer v1.5.0 // indirect
	github.com/mattn/go-colorable v0.1.11 // indirect
	github.com/mattn/go-isatty v0.0.14 // indirect
	github.com/pkg/browser v0.0.0-20210706143420-7d21f8c997e2 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/samber/lo v1.27.1 // indirect
	github.com/tkrajina/go-reflector v0.5.5 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v1.2.1 // indirect
	github.com/wailsapp/mimetype v1.4.1 // indirect
	golang.org/x/crypto v0.1.0 // indirect
	golang.org/x/exp v0.0.0-20220303212507-bbda1eaf7a17 // indirect
	golang.org/x/net v0.7.0 // indirect
	golang.org/x/sys v0.5.0 // indirect
	golang.org/x/text v0.7.0 // indirect
)

// replace github.com/wailsapp/wails/v2 v2.5.0 => /Users/aomsir/MyStatic/GOPATH/pkg/mod

```

> Can you provide your "go.mod" file? I think the problem is related to repos you are importing in your go files.

**Comment by ivila** [comment]
It could be some reasons of cgo in MacOS, you can try following work around and see if any of these works:
1, disable cgo, try command: ```CGO_ENABLED=0 wails build```
2, set TARGET_OS_EMBEDDED yourself, try command: ```CGO_CXXFLAGS="-DTARGET_OS_DRIVERKIT=0 -O2 -g" wails build```

**Comment by aomsir** [comment]
The two commands remind me this information
<img width="766" alt="image" src="https://github.com/wailsapp/wails/assets/60360782/59826b8f-8279-4629-bff6-4399b1cde5ef">
