### ISSUE TITLE
Using xtermjs wails dev gives wrong output but wails build works fine

### ISSUE THREAD

**Issue by JensvandeWiel** [wailsapp/wails#2799]
### Description

Im using xterm to emulate a console in the frontend, but when using wails dev no new lines are created is i use wails build it works fine!
**Using wails dev:**
![image](https://github.com/wailsapp/wails/assets/85284773/75eba662-d996-477e-b15f-653b6374f23d)
**Using wails build:**
![image](https://github.com/wailsapp/wails/assets/85284773/684de326-840e-4b75-8f8e-0bb588d89a06)

I have already created an issue at xterm repo but we found out its not xterm but the bundler or else
https://github.com/xtermjs/xterm.js/discussions/4615

### To Reproduce

1. Create a new wails app
2. create an xterm console using react. example repo without wails:  https://github.com/JensvandeWiel/tetst

To check if it created a new line i made a button that sends a string to the terminal using Terminal.write(string + "\n") or just use Terminal.writeln

for more info on xtern check: http://xtermjs.org/docs/

### Expected behaviour

**Using wails build:**
![image](https://github.com/wailsapp/wails/assets/85284773/684de326-840e-4b75-8f8e-0bb588d89a06)

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 19045)
ID           | 22H2
Go Version   | go1.20.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 115.0.1901.183
Nodejs     | N/A          | Installed | 18.16.0
npm        | N/A          | Installed | 9.5.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Related discord thread: https://discord.com/channels/1042734330029547630/1134151661179375676

**Comment by JensvandeWiel** [comment]
Waybe a place to start is what wails dev does different from wails build

**Comment by JensvandeWiel** [comment]
more context: left is wails build -debug, right is wails dev.
![image](https://github.com/wailsapp/wails/assets/85284773/bad2d17b-010b-4c39-adb7-c5c081460a0f)

**Comment by leaanthony** [comment]
Please keep this up to date with the discord help thread.

**Comment by JensvandeWiel** [comment]
stffabi — Yesterday at 11:58 PM
Does it happen when accessing vite directly in your browser? 
Mr. Alpaca
OP
 — Today at 12:11 AM
let me try
yes same thing happens 😦
if i use xterm in a basic react app that uses vite it works fine

**Comment by JensvandeWiel** [comment]
Ok got it working, for some reason it does not work in react class component but ill investigate that tomorrow!

**Comment by asjdf** [comment]
I guess you put the "xterm component" inside the `<StrictMode>` from react. The "xterm component" inside the `<StrictMode>` will render **twice** in dev mode which will break the xterm.
