### ISSUE TITLE
Correct typing of embedded structs

### ISSUE THREAD

**Issue by Pixdigit** [wailsapp/wails#280]
**Description**

I have a `FileTree` type which consist of an Absolute path accompanied by an embedded `os.FileInfo`. That struct is bound to Wails. It has a method `Children()` which returns `[]FileTree`. In javascript the promise resolves to an array of objects which have and `AbsPath` and an empty Object `FileInfo`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://gitlab.com/Pixdigit/fermion/tree/wails_issue
2. When build it should print out the array to console

**Expected behaviour**
Having each `FileTree` behaving as the bound `FileTree` i.e. having the methods of the `FileInfo` exposed. Or a reason why this is intended behaviour.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.13-pre |
| Go Version    | go1.13.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 7.4.0 |
| Npm           | v11.15.0 |
| Node          | 6.9.0 |

**Comment by Pixdigit** [comment]
Nvm I just haven't quite understood how and what kind of  data front and backend exchange.

**Comment by leaanthony** [comment]
Glad you got it sorted. If you feel the docs could explain it better then please feel free to make any suggestions on updating it. We are always looking to improve them :+1:
