### ISSUE TITLE
[Linux] new app option to set GTK's program name (g_set_prgname)

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#2800]
### Is your feature request related to a problem? Please describe.

As usual on Linux (gnome) setting the icon for a program is not too straight forward. You need a .desktop file, but when the executable's name differs too much form the program's name in the desktop file the set icon is not shown, even if the shortcut is pinned on the doc.

![image](https://github.com/wailsapp/wails/assets/8627125/6759456b-7822-4f7c-bdf7-658f5346bb2c)

However if we set the program name in GTK `g_set_prgname()` we can name the program anything we want as long as the .desktop file and the program name matches. And it properly groups the running instances as well. (In V3 this could help window grouping as well.)

![image](https://github.com/wailsapp/wails/assets/8627125/f9229605-a8e2-452d-9058-0033a144fcbb)

It would work on other windowing systems as well.

If this change is OK I'll make a PR for it.

### Describe the solution you'd like

I would like to add a new option to `v2/pkg/options/linux/linux.go` called `ProgramName`

```golang
// Options specific to Linux builds
type Options struct {
	// ProgramName used to set GTK's program name property. [see the docs]
        //
        // If a .desktop file is created for the program and the Name matches with this value the desktop icon is set and instance grouping works properly as well.
	//
	// [see the docs]: https://docs.gtk.org/glib/func.set_prgname.html
	ProgramName string
       
        ...
}
```

And call the `g_set_prgname()` function in `v2/internal/frontend/desktop/linux/frontend.go` `NewFrontend()` after the signal handlers are installed:

```golang
if appoptions.Linux.ProgramName != "" {
    C.g_set_prgname(C.CString(appoptions.Linux.ProgramName))
}
```

### Describe alternatives you've considered

We could refactor the whole Linux C code to use GtkApplication, but its a really big change and I think its not worth it.

But the change proposed above is a few lines and it would make life a little easier.

**Comment by leaanthony** [comment]
Yeah let's do it 👍
