### ISSUE TITLE
How to change default app logo

### ISSUE THREAD

**Issue by devzwy** [wailsapp/wails#2802]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Please. 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by trueFireblade** [comment]
If I'm not mistaken just replace `build/windows/icon.ico` to change the icon for the windows exe. And for Macos it seems you need
```go
...
err := wails.Run(&options.App{
  ...
  Mac: &mac.Options{
    About: &mac.AboutInfo{
      Title: "MyApp",
      Message: "My message",
      Icon: icon,
    }
  },
  ...
})
```
where icon is
```go
//go:embed build/path/to/imagefile
var icon []byte
```

Though you'll have to first verify this info as I own neither a windows nor macos system so can't guarantee that this is 100% accurate, hope I still was able to provide you a helpful pointer

**Comment by leaanthony** [comment]
https://wails.io/docs/gettingstarted/firstproject#project-layout

**Comment by devzwy** [comment]
Thanks.
