### ISSUE TITLE
drag a window with the parameter "-- walls draggable: drag"

### ISSUE THREAD

**Issue by li9hu** [wailsapp/wails#2803]
### Description

When I drag a window with the parameter "-- walls draggable: drag", the mouse is not in a pointer state, but in the character "I", which is strange。

### To Reproduce

1.Create a basic example of React 
2. modify index.html
3. add  style -- walls draggable: drag

### Expected behaviour

I think it would be more reasonable to default to the pointer state when dragging

### Screenshots

https://github.com/wailsapp/wails/assets/48636077/30684b39-9ecb-4115-b3b5-4e5cca2820ea

### System Details

```shell
System

OS           | MacOS
Version      | 13.4
ID           | 22F66
Go Version   | go1.20.3
Platform     | darwin
Architecture | arm64

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397
Nodejs                    | N/A          | Installed | 20.3.1
npm                       | N/A          | Installed | 9.6.7
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency
```

**Comment by leaanthony** [comment]
Only CSS will fix this. https://stackoverflow.com/questions/10809995/css-disable-text-selection

**Comment by LvBay** [comment]
> Only CSS will fix this. https://stackoverflow.com/questions/10809995/css-disable-text-selection

It would be great if the solution could be explained in more detail. I'm also blocked by the same problem

**Comment by LvBay** [comment]
![image](https://github.com/wailsapp/wails/assets/18084744/02930dc6-9f79-4fcb-a567-32a422215087)
* {
    -webkit-touch-callout:none;
    -webkit-user-select:none;
    -moz-user-select:none;
    -ms-user-select:none;
    user-select:none;
}

After adding the above css, it was solved
