### ISSUE TITLE
Window flashes through white before BackgroundColour

### ISSUE THREAD

**Issue by sandhu** [wailsapp/wails#2804]
### Description

The window flashes through white before the `BackgroundColour` specified in the `options.App` to `wails.Run` takes effect.

### To Reproduce

1. Create fresh project with `wails init -n myproject -t vanilla`
2. `wails dev` or `wails build`

When the window launches it is briefly white `~1s` before taking the specified `BackgroundColour`

### Expected behaviour

Windows should have the specified `BackgroundColour` when it first become visible.

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                 

# System

OS           | MacOS   
Version      | 13.4.1  
ID           | 22F82   
Go Version   | go1.20.6
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397   
Nodejs                    | N/A          | Installed | 20.5.0 
npm                       | N/A          | Installed | 9.8.0  
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by sandhu** [comment]
In the generated project it appears that the background is being set in `frontend/src/style.css` and the `BackgroundColour` property appears to have no effect.

**Comment by leaanthony** [comment]
It does, but that's because the web view default background colour is white. You can use the window colour if you want by adding the following to your application config: 

```go
		Mac: &mac.Options{
			WebviewIsTransparent: true,
		},
```

I've added this to the troubleshooting guide on the main website.

**Comment by sandhu** [comment]
Thank you. I had to add the following to get the desired effect. Otherwise the window was completely transparent.
```
			WindowIsTranslucent:  false,
```
