### ISSUE TITLE
Marshaling data from frontend

### ISSUE THREAD

**Issue by jschweizer78** [wailsapp/wails#281]
**Description**

How do you marshal data recived from the from the frontend, in go code? It appears to send a generic map[string]interface{}, and when I try to type interfaces I get memory access error. I am a newbie so maybe I am just missing something. An example of binding an object would be helpful.

**To Reproduce**
Steps to reproduce the behaviour:
1. pass JSON object from frontend to backend
2. get an interface from map
3. try to type assert interface{} (even if string)

**Expected behaviour**
to convert interface to a real type or struct.

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.5 |
| Go Version    | go1.13.3 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | v10.15.1 |
| Node          | 6.12.0 |

**Additional context**

**Comment by leaanthony** [comment]
Hi! Thanks for opening this ticket as the docs are unclear about this. Wails doesn't currently support automatic conversion of objects from JS to Go, however that would be a great enhancement for the future so will make a note of that. 

If you really want to do this, I'd recommend using hashicorp's [mapstructure](https://github.com/mitchellh/mapstructure). I have now detailed how to do this in the [reference guide](https://wails.app/reference/#type-conversion). 

Feel free to close this if this is sufficient for you.

**Comment by jschweizer78** [comment]
that is wonderful. Thank you so much for the fast reply. This is very
helpful, it works perfectly. :)

**Comment by leaanthony** [comment]
Thanks for raising awareness of a gap in the docs. Good luck! :+1:
