### ISSUE TITLE
Qwik support please?

### ISSUE THREAD

**Issue by LazyClicks** [wailsapp/wails#2818]
### Describe the solution you'd like

Support for the resumability JavaScript framework Qwik 

### Describe alternatives you've considered

I've checked Tauri out which supports Qwik but it uses rust for the backend and I would prefer Go instead

**Comment by leaanthony** [comment]
What's stopping you using it?

**Comment by LazyClicks** [comment]
Hello, it doesn't seem to have Qwik integration tho? will it work without it?
