### ISSUE TITLE
enhancement: make gtk-webkit optional

### ISSUE THREAD

**Issue by mewmew** [wailsapp/wails#282]
First of, thanks for releasing Wails! It's been great to get rather seamless interaction between Go and the frontend. I imagine a lot of work went into the marshalling of Go structs to equivalent JS values, and it's appreciated.

I just reinstalled my laptop the other week, and as such, have had a pretty clean slate of installed packages. When I tried to build `pippi`, a tool that my brother and I have been working on, I ran into this build error:

```
$ go get github.com/wailsapp/wails@master
go: finding github.com/wailsapp/wails master
go: downloading github.com/wailsapp/wails v0.18.5


# pkg-config --cflags  -- gtk+-3.0 webkit2gtk-4.0
Package webkit2gtk-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'webkit2gtk-4.0', required by 'virtual:world', not found
pkg-config: exit status 1
```

This makes perfect sense, as my machine does not have webkit2gtk installed. I went ahead and installed this package, and of course, the error went away and Wails now builds successfully.

However, it struck me that it would be really useful if this dependency was made optional.

In particular, it is possible and also common practice to use Wails from a web browser. This is indeed how my brother and I have been working, and we rarely (read never) use the webkit GTK frontend of Wails, but always use a browser to interface towards it.

As such, it would be interesting to look into if it was possible to make the gtk-webkit dependency optional. Of course, without affecting the natural work flow of those how do use Wails in this "app" mode.

Just putting it out there so we can think of a solution. My initial guess would be to use build tags, but I'm not sure how well that works with e.g. Go modules, etc.

Well, food for thought.

Cheers,
Robin

**Comment by bh90210** [comment]
Hello Robin,
I think what you are describing is using wails as web app tool?
@leaanthony will be more detailed but the feature to use wails as a webserver essentially used to be supported and I am under the impression that after v1 it will actually re-implemented.

**Comment by mewmew** [comment]
@bh90210, oh. you can most certainly use Wails as a web server today. Using `wails serve` and then navigating to `localhost:4200` works perfectly fine.

My thought was mainly to make the dependency on webkit optional, as users of Wails may not always have access to webkit2gtk locally, but may have access to a web browser.

**Comment by leaanthony** [comment]
Hey there!

Thanks for the kind words! This is something we used to do and will do so
again post v1. It's actually first on the list. If you have any thoughts on
what a "webserver" deploy might look like, I'd be really keen to hear them.

Thanks.

**Comment by bh90210** [comment]
I have spent sometime thinking about it and my thoughts on it are that trying to support as many linux distributions as possible with double documentation (with/without webkit) would turn out more confusing to both users and maintainers. My assumption is that most people will use wails to produce desktop apps. Though I too see the merit of using wails as framework for web apps my take would be that _"forcing"_ users intending to use wails for not producing standalone binaries to install one extra lib would *for the moment* seems the least problematic option. 
Implementing the webkit library checking as optional is not that hard but the particular details would require some thoughtful design.

**Comment by leaanthony** [comment]
Yeah, for it to work, it has to be "seamless", which means you have to use
the "lowest common denominator". Example: authentication. Whatever
mechanism you use, it has to work on desktop as well as server. As that's
usually handled by middleware, what does that mean for desktop apps?
Likelihood is the need for extra "hooks". Desktop apps by their nature are
single user, but web apps multi-user. We just need to think a bit more
about the use cases. Maybe it's not a problem as thing like auth have to be
handled by the user anyway.

My initial thoughts were along the lines of doing something similar to
serve but handle multi-user;

   - IPC comms is done via websockets
   - Should mean no API change
   - We could do "rest" type methods using /api/<package>/<struct>/<method>
   type structure...

**Comment by leaanthony** [comment]
Did you have any more thoughts on this @mewmew?

**Comment by mewmew** [comment]
> Did you have any more thoughts on this @mewmew?

I think you've covered most aspects. If time is limited with development, the indeed focus on the core aspects rather than this.

Are there any other dependencies of Wails than gtk-webkit that require Cgo? If not, than that would be one motivating aspect to allow building wails without requiring gtk-webkit, but as mentioned, only do this once the more important issues are taken care of.

Cheers,
Robin

**Comment by leaanthony** [comment]
I'm going to get v1 over the line, take stock of where we are at and start prioritising work for v2. As I said earlier, this is one of the main things I want to achieve. Will close for now but be assured we will look at it 👍
