### ISSUE TITLE
可以像Flutter一样手动热加载吗，修改服务端代码频繁重启总是被打断，很窝火。

### ISSUE THREAD

**Issue by akkagao** [wailsapp/wails#2820]
### Describe the solution you'd like

可以像Flutter一样手动热加载吗，修改服务端代码频繁重启总是被打断，很窝火。

**Comment by almas1992** [comment]
```shell
wails dev -help
Wails CLI v2.5.1

Wails dev - Runs the application in development mode
Flags:

  ..............
  ..............
  -extensions string
    	Extensions to trigger rebuilds (comma separated) eg go (default "go")
  ..............
  ..............
```
wails 默认是会监听后缀为`go` 的文件变更实现热加载，可通过 `-extensions` 参数能实现你的需求,传个非`go`字符串做监听后缀即可，如：`wails dev -extensions nothing`

**Comment by akkagao** [comment]
> ```shell
> wails dev -help
> Wails CLI v2.5.1
> 
> Wails dev - Runs the application in development mode
> Flags:
> 
>   ..............
>   ..............
>   -extensions string
>     	Extensions to trigger rebuilds (comma separated) eg go (default "go")
>   ..............
>   ..............
> ```
> 
> wails 默认是会监听后缀为`go` 的文件变更实现热加载，可通过 `-extensions` 参数能实现你的需求,传个非`go`字符串做监听后缀即可，如：`wails dev -extensions nothing`


这个操作我试过，会导致无法热加载，-debounce 是延后了触发时机。
比较合理的做法是能让用户自主触发热加载。
Flutter的做法是 命令行中输入 h 或者 r，触发热加载。

**Comment by almas1992** [comment]
> > ```shell
> 
> > wails dev -help
> 
> > Wails CLI v2.5.1
> 
> > 
> 
> > Wails dev - Runs the application in development mode
> 
> > Flags:
> 
> > 
> 
> >   ..............
> 
> >   ..............
> 
> >   -extensions string
> 
> >     	Extensions to trigger rebuilds (comma separated) eg go (default "go")
> 
> >   ..............
> 
> >   ..............
> 
> > ```
> 
> > 
> 
> > wails 默认是会监听后缀为`go` 的文件变更实现热加载，可通过 `-extensions` 参数能实现你的需求,传个非`go`字符串做监听后缀即可，如：`wails dev -extensions nothing`
> 
> 
> 
> 
> 
> 这个操作我试过，会导致无法热加载，-debounce 是延后了触发时机。
> 
> 比较合理的做法是能让用户自主触发热加载。
> 
> Flutter的做法是 命令行中输入 h 或者 r，触发热加载。

变通一下嘛，比如创建个 xx.nothing 的文件，想触发热加载时往这个文件里随便写个内容保存一下就好了
