### ISSUE TITLE
How to use system tray 

### ISSUE THREAD

**Issue by xilu-wang** [wailsapp/wails#2821]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

sounds like wails support systemtray ? How to use it ? Any documents and examples ?
https://github.com/wailsapp/wails/blob/v2.5.1/v2/pkg/options/systemtray.go#L8

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
That's old and should be removed. Support is coming next major version. There are workarounds for using 3rd party packages. Search issues for details 👍

**Comment by W1M0R** [comment]
Linking a few of the issues for convenience:

1. #1521 
2. #1959 
3. #2181 
4. #2157 
5. #2158
