### ISSUE TITLE
Build for linux arm64 error

### ISSUE THREAD

**Issue by freecells** [wailsapp/wails#2833]
### Description

it's a start program from wails.io , cross build for linux/arm64 error:

$ CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc wails build --clean  --platform="linux/arm64" 
Wails CLI v2.5.1

# Build Options

Platform(s)        | linux/arm64                               
Compiler           | /snap/bin/go                              
Skip Bindings      | false                                     
Build Mode         | production                                
Frontend Directory | /home/keven/go/src/keven/wildcall/frontend
Obfuscated         | false                                     
Skip Frontend      | false                                     
Compress           | false                                     
Package            | true                                      
Clean Bin Dir      | true                                      
LDFlags            |                                           
Tags               | []                                        
Race Detector      | false                                     

# Building target: linux/arm64

  • Generating bindings: 
  ERROR   
          # runtime/cgo
          aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
          
          exit status 1

Go env:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/k/.cache/go-build"
GOENV="/home/k/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/k/go/pkg/mod"
GONOPROXY="*.corp.example.com"
GONOSUMDB="*.gorm.io"
GOOS="linux"
GOPATH="/home/k/go"
GOPRIVATE="*.corp.example.com"
GOPROXY="https://goproxy.io,direct"
GOROOT="/snap/go/current"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/snap/go/current/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/k/go/src/k/wildcall/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build112312382=/tmp/go-build -gno-record-gcc-switches"

### To Reproduce

empty

### Expected behaviour

build success

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                                                                                    

# System

OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version   | go1.20.7
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.5.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                  
*docker    | docker.io             | Installed | 20.10.25-0ubuntu1~22.04.1
gcc        | build-essential       | Installed | 12.9ubuntu3              
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2         
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.40.5-0ubuntu0.22.04.1  
npm        | npm                   | Installed | 8.5.5                    
*nsis      | nsis                  | Installed | v3.08-2                  
pkg-config | pkg-config            | Installed | 0.29.2-1ubuntu3          
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

This is as known issue for v2 when cross compiling and using ENV variables to define another compiler. https://github.com/wailsapp/wails/issues/1921#issuecomment-1312214045

> Have you tried to skip the building of your bindings with -skipbindings? For generating the bindings, a binary is build and executed. Since you are using GOOS and GOARCH the generated binary is a windows binary, which can't be executed on Linux.

So in your case for bindings generation a AMD64 binary is build because your GOARCH is amd64 and it tries to use `aarch64-linux-gnu-gcc` in that case and that is not going to work.

This is most probably never going to be fixed for v2, but v3 (pre-alpha) uses another approach for binding generations where this is not a problem anymore.

**Comment by stffabi** [comment]
Duplicate of #1921

**Comment by freecells** [comment]
add -skipbindings  get error :
# github.com/wailsapp/wails/v2/pkg/assetserver/webview
In file included from /usr/aarch64-linux-gnu/include/features.h:510,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/aarch64-linux-gnu/include/limits.h:26,
                 from /usr/lib/gcc-cross/aarch64-linux-gnu/11/include/limits.h:203,
                 from /usr/lib/gcc-cross/aarch64-linux-gnu/11/include/syslimits.h:7,
                 from /usr/lib/gcc-cross/aarch64-linux-gnu/11/include/limits.h:34,
                 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:11,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../../../pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/pkg/assetserver/webview/request_linux.go:9:
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by freecells** [comment]
it's a big bug 😞

**Comment by freecells** [comment]
CGO 真是让人奔溃的
