### ISSUE TITLE
How to disable the right-click mouse gesture functionality?

### ISSUE THREAD

**Issue by geekroscom** [wailsapp/wails#2838]
![1](https://cdn.geekros.com/robotchain/upload/image/20230828125303.png)

### Description

How to disable the right-click mouse gesture functionality?

### To Reproduce

Hold down the right mouse button and slide within the interface.

### Expected behaviour

Disable mouse gesture events for the WebView.

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Windows 10 Pro     
Version      | 2009 (Build: 22621)
ID           | 22H2               
Go Version   | go1.19.4           
Platform     | windows            
Architecture | amd64              

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 116.0.1938.54
Nodejs     | N/A          | Installed | 18.13.0
npm        | N/A          | Installed | 8.19.3
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.08
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by JoiLa** [comment]
> 
you can try
```javascript
document.oncontextmenu = new Function('event.returnValue=false')
```

**Comment by geekros** [comment]
> > 
> 
> you can try
> 
> ```js
> document.oncontextmenu = new Function('event.returnValue=false')
> ```

This is not a reliable approach; it will bring about more issues or result in the unavailability of other functions. The official party should provide a better way to handle this.

**Comment by geekros** [comment]
This issue seems to have emerged in recent versions; it appeared to be functioning normally during earlier stages of development.

**Comment by geekros** [comment]
Is there a viable solution available?

**Comment by KiddoV** [comment]
I don't think you can right-click to open the webview2 menu anymore when you build to exe (bin) file. It only appear when you ``wails dev`` or use ``-debug`` when build ``wails build -debug`` 🤔

**Comment by geekros** [comment]
> I don't think you can right-click to open the webview2 menu anymore when you build to exe (bin) file. It only appear when you `wails dev` or use `-debug` when build `wails build -debug` 🤔

I found through testing that both wails dev and wails build -webview2 embed -nsis will trigger the webview2 gesture event when you long-press the right mouse button and drag.

![1](https://cdn.geekros.com/robotchain/upload/image/20230828125303.png)

**Comment by geekros** [comment]
Haven't any of you encountered this issue?

**Comment by leaanthony** [comment]
Could you please provide a video to help us see what you're seeing? Thanks!

**Comment by geekros** [comment]
> Could you please provide a video to help us see what you're seeing? Thanks!

Video：https://cdn.geekros.com/robotchain/upload/image/18-09-16.mp4

**Comment by leaanthony** [comment]
Oh wow, I've never seen that! I can see what is needed to disable it. A quick test appears to indicate that `GetICoreWebView2Settings6()` isn't working as expected so will need more time to debug it.

**Comment by geekros** [comment]
> Oh wow, I've never seen that! I can see what is needed to disable it. A quick test appears to indicate that `GetICoreWebView2Settings6()` isn't working as expected so will need more time to debug it.

I feel the issue might be related to the version of WebView2, as it seems like Windows automatically upgraded Edge for me.

```
Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 116.0.1938.54
```

**Comment by leaanthony** [comment]
The Settings6 stuff was released 2 years ago so I don't think it's a version issue. The UUID looks fine.... the lookup just returns nil :/

**Comment by leaanthony** [comment]
I've found the issue and will be creating a PR tonight.

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/local-development#testing-a-pr). Let us know how you get on 👍

**Comment by geekros** [comment]
Thank you very much for your help. I followed the method you provided to update and try it out, and discovered new configuration options:

```
...
WebviewDisableRendererCodeIntegrity bool

// Configure whether swipe gestures should be enabled
EnableSwipeGestures bool
...
```

I also tried adding this new configuration item in my own project, but whether it's set to true or false, the problem I raised still exists.

```
...
err := wails.Run(&options.App{
		Title:     "",
		Width:     1200,
		Height:    768,
		MinWidth:  1200,
		MinHeight: 768,
		AssetServer: &assetserver.Options{
			Assets: template,
		},
		BackgroundColour: &options.RGBA{R: 30, G: 31, B: 34, A: 1},
		OnStartup:        start.Startup,
		OnShutdown:       start.Shutdown,
		Bind: []interface{}{
			start,
		},
		Windows: &windows.Options{
			WebviewDisableRendererCodeIntegrity: true,
			DisableWindowIcon:                   true,
			EnableSwipeGestures:                 false,
			CustomTheme: &windows.ThemeSettings{
				DarkModeTitleBar:  windows.RGB(43, 45, 48),
				DarkModeTitleText: windows.RGB(187, 187, 187),
				DarkModeBorder:    windows.RGB(60, 63, 65),
				LightModeTitleBar:  windows.RGB(43, 45, 48),
				LightModeTitleText: windows.RGB(187, 187, 187),
				LightModeBorder:    windows.RGB(60, 63, 65),
				DarkModeTitleBarInactive:  windows.RGB(60, 63, 65),
				DarkModeTitleTextInactive: windows.RGB(187, 187, 187),
				DarkModeBorderInactive:    windows.RGB(60, 63, 65),
				LightModeTitleBarInactive:  windows.RGB(60, 63, 65),
				LightModeTitleTextInactive: windows.RGB(187, 187, 187),
				LightModeBorderInactive:    windows.RGB(60, 63, 65),
			},
		},
		Debug: options.Debug{
			OpenInspectorOnStartup: false,
		},
	})
...
```

**Comment by leaanthony** [comment]
You changed your project go.mod to use replace like in the instructions?

**Comment by geekros** [comment]
> You changed your project go.mod to use replace like in the instructions?

Yes, the replacements and modifications have been made as follows:

```
module toolschain

go 1.18

require (
	github.com/gin-gonic/gin v1.8.2
	github.com/gookit/color v1.5.2
	github.com/wailsapp/wails/v2 v2.5.1
)

require (
	github.com/bep/debounce v1.2.1 // indirect
	...
)

replace github.com/wailsapp/wails/v2 => D:\wails\v2

```

**Comment by leaanthony** [comment]
I think I found the issue, please re-pull from the PR branch and try again 🙏

**Comment by leaanthony** [comment]
@geekros - any updates?

**Comment by geekros** [comment]
> @geekros - any updates?

I'm truly sorry, I've been quite busy recently. I've tested it, and it can solve the problem.

**Comment by leaanthony** [comment]
I can't actually believe it!!!
