### ISSUE TITLE
JSON imports for Vuex does not re-import upon restart of application.

### ISSUE THREAD

**Issue by grvlle** [wailsapp/wails#286]
**Description**

I've imported a json file in my Vuex Store, this used to re-import the contents for each time I started the application. Now I need to re-compile (wails build) for it to re-import the contents.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import a .json file containing a few objects (import JSONFile ../file.json)
2. Assing the variable to a vuex store (store {file: JSONFile})
3. Loop through the objects (`<div v-for="$store.JSONFile"><p>hi</p></div>`)
4. Wails build -> start the application
5. Take note of the number of "hi"'s displayed.
6. Close the application
7. Start the application
8. Add more JSON objects to file.json
9. Start the application
10. The same number of "hi"'s will be displayed.
11. Wails build -> start the application
12. The correct number of "hi"'s will be displayed.

**Expected behaviour**
The wails app should re-import the file at each launch of the application. This was the case before the v0.19.0-pre2 version. 

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.19.0-pre2 |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 7.4.0 |
| Npm           | 6.10.3 |
| Node          | v12.10.0 |

**Additional context**

**Comment by leaanthony** [comment]
Hi. All external files *should* be statically compiled in by default. If it
did not do that previously, then it was a bug. If you want dynamic loading,
you will need to use file I/O from the backend, as per the Todo example on
the documentation site.

Hope that helps.
