### ISSUE TITLE
Vuetify 2.1.0

### ISSUE THREAD

**Issue by ljjimenez** [wailsapp/wails#287]
**Description**

Upgrade to Vuetify 2.1.0, is it possible?

I would like to migrate a web app to desktop, but using Vuetify 2.1.0.

**Comment by bh90210** [comment]
hi @ljjimenez 
I am sure it is possible! I am looking into vuetify and seems there are many ways to approach it.
from the point of view of Wails though, what u need to do 3 things:
1. Make sure you load all images, fints like this https://github.com/wailsapp/wails/blob/daeda501f448cb3896f07d1716c7c7daf662c2ef/cmd/templates/vuetify-basic/frontend/vue.config.js#L13 
2. make sure to only produce one `.js` file https://github.com/wailsapp/wails/blob/daeda501f448cb3896f07d1716c7c7daf662c2ef/cmd/templates/vuetify-basic/frontend/vue.config.js#L31
3. and finnaly make sure to only produce one `.css` file https://github.com/wailsapp/wails/blob/daeda501f448cb3896f07d1716c7c7daf662c2ef/cmd/templates/vuetify-basic/frontend/vue.config.js#L4

if need help please share your repo (if not private) so we can take a look at your code :)

**Comment by leaanthony** [comment]
Hi. We had a [ticket](https://github.com/wailsapp/wails/issues/226) for this that went stale. I don't think Michael responded for quite a while so it went stale. If you are able to pick this up and make a PR, we will look at it :+1:

**Comment by Lyimmi** [comment]
One of my projects is made with vuetify 2.x, but it does not work on windows (MSHTML/Webview isse). I have a few ideas how to make it work, but didn't have any motivation to do so.

I can make a PR, based on that project, if needed.
In the ticket that @leaanthony mentioned there are two alternatives, I would go with the second one to make two separate Vuetify templates.

But if you guys think it's ok to update the existing one is good for me too.

**Comment by bh90210** [comment]
hey @Lyimmi amazing! A new Vue 2.x template sounds fine.

Let's ask @MichaelHipp (https://github.com/MichaelHipp/wails/tree/vuetify2-support) if he has made any progress, to possible avoid double coding the same thing..

**Comment by leaanthony** [comment]
A PR would be awesome! I'd go for just updating the current template if
everyone is upgrading. But if it's kinda like Python then maybe a new
template?

**Comment by MichaelHipp** [comment]
I haven't looked at it since 10/2 when I was told we were going into a feature freeze for v1.0. I still have it and doubt 2.1 would be much different than 2.0.

**Comment by leaanthony** [comment]
Hey @MichaelHipp. Looking through the comments on the ticket, it looked like you were still working on it. Is the PR good?
