### ISSUE TITLE
Go 1.21.0 go mod changes break wails run/build

### ISSUE THREAD

**Issue by AlexBitsTech** [wailsapp/wails#2875]
### Description

With Go version 1.21.0, Golang made changes to the version displayed in go mod. It now displays 1.21.0 instead of 1.21. When I run wails dev I get this error: `:3: invalid go version '1.21.0': must match format 1.23`.

### To Reproduce

1. Update to go 1.21.0
2. Run go mod tidy
3. Run wails dev

### Expected behaviour

For wails dev to work.

### Attempted Fixes

Manually setting the Go version to 1.21 in the go mod file makes wails dev work once. Since wails dev runs go mod tidy, the version is changed again.

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 116.0.1938.62
Nodejs     | N/A          | Installed | 18.17.1
npm        | N/A          | Installed | 9.6.7
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

Nice catch 👍 , I'm just working on a PR to fix this.

**Comment by stffabi** [comment]
PR #2876 is up with a fix.
