### ISSUE TITLE
Is tailwind not supported?

### ISSUE THREAD

**Issue by furkangkhsn** [wailsapp/wails#288]
I have a vue+vuetify app with tailwind css. I use vuetify for some components and tailwind for the rest. But with wails, tailwind not working. Should i do something else? or not use it? Everything is working except tailwind.

**Comment by leaanthony** [comment]
Hi. I've never used tailwind. According to the docs it should work, but
note that if you're on windows you won't be able to some things:
https://tailwindcss.com/docs/browser-support

**Comment by furkangkhsn** [comment]
Ok i found it. package.json file generated by wails includes postcss section which overwrites the postcss file.

**Comment by Failip420** [comment]
Hello I got tailwind to work but things as @apply doesn't work?

**Comment by red-co** [comment]
I wasted two hours by this problem. Here I give the solution.
```shell
yarn add tailwindcss
yarn add utoprefixer postcss
```
you need have tailwindcss file and postcss file,
---
This works, but I don't know why
