### ISSUE TITLE
Use CEF for the front web engine

### ISSUE THREAD

**Issue by liuxgo** [wailsapp/wails#2886]
### Is your feature request related to a problem? Please describe.

Webkit2gtk is slow and lacks many features (such as WebRTC) on raspberry pi. 

### Describe the solution you'd like

Can you give a option of use CEF instead of webkit2gtk on linux?

**Comment by leaanthony** [comment]
If you want to make a PR for that, I'd happily accept it

**Comment by marcio199226** [comment]
@liuxgo @leaanthony  do you know any other go bindings for cef besided these https://github.com/Gurkengewuerz/cefgo or https://github.com/cztomczak/cef2go

We can give it a try. I'm also missing webrtc support on unix based systems

**Comment by leaanthony** [comment]
I don't sorry

**Comment by liuxgo** [comment]
@marcio199226 sorry, I don't. Thanks for your information really.

**Comment by zhaojunliing** [comment]
https://github.com/asticode/go-astilectron

**Comment by leaanthony** [comment]
We're moving to webkit2gtk v4 for Wails3. Should fix a number of concerns.

**Comment by gedw99** [comment]
https://github.com/energye might be a useful resource for CEF and related things.
