### ISSUE TITLE
Error on `wails init`

### ISSUE THREAD

**Issue by furkangkhsn** [wailsapp/wails#289]
[2019-11-17T17_11_10_741Z-debug.log](https://github.com/wailsapp/wails/files/3855867/2019-11-17T17_11_10_741Z-debug.log)
I got an error message while trying to initialize a new vue project. I attached the error log.

**Comment by leaanthony** [comment]
Please file the issue using `wails issue`. Thank you.

**Comment by furkangkhsn** [comment]
I think if you make the npm process during initialization on the terminal, it will be much more satisfying. Right now, it feels like it is stuck at building project.
