### ISSUE TITLE
CPU usage reaching 30-35%

### ISSUE THREAD

**Issue by salman0ansari** [wailsapp/wails#2894]
### Description

there is a component whenever it renders CPU usage gets 30-35%
the component does not contain any code logic its a simple html table with some css

### To Reproduce

A React component with simple HTML table with 10 rows.

### Expected behaviour

cpu usage should not reach that high

### Screenshots

![image](https://github.com/wailsapp/wails/assets/30106022/6fb95711-c58e-4740-beff-34c87d528fc1)

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.tem - Please wait (this may take a long time)... (1s)

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.5
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 116.0.1938.69
Nodejs     | N/A          | Installed | 20.3.1
npm        | N/A          | Installed | 9.6.7
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.09
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

might be related
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3111

**Comment by leaanthony** [comment]
Thanks for opening this. Not sure what we can do other than track the upstream bug.

**Comment by salman0ansari** [comment]
> Thanks for opening this. Not sure what we can do other than track the upstream bug.

 there's nothing we can do except waiting them to fix it?

**Comment by leaanthony** [comment]
What do you suggest we do? I'm open to ideas.

**Comment by vikramparihar** [comment]
Seems GPU graphics processing unit. Taking too much uses. 

As I can see you uave used react for table rendering. Will you share your react snippets here for table .

Have you used any use effect or some thing else which refreshing your ui. Frequently.

**Comment by salman0ansari** [comment]
> Seems GPU graphics processing unit. Taking too much uses.
> 
> As I can see you have used react for table rendering. Will you share your react snippets here for table .
> 
> Have you used any use effect or some thing else which refreshing your ui. Frequently.

https://gist.github.com/salman0ansari/300caef8977040e7c662e933f27a4f26#file-table-tsx

**Comment by vikramparihar** [comment]
@salman0ansari  Will you please also share the screens shot of GPU uses before table render on UI. So i will be sure GPU consumption not going high due to only HTML rendering.

**Comment by salman0ansari** [comment]
> @salman0ansari Will you please also share the screens shot of GPU uses before table render on UI. So i will be sure GPU consumption not going high due to only HTML rendering.

I am currently unable to replicate this issue. Although the code for the table component remains unchanged, I have built a new executable, and it appears that the issue has been resolved.

**Comment by vikramparihar** [comment]
Thank you for updates. So we can considered this ticket as closed.
Could you please mark this ticket as resolved as of now.
