### ISSUE TITLE
Change the website favicon to the Red Dragon face

### ISSUE THREAD

**Issue by lil5** [wailsapp/wails#2907]
### Is your feature request related to a problem? Please describe.

The current favicon has no obvious design connection to the logo shown in the website.

### Describe the solution you'd like

Something like this: 

![Screenshot 2023-09-14 at 09 45 18](https://github.com/wailsapp/wails/assets/17646836/02203e97-3a6b-4b99-8a0b-015978451aac)

You can use this tool to generate the favicon from this image if you like
https://realfavicongenerator.net/

### Describe alternatives you've considered

Make the W red

**Comment by leaanthony** [comment]
I tried that and it looked like crap quite honestly 😅 if you're able to make one that looks half decent at 32x32 then feel free to open a PR 👍

**Comment by PylotLight** [comment]
imo the straight generated one using above tool looks aight to me.
![image](https://github.com/wailsapp/wails/assets/7006124/e2551314-9053-4714-ace3-00878a4ab6c4)

**Comment by leaanthony** [comment]
done! Should be deployed in the next 10 mins
