### ISSUE TITLE
WebView2 installation succeeded, but the wails doctor command shows that it is not installed

### ISSUE THREAD

**Issue by sclang007** [wailsapp/wails#2917]
### Description

WebView2 runtime, after successful installation, the 'wails doctor' command displays' Available '

### To Reproduce

Wails did not provide specific feedback on the reason

### Expected behaviour

The result should be Installed

### Screenshots

![1](https://github.com/wailsapp/wails/assets/46955708/9457e0e7-cd0d-412d-9086-c9babce025e3)
![2](https://github.com/wailsapp/wails/assets/46955708/b27815fc-f1f7-47fe-8f92-dfce0ef017ed)

### System Details

```shell
DEB | Using go webview2loader


          Wails Doctor



# Wails
Version | v2.6.0

# System
┌────────────────────────────────────────────────┐
| OS           | Windows 10 Pro for Workstations |
| Version      | 2009 (Build: 19044)             |
| ID           | 21H2                            |
| Go Version   | go1.21.1                        |
| Platform     | windows                         |
| Architecture | amd64                           |
└────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version |
| WebView2   | N/A          | Available |         |
| Nodejs     | N/A          | Installed | 18.17.1 |
| npm        | N/A          | Installed | 9.6.7   |
| *upx       | N/A          | Available |         |
| *nsis      | N/A          | Available |         |
└──────────── * - Optional Dependency ────────────┘

# Diagnosis
Required package(s) installation details:
  - WebView2 : Available at https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 WARNING  Your system has missing dependencies!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Installed as admin or user?

**Comment by stffabi** [comment]
I saw cases where the wrong architecture was being installed, e.g. x86 only on amd64. The installation of the runtime succeeds but it can't be used because arch is wrong. So maybe that's something to be checked in your case.

**Comment by sclang007** [comment]
Thank you! It has been resolved and the amd64 version of WebView2 has been re downloaded. It now displays Installed
![2](https://github.com/wailsapp/wails/assets/46955708/1fc6c694-a51e-4b94-908a-5ca897557c69)
![1](https://github.com/wailsapp/wails/assets/46955708/588c535e-8cb7-42cf-9f17-30cc3eaeb41a)

**Comment by stffabi** [comment]
Great that you could solve this issue. We could probably try to give some more information in Wails doctor and detect e.g. inconsistent installed architectures.

I'm going to close this issue, feel free to reopen it if you see any further problem with WebView2 detection.
