### ISSUE TITLE
Usage of file:// Urls

### ISSUE THREAD

**Issue by fbrinker** [wailsapp/wails#292]
Hello,

I'm trying to show image thumbnails of files in a selected directory, but embedding the image via `file://path` does throw the following error:
```
CONSOLE ERROR Not allowed to load local resource
```

So the browser disallows that access due to security reasons. Is it possible to disable that security policy, like in Electron?
* See https://stackoverflow.com/questions/58385872/not-allowed-to-load-local-resource-with-file-image-url-in-electron-app
* They set `webSecurity` to `false`

Or is there any other way to solve that? I would love to embed the original files (or created thumbnails in /tmp/) in the frontend. 

At the moment I'm thinking of reading and encoding the files with base64 and sending them inline via HTML, but that seems to be an overhead... :)

**Comment by bh90210** [comment]
hi @fbrinker I am not aware of a way to turn security off, maybe @leaanthony can weight in on this. If there is a way that'd be amazing though.

when I was confronted with a similar issue, I needed a simple drag'n'drop, I indeed []byte (base64) everything and send it to back. https://github.com/bh90210/wails-tutorial/blob/master/client/frontend/src/components/Drop.js#L42

maybe there should be a proposed way to solve similar issues? a guide or tutorial?

**Comment by leaanthony** [comment]
Yeah, it would be good if this was part of the runtime. I'll add it to the list.

**Comment by leaanthony** [comment]
If it does not need to be dynamic, then it should just be webpacked in the bundle.

**Comment by fbrinker** [comment]
Absolutely! 

But in my case I am trying to write something like an local Image Browser. Right now I'm scanning a source directory for images, create their thumbnails and save the base64 blob into a temporary database to load them into the UI afterwards.

Works so far but seems to be far slower / resource hungry when loading the page than using file urls would be and is some sort of workaround.

Loading 1k images in one page with their base64 blob takes ~15s, so it is okay in my case. I've already optimized the base64 blob site with using webp thumbnails instead of jpeg and load every image event based, so there is no latency time

**Comment by leaanthony** [comment]
What platform is this for?

**Comment by fbrinker** [comment]
Currently I'm planning Linux and Windows, but OSX would be nice too (but it should be similar to Linux, because its using Webkit too?). My plan is to create a cross-platform application to import and organize images "semi-automatically"

**Comment by leaanthony** [comment]
That's a cool sounding project. I've found a workaround for Linux but not
tested it yet. It mah need to wait until v1 is out mind.

**Comment by fbrinker** [comment]
There's no rush Thanks for already looking into this. :)

I'm fine with my solution right now, even if it's an overhead with the base64 data. Nevertheless, it would be a nice optimization at the end, but it's no showstopper

**Comment by leaanthony** [comment]
OK cool. All I did was do a Google search on Gtk WebKit local file URLs and
found a SO post showing how to enable the feature. If you get time, a
similar search for the windows and Mac equivalents would be good 😃

**Comment by leaanthony** [comment]
I'll be adding this feature, so reopening

**Comment by leaanthony** [comment]
I think this is actually impossible. We load the main html via a data-uri and it seems you can only allow access to `file://` urls if you loaded via a `file://` url. 

Have you done any further research around this? I'd rather not dump the html to disk and then load it off disk to enable this feature.

**Comment by leaanthony** [comment]
Been thinking. We *could* have a method on the runtime called `LoadFile` which returned back a base64 string. We could intercept that at the C layer and do the file I/O there. It wouldn't need to come back to Go.

**Comment by leaanthony** [comment]
@fbrinker please let us know if you are still interested in this. If it's not urgent, I'm going to put it on hold for a while and see if anything transpires in the webkit libraries.

**Comment by fbrinker** [comment]
Thanks for looking into this :)

It's not urgent, since I've worked around it for now, so I'm fine with putting this on hold for a while :+1:

**Comment by leaanthony** [comment]
Am going to defer this to Wails v2. We won't forget.

**Comment by dzpt** [comment]
and the final solution for this?
I'm using v2 and still can't display local img

**Comment by stffabi** [comment]
> and the final solution for this? I'm using v2 and still can't display local img

@dzpt you can achieve this by using the new [options.AssetsHandler](https://wails.io/docs/reference/options/#assetshandler). There's also a little guide how to use them for [Dynamic Assets](https://wails.io/docs/guides/dynamic-assets).
