### ISSUE TITLE
Enable HiDPI on Windows (looks blurry)

### ISSUE THREAD

**Issue by JackMordaunt** [wailsapp/wails#293]
**Description**

Blurry window for high resolutions, eg 4k.
I searched around in case this was already addressed and couldn't find anything. 

**To Reproduce**

1. High DPI screen + Windows.
2. Build and Run the demo.

**Expected behaviour**

Should not be blurry.

**Screenshots**

<img width="598" alt="wails-blurry" src="https://user-images.githubusercontent.com/6916093/69490274-03f8e200-0eea-11ea-86b6-320d97f4e5e2.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.19.0 |
| Go Version    | go1.13.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 6.13.1 |
| Node          | v13.2.0 |

**Comment by leaanthony** [comment]
Hey @JackMordaunt. Firstly, thanks for the icns library 👍 
Regarding HiDPI, this has been pretty tricky. The guide I used is [here](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v%3Dvs.85)) and the manifest file that gets used is [here](https://github.com/wailsapp/wails/blob/develop/cmd/packages/windows/wails.exe.manifest). 
If you make a copy of the manifest and call it <basename>.exe.manifest, where <basename> is your app name (sans .exe), then it will use it during compilation. Maybe it just needs to use 'system' but I'm not sure how that would affect multi-monitor setups.

**Comment by JackMordaunt** [comment]
Yes, I was afraid of needing to directly mess with manifest files!

After viewing the docs, I tried the api method and it works great on a single monitor setup.

```go
syscall.NewLazyDLL("user32.dll").NewProc("SetProcessDPIAware").Call()
``` 

If I understood correctly, the reason this method is *not* recommended is because it doesn't handle *changes* in DPI: if you have multiple monitors with different resolutions, Windows will use "bitmap scaling" which produces a blurry result when moving from lower to higher DPI. I'm assuming higher-to-lower DPI would be fine since it's just downscaling. 

For reference, here's what I ended up with: 

```go
// main_windows.go
package main

import (
	"fmt"
	"log"
	"syscall"
)

func init() {
	if err := SetProcessDPIAware(); err != nil {
		log.Printf("setting process dpi aware: %v", err)
	}
}

// SetProcessDPIAware via user32.dll
// https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware
func SetProcessDPIAware() error {
	status, r, err := syscall.NewLazyDLL("user32.dll").NewProc("SetProcessDPIAware").Call()
	if status == 0 {
		return fmt.Errorf("exit status %d: %v %v", status, r, err)
	}
	return nil
}

```

**Comment by leaanthony** [comment]
Hi @JackMordaunt - absolutely! I would love to know how this affects other setups mind.

**Comment by leaanthony** [comment]
I've added in the change to the latest pre-release. Grab it with `wails update -pre`.
It looks great on my system! Thanks for spending time on this! Added you to the contributor list 👍

**Comment by JackMordaunt** [comment]
That’s great! 

Since I don’t have the manifest setup, I’m not sure how the api interacts with it. 

Hopefully the manifest takes precedence!

I might try an awkward monitor setup 4K + 1080p with and without manifest file to confirm. 

In any case, glad I could help :)

**Comment by leaanthony** [comment]
Thanks Jack!

There's a stock manifest that gets copied to the project directory and
compiled in. If you are uqick, you can see it. There used to be a flag that
kept those files lying around so you could edit them, in much the same way
as the icon. If that's been removed I may add it back as I think that would
help debug.

Thanks for your help on this issue, the builds look great now 😃

**Comment by leaanthony** [comment]
Looking at the code, it *should* keep the files lying around if you build like this: `wails build -d -p`.
