### ISSUE TITLE
how to use vue-router and How to jump to the page

### ISSUE THREAD

**Issue by yirenyishi** [wailsapp/wails#294]
how to use vue-router and How to jump to the page

**Comment by leaanthony** [comment]
Hi. This has been covered before [here](https://github.com/wailsapp/wails/issues/236) and [here](https://github.com/wailsapp/wails/issues/150). Feel free to create a PR for the docs on how to use it.

**Comment by leaanthony** [comment]
Hi. Does [this answer](https://github.com/wailsapp/wails/issues/295#issuecomment-558128731) fix it for you?
