### ISSUE TITLE
'Undefined "wails"' Error when using with vue-router

### ISSUE THREAD

**Issue by furkangkhsn** [wailsapp/wails#295]
**Description**

After adding router to the project, the builded executable not working. The Error says 'Undefined "wails"'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'wails init'
2. Select 'vue/webpack template'
3. Run 'cd project_folder/frontend'
4. Run 'vue add router'
5. Select 'no history mode'
5. Run 'cd ..'
6. Build project with 'wails build'
7. Run the executable

**Expected behaviour**
Runs without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/23143160/69538803-27786700-0f94-11ea-98bf-3085ad515630.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.19.0-pre2 |
| Go Version    | go1.13.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.12.0 |
| Node          | v12.13.0
 |

**Additional context**
Setup has vue, vuex, vuetify and vue-router.

**Comment by furkangkhsn** [comment]
Edit: It seems to work If you use "abstract" as the routing mode.

**Comment by leaanthony** [comment]
Hi! Thanks for investigating this. There are a number of people who will
benefit from this.

**Comment by leaanthony** [comment]
We are desperate for a quick tutorial on vue/vue-router/vuex, so if you find the time for a short tutorial, we would love to add that to the docs.

**Comment by Splode** [comment]
> 
> 
> We are desperate for a quick tutorial on vue/vue-router/vuex, so if you find the time for a short tutorial, we would love to add that to the docs.

I ran into this issue when referencing the [Vue Router guide](https://wails.app/guides/vuerouter/). Nevertheless, I did successfully set up Vue Router and Vuex.

@leaanthony Is there still a desire for updated documentation?

**Comment by leaanthony** [comment]
If you have time, that would be perfect. Let me know if you need a hand with that. :+1:
