### ISSUE TITLE
add a pure JavaScript and TypeScript official templates

### ISSUE THREAD

**Issue by devhindo** [wailsapp/wails#2956]
### Is your feature request related to a problem? Please describe.

I think a clean starter template has more priority than the famous frameworks available templates. cause we all want a clean minimalist starter and also in simple projects

### Describe the solution you'd like

 a pure `index.html`, `style.css` and `script.js` template would be cool. Also another one for TypeScript that has `tsconfig.json` file would be cooler

### Describe alternatives you've considered

the community templates weren't that useful. and as I said a pure template was required at the beginning before thinking of the frameworks

**Comment by leaanthony** [comment]
Hi. Is there anything that's stopping you from doing this? There's no requirement to use anything in a template. Just put your plain HTML/CSS/JS in your dist directory and you should be good.
