### ISSUE TITLE
"SecurityError" When Trying to Use with WebSockets

### ISSUE THREAD

**Issue by furkangkhsn** [wailsapp/wails#296]
**Description**

I try to use Apollo Graphql with wails. But after build, it gives SecurityError. It works on ie11 and Edge. Windows restrict socket connections to 8 per host. But I edited the registery and still throws SecurityError.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'wails init'
2. Select 'vue/webpack template'
3. Install Apollo GraphQL extension for vue.
4. Install necessary polyfills. (Babel, ES6Polyfills, corejs object and array polyfills.)
5. Build the project.
6. Run the executable.

**Expected behaviour**
Not throws an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/23143160/69614578-6108ab00-1044-11ea-8ea0-f92f471a7bad.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.19.0-pre2 |
| Go Version    | go1.13.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.12.0 |
| Node          | v12.13.0 |

**Comment by leaanthony** [comment]
Hi! Thanks for your persistence with the Windows builds. It is by far the
weakest in terms of what mshtml supports. I've spent some time creating a
global error handler which I'm hoping will report errors better as well as
a console I've hacked together. I'll look at getting a prerelease out with
those 2 additions in the hope that'll help you further debug the issue.
Thanks again for your support 👍

**Comment by leaanthony** [comment]
Hi @furkangkhsn - I've added the console to the latest build. It may or may not help you as it is really basic. If you update to v0.20.0-pre1 using `wails update -pre` you can activate the console using shift-ESC on any debug build.

**Comment by leaanthony** [comment]
I've just tested the instructions [here](https://deskgap.com/devtools/) and they allow remote debugging on Windows.

- Install a recent version of Visual Studio (The free “Community” Edition is fine. The following steps are based on VS 2017). Make sure the “ASP.NET and web development” workload is selected in the installer;

- Open Debug -> Attach to Process...;

- Click Select... and choose Debug there code types: -> Script

- Find and select the process of your DeskGap application in Available Pocesses;

- Click Attach. The DOM Explorer and JavaSript Console should now show up. If not, open them in Debug -> Windows.

**Comment by furkangkhsn** [comment]
The error is related to mshtml. Is there a way to change the engine? Maybe wails will try to find the installed version of chrome? Then run the webview on that? Or use a different engine like ultralight or salvo?

**Comment by leaanthony** [comment]
Not possible at the moment, but I will be working with another project on
bringing the Edge rendering engine into Wails. The code exists, we just
need to create a Go bridge.
