### ISSUE TITLE
Virustotal false positive detection

### ISSUE THREAD

**Issue by benjiewheeler** [wailsapp/wails#2965]
### Description

Some of the detection vendors on VirusTotal flag executables produced by wails as positive for having malware, even a vanilla project.

[Sample VT report](https://www.virustotal.com/gui/file/48fc705ebad51972e5f30f797e3be17aaff67a002e4144d1007821ebe9329f04/detection)

### To Reproduce

1. Init a new project `wails init -n virustest`
2. build the project `wails build --platform windows/amd64 -clean -trimpath -upx`
3. Upload to VirusTotal

### Expected behaviour

This shouldn't be flagged as potential malware, especially if it's aan empty project that does absolutely nothing, some users will not accept a software that is detected as malware even if it's a false positive of just 1 or 2 detections among 70 different detectors (used by VT)

### Screenshots

![VirusTotal report](https://github.com/wailsapp/wails/assets/47009136/ea37108d-88d8-4fd6-82ff-d41d36ee2c46)

### Attempted Fixes

Not sure if this is something that can be fixed on Wails itself, or will it require contacting VT (or the antivirus vendors they use) to get to the root cause of this.

Regardless I thought to bring this into your attention.

### System Details

```shell
# Wails
Version         | v2.6.0
Package Manager | apt

# System
(Zorin OS is just a flavor of Ubuntu)
┌─────────────────────────┐
| OS           | Zorin OS |
| Version      | 16       |
| ID           | zorin    |
| Go Version   | go1.20.7 |
| Platform     | linux    |
| Architecture | amd64    |
└─────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 24.0.6                  |
| gcc        | build-essential       | Installed | 12.8ubuntu1             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.18-1ubuntu1        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.20.04.1 |
| npm        | npm                   | Installed | 9.6.7                   |
| *nsis      | nsis                  | Available | 3.05-2                  |
| pkg-config | pkg-config            | Installed | 0.29.1                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘
```

**Comment by leaanthony** [comment]
Thanks for bringing his up. It's a situation a lot of Go projects have as, unfortunately, Go is a great language for malware. Obviously there's nothing we can do on our side and we hope people file reports back to vendors when they encounter the issue. Thanks again.

**Comment by stffabi** [comment]
I think we can close this, as there's nothing we can do about that on our side and this is an Go ecosystem problem.
