### ISSUE TITLE
HTTP-Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by aa0mia0aa** [wailsapp/wails#2966]
### Description

if i start hatt on window10 i get this error: HTTP-Error 500.19 - Internal Server Error
url: [http://wails.localhost:80/](http://wails.localhost/)
Modul: IIS Web Core
errorcode: 0x80070003
configuration-file could not be read
configuration-file: \?\C:\inetpub\wwwroot\web.config

### To Reproduce

Start the hatt-windows-amd64.exe or hatt.exe

### Expected behaviour

Normal Program start

### System Details

```shell
Windows 10 Build 19045.3516 64bit
```

**Comment by leaanthony** [comment]
I'm not sure what this has to do with Wails. Feel free to reopen if you can show a reproducible example.

**Comment by FrenchGithubUser** [comment]
It is a reference to this : https://github.com/FrenchGithubUser/Hatt/issues/27

But indeed, it needs to be reproducible

**Comment by leaanthony** [comment]
Wails has nothing to do with IIS so I'm not sure how it's relevant.

**Comment by FrenchGithubUser** [comment]
I'm not very familiar with IIS, but would that mean it looks like an issue on the user's machine rather than the program itself ?

**Comment by leaanthony** [comment]
There is nothing in the description that suggests it's anything to do with this project.
