### ISSUE TITLE
iframe close cross-doamin

### ISSUE THREAD

**Issue by duanshuiliu** [wailsapp/wails#2968]
### Is your feature request related to a problem? Please describe.

I want to use an existing website in iframe. However, cookies cannot be stored in iframe, because they cross domains. Can you add a parameter to disable the cross domain feature of iframe

### Describe the solution you'd like

I find similar property settings already exist in CoreWebView2Frame (Webview2 api)

**Comment by duanshuiliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by duanshuiliu** [comment]
I think it should be this in windows:
CoreWebView2Frame Class   
PermissionRequested.

In linux/mac, I don`t know

**Comment by leaanthony** [comment]
Moving all cookie related discussions to #3908

**Comment by duanshuiliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
