### ISSUE TITLE
Nothing is showed up for template project on armv8/ubuntu

### ISSUE THREAD

**Issue by dylanadv** [wailsapp/wails#2975]
### Description

An empty screen is displayed when I launch the template project. But it is normal to open http://localhost:34115 with browser.

### To Reproduce

0 : on armv8/ubuntu 18.04
1 : wails init
2 : wails build
3 : an empty screen

### Expected behaviour

Default template screen

### Screenshots

[https://drive.google.com/file/d/1T7allywXEN9_GsipweLiDaObpBuFLcH6/view](url)

### System Details

```shell
1 : armv8/ubuntu 18.04
2 : Wails : V2.6.0
3 : node : V18.18.0
4 : npm : 9.8.1
5 : go : go1.18.10 linux/arm64
```

**Comment by infinitebugs32** [comment]
I suggest you try the solution provided by @leaanthony  in #2977

**Comment by dylanadv** [comment]
I executed it on a 20.04 machine and got the same result without any web screen.
Is it related to the webkit package? I saw someone doing the transplantation of directfb+gtk+webkit on arm.[https://blog.csdn.net/weixin_42509964/article/details/116923546](url)

**Comment by leaanthony** [comment]
Yes, it does appear to be related to webkit2gtk

**Comment by dylanadv** [comment]
Update status: When I move the cursor on the blank black screen, I find that the cursor will change and the position is the textbox and button in the original web page. Does this further prove that it is a problem with the render screen or frame buffer of webkit?

**Comment by dylanadv** [comment]
does it render the screen with opengl only?

**Comment by leaanthony** [comment]
Try this: https://github.com/wailsapp/wails/issues/2977#issuecomment-1761765185

**Comment by dylanadv** [comment]
Thanks! It worked, I made the next command before executing it: export WEBKIT_DISABLE_COMPOSITING_MODE=1, my environment is ARMv8 Processor rev 1 (v8l) × 8/Ubuntu 20.04.6 LTS with: NVIDIA Tegra Orin (nvgpu)/integrated.
