### ISSUE TITLE
how to multiple select folder? i need this

### ISSUE THREAD

**Issue by plane55** [wailsapp/wails#2986]
### Describe the solution you'd like

how to multiple select folder

**Comment by leaanthony** [comment]
https://github.com/wailsapp/wails/pull/2960

**Comment by plane55** [comment]
怎么实现的呢？代码是什么？How to achieve it ? show achieve code

**Comment by plane55** [comment]
> #2960

i don't know how to achieve it ?

**Comment by leaanthony** [comment]
Duplicate of #2411

**Comment by plane55** [comment]
if don't have this select multiple folder I can't finish my application
