### ISSUE TITLE
Indefinite parameter error

### ISSUE THREAD

**Issue by hq-zhonger** [wailsapp/wails#2993]
### Description

ERR occurs when the vue3 front-end passes to the back-end... string type variable parameters | error parsing arguments: json: cannot unmarshal string into Go value of type []string

### To Reproduce

go
func Test(url string, test ...string) {
	if test != nil {
		gjson.Parse(test[0])
	}
}
vue3
 await Test((this.store.target || "").split('\n'),JSON.stringify(json))

### Expected behaviour

...string itself can pass string

### Screenshots

<img width="1120" alt="屏幕截图 2023-10-20 132118" src="https://github.com/wailsapp/wails/assets/78897251/677ae8bc-55dd-4acb-8f3a-20db4926be59">

### System Details

```shell
os : windows 11
go : 1.21.1
wails : 1.6.0
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this. 

Variadic arguments are currently not support and are a known limitation.

See also #1186 and [Cannot call backend method from frontend with variadic arguments](https://wails.io/docs/guides/troubleshooting#cannot-call-backend-method-from-frontend-with-variadic-arguments).

**Comment by stffabi** [comment]
Closing this as we don't support his for now.

**Comment by JaneX8** [comment]
This is still not supported?
