### ISSUE TITLE
dependencies are up to date...

### ISSUE THREAD

**Issue by siulfe** [wailsapp/wails#301]
**Description**

error while run wails init, throw: !ensuring dependencies are up to date

![Captura](https://user-images.githubusercontent.com/50551002/69769687-db742080-1153-11ea-8add-a817e030817a.PNG)

**Comment by leaanthony** [comment]
Can you please reopen this ticket using `wails issue` so we can see your environment? Thanks.

**Comment by bh90210** [comment]
#300 
hi @siulfe I think if you `wails update -pre` your problem will be fixed :)
