### ISSUE TITLE
安装完环境后，项目无法正常启动

### ISSUE THREAD

**Issue by liaosiqian** [wailsapp/wails#3015]
### Description

安装完环境后，项目无法正常启动

### To Reproduce

1、Run wails dev or  wails build
2、Wait for the build
3、See the error:

DEB | Using go webview2loader
Wails CLI v2.6.0

Executing: go mod tidy
  • Generating bindings: 
  ERROR   

          fork/exec C:\Users\ADMINI~1\AppData\Local\Temp\wailsbindings.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software 
publisher.

### Expected behaviour

Normal behavior

### Screenshots

![EK@DP5E}2RR%5LAQ6E1`HT2](https://github.com/wailsapp/wails/assets/15165772/37b820dc-801e-424f-98de-71334d723523)

### Attempted Fixes

安装过程有遇到一个问题：
一开始初始化wails，使用下面的命令 ，下载到的是一个 linux_amd64的 wails文件
go install github.com/wailsapp/wails/v2/cmd/wails@latest

后面替换成windows，才正常下载到了 wails.exe
GOOS=windows GOARCH=amd64 go install github.com/wailsapp/wails/v2/cmd/wails@latest

是否可能因为环境问题导致

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌────────────────────────────────────┐
| OS           | Windows 10 Pro      |
| Version      | 2009 (Build: 19045) |
| ID           | 22H2                |
| Go Version   | go1.21.1            |
| Platform     | windows             |
| Architecture | amd64               |
└────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 118.0.2088.76 |
| Nodejs     | N/A          | Installed | 16.13.0       |
| npm        | N/A          | Installed | 8.1.0         |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘
```

**Comment by leaanthony** [comment]
https://github.com/golang/go/issues/44817

**Comment by leaanthony** [comment]
是的，我认为这是环境问题。您是否尝试过检查"go env"的输出？

**Comment by liaosiqian** [comment]
> 是的，我认为这是环境问题。您是否尝试过检查"go env"的输出？

感谢回复，下面是 go环境的信息

set GO111MODULE=on
set GOARCH=amd64                                         
set GOPATH=C:\Users\Administrator\go
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:/Users/Administrator/sdk/go1.21.1
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\Administrator\sdk\go1.21.1\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\Administrator\GolandProjects\WorkHelper\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build2210219793=/tmp/go-build -gno-record-gcc-switches

我也有尝试使用本地的go环境编译， 但是还是碰到了相同的问题
