### ISSUE TITLE
implement modals/alert boxes in the frontend

### ISSUE THREAD

**Issue by riyanswat** [wailsapp/wails#3018]
### Is your feature request related to a problem? Please describe.

Wails currently lacks support for modal dialogs or alert boxes in its frontend. This limitation makes it difficult to provide critical user feedback or interact with users in certain scenarios.

### Describe the solution you'd like

Introduce support for modal dialogs or alert boxes in the frontend, allowing developers to create user-friendly, interactive interfaces seamlessly. This addition will enhance UX, imo.

**Comment by PylotLight** [comment]
I see this as a frontend responsibility thus not an issue for wails, as you have the freedom to implement your own solution for this. Wails is frontend agnostic, so what global solution would be provided here?
I implemented my own solution for this using chi + templ + htmx

**Comment by leaanthony** [comment]
Thanks for the suggestion. I agree with @PylotLight - we want to make sure that we are as flexible as possible so we'll pass on this at this time. If you have any further thoughts, feel free to let us know.

**Comment by riyanswat** [comment]
> I see this as a frontend responsibility thus not an issue for wails, as you have the freedom to implement your own solution for this. Wails is frontend agnostic, so what global solution would be provided here? I implemented my own solution for this using chi + templ + htmx

Ah... I see my post was vague. I'm new to Wails (and frontend technologies).. I did implement a modal in html/css but it just wouldn't show up on the desktop app

**Comment by PylotLight** [comment]
> Ah... I see my post was vague. I'm new to Wails (and frontend technologies).. I did implement a modal in html/css but it just wouldn't show up on the desktop app

Join us on the discord and we may be able to assist with your implementation.
