### ISSUE TITLE
[v2, mac] Could not create transparent window

### ISSUE THREAD

**Issue by icaliskanoglu** [wailsapp/wails#3036]
### Description

I am trying to create a transparent background application. It is working in linux and windows as expected but it is not transparent for macOS. Here is the configuration:

```	
	err = wails.Run(&options.App{
		Width:            512,
		Height:           512,
		BackgroundColour: &options.RGBA{R: 0, G: 0, B: 0, A: 0},
		Mac: &mac.Options{
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
		},
		Linux: &linux.Options{
			WindowIsTranslucent: true,
		},

		Frameless: true,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		OnStartup: app.startup,
		Bind: []interface{}{
			app,
		},
		AlwaysOnTop: true,
	})
```

### To Reproduce

1. wails init -n test -t react
2. cd test
3. open main.go 
4. add Mac Options to options.App 
5. wails dev

Mac Options: 		
```
Mac: &mac.Options{
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
		},
```

### Expected behaviour

Based on the [document](https://wails.io/docs/reference/options#webviewistransparent-1) , I am expecting the window should be transparent. 

### Screenshots

<img width="1022" alt="image" src="https://github.com/wailsapp/wails/assets/4953268/205aceb1-38e3-482a-adf2-4e78269aa067">

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.0     |
| ID           | 23A344   |
| Go Version   | go1.21.1 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version         |
| Xcode command line tools  | N/A          | Installed | 2399            |
| Nodejs                    | N/A          | Installed | 16.20.2         |
| npm                       | N/A          | Installed | 10.1.0          |
| *Xcode                    | N/A          | Installed | 15.0.1 (15A507) |
| *upx                      | N/A          | Available |                 |
| *nsis                     | N/A          | Available |                 |
└─────────────────────── * - Optional Dependency ────────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by oti-adjei** [comment]
Currently having the same issue. Translucent property not working on my mac.

**Comment by mazhan465** [comment]
I get same problem, and not know how to resolve

**Comment by FreakyTurtle** [comment]
The window is transparent, delete all the html and make sure the background colour isn't set, I'm guessing you might want to hide the titlebar as well

**Comment by leaanthony** [comment]
Yeah, I think this isn't a bug but an application issue. Closing this for now.

**Comment by huija** [comment]
> The window is transparent, delete all the html and make sure the background colour isn't set, I'm guessing you might want to hide the titlebar as well

it's not work for me [v2，win11]
![image](https://github.com/user-attachments/assets/18516a9b-6993-49ca-95f3-fa7a8f4ae905)
![image](https://github.com/user-attachments/assets/135260ff-e2ad-4e59-82fd-dc81228dd2af)
![image](https://github.com/user-attachments/assets/1bf126a4-810a-4239-afba-1f1756c98ea2)

**Comment by Rishabh-Hupr** [comment]
> The white screen problem has been solved. Adding the following parameters is feasible. ![image](https://github.com/user-attachments/assets/23b15ad0-5ae8-4538-8f43-44c6488f4dc0)

This is for windows, not for mac



Mine is still not working in mac using WebviewIsTransparent: true

**Comment by yuczzzzz** [comment]
When I set the WindowIsTranslucent option on macOS to false, I achieve a transparent window, allowing me to adjust the transparency simply by tweaking the background-color in CSS.
