### ISSUE TITLE
Translation: AccessServer Handler cannot upload files.

### ISSUE THREAD

**Issue by bogerj** [wailsapp/wails#3037]
### Description

I used the AccessServer's handler to receive requests from the frontend, but I found that the ContentLength of the received POST request is always 0, and there is no data in the body either.

前端通过 表单上传了一个文件，但是后台无法接受文件

### To Reproduce

 I created a form in the frontend to upload files, but the backend is not receiving the files.

前端通过 表单上传了一个文件，但是后台无法接受文件

### Expected behaviour

can upload file 

能上传文件

### Screenshots

![image](https://github.com/wailsapp/wails/assets/150119798/bdce0090-0d3c-41e3-b730-ececcf794626)

### System Details

```shell
# System                          
                                  
OS           | Windows 10 Pro     
Version      | 2009 (Build: 19045)
ID           | 22H2               
Go Version   | go1.20.1           
WebView2   | N/A          | Installed | 116.0.1938.76
Nodejs     | N/A          | Installed | 14.17.2
npm        | N/A          | Installed | 6.14.13
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by bogerj** [comment]
assetServer  config 

AssetServer: &assetserver.Options{
   Assets:     assets,
   Handler:    httpProxy.NewFileLoader(),
},

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

Unfortunately this is a WebView2 issue with multi-part POST data, and beyond our control. Please see the tracking issue on the webview2feeeback repo: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2162

**Comment by bogerj** [comment]
May I ask ， if there are any other ways to achieve the function of uploading files from web pages to specific interfaces

**Comment by leaanthony** [comment]
Use Go to do the job. We don't recommend using JS for anything other than view.

**Comment by bogerj** [comment]
谢谢，我明白了，我在尝试下其他方法
