### ISSUE TITLE
wails init with vanilla js as Default option

### ISSUE THREAD

**Issue by octavonu** [wailsapp/wails#304]
Hello Wailsapp,

Congratulations on your work and milestone. I think that this will be huge!

I am just learning the go lang. together with js/CSS/HTML, therefore do you think that would be possible to add a Default option to wails init with no framework behind? Just for plain js & HTML.

Thank you for your work

**Comment by leaanthony** [comment]
Hi there. This will be part of Wails v2.

**Comment by leaanthony** [comment]
Closing this as it won't be part of Wails V1, however it IS on the roadmap.

**Comment by bh90210** [comment]
#336
