### ISSUE TITLE
Additional file packaging

### ISSUE THREAD

**Issue by sgx-wb** [wailsapp/wails#3043]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I have a small problem, for example, I have some files that I need to use when my program is running, how can I build the files in exe?

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
How do you intend to use them? This might help: https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/. Wails doesn't offer anything special in this regard, it just uses embed. Good luck! 👍

**Comment by sgx-wb** [comment]
> How do you intend to use them? This might help: https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/. Wails doesn't offer anything special in this regard, it just uses embed. Good luck! 👍

![image](https://github.com/wailsapp/wails/assets/96750945/08f04b76-0c34-4a12-a2e5-f06c95cb11bf)
I'm sorry I'm a rookie in this respect. I want to call a unix file after building wails, but it keeps prompting the path problem and can't be executed. Is there any relevant code to refer to?

**Comment by afocus** [comment]
You need to extract the embedded files to a temporary directory and then execute them. Note the execution permissions

**Comment by almas1992** [comment]
You can try this package https://github.com/getlantern/byteexec . 
example here [command_darwin.go](https://github.com/getlantern/elevate/blob/main/command_darwin.go)
