### ISSUE TITLE
Javascript event data absent in backend

### ISSUE THREAD

**Issue by Pixdigit** [wailsapp/wails#305]
**Description**
Additional data added to events in javascript are not transported to backend.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone example project from https://gitlab.com/Pixdigit/wails-issue-demo
2. Start project either via wails serve or build
3. In main.js an event is emitted and logged to terminal in main.go
4. Output does not include any data

**Expected behaviour**
Data is transported to backend

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 7.4.0 |
| Npm           | 6.9.0 |
| Node          | v11.15.0 |

**Comment by leaanthony** [comment]
Thanks for opening this. We know this works so there must be something up
with this configuration. Have you tried maintaining a reference to runtime?
That's all I can think of off the top of my head.

**Comment by leaanthony** [comment]
Found the bug. Fix incoming...

**Comment by leaanthony** [comment]
The runtime package has been updated to v1.0.10. This should fix the issue. If ou just recompile your project, it should pick up the fix. Let us know. :+1:

**Comment by Pixdigit** [comment]
Works now. Thank you
