### ISSUE TITLE
use dlv debug go backend

### ISSUE THREAD

**Issue by jan-bar** [wailsapp/wails#3050]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

To debug the frontend at runtime I add a `debugger` to the code

But I found that it is troublesome to debug the go backend besides adding logs in the code, so I studied a solution

1. run `wails dev` 
2. Find the `pid` of the running program, I found the pid via `tasklist | findstr myproject`
3. Start dlv debugging function: run `dlv --listen=:2345 --headless=true --api-version=2 --check-go-version=false --only-same-user=false attach $pid` 
4. Configure vscode `.vscode/launch.json`
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "debug golang",
      "type": "go",
      "debugAdapter": "legacy",
      "request": "attach",
      "mode": "remote",
      "port": 2345,
      "host": "127.0.0.1",
    }
   ]
}
```

5. Debugging with vscode breakpoints
![GIF 2023-11-11-星期六 14-46-53](https://github.com/wailsapp/wails/assets/14202095/c1821d2b-025b-4574-bb00-cf534efe15e3)

7. Create goland debugging configuration，Then start dlv and run debugging in goland
![image](https://github.com/wailsapp/wails/assets/14202095/7aaf4c5e-6cad-47ca-ba35-bfff90d4fd09)

![GIF 2023-11-11-星期六 14-50-49](https://github.com/wailsapp/wails/assets/14202095/2d16118f-0b52-48ab-8092-7bd0dd648c6b)

I didn't find any relevant articles in the official documents. It would be great if this method was added to the official documents so that more people can debug the code more quickly and conveniently.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by FriscPlusPlus** [comment]
I improved what you did to automate it: https://gist.github.com/FriscPlusPlus/66abadcc451e77fde9b9cf359276f05b now it's a matter of just pressing a button!

**Comment by ElPandos** [comment]
@FirasSharp can you share it again? your gist is 404

**Comment by FirasSharp** [comment]
> [@FirasSharp](https://github.com/FirasSharp) can you share it again? your gist is 404

Sure, [here](https://gist.github.com/FirasSharp/66abadcc451e77fde9b9cf359276f05b)! I forgot to say that it is windows only, but it can be used for other OS, just remove the .exe

**Comment by ElPandos** [comment]
Works like a charm :)
I missed the **problemMatcher** part in my own attempts to get it running...

Running in a go devcontainer so i had to install: python3, python3-psutil
