### ISSUE TITLE
ui and web page co-compile selection

### ISSUE THREAD

**Issue by hq-zhonger** [wailsapp/wails#3051]
### Is your feature request related to a problem? Please describe.

Hello on windows native ui interface on linux without ui want to run with web interface to achieve flexible effect I noticed that wail dev stage has the port 34115 as web interface access when I after wails build this port disappeared save dev build See devtools' local unterminated port View wails command line build document Try -devserver "host:port" invalid Is there a compilation method for wails that preserves the ui interface and web interface co-existing

### Describe the solution you'd like

web interface and ui interface coexist

### Describe alternatives you've considered

wails build -mode web,ui . -devserver "0.0.0.0:34115"

**Comment by leaanthony** [comment]
I'm sorry. I'm not sure I fully understand your request.

**Comment by hq-zhonger** [comment]
I hope that wails can coexist as desktop application and web application. For example, when using wails dev to build an application, it can be used as a desktop application, or it can be operated as a web application at wails.localhost:34115. This greatly enhances the flexibility of wails. I can write desktop applications and web applications at the same time. For example, if I am on the Windows platform, I want to run the desktop application graphically. On the terminal Linux server, I can also run the wails program as a web program. But I formally build the program in wails build. After that, the 35115 port will disappear. Can you add new compilation options, retain the web 34115 port, and disable dev debugging. Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wailsapp/wails"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月12日(星期天) 上午8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wailsapp/wails] ui and web page co-compile selection (Issue #3051)





 
I'm sorry. I'm not sure I fully understand your request.

**Comment by leaanthony** [comment]
There will be a server plugin for v3 so yes, we are doing this 👍 Closing this as it's already being tracked.
