### ISSUE TITLE
command not found: wails

### ISSUE THREAD

**Issue by Kline-x** [wailsapp/wails#307]
command not found: wails

**Comment by bh90210** [comment]
hello there,

when you installed `wails` did you have `GO111MODULE=on`?

ie `GO111MODULE=on go get -u github.com/wailsapp/wails/cmd/wails`

**Comment by tmclane** [comment]
Also make sure you have the directory where the binary is placed in your `PATH`.

**Comment by incafox** [comment]
same "bug" here, i tried to install wails on my existing go project directory and nothing happend, pls help

**Comment by incafox** [comment]
i clearly read the instructions, was my foult, everything is okay

**Comment by leaanthony** [comment]
Closing this ticket due to inactivity.

**Comment by dm-grinko** [comment]
Should I add PATH like this:
export PATH="$PATH:~/go/bin"
?
it's not working

**Comment by renozion** [comment]
same issue here friends, i installed go get github.com/wailsapp/wails/cmd/wails did everything on export and still cannot run command wails build on directory needed :(

**Comment by prosperoking** [comment]
Same, the wails cli is not working

**Comment by tmclane** [comment]
Did you ensure that your GOPATH/bin is part of the PATH in your environment?  You can google how to set it for each OS.

**Comment by tmclane** [comment]
Can you 'go install' anything and have it work as a command no matter where in the file system your prompt is located?

**Comment by prosperoking** [comment]
Thanks for the hint. I added the gopath to my pah

**Comment by prosperoking** [comment]
works now
