### ISSUE TITLE
failed to init GTK

### ISSUE THREAD

**Issue by qq446887609** [wailsapp/wails#3086]
### Description

docker linux arm64 run wails dev panic

### To Reproduce

run :   wails dev

### Expected behaviour

panic: failed to init GTK

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:143 +0x330
sync.(*Once).doSlow(0x1059440, 0xc4fc78)
	/golang/go/src/sync/once.go:74 +0xf0
sync.(*Once).Do(0x1059440, 0xc4fc78)
	/golang/go/src/sync/once.go:65 +0x44
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0xc8d070, 0x400014f6e0}, 0x40000a6640, 0x400009c888, 0x400013c8a0, {0xc89880, 0x4000134ac0})
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:134 +0x54
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend({0xc8d070, 0x400014f6e0}, 0x40000a6640, 0x400009c888, 0x400013c8a0, {0xc89880, 0x4000134ac0})
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/desktop_linux.go:16 +0x58
github.com/wailsapp/wails/v2/internal/app.CreateApp(0x40000a6640)
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/app/app_dev.go:219 +0x1214
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0x40000aaf40)
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/application/application.go:57 +0x6c
github.com/wailsapp/wails/v2.Run(0x40000a6640)
	/root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/wails.go:14 +0x30
main.main()

### System Details

```shell
# Wails
Version         | v2.6.0
Package Manager | apt   

# System
┌──────────────────────────┐
| OS           | Ubuntu    |
| Version      | 20.04     |
| ID           | ubuntu    |
| Go Version   | go1.20.11 |
| Platform     | linux     |
| Architecture | arm64     |
└──────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Available | 24.0.5-0ubuntu1~20.04.1 |
| gcc        | build-essential       | Installed | 12.8ubuntu1.1           |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.20-0ubuntu1.1      |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.20.04.1 |
| npm        | npm                   | Installed | 9.6.3                   |
| *nsis      | nsis                  | Installed | v3.05-2                 |
| pkg-config | pkg-config            | Installed | 0.29.1                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘
```

**Comment by qq446887609** [comment]
> ### Description
> linux arm64 run wails dev panic
> 
> ### To Reproduce
> run : wails dev
> 
> ### Expected behaviour
> panic: failed to init GTK
> 
> goroutine 1 [running, locked to thread]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1() /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:143 +0x330 sync.(*Once).doSlow(0x1059440, 0xc4fc78) /golang/go/src/sync/once.go:74 +0xf0 sync.(*Once).Do(0x1059440, 0xc4fc78) /golang/go/src/sync/once.go:65 +0x44 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0xc8d070, 0x400014f6e0}, 0x40000a6640, 0x400009c888, 0x400013c8a0, {0xc89880, 0x4000134ac0}) /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:134 +0x54 github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend({0xc8d070, 0x400014f6e0}, 0x40000a6640, 0x400009c888, 0x400013c8a0, {0xc89880, 0x4000134ac0}) /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/desktop_linux.go:16 +0x58 github.com/wailsapp/wails/v2/internal/app.CreateApp(0x40000a6640) /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/app/app_dev.go:219 +0x1214 github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0x40000aaf40) /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/application/application.go:57 +0x6c github.com/wailsapp/wails/v2.Run(0x40000a6640) /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/wails.go:14 +0x30 main.main()
> 
> ### Screenshots
> _No response_
> 
> ### Attempted Fixes
> _No response_
> 
> ### System Details
> ```shell
> # Wails
> Version | v2.6.0
> 
> # System
> ┌─────────────────────────────┐
> | OS           | CentOS Linux |
> | Version      | 7            |
> | ID           | centos       |
> | Go Version   | go1.21.4     |
> | Platform     | linux        |
> | Architecture | arm64        |
> └─────────────────────────────┘
> 
> # Dependencies
> ┌──────────────────────────────────────────────┐
> | Dependency | Package Name | Status | Version |
> └──────────────────────────────────────────────┘
> ```
> 
> ### Additional context
> _No response_

**Comment by qq446887609** [comment]
And when I use it
wails build -platform linux/arm64

The opening effect is as follows:
![telegram-cloud-photo-size-5-6287155935034063001-y](https://github.com/wailsapp/wails/assets/23548259/dff24a2e-8b1c-4008-8d28-94fab23839cc)

**Comment by qq446887609** [comment]
The gtk installation version
root@ca504450f8e4:/usr/src/app/tong_xin_uos/gost_uos# pkg-config --modversion gtk+-3.0
3.24.20

**Comment by qq446887609** [comment]
Test again

environment:
<img width="970" alt="image" src="https://github.com/wailsapp/wails/assets/23548259/09932678-c0b9-4780-b158-41ebb0cf349a">


wails dev:
The web seems to be working
![image](https://github.com/wailsapp/wails/assets/23548259/859ed80b-b8cd-49a2-a9c9-5d724d71009e)

**Comment by tmclane** [comment]
I see a reference to Docker in the initial description.  Are you running inside Docker?  I know there is a way to expose x11 from the host to a docker runtime but I don't have the instructions on hand.  Is that what you are doing?

**Comment by qq446887609** [comment]
> 我在最初的描述中看到了对 Docker 的引用。你在 Docker 内部运行吗？我知道有一种方法可以将 x11 从主机公开给 docker 运行时，但我手头没有说明。你就是这么做的吗？

Initially yes,
But I have given up use ‘wails’
Since I can t modify the specific OS environment dependency
Some weird debian distributions

**Comment by hny** [comment]
When developing remotely via SSH in containers or Linux environments without a GUI desktop, consider using X11 forwarding. For details, refer to the link below.
https://www.cnblogs.com/Bubgit/p/18829192
