### ISSUE TITLE
I use generate bindings, but wails.CallByID() dose't work.

### ISSUE THREAD

**Issue by crismcn** [wailsapp/wails#3087]
### Description

I bound a package other than main and it was prompted that the method id could not be found.

### To Reproduce

```
$ wails3 generate bindings
$ wails.CallByID(xxx)
```

### Expected behaviour

1. After investigation, it was found that the strategy for generating boundMethod ID when generating binding from the v3-alpha.2 branch source code was inconsistent with that at runtime.
- `v3/internal/parser/parser.go`, line 421
```
    fqn := fmt.Sprintf("%s.%s.%s", pkg.Path, name, funcDecl.Name.Name)
```
- `v3/pkg/application/bindings.go`, line 208
```
 func (b *Bindings) getMethods(value interface{}, isPlugin bool) ([]*BoundMethod, error) {
```
2. I modified the code and it works
- `v3/internal/parser/parser.go`, line 421
```
   fqn := fmt.Sprintf("%s.%s.%s", filepath.Base(pkg.Path), name, funcDecl.Name.Name)
```

### Screenshots

<img width="1593" alt="image" src="https://github.com/wailsapp/wails/assets/43445354/a6075a51-858c-49ee-b6f9-95a9a2140f59">
<img width="1318" alt="image" src="https://github.com/wailsapp/wails/assets/43445354/0c5a2087-f09b-463e-88db-16467362826a">
<img width="799" alt="image" src="https://github.com/wailsapp/wails/assets/43445354/29199474-dae7-4ec0-8e9a-0b0eda34a07d">

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.1.1   |
| ID           | 23B81    |
| Go Version   | go1.21.3 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘
# Dependencies
┌───────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version        |
| Xcode command line tools  | N/A          | Installed | 2403           |
| Nodejs                    | N/A          | Installed | 18.18.2        |
| npm                       | N/A          | Installed | 9.8.1          |
| *Xcode                    | N/A          | Installed | 14.3 (14E222b) |
| *upx                      | N/A          | Available |                |
| *nsis                     | N/A          | Installed | v3.08          |
└─────────────────────── * - Optional Dependency ───────────────────────┘
```

**Comment by leaanthony** [comment]
Hi. 
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there.
Closing this for now.
Thanks again 🙏
