### ISSUE TITLE
macOS cannot receive shutdown signal

### ISSUE THREAD

**Issue by OneSeven** [wailsapp/wails#3095]
### Description

In macOS, when closing an application by right-clicking on the dock, the shutdown signal cannot be received and the subsequent shutdown cannot be processed.

### To Reproduce

Right-click the icon in the dock bar and select exit the application

### Expected behaviour

Can handle exit behavior

### System Details

```shell
wails 2.6
macOS 13
```

**Comment by plutov** [comment]
@leaanthony we can close this ticket I believe.
