### ISSUE TITLE
The requested operation requires elevation.

### ISSUE THREAD

**Issue by HelloAllenZhu** [wailsapp/wails#3096]
I encountered this error when I run: `wails build` and `wails dev` on Windows.

Error: 
Generating bindings: fork/exec C:\Users\username\AppData\Local\Temp\wailsbindings.exe: The requested operation requires elevation.

Could someone help me with it?

Thank you very much!

**Comment by leaanthony** [comment]
Might be best to ask in discord. This is a slow channel for help like this

**Comment by PylotLight** [comment]
I would also add that issues on github should specifically be for bugs not just general usage errors.

**Comment by HelloAllenZHU** [comment]
I found the reason of it: Missing dynamic library(dll) which should be placed in the wails project directory.

**Comment by HelloAllenZHU** [comment]
I found the reason of it: Missing dynamic library(dll) which should be placed in the wails project directory.
