### ISSUE TITLE
Support Distribution 'ArcoLinux'

### ISSUE THREAD

**Issue by LubeckHuaman** [wailsapp/wails#310]
**Description**
Distribution 'arcolinux' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | arcolinux |
| Distribution Name   | ArcoLinux |
| Distribution Version   | v19.12.16 |

Arcolinux is arch linux based distribution and link "guide how to add support for your linux distro" located on "getting started" is empty.

**Comment by bh90210** [comment]
hey @incafox 
the guide on https://wails.app/guides/distro/ works as should for me.
BUT archolinux should be supported already!

can you please share the output of `cat /etc/os-release`?

**Comment by incafox** [comment]
thanks for the answer, here is the output:

NAME="ArcoLinux"
ID=arcolinux
ID_LIKE="arch"
VERSION_ID=v19.12.16
ANSI_COLOR="0;36"
HOME_URL="https://arcolinux.info"
SUPPORT_URL="http://arcolinuxforum.com"

**Comment by bh90210** [comment]
I am investigating asap.
there should be a PR ready in a couple of hours :)

**Comment by incafox** [comment]
thankyou so much

**Comment by bh90210** [comment]
#312

**Comment by leaanthony** [comment]
Have you tested this @incafox ?

**Comment by incafox** [comment]
yes, it works! thankyou. :)
