### ISSUE TITLE
How to run Golang HTML template based site on Wails?

### ISSUE THREAD

**Issue by rohanray** [wailsapp/wails#3102]
### Describe the solution you'd like

Instead of using JS frameworks like Svelte, React etc. if we build a Golang HTML template based webapp (in conjunction with HTMX), how can we serve such a website within Wails?

**Comment by SamHennessy** [comment]
You can define an asset handle that works much like a web server.

https://wails.io/docs/guides/dynamic-assets/

Is that what you are looking for?
