### ISSUE TITLE
Implement a globalShortcut API

### ISSUE THREAD

**Issue by philc** [wailsapp/wails#3112]
This API allows the Wails app to bind a shortcut that is handled by the app even when it's not focused.

I'm writing a Spotlight/Alfred/Raycast style app which requires this functionality: typing the app's shortcut will summon the app, as cmd+space does for Spotlight.

Electron ([docs](https://www.electronjs.org/docs/latest/api/global-shortcut)) and Tauri ([docs](https://tauri.app/v1/api/js/globalshortcut/)) have this feature.

**Comment by philc** [comment]
For anyone who comes across this issue, @OlegGulevskyy made a [Wails example](https://github.com/OlegGulevskyy/wails-global-shortcut-demo/blob/master/app.go) of this using the golang-design/hotkey package.

**Comment by leaanthony** [comment]
The good thing about using a 3rd party library is that you're in total control. All we'd do is wrap it and that would be less flexible, unless you have a different take?

**Comment by philc** [comment]
@leaanthony Yes, that seems reasonable (and will satisfy my use case), so I'll close this.

In case there's future discusion, I think the reasons to have it be part of Wails:

1. Wails can make the API accessible to JavaScript, requiring less Go expertise from users.
2. Discovery, so developers can more easily find out how to achieve a global shortcut. Although now that this issue exists, anyone searching for globalShortcut in this repo will find this thread. Formerly the info was in discord and not discoverable with a search.
3. Controlling the implementation. If there was no preexisting high-quality third-party implementation for this, I would be advocating to put it on the roadmap.
