### ISSUE TITLE
-compiler flag is ignored in binding generation

### ISSUE THREAD

**Issue by xtrafrancyz** [wailsapp/wails#3120]
### Description

Command `wails build -compiler go1.20.12` fails to complete when default go version installed is 1.21. The reason is binding generation process where there is no compiler setting. Go 1.21 forcibly adds line `toolchain go1.21.5` to `go.mod` file and it becomes broken for 1.20.
https://github.com/wailsapp/wails/blob/aa8cd7ce67b1427d75cb4f56259d76cc22b4a882/v2/pkg/commands/bindings/bindings.go#L48-L55

It would also be nice for `wails dev` to support `-compiler` flag to avoid manual editing `go.mod` for release build.

### To Reproduce

1. Install latest Go version (1.21) globally
2. Install Go 1.20 https://go.dev/doc/manage-install (`go install golang.org/dl/go1.20.12@latest`, `go1.20.12 download`)
3. Create Wails project `wails init`
4. Remove `toolchain 1.21.x` from `go.mod` and change version to `go 1.20`
5. Run `wails build -compiler go1.20.12`

Error output:
```
go.mod:5: unknown directive: toolchain
  ERROR   exit status 1
```

### Expected behaviour

Compilation successful with Go 1.20

### Attempted Fixes

Workaround: `wails build -compiler go1.20.12 -skipbindings` and edit `go.mod` every time before build.

### System Details

```shell
# Wails
Version | v2.7.1

# System
┌───────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Home Single Language                                            |
| Version      | 2009 (Build: 22621)                                                        |
| ID           | 22H2                                                                       |
| Go Version   | go1.21.5                                                                   |
| Platform     | windows                                                                    |
| Architecture | amd64                                                                      |
| CPU          | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz                                  |
| GPU 1        | NVIDIA GeForce MX350 (NVIDIA) - Driver: 31.0.15.3203                       |
| GPU 2        | Intel(R) Iris(R) Plus Graphics (Intel Corporation) - Driver: 31.0.101.2114 |
| Memory       | 16GB                                                                       |
└───────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 120.0.2210.61 |
| Nodejs     | N/A          | Installed | 20.10.0       |
| npm        | N/A          | Installed | 10.2.3        |
| *upx       | N/A          | Installed | upx 4.2.1     |
| *nsis      | N/A          | Installed | v3.08         |
└─────────────── * - Optional Dependency ───────────────┘
```

### Additional context

Compilation with 1.20 is needed for Windows 7, although there is no official support, but it works

**Comment by leaanthony** [comment]
Great idea. Happy to accept a PR for this 👍
