### ISSUE TITLE
(bridge) implement  bridge/dev server remote connection support

### ISSUE THREAD

**Issue by tmclane** [wailsapp/wails#313]
Update the bridge.js and supporting Javascript development servers to allow for remote bridge connections.
This will allow for connections made to the Node development server for each of the front0end implementations to successfully be made from remote devices.

The files needing updated are:

* runtime/assets/bridge.js
* cmd/templates/angular-template/frontend/package.json.template
* cmd/templates/vuebasic/frontend/vue.config.js
* cmd/templates/vuetify-basic/frontend/vue.config.js

**Comment by leaanthony** [comment]
Fixed by #314
