### ISSUE TITLE
multiple bridge connection support

### ISSUE THREAD

**Issue by tmclane** [wailsapp/wails#316]
This issue is a proposal for multiple websocket management in the `renderer/bridge` code:

The proposal includes the following:
* Updating the `interfaces.Renderer` `Dispatch` function signature to accept a `CallbackFunc` argument to be used in place of the `Callback` function defined in the interface.
* updating the `lib.renderer.WebView` and `lib.renderer.Bridge` to use the updated `Dispatch` passing in the relevant private callback function such that the plumbing works properly
* deprecating and removing the `interfaces.Renderer.Callback` function requirement (replaced by previous bullet point)
* updating the `lib.renderer.Bridge` code to use a `map[string]*conn.WebSocket` instead to keep track of connected sessions for notification
* (optional) add a `NewBridge` function to replace the direct use of the `Bridge{}` struct initialization in app.go
* (optional) move the bridge code to a package of renderer -> `lib.renderer.bridge` and create a new `renderer` package level bridge.go containing the `NewBridge` function

The last two marked optional can be removed and the new websocket `session` code be placed inside the original `lib/renderer/bridge.go` file if so desired.  I thought that perhaps since the webview had a similar pattern that this might be a better layout.

Note: The code doing all of the above is found in [tmclane/316-multi-bridge-conn](https://github.com/tmclane/wails/tree/316-multi-bridge-conn)

**Comment by leaanthony** [comment]
Ping me when you're back and we'll go over this.
