### ISSUE TITLE
[FEATURE REQ] Multiple windows

### ISSUE THREAD

**Issue by ultimateshadsform** [wailsapp/wails#3169]
It would be cool if we could have multiple windows. Like instead of having 1 window for something we can create another window with something else.

Is it already possible? I don't know.

But it would be cool to have it available.

**Comment by JensvandeWiel** [comment]
this will probably be possible with wails v3:
https://wails.io/blog/the-road-to-wails-v3/#thoughts-on-the-v3-api

**Comment by ultimateshadsform** [comment]
Looks awesome!!! Can't wait for it to be implemented!
