### ISSUE TITLE
Can we add instructions for installing NSIS through Winget and Scoop?

### ISSUE THREAD

**Issue by lukewatts** [wailsapp/wails#3170]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Currently, there is only documentation to install NSIS manually, or via Chocolatey, however, Winget and Scoop may be preferable as they are both more modern ways of doing this via CLI.

Also, could we make Winget (the official Windows package manager) or Scoop the preferred method of installation instead of Chocolatey (which is a bit outdated compared to the others)?

Scoop in particular is more like homebrew, in that the installation is isolated and the path is already pointing to the Scoop location so there is no need to update the PATH manually.

I've already got a branch ready for this waiting here if you'd like to review, and I'm happy to answer any questions: https://github.com/lukewatts/wails/tree/windows-nsis-install-documentation-improvements

Thanks! Wails is awesome!

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Hi Luke 👋 That sounds like a great idea! Feel free to open the PR 👍

**Comment by lukewatts** [comment]
Thanks, I'll open that PR shortly!
