### ISSUE TITLE
Some MacOS versions may cause window pop ups to fail to display when calling runtime.dialog

### ISSUE THREAD

**Issue by qiwentaidi** [wailsapp/wails#3175]
### Description

Some MacOS versions may cause window pop ups to fail to display when calling runtime.dialog

### To Reproduce

`func (a *App) SelectFile() string {
	selection, err := runtime.OpenFileDialog(a.ctx, runtime.OpenDialogOptions{
		Title: "选择文件",
		Filters: []runtime.FileFilter{
			{
				DisplayName: "文本数据",
				Pattern:     "*.txt",
			},
		},
	})
	if err != nil {
		return fmt.Sprintf("err %s!", err)
	}
	return selection
}`

### Expected behaviour

Open file dialog box normally

### Screenshots

![image](https://github.com/wailsapp/wails/assets/104491549/a74c27e9-2762-4c46-8b71-25d2f0b8d8c3)

### System Details

```shell
null
```

**Comment by leaanthony** [comment]
Thanks for opening. Which versions?

**Comment by qiwentaidi** [comment]
![image](https://github.com/wailsapp/wails/assets/104491549/f61947f2-f793-4c86-9f2e-4a6ed6f03f0f)

**Comment by qiwentaidi** [comment]
Using macos 14.3.0 or above can solve the problem

**Comment by makew0rld** [comment]
I am also seeing an open file dialog flash up and close without working, but on macOS 14.5. I will investigate this further and open an issue if needed but I'm wondering if anyone else can confirm this.

**Comment by leaanthony** [comment]
I suspect it's to do with the filters.

**Comment by makew0rld** [comment]
In my case it turns out that this was caused by running the binary directly instead of opening the `.app`, so I don't consider this an issue for me anymore.
