### ISSUE TITLE
Add `Wails install` command to allow installing npm dependencies in the frontend folder from the root

### ISSUE THREAD

**Issue by lukewatts** [wailsapp/wails#3180]
### Is your feature request related to a problem? Please describe.

It's a silly thing...and I'm not sure if this happens to anyone else, but I keep running `npm install <package>`  from the root folder. 

The problem is that it then creates a node_modules folder and a package.json in the root, and it seems like everything worked. And then I realise my mistake and have to go remove them and cd into frontend and redo.

Of course, package.json belongs in the frontend directory. And yes I should just be more careful...but what's the fun in that :)

### Describe the solution you'd like

I was thinking it would be great if there was a `wails install <package>`, that essentially just CDs into frontend and runs `npm install <package>`

I know everything in the wails CLI is currently to do with Go and building etc, so not sure if this is the right place for it. But thought I'd bring it up and see what people think?

### Describe alternatives you've considered

I think there's a way to add a package.json to the root folder that says "when npm install is run, do this command first" but I couldn't get it working. Something like a "preinstall" in the scripts section I think :/

### Additional context

Thank you!

**Comment by lukewatts** [comment]
Also, I come from PHP land, and Laravel has a CLI called `artisan`.

One really nice thing they have is that everything is prefixed so there CLI commands are grouped.

So wails could do similar to allow for a whole slue of frontend specific commands

```bash
wails frontend:install <flags> <package>
wails frontend:generate component --react <ComponentName>
wails frontend:run <command> // Runs npm run <command> in frontend
wails frontend:test // runs frontend test (npm run test)
```

The nice thing about this is that when you run `wails frontend` you would only get a list of the command prefixed with frontend:

**Comment by leaanthony** [comment]
Hi Luke! 👋 
I get how frustrating that must be, but I'm not sure a new subcommand is the right solution. Not all people use `npm` so this method would end up just being `cd`. Even then not everyone uses the `frontend` directory. 
In v3, we're externalising the entire build system using [Task](https://taskfile.dev) so you can just update that with extra commands if you like. Task also allows you to do what you wrote in your second comment too so I think we're good?

**Comment by lukewatts** [comment]
Thanks Lea! Perfect, Task does seem like it would work for this scenario. I'll probably just add that to my current project in the meantime. 
Thanks

**Comment by lukewatts** [comment]
Just for anyone whoe might find this and who also wants to setup Task in the meantime for this purpose. This is how you'll need to setup your `taskfile.yml`:

```yml
frontend:install: 
    dir: frontend # This CDs into the frontend directory
    cmds:
      - npm install {{.CLI_ARGS}} # REQUIRED: The .CLI_ARGS variable lets you pass the package and additional flags 
      - cd ..
```

Then you'll run the command like so: 

```bash
task frontend:install -- <package>
```

The `--` is required, as stuff after this is what gets passed to `{{.CLI_ARGS}}`
