### ISSUE TITLE
How to play local audio files

### ISSUE THREAD

**Issue by jmy2022** [wailsapp/wails#3184]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

I can't play a local video file, is it only over https

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
I'd personally play audio from Go using https://github.com/gopxl/beep

**Comment by domingguss** [comment]
> I'd personally play audio from Go using https://github.com/gopxl/beep

im trying this right now, but it seems it doesn't work as I don't hear anything.. any suggestions?

```golang
// Greet returns a greeting for the given name
func (a *App) Greet(name string) string {

	f, err := os.Open("gunshot.wav")
	if err != nil {
		log.Fatal(err)
	}

	streamer, format, err := wav.Decode(f)
	if err != nil {
		log.Fatal(err)
	}

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/60))

	buffer := beep.NewBuffer(format)
	shot := buffer.Streamer(0, buffer.Len())
	speaker.Play(shot)
	log.Printf("Playing sound")

	return fmt.Sprintf("Hello %s, It's show time!", name)
}

```

**Comment by suifengtec** [comment]
> > I'd personally play audio from Go using https://github.com/gopxl/beep
> 
> im trying this right now, but it seems it doesn't work as I don't hear anything.. any suggestions?
> 
> // Greet returns a greeting for the given name
> func (a *App) Greet(name string) string {
> 
> 	f, err := os.Open("gunshot.wav")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	streamer, format, err := wav.Decode(f)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/60))
> 
> 	buffer := beep.NewBuffer(format)
> 	shot := buffer.Streamer(0, buffer.Len())
> 	speaker.Play(shot)
> 	log.Printf("Playing sound")
> 
> 	return fmt.Sprintf("Hello %s, It's show time!", name)
> }

such as following:
`	
// Initialize the speaker
	err = speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
	if err != nil {
		log.Fatal(err)
	}

	// Play the audio
	done := make(chan bool)
	speaker.Play(beep.Seq(streamer, beep.Callback(func() {
		done <- true
	})))

	// Wait for the audio to finish playing
	<-done
`
