### ISSUE TITLE
Support Distribution 'Deepin'

### ISSUE THREAD

**Issue by js00070** [wailsapp/wails#319]
**Description**
Distribution 'deepin' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | deepin |
| Distribution Name   | Deepin |
| Distribution Version   | 15.11 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
I am working on it :)

**Comment by bh90210** [comment]
done :smiley: 

test update with `wails update -pre` :+1:

**Comment by leaanthony** [comment]
Any feedback @js00070 ?

**Comment by leaanthony** [comment]
Closing due to lack of response
