### ISSUE TITLE
Build fails due to dlls not in path

### ISSUE THREAD

**Issue by mega-rds** [wailsapp/wails#3194]
### Description

I have a project, that has Go code that has C++ code bindings. These are present in the dlls that I have.
When I run the wails build command it fails, it seems during creating the TS bindings, the evaulation of Go code bugs out due to not finding the DLLs
The problem goes away when I place the DLLs in the project root. 

I would like to keep the DLLs in a subdirectory with further subdivided as x64, x86. Having them on the root is just problematic.

Am I missing something from the documentation?

Thanks in advance

Here is the screenshot of the error
![Screenshot 2024-01-11 145707](https://github.com/wailsapp/wails/assets/155939210/39cb782b-12f8-4600-883b-89c31bd28ad5)

### To Reproduce

wails build

### Expected behaviour

There should be a way to add the DLLs via the wails build command

### Attempted Fixes

Moved the x64 dlls to the base of the project, the x64 build compiles now

### System Details

```shell
Wails Doctor



# Wails
Version | v2.6.0

# System
┌────────────────────────────────────────────────┐
| OS           | Windows 10 Home Single Language |
| Version      | 2009 (Build: 22631)             |
| ID           | 23H2                            |
| Go Version   | go1.21.5                        |
| Platform     | windows                         |
| Architecture | amd64                           |
└────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version        |
| WebView2   | N/A          | Installed | 120.0.2210.121 |
| Nodejs     | N/A          | Installed | 20.10.0        |
| npm        | N/A          | Installed | 10.2.3         |
| *upx       | N/A          | Available |                |
| *nsis      | N/A          | Installed | v3.09          |
└─────────────── * - Optional Dependency ────────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
If you keep your DLLs in a different directory, you need to tell the compiler where they are. You could try setting the `CGO_LDFLAGS` environment variable to achieve this: https://pkg.go.dev/cmd/cgo

**Comment by mega-rds** [comment]
How do I merge these with the wails build command?

**Comment by mega-rds** [comment]
> If you keep your DLLs in a different directory, you need to tell the compiler where they are. You could try setting the `CGO_LDFLAGS` environment variable to achieve this: https://pkg.go.dev/cmd/cgo

Hello

An example would be of big help

**Comment by snopywithchary** [comment]
> > 如果将 DLL 保存在其他目录中，则需要告诉编译器它们的位置。您可以尝试设置环境变量来实现此目的： https://pkg.go.dev/cmd/cgo`CGO_LDFLAGS`
> 
> 你好
> 
> 一个例子会有很大的帮助

I also encountered this problem, but I solved it by actively adding the path of the dll to the environment variable
$env:PATH += ";$PWD/build/bin" ->wails build

**Comment by snopywithchary** [comment]
> 我现在用 env var 解决了。 我还弄清楚了如何在代码中内联执行此操作。谢谢`CGO_LDFLAGS`

add dll forlder to env:PATH? What does this have to do with CGO_LDFLAGS?
