### ISSUE TITLE
I'm having issues running compiled programs on Steam Deck.

### ISSUE THREAD

**Issue by biuaxia** [wailsapp/wails#3198]
### Description

I have developed a software using Wails, originally intended to run as an exe program on Windows. However, I have unexpectedly encountered users with Steam Deck devices.

I have tried different webview2 strategies, such as edownload, embed, and browser, but none of them seem to work. Users are either prompted to download and install dependencies or informed that the minimum version requirement is not met.

I would like to inquire about possible solutions to ensure a smooth user experience on Steam Deck devices.

### To Reproduce

The program is at the bottom, which can be downloaded and run on the SteamDeck device directly.

[flyy_client_v3内嵌.zip](https://github.com/wailsapp/wails/files/13914583/flyy_client_v3.zip)

### Expected behaviour

I want to be able to run properly, or tell me how to modify the program to make it work properly?

### Screenshots

![7eebb5ba885a69dc4ecf09b020bdd06](https://github.com/wailsapp/wails/assets/46131142/7382b833-0679-461f-86de-5b20f2be08db)
![e3e6210cfaa76aebc42e8ef730e03b3](https://github.com/wailsapp/wails/assets/46131142/906fa5e1-4de9-4f67-95c6-4373c710bd2f)
![e59e16eba8506507fe52eac44965c6f](https://github.com/wailsapp/wails/assets/46131142/40b81ab9-da20-41eb-864e-a96737a090d2)

![6b807e0f236e65bd2443cedb4bddfdf](https://github.com/wailsapp/wails/assets/46131142/b7578627-cff7-4114-bfb7-1016d603fc4e)

![a6edadc931923a3adc865461b34a086](https://github.com/wailsapp/wails/assets/46131142/81493fc6-2917-479d-af64-2e535e0e8db4)

https://github.com/wailsapp/wails/assets/46131142/0513d132-dfbb-4d07-a0ee-928ec6fa552b

### System Details

```shell
Wails Doctor



# Wails
Version | v2.7.1

# System
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                                                   |
| Version      | 2009 (Build: 19045)                                                                              |
| ID           | 22H2                                                                                             |
| Go Version   | go1.21.3                                                                                         |
| Platform     | windows                                                                                          |
| Architecture | amd64                                                                                            |
| CPU          | 12th Gen Intel(R) Core(TM) i5-12600KF                                                            |
| GPU 1        | OrayIddDriver Device (Shanghai Best Oray Information Technology Co., Ltd.) - Driver: 17.1.58.818 |
| GPU 2        | NVIDIA GeForce RTX 3070 Ti (NVIDIA) - Driver: 31.0.15.4633                                       |
| Memory       | 64GB                                                                                             |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version        |
| WebView2   | N/A          | Installed | 120.0.2210.121 |
| Nodejs     | N/A          | Installed | 18.17.1        |
| npm        | N/A          | Installed | 9.6.7          |
| *upx       | N/A          | Available |                |
| *nsis      | N/A          | Available |                |
└─────────────── * - Optional Dependency ────────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

StreamDeck uses [SteamOS](https://en.wikipedia.org/wiki/SteamOS) which is based on Linux and not Windows. They use [Proton](https://en.wikipedia.org/wiki/Proton_(software)) as compatibility layer to run Windows games and therefore it's not possible to run the Microsoft WebView2 Component on it.

I would suggest you to try building your App for Linux and see if that works.

**Comment by stffabi** [comment]
I'm going to close this issue, because WebView2 and Windows builds are not meant to be run under any Windows Compability Layer on Linux.
