### ISSUE TITLE
Support Distribution 'Manjaro-ARM'

### ISSUE THREAD

**Issue by janantos** [wailsapp/wails#320]
**Description**
Distribution 'manjaro-arm' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.5 |
| Platform      | linux |
| Arch          | arm64 |
| GO111MODULE   | on |
| Distribution ID   | manjaro-arm |
| Distribution Name   | Manjaro-ARM |
| Distribution Version   |  |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
#319 a PR is coming in

**Comment by bh90210** [comment]
@janantos sorry for the delay
a new pre-release will be out soon. you will be able to update and test with `wails update -pre`

If I understand you are planning on using wails on some ARM device? Please let us know is you succeed. If not please report back for support. :smiley:

**Comment by leaanthony** [comment]
v1.0.2-pre3 supports this now. Please update using `wails update -pre` and let us know :+1:

**Comment by janantos** [comment]
@bh90210 ji, yes I am going to use it on Pinebook Pro, will definitively give you feedback soon. Thanks for your effort.

**Comment by janantos** [comment]
> @janantos sorry for the delay
> a new pre-release ~will be~ is out ~soon~ (@leaanthony). you will be able to update and test with `wails update -pre`
> 
> I understand you are planning using wails on some ARM device? Please let us know if you succeed. If not please report back for support. smiley

hi, thanks again for your effort, but it does not work.

wails init
Wails v1.0.2-pre3 - Initialising project

The name of the project (My Project): test
Project Name: test
The output binary name (test): 
Output binary Name: test
Project directory name (test): 
Project Directory: test
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  5: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
✓ Generating project...
⡿ Building project (this may take a while)...
Wails v1.0.2-pre3 - Building Application

⢿ Ensuring frontend dependencies are up to date (This may take a while)

✗ Ensuring frontend dependencies are up to date (This may take a while)
Error: signal: illegal instruction (core dumped)

✗ exit status 255
Error: exit status 255

it sort of generate souurce folder as I can see, but then fails on illegal instruction.
cant found dumped core, any hint?

**Comment by bh90210** [comment]
#326

**Comment by bh90210** [comment]
after a quick search I've found https://archlinuxarm.org/forum/viewtopic.php?f=15&t=9583
can you please `npm -v` and share the result?

+ https://github.com/nodejs/help/issues/1453#issuecomment-415761791
`The Illegal instruction error concerns the production (by the JIT) of an instruction that the processor does not recognise as valid. That might arise if the architecture of what was downloaded does not match the real architecture of your machine (you are most likely to be on an x64).`

+ https://stackoverflow.com/questions/42159324/illegal-instruction-core-dumped-node-js
`It seems that you copied the node_modules instead of moving everything else and running npm install to install dependencies.`

can you please confirm if a projectname/frontend folder in was created before the exit error?

also many seem to suggest maybe using a different node version actually solves the issue

**Comment by bh90210** [comment]
* https://raspberrypi.stackexchange.com/questions/24059/node-js-v0-11-14-exits-with-illegal-instruction
### Test node
To test whether this is the reason you are experiencing the 'Illegal instruction' error, run node --v8-options and look at the second line. If it is:

`ARMv7=1 VFP3=0 VFP32DREGS=0 NEON=0 SUDIV=0 ...`
then the ARMv7=1 hints that V8 is compiled for ARMv7.

**Comment by leaanthony** [comment]
Awesome work @bh90210 - I've added an ARM section in the docs to capture this information and add a Work in progress notice to it. @janantos - once you confirm the solution, we'll ensure the docs reflect this. It will greatly help others who will be using ARM.

**Comment by janantos** [comment]
hi, whatever was fixed in 1.0.2-pre5 fixed the problem itself.
nothing needs to be set in Manjaro-arm

current tested versions
npm 6.13.6
node 13.6.0

manjaro-arm is full 64bit (aarch64) not like rapsbian where is 64bit kernel but 32bit userspace (armhf)

so we can declate it working, as vue project builds and run. I am using pinebook pro which have chipset RK3399, it is arm8 not arm7 as rpi.

thanks for your effort.

great job

**Comment by leaanthony** [comment]
Thanks for confirming. Wails hasn't been targetting ARM specifically so I'm
not sure what performance is like. Hopefully, this is something you could
give feedback on. Good luck 👍

**Comment by janantos** [comment]
@leaanthony do you have any benchmark? On the other side rk3399 chipset is quite powerful. Definitively will provide feedback.

**Comment by leaanthony** [comment]
No benchmarks for me, but some of the IPC is quite CPU intensive. I'm also
wondering if tinygo would be an option too....

**Comment by janantos** [comment]
@leaanthony I would doubt tinygo will work as cgo is partially supported. Also standard library is not fully supported.

**Comment by leaanthony** [comment]
Thanks for the feedback. Glad it's working for you. Closing.
