### ISSUE TITLE
Wails in Win32

### ISSUE THREAD

**Issue by nilopaim** [wailsapp/wails#321]
I'm trying to use Wails on a 32 bits Mingw installation, but I'm getting

`In file included from C:\Go\external\pkg\mod\github.com\wailsapp\wails@v1.0.2-pre2\lib\renderer\webview\webview.go:26:0:
./webview.h:64:22: fatal error: mshtmhst.h: No such file or directory`

I've tried this on two boxes: one with Windows 10 64 bits and another with Windows 10 32 bits.

My primary development box is Win 10 64 bits, but my final application must be compiled in 32 bits.

Any hints?

**Comment by nilopaim** [comment]
I've got it to work reinstalling a fresh Mingw. 

Thanks and congrats for your fantastic tool.

**Comment by leaanthony** [comment]
Glad you fixed it! Please consider creating a PR for the docs with this
information. Best of luck.

**Comment by ljjimenez** [comment]
Did you compile it on the 64-bit machine for 32-bit?
