### ISSUE TITLE
wails macos cant support Chinese character 

### ISSUE THREAD

**Issue by linktomarkdown** [wailsapp/wails#3216]
### Description

When wails is packaged and built to build a macos application, the Chinese character data obtained from the clipboard is all garbled.

### To Reproduce

<img width="985" alt="image" src="https://github.com/wailsapp/wails/assets/115915567/8202ccb4-8b8d-472b-a6b5-06a80bf2eb41">

### Expected behaviour

none

### System Details

```shell
# System

OS           | MacOS   
Version      | 11.5.2  
ID           | 20G95   
Go Version   | go1.20.3
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.4.1
```

**Comment by almas1992** [comment]
Provide reproducible sample code or projects.

**Comment by linktomarkdown** [comment]
![image](https://github.com/wailsapp/wails/assets/115915567/3b2675b2-17fd-493c-b920-3b9de3cf3911)

I use Vue3, and then assign the clipboard method of wails to the global proxy without any transfer operation.

**Comment by hsiafan** [comment]
> ![image](https://private-user-images.githubusercontent.com/115915567/300696145-3b2675b2-17fd-493c-b920-3b9de3cf3911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzQ1NjAsIm5iZiI6MTcwNjY3NDI2MCwicGF0aCI6Ii8xMTU5MTU1NjcvMzAwNjk2MTQ1LTNiMjY3NWIyLTE3ZmQtNDkzYy1iOTIwLTNiOWRlM2NmMzkxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwNDExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDEzY2FhZGE0MDgyMTQ2ZGNiNjRhNDE2ZjEwMWJmZTEwZTAyZTU5NzJlM2Q5ZWViMWMwMTYxNTI3NGYyNDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zlao9DFXjzyEGbI32uGxMpJYqUK0XqDot6cmSWXLoTo)
> 
> I use Vue3, and then assign the clipboard method of wails to the global proxy without any transfer operation.

It's challenging to identify any issues with just a small piece of code as this. 
Maybe you could write minimal reproducible example just with origin ClipboardGetText method.

**Comment by leaanthony** [comment]
Are you using the correct charset for your HTML?
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
</head>
<body>
  <!-- Your content here -->
</body>
</html>```

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/local-development#testing-a-pr). Let us know how you get on 👍

**Comment by leaanthony** [comment]
@linktomarkdown - Any updates? 
@hsiafan - Does the linked PR work for you?

**Comment by hsiafan** [comment]
> @linktomarkdown - Any updates? @hsiafan - Does the linked PR work for you?

The current version using pbcopy just works well for me. The PR works correctly too.

**Comment by leaanthony** [comment]
Closing due to lack of feedback.
