### ISSUE TITLE
【V3】 Event feature not work with the default project template.

### ISSUE THREAD

**Issue by SudoUserReal** [wailsapp/wails#3219]
### Description

Event not work with the default project template. 
When use `wails3 init -n myfirstapp` and go to myfirstapp dir and run `wails3 dev`, In the app, The time string in the element with the id `time` won't be updated as the code in the main.js' write. The event is sent by go but not not received on the javascript side.

### To Reproduce

1. `wails3 init -n myfirstapp`
2. go to the dir `myfirstapp`
3. `wails3 dev`
4. use the devtools to check the string in the element with the id 'time'

### Expected behaviour

The content of `#time` element should be updated by the event hook.

### System Details

```shell
Windows 10 Entriprise LSTC.
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏

**Comment by PylotLight** [comment]
> @leaanthony The Discord invite link is expired. ![image](https://private-user-images.githubusercontent.com/29626873/300171685-af93ac11-d4fe-4a1b-a91e-45088ef0713a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTEzNDQsIm5iZiI6MTcwNjM1MTA0NCwicGF0aCI6Ii8yOTYyNjg3My8zMDAxNzE2ODUtYWY5M2FjMTEtZDRmZS00YTFiLWE5MWUtNDUwODhlZjA3MTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwMjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMjA4MGFjN2M0NTU3ODVlY2Y1NDY1ODA1YTJhYjY3YzQ5NTMzMDdiNzAzN2E3MzY4YjI0MjRmNzNhNjdhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zepeqcwdj39FY3FJX5w_8RMiM5yIPhQ0D45Q-dUx_ew)

https://discord.gg/KTR6d2Un
