### ISSUE TITLE
Wails fails on "wails build" but runs with "wails serve"

### ISSUE THREAD

**Issue by billacw** [wailsapp/wails#323]
**Description**

I can debug with "wails serve" but "wails build" fails with error missing file. It seems to be misspelling the main.css file as main.cs

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The package builds into an executable

**Screenshots**
here is the output of "wails build"
![wails build error](https://user-images.githubusercontent.com/58347572/71859313-4a259180-30a3-11ea-814b-93bc26af3798.png)

Here is the output of "wails serve"
![wails serve works](https://user-images.githubusercontent.com/58347572/71859283-32e6a400-30a3-11ea-8237-88502994064a.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2-pre2 |
| Go Version    | go1.13 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.12.1 |
| Node          | v12.13.1
 |

GO111MODULE is set, see the "go env" list below

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\billa\AppData\Local\go-build
set GOENV=C:\Users\billa\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\billa\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\billa\go\src\countworks.us\golang\paperdata\rentmgrbillload\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\billa\AppData\Local\Temp\go-build752979514=/tmp/go-build -gno-record-gcc-switches

**Additional context**

**Comment by bh90210** [comment]
hmmm the log says `main.cs` can not be found. could it be it or is it cut out (the final `s`) due to some windows weirdness?

**Comment by billacw** [comment]
The main.css and main.css.map was created in the directory and remains after the failed build.
located in C:\Users\billa\go\src\countworks.us\golang\paperdata\dp2rm\frontend\build\static\css

**Comment by leaanthony** [comment]
That's a long path in the error. Is it 256 chars long?

**Comment by billacw** [comment]
The path is 93 characters
C:\Users\billa\go\src\countworks.us\golang\paperdata\dp2rm\frontend\build\static\css\main.css

**Comment by billacw** [comment]
created a new Wails project with init in a different directory on the same machine. Same error.

**Comment by billacw** [comment]
Sorry my mistake. This is not a bug. I set the CSS in my main function to "main.cs" not "main.css". Once I fixed that mistake it compiled!!
