### ISSUE TITLE
v3, installed from source code under alpha release, got "ERROR   Rel: can't make  relative to <project folder>" due to lack of .git folder

### ISSUE THREAD

**Issue by stanleyyzhu** [wailsapp/wails#3251]
### Description

If wails3 is installed from the "source code" packet under v3 alpha release, it will fail to init a project due to lack of ".git" folder (not sure if this is a bug or just a temp phase during development)

### To Reproduce

Windows 10 (but it doesn't look like OS related)

1. Downloaded "source code" from [v3.0.0-alpha.4](https://github.com/wailsapp/wails/releases/tag/v3.0.0-alpha.4)
2. Unzip it and install it by following commands:
```
cd <wails_download_folder>\v3\cmd\wails
go install
```
3. Go to any folder where I want to create a new project, create a new project
```
wails3 init -n myfirstapp -t svelte-ts
ERROR   Rel: can't make  relative to <my project folder>\myfirstapp
```

### Expected behaviour

A new project should be able to get initialized

### Attempted Fixes

Use git to grab source code. 
I don't know if this would impact the final release, so raise it up just in case

### System Details

```shell
C:\Telus\Projects>wails3 doctor


          Wails Doctor



# Build Environment
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | 471d6260430acdd43b0e092d3236fc8347e077fe
Modified       | false
-buildmode     | exe
-compiler      | gc
CGO_ENABLED    | 0
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1
GOARCH         | amd64
GOOS           | windows
vcs            | git
vcs.modified   | false
vcs.revision   | 471d6260430acdd43b0e092d3236fc8347e077fe
vcs.time       | 2024-02-07T21:31:58Z

# System
Name              | Windows 10 Home
Version           | 2009 (Build: 19045)
ID                | 22H2
Branding          | Windows 10 Home
Platform          | windows
Architecture      | amd64
Go WebView2Loader | true
NSIS              | Not Installed
WebView2 Version  | 121.0.2277.112
CPU               | Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
GPU 1             | Intel(R) HD Graphics Family (Intel Corporation) - Driver: 20.19.15.4531
Memory            | 8GB

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

### Additional context

The reason of this ERROR is that:

In "wails\v3\internal\debug\debug.go", func init() will try to find ".git" directory and use it to set var "LocalModulePath"
```
var LocalModulePath = ""

func init() {
	// Check if .git exists in the relative directory from here: ../../..
	// If it does, we are in a local build
	gitDir := RelativePath("..", "..", "..", ".git")
	if _, err := os.Stat(gitDir); err == nil {
		modulePath := RelativePath("..", "..", "..")
		LocalModulePath, _ = filepath.Abs(modulePath)
	}
}
```

However, if the source code is downloaded from alpha release, or whatever method without using git, there won't be ".git" directory by default, therefore, "os.Stat(gitDir)" will return with err "The system cannot find the file specified." then LocalModulePath will remain empty.

Then in the step under "wails\v3\internal\templates\templates.go" func Install(), `relativePath, err = filepath.Rel(projectDir, debug.LocalModulePath)` will return error
```
// Calculate relative path from project directory to LocalModulePath
var relativePath string
relativePath, err = filepath.Rel(projectDir, debug.LocalModulePath)
if err != nil {
	return err
}
```

**Comment by leaanthony** [comment]
Thanks for taking the time to open this. We only support the installation method outlined in the [documentation](https://v3alpha.wails.io/) during alpha 🙏
