### ISSUE TITLE
Incorrect dependency requirement for V3

### ISSUE THREAD

**Issue by istiak101** [wailsapp/wails#3253]
### Description

V3 alpha can not be installed due to incorrect dependency requirement.

```
# pkg-config --cflags  -- gtk+-3.0 webkit2gtk-4.0 javascriptcoregtk-4.1
Package javascriptcoregtk-4.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `javascriptcoregtk-4.1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'javascriptcoregtk-4.1', required by 'virtual:world', not found
pkg-config: exit status 1
```

It should be either 4.0 or 4.1 for both webkit2gtk and javascriptcoregtk.

### To Reproduce

NA

### Expected behaviour

NA

### System Details

```shell
NA
```

**Comment by PylotLight** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.

Thanks again 🙏

**Comment by PylotLight** [comment]
P.S libjavascriptcoregtk-4.1-dev I think is what you're looking for?

**Comment by istiak101** [comment]
> P.S libjavascriptcoregtk-4.1-dev I think is what you're looking for?

Different API version for webkit2gtk and javascriptcoregtk. I got it installed but why two versions of API?

**Comment by leaanthony** [comment]
I've removed the need for libjavascriptcoregtk.
