### ISSUE TITLE
[v3] wails3 init "Rel: can't make  relative to <ProjectDir>" error

### ISSUE THREAD

**Issue by nehzata** [wailsapp/wails#3255]
### Description

`debug.LocalModulePath` is an empty string for non-local builds and causes an error in `filepaths.Rel` on [this](https://github.com/wailsapp/wails/blob/471d6260430acdd43b0e092d3236fc8347e077fe/v3/internal/templates/templates.go#L217) line in templates.Install.

### To Reproduce

1. `go install github.com/wailsapp/wails/v3/cmd/wails3@v3-alpha`
2. `wails3 init -n helloworld`

### Expected behaviour

Expect the template project to be installed. Instead receive the error below.

### Screenshots

```
➜  test> wails3 init -n helloworld
  ERROR   Rel: can't make  relative to /tmp/test/helloworld
```

### System Details

```shell
# Build Environment
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
-buildmode     | exe
-compiler      | gc
CGO_CFLAGS     |
CGO_CPPFLAGS   |
CGO_CXXFLAGS   |
CGO_ENABLED    | 1
CGO_LDFLAGS    |
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOARCH         | arm64
GOOS           | darwin

# System
Name            | MacOS
Version         | 14.2.1
ID              | 23C71
Branding        | Sonoma
Platform        | darwin
Architecture    | arm64
Apple Silicon   | true
CPU             | Apple M1 Pro
Xcode cli tools | 2405
CPU             | Unknown
GPU             | Unknown
Memory          | Unknown

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Hi. I'm going to close this for the reasons mentioned in the PR. We can revisit it during Beta :+1:
