### ISSUE TITLE
Add `skip go mod tidy` option to `wails dev`

### ISSUE THREAD

**Issue by te5se** [wailsapp/wails#3269]
We'd like to use wails for development in our company, but we have a local network without access to internet.

In previous Go projects vendoring covered all problems, but with wails when running `wails dev` command `go mod tidy` tries to go to internet and fails.

Command `wails build` has `-m` option that allows to skip `go mod tidy` step and we could use it to build application and debug the backend side of it, but inability to run `wails dev` makes it impossible to take advantage of a hot reload feature, so the development process is slower. 

Would you consider adding the same option to `wails dev`?

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

I think that is a viable enhancement request, would you like to provide a PR?

**Comment by te5se** [comment]
Sounds fun, I'll see what I can do

**Comment by istiak101** [comment]
@te5se would athens work for you?

https://github.com/gomods/athens

**Comment by te5se** [comment]
@istiak101, if I'm not mistaken, PROXY server allows to pull from several sources, allowing to keep some of your libraries private, but doesn't replace those sources, unlike nexus for nuget of npm packages. 

Our network is completely separate from Internet, so PROXY wouldn't be able to get all needed packages and creating complete github copy of needed packages is just unrealistic

**Comment by te5se** [comment]
- PR https://github.com/wailsapp/wails/pull/3275

**Comment by stffabi** [comment]
The PR has been merged.
