### ISSUE TITLE
Improvement Proposal for Browser-Only Development Mode in Wails

### ISSUE THREAD

**Issue by m0a** [wailsapp/wails#3274]
### Is your feature request related to a problem? Please describe.

Yes, the current behavior of Wails where the desktop application restarts upon code modifications causes a significant disruption in the development experience. Specifically, when the desktop application restarts, it causes a loss of focus in VSCode, which is detrimental to productivity.

### Describe the solution you'd like

I propose the introduction of a new command-line option, such as wails dev --browser-only, which would launch the development server without opening the desktop application window. This would allow for reloads triggered by code changes to occur within the browser, preventing the desktop application from restarting and avoiding the loss of focus in VSCode.

### Describe alternatives you've considered

N/A - The main issue is the loss of focus in VSCode during the development process when the desktop application restarts. An alternative solution has not been identified that addresses this specific problem.

**Comment by leaanthony** [comment]
I understand your reasoning for this, but there's a fundamental issue with developing in the browser at all. It was originally intended to allow people to use their favourite browser extensions. Unfortunately, it's also easy to develop against browser APIs that may not exist in the webview implementations leading to apps working fine in Dev mode and not the built binary. If you do a search you will find _many_ such tickets. This has led us to reconsider having a browser Dev mode at all in v3, as you can connect to vite for frontend development anyway. It is confusing to developers why their app works in a browser and not compiled. The focus of development should be on the app as that's what's being released.

**Comment by m0a** [comment]
Thank you for the detailed explanation. I now understand the potential issues with developing against browser APIs that may not be supported in the webview, and the confusion it can cause when an app works in development mode but not in the compiled binary. Given this insight and the possibility to use Vite for frontend development, I agree that pursuing a browser-only development mode may not be the best approach. I appreciate the time you've taken to address my concerns, and I will close this issue now. Looking forward to more improvements in Wails and will continue to support the project.
