### ISSUE TITLE
Propose Change: Default Module Name to Project Name

### ISSUE THREAD

**Issue by Owbird** [wailsapp/wails#3277]
### Describe the solution you'd like

The solution I propose is to modify the Go Wails project templates to automatically generate a `go.mod` file with at least the project name as the module name, instead of the default placeholder "changeme".

**Comment by leaanthony** [comment]
Feel free to create a PR that does this. I would suggest having it as a CLI parameter.

**Comment by PylotLight** [comment]
This could also benefit templates that include project imports so the imports are templated using the provided arg.
E.g my htmx template that imports components using the module name could benefit from the templated name.

**Comment by Twacqwq** [comment]
Hi @leaanthony,

I tried adding a CLI parameter to the init command that changes the default module name to the project name. 
Could you please take a moment to review it when you have the time? thx.
