### ISSUE TITLE
Adding Linux Options to main.go kills the frontend.

### ISSUE THREAD

**Issue by FooterManDev** [wailsapp/wails#3283]
### Description

When configuring Linux options in the main func, the app goes blank. The Troubleshooting Guide did not help, because I have the proper code.
I confirm this is specifically a problem with the Linux Options, because removing it from the main func fixes the blank problem. It is not caused by my Icon var underneath the assets var. You can see it [here](https://github.com/FooterMan15/Tritium/blob/main/main.go#L12).
Even including Linux options with nothing configured makes the app blank.
When viewing the app in a browser, the UI shows just fine.

### To Reproduce

Add Linux options to the Main function.
Launch application with `wails dev`

### Expected behaviour

I expected to have an app that has a UI.

### Screenshots

![image](https://github.com/wailsapp/wails/assets/71946346/60598ec5-be82-4ffa-892e-f81f362ba44c)

### System Details

```shell
# Wails
Version         | v2.8.0
Package Manager | pacman

# System
┌──────────────────────────────────────────────────────────────────────────────────────┐
| OS           | EndeavourOS                                                           |
| Version      | Unknown                                                               |
| ID           | endeavouros                                                           |
| Go Version   | go1.22.0                                                              |
| Platform     | linux                                                                 |
| Architecture | amd64                                                                 |
| CPU          | AMD Ryzen 5 3600 6-Core Processor                                     |
| GPU 1        | Unknown                                                               |
| GPU 2        | TU106 [GeForce RTX 2060 Rev. A] (NVIDIA Corporation) - Driver: nvidia |
| Memory       | 32GB                                                                  |
└──────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version     |
| *docker    | docker       | Available | 1:25.0.2-1  |
| gcc        | gcc          | Installed | 13.2.1-5    |
| libgtk-3   | gtk3         | Installed | 1:3.24.41-1 |
| libwebkit  | webkit2gtk   | Installed | 2.42.5-2    |
| npm        | npm          | Installed | 10.4.0-2    |
| pkg-config | pkgconf      | Installed | 2.1.0-2     |
└────────────── * - Optional Dependency ──────────────┘

# Diagnosis
Optional package(s) installation details: 
  - docker: sudo pacman -S docker

 SUCCESS  Your system is ready for Wails development!
```

### Additional context

The Linux options do work, I can set the application icon.
This application uses Vue, not built from a template.
https://github.com/FooterMan15/Tritium

**Comment by atterpac** [comment]
Are there any errors in the console when running?
Have you tried adjusting your web gpu policy? Arch distros typically have some issue with rendering and that's the most common fix 
https://wails.io/docs/reference/options#webviewgpupolicy

**Comment by FooterMan15** [comment]
Aha, changing the Policy to Never fixed my issue. Thank you.
