### ISSUE TITLE
chunk js css

### ISSUE THREAD

**Issue by ewener** [wailsapp/wails#329]
I use Vue as the front-end framework,many chunk JS CSS will be generated,but walls can only use one JS and CSS,what should I do?

**Comment by coolhlm** [comment]
I seem to have the same problem. when I used 'wails serve' and 'npm run dev',browser can work normally, but when I used 'waves build', I get a blank page . It seems that the CSS and JS files can't be found. How can I fix this issue.Thank you.

**Comment by leaanthony** [comment]
> I use Vue as the front-end framework,many chunk JS CSS will be generated,but walls can only use one JS and CSS,what should I do?

Hi. There will be no support for chunking in Wails. The templates come with everything you need to set up a project. They bundle everything in a way that can be used.

**Comment by leaanthony** [comment]
> I seem to have the same problem. when I used 'wails serve' and 'npm run dev',browser can work normally, but when I used 'waves build', I get a blank page . It seems that the CSS and JS files can't be found. How can I fix this issue.Thank you.

Please open up another ticket with more information. Thanks.
