### ISSUE TITLE
Hi, I submitted a PR for a security issue and a fix patch, please take a look.

### ISSUE THREAD

**Issue by bayuncao** [wailsapp/wails#3297]
### Describe the solution you'd like

Hi, I submitted a PR for a security issue and a fix patch, please take a look.
https://github.com/wailsapp/wails/security/advisories/GHSA-c5g2-ffp7-7vgx

**Comment by leaanthony** [comment]
I've looked and responded. I don't believe it's a security issue at all. Feel free to reply on the security ticket.
