### ISSUE TITLE
v3: Incorrect 'startURL' with 'FRONTEND_DEVSERVER_URL' present

### ISSUE THREAD

**Issue by joshdrake** [wailsapp/wails#3298]
### Description

When `FRONTEND_DEVSERVER_URL` is present (eg: `wails3 dev` when using `vite`), `assetserver.GetStartURL` incorrectly ignores the user-provided `URL`, leading to the default path always being requested.

As well, when `FRONTEND_DEVSERVER_URL` is present, the package-global `baseURL` is modified in `GetStartURL`, and subsequent calls to `GetStartURL` can lead to incorrectly formatted `Host` values, due to incorrectly joining the `Host` of the `baseURL` and the `Port` parsed from `FRONTEND_DEVSERVER_URL`.

### To Reproduce

1. Create two windows:

```	
app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
    Title: "Window 1",
    URL: "/win-1",
})

app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
    Title: "Window 2",
    URL: "/win-2",
})
```

2. `wails3 dev` with a default template using vite
3. Observe the `path` requested to the vite development server
4. Observe that one of the two windows (non-deterministic) will not load, due to the URI being incorrect (eg: the URI will be something like `wails://[localhost:5173]:5173`)

### Expected behaviour

Multiple windows are opened correctly with the provided `URL` when using a development server for assets (eg: vite).

### System Details

```shell
# Build Environment
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | 4467a1ffa273059da10b45bbfd38c656f9e6dc28
Modified       | true
-buildmode     | exe
-compiler      | gc
CGO_CFLAGS     |
CGO_CPPFLAGS   |
CGO_CXXFLAGS   |
CGO_ENABLED    | 1
CGO_LDFLAGS    |
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1
GOARCH         | amd64
GOOS           | linux
vcs            | git
vcs.modified   | true
vcs.revision   | 4467a1ffa273059da10b45bbfd38c656f9e6dc28
vcs.time       | 2024-03-04T11:38:21Z

# System
Name         | Fedora Linux
Version      | 38
ID           | fedora
Branding     | 38 (Workstation Edition)
Platform     | linux
Architecture | amd64
gcc          | 13.2.1
libgtk-3     | 3.24.41
libwebkit    | 2.42.5
npm          | 10.2.3
pkg-config   | 1.8.0
CPU          | AMD Ryzen 5 7600X 6-Core Processor
GPU 1        | Raphael (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu
GPU 2        | Navi 23 [Radeon RX 6600/6600 XT/6600M] (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu
Memory       | 64GB

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

**Comment by stffabi** [comment]
The PR to fix this has been merged.
