### ISSUE TITLE
varly app domain expired

### ISSUE THREAD

**Issue by sougiovn** [wailsapp/wails#3304]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

The varly app example in the introduction is leading to an expired domain: https://varly.app/

![image](https://github.com/wailsapp/wails/assets/4052932/4d8cb08b-5a9d-4d5a-bfa3-5ff92e7ba683)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Thanks for letting us know. Fixed.
