### ISSUE TITLE
Linux WebRTC not supported

### ISSUE THREAD

**Issue by bh90210** [wailsapp/wails#332]
Edge and Webkit both support WebRTC but atm webkitgtk does not.

_from https://webkitgtk.org/_
_"Support for audio and video
The web isn’t just for reading words. We drive development of the GStreamer WebKit backend and support full integration of video into page content and the HTML canvas element. Currently we are working to finish support for WebAudio and WebRTC."_

so there is nothing we can really do but wait.
nevertheless I'm opening the issue to a. document the bug and b. keep track of the updates with `webkitgtk`

**Comment by winwisely99** [comment]
Requires the zserge lib that is not on the master branch.

I am not sure if it stable yet though ?

Anyone tried ?

**Comment by leaanthony** [comment]
@winwisely99 Did you try it? We could add it to v2.

**Comment by bh90210** [comment]
webRTC support (or lack thereof on Linux) has to do with webkitgtk and its maintainers, I am afraid.

**Comment by amelkikh** [comment]
> webRTC support (or lack thereof on Linux) has to do with lib webkitgtk and its maintainers, I am afraid.

What are the reasons for this concern?
