### ISSUE TITLE
init failed

### ISSUE THREAD

**Issue by soluty** [wailsapp/wails#333]
**Description**

wails init

Wails v1.0.1 - Initialising project
The name of the project (My Project): ddd
Project Name: ddd
The output binary name (ddd):
Output binary Name: ddd.exe
Project directory name (ddd):
Project Directory: ddd
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
> Generating project...
- Building project (this may take a while)...
Wails v1.0.1 - Building Application

> Ensuring frontend dependencies are up to date (This may take a while)
> Building frontend...
/ Ensuring Dependencies are up to date...build github.com/wailsapp/wails/lib/renderer/webview: cannot load github.com/wailsapp/wails/lib/renderer/webview: no Go source files

! Ensuring Dependencies are up to date...
Error: exit status 1

! exit status 1
Error: exit status 1

**To Reproduce**
Steps to reproduce the behaviour:
1. type wails init

**Expected behaviour**
wails can init correct 

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 5.1.0 |
| Npm           | 6.12.0 |
| Node          | v12.13.0
 |

**Additional context**
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flag
s=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcx
x-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdrag
on.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

**Comment by leaanthony** [comment]
That's odd. Do the other templates work?

**Comment by soluty** [comment]
also not work

**Comment by soluty** [comment]
my system disabled windows hyper-v and use virtualBox  for vm.  dose this has any effect?

**Comment by leaanthony** [comment]
None. Try using the latest pre-release: `wails update -pre`
