### ISSUE TITLE
WebKit2-GTK4.1 support

### ISSUE THREAD

**Issue by ad-on-is** [wailsapp/wails#3345]
### Is your feature request related to a problem? Please describe.

I'm trying to publish to Flathub, and the folks there are very strict on their guidlines.

I can build a wails app successfully using the org.gnome.Sdk 3.38, since it comes with webkit2gtk-4.0, but 3.38 is EOL and not supposed to be used.
However, when I try to build it on org.gnome.Sdk 46, which uses webkitgtk.1, wails refuses to build since 4.0 is missing.

### Describe the solution you'd like

Add support for webkit2gtk-4.1+

**Comment by leaanthony** [comment]
Yeah, we can totally look at this 👍

**Comment by hypolas** [comment]
I use Ubuntu 20.04. 

I had same problem.

Do you have a solution to bypass waiting?

Best regards.

**Comment by atterpac** [comment]
Fixed on master in #3461 build with `-tags webkit2_41`
