### ISSUE TITLE
Unable to maximize/minimize window

### ISSUE THREAD

**Issue by No-Cash-7970** [wailsapp/wails#3355]
### Description

When using Wails v3-alpha, the window does not allow for being minimized or maximized and the buttons are missing. Only closing the window is allowed.

### To Reproduce

Install and run a new Wails3 project using the _Your First Application_ guide

### Expected behaviour

The window can be minimized and maximized using the window buttons.

### Screenshots

Windows 11
![image](https://github.com/wailsapp/wails/assets/105998824/7652911f-0c11-4534-899b-081ad126d29d)

Linux (from someone else who has the same issue)
![mc2VTh](https://github.com/wailsapp/wails/assets/105998824/97cd51cf-311d-47e1-ae99-90a649507dcd)

### Attempted Fixes

- Tried removing wails3 and reinstalling it
- Removed all window options

### System Details

```shell
# Build Environment
Wails CLI    | v3.0.0-alpha.4

Go Version   | go1.22.1
Revision     | 238b9ede787b693705fc0a9a8f36da50ac44f6b2
Modified     | false
-buildmode   | exe
-compiler    | gc
CGO_ENABLED  | 0
GOAMD64      | v1
GOARCH       | amd64
GOOS         | windows
vcs          | git
vcs.modified | false
vcs.revision | 238b9ede787b693705fc0a9a8f36da50ac44f6b2
vcs.time     | 2024-03-26T10:11:35Z

# System
Name              | Windows 10 Pro
Version           | 2009 (Build: 22621)
ID                | 22H2
Branding          | Windows 11 Pro
Platform          | windows
Architecture      | amd64
Go WebView2Loader | true
NSIS              | Not Installed
WebView2 Version  | 122.0.2365.92
CPU               | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU 1             | NVIDIA Quadro RTX 5000 with Max-Q Design (NVIDIA) - Driver: 30.0.14.7284
GPU 2             | Intel(R) UHD Graphics 630 (Intel Corporation) - Driver: 27.20.100.8681
Memory            | 48GB
```

**Comment by leaanthony** [comment]
Fixed on the `v3-alpha` branch 👍 Thanks for reporting.
