### ISSUE TITLE
Compilation failure for v3-alpha version

### ISSUE THREAD

**Issue by bensema** [wailsapp/wails#3356]
### Description

  ERROR   task: Failed to run task "build": exit status 1

### To Reproduce

1. wails3 init -n myfirstapp
2. wails3 build

### Expected behaviour

➜  work cd myfirstapp 
➜  myfirstapp ls
Inter Font License.txt build                  go.mod                 greetservice.go
Taskfile.yml           frontend               go.sum                 main.go
➜  myfirstapp wails3 build

 WARNING  `wails3 build` is an alias for `wails3 task build`. Use `wails task` for better control and more options.
task: Task "generate:icons" is up to date
task: [go:mod:tidy] go mod tidy
task: [generate:bindings] wails3 generate bindings -silent
task: [install:frontend:deps] npm install

added 12 packages, and audited 13 packages in 6s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
task: [build:frontend] npm run build -q

> frontend@0.0.0 build
> vite build --minify false --mode development

vite v5.2.7 building for development...
✓ 21 modules transformed.
dist/index.html                 1.25 kB │ gzip: 0.62 kB
dist/assets/index-BxUD4Cb8.js  36.61 kB │ gzip: 8.13 kB
✓ built in 255ms
task: [build:darwin] go build -gcflags=all="-N -l" -o bin/myfirstapp
# github.com/wailsapp/wails/v3/pkg/application
../wails/v3/pkg/application/webview_window_darwin.go:67:23: error: property 'textInteractionEnabled' not found on object of type 'WKPreferences *'
                        config.preferences.textInteractionEnabled = *preferences.TextInteractionEnabled;
                                           ^
../wails/v3/pkg/application/webview_window_darwin.go:73:33: error: property 'elementFullscreenEnabled' not found on object of type 'WKPreferences *'
             config.preferences.elementFullscreenEnabled = *preferences.FullscreenEnabled;
                                ^
2 errors generated.
  ERROR   task: Failed to run task "build": exit status 1

### Screenshots

<img width="1147" alt="截屏2024-03-30 09 12 48" src="https://github.com/wailsapp/wails/assets/5534112/34e62d40-abda-4c0e-a8f5-77442833e317">

### System Details

```shell
➜  ~ wails3 doctor       

                                
          Wails Doctor          
                                

                                                                                
# Build Environment
Wails CLI    | v3.0.0-alpha.4
                          
Go Version   | go1.22.0                                
Revision     | c839c053cb71c3e07c38c0307157a931829de1d1
Modified     | false                                   
-buildmode   | exe                                     
-compiler    | gc                                      
CGO_CFLAGS   |                                         
CGO_CPPFLAGS |                                         
CGO_CXXFLAGS |                                         
CGO_ENABLED  | 1                                       
CGO_LDFLAGS  |                                         
GOAMD64      | v1                                      
GOARCH       | amd64                                   
GOOS         | darwin                                  
vcs          | git                                     
vcs.modified | false                                   
vcs.revision | c839c053cb71c3e07c38c0307157a931829de1d1
vcs.time     | 2024-03-29T10:44:59Z                    

# System
Name            | MacOS                                   
Version         | 13.3.1                                  
ID              | 22E261                                  
Branding        | Ventura                                 
Platform        | darwin                                  
Architecture    | amd64                                   
Apple Silicon   | unknown                                 
CPU             | Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Xcode cli tools | 2397                                    
CPU             | Unknown                                 
GPU             | Unknown                                 
Memory          | Unknown                                 

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏

**Comment by kapiw04** [comment]
> https://v3alpha.wails.io/getting-started/feedback

https://v3alpha.wails.io/feedback/
