### ISSUE TITLE
Low framerate on my Wails App. Is it WebView?

### ISSUE THREAD

**Issue by Blankeos** [wailsapp/wails#3364]
### Description

The FPS seems to be capped at 29-30. But on the Arc Browser, it seems to run 125 FPS.

### To Reproduce

Don't really have a way to reproduce, but you can try this repo: https://github.com/Blankeos/snom-sql

### Expected behaviour

Higher FPS.

### Screenshots

It's kind of capped at 30fps (right one)

Here's a vid:
https://github.com/wailsapp/wails/assets/38070918/9164d192-5a87-4ee6-b0e9-86822aedb292

### Attempted Fixes

I looked into this but don't know how to implement it: https://stackoverflow.com/questions/7422427/android-webview-slow

Might be related to webview capping my framerate. This is for Android though. I'm on a Mac so I don't know.

### System Details

```shell
# Wails
Version | v2.8.0

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.3                                                                                                                        |
| ID           | 23D56                                                                                                                       |
| Go Version   | go1.22.1                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | arm64                                                                                                                       |
| CPU          | Apple M3 Max                                                                                                                |
| GPU          | Chipset Model: Apple M3 Max Type: GPU Bus: Built-In Total Number of Cores: 30 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 36GB
```

### Additional context

```ts
// Code for framerate 
	import { onMount } from 'svelte';

	let before: number;
	let now: number;
	let fps: number;
	onMount(() => {
		before = Date.now();
		fps = 0;
		requestAnimationFrame(function loop() {
			now = Date.now();
			fps = Math.round(1000 / (now - before));
			before = now;
			requestAnimationFrame(loop);
		});
	});
```

**Comment by Blankeos** [comment]
DAMN.

<img width="488" alt="image" src="https://github.com/wailsapp/wails/assets/38070918/25bddf05-623b-42e8-9e12-ec0ee6e32eed">

It was Safari on Low Power Mode smh: https://stackoverflow.com/questions/74071316/safari-requestanimationframe-running-at-30fps

It is good now:
<img width="1022" alt="image" src="https://github.com/wailsapp/wails/assets/38070918/5b820415-6767-44a2-bfb8-53c5af4f9fe2">

**Comment by leaanthony** [comment]
We'll consider helping more on this front in v3 with this API https://developer.apple.com/documentation/foundation/nsprocessinfo/1617047-lowpowermodeenabled
