### ISSUE TITLE
Border in fullscreen application

### ISSUE THREAD

**Issue by VladislavSournine** [wailsapp/wails#337]
I have fullscreen application. All works fine in dev-mode. In chrome/firefox - I have no problem. But in fullscreen - I got black borders at screen. And view stay draggable for user

Steps to reproduce the behaviour:
1. Get screen size of your monitor (1024/768). 
2. Create Fullscreen application with same resolution
3. Create css style for screen size
4. Check view in your browser (wails serve mode)
5. Confirm - you haven't black border - at left and top line
6. Build application 
7. Run application.
8. You'll see black line at left side, up side.
9. Your design - a little bigger then ssreen 

**Expected behaviour**
Not to see unexpected border in fullscreen application

**Screenshots**

![Screenshot from 2020-01-22 11-36-31](https://user-images.githubusercontent.com/41969/72883171-83e5d180-3d0c-11ea-9ff7-ba58b10678d6.png)

**System Details**
Ubuntu 18.04, Go version go1.13.4 linux/amd64. React 16.12.0

**Additional context**
No additiona context

**Comment by leaanthony** [comment]
Are you sure this isn't a CSS issue?

**Comment by VladislavSournine** [comment]
I think no.
Chrome/Firefox - works fine with this css.
Webview - no.
In css:

> body, html {
  height: 768px;
  width: 1024px;
}

and
>@font-face {
    font-family: GothamPro;
    src: url("fonts/GothamPro.eot") format("eot");
    src: url("fonts/GothamPro.ttf") format("ttf");
    src: url("fonts/GothamPro.woff") format("woff");
}

body {
    font-family: GothamPro, serif;
}

But no font in builded application... May be this problem?

**Comment by leaanthony** [comment]
It's perhaps the default CSS.

Try this:
```
* {
  padding: 0;
  margin: 0;
}
```

**Comment by VladislavSournine** [comment]
Wow. Thanks!
This time - works fine.
yesterday - not work. Hard day... ;-)
Thank you!
