### ISSUE TITLE
Frameless Window

### ISSUE THREAD

**Issue by tlscipher** [wailsapp/wails#338]
Is it possible to add an option for frameless windows? In electron you can pass a parameter to indicate you want a window without the default frame/title bar. Would be great if we could use that here as well.

**Comment by leaanthony** [comment]
This is something I'll stick in the backlog for V2. The general strategy will be to provide a feature flag system, where we perhaps implement something like this on one platform initially and over time extend that to the other platforms. What platform are you using primarily?

**Comment by leaanthony** [comment]
@mehtaabGill what OS are you targeting?

**Comment by zhuqiyun** [comment]
> @mehtaabGill what OS are you targeting?

arm9，linux3.10

**Comment by leaanthony** [comment]
I've added it to the V2 backlog :+1: 
Out of interest, how do you think you will move a frameless window?

**Comment by amelkikh** [comment]
Hi! 
I'm coding app for Win10. 
Please consider this platform too.

**Comment by chenxun450** [comment]
It hard to move a browser without its title...    
How should we overwrite the Mouse Event like Qt

**Comment by leaanthony** [comment]
By allowing you to specify any elements that allow moving via a special attribute.

**Comment by leaanthony** [comment]
This has already been implemented in v2. Porting to Mac and windows soon.

**Comment by drharryhe** [comment]
eager to see the feature on v2 (for mac and windows), when v2 will be released as plan?

**Comment by leaanthony** [comment]
v2 for Mac is in alpha and I guess not too far off beta. Then linux, then windows. No firm release date yet.

**Comment by afocus** [comment]
> Hi! I'm coding app for Win10. Please consider this platform too.

me too
