### ISSUE TITLE
Is there any way for applications built with wails to support windows7?

### ISSUE THREAD

**Issue by sundaqiang** [wailsapp/wails#3390]
### Description

Can applications built with wails support windows7? Check to see if Tauri can support windows7!

### To Reproduce

Can applications built with wails support windows7? Check to see if Tauri can support windows7!

### Expected behaviour

Can applications built with wails support windows7? Check to see if Tauri can support windows7!

### System Details

```shell
Can applications built with wails support windows7? Check to see if Tauri can support windows7!
```

**Comment by leaanthony** [comment]
We don't support windows 7.

**Comment by sundaqiang** [comment]
> We don't support windows 7.


https://github.com/wailsapp/wails/issues/1063

I looked it up and finally implemented windows7. Do you remove it now? If so, which version is available?
