### ISSUE TITLE
window.runtime should be available to files other than index.html

### ISSUE THREAD

**Issue by philc** [wailsapp/wails#3393]
On launch, index.html has window.runtime. Any other HTML file (e.g. settings.html) has an undefined window.runtime. This is the case if settings.html is opened on a dev port (http://localhost:34115/settings.html) or navigated to in the Wails frontend app via window.location.

This is important when splitting the screens of an app into separate webpages; non-index.html pages may need access to window.runtime.

As a workaround, one can make the whole app a SPA, but that's extra/unnecessary complexity.

### Additional context

Wails 2.8.1, MacOS 14.4.1.

**Comment by leaanthony** [comment]
Does this work for you?
https://wails.io/docs/guides/frontend

**Comment by philc** [comment]
That is exactly what I needed. I read through several doc pages but didn't manage to discover the Frontend guide. Thank you! Sorry for the noise.

**Comment by leaanthony** [comment]
All good 😎
