### ISSUE TITLE
when will wails v3 stable version be released?

### ISSUE THREAD

**Issue by Nyx2022** [wailsapp/wails#3396]
### Is your feature request related to a problem? Please describe.

can i know when will wails v3 stable version be released?

### Describe the solution you'd like

can i know when will wails v3 stable version be released?

### Describe alternatives you've considered

can i know when will wails v3 stable version be released?

### Additional context

can i know when will wails v3 stable version be released?

**Comment by leaanthony** [comment]
When it's ready.
