### ISSUE TITLE
[VueJS] Unable to iterate a list on Windows. It works fine on MacOS and Linux.

### ISSUE THREAD

**Issue by grvlle** [wailsapp/wails#340]
**Description**
Unable to iterate a list on Windows. It works fine on MacOS and Linux.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://vuejs.org/v2/guide/list.html
2. Pick one or multiple ways of iterating a list.
3. Wails init
4. Try to iterate one of the lists.

**Expected behaviour**
The ability to iterate and present the results of the list of objects in a loop using v-for.

**System Details**
```
❯ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/vito/Code/Go/bin"
GOCACHE="/home/vito/.cache/go-build"
GOENV="/home/vito/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vito/Code/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build388018050=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by grvlle** [comment]
Windows enviornment where the problem is present. 
```
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build554396558=/tmp/go-build -gno-record-gcc-switches

```

**Comment by grvlle** [comment]
Worth noting is that I got it working for a moment, tried to implement it in a more robust way, that broke the component. When restoring the code to when it was working, the component i still broken. I'm also unable to bring up the JS console using Shift+Esc

**Comment by grvlle** [comment]
Finally managed to access the JS console and noticed IE11 didn't play nice with ES6. Had to opt out from using list = [...var].

**Comment by leaanthony** [comment]
Glad you got some use out of the windows console. At least that's SOME ROI :smile: Any windows quirks are 99% to do with the renderer. We are really hoping to switch to edgeHTML for v2, if not edge chromium.

**Comment by grvlle** [comment]
Haha, thank God! Can't wait. 🙌🙌🙌

**Comment by masterdubs** [comment]
Is there any planned date for this implementation?  IE11 is so full of bug :)
