### ISSUE TITLE
Changing build platform

### ISSUE THREAD

**Issue by salmi3d** [wailsapp/wails#341]
Greetings to wails team!
Sorry, I don't find any other place to ask a question. I'm developing wails app on win x64. Is it possible to build exe for win x32 platform? Thanks in advance!

**Comment by leaanthony** [comment]
Doing this will probably not be possible with V1 I'm afraid. How do you think it might work? 2 installations of TDM?

**Comment by salmi3d** [comment]
I don't know, just asking for such possibility.

**Comment by leaanthony** [comment]
Hi @salmi3d - You may be interested in the PR recently raised. We're looking at integrating xgo and it seems to work. We would love you to test if you can!
