### ISSUE TITLE
Let to configure wailsbridge websocket url

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#342]
As seen in file runtime/assets/bridge.js and wails/lib/renderer/bridge.go there are hard coded web socket url and port.

We need to change it.

Can you add ability to configure this?

**Comment by tmclane** [comment]
If you look at the `develop` branch you will see that it is in fact actually set to whatever the browser's `window.location.hostname` value is:

https://github.com/wailsapp/wails/blob/develop/runtime/assets/bridge.js

The port isn't configurable at this time.

**Comment by leaanthony** [comment]
Can we close this?

**Comment by konez2k** [comment]
As a temporary workaround, open the inspector and change the websocket URL manually:

```
window.wailsbridge.wsURL = "ws://custom_ip_or_host:34115/bridge"
```

**Comment by leaanthony** [comment]
Added this to https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements - closing.
