### ISSUE TITLE
atomicgo.dev is not reach anymore, so can´t install wails

### ISSUE THREAD

**Issue by gaetan1903** [wailsapp/wails#3448]
### Description

I  want to install wails but atomicgo.dev is not reached so error in installation

### To Reproduce

go install github.com/wailsapp/wails/v2/cmd/wails@latest

### Expected behaviour

wails installed but i have error 

go: downloading atomicgo.dev/cursor v0.1.1
go: downloading atomicgo.dev/keyboard v0.2.8
../../go/pkg/mod/github.com/pterm/pterm@v0.12.49/area_printer.go:6:2: unrecognized import path "atomicgo.dev/cursor": https fetch: Get "https://atomicgo.dev/cursor?go-get=1": dial tcp 88.198.43.28:443: connect: connection refused
../../go/pkg/mod/github.com/pterm/pterm@v0.12.49/interactive_confirm_printer.go:9:2: unrecognized import path "atomicgo.dev/keyboard": https fetch: Get "https://atomicgo.dev/keyboard?go-get=1": dial tcp 88.198.43.28:443: connect: connection refused
../../go/pkg/mod/github.com/pterm/pterm@v0.12.49/interactive_confirm_printer.go:10:2: unrecognized import path "atomicgo.dev/keyboard": https fetch: Get "https://atomicgo.dev/keyboard?go-get=1": dial tcp 88.198.43.28:443: connect: connection refused

### System Details

```shell
wails command not found
```

**Comment by leaanthony** [comment]
Might be a local/temporary problem. Working ok here: 
```
PS D:\GolandProjects> go install github.com/wailsapp/wails/v2/cmd/wails@latest
PS D:\GolandProjects> 
```
Feel free to reopen if you think this is an issue with the project itself 👍

**Comment by gaetan1903** [comment]
yes, the site is up now and installation works
