### ISSUE TITLE
Errors are not obvious because command output is hidden

### ISSUE THREAD

**Issue by moqmar** [wailsapp/wails#345]
**Description**
I mistakenly used `parcel script.js` as a build command, and waited around 15 minutes before noticing that the command starts a webserver (duh), so I changed it to `parcel build script.js`. That would have been way faster to debug if Wails just forwarded STDOUT & STDERR directly instead of showing that beautiful but unneccessary spinner.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build a Wails application which doesn't have node_modules yet
2. It will take a long time without any log messages
3. The log messages will show up once "npm install" has completed, and in the wrong order, and not at all if the process is taking indefinitely long for some reason

**Expected behaviour**
The log messages show up at the time they occur.

**Additional context**
In https://github.com/wailsapp/wails/blob/79188c503f9ab4518bf2c303f4ad28016100b1eb/cmd/shell.go#L19 it should just assign os.Stdout/Stderr to cmd's Stdout/Stderr IMO - hiding the output doesn't really make it any more user-friendly.

**Comment by leaanthony** [comment]
The output is hidden because of console spam. Errors are surfaced if they occur. As your mistake didn't result in an error, it wasn't surfaced. There's an argument for a verbose flag though.

**Comment by leaanthony** [comment]
There's a `-verbose` flag on the `develop` branch now. It will be part of the next pre-release.

**Comment by leaanthony** [comment]
`v1.0.3-pre1` has the change.
