### ISSUE TITLE
Broken link found at docs/guides/obfuscated/

### ISSUE THREAD

**Issue by xob0t** [wailsapp/wails#3450]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

https://wails.io/docs/guides/obfuscated/

> These settings may be persisted in your [project config](https://wails.io/docs/guides/reference/project-config).

Leads to "Page Not Found"

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Thanks! A fix will be available next release 👍
