### ISSUE TITLE
Wails crash

### ISSUE THREAD

**Issue by VladislavSournine** [wailsapp/wails#346]
**Description**
After (or when) reac app is reloading - got panic crash

**To Reproduce**
1. You need to have application with not-fash api requests, emits.
2. You need to update js code when wails serve, and (possible) works with one of request, or try to emit socket.
3. Got error

`panic: concurrent write to websocket connection

goroutine 514 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00030fa58, 0xc000554801, 0xc0005548f3, 0x0, 0xd, 0x90, 0xc000554870)
	/home/vladislav/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x612
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0002fedc0, 0x1, 0xc000554870, 0x83, 0x90, 0x90, 0x1)
	/home/vladislav/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:763 +0x23d
github.com/wailsapp/wails/lib/renderer/bridge.(*session).sendMessage(0xc000135810, 0xc0005547e0, 0x83, 0x0, 0x0)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:39 +0xef
github.com/wailsapp/wails/lib/renderer/bridge.(*session).evalJS(...)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:88
github.com/wailsapp/wails/lib/renderer/bridge.(*session).Callback(0xc000135810, 0xc000554750, 0x82, 0x0, 0xc0005546c0)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:82 +0x7d
github.com/wailsapp/wails/lib/ipc.(*Manager).SendResponse.func1(0xc0003c9560, 0xc0003c9560, 0x1)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/manager.go:171 +0xdd
github.com/wailsapp/wails/lib/ipc.(*ipcMessage).ReturnSuccess(0xc000080580, 0x9c9540, 0xc0003c93f8, 0xc00030fd58, 0xc00030ff30)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/message.go:92 +0xac
github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1.1(0xc99f60, 0xc0000d40a0, 0xc000182c20, 0xc0000c02a0, 0xc000010138)
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/manager.go:75 +0x333
created by github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1
	/home/vladislav/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/mana`

**System Details**
Linux Mint 19.2 Cinnamon
Go  go version go1.13.4 linux/amd64
Wails 1.0.2
Browser for dev - latest Chrome

**Comment by tmclane** [comment]
Howdy.  I am looking into this bug but so far I can not recreate it.
Can you provide more information on your steps for reproduction?

I did the following:

- go get -u github.com/wailsapp/wails/cmd/wails
- wails init 
```
wails init
Wails v1.0.2 - Initialising project

The name of the project (My Project): ServerTest
Project Name: ServerTest
The output binary name (servertest): 
Output binary Name: servertest
Project directory name (servertest): 
Project Directory: servertest
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  5: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 2
Template: React JS
✓ Generating project...
✓ Building project (this may take a while)...
Project 'ServerTest' built in directory 'servertest'!
```
- cd servertest
- wails serve
- `cd frontend`enter `frontend`

**Comment by VladislavSournine** [comment]
@tmclane I'll try to repeat it with 100% guarantee.
Possible - I think - it's long working backend.Api, which send data (Emit) to reloading react.
But - I'm not sure...
If you can help me with precision detecting problem - (which socket message?) and debug it - I'll be faster...

**Comment by VladislavSournine** [comment]
@tmclane Problem with js state:
- when update js code - some redux state has been droped. But start API request - working. With wrong (nil) paramaters. So. This is my fault. Sorry
