### ISSUE TITLE
CSS Transparency Effect Causes Ghosting

### ISSUE THREAD

**Issue by TaterTotX** [wailsapp/wails#3474]
### Description

WebviewIsTransparent: true,

html {
    background-color: rgba(123, 140, 157, 0);
    text-align: center;
}

I'm experiencing a ghosting effect in my built app that doesn't occur in the web display. When I apply a transparency effect to an element in CSS, such as a background or a border, a faint duplicate of the element appears to trail behind it as it moves. This issue is noticeable during animations or when the element has a moving background.

### To Reproduce

Apply transparency to an element using CSS, e.g., background-color: rgba(0, 0, 0, 0.5);
Animate or move the element, such as changing its position or opacity.

### Expected behaviour

The transparent element should move smoothly without any ghosting or trail effect, similar to the behavior in the web display.

### Screenshots

<img width="440" alt="image" src="https://github.com/wailsapp/wails/assets/102522568/684c49aa-7fe4-433b-92e2-a4ba8968c703">

### System Details

```shell
macos 14.2 (23C64)
```

**Comment by leaanthony** [comment]
I can't tell what element is being ghosted here but I do know it's likely nothing to do with Wails.

**Comment by TaterTotX** [comment]
> I can't tell what element is being ghosted here but I do know it's likely nothing to do with Wails.

Steps to Reproduce

wails init -n ghost_test -t vue

wails dev


app.vue 
<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>
<template>
</template>
<style>
</style>


func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "ghost_test",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 0},
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},

		Mac: &mac.Options{
			WebviewIsTransparent: true,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}

<img width="1096" alt="Pasted Graphic" src="https://github.com/wailsapp/wails/assets/102522568/84bd4560-12eb-498a-901f-ce8073b8e191">
