### ISSUE TITLE
Small Webview window running app and small text for buttons. Dev build correct size

### ISSUE THREAD

**Issue by billacw** [wailsapp/wails#348]
**Description**

Build the app with width=1000 and height=800 but running the app displays a small main window

**To Reproduce**
Steps to reproduce the behaviour:
Wails code
	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 800,
		Title:  "RMBLConfig v1.0",
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})

**Expected behaviour**
The app to have the correct window size

**Screenshots**
App run from command line after build
(https://drive.google.com/file/d/1rlWXS4ohiSZBwzCWDYRXvSvWg6d2q-wl/view?usp=sharing)
Wrong size window, button fonts shrunk

Browser view running with npm run start
(https://drive.google.com/file/d/18C33HRz8Ds8pTFx9_Wyg5KCScHTeMuVo/view?usp=sharing)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2-pre2 |
| Go Version    | go1.13 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.12.1 |
| Node          | v12.13.1
 |

**Comment by leaanthony** [comment]
It probably won't fix your issue, but you should probably upgrade to v1.0.2.

For Windows, you need to design your app as if you're targeting IE9. Have you tried running `wails serve` and using IE to test?

**Comment by billacw** [comment]
here is the initial project doing the same thing. I think it might be my Windows display settings. I have "Scale and layout" set to 200%
Startup project in browser
(https://drive.google.com/file/d/1v5hXdZ73p3RwvZZOxqDfYOTANTFMbCmr/view?usp=sharing)

Startup project run as an app
(https://drive.google.com/file/d/168Ve7FKRzfJ4oBXzLcvO1AnfqdabD5OE/view?usp=sharing)

windows 10 display settings
(https://drive.google.com/file/d/1Ln8GZmVeEeD6xNi_0eEdb-ths6TeIPJC/view?usp=sharing)

**ANSWER:** it is my display settings. If I reduce the scale to recommended scale of %150 then the app displays correctly.
Maybe my React code does not scale properly?
Windows gives this warning for the Scale., "Some apps won't respond to scaling changes until you close and reopen them"

Project with Scale and Layout set to recommended 150%
(https://drive.google.com/file/d/15ShJXTpaY_00vomUPBJeWF1majIU4F7b/view?usp=sharing)

**Comment by leaanthony** [comment]
Glad you got to the bottom of it!
