### ISSUE TITLE
How to run JavaScript from Go?

### ISSUE THREAD

**Issue by raguay** [wailsapp/wails#349]
It's not a bug, but a question. I've looked all over the site, but I can't find details on how to run arbitrary JavaScript code from Go Lang in the browser. I'm running a fiber HTTP server in Go that I want to post to the front-end when I get certain requests.

**Comment by leaanthony** [comment]
The best way to do that is to [emit](https://wails.app/reference/runtime/#emit) an event with the data. This can be picked up by the frontend and processed as you wish.

**Comment by leaanthony** [comment]
Perhaps the [Quotes Tutorial](https://wails.app/tutorials/quotes/) will be useful to you?

**Comment by raguay** [comment]
I'm trying to use it, but it just segment faults each time.

**Comment by leaanthony** [comment]
If so, please open up a bug report using `wails issue` and we will see what we can do.
