### ISSUE TITLE
Wails App, built with v2.8.2, cannot run on Ubuntu 24.04

### ISSUE THREAD

**Issue by chensun08** [wailsapp/wails#3502]
### Description

Wails App, built with v2.8.2, cannot run on Ubuntu 24.04.
Error show:
error while loading shared libraries: libjavascriptcoregtk-4.0-so.18: cannot open shared object file: no such file or directory

### To Reproduce

Build Wails App with v2.8.2
copy the app to ubuntu 24.04
run the app on ubuntu 24.04

### Expected behaviour

Could run wails app correctly 

### System Details

```shell
Wails v2.8.2
```

**Comment by atterpac** [comment]
This is fixed on master build with `-tags webkit2_41`

**Comment by voodooEntity** [comment]
Is there any plan to release a 2. version including the fix?

**Comment by atterpac** [comment]
> Is there any plan to release a 2. version including the fix? 

Yes 2.8.3 should have this when released

**Comment by leaanthony** [comment]
Should be out today

**Comment by makew0rld** [comment]
Could this tag be documented somewhere as needed for Ubuntu 24.04 and later?

**Comment by leaanthony** [comment]
https://wails.io/docs/gettingstarted/building
