### ISSUE TITLE
my wails serve prints log are debug mode

### ISSUE THREAD

**Issue by Virgil-N** [wailsapp/wails#351]
**Description**

my log' level is debug mode, how can i change it to headless mode

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 8.1.0 |
| Npm           | 6.9.0 |
| Node          | v10.16.0
 |

**Additional context**
one more thing: there is an error.
time="2020-02-25T21:14:34+08:00" level=info msg="[Todos] modified file: E:\\workspace\\go\\wails\\todos\\mylist.json"
time="2020-02-25T21:14:34+08:00" level=debug msg="[main.Todos.SaveList] results = [<error Value>]"
time="2020-02-25T21:14:34+08:00" level=info msg="[Todos] modified file: E:\\workspace\\go\\wails\\todos\\mylist.json"
time="2020-02-25T21:14:34+08:00" level=debug msg="[Bind] # of return types: 1"
time="2020-02-25T21:14:34+08:00" level=debug msg="[Bind] # of results: 1"
time="2020-02-25T21:14:34+08:00" level=debug msg="[IPC] processed call" err="<nil>" result="<nil>"
time="2020-02-25T21:14:34+08:00" level=debug msg="[Events] Got Event" data="[]" name=filemodified
time="2020-02-25T21:14:34+08:00" level=debug msg="[IPC] Finished processing call" 1D=0xc000006068
panic: concurrent write to websocket connection

goroutine 35 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0001b18b0, 0xc000082601, 0xc0000826ed, 0x0, 0x3, 0x30, 0xc0000826c0)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x6fd
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0003562c0, 0x1, 0xc0000826c0, 0x2d, 0x30, 0x30, 0x1)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:752 +0x253
github.com/wailsapp/wails/lib/renderer/bridge.(*session).sendMessage(0xc000314190, 0xc000082690, 0x2d, 0x0, 0x0)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:39 +0xf6
github.com/wailsapp/wails/lib/renderer/bridge.(*session).evalJS(...)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:88
github.com/wailsapp/wails/lib/renderer/bridge.(*Bridge).NotifyEvent(0xc0002ca000, 0xc0001d4360, 0x0, 0x0)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/bridge.go:165 +0x31b
github.com/wailsapp/wails/lib/event.(*Manager).Start.func1(0xc00009c910)
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/event/manager.go:111 +0x373
created by github.com/wailsapp/wails/lib/event.(*Manager).Start
        E:/workspace/go/GOPATH_DIR/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/event/manager.go:99 +0x134
Error: exit status 2

------
i'm a beginner, hope u can help me. thanks.

**Comment by leaanthony** [comment]
Using the `-loglevel` flag. https://wails.app/guides/debugging/
