### ISSUE TITLE
如果我在go项目中不指定位置创建文件， 那么这个文件会出现在什么地方

### ISSUE THREAD

**Issue by FlynnWan** [wailsapp/wails#3519]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

如题， 我的数据不多，不需要数据库， 如果我在go中创建一个文件， 那么这个文件会被保存在哪里， mac和Linux我也有同样的问题。

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by FiyZou** [comment]
我已经有了解决方案
```go
func getUserHomeDir() (string, error) {
	// 获取当前用户的信息
	usr, err := user.Current()
	if err != nil {
		return "", err
	}

	// 获取用户的主目录
	homeDir := usr.HomeDir

	// 如果 HomeDir 为空，尝试从环境变量中获取
	if homeDir == "" {
		switch runtime.GOOS {
		case "windows":
			homeDir = os.Getenv("HOMEDRIVE") + os.Getenv("HOMEPATH")
			if homeDir == "" {
				homeDir = os.Getenv("USERPROFILE")
			}
		default:
			homeDir = os.Getenv("HOME")
		}
	}

	if homeDir == "" {
		return "", fmt.Errorf("无法确定用户的主目录")
	}

	return homeDir, nil
}
```
