### ISSUE TITLE
[BUG] Double file dialog windows when called once, for consecutive rebuilds after initial one via ``wails dev``

### ISSUE THREAD

**Issue by Z3NTL3** [wailsapp/wails#3520]
### Description

# Intro
There is an issue with the ``wails dev`` development environment. That is, when you do use a file dialog, let's say from the frontend. If the user presses a button you call a file dialog to be opened. After that if you'd make a change to ``index.html``, thus forcing a rebuild, then you have to press the button again (opening a file dialog) and you'll see the file dialog gets executed more than once, like as if it is executed in a loop. Sometimes you even get ``[0530/095201.152:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0``.

### To Reproduce

1. In your frontend make a button that fires an event to the ``go runtime``.
2. Catch the event and open a file dialog, using ``runtime.OpenFileDialog``.
   ```go
    // My exact options in my case; are
    runtime.OpenDialogOptions{
		DefaultDirectory: path.Join(RootDir),
		Title:            "test",
		Filters: []runtime.FileFilter{
			{
				DisplayName: "Select file (.txt)",
				Pattern:     "*.txt",
			},
		},
	}
   ```
3. Click on the cancel button when the file dialog is shown.
4. Make a change in ``index.html`, to just force a rebuild of assets.
5. Repeat the interaction with file dialog, click cancel, and you'll see that you get more than one file dialog being shown after one-another. As if it is executed in a loop.
   > Sometimes you'll even see ``[0530/095201.152:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0``.

> **Note**<br>
> I am not executing the file dialog in a loop so it's not from my end.<br>
> **Here is the source**
> ```go 
> func (a *App) dialog_exec(optionalData ...interface{}) {
> 	var err error
> 	defer func(err_ *error) {
> 		if *err_ != nil {
> 			fmt.Println((*err_).Error())
> 			runtime.EventsEmit(a.ctx, Fire_ErrEvent, (*err_).Error())
> 		}
> 	}(&err)
> 
> 	props, ok := optionalData[0].(string)
> 	if !ok {
> 		err = ErrPropsInvalid
> 		return
> 	}
> 
> 	opts := runtime.OpenDialogOptions{
> 		DefaultDirectory: path.Join(RootDir),
> 		Title:            "ProxyBeast - File dialog",
> 		Filters: []runtime.FileFilter{
> 			{
> 				DisplayName: "Select file (.txt)",
> 				Pattern:     "*.txt",
> 			},
> 		},
> 	}
> 	if props == SaveFile {
> 		opts.DefaultDirectory = path.Join(opts.DefaultDirectory, "saves")
> 	}
> 
> 	loc, err := a.dialog(opts)
> 	if err != nil {
> 		return
> 	}
> 
> 	f, err := OpenFileRDO(loc)
> 	if err != nil {
> 		return
> 	}
> 
> 	FD[props].Close()
> 	FD[props] = f
> 
> 	runtime.EventsEmit(a.ctx, props, path.Base(loc))
> }
> ```
> If that s not enough click here [Source](https://github.com/Z3NTL3/ProxyBeast/blob/main/core/app.go)

### Expected behaviour

- Opening the file dialog once
- Not getting erors like ``[0530/095201.152:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0``

### Attempted Fixes

- None
  > Because in a ``wails build`` builded bin it does never happen, only in ``wails dev`` environment.

### System Details

```shell
ProxyBeast on  main [✘!?] via 🐹 v1.22.2 via  v20.11.0 
❯ wails doctor

                                
          Wails Doctor          
                                


# Wails
Version | v2.8.1

# System
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Home                                                                |
| Version      | 2009 (Build: 22631)                                                            |
| ID           | 23H2                                                                           |
| Go Version   | go1.22.2                                                                       |
| Platform     | windows                                                                        |
| Architecture | amd64                                                                          |
| CPU          | AMD Ryzen 7 4800H with Radeon Graphics                                         |
| GPU 1        | NVIDIA GeForce RTX 2060 (NVIDIA) - Driver: 31.0.15.5244                        |
| GPU 2        | AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.) - Driver: 31.0.21912.14 |
| Memory       | 16GB                                                                           |
└───────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 125.0.2535.67 |
| Nodejs     | N/A          | Installed | 20.11.0       |
| npm        | N/A          | Installed | 10.2.5        |
| *upx       | N/A          | Installed | upx 4.2.3     |
| *nsis      | N/A          | Installed | v3.10         |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

i can provide a vid if neccessary.

after the initial ``wails dev`` rebuild the loop just gets incremented every new rebuild on top, so for example after 4 rebuilds, calling ``runtime openfiledialog`` once opens it 4 times in a row

**Comment by leaanthony** [comment]
I think this was covered in discord? Using a mutex will give you control of your dialogs :-)

**Comment by Z3NTL3** [comment]
> I think this was covered in discord? Using a mutex will give you control of your dialogs :-)

oke ty

**Comment by leaanthony** [comment]
Correct

**Comment by Z3NTL3** [comment]
makes sense thnx
