### ISSUE TITLE
Request to Add Arabic Language Support for Documentation

### ISSUE THREAD

**Issue by Mrkouhadi** [wailsapp/wails#3541]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Could you please add Arabic language support for the project's documentation. It will greatly help Arabic speaking developers understand and use Wails.
I'll do my best to help with the translation process.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
If you're happy to get involved, feel free to join the translation project here: https://crowdin.com/project/wails 👍

**Comment by Mrkouhadi** [comment]
> If you're happy to get involved, feel free to join the translation project here: https://crowdin.com/project/wails 👍

Alright, Thank you very much.
