### ISSUE TITLE
`wails build` should specific wails.json path(wails build 命令应该可以自定义 wails.json 路径)

### ISSUE THREAD

**Issue by funte** [wailsapp/wails#3549]
### Is your feature request related to a problem? Please describe.

In some situations, we want output different versions one time, if the `wails build` could specific wails.json path, we can write build script like this:
有些情况下, 可能需要一次构建不同版本的输出, 如果 `wails build` 命令可以自定义 wails.json 路径, 编译脚本就可以写成下面这样:
```sh
# still use the default wails.json, same to "wails build -config wails.json"
wails build
# use the another.json
wails build -config another.json
```

### Describe the solution you'd like

`wails build` add `-config` flag to specific the wails.json  path, if user not specific the `-config`, still use the default wails.json.
`wails build` 命令添加 `-config` 用来指定 wails.json  路径, 如果用户未指定 `-config`, 仍然使用默认路径下的 wails.json.

**Comment by q1255490** [comment]
May i ask  Is this function implemented?
