### ISSUE TITLE
Openlayers does not work with the built mode, it works with dev mode

### ISSUE THREAD

**Issue by amsanket22** [wailsapp/wails#355]
**Description**

I am using open layers mapping library, we can move the canvas in dev mode(wails serve & npm run dev) but once I create binary, I am unable to move and pan the map. 

I am using Vue JS as a front-end framework, I tried changing the life cycles hooks to initialise the map and even CSS but doesn't work

**Comment by amsanket22** [comment]
I am trying this on ubuntu 18.04

**Comment by leaanthony** [comment]
We, as a project, don't do anything special with canvas, or any part of the DOM. The likelihood is that it's a difference in the way events are handled? If you set up a repo with an example project, we may find some time to look at it for you. Thanks.
