### ISSUE TITLE
macOS panic when serving middleware response

### ISSUE THREAD

**Issue by makew0rld** [wailsapp/wails#3550]
### Description

I have an in-development Wails application that at one point, makes an HTTP request to a custom path. In my case the request comes from the `src` attribute of an `img` tag set using JavaScript, but I don't think that's relevant. The request is served by my custom code, set in the app options with `assetserver.Options.Middleware`.

Here is the stack trace I get from macOS (formatting is slightly garbled, sorry):

```
panic: runtime error: cgo argument has Go pointer to unpinned Go pointer

goroutine 29 [running]:github.com/wailsapp/wails/v2/pkg/assetserver/webview.(*responseWriter).Write.func1(0xc0000160a0?, 0xc000170548, 0x8)
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/webview/responsewriter_darwin.go:108 +0x4bgithub.com/wailsapp/wails/v2/pkg/assetserver/webview.(*responseWriter).Write(0xc000012018, {0xc000170548, 0x8, 0x7fd374b25350?})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/webview/responsewriter_darwin.go:108 +0x6agithub.com/wailsapp/wails/v2/pkg/assetserver.(*contentTypeSniffer).Write(0xc000012030, {0xc000170548, 0x8, 0x8})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/content_type_sniffer.go:19 +0x48
image/png.(*encoder).writeChunk(0xc000170508, {0xc000170554, 0xc000012030?, 0x400}, {0x103e64b08?, 0x8?})
	/Users/runner/hostedtoolcache/go/1.22.4/arm64/src/image/png/writer.go:115 +0x13f
image/png.(*encoder).writeIHDR(0xc000170508)
	/Users/runner/hostedtoolcache/go/1.22.4/arm64/src/image/png/writer.go:166 +0xd8
image/png.(*Encoder).Encode(0x1044945c0, {0x1048a9318, 0xc000012030}, {0x1042704b0, 0xc0003ae080})
	/Users/runner/hostedtoolcache/go/1.22.4/arm64/src/image/png/writer.go:659 +0x539
main.(*App).middleware-fm.(*App).middleware.func1({0x104270ad0?, 0xc000012030?}, 0x7fd374b25300?)
	/Users/runner/work/<censored>/<censored>/app.go:70 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc00017e240?, {0x104270ad0?, 0xc000012030?}, 0xf?)
	/Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x29github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).ServeHTTP(0xc000122c80, {0x104270ad0, 0xc000012030}, 0xc0003a2120)
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/assetserver.go:183 +0x579github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).processWebViewRequestInternal(0xc000122c80, {0x1042724f8, 0xc000126558})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/assetserver_webview.go:149 +0xab7github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).processWebViewRequest(0xc000122c80, {0x1042724f8, 0xc000126558})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/assetserver_webview.go:57 +0x48
created by github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).ServeWebViewRequest in goroutine 19
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/assetserver/assetserver_webview.go:49 +0xe5
```

(This is a stack trace from v2.8.2 but from looking at the source code I *believe* this still happens with v2.9.1)

The actual panic appears to be happening right here: https://github.com/wailsapp/wails/blob/5cd0caccc4e238e276611e7ed7fc91eac4765c46/v2/pkg/assetserver/webview/responsewriter_darwin.go#L101-L108

I did some research, and the bug here appears to simply be that `content` is a variable, rather than passing the `unsafe.Pointer(&buf[0])` code into the C function directly. Ordinarily this wouldn't matter of course, but it seems for CGo it does because the Go type checker is not smart enough to understand this.

My sources for this claim are:
- https://github.com/golang/go/issues/14210#issuecomment-346402945
- https://github.com/golang/go/issues/28606
- https://ericchiang.github.io/post/cgo/

This would make the fix pretty simple: just get rid of the `content` variable. And change where the same thing happens again [here](https://github.com/wailsapp/wails/blob/5cd0caccc4e238e276611e7ed7fc91eac4765c46/v2/pkg/assetserver/webview/responsewriter_darwin.go#L126-L133). Maybe it happens in other places too?

I have not been able to test this proposed fix yet, or created a minimal reproducible example yet. I hope to do, maybe this weekend. I am filing this issue in advance in hopes that someone else will beat me to it.

I searched the Internet as best I could for anyone running into this specific panic with Wails, and I couldn't find anything. I guess no one has used middleware on macOS with Wails v2 before? Seems possible, but maybe something deeper is going on as well. Hopefully someone else can reproduce this. For what it's worth I have seen this on two separate macOS Sonoma machines.

### To Reproduce

1. Create a wails project with a middleware server, and a frontend that makes a request to that middleware
2. Observe the crash on macOS

Minimal reproducible example repo coming soon hopefully.

### Expected behaviour

No crashing with middleware usage on macOS :)

### Screenshots

Here's basically the same stack trace, but in screenshot form:

![image](https://github.com/wailsapp/wails/assets/25111343/ab1f51da-f523-4065-8fca-7cbfac6aff71)

### Attempted Fixes

Will be attempting a fix with modified C code soon. Essentially just inlining the `content` variable.

### System Details

![image](https://github.com/wailsapp/wails/assets/25111343/747daba4-424b-4da9-a1ba-eef23f2ac647)

**Comment by leaanthony** [comment]
Thanks for the thorough big report 🙏 Seems like it should be reasonably easy to fix. I'm pretty sure people have used middleware with v2/Mac but CGO is a fickle beast.

**Comment by stffabi** [comment]
This is very interesting. Every request for serving content goes through that code `[wails/v2/pkg/assetserver/webview/responsewriter_darwin.go](https://github.com/wailsapp/wails/blob/5cd0caccc4e238e276611e7ed7fc91eac4765c46/v2/pkg/assetserver/webview/responsewriter_darwin.go#L101-L108` regardless of using a middleware or not.

So even loading just the html content of the frontend is also going through that code. Very interesting we haven't seen that report for so long.

**Comment by makew0rld** [comment]
Huh! That's what I thought as well when I was digging through the code, but I figured I must have been wrong, since I only see the crash once the middleware content is loaded. Maybe this has something to do with the fact that the content sniffer is making the Write call? And maybe non-middleware requests don't have content sniffing? Got a few pathways to test I guess.

-------- Message d'origine --------

**Comment by makew0rld** [comment]
Ok I was able to create a minimal reproducible example! Repo is here: https://github.com/makew0rld/wails-issue-3550

I took the vanilla wails default project, and made a small change. To see only the diff, you can look at this commit: https://github.com/makew0rld/wails-issue-3550/commit/e17600f1e88d8faf8f51f6c432df357c9e5266cb

It turns out that content-sniffing is required for the crash, or at least something involving PNG encoding. Simply writing a response in the middleware handler (like with `fmt.Fprintln`) was not enough. It only crashed on macOS once I started writing with the PNG encoder.

Here's the exact crash I got after running the binary for this repo on macOS: 

![image](https://github.com/wailsapp/wails/assets/25111343/3dff2c5c-c559-4e47-8643-8681b723c837)

Seems the same as the one I posted before, so I feel confident I am reproducing the same bug.

**Comment by makew0rld** [comment]
@leaanthony @stffabi any thoughts why this is happening, given my example above? I have an idea of how to fix this as mentioned in my opening comment, but I would hesitate to apply that without understanding what's causing the bug in the first place.

**Comment by leaanthony** [comment]
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/local-development#testing-a-pr). Let us know how you get on 👍

**Comment by leaanthony** [comment]
@makew0rld - any feedback on this? Thanks 🙏

**Comment by makew0rld** [comment]
I appreciate the fix! It may be a couple weeks at most before I can test it out. I will respond in this thread once I do.

-------- Message d'origine --------

**Comment by makew0rld** [comment]
The PR totally works with my app! I only had to make a small change to it, as noted in the PR thread. Thanks! Would love to see a release for this when possible.
