### ISSUE TITLE
Wails app on build macos

### ISSUE THREAD

**Issue by zuno90** [wailsapp/wails#3558]
I had successfully build on my macos m1 and embeded ffmpeg static into binary build, but bundle file was not work. By running executable file inside Contents/MacOS, that is worked as I expected.
So what s happen with bundle file, what i need to active and anything. Thanks for any helps!

**Comment by atterpac** [comment]
Mac has a lot of restrictions security wise, you need to make sure everything inside the contents is properly signed and notarized as well as the final application 

https://wails.io/docs/reference/options#webviewbrowserpath

**Comment by atterpac** [comment]
> Do we need to go through the app signing steps mentioned [here](https://wails.io/docs/guides/mac-appstore#mac-app-store-process), even if we do not want to distribute through app store? or is there a simpler way for this?

You can try packaging it with ditto into a zip for sharing but apple is getting more and more strict every release on what it allows through security

**Comment by leaanthony** [comment]
Is this failing to open on your own machine? What does `wails doctor` output?

**Comment by leaanthony** [comment]
Looks like this isn't directly a Wails bug. If you have more details and can show hoot reproduce, feel free to open this again 👍
