### ISSUE TITLE
wails build with error: \runtime\assets\bridge.js: The system cannot find the path specified.

### ISSUE THREAD

**Issue by drharryhe** [wailsapp/wails#356]
I write a demo， it can run well with wails serve/npm run serve.
but when i try to build it to an exe, it fail with the error below:
![image](https://user-images.githubusercontent.com/4024888/75948347-37321080-5ede-11ea-939f-199222bb9382.png)

this  is my project code structure:
![image](https://user-images.githubusercontent.com/4024888/75948418-59c42980-5ede-11ea-9836-c3361a449db0.png)
the topper in red block is my wails app.

my main.go is as below:
![image](https://user-images.githubusercontent.com/4024888/75948483-84ae7d80-5ede-11ea-82ef-682360d8f522.png)

How should I fix this build error? thanks a lot

**Comment by leaanthony** [comment]
Hey there. Sorry you're having this issue. I can certainly look at this at the weekend.

**Comment by drharryhe** [comment]
thanks for quick response. I do wails issue to here https://github.com/wailsapp/wails/issues/357

**Comment by leaanthony** [comment]
Thanks,closing this.
