### ISSUE TITLE
wails build with error: \runtime\assets\bridge.js: The system cannot find the path specified

### ISSUE THREAD

**Issue by drharryhe** [wailsapp/wails#357]
**Description**

I write a demo， it can run well with wails serve/npm run serve.
but when i try to build it to an exe, it fail with the error below:

**To Reproduce**
Steps to reproduce the behaviour:
do wails build on win10

**Expected behaviour**
build exe successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/4024888/75983698-f361fa00-5f23-11ea-98f2-14e722e52f3f.png)

this is my project code structure:
![image](https://user-images.githubusercontent.com/4024888/75983754-0c6aab00-5f24-11ea-8bb7-cb27b53f7faa.png)
the topper in red block is my wails app.

my main.go is as below:
![image](https://user-images.githubusercontent.com/4024888/75983771-14c2e600-5f24-11ea-878a-894d19b37dda.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13.8 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.13.4 |
| Node          | v12.16.1
 |

**Additional context**

**Comment by drharryhe** [comment]
it looks like use wrong context dir when compile  topper\vendor\github.com\wailsapp\wails\cmd\helpers.go. it not use the dir of helpers.go ,but the dir of  main.go

**Comment by drharryhe** [comment]
this is my main.go
`package main

import (
	"github.com/leaanthony/mewn"
	"github.com/wailsapp/wails"

	"ktop/topper/model"
)

func main() {
	js := mewn.String("./frontend/dist/app.js")
	css := mewn.String("./frontend/dist/app.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:     1024,
		Height:    768,
		Title:     "Demo",
		JS:        js,
		CSS:       css,
		Colour:    "#990000",
		Resizable: true,
	})

	//conf := model.NewConfig()
	//if conf == nil {
	//	return
	//}
	app.Bind(model.NewDemoEngine(nil))
	app.Run()
}
`

this is my demo module:
`
package model

import "github.com/wailsapp/wails"

type ModMethodResult struct {
	Error string      `json:"error"`
	Data  interface{} `json:"data"`
}

func NewDemoEngine(conf *Config) *DemoEngine {
	engine := new(DemoEngine)
	//engine.Prepare(conf)
	return engine
}

type DemoEngine struct {
	//BaseModule
}

func (this *DemoEngine) WailsInit(runtime *wails.Runtime) error {
	//if err := this.BaseModule.WailsInit(runtime); err != nil {
	//	return err
	//}

	return nil
}


func (this *DemoEngine) WailsShutdown() {

}

func (this *DemoEngine) Echo(ps map[string]interface{}) *ModMethodResult {
	res := new(ModMethodResult)
	res.Data = ps
	return res
}
`

**Comment by leaanthony** [comment]
Ah so this is specifically when using Wails in the context of a vendor directory? The project is designed to be use as a Go Module and hasn't been designed for use like this. Does it work if you *don't* vendor it?

**Comment by drharryhe** [comment]
it's interesting. i just use goland open topper as the project, and wails build succeeds. the gomodule config is the same as the my origianl project. the difference between to projects is that ,the first project contains topper(desktop program) and the backend server and the second one just contains topper.

i dont know why but the project does build successfully.

Thanks for your response anyway, leaanthony.

**Comment by leaanthony** [comment]
I'm glad you found a solution!

**Comment by drharryhe** [comment]
the issue happens  again. I found the bridges.js is not present in the project folders as well as the vendor folders.
![image](https://user-images.githubusercontent.com/4024888/76199690-4d680580-622b-11ea-9ba0-369f6a95f2ff.png)

**Comment by leaanthony** [comment]
I will look at this today

**Comment by leaanthony** [comment]
Ok, I can reproduce this and based on time constraints, all i can say is I won't have time to support vendoring. At least, not for v1. If you delete your vendor folder, it will work. I have added vendoring as a ticket for v2 though 👍
