### ISSUE TITLE
Enable cookies in WebViews

### ISSUE THREAD

**Issue by doorlay** [wailsapp/wails#3609]
### Is your feature request related to a problem? Please describe.

I'd like to be able to grab cookies from an active WebView on all OSs.

### Describe the solution you'd like

Adding a CookieManager object to manage cookies for a session. This would allow users to call `GetCookiesAsync` (or something of that sort) to retrieve cookies for a given URI, exposing them to the WebView.

### Additional context

MacOS docs: https://developer.apple.com/documentation/webkit/wkwebsitedatastore#overview
Linux docs: https://webkitgtk.org/reference/webkit2gtk/2.24.2/WebKitCookieManager.html
Microsoft docs: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2cookiemanager?view=webview2-winrt-1.0.2478.35

**Comment by leaanthony** [comment]
How is it going?

**Comment by doorlay** [comment]
@leaanthony Unfortunately the requirements changed for my use-case, so I'm no longer going to be working on this.

**Comment by pavelbinar** [comment]
Hi guys, I am trying to implement the authentication service https://clerk.com/ into the Wails but having the problem that the JWT is stored in the cookies...

@leaanthony You may have better overview how other using the authentication services inside or in combination of Wails or perhaps how to temporarily monkey patch this issue.

**Comment by leaanthony** [comment]
There's a chance it works already on Windows. There was someone who wanted to do a PR for this but I haven't heard back for a while.

**Comment by leaanthony** [comment]
Moving (and linking) all cookie issues to #3908
