### ISSUE TITLE
Image use

### ISSUE THREAD

**Issue by metacatdud** [wailsapp/wails#363]
Load images other then converting them into base64? I am trying vanilla with `frontend/dist` and `frontend/src` folders
In `dist` i have the `index.html` and `img/image.png`
In `index.html` i havea a simple `<img id="sprite" src="/img/animals.png" alt="">`. I tried every possible path and I can get it to display the image.
Any advice/workaround?

Stack:
- go 1.14
- win 10

**Comment by leaanthony** [comment]
Hi. We don't support loading files like this as it's seen as a bit of an anti-pattern - you'll end up with a binary that can't be distributed without the relevant images with it. Is that your use case? The goal of the project is to create a single distributable binary. for v2 we are looking at supporting a local file url, like `file://` but I'm unconvinced that would satisfy your use case entirely.

**Comment by leaanthony** [comment]
I should also mention that vanilla isn't really supported like this either, but absolutely is in v2. The reason we built the templates with webpack was so that asset bundling wouldn't be an issue for you.

**Comment by metacatdud** [comment]
Thank you! I love this project and I hope people will give it a change. I've been watching it on reddit since its first announce. I want to create a simple quest game wit it :) I seem to pack every thing i need:
- Simple fe <-> be communication
- No enforced patterns
- Light
- Easy to get go even without proper documentation is pretty intuitive  - I think this became a go and gophers thing - to have simple stupid approaches <3 
Kudos to that!

On other note. Would not outputting a single file might be big and eat up a lot of memory? :/
