### ISSUE TITLE
Add Chinese Traditional to the docs

### ISSUE THREAD

**Issue by uynilo9** [wailsapp/wails#3633]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

As the title, I hope we could add Chinese Traditional to the docs. For those who use traditional Chinese (such as me), reading simplified Chinese is a bit strenuous. Let's make the docs better and clearer.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Feel free to join our [crowdin project](https://crowdin.com/project/wails) 👍
