### ISSUE TITLE
'wails' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by fu931113** [wailsapp/wails#3634]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

当我安装完成之后检查 "~/go/bin" 是否在您的 PATH 变量中： echo $PATH | grep go/bin，我已经添加了变量，还是提示'wails' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by levinit** [comment]
reinstall wails `go install github.com/wailsapp/wails/v2/cmd/wails@latest`  and run `which wails`

**Comment by leaanthony** [comment]
Feel free to reopen if the previous answer didn't work.

**Comment by Aues6uen11Z** [comment]
For a Go beginner like me, the statement

> Normally, it means that the go/bin directory in your User's home directory is not in the PATH environment variable.

can be somewhat misleading. In fact, what should be added to the environment variable is GOPATH/bin, rather than the bin directory under the Go installation directory.

**Comment by leaanthony** [comment]
Feel free to open a PR! 👍
