### ISSUE TITLE
"Creating controller failed with 80070002" when trying to launch wails app

### ISSUE THREAD

**Issue by varppi** [wailsapp/wails#3635]
### Description

Every time I try run a wails app from my main Windows 11 machine it throws this error:
```
C:\Users\XXXXXX\Desktop\testwails\build\bin>testwails.exe
2024/07/24 22:49:58 Creating controller failed with 80070002: The system cannot find the file specified.
[0724/224958.905:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

(the app window flashes for like a split second, disappears and then throws the errors above)

### To Reproduce

not sure tbh... worked on another windows 11 machine...

### Expected behaviour

for it to launch proper and not throw errors lol

### Attempted Fixes

I tried it on different machines and it worked 
I have tried reinstalling the dependencies.
ofc tried to search the errors online to try find a fix without any luck

Also tried these commands:
```
wails dev
wails build --debug --webview2 <every single mode>
```

### System Details

```shell
# Wails
Version | v2.9.1

# System
<issue closed so censoring this>

# Dependencies
┌────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version        |
| WebView2   | N/A          | Installed | 115.0.1901.183 |
| Nodejs     | N/A          | Installed | 20.12.2        |
| npm        | N/A          | Installed | 10.5.0         |
| *upx       | N/A          | Installed | upx 4.2.4      |
| *nsis      | N/A          | Installed | v2.51          |
└─────────────── * - Optional Dependency ────────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```
```


### Additional context

OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621

**Comment by leaanthony** [comment]
Sounds like a borked Webview2 install. Anything you can tell us about that?

**Comment by R00tendo** [comment]
> Sounds like a borked Webview2 install. Anything you can tell us about that?
I have tried reinstalling everything, but it still doesn't work so I don't believe it is a broken install... Also isn't the idea of wails that it has all the required stuff packed into the EXE so that you don't have to install anything that doesn't already come with the system by default? If this is the case, it is very interesting that even if I compile it in a VM, it doesn't work on the main system. Only in the VM and my other devices.

**Comment by leaanthony** [comment]
Windows has Webview2 installed by default but that doesn't mean an upgrade could bork it

**Comment by R00tendo** [comment]
> Windows has Webview2 installed by default but that doesn't mean an upgrade could bork it

I ran system reset on the computer and it works now. I think it might've been just that, a broken install or something similar and not a problem with Wails itself. Still pretty weird..., ig for the people that might have the same problem, just reset windows lol
