### ISSUE TITLE
some of the robotgo method will cause crash.

### ISSUE THREAD

**Issue by soymikey** [wailsapp/wails#3647]
### Description

When i call these methods in Wails will cause crash. but it works find in go itself. 
Does Wails has it own env to run go?

**Code**
`    robotgo.KeyDown("command")
    robotgo.KeyTap("v")
    robotgo.KeyUp("command")
` 

**Go**
```go
package main

import (
    "fmt"
    "github.com/go-vgo/robotgo"
    "time"
)

func main() {
    // Copy text to the clipboard
    textToCopy := "Hello, World!"
    err := robotgo.WriteAll(textToCopy)
    if err != nil {
        fmt.Println("Failed to copy text:", err)
        return
    }
    fmt.Println("Copied text:", textToCopy)

    // Wait for the user to focus on the input field
    fmt.Println("Please move the cursor to the target input field within 5 seconds...")
    time.Sleep(5 * time.Second)

    // Simulate pressing Command + V keys (for macOS)
    robotgo.KeyDown("command")
    robotgo.KeyTap("v")
    robotgo.KeyUp("command")

    // If using Windows/Linux, use Control + V keys
    // robotgo.KeyDown("control")
    // robotgo.KeyTap("v")
    // robotgo.KeyUp("control")

    // Read text from the clipboard and verify
    pastedText, err := robotgo.ReadAll()
    if err != nil {
        fmt.Println("Failed to read clipboard content:", err)
        return
    }
    fmt.Println("Pasted text:", pastedText)
}
``` 

**Error**

`SIGTRAP: trace trap
PC=0x199d8e814 m=16 sigcode=0
signal arrived during cgo execution

goroutine 262 gp=0x14000682fc0 m=16 mp=0x140002f5b08 [syscall]:
runtime.cgocall(0x102af5158, 0x14000588878)
        /Users/maoqiangzheng/.gvm/gos/go1.22.5/src/runtime/cgocall.go:157 +0x44 fp=0x14000588830 sp=0x140005887f0 pc=0x1024a7414
github.com/go-vgo/robotgo._Cfunc_keyCodeForChar(0x76)
        _cgo_gotypes.go:712 +0x34 fp=0x14000588870 sp=0x14000588830 pc=0x10297c554
github.com/go-vgo/robotgo.checkKeyCodes({0x102c2aeb8, 0x1})
        /Users/maoqiangzheng/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/key.go:351 +0xb0 fp=0x14000588910 sp=0x14000588870 pc=0x10297c950
github.com/go-vgo/robotgo.keyTaps({0x102c2aeb8, 0x1}, {0x0, 0x0, 0x0}, 0x0)
        /Users/maoqiangzheng/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/key.go:409 +0x58 fp=0x14000588990 sp=0x14000588910 pc=0x10297d1b8
github.com/go-vgo/robotgo.KeyTap({0x102c2aeb8, 0x1}, {0x0, 0x0, 0x0})
        /Users/maoqiangzheng/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.1/key.go:528 +0x510 fp=0x14000588bb0 sp=0x14000588990 pc=0x10297def0
main.(*App).Write(0x140001a0900, {0x1400023c4c8, 0x15})
        /Users/maoqiangzheng/Documents/project/go-desktop/wails-demo/app.go:165 +0x88 fp=0x14000588c00 sp=0x14000588bb0 pc=0x102af34a8
runtime.call32(0x1400051a5a0, 0x140001561a8, 0x0, 0x0, 0x0, 0x18, 0x14000589008)
        /Users/maoqiangzheng/.gvm/gos/go1.22.5/src/runtime/asm_arm64.s:504 +0x78 fp=0x14000588c30 sp=0x14000588c00 pc=0x10250fff8
runtime.reflectcall(0x0?, 0x8?, 0x8?, 0x334978?, 0x140?, 0x12?, 0x102c7c220?)
        <autogenerated>:1 +0x34 fp=0x14000588c70 sp=0x14000588c30 pc=0x1025157c4
reflect.Value.call({0x102d15be0, 0x140001a0900, 0x2e13}, {0x102b1420d, 0x4}, {0x1400000eca8, 0x1, 0x1})
        /Users/maoqiangzheng/.gvm/gos/go1.22.5/src/reflect/value.go:596 +0xa00 fp=0x140005896e0 sp=0x14000588c70 pc=0x1025930e0
reflect.Value.Call({0x102d15be0, 0x140001a0900, 0x2e13}, {0x1400000eca8, 0x1, 0x1})
        /Users/maoqiangzheng/.gvm/gos/go1.22.5/src/reflect/value.go:380 +0x74 fp=0x14000589760 sp=0x140005896e0 pc=0x102592594
github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call(0x1400022c700, {0x14000334950, 0x1, 0x1})
        /Users/maoqiangzheng/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/binding/boundMethod.go:72 +0x31c fp=0x14000589a30 sp=0x14000589760 pc=0x102a2ca6c
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage(0x14000212680, {0x1400042bf80, 0x64}, {0x102d3e8c0, 0x140002022a0})
        /Users/maoqiangzheng/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/dispatcher/calls.go:45 +0x430 fp=0x14000589d50 sp=0x14000589a30 pc=0x102ae8d40
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage(0x14000212680, {0x1400042bf80, 0x64}, {0x102d3e8c0, 0x140002022a0})
        /Users/maoqiangzheng/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/dispatcher/dispatcher.go:42 +0x18c fp=0x14000589ec0 sp=0x14000589d50 pc=0x102ae98ac
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage.func1()
        /Users/maoqiangzheng/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/desktop/darwin/frontend.go:390 +0x70 fp=0x14000589fd0 sp=0x14000589ec0 pc=0x102a3be30
runtime.goexit({})`
    
    

### To Reproduce

Please follow this code example provided.

### Expected behaviour

These code should works same as it works in go.

### System Details

```shell
# Wails
Version | v2.9.1

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 13.4                                                                                                                        |
| ID           | 22F66                                                                                                                       |
| Go Version   | go1.22.5                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | arm64                                                                                                                       |
| CPU          | Apple M1 Pro                                                                                                                |
| GPU          | Chipset Model: Apple M1 Pro Type: GPU Bus: Built-In Total Number of Cores: 16 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 32GB                                                                                                                        |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version          |
| Xcode command line tools  | N/A          | Installed | 2397             |
| Nodejs                    | N/A          | Installed | 18.20.3          |
| npm                       | N/A          | Installed | 10.7.0           |
| *Xcode                    | N/A          | Installed | 14.3.1 (14E300c) |
| *upx                      | N/A          | Available |                  |
| *nsis                     | N/A          | Available |                  |
└──────────────────────── * - Optional Dependency ────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
No special environment... if you run it in `lldb` can you see what it's trying to do at the point of crash?

**Comment by leaanthony** [comment]
What was the issue?

**Comment by jherman** [comment]
@leaanthony I don't know if OP ever actually solved the issue, but I am still able to reproduce it. In fact, I created simple Hello World wails project and had it crash using just one simple command:

`wails init -n wails-robotgo -t vanilla`

and the command being:

```
func (a *App) WatchMeCrash() {
	fmt.Println("WatchMeCrash")

	robotgo.KeyDown(robotgo.Key0)
}
```

This will crash the application. You can find that repo here:

https://github.com/jherman/wails-robotgo

Let me know if you have any questions.

**Comment by leaanthony** [comment]
Does robotgo expect to be running on the main thread?

**Comment by jherman** [comment]
That is a great point. I don't know all the ins and outs of robotgo, but I imagine since it automates keypresses, mouse movements, etc... that it needs to be on the main thread. There documentation doesn't seem to make mention of it either. Is that the issue here?

Edit: I should mention this works fine in Windows. I only have an issue with macOS.
