### ISSUE TITLE
Loading widow

### ISSUE THREAD

**Issue by ewener** [wailsapp/wails#365]
I'm sorry, my English is not good.

I encountered some problems when using 'wails'. As new styles and pictures are constantly introduced into the front end, the size of CSS and JS is getting larger and larger. When I start the app, there will be a few seconds of blank screen. I guess it's rendering slowly. I want to add a window in the loading process to make the user experience better, but I can't find a way to solve this problem, I hope I hope you can give me some advice or solutions,thanks.

**Comment by leaanthony** [comment]
Hi. We don't support any pre-rendering, thought it's a good idea. It's unlikely we'll do much about this in V1. In V2 (in development), we store the assets in a completely different way which provides instant rendering on the frontend.
