### ISSUE TITLE
rasberry

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#366]
how to build for rasberry？

**Comment by leaanthony** [comment]
What's your error?

**Comment by zhuqiyun** [comment]
> What's your error?

no error  ，want to cross compile at windows for rasberry   ，like GOOS=linux    ，GOARCH=arm？

**Comment by leaanthony** [comment]
Try this: https://github.com/wailsapp/wails/pull/347

**Comment by zhuqiyun** [comment]
> Try this: #347

thanks  ，i will discuss on that topic
