### ISSUE TITLE
[REQUEST] Update libwebkit2gtk to version 4.1

### ISSUE THREAD

**Issue by c0des1ayr** [wailsapp/wails#3662]
### Is your feature request related to a problem? Please describe.

On Debian 13, libwebkit2gtk-4.0 is unavailable, and only v4.1 is. Since Wails requires v4.0 explicitly, it fails to build on Debian 13 without having to install 4.0 manually, which risks dependency hell.

### Describe the solution you'd like

I would like for the next version (2.9.2) to be built using `libwebkit2gtk-4.1`, or at least for there to be a branch that is made to use v4.1.

### Describe alternatives you've considered

I've attempted to install v4.0 before, but doing so broke many applications I had installed, forcing me back on v4.1.

**Comment by samfweb** [comment]
@c0des1ayr check out https://github.com/wailsapp/wails/issues/3345.

**Comment by leaanthony** [comment]
https://wails.io/docs/gettingstarted/building 👍

**Comment by mibeon** [comment]
> https://wails.io/docs/gettingstarted/building 👍

@leaanthony And how we should run "wails dev" with webkit2gtk-4.1?

**Comment by apicalshark** [comment]
> > https://wails.io/docs/gettingstarted/building 👍
> 
> [@leaanthony](https://github.com/leaanthony) And how we should run "wails dev" with webkit2gtk-4.1?

I think `wails dev -tags webkit2_41` is the way.
