### ISSUE TITLE
TS Wails.Events.On definition

### ISSUE THREAD

**Issue by svkior** [wailsapp/wails#367]
**Description**

In typescript there is no possibility to pass parameter for callback according to TS typedef

**To Reproduce**
Steps to reproduce the behaviour:
1. in typescript code:
    Wails.Events.On("info", message => {
		console.log(message);
    });

**Expected behaviour**
Code compiles.

**Screenshots**
<img width="691" alt="Screenshot 2020-03-20 11 36 15" src="https://user-images.githubusercontent.com/782225/77147765-19000f00-6a9f-11ea-92bc-2b075dc2d26c.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13.6 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | 6.13.6 |
| Node          | v13.7.0 |

**Additional context**

**Comment by leaanthony** [comment]
Hi. Typescript support is experimental at the moment. What does your typescript definition for the Wails runtime look like?

**Comment by leaanthony** [comment]
Ah, I see what's happening. 
Nice catch! I've updated the runtime library to `@wailsapp/runtime@1.0.11`. Please upgrade to use this one and let me know how it goes 👍

**Comment by svkior** [comment]
Works Perfect for me.
