### ISSUE TITLE
"Reveal in Explorer" feature

### ISSUE THREAD

**Issue by Krzysztofz01** [wailsapp/wails#3672]
### Is your feature request related to a problem? Please describe.

A common option in desktop software when working with files is the ability to quickly navigate to a directory by opening it in the default file explorer on a given system, or by showing a particular file in a directory with its additional selection. I think this is an option that could appear in Wails as a method in the *runtime*.

### Describe the solution you'd like

Method:
```go
runtime.RevealInExplorer(path string, focus bool) error
```

Through the focus parameter, we choose whether we want to select the file after running the explorer.

### Describe alternatives you've considered

In a project I am working on, I managed to implement such functionality by running a new file explorer process (via `os.exec`) with the appropriate flags. Support for Windows and Mac is trivial, but for Linux, it depends on the DE used.

### Additional context

I don't know what the approach to performing such operations is in Wails internally, but my existing implementation is basically plug'n play and I would be happy to take on the implementation.

**Comment by leaanthony** [comment]
This is now supported in v3 by this commit: https://github.com/wailsapp/wails/commit/2e4fce7c67c4a98f9400e8f64d15dd1c6b861527

If you want this in v2, feel free to reopen this and open a PR. Thanks 🙏

**Comment by Krzysztofz01** [comment]
> This is now supported in v3 by this commit: [2e4fce7](https://github.com/wailsapp/wails/commit/2e4fce7c67c4a98f9400e8f64d15dd1c6b861527)
> 
> If you want this in v2, feel free to reopen this and open a PR. Thanks 🙏

I have examined the implementation and prepared a proposal for extending the functionality. As advised, I have opened a thread on Discord titled ‘Extending the new OpenDirectory feature’.
