### ISSUE TITLE
Unable to hide the icon in the dock of mac

### ISSUE THREAD

**Issue by kishorkumar287** [wailsapp/wails#3700]
### Description

While starting the wails i am starting it has hidden but in the dock menu the app is showing in mac, can you explaing what is the reason for it?

### To Reproduce

func (stype *StartType) startup(ctx context.Context) {
	stype.Ctx = ctx
	wailsRunTime.Hide(ctx)
}

func main() {

err := wails.Run(&opts2.App{
			Title:            "",
			Width:            480,
			Height:           750,
			Assets:           assets,
			OnStartup:        stype.startup,
			BackgroundColour: &opts2.RGBA{R: 27, G: 38, B: 54, A: 1},
			Frameless:        true,
			StartHidden:      true,
			Bind: []interface{}{
				stype,
			},
		})
}
### Expected behaviour

The app icon should not be shown indock, but its getting showed

### Screenshots

![mac wails icon](https://github.com/user-attachments/assets/36330dd2-027e-453f-bedc-60c721afeea7)

### System Details

```shell
kishor@Kishors-MacBook-Air polaris % wails doctor
          Wails Doctor
# Wails
Version | v2.8.2
# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                                                                   |
| Version      | 14.4.1                                                                                                                                                                  |
| ID           | 23E224                                                                                                                                                                  |
| Go Version   | go1.22.3                                                                                                                                                                |
| Platform     | darwin                                                                                                                                                                  |
| Architecture | amd64                                                                                                                                                                   |
| CPU          | Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz                                                                                                                              |
| GPU          | Chipset Model: Intel Iris Plus Graphics Type: GPU Bus: Built-In VRAM (Dynamic, Max): 1536 MB Vendor: Intel Device ID: 0x8a5c Revision ID: 0x0007 Metal Support: Metal 3 |
| Memory       | 8GB                                                                                                                                                                     |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2406    |
| Nodejs                    | N/A          | Installed | 20.14.0 |
| npm                       | N/A          | Installed | 10.7.0  |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Available |         |
└─────────────────── * - Optional Dependency ────────────────────┘
# Diagnosis
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
 SUCCESS  Your system is ready for Wails development!
 :hearts:   If Wails is useful to you or your company, please consider sponsoring the project:
```

**Comment by kishorkumar287** [comment]
got the solution
https://github.com/wailsapp/wails/discussions/2144

**Comment by kishorkumar287** [comment]
got the solution
https://github.com/wailsapp/wails/discussions/2144

**Comment by popaprozac** [comment]
I was looking to set this programmatically as well and did this:
```
// #cgo CFLAGS: -x objective-c
// #import <AppKit/AppKit.h>
//
// void hideDockIcon() {
//     [NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];
// }
//
// void showDockIcon() {
//     [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
// }
```

Hope this helps you or others in the future.

**Comment by leaanthony** [comment]
> I was looking to set this programmatically as well and did this:
> 
> ```
> // #cgo CFLAGS: -x objective-c
> // #import <AppKit/AppKit.h>
> //
> // void hideDockIcon() {
> //     [NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];
> // }
> //
> // void showDockIcon() {
> //     [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
> // }
> ```
> 
> Hope this helps you or others in the future.

Do you think we should support this in the API?

**Comment by popaprozac** [comment]
I was going back and forth on this. It's so easy to implement in userland but I do think having this in core makes sense with the implications around system tray usage etc. I have no idea what this looks like on Windows or Linux. I'll open a PR for macOS and explore the others if you're cool with that.

**Comment by popaprozac** [comment]
@leaanthony do you think this could be baked in to the application code or part of a Dock service? EaaS (everything as a service)? That would be nice to be able to add additional Dock stuff in the future if we come across anything 👀
