### ISSUE TITLE
Concurrent write to WebSocket

### ISSUE THREAD

**Issue by svkior** [wailsapp/wails#372]
**Description**

Wails crashes during websocket communication

**To Reproduce**

from TS:

```
Wails.Events.On("update_status", (newStatus) => {
			console.log("On STATUS: ", newStatus)
		  });

for(int i=0; I < 100; I++){
  backend.IntelliMech.SetStatus(`Count: ${i}`)
}

```

from GoLang

```
func (im *IntelliMech) wailsRunner() {
	for {
		select {
		case newStat := <-im.inStatus:
			im.Lock()
			im.status = newStat
			im.Unlock()
			im.Runtime.Events.Emit("update_status", newStat)
		}
	}
}

func (im *IntelliMech) SetStatus(data string) {
	log.Printf("We Have New Status %s", data)
	im.inStatus <- data

}
```

panic: concurrent write to websocket connection

goroutine 6 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00011b8b0, 0xc000173401, 0xc0001734b6, 0x0, 0xa, 0x40, 0xc000173480)
        /Users/svkior/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x6f6
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc000280160, 0x1, 0xc000173480, 0x36, 0x40, 0x40, 0x1)
        /Users/svkior/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:752 +0x24c
github.com/wailsapp/wails/lib/renderer/bridge.(*session).sendMessage(0xc000154d70, 0xc000173440, 0x36, 0x0, 0x0)
        /Users/svkior/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:39 +0xef
github.com/wailsapp/wails/lib/renderer/bridge.(*session).evalJS(...)
        /Users/svkior/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/session.go:88
github.com/wailsapp/wails/lib/renderer/bridge.(*Bridge).NotifyEvent(0xc000254070, 0xc0002c8960, 0x0, 0x0)
        /Users/svkior/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/bridge/bridge.go:165 +0x314
github.com/wailsapp/wails/lib/event.(*Manager).Start.func1(0xc000154820)
        /Users/svkior/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/event/manager.go:111 +0x36c
created by github.com/wailsapp/wails/lib/event.(*Manager).Start
        /Users/svkior/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/event/manager.go:99 +0x12d
Error: exit status 2

**Expected behaviour**
No Error

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13.6 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | 6.13.6 |
| Node          | v13.7.0 |

**Additional context**

**Comment by leaanthony** [comment]
This is one for @tmclane

**Comment by tmclane** [comment]
I'll look into it further.  @leaanthony Will you assign it to me please?

**Comment by tmclane** [comment]
@svkior Would you happen to have a small project that can reproduce this?

**Comment by tmclane** [comment]
Or if not can you give me more information on which template you used to create your project?

**Comment by svkior** [comment]
@tmclane I can do a small project for all issues. Please, give me an hour. I created my own template. May be I did it wrong way.

**Comment by tmclane** [comment]
@svkior No there is definitely a bug here.  I am attempting to reproduce it myself but I thought it might be faster if you gave me a small skeleton that reproduces it.

**Comment by tmclane** [comment]
One thing I notice wrong with your example TS code up there is:

```diff
Wails.Events.On("update_status", (newStatus) => {
			console.log("On STATUS: ", newStatus)
		  });

for(int i=0; I < 100; I++){
-  backend.IntelliMech.SetStatus(`Count: ${i}`)
+  window.backend.IntelliMech.SetStatus(`Count: ${i}`)
}
```

**Comment by tmclane** [comment]
FYI: I have reproduced the issue.

**Comment by svkior** [comment]
https://github.com/svkior/apprun-wails-boilerplate

**Comment by svkior** [comment]
Do you need my help to fix it?

**Comment by tmclane** [comment]
One thing I notice in your code is you are actually running the following code in the Wails callback itself!

```
for(var i=0; i < 100; i++){
		window.backend.MyBridge.SetStatus(`Count: ${i}`)
}
```	

I would recommend you move that elsewhere.  This callback happens after the Wails runtime initializes and is ready so I suppose it should work although it really seems like a bad idea.

Thank you for the sample application.  I'm looking into solutions now.

**Comment by svkior** [comment]
@tmclane this crash happend even I call it from button onclick event.

There was similar bug in my previous project because gorilla websocket is not thread safe and I had to write thread-safe routines around websocket.

**Comment by tmclane** [comment]
it has a `sync.Mutex` around the write call already

**Comment by tmclane** [comment]
If you remove this line I bet the crash goes away:

https://github.com/svkior/apprun-wails-boilerplate/blob/45fe9526ced4fb9df6c925ab4df678bd741d4ca2/wails.go#L31

You are causing the event from the frontend to immediately emit the same event back to the frontend.
Was that your intention?

It still shouldn't crash - so I am looking into how to fix it.

**Comment by svkior** [comment]
@tmclane I simulate concurrent two way communication for my new project.

It will be control & monitoring system with a lot of params like grafana has. There are ten control stations with the same information and I simulate Control Button Press on one station and return info to all stations.

And I have two separate go routines. This case is the worst case according to my opinion.

**Comment by svkior** [comment]
> it has a `sync.Mutex` around the write call already

@tmclane this Mutex should cover reading and writing together.

**Comment by tmclane** [comment]
Yes I figured that might be required.  I am working on getting it changed out.

**Comment by tmclane** [comment]
Opened a PR against your sample project that doesn't crash.  
Hopefully it will help you proceed with development while I figure out the right way to correct this issue permanently:

https://github.com/svkior/apprun-wails-boilerplate/pull/1

**Comment by svkior** [comment]
@tmclane thank You very much.

But if I decrease update time to 100 Milliseconds - it crashes again. Anyway right now during the development I use delay for 1 second. 

May be it https://github.com/gorilla/websocket/issues/119 helps

**Comment by tmclane** [comment]
That issue shows exactly the same method as how the bridge code is written: 

```go
func (s *session) sendMessage(msg string) error {
	s.lock.Lock()
	defer s.lock.Unlock()


	if err := s.conn.WriteMessage(websocket.TextMessage, []byte(msg)); err != nil {
		s.log.Debug(err.Error())
		return err
	}


	return nil
}```

I believe the issue is a race condition with it receiving from the remote side and sending there at the same time.  I can't see any way for the lock to be skipped and write to the socket.

**Comment by tmclane** [comment]
For the time being use a slightly larger time to do the updates and hopefully that will minimize this from happening until I can fix it permanently.

**Comment by tmclane** [comment]
FYI: I opened a PR to address this: https://github.com/wailsapp/wails/pull/373

Feel free to try my branch.  

Checkout my repository and branch:

```
cd ~/go/src/github.com/
mkdir tmclane
git clone https://github.com/tmclane/wails.git
git checkout bugfix/372-bridge-chan
```

Then edit your project's `go.mod` and add the following line at the end:

```
replace github.com/wailsapp/wails => /home/tmclane/go/src/github.com/wailsapp/wails
```

From then on whenever you run `wails serve` in your project directory it will use my fork and branch.

**Comment by svkior** [comment]
Works well for me. Thanks a lot. Waiting for Next Version. Should I close the issue, or I need to wait for new release?

**Comment by svkior** [comment]
@tmclane after around hour of work - backend blocks web socket. And I need to kill the backend.

**Comment by tmclane** [comment]
odd.. Did you update your example by any chance? 

Update your checkout of my repository / branch:

```
git fetch 
git pull origin bugfix/372-bridge-chan
```

I bumped the channel capacity to 100.  See if that helps or if it still blocks eventually.

**Comment by tmclane** [comment]
Any chance you could batch messages? It might help lower the total number of messages needing to be sent / processed.

**Comment by tmclane** [comment]
FYI: My PR was merged to develop.  Hopefully that fixes your issue.

**Comment by svkior** [comment]
@tmclane I'll test it on next week.
