### ISSUE TITLE
Windows snipping tool crashes wails apps

### ISSUE THREAD

**Issue by hyptocrypto2** [wailsapp/wails#3730]
### Description

First noticed with personal app. But tested against example apps in wails repo. I suspect this is due to the way the the snipping tool hooks into the GPU driver. 
This does not happen in edge, and if im not mistaken, both wails and edge should be using the same webview2 backend?

### To Reproduce

1. Build any wails app with `-ldflags "-H=windowsgui"`
2. Start snipping tool screen recording.
3. Start/use app within the screen recording view. 

### Expected behaviour

App should run normally

### Attempted Fixes

I tried initializing the windows with WebViewGPUDisabled, but same result. 
Often no logs, sometimes there are traces of invalid windows handles. 
Also nothing in the windows event viewer. 

### System Details

```shell
❯ wails3 doctor


          Wails Doctor



# System
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 14.5         |
| ID            | 23F79        |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M3 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |
└──────────────────────────────┘

# Build Environment
┌─────────────────────────────────────────────────────────┐
| Wails CLI    | v3.0.0-alpha.4                           |
| Go Version   | go1.22.4                                 |
| Revision     | ab06920e74473cb0e34bf2dfffdd8bda023f3ddc |
| Modified     | false                                    |
| -buildmode   | exe                                      |
| -compiler    | gc                                       |
| CGO_CFLAGS   |                                          |
| CGO_CPPFLAGS |                                          |
| CGO_CXXFLAGS |                                          |
| CGO_ENABLED  | 1                                        |
| CGO_LDFLAGS  |                                          |
| GOARCH       | arm64                                    |
| GOOS         | darwin                                   |
| vcs          | git                                      |
| vcs.modified | false                                    |
| vcs.revision | ab06920e74473cb0e34bf2dfffdd8bda023f3ddc |
| vcs.time     | 2024-06-08T22:28:38Z                     |
└─────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────┐
| Xcode cli tools | 2408    |
| npm             | 10.7.0  |
| *NSIS           | v3.10   |
└─ * - Optional Dependency ─┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏
