### ISSUE TITLE
Windows system calls the runtime OpenDirectoryDialog anomalies, 2.8.0 and 2.9.1 version have to

### ISSUE THREAD

**Issue by wuxiaoyao666** [wailsapp/wails#3736]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

Then call the runtime OpenDirectoryDialog, I MacOS system can be normal open, But Windows will flash back and [0908/200034.751: ERROR: window_impl. Cc (121)] Failed to unregister class Chrome_WidgetWin_0. ERROR = 1412

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- Please include the output of `wails doctor`

**Comment by xray-bit** [comment]
Is your problem similar to this #3681 ? It has been fixed on the master branch

**Comment by itlangzi** [comment]
When I call the go func from js, the param value is more than 10kb, and then this error occurs. If the value is smaller, this error will not occur.

**Comment by xray-bit** [comment]
This problem is caused by a bug in [go-webview2](https://github.com/wailsapp/go-webview2), which has been fixed in v1.0.16, you can update the version of go-webview2 to v1.0.16.

**Comment by itlangzi** [comment]
> This problem is caused by a bug in [go-webview2](https://github.com/wailsapp/go-webview2), which has been fixed in v1.0.16, you can update the version of go-webview2 to v1.0.16.

helpful，my problem is solved, thank you！！！

**Comment by leaanthony** [comment]
Latest release of Wails should fix this too

**Comment by leaanthony** [comment]
I think this is complete now so closing
