### ISSUE TITLE
After the wails build exe file is opened, websocet uses

### ISSUE THREAD

**Issue by jinronga** [wailsapp/wails#3758]
### Description

After the wails build exe file is opened, websocet uses

### To Reproduce

After the wails build exe file is opened, websocet uses

### Expected behaviour

After the wails build exe file is opened, websocet uses

### Screenshots

After the wails build exe file is opened, websocet uses

### Attempted Fixes

After the wails build exe file is opened, websocet uses

### System Details

```shell
After the wails build exe file is opened, websocet uses
```

### Additional context

After the wails build exe file is opened, websocet uses

**Comment by leaanthony** [comment]
Spam
