### ISSUE TITLE
Is there some way to capture all keybord events?

### ISSUE THREAD

**Issue by nilopaim** [wailsapp/wails#376]
In my application I need to have total control of the keyboard, even the Fn keys.

I'm using the Vuetify standard template.

Is there some way to catch all keyboard events?

EDIT: I don't know why this was marked as BUG, and couldn't find how to change this. Sorry, guys.

**Comment by tmclane** [comment]
Maybe this will be helpful to you:
https://medium.com/@marin.basic02/sniffing-global-keyboard-events-in-go-e5497e618192

**Comment by leaanthony** [comment]
Can this be closed?
