### ISSUE TITLE
How to copy assets to the bundle

### ISSUE THREAD

**Issue by jurkat** [wailsapp/wails#378]
Hello, 

i changed the default FE to svelte. Everything woks fine, gerat job! 

But now i want to integrate font awesome, so i need to copy the fonts into the bundle because get them from a can is not useful for a desktop app. Is it possible to copy an own asset folder with images, fonts... into the bundle?

I think it should work like integrating the bundle.css/.js by targeting it in the wails.CreateApp.

Tanks :)

**Comment by leaanthony** [comment]
Like the other templates: webpack. Check one of them out and see how fonts are configured there

**Comment by leaanthony** [comment]
Can this be closed?

**Comment by jurkat** [comment]
Sorry, yes can be closed. Thank you!
