### ISSUE TITLE
Cannot read properties of undefined (reading 'EventsOff') or (reading 'main')

### ISSUE THREAD

**Issue by ManabBala** [wailsapp/wails#3781]
### Description

using useEffect to add a event listener. after wails dev application as expected but once i refresh the page with context menu, this occurs. 
```
TypeError: Cannot read properties of undefined (reading 'EventsOff')
    at EventsOff (http://wails.localhost:34115/wailsjs/runtime/runtime.js:48:27)
    at http://wails.localhost:34115/src/pages/Playground/Playground.jsx:101:7
    at commitHookEffectListMount (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:16463:34)
    at invokePassiveEffectMountInDEV (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:17872:19)
    at invokeEffectsInDev (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:19221:19)
    at commitDoubleInvokeEffectsInDEV (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:19206:15)
    at flushPassiveEffectsImpl (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:19023:13)
    at flushPassiveEffects (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:18967:22)
    at http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:18848:17
    at workLoop (http://wails.localhost:34115/node_modules/.vite/deps/chunk-H3JL4PHL.js?v=7832564a:197:42)
💿 Hey developer 👋
```
FE code:
```js
useEffect(() => {
    console.log("fucking with me again");

    if (!listenerMounted) {
      console.log("Mounting GaEventsListener");
      EventsOff("GaEventsListen");
      EventsOn("GaEventsListen", (data) => {(data)=>{doing my job}}
       setListenerMounted(true);
    }
  }, []);
  ```
    BE code:
    
    -------------------------
    package main
    
    import (
    "bufio"
    "bytes"
    "context"
    "database/sql"
    "encoding/base64"
    "encoding/json"
    "fmt"
    "io"
    "log"
    "net/http"
    "os"
    "os/exec"
    "path/filepath"
    "runtime"
    "strconv"
    "strings"
    
    _ "github.com/mattn/go-sqlite3"
    wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"
    )
    
    var wailsContext *context.Context
    // ...
    func (a *App) DOMReady(ctx context.Context) {
    wailsContext = &ctx
    
    // ...
func GaEventsListen(packageName string, serialId string) {
    wailsRuntime.EventsEmit(*wailsContext, "GaEventsListen", string(jsonData))
    
    }

   -----------------------------------------
    

     package main

import (
	"embed"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
)

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "analytics_debugger",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		OnDomReady:       app.DOMReady,
		OnShutdown:       app.shutdown,
		Bind: []interface{}{
			app,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}

### To Reproduce

- open application with wails dev
- going to the route/page
- refresh my page or any erros at FE code and vite triggers refresh
(I think vite hot reload might playing some role)

### Expected behaviour

normal refresh behaviors with vite.  

### System Details

```shell
# Wails
Version | v2.9.1

# System
┌──────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                             
                   |
| Version      | 2009 (Build: 22631)                                        
                   |
| ID           | 23H2                                                       
                   |
| Go Version   | go1.23.0                                                   
                   |
| Platform     | windows                                                    
                   |
| Architecture | amd64                                                      
                   |
| CPU          | AMD Ryzen 5 5600G with Radeon Graphics                     
                   |
| GPU          | AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.) - Driver: 31.0.14046.0 |
| Memory       | 24GB                                                       
                   |
└──────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 129.0.2792.52 |
| Nodejs     | N/A          | Installed | 22.4.0        |
| npm        | N/A          | Installed | 10.2.5        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/     

 SUCCESS  Your system is ready for Wails development!
```

### Additional context

```js
TypeError: Cannot read properties of undefined (reading 'main')
    at AdbList (http://wails.localhost:34115/wailsjs/go/main/App.js:6:22)
    at getCurrentDevices (http://wails.localhost:34115/src/pages/Dashboard.jsx:72:5)
    ```

my FE package.json
{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@supabase/supabase-js": "^2.45.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^5.3.0",
    "react-router-dom": "^6.26.1"
  },
  "devDependencies": {
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.0.1",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.45",
    "prettier": "^3.3.3",
    "prettier-plugin-tailwindcss": "^0.6.6",
    "tailwindcss": "^3.4.10",
    "vite": "^3.0.7"
  }
}

**Comment by liuyulvv** [comment]
I had this issue and it was solved when I changed `createBrowserRouter` to `createHashRouter`.
[doc](https://wails.io/docs/guides/routing/#react)

**Comment by ManabBala** [comment]
@liuyulvv thanks. this did solve my issue.

**Comment by ManabBala** [comment]
@leaanthony , @leaanthony Having issue cleaning listener.
```js
  // Setup the event listener
  useEffect(() => {
    console.log("Mounting GaEventsListener");
    // Set up the event listener with EventsOn
    const cancelGaEventListener = EventsOn(
      "GaEventsListen",
      handleGaEventsListen,
    );

    // Cleanup function to remove the event listener on unmount
    return () => {
      console.log("Unmounting GaEventsListener");
      if (typeof cancelGaEventListener === "function") {
        cancelGaEventListener(); // Cancel the listener using the function returned by EventsOn
      }
    };
  }, []); // No dependencies to avoid infinite loop
  ```
normally works fine. but if I navigate back(either with context menu or useNavigate hook) error occur. which i believe wails internal "event.js" error as it fails to kill the event listener.
  ```js
  react-dom.development.js:22878 
 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at listenerOff (events.js:209:49)
    at events.js:62:1
    at Playground.jsx:143:9
    at safelyCallDestroy (react-dom.development.js:22971:5)
    at commitHookEffectListUnmount (react-dom.development.js:23139:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:25137:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:25087:5)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24995:11)
    at commitPassiveUnmountEffects (react-dom.development.js:24980:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27077:3)
```
Then if i refresh and re-enter into the page then i have two event listener as my callback func triggers twice.
I event tried to use "EventsOff" explicitly before setting a "EventsOn" but that goes to vain.
Am I implementing the navigation right with hash router and useNavigate?
