### ISSUE TITLE
wails dev 模式能否新增-platform参数指定调试运行于32位环境

### ISSUE THREAD

**Issue by uller-cn** [wailsapp/wails#3784]
### Is your feature request related to a problem? Please describe.

问题产生描述：

我们使用wails开发32位windows pc桌面程序，程序使用了c++编写的32位类库需要使用32位cgo进行编译，我们开发环境为Wails CLI v2.9.1、go1.23.1 windows/amd64、TDM-GCC-32 10.3.0-2、goland2023.2.4，go env 已经修改GOARCH=386、 GOGCCFLAGS=-m32 -mthreads，项目使用wails build -upx -platform windows/386进行编译的时候可以正常编译，但使用wails dev的时候提示cc1.exe: sorry, unimplemented: 64-bit mode not compiled in，感觉是wails dev的时候由于没有-platform参数指定运行位数，造成wails自动读取的是64位cgo。

Running frontend DevWatcher command: 'npm run dev'
  ➜  Network: use --host to expose
Building application for development...
  • Generating bindings: Done.
  • Generating application assets: Done.
  • Compiling application: # runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

Build error - exit status 1
No version running, build will be retriggered as soon as changes have been detected
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:5173/
Using reload debounce setting of 100 milliseconds

### Describe the solution you'd like

wails dev 模式能否新增-platform参数指定调试运行于32位环境，如果增加参数不可行，是否可以读取go env中的环境变量来决定使用具体的cgo？

非常感谢。

**Comment by leaanthony** [comment]
Use 64bit C compiler 👍

**Comment by nausifmominn** [comment]
@leaanthony 

I am using a 32-bit .dll library for hardware integration, and they only provide a 32-bit version. Is there any way or workaround to run wails dev in 32-bit? It works perfectly when I build with wails build 32-bit. however, its hard to debug the App.

**Comment by leaanthony** [comment]
There's no plans to support 32 bit as nobody has 32 bit machines and it's a big support burden. That being said you might get it to work on Linux where they still make 32 bit builds available.
