### ISSUE TITLE
Ask for Admin rights

### ISSUE THREAD

**Issue by bovealexandre** [wailsapp/wails#3794]
### Is your feature request related to a problem? Please describe.

Hi,

I'm currently building an app using wail and I find it ugly how at the moment we have to ask for admin rights on both Windows, Linux and macOS

### Describe the solution you'd like

I would like an option on wails.json to have the opportunity to ask for rights

### Describe alternatives you've considered

for the moment I'm doing everything by hand and it's ugly. You have to start once the program, then it'd ask for permission and then rerun the program.

**Comment by JeremyPasco** [comment]
For Windows you could add a directive into your manifest file:
```xml
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
        <requestedPrivileges>
            <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
        </requestedPrivileges>
    </security>
</trustInfo>
```
But I haven't found a equivalent for Linux/Mac.

**Comment by ultimateshadsform** [comment]
On mac or linux you can just check Geteuid or something check if 0 then root etc.

https://pkg.go.dev/os#Geteuid

**Comment by bovealexandre** [comment]
It's OK I did it in another way

I connected via ssh to localhost
