### ISSUE TITLE
Is your obligation to go through a pre-selected template. (Need information, not bug)

### ISSUE THREAD

**Issue by Anth0-M** [wailsapp/wails#381]
Hello,

I allow myself to describe to know if we can use 

- pure **JS/CSS**
- **[DART](https://dart.dev/)** which compiles in OPTIMIZED JS
-  **[VECTY](https://github.com/gopherjs/vecty)** which allows to write GO and compile in **VANILLA JS** via [GOPHERJS](https://github.com/gopherjs/gopherjs) or **WebAssembly**

instead of templates (Angular, React, vue) ?

Thank you.

**Comment by leaanthony** [comment]
You can provide whatever you like so long as it's a js + css file. The templates are there to make life a bit easier and pack all the assets into these files so you don't have portability issues. Good luck!
