### ISSUE TITLE
Add output flags to build command line action

### ISSUE THREAD

**Issue by miolini** [wailsapp/wails#382]
I would be happy if build action will have output flags (output directory and binary name overridings) to specify output path of compiled application. It will be useful for the CI/CD.

**Comment by miolini** [comment]
I have create PR
https://github.com/wailsapp/wails/pull/383

**Comment by leaanthony** [comment]
We should bundle this as part of #377 - Though I do think it should be a single flag. @tmclane ?

**Comment by bh90210** [comment]
did that flag made it to #377 after all?

a single flag sound neater to me too :+1:
