### ISSUE TITLE
can't add any column for my GoToSocial Instance

### ISSUE THREAD

**Issue by huggenknubbel** [wailsapp/wails#3833]
### Description

Login with my GoToSocial Account works fine. I can see my Profile, my Profiletext etc. But the click at the "+" sybol does nothing.

### To Reproduce

login into GoToSocial account
click "+" symbol

### Expected behaviour

add a new column

### Screenshots

![grafik](https://github.com/user-attachments/assets/b009758f-4933-4c99-9d53-68c92b5c9f4a)

### System Details

```shell
Windows 10 (latest version)
```

**Comment by levinit** [comment]
It is a web frontend development issue, and too less description...

**Comment by leaanthony** [comment]
It looks like you are trying to report a bug but haven't provided enough details. Please open a now issue and make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- Please include the output of `wails doctor`
