### ISSUE TITLE
Add documentation for contributing and testing builds

### ISSUE THREAD

**Issue by AddictArts** [wailsapp/wails#385]
Hi, I'm interested in building it locally from a git clone. The docs mention building the command line wails executable, but that is not the entire app.

I understand creating a branch off dev and pull requests, However:

Do, contributors change their $GOPATH/src/github.com/wailsapp/wails source? checkout develop there, checkout branch, and build what?

How do you build the runtime, things in lib?

I know wails build does that, but is that really the preferred developer workflow? `go install --tags=dev` then run wails build on something?

Thanks, I'd like to contribute, but need to be able to test complete local builds.

**Comment by fallion** [comment]
Wails uses go modules. So you should be able to clone it anywhere and run `go mod download`. Just my 2 cents.

**Comment by tmclane** [comment]
Yes all the usual Go tricks apply and work. 
I like to add a `replace` line to the bottom of the project's go.mod to ensure it uses my updated copy if I am testing an addition/fix to the Wails source.

    replace github.com/wailsapp/wails => /home/tmclane/go/src/github.com/wailsapp/wails

**Comment by tmclane** [comment]
You are welcome to checkout your fork to wherever makes sense as well.

**Comment by leaanthony** [comment]
Thanks for asking the question @AddictArts! Based on your feedback, it seems like we need to update [this page](https://wails.app/development/) to answer these kinds of questions. I'll see if I can get this done over the long weekend. Thanks.

**Comment by AddictArts** [comment]
@leaanthony Yes that would be fantastic.

First I am relatively new to go, so there seems to be some embedded knowledge from months to years of working with github go code that is not written down.

@fallion Thanks, but I can tell that it isn't really doing anything useful if you've already run wails, or compiled the cmd/wails main.go.

What I can't see is how, say I made changes to /runtime, or /lib? For example I put an error in /lib/renderer/bridge/bridge.go and when I compiled the cmd/wails it build and installed as expected. So, how would I get `wails build` to use my modified go code in lib etc.

**Comment by AddictArts** [comment]
PS: You have a /scripts but it has to build files build.sh and build.go, they both seem to be equivalent. Thanks for all the help. Cheers

**Comment by leaanthony** [comment]
Hi. Haven't forgotten about this. Docs are hard 😃

**Comment by leaanthony** [comment]
I've updated https://wails.app/development/ - could you let me know ifthere's anything else you think should be added? Thanks.

**Comment by AddictArts** [comment]
Worked beautifully. I was kinda getting it, after the comments here. Understanding the command as a program, being separate from the code your app builds with, was at first disorienting. This as someone new to go. Thanks again and hopefully a pull request will follow, code is forked. Cheers
