### ISSUE TITLE
[v3] Template bring with .gitignore

### ISSUE THREAD

**Issue by northes** [wailsapp/wails#3852]
### Describe the solution you'd like

The template is recommended to bring .gitignore to simplify the development process

**Comment by northes** [comment]
such as:

```
.idea
.vscode
.task
bin

frontend/.svelte-kit
frontend/dist
frontend/node_modules
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏
