### ISSUE TITLE
Add best practices for react template

### ISSUE THREAD

**Issue by wail-asad** [wailsapp/wails#3859]
### Describe the solution you'd like

Implement this structure: [https://github.com/alan2207/bulletproof-react](https://github.com/alan2207/bulletproof-react)

**Comment by leaanthony** [comment]
Hi. Thanks for the suggestion. We don't deep dive any frontend projects but give you a starter template that you are free to enhance as you like. We are unlikely to move away from this any time soon. Thanks again.
