### ISSUE TITLE
Angular questions

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#386]
I am using wails with Angular and I followed the guides on api references / guides on the website but at some point in your frontend, you make usage of the "backend"(window.backend) and the "wails"(window.wails) properties, I cannot seem to find that property on with angular, could you indicate me what the right property is ? Thanks

**Comment by leaanthony** [comment]
Hi. This is in the docs though perhaps a bit subtle. These have nothing to do with Angular. window.wails is the JS Wails runtime and window.backend has all your Go sturcts and methods. I'd recommend going through the Todo tutorial.

**Comment by InfRandomness** [comment]
Yeah, I went through and I verified everything, the problem is that angular does not recognize the property "backend", so it refuses to compile 

```
    ERROR in src/app/register/register.component.ts(34,12): error TS2339: Property 'backend' does not exist on type 'Window'.

```

**Comment by leaanthony** [comment]
Does the default project work for you?

**Comment by InfRandomness** [comment]
If I init a project with the "wails init" command / configure it with angular, cd into the dir and execute "wails build" and execute the binary, everything runs yeah

**Comment by leaanthony** [comment]
I'm not sure I can answer your question then. Either `window` or `window.backend` is getting overwritten or your project has been configured in a way that doesn't include the wails runtime.

**Comment by InfRandomness** [comment]
it somehow doesn't work, I don't know what to do.

**Comment by brandonwkipp** [comment]
I ran into this issue using the `react` template, but only when I started using `typescript`. I had to add a global interface to my root component like this:
```
declare global {
  interface Window { backend: any; }
}
```
