### ISSUE TITLE
unable to set icon application icon in mac

### ISSUE THREAD

**Issue by kishorkumar287** [wailsapp/wails#3860]
### Description

unable to set icon application icon in mac, replaced appicon.png in build folder it works for windows but the same doesn't work for mac.

### To Reproduce

replace the appicon.png with your icon in build folder and build the executable it didn't work.
![image (8)](https://github.com/user-attachments/assets/f9be0aef-980e-4a8f-8567-3de824da67e9)

### Expected behaviour

The icon in the dock should be replaced but i am able to see only the default icon in mac.

### System Details

```shell
Wails Doctor
# Wails
Version | v2.9.2
# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                                                                   |
| Version      | 14.4.1                                                                                                                                                                  |
| ID           | 23E224                                                                                                                                                                  |
| Go Version   | go1.23.1                                                                                                                                                                |
| Platform     | darwin                                                                                                                                                                  |
| Architecture | amd64                                                                                                                                                                   |
| CPU          | Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz                                                                                                                              |
| GPU          | Chipset Model: Intel Iris Plus Graphics Type: GPU Bus: Built-In VRAM (Dynamic, Max): 1536 MB Vendor: Intel Device ID: 0x8a5c Revision ID: 0x0007 Metal Support: Metal 3 |
| Memory       | 8GB                                                                                                                                                                     |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2406    |
| Nodejs                    | N/A          | Installed | 20.14.0 |
| npm                       | N/A          | Installed | 10.7.0  |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Available |         |
└─────────────────── * - Optional Dependency ────────────────────┘
# Diagnosis
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Did you try the tips here? https://github.com/wailsapp/wails/issues/1143

**Comment by leaanthony** [comment]
Closing due to lack of response. Feel free to reopen if you have more information.

**Comment by kishorkumar287** [comment]
Yeah, tried in the same way, but still its not working in mac, the same works in windows.

**Comment by ansxuman** [comment]
> Yeah, tried in the same way, but still its not working in mac, the same works in windows.

It will not show for binary, try building package using `task package`

**Comment by kishorkumar287** [comment]
Sorry, @Ansxuman, I didn’t quite understand. Could you please explain it more clearly? If possible, could you also share any reference links?

**Comment by ansxuman** [comment]
> Sorry, @ansxuman, I didn’t quite understand. Could you please explain it more clearly? If possible, could you also share any reference links?

So basically now we have Taskfile in wails3 to automate the building part, you can use `task package` or `wails3 package` to build the package, there you will get the appIcon. If you build only the binary, the app icon will not be included. Once you build the package goto bin, there you will find your package <example.app>.

**Comment by leaanthony** [comment]
He's asking about v2. `wails build` will include the icon.

**Comment by ansxuman** [comment]
> He's asking about v2. `wails build` will include the icon.

Ah, my mistake. Looks like I am too involved in my project, which uses Wails 3.

**Comment by mylordkaz** [comment]
Hi guys, I don’t wanted to open a new issue as it’s a bit similar. 
I’m on Wails v2.9
I found out to set the icon for macOS but he don’t have that rounded corners style like most Mac app icons. 
I tried to use the icns format from Mac instead but it doesn’t seem to work either. 
Any hints or advice, how to set it properly ? 
Thanks you very much

**Comment by budiadiono** [comment]
If you are using Wails `v2.9.2` like me, you need to update `build/darwin/Info.plist` file under `CFBundleIconFile` section. I did it and it worked.

![Image](https://github.com/user-attachments/assets/07e8ecd9-0d06-4ff6-acc1-c37ab1b64687)

**Comment by mylordkaz** [comment]
@budiadiono

Thank you, I tried but it doesn't do the trick... Do you store the .icns icon in `build` or `build/darwin` ? 
If I don't have a png icon in build it will automatically create one. 
I tried with the icon in both location. same result. it only use my png icon.

**Comment by robksawyer** [comment]
Yeah, it's a bit unclear where the app icon should be placed to have `wails build` pick it up. Can someone confirm? Or is the process, run `wails build` and then replace the icon generated with your own icon and then run again or something?
