### ISSUE TITLE
blink on taskbar, change icon on taskbar, change title while running

### ISSUE THREAD

**Issue by Valdenirmezadri** [wailsapp/wails#3862]
### Describe the solution you'd like

I have a chat system in electron, it can do practically everything with wails3, which made me very satisfied. However, one thing that is very important for my clients is blinking, to get the client's attention.

I also need to change the icon of the application to inform that there are unread messages.

### Additional context

![screenshot_29-10-2024:16:44:01](https://github.com/user-attachments/assets/30895cee-daa8-4a2e-8938-43f361017c65)

**Comment by Valdenirmezadri** [comment]
blinks its ok calling focus(), but need change the icon to  toggle info

**Comment by leaanthony** [comment]
This can be done in v3 using `window.Flash()`. The implementation is here if you want to back port it to v2: https://github.com/wailsapp/wails/blob/086c7ae32d7380363b86cb39f616a1ce2e6b2e84/v3/pkg/w32/window.go#L255

**Comment by Valdenirmezadri** [comment]
cool, it worked, and how to change the icon while running the application?

**Comment by leaanthony** [comment]
Have you tried `window.SetIcon()`? Pease feel free to join our discord for more v3 support as the current policy during alpha is to discuss there. Good luck!

**Comment by victory-zz** [comment]
Hi bro, how do you implement the taskbar and tray icon blinking functionality? I'm using Wails v2 and the methods in the systrayll package, but I haven't been able to get it to work, which is really frustrating.
