### ISSUE TITLE
app interface keep flicking on macos m1/m3 when uses wails dev

### ISSUE THREAD

**Issue by daoxiaonoodles** [wailsapp/wails#3864]
### Description

app interface  keep flicking on macos m1/m3 when uses wails dev:

The console continuously prints logs  indicating that all frontend dependency files (in node_modules) cannot be found, and it keeps looping these log messages. Meanwhile, the app interface keeps flickering. I tried it on another Mac with an M1 chip, and the same issue occurs.

DEB | [AssetHandler] Handling request '/' (file='.')
DEB | [AssetHandler] File '.' not found, serving '/' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/'
DEB | [AssetHandler] Handling request '/src/main.ts' (file='src/main.ts')
DEB | [AssetHandler] File 'src/main.ts' not found, serving '/src/main.ts' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/main.ts'
DEB | [AssetHandler] Handling request '/@vite/client' (file='@vite/client')
DEB | [AssetHandler] File '@vite/client' not found, serving '/@vite/client' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/@vite/client'
DEB | [AssetHandler] Handling request '/node_modules/.pnpm/vite@2.9.18/node_modules/vite/dist/client/env.mjs' (file='node_modules/.pnpm/vite@2.9.18/node_modules/vite/dist/client/env.mjs')
DEB | [AssetHandler] File 'node_modules/.pnpm/vite@2.9.18/node_modules/vite/dist/client/env.mjs' not found, serving '/node_modules/.pnpm/vite@2.9.18/node_modules/vite/dist/client/env.mjs' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.pnpm/vite@2.9.18/node_modules/vite/dist/client/env.mjs'
DEB | [AssetHandler] Handling request '/node_modules/.vite/deps/element-plus.js' (file='node_modules/.vite/deps/element-plus.js')
DEB | [AssetHandler] Handling request '/src/App.vue' (file='src/App.vue')
DEB | [AssetHandler] Handling request '/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/dist/index.css' (file='node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/dist/index.css')
DEB | [AssetHandler] Handling request '/node_modules/.vite/deps/vue.js' (file='node_modules/.vite/deps/vue.js')
DEB | [AssetHandler] File 'node_modules/.vite/deps/vue.js' not found, serving '/node_modules/.vite/deps/vue.js' by AssetHandler
DEB | [AssetHandler] File 'node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/dist/index.css' not found, serving '/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/dist/index.css' by AssetHandler
DEB | [AssetHandler] File 'node_modules/.vite/deps/element-plus.js' not found, serving '/node_modules/.vite/deps/element-plus.js' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.vite/deps/vue.js?v=0a6c803c'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.vite/deps/element-plus.js?v=0a6c803c'
DEB | [AssetHandler] Handling request '/node_modules/.vite/deps/element-plus_es_locale_lang_zh-cn.js' (file='node_modules/.vite/deps/element-plus_es_locale_lang_zh-cn.js')
DEB | [AssetHandler] File 'node_modules/.vite/deps/element-plus_es_locale_lang_zh-cn.js' not found, serving '/node_modules/.vite/deps/element-plus_es_locale_lang_zh-cn.js' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/dist/index.css'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.vite/deps/element-plus_es_locale_lang_zh-cn.js?v=0a6c803c'
DEB | [AssetHandler] File 'src/App.vue' not found, serving '/src/App.vue' by AssetHandler
DEB | [AssetHandler] Handling request '/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/theme-chalk/dark/css-vars.css' (file='node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/theme-chalk/dark/css-vars.css')
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/App.vue'
DEB | [AssetHandler] File 'node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/theme-chalk/dark/css-vars.css' not found, serving '/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/theme-chalk/dark/css-vars.css' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.pnpm/element-plus@2.8.0_vue@3.4.38_typescript@4.9.5_/node_modules/element-plus/theme-chalk/dark/css-vars.css'
DEB | [AssetHandler] Handling request '/node_modules/.vite/deps/chunk-TWLJ45QX.js' (file='node_modules/.vite/deps/chunk-TWLJ45QX.js')
DEB | [AssetHandler] File 'node_modules/.vite/deps/chunk-TWLJ45QX.js' not found, serving '/node_modules/.vite/deps/chunk-TWLJ45QX.js' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.vite/deps/chunk-TWLJ45QX.js?v=0a6c803c'
DEB | [AssetHandler] Handling request '/node_modules/.vite/deps/chunk-USMWXLSI.js' (file='node_modules/.vite/deps/chunk-USMWXLSI.js')
DEB | [AssetHandler] File 'node_modules/.vite/deps/chunk-USMWXLSI.js' not found, serving '/node_modules/.vite/deps/chunk-USMWXLSI.js' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/.vite/deps/chunk-USMWXLSI.js?v=0a6c803c'
DEB | [AssetHandler] Handling request '/__vite_ping' (file='__vite_ping')
DEB | [AssetHandler] File '__vite_ping' not found, serving '/__vite_ping' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/__vite_ping'
DEB | [AssetHandler] Handling request '/' (file='.')
DEB | [AssetHandler] File '.' not found, serving '/' by AssetHandler

### To Reproduce

1.open project (vue3+typescript)
2.wails dev

### Expected behaviour

no flicking and can click button or input text

### Attempted Fixes

1.cd frontend && rm -rf node_modules
2. pnpm install
3. cd .. && wails dev

### System Details

```shell
# Wails
Version | v2.9.2

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.6                                                                                                                        |
| ID           | 23G80                                                                                                                       |
| Go Version   | go1.21.1                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | amd64                                                                                                                       |
| CPU          | Apple M3 Pro                                                                                                                |
| GPU          | Chipset Model: Apple M3 Pro Type: GPU Bus: Built-In Total Number of Cores: 18 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 18GB                                                                                                                        |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version        |
| Xcode command line tools  | N/A          | Installed | 2408           |
| Nodejs                    | N/A          | Installed | 18.20.2        |
| npm                       | N/A          | Installed | 10.5.0         |
| *Xcode                    | N/A          | Installed | 15.3 (15E204a) |
| *upx                      | N/A          | Available |                |
| *nsis                     | N/A          | Available |                |
└─────────────────────── * - Optional Dependency ───────────────────────┘
```

**Comment by daoxiaonoodles** [comment]
finally i resolved by update devDependencies as follows:

"devDependencies": {
    "@vitejs/plugin-vue": "^3.0.3",
    "typescript": "^4.6.4",
    "vite": "^3.0.7",
    "vue-tsc": "^1.8.27",
    "@babel/types": "^7.18.10"
  }




And the problematic version is as follows:

"devDependencies": {
    "@vitejs/plugin-vue": "^1.9.0",
    "typescript": "^4.4.3",
    "vite": "^2.5.10",
    "vue-tsc": "^0.3.0"
  }

**Comment by leaanthony** [comment]
Just tried this on an M2 and it works as expected.

**Comment by leaanthony** [comment]
Closing this for now as it sounds like you fixed your issue 👍
