### ISSUE TITLE
Support Distribution 'Solus'

### ISSUE THREAD

**Issue by gohryt** [wailsapp/wails#387]
**Description**
Distribution 'solus' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.14.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | solus |
| Distribution Name   | Solus |
| Distribution Version   | 4.1 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
Can you please provide more information like is Solus based on an existing distro?

**Comment by leaanthony** [comment]
There doesn't appear to be an obvious way to check if a package is installed or not. Running `eopkg info` returns an exit code of 0 regardless. The only option is parsing stdout from this command. Can you think of a better way?

**Comment by leaanthony** [comment]
I've added in support for Solus in the latest pre-release `wails update -pre`. 
![image](https://user-images.githubusercontent.com/1943904/82963131-5f28a000-a005-11ea-8340-e999a4bb2f2f.png)

**Comment by leaanthony** [comment]
No response. Closing.
