### ISSUE TITLE
wails3 custom template

### ISSUE THREAD

**Issue by Hunmuhe** [wailsapp/wails#3875]
### Is your feature request related to a problem? Please describe.

cmd: wails3 init -n myapp -t https://github.com/misitebao/wails-template-vue
ERROR: invalid template name: https://github.com/misitebao/wails-template-vue. Use -l flag to list valid templates

### Describe the solution you'd like

wails3 init -n myapp -t https://github.com/misitebao/wails-template-vue
need custom template

**Comment by Hunmuhe** [comment]
Because the official templates are too few and not very suitable for my preferences.

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏
