### ISSUE TITLE
Error: flag provided but not defined: -ldflags

### ISSUE THREAD

**Issue by ndoubismarck** [wailsapp/wails#388]
**Description**
I am trying to build a Wails Windows executable on MacOS using the following command `env GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc CGO_ENABLED=1 wails build -ldflags -H=windowsgui` or `env GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc CGO_ENABLED=1 wails build -ldflags="-H windowsgui"` and I am getting this error `Error: flag provided but not defined: -ldflags`. Building without `-ldflags` works fine and the windows executable is working fine, except that it shows the console window alonside the application window. What am I missing here?

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the Terminal App on MacOS
2. `cd` to your wails project directory
3. Type `env GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc CGO_ENABLED=1 wails build -ldflags -H=windowsgui` or `env GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc CGO_ENABLED=1 wails build -ldflags="-H windowsgui"` and press return
4. See the error `Error: flag provided but not defined: -ldflags`

**Expected behaviour**
A windows executable file must be generated

**System Details**
<table>
<tr>
<td>Platform</td><td>MacOS 10.11 (darwin/amd64)</td>
</tr>
<tr>
<td>GO Version</td><td>go1.14.2</td>
</tr>
<tr>
<td>Wails Version</td><td>1.0.2</td>
</tr>
<tr>
<td>GO111MODULE</td><td>Not Set (solves nothing even when set to on)</td>
</tr>
</table>

**Additional context**
My main goal is to disable the Windows console which pops up alongside the wails application window?

**Comment by leaanthony** [comment]
Hi. We don't support this in this way, although if you look at the PRs, we have a solution in the pipeline 👍

**Comment by ndoubismarck** [comment]
Okay, thanks. But in the meantime, how can I disable the Windows console which pops up alongside the wails application window?

**Comment by leaanthony** [comment]
If you don't want to use the cross compile branch then the only option currently is compile it on windows.
