### ISSUE TITLE
Error in serving frontend after build -p

### ISSUE THREAD

**Issue by alinangnaiba** [wailsapp/wails#389]
**Description**

After packaging the application I get an error when running npm run serve the frontend. Looking at the Sources tab the issue is from this line window.wails._.Init(callback);

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build -p`
2. Run `npm run serve` in frontend directory
3. In the browser go to `localhost:8080` or where ever your app is running
4. Open dev tool to view console error

**Screenshots**
![image](https://user-images.githubusercontent.com/6457958/79682836-2c49fa00-8258-11ea-950b-6e007bec31fe.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.10.2 |
| Node          | v12.8.1
 |

**Comment by leaanthony** [comment]
Serve isn't for packaged apps. Only package them when you're ready to distribute them. Does it work for you without the -p?

**Comment by alinangnaiba** [comment]
No, I wanted to make additional functionality in the app after it is packaged. I want to add code and run serve again

**Comment by alinangnaiba** [comment]
Ok, so I tried creating a new app with wails init, this time I chose the vuetify template. I get the same error. It's the first time I ran npm run serve and I have not edited the code.

**Comment by alinangnaiba** [comment]
I figured what happened. Thanks!

**Comment by leaanthony** [comment]
what happened?

**Comment by alinangnaiba** [comment]
A user error. Backend was not running and I forgot to comment out Wails.Init(). :)

**Comment by leaanthony** [comment]
you shouldn't need to comment out wails.Init. If it doesn't work without commenting it out, please reopen this.
