### ISSUE TITLE
input style error

### ISSUE THREAD

**Issue by nzlov** [wailsapp/wails#3893]
### Description

Input style is abnormal, initialize the project
* Input width is very narrow
* Input has no cursor
* Input has no selection color

### To Reproduce

1. wails init -n dt -t vue
2. wails dev

### Expected behaviour

input style ok

### Screenshots

init width
![image](https://github.com/user-attachments/assets/00e40335-5fa9-4005-b4c9-3a05f0d1a453)

modify width

![image](https://github.com/user-attachments/assets/6ea6a806-db32-4167-a3dc-7ae22c2200d9)

### System Details

```shell
Wails Doctor          
                                

                                                                               
# Wails
Version         | v2.9.2
Package Manager | pacman

# System
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Arch Linux                                                                     |
| Version      | Unknown                                                                        |
| DM           | Hyprland                                                                       |
| ID           | arch                                                                           |
| Go Version   | go1.23.2                                                                       |
| Platform     | linux                                                                          |
| Architecture | amd64                                                                          |
| CPU          | AMD Ryzen 9 7945HX with Radeon Graphics                                        |
| GPU          | AD107M [GeForce RTX 4060 Max-Q / Mobile] (NVIDIA Corporation) - Driver: nvidia |
| Memory       | 66GB                                                                           |
└───────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version                     |
| *docker    | docker       | Installed | 1:27.3.1-1                  |
| gcc        | gcc          | Installed | 14.2.1+r134+gab884fffe3fc-1 |
| libgtk-3   | gtk3         | Installed | 1:3.24.43-4                 |
| libwebkit  | webkit2gtk   | Installed | 2.46.3-1                    |
| npm        | npm          | Installed | 10.9.0-1                    |
| pkg-config | pkgconf      | Installed | 2.1.1-1                     |
└────────────────────── * - Optional Dependency ──────────────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by nzlov** [comment]
wails3 same problem.


                                
          Wails Doctor          
                                

                                                                                   
# System
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Arch Linux                                                                      |
| Version      | Unknown                                                                         |
| ID           | arch                                                                            |
| Branding     |                                                                                 |
| Platform     | linux                                                                           |
| Architecture | amd64                                                                           |
| CPU          | AMD Ryzen 9 7945HX with Radeon Graphics                                         |
| GPU 1        | AD107M [GeForce RTX 4060 Max-Q / Mobile] (NVIDIA Corporation) - Driver: nvidia  |
| Memory       | 66GB                                                                            |
└────────────────────────────────────────────────────────────────────────────────────────────────┘

# Build Environment
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.7                                                                                                            |
| Go Version     | go1.23.3                                                                                                                  |
| -buildmode     | exe                                                                                                                       |
| -compiler      | gc                                                                                                                        |
| CGO_CFLAGS     |                                                                                                                           |
| CGO_CPPFLAGS   |                                                                                                                           |
| CGO_CXXFLAGS   |                                                                                                                           |
| CGO_ENABLED    | 1                                                                                                                         |
| CGO_LDFLAGS    |                                                                                                                           |
| DefaultGODEBUG | asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1 |
| GOAMD64        | v1                                                                                                                        |
| GOARCH         | amd64                                                                                                                     |
| GOOS           | linux                                                                                                                     |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────┐
| webkit2gtk | 2.46.3-1                    |
| gcc        | 14.2.1+r134+gab884fffe3fc-1 |
| gtk3       | 1:3.24.43-4                 |
| npm        | 10.8.3                      |
| pkg-config | 2.1.1-1                     |
└──────── * - Optional Dependency ─────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

Need documentation? Run: wails3 docs

 ♥   If Wails is useful to you or your company, please consider sponsoring the project: wails3 sponsor

**Comment by leaanthony** [comment]
Honestly, this sounds like a local issue if it's in both v2 and v3 for you. Do the other templates look the same?

**Comment by nzlov** [comment]
The same is true for other templates. I also suspect that it is a local environment problem, but I don’t know how to troubleshoot it.

**Comment by nzlov** [comment]
I tested the `xfce` environment. If webgpu is enabled, an error message appears when starting up.
```
Failed to create GBM buffer of size 1024x768: Invalid argument
```
Enable the environment by setting `WEBKIT_DISABLE_DMABUF_RENDERER=1`. There is no problem.
If `hyprland` is used, `GDK_BACKEND=x11` and `WEBKIT_DISABLE_DMABUF_RENDERER=1` are set, and the interface does not respond.


![image](https://github.com/user-attachments/assets/98830255-fa6b-488d-b8f1-0d99bfb52ea6)

**Comment by nzlov** [comment]
I tested the `xfce` environment. If webgpu is enabled, an error message appears when starting up.
```
Failed to create GBM buffer of size 1024x768: Invalid argument
```
Enable the environment by setting `WEBKIT_DISABLE_DMABUF_RENDERER=1`. There is no problem.
If use `hyprland` or `plasma`  with `wayland`,
Set `GDK_BACKEND=x11` and `WEBKIT_DISABLE_DMABUF_RENDERER=1`, the interface will not respond.

**Comment by nzlov** [comment]
use `plasma 6` , get `Gdk-Message: 17:20:38.372: Error 71 (Protocol error) dispatching to Wayland display.`
```
Wails CLI v2.9.2

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.

> frontend@0.0.0 dev
> vite


  VITE v3.2.11  ready in 136 ms

Vite Server URL: http://localhost:5173/
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  • Generating bindings: Done.
  • Compiling application: Done.
  • Packaging application: Done.

Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:5173/
Using reload debounce setting of 100 milliseconds
Watching (sub)/directory: /home/nzlov/workspaces/wails/json
INF | Serving assets from frontend DevServer URL: http://localhost:5173/
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
DEB | [DevWebServer] Serving DevServer at http://localhost:34115
DEB | [AssetHandler] Handling request '/' (file='.')
DEB | [AssetHandler] File '.' not found, serving '/' by AssetHandler
DEB | [ExternalAssetHandler] Loading 'http://localhost:5173/'
Gdk-Message: 17:20:38.372: Error 71 (Protocol error) dispatching to Wayland display.
^C
Caught quit
Development mode exited
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

**Comment by nzlov** [comment]
Not sure what happened, this bug disappeared today
