### ISSUE TITLE
I do this using v3-alpha  wails3 dev times an error

### ISSUE THREAD

**Issue by mmdi1** [wailsapp/wails#3906]
### Description

I do this using v3-alpha

wails3 init -n deme -t vue-ts
cd demo && wails3 dev
error:
SRC/components/HelloWorld. Vue (4, 2) : error TS2307: Cannot find module '@wailsio/runtime' or its corresponding type declarations.
ERROR   task: Failed to run task "build": exit status 2
2024/11/24 00:22:10 ERROR Running Command exec="wails3 task build" err="exit status 1"

### To Reproduce

I do this using v3-alpha

wails3 init -n deme -t vue-ts
cd demo && wails3 dev
error:
SRC/components/HelloWorld. Vue (4, 2) : error TS2307: Cannot find module '@wailsio/runtime' or its corresponding type declarations.
ERROR   task: Failed to run task "build": exit status 2
2024/11/24 00:22:10 ERROR Running Command exec="wails3 task build" err="exit status 1"

wails3 init -n deme -t vue
cd demo && wails3 dev
All is well

Excuse me, where did I go wrong??

node version:18
All other configurations are default
my package.json:
{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@types/node": "^22.9.3",
    "path": "^0.12.7",
    "vue": "^3.2.45"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "@wailsio/runtime": "latest",
    "typescript": "^4.9.3",
    "vite": "^5.0.0",
    "vue-tsc": "^1.0.11"
  }
}

### Expected behaviour

wails3 init -n deme -t vue-ts
cd demo && wails3 dev
Normal operation

### System Details

```shell
system: Apple M2
node: v18.20.4
wails: v3.0.0-alpha.7
vite: vite/5.4.3 darwin-arm64 node-v18.20.4
vue: @vue/cli 5.0.8
@types/node: 22.9.3
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏

**Comment by ilaziness** [comment]
Version downgrade
