### ISSUE TITLE
Does that possible to open new window from menu?

### ISSUE THREAD

**Issue by sheenazien8** [wailsapp/wails#3929]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

How can i open the new window from menu?

in my case i want to open the setting page in new window.

![Screenshot 2024-12-04 at 17 20 10](https://github.com/user-attachments/assets/70d9f114-4f7a-48ea-8483-da5ba4f3675b)

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Not in v2, but you can in v3 - https://v3alpha.wails.io
