### ISSUE TITLE
[V3]Add monitorchange event 

### ISSUE THREAD

**Issue by c1ngular** [wailsapp/wails#3934]
### Is your feature request related to a problem? Please describe.

V3 has get screens feature, but lacking screen/monitor change event , so no efficient way to get notified when monitor connected or disconnected . 

### Describe the solution you'd like

Add application level event i e. screenchange , to watch monitor changes

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏
