### ISSUE TITLE
Wails Quasar runs in serve but not in build

### ISSUE THREAD

**Issue by SGarno** [wailsapp/wails#394]
**Description**

After applying vue add Quasar to new Wails project frontend, the application displays properly in npm run serve but when built, nothing shows.   Quasar is a vue plugin.

**To Reproduce**
Steps to reproduce the behaviour:

Install Vue/CLI and [Quasar](https://quasar.dev/)

- wails init myProj
- cd myProj\frontend
- vue add quasar

within frontend, `npm run serve` displays the application properly

when `wails build` is used, it is a blank screen.

Putting in Wails.Log.Info() messages show that the App.vue is mounting, but the quasar components are not recognized.

No errors are displayed and `<Shift><Esc>` does not bring up any console message.  No errors are displayed, just not rendered.

**Expected behaviour**
Should render same as npm run serve

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.14.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.13.4 |
| Node          | v12.16.1
 |

**Additional context**

**main.js**
```
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import Vue from 'vue';
import App from './App.vue';

Vue.config.productionTip = false;
Vue.config.devtools = true;

import * as Wails from '@wailsapp/runtime';
import './quasar'

Wails.Init(() => {
	Wails.Log.Info("Intialized")
	new Vue({
		render: h => h(App)
	}).$mount('#app');
});
```

**app.vue**

```
<template>
  <div id="app">
    <img
      alt="Wails logo"
      src="./assets/images/logo.png"
      class="logo zoomIn"
    >
    <HelloWorld />
    <q-layout view="lHh Lpr lFf">
      <q-header
        elevated
        class="glossy"
      >
        <q-toolbar>
          <q-btn
            flat
            dense
            round
            @click="leftDrawerOpen = !leftDrawerOpen"
            aria-label="Menu"
            icon="menu"
          />

          <q-toolbar-title>
            Quasar App
          </q-toolbar-title>

          <div>Quasar v{{ $q.version }}</div>
        </q-toolbar>
      </q-header>

      <q-drawer
        v-model="leftDrawerOpen"
        show-if-above
        bordered
        content-class="bg-grey-2"
      >
        <q-list>
          <q-item-label header>Essential Links</q-item-label>
          <q-item
            clickable
            tag="a"
            target="_blank"
            href="https://quasar.dev"
          >
            <q-item-section avatar>
              <q-icon name="school" />
            </q-item-section>
            <q-item-section>
              <q-item-label>Docs</q-item-label>
              <q-item-label caption>quasar.dev</q-item-label>
            </q-item-section>
          </q-item>
          <q-item
            clickable
            tag="a"
            target="_blank"
            href="https://github.com/quasarframework/"
          >
            <q-item-section avatar>
              <q-icon name="code" />
            </q-item-section>
            <q-item-section>
              <q-item-label>Github</q-item-label>
              <q-item-label caption>github.com/quasarframework</q-item-label>
            </q-item-section>
          </q-item>
          <q-item
            clickable
            tag="a"
            target="_blank"
            href="https://chat.quasar.dev"
          >
            <q-item-section avatar>
              <q-icon name="chat" />
            </q-item-section>
            <q-item-section>
              <q-item-label>Discord Chat Channel</q-item-label>
              <q-item-label caption>chat.quasar.dev</q-item-label>
            </q-item-section>
          </q-item>
          <q-item
            clickable
            tag="a"
            target="_blank"
            href="https://forum.quasar.dev"
          >
            <q-item-section avatar>
              <q-icon name="forum" />
            </q-item-section>
            <q-item-section>
              <q-item-label>Forum</q-item-label>
              <q-item-label caption>forum.quasar.dev</q-item-label>
            </q-item-section>
          </q-item>
          <q-item
            clickable
            tag="a"
            target="_blank"
            href="https://twitter.com/quasarframework"
          >
            <q-item-section avatar>
              <q-icon name="rss_feed" />
            </q-item-section>
            <q-item-section>
              <q-item-label>Twitter</q-item-label>
              <q-item-label caption>@quasarframework</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-drawer>

      <q-page-container>
        <HelloWorld />
      </q-page-container>
    </q-layout>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import Wails from '@wailsapp/runtime';
import "./assets/css/main.css";

export default {
  name: 'app',

  components: {
    HelloWorld
  },

  data () {
    return {
      leftDrawerOpen: false
    }
  },

  mounted () {
    Wails.Log.Info("Mounted the app");
  }
}
</script>

<style>
</style>

```

**babel.config.js**
```
module.exports = {
  "presets": [
    [
      "@vue/app",
      {
        "useBuiltIns": "entry"
      }
    ]
  ],
  "plugins": [
    [
      "transform-imports",
      {
        "quasar": {
          "transform": "quasar/dist/babel-transforms/imports.js",
          "preventFullImport": true
        }
      }
    ]
  ]
}
```

**Comment by SGarno** [comment]
I have made some progress and close to having a Quasar template for Wails...but I am stuck now and not sure how to debug this.    

I have been able to determine that the quasar components and the CSS is being properly loaded into the app.   But I am still getting nothing rendered inside any components.    I do see things being rendered outside of a component.

```
<template>
  <div>
    <h5>Components {{ JSON.stringify(Object.keys($options.components))}}</h5>
    <q-layout view="lHh Lpr lFf">
          :
    </q-layout>
  </div>
</template>
```

The H5 gets displayed, but anything in q-layout does not.   

Any suggestions on how I can debug this? (npm run serve works, just wails build does not)    The `wails build -d` creates a debug version, but I cannot get into the console to see if there are errors.  

Any help would be greatly appreciated!

**Comment by leaanthony** [comment]
Hey thanks for the effort in trying to solve this. I have no experience with Quasar. Is the issue that the Quasar library itself isn't getting included in the generated bundle? Also, FYI: run your app with `-loglevel debug` to get spam-level output to the console. Unfortunately mshtml doesn't come with a debug window though i did try to hack one together which you should be able to access via `SHIFT-ESC`. V2 will use Edge/Chromium so thankfully this problem will be old news in the near future.

**Comment by SGarno** [comment]
Quasar is indeed getting instantiated.  It uses $q, so in the Vue template I have $q.Version and it displays properly.   There is one thing that happens during the webpack....perhaps this is the issue:

```
40% building 177/212 modules 35 active D:\Development\wails\frontend\node_modules\core-js\internals\is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. 
Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
40% building 178/213 modules 35 active D:\Development\wails\frontend\node_modules\querystring-es3\decode.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick 
plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
98% after emitting SizeLimitsPlugin
```

As for loglevel....it doesn't seem to output anything different than the normal debug build (compiled using wails build -d).   Is this flag for the compiled app or wails?

I cannot seem to get to the `Shift-ESC` to work on the built app.   Keep in mind I am referring to all this stuff not working when running from a `wails build -d`.   Everything runs properly in `wails serve`.    

I am using the published build of wails....should I be using the -pre??

**Comment by leaanthony** [comment]
It's a flag for the compiled app in debug mode. There's been a number of updates to the `-pre` branches - perhaps try it? You can try it using `wails update -pre` and if you want to revert just run `wails update`. Shift-Esc should work but....windows is hard.

The thing to remember is that the WebView used for rendering content in the compiled apps is not a full browser. Some libraries will use features unavailable to it - hence why it might work in serve and not in build. Serve was intended to make developing easier but perhaps we should drop it?

**Comment by SGarno** [comment]
Ok, I went ahead and created a linux vm to try this there and see if I can get a console up and running (via Shift-Esc) and debug the issue.   I ran into a number of problems including the wails command line app doesn't compile.    (should I log these issues separately?)

The short of it is, I finally got wails to build and run.   I performed a wails init using the basic Vue app and it comes up black.    When I run it as wails/npm serve, I can see that window.wails is not defined.

I tried to upgrade to -pre, but the version on linux shows up as v1.5.0 and the upgrade will not work.   When I try to specify the version on the command line, it fails and says it can't find it.   I edited the version.go file, recompiled, and still no luck.   It generates the error `invalid github.com/ import path "github.com/wailsapp/wails/cmd/wails@v1.0.3-pre2"`

I am running this on Linux Mint Cinnamon (essentially Ubuntu 18.04).

Struggling to find a way to debug this and get it working....any other thoughts?    I really like the idea of wails.    So much better than using Electron with NodeJS as a backend.

**Comment by leaanthony** [comment]
I'm amazed you've had so many issues, which is unusual. 1.5.0 is the latest so you won't get any pre-release updates. Editing the version.go will not do anything except give you errors. 

Was your original compile issue similar to this: https://github.com/wailsapp/wails/issues/398?

**Comment by leaanthony** [comment]
I appreciate you spending time looking at this. potentially it is a clash with the #app div. Officially we only support the supplied templates for this reason: we can't test every combination of js frameworks and libs. That being said, if you upload an example project demonstrating your issue then we may be able to look at it. It would be good to add to our templates.

Regarding slow start ups, this is especially true on Windows. We're addressing this in v2.

**Comment by SGarno** [comment]
It is very simple to reproduce.    Assuming you have @vue/cli installed, then from the command line:

- wails init (use Vue template)
- cd frontend
- vue add quasar

That's it.    

BTW:  I really love what you have done here...it is what I have been hoping for:  A modern UI onto a performant backend that is distributed as a single multi-platform binary.   (could that be utopia?? :)

**Comment by SGarno** [comment]
One comment on the above....that is the way to simply track down what the issue might be; as it just modifies the existing app with the quasar plugins into Vue.  

But, if you can help me get to the root cause and get it to work, I would like to try to create a wails template that is built off of using the Quasar CLI (if possible).   Ideally, one that can take the output of the Quasar CLI and just drop it into wails seamlessly.    

The reason for this is because the quasar cli allows you to specify various modules (i.e. Axios, Fontawesome, etc) to incorporate in your project when it is generated.    Worst case, I can create multiple wails templates with the different configurations to get the same effect.

**Comment by leaanthony** [comment]
I believe @bh90210 took a similar approach to the Angular CLI. You might want to check that out. I'll have a look at it, however that's not likely to be until at least this weekend. But I *will* look at it when I can.

**Comment by SGarno** [comment]
Most appreciated and thank you!!

**Comment by bh90210** [comment]
hey @SGarno I am sure it is possible albeit tedious.

The whole process of maintaining custom cli forks makes it really hard to justify doing it while v2 address these kinds of issues and enable all such CLIs use natively. (if I have understood the design right  :-p)

**Comment by SGarno** [comment]
@bh90210 Where did you get the information on v2?    I read Post V1 Enhancements but didn't see anything specific about what would be coming to enable other CLIs to be used.    

What I was hoping to do was find out what is needed to make Quasar work in Wails, then figure out how to bridge the gap between what is needed and what is provided by the Quasar CLI.    Perhaps go the other direction and make a `vue add wails` component or something similar if I could not do it within wails template.

Anyway, this is a great project and am pretty excited about the potential.   I hope the issue with WebView gets sorted out.   I prefer webview over Chromium from a footprint perspective.

**Comment by leaanthony** [comment]
I can speak to this. V2 has been evolvinflg from some experiments in my private repo so it kinda non public right now. It would be good to understand how you would solve this and what yourideal outcome would be and we can try to kick that goal 😃

**Comment by SGarno** [comment]
The bot closed this issue....Is this something you are still considering?

**Comment by leaanthony** [comment]
Would love to support it but don't have time. Am happy to accept a PR if
you get it working though!
