### ISSUE TITLE
Is there a way to open a window in a specific screen?

### ISSUE THREAD

**Issue by tomiamao** [wailsapp/wails#3946]
### Describe the solution you'd like

Working on a presentation software that needs to open multiple windows on different screens. Is there a way to open a window on a specific screen?

For example, assume I have 2 screens connected to a computer. When the app is run, i want to show the slide notes on the primary screen (the one the presenter is using) and then the actual presentation slide on another screen (e.g a projector). Is this possible in v3? looked through the docs and don't find anything talking about this.

**Comment by leaanthony** [comment]
For v2, no. Let's track this request in #3947
