### ISSUE TITLE
Generated bindings include context.Context

### ISSUE THREAD

**Issue by MenzenJ** [wailsapp/wails#3948]
### Description

Hello,

as far as I understood, if I add a context as the first parameter to a function in go the generated binding should not include it as a parameter.
Allowing me to cancel it by calling `promise.cancel()`

But in my project it is included anyways on every function I use a context as first parameter.
I am using the vue-ts template and even on a clean project I get the same behavior.

Example go function:
```golang
func (a *App) Greet(ctx context.Context, name string) string {
  return fmt.Sprintf("Hello %s, It's show time!", name)
}
```

Generated binding:
```typescript
import {context} from '../models';

export function Greet(arg1:context.Context,arg2:string):Promise<string>;
```

It will even not generate a `models.ts` file and the frontend compilation fails:
```
Wails CLI v2.9.2

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build

    src/components/HelloWorld.vue(11,3): error TS2554: Expected 2 arguments, but got 1.

  ERROR   exit status 2
```

This issue is somewhat related to https://github.com/wailsapp/wails/issues/2348 but already with the example app it is reproducible.

I will try to create a pull request with a test and will link it here if I am able to (not sure if I know how to do it yet).

### To Reproduce

1. setup project with `wails init -n context-binding-reprod -t vue-ts`
2. navigate to `app.go`, change the `Greet` function signature to include `ctx context.Context` *as first parameter* (ensure the import is added, too)
3. run `wails dev`
4. see, that the frontend compile fails due to the `Greet`function now requiring a context parameter.

### Expected behaviour

The context parameter is omitted in the typescript function.

### Attempted Fixes

Tried to check if any of the template settings interfere but did not find anything related.

### System Details

```shell
# Wails
Version | v2.9.2

# System
┌──────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                        |
| Version      | 2009 (Build: 22631)                                                   |
| ID           | 23H2                                                                  |
| Go Version   | go1.22.2                                                              |
| Platform     | windows                                                               |
| Architecture | amd64                                                                 |
| CPU          | Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz                              |
| GPU 1        | Intel(R) UHD Graphics 630 (Intel Corporation) - Driver: 31.0.101.1999 |
| GPU 2        | NVIDIA Quadro T2000 (NVIDIA) - Driver: 32.0.15.5612                   |
| Memory       | 32GB                                                                  |
└──────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 131.0.2903.86 |
| Nodejs     | N/A          | Installed | 20.12.1       |
| npm        | N/A          | Installed | 10.5.0        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!
```

**Comment by MenzenJ** [comment]
I just realized I have read the v3 documentation, is it even possible to do it in v2?

I tested with the current wails3 and it works properly.

Edit: Seems like this was only added to version 3
https://github.com/wailsapp/wails/discussions/2765

**Comment by leaanthony** [comment]
Correct. We won't be supporting this in v2 as back porting that feature would involve significant work

**Comment by MenzenJ** [comment]
Thank you very much for your answer!
