### ISSUE TITLE
Support Distribution Unknown

### ISSUE THREAD

**Issue by yykpf** [wailsapp/wails#395]
系统版本：
![image](https://user-images.githubusercontent.com/14089155/79864506-272dac00-840c-11ea-824c-7307ff426dd1.png)
错误信息：
![image](https://user-images.githubusercontent.com/14089155/79864796-a4592100-840c-11ea-94d2-df2854c2e650.png)

**Comment by mattLLVW** [comment]
The issue is that there's no `/etc/os-release` in CentOS 6.10 which is how Wails determine distro infos.
The only sure way to get the needed infos is to parse `/etc/system-release` which looks like this:

```bash
CentOS release 6.10 (Final)
```

**Comment by bh90210** [comment]
indeed centos doesn't have `/etc/os-release` https://linuxconfig.org/how-to-check-centos-version

a simple way around it, haven't tested it though, as the article suggests is querying release info like this `cat /etc/*elease` 
it works on ubuntu, if someone can test on centos as well that'd be great :)

**Comment by leaanthony** [comment]
Re-opening this.
