### ISSUE TITLE
[wails3] windows file drag and drop throw error: WebviewWindow #4 not found

### ISSUE THREAD

**Issue by itlangzi** [wailsapp/wails#3950]
### Description

Use app.NewWebviewWindowWithOptions to create multiple windows, and then close the last created. The file drag and drop function of all  created windows will be unavailable. The error message is WebviewWindow #3 not found.

### To Reproduce

....

### Expected behaviour

Close any window, and the file drag and drop functions in other windows should work  well.

### System Details

```shell
System: windows
Go version: go1.23.4
Wails CLI: v3.0.0-alpha.8.3
```

**Comment by leaanthony** [comment]
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏
