### ISSUE TITLE
[v3] pattern webview2/MicrosoftEdgeWebview2Setup.exe: no matching files found

### ISSUE THREAD

**Issue by gerbil** [wailsapp/wails#3957]
### Description

Can't install wails via `v3-alpha` branch

Feels like latest update broke the thing:
```
Error: ../../internal/commands/generate_webview2.go:12:12: pattern webview2/MicrosoftEdgeWebview2Setup.exe: no matching files found
Error: Process completed with exit code 1.
```

### To Reproduce

1. Git clone
2. Switch to v3-alpha branch
3. Install wails via go install

### Expected behaviour

Installed successfully

### System Details

```shell
n/a
```

**Comment by leaanthony** [comment]
Thanks! the .gitignore was wrong. Fixed and pushed 👍
