### ISSUE TITLE
Angular Template AppRoute not working 

### ISSUE THREAD

**Issue by madlybong** [wailsapp/wails#396]
While "wails serve" everything is working fine.
But after successful "wails build" / "wails build -d" routing is not working ... (No error in debugger)

**app.module.ts**
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule, routes } from './app-routing.module';
import { AppComponent } from './app.component';

import { APP_BASE_HREF } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { LoginComponent } from './login/login.component';
import { CrudComponent } from './crud/crud.component';
import { PreviewComponent } from './preview/preview.component';

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    CrudComponent,
    PreviewComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule
  ],
  providers: [{provide: APP_BASE_HREF, useValue : '/' }],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**app-routing.module.ts**
`import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { CrudComponent } from './crud/crud.component';
import { PreviewComponent } from './preview/preview.component';

export const routes: Routes = [{
  path: '',
  redirectTo: '/login',
  pathMatch: 'full'
},
{
  path: 'login',
  component: LoginComponent
},
{
  path: 'crud',
  component: CrudComponent
},
{
  path: 'preview',
  component: PreviewComponent
}];

@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ],
  exports: [RouterModule]
})

export class AppRoutingModule { }`

**Comment by leaanthony** [comment]
Can't help specifically with Angular routing but routing in Vue was solved by [this person](https://github.com/wailsapp/wails/issues/236#issuecomment-532741700). Perhaps it's a similar fix?
