### ISSUE TITLE
Generate .ico files for Windows builds

### ISSUE THREAD

**Issue by dedo1911** [wailsapp/wails#397]
**Description**

After running `wails build -p` it successfully generates icon resources to edit (appname.ico) but this file gets deleted running `wails build` (without -p) or `wails serve`.

This appears to be happening for Windows resources only. macOS appicon.png is not being deleted.

Involved resources:
`appname.rc`
`appname.ico`
`appname.exe.manifest`
`appname-res.syso`

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build -p`
2. Check that resource files have been generated
3. Run `wails build` or `wails serve`
4. Check that resource files have been deleted

**Expected behaviour**
Resource files shouldn't be deleted (at least .ico) upon non packaging builds

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.13.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 6.13.7 |
| Node          | v13.8.0 |

**Comment by leaanthony** [comment]
This is working as intended. Originally the thought was just to keep the project clean. What's the scenario where this is causing a problem for you?

**Comment by dedo1911** [comment]
The issue is that .ico file is always the stock wails icon and is not being generated from appicon.png

This means that every time i need to manually add the .ico resource to the root of the project as it’s not being kept or correctly generated.

**Comment by leaanthony** [comment]
The ICO file absolutely should ve generated from the PNG. If that isn't the case, it's a bug.

**Comment by dedo1911** [comment]
Ok I've tried once more and I've modified **only** `appicon.png`
The result is the same:
macOS → builds are working correctly. appicon.png is being used correctly and .app folders display the correct icon.

Windows → builds generate the ico file from scratch using the default one if none is present, instead of generating it from appicon.png.

To get a correct Windows package I would need to manually convert png to ico then run a build again. This is a bug.

**Comment by leaanthony** [comment]
nice catch. I really thought we were generating the ICO file. This absolutely should be happening. Thanks for raising it.

**Comment by dedo1911** [comment]
1.6.0-pre2: icons are being used correctly from "appname.ico" and after build the file is being deleted.
I think only missing is ico generation then.

**Comment by leaanthony** [comment]
Looking back over the history, icon generation *was* something we wanted to do but didn't get round to. As the title of this issue now doesn't reflect the real issue, I've renamed it and added the enhancement label.

**Comment by dedo1911** [comment]
Here's a simple and working png to ico converter example I found on the web if you want to have a look
https://github.com/Kodeworks/golang-image-ico

**Comment by leaanthony** [comment]
Hey @dedo1911 - I've opened #416 for this. Please feel free to check it out and have a play.

**Comment by dedo1911** [comment]
I've taken a step further and improved the icon generation to generate the usual multiple sizes .ico that Windows uses (256, 128, 64, 48, 32, 16):

Full example: https://play.golang.org/p/FkaPiB3Y7AT

If you like It I can PR it

**Comment by leaanthony** [comment]
That sounds great! I've actually split off this functionality into a library+tool and was thinking of importing it back into Wails but I'm ok leaving that to v2. The code looks very similar :-)
