### ISSUE TITLE
ubuntu18.04  

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#398]
zhu@zhu-TM1703:~/go-dev/test1$ wails build
Wails v1.5.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
⣻ Ensuring Dependencies are up to date...# pkg-config --cflags  -- gtk+-3.0 webkit2gtk-4.0
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'world', not found
Package 'webkit2gtk-4.0', required by 'world', not found
pkg-config: exit status 1

**Comment by zhuqiyun** [comment]
when exute "wails build", output  above error

**Comment by tmclane** [comment]
You need to install the relevant packages to your system.

Is this ubuntu/debian?

```
sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev
```
