### ISSUE TITLE
Expose Hint from Webview to allow for finer window control

### ISSUE THREAD

**Issue by alex-zissis** [wailsapp/wails#400]
**Description**
Webview allows you to set a `Hint` which allows to control window resizing. The hint will change the dimensions you pass to the window to make them either maximum, minimum, none (default behaviour) or fixed. 

It would be great if this could be exposed in Wails. I want to set a minimum size for my app but allow users to make it larger if they please. I currently use `Resizable=true` however this behaviour means they can make the window smaller as well.

Thanks!

**Comment by leaanthony** [comment]
Hi! If this is available in WebView we can do it. It's absolutely going to be part of V2

**Comment by alex-zissis** [comment]
Perfect thank you :)
