### ISSUE TITLE
wails init

### ISSUE THREAD

**Issue by gauravbombatkar** [wailsapp/wails#401]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
I started to generate a new project using the wails init command. It takes a very long time to generate a new project. But the project did not create.

**To Reproduce**

**Expected behaviour**
 

**Screenshots**

**System Details**
Windows-7, GO version 1.13.6

**Additional context**

**Comment by leaanthony** [comment]
Please make a video with what you see and what gets created. Almost certainly this is an internet connection issue

**Comment by bh90210** [comment]
It has been reported before #368 #289 are the ones that are somehow most related to the above and yes I too agree it seems like an internet connection problem. 

Maybe we should address this in docs somewhere, for windows users, as a common bug/error/pitfall? (looking at init related issues it seems there are two broad categories. On linux usually either libraries missing or -while wails was younger- various CLI bugs, but these are mostly address by now. On windows though it seems that it is either connection issues or some other bug that I have no idea what it might be. But to the extend that it is persistent and we can not find out/fix, maybe address it by warning that there is a know glitch and suggest the `have you tried turning it off and on again` solution)

**Comment by leaanthony** [comment]
100% of the time I'm unable to reproduce this behaviour.
