### ISSUE TITLE
Support React with Typescript for frontend

### ISSUE THREAD

**Issue by tinhtruong** [wailsapp/wails#402]
**Description**

It would be great if I can use Typescript for my React application instead of Javascript

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 11.0.3 |
| Npm           | 6.9.0 |
| Node          | v10.16.1 |

**Additional context**

**Comment by leaanthony** [comment]
Feel free to use whatever you like for the frontend - Wails is not constraining you. Just make sure that you generate your js and css bundles in the same directory as default.

**Comment by getpoppn** [comment]
@leaanthony I think the op was speaking about the code generator. create-react-app has a typescript option. In general, I think it would be cool if there was a typescript option added to the cli.

**Comment by leaanthony** [comment]
That feels like it should be a new template. Happy to accept a PR!
