### ISSUE TITLE
how to  remove "titlebar"

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#403]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

**Comment by dedo1911** [comment]
If you're looking to create a borderless/frameless window, this is not (yet) possible.

**Comment by leaanthony** [comment]
If you're requesting this: https://github.com/wailsapp/wails/issues/338 please close and track that ticket. If not, then please clarify.
