### ISSUE TITLE
Page refresh F5

### ISSUE THREAD

**Issue by dedo1911** [wailsapp/wails#404]
Hello everyone.
I've just noticed that F5 reloads the page and breaks everything.
I've tried capturing the even on document keyup/keydown/keypress, none worked.

Is there a solution to avoid page refresh already or a way to completely disable it from webview itself?

Thanks in advance!

**Comment by leaanthony** [comment]
Great question! What OS etc?

**Comment by dedo1911** [comment]
Looks like Windows only.

I've tried also macOS and Linux (Ubuntu 20.04) and I wasn't able to refresh the page (F5 or ctrl/cmd+R)

**Comment by leaanthony** [comment]
Ultimately,  it's down to webview. We are replacing it for v2. Would gladly accept a PR to prevent this in out Webview fork

**Comment by leaanthony** [comment]
Looked briefly at this. It looks like we could just test the key being handled here: https://github.com/wailsapp/wails/blob/master/lib/renderer/webview/webview.h#L1489-L1523
Something like:
```
    switch (msg.message)
    {
    case WM_QUIT:
      return -1;
    case WM_COMMAND:
    case WM_KEYDOWN:
    case WM_KEYUP:
    {
      if ( msg.wParam == VK_F5 ) {     // ADDED
         break;                        // ADDED
      }                                // ADDED
      HRESULT r = S_OK;
      IWebBrowser2 *webBrowser2;
      IOleObject *browser = *w->priv.browser;
      if (browser->lpVtbl->QueryInterface(browser, iid_unref(&IID_IWebBrowser2),
                                          (void **)&webBrowser2) == S_OK)
      {
        IOleInPlaceActiveObject *pIOIPAO;
        if (browser->lpVtbl->QueryInterface(
                browser, iid_unref(&IID_IOleInPlaceActiveObject),
                (void **)&pIOIPAO) == S_OK)
        {
          r = pIOIPAO->lpVtbl->TranslateAccelerator(pIOIPAO, &msg);
          pIOIPAO->lpVtbl->Release(pIOIPAO);
        }
        webBrowser2->lpVtbl->Release(webBrowser2);
      }
      if (r != S_FALSE)
      {
        break;
      }
    }
    default:
      TranslateMessage(&msg);
      DispatchMessage(&msg);
    }
    return 0;
  }
```

If you want this done quickly, I'd suggest playing with this and raising a PR.

**Comment by dedo1911** [comment]
I've tested a local version with your suggested modification and works properly.
I'm not in a rush to PR it, but please try to include it in a future release if possible.
Thank you!

**Comment by leaanthony** [comment]
So that code worked as is?

**Comment by dedo1911** [comment]
Yes. I've just copy-pasted

**Comment by leaanthony** [comment]
This is now available in the latest pre-release: `wails update -pre` to get it!

**Comment by dedo1911** [comment]
Tried and patch works fine on latest pre (1.6.0-pre2) Thanks!
