### ISSUE TITLE
Is there any way to "unsubscribe" from an event?

### ISSUE THREAD

**Issue by vicsnow** [wailsapp/wails#405]
**Description**
I am running a project, having **appRun** as frontend.
There are two containers, I switch between, and both receive different events.

So I do `Wails.Events.On`  when I _mount_ the component
And it seems, that I need to unsub or ignore other component's events on _unmount_
So, like the title says, is there any way to **"unsubscribe"** from an event?
Or I just need to have some additional backend logic, which does only one event emission at a time?

**Additional context**
It looks like this: 
I have `<Data1 />` and `<Data2 />` containers
`Data1` has `Wails.Events.On("update_data1", ()=>{ ***update logic***})` when it's _mounted_
`Data2` has `Wails.Events.On("update_data2", ()=>{ ***update logic***})` when it's _mounted_
Let's say, that `<Data1/>` is currently rendered, **after** I did render `<Data2/>` and call it's _mounted_ method 
Receiving both `update_data1` and `update_data2` events leads to incorrect rendering 
So I need to either **"unsubscribe"** from `update_data2` event on `<Data2/>` _unmount_ , or have some workaround logic, which allows emitting only one event at a time

**Comment by leaanthony** [comment]
There currently isn't an unsubscribe feature but there probably should be. In your particular case, it sounds like you just need to ignore data2 events when data1 is mounted. If that's really what you want to do then potentially your listener can just test to see which component is mounted and ignore events for the hidden container. I guess I don't get why both containers are listening to each others events. Whilst I think having unsubscribe may be useful, it doesn't feel like that's the right solution for your particular problem.

**Comment by vicsnow** [comment]
Yea, okay, testing to see which component is mounted sounds like a reasonable solution. And that is an optimization anyways

**Comment by Jmeigs1** [comment]
I am running into this issue using react.  Binding ```Wails.Events.On``` with useEffect leads to the callback being bound multiple times, run when the component is not mounted, etc.  Workarounds are possible but its very idiomatic (in react at least) to bind and unbind as part of the component lifecycle.

Any chance this could be re-opened?

**Comment by leaanthony** [comment]
Funny timing. I just added this to v2. Should be relatively easy to backport.
