### ISSUE TITLE
FEEDBACK REQUESTED: Target Platforms

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#406]
In the absence of telemetry for Wails, I'd like to get feedback on target platforms. We did this about 9 months ago so would like a refresh.

Please reply with your target OSes (can be multiple).

Thank you!

**Comment by masterdubs** [comment]
OSX - Windows -Linux and mobile when possible ( IOS & Android ).

**Comment by nilopaim** [comment]
Windows. Linux and mobile in a distant future (maybe next year).

**Comment by dedo1911** [comment]
Windows, Linux, and macOS

**Comment by tmclane** [comment]
RaspberryPi (Linux), Windows, Linux (in general), OS X

**Comment by bh90210** [comment]
Ubuntu

**Comment by lukeholder** [comment]
linux, macos and windows

**Comment by Lyimmi** [comment]
Linux, RaspberryPi (Linux), Windows

**Comment by pedzed** [comment]
In the following order:
1. Linux (Ubuntu)
1. Windows
1. macOS
1. Web browser (Chrome OS?)

**Comment by ahmadfarisfs** [comment]
Raapberry pi

**Comment by TAINCER** [comment]
Windows and Linux

**Comment by leaanthony** [comment]
Thanks for the feedback everyone!
