### ISSUE TITLE
Unable build wails application if go.mod is located not in the same directory

### ISSUE THREAD

**Issue by svkior** [wailsapp/wails#411]
**Description**

I have big project with structure

`MainForderWithGoMod/projectlib/cmd/projectMain`

my go.mod is located in MainForderWithGoMod

**To Reproduce**
Steps to reproduce the behaviour:
1. cd MainForderWithGoMod/projectlib/cmd/projectMain
2. wails build
3. See error:

`
Wails v1.5.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
Error: Unable to load go.mod
`

**Expected behaviour**
I want to build project

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 11.0.3 |
| Npm           | 6.14.4 |
| Node          | v14.0.0 |

**Additional context**

**Comment by tmclane** [comment]
The `go.mod` file should be in the root of your project which is the normal location for a `go.mod` file.

If there is no `main.go` file in the root of the project this error can occur.
One workaround is to place a file named `main.go` or something else in the root and to simply import the private package containing your application in that file.  You can keep all your logic elsewhere but the current built system requires go code at the root of the project.

**Comment by leaanthony** [comment]
Do you have an example repo that reproduces this problem?

**Comment by svkior** [comment]
@tmclane  - OK. I see.
I'll check this solution in two days, and answer. I think I'll make example for this issue with private repo

**Comment by tmclane** [comment]
Here's an example project:

https://github.com/tmclane/wails-private

**Comment by leaanthony** [comment]
@svkior - I think I understand your issue now. This is tricky as it's confusing as to where your "project root" lies. Do you have an entire Wails project in `MainForderWithGoMod/projectlib/cmd/projectMain`? 

The reason this is happening is because the cli tries to ensure you have the same version of Wails in your go.mod as the one installed (having these out of sync will cause issues). It looks in the project root for the go.mod. 

Where is your `project.json` file? Happy to reopen if you engage with the ticket, otherwise it will be closed.

**Comment by tmclane** [comment]
@leaanthony @svkior Does my example project not match up to how you would like to use the project?

I thought my solution was a reasonable workaround (one that I used in my own project even).

**Comment by leaanthony** [comment]
I could be wrong, but I think he has his entire wails project under cmd, but the go.mod outside of that. Will leave this open another week.
