### ISSUE TITLE
win10  docker  cross-compile    

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#412]
this is compile result:

Wails v1.5.0 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
> Ensuring Dependencies are up to date...
> Pulling wailsapp/xgo:latest docker image... (may take a while)
> Packing + Compiling project for linux/arm-7 using docker image wailsapp/xgo:latest...
Awesome! Project 'gateway' built!

question:    can't find image，where ？

**Comment by tmclane** [comment]
The image is pulled from docker hub. 
https://hub.docker.com/r/wailsapp/xgo

**Comment by leaanthony** [comment]
The compiled binary is built in the build directory in the project root

**Comment by zhuqiyun** [comment]
> The compiled binary is built in the build directory in the project root

1、when compile on ubuntu  ，i really got the bin img in the project root /build。
2、another hand，when on windows10  ，the compile message said success，but i have not got bin in build directory。

**Comment by leaanthony** [comment]
<img width="487" alt="wails build" src="https://user-images.githubusercontent.com/1943904/82129481-1d088e80-97bb-11ea-88cd-9e0350c240b2.png">

**Comment by tmclane** [comment]
@zhuqiyun I would recommend running the builds in verbose mode if you still can't find the binaries after @leaanthony 's example above.

```
wails build -verbose 
```

**Comment by zhuqiyun** [comment]
> @zhuqiyun I would recommend running the builds in verbose mode if you still can't find the binaries after @leaanthony 's example above.
> 
> ```
> wails build -verbose 
> ```

ok,i will try

**Comment by leaanthony** [comment]
Any feedback?
