### ISSUE TITLE
Support Distribution 'Deepin'

### ISSUE THREAD

**Issue by tea4go** [wailsapp/wails#413]
**Description**
Distribution 'Deepin' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | Deepin |
| Distribution Name   | Deepin |
| Distribution Version   | 20 Beta |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
Isn't this based on Ubuntu?

**Comment by leaanthony** [comment]
Deepin support has been available for a while. Can you please try the latest pre-release to see if that works for you (v1.6.0-pre2).

**Comment by leaanthony** [comment]
It looks like Deepin have changed their ID to be "Deepin" from "deepin". I've pushed a fix which fixes this. Tested with Deepin 20 beta.
`wails update -pre` to get the fix.
