### ISSUE TITLE
wails serve is too slow

### ISSUE THREAD

**Issue by pedzed** [wailsapp/wails#414]
This is more of a feeling/frustration thing than a real bug. It works fine, but it can always be quicker.

When running `wails serve`, the first message you get is

> Ensuring Dependencies are up to date...

Can that check be reduced to a week or so? It takes quite some time and it checks every single time you run `wails serve`.

Maybe there are also other things that slow it down and it would be great if that would be optimized.

**Comment by pedzed** [comment]
(I cannot manage labels, otherwise I would have removed 'bug')

**Comment by leaanthony** [comment]
Please open a ticket using `wails issue` and provide more details - this gives us nothing to help you with.

**Comment by pedzed** [comment]
Copying from my other issue, is this what you were looking for?

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.2 |
| Platform      | darwin (macOS) |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 4.2.1 |
| Npm           | 6.14.5 |
| Node          | v14.2.0 |

It's a fresh project and I haven't really done anything crazy.
