### ISSUE TITLE
Ivalid JSON data

### ISSUE THREAD

**Issue by andrewrynhard** [wailsapp/wails#419]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
I am trying to send a kubernetes struct to the frontend using events. I get an error from here: https://github.com/wailsapp/wails/blob/94c56115a582082ec9205f4c7e1b4f2e50e077e5/runtime/js/core/events.js#L111

**To Reproduce**

**Expected behaviour**
I'd like to see the error. Looks like `e` is caught but never sent in the error description. It would be very useful to know the error.

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

**Comment by leaanthony** [comment]
Great call! I think it would be better to just prepend the error message of the original error and send that back. Thoughts?

**Comment by leaanthony** [comment]
Something like:
```
e.message = 'Invalid JSON data sent to notify [Event name = ' + eventName +'] ' + e.message); 
```

**Comment by leaanthony** [comment]
What makes this interesting to me is that this error is from an internal call from backend to frontend so I'd be really interested in how you triggered it.

**Comment by leaanthony** [comment]
I've created branch https://github.com/wailsapp/wails/tree/419-better-json-error-reporting if you want to play with it

**Comment by andrewrynhard** [comment]
Hmm. So I built our app with this and and the error seems empty. I am also having a tough time reproducing dependably. Give me a bit more time to dig.
