### ISSUE TITLE
Support Distribution 'Pop!_OS'

### ISSUE THREAD

**Issue by BearHeathen** [wailsapp/wails#421]
**Description**
Distribution 'pop' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | pop |
| Distribution Name   | Pop!_OS |
| Distribution Version   | 20.04 |

Not sure why this isn't working, it should work just as well as the latest Ubuntu or Debian, being that it is a direct child of both?

**Comment by leaanthony** [comment]
Support has been added to the develop branch. I'll look at getting another pre-release out today.

**Comment by BearHeathen** [comment]
> Support has been added to the develop branch. I'll look at getting another pre-release out today.

Much obliged! The popularity of this distro seems to be growing by leaps and bounds, as is the reputation of Wails. Ergo, this should be ultimately useful to a sizable subsection of Linux users.

**Comment by leaanthony** [comment]
Latest pre-release includes this now. Please update with `wails update -pre`.

**Comment by BearHeathen** [comment]
My apologies for forgetting to close like a mannerless buffoon. I'm chugging away with Wails on Pop with nary an issue! Many thanks!

**Comment by leaanthony** [comment]
No worries man! Glad it's working for you!
