### ISSUE TITLE
Support Distribution 'NixOS'

### ISSUE THREAD

**Issue by lobre** [wailsapp/wails#422]
Hello, and thanks for this awesome toolkit. I am currently running NixOS and I can see it is not yet supported. I have just seen the documentation page on how to add a new distribution.

I'll try and submit a PR if I manage to get it working!

**Description**
Distribution 'nixos' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.13.8 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | nixos |
| Distribution Name   | NixOS |
| Distribution Version   | 20.03.1926.f45ccd9d20b |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
NixOS uses a custom package manager right?

**Comment by lobre** [comment]
Yes it does. The whole distribution is built using the same model as its package manager.

I started implementing the changes in Wails to support it but it will be a little bit more complex that I thought.

Due to its design, libraries are not allowed to be installed as regular binary packages. 

https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

For a build that requires external libraries, it is recommended to first run an hermetic "nix-shell" that will install and setup the libraries in a dedicated context. Hence, the libraries are not installed globally and they "disappear" when the shell is exited. 

This specific behavior does not really make it easy for integrating it out of the box as other distros. 

But I will still try to find a way so it still make sense and does not differ too much from the other implementations.
