### ISSUE TITLE
a little worry about core of win-platform

### ISSUE THREAD

**Issue by Purple-CSGO** [wailsapp/wails#423]
Hello, I'm hugly interested in this project and attracted by the `vue-wails-go` feature that allows me to do most of the frontend jobs using web-side languages, but I'm a little worried about how's the compatibility and performance on windows platform. Heard that it's using ie kernel and gonna turn to edge/chromium, but what about win7?
  If there's really such problems, will wails offer the ability to call the browsers that users have installed or put a mini broswer(~10MB) together with executable files.

**Comment by leaanthony** [comment]
Hi. Microsoft doesn't support Win 7 any more and neither will we moving forward. mshtml is a huge pain to support and by the time wails v2 is out, Edge Chromium will be the default renderer.
