### ISSUE TITLE
Windows 10 64 bits problem with 1.6.0-pre3

### ISSUE THREAD

**Issue by nilopaim** [wailsapp/wails#425]
I have a Windows 10 64 bits box. Everything I have done with Wails till now works.

Go version go1.13.5 windows/386.
Gcc and libraries downloaded and installed from http://tdm-gcc.tdragon.net/download, as advised.

After a wails update --pre I'm getting errors, during a wails init and a wails build:

Wails v1.6.0-pre3 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
> Ensuring Dependencies are up to date...
- Packing + Compiling project...# sgdevui
c:\go\pkg\tool\windows_386\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `C:\Users\nilo\AppData\Local\Temp\go-link-596674131\000000.o' is incompatible with i386 output
collect2.exe: error: ld returned 1 exit status

Nor Go neither gcc previously installed changed. 

Before wails update --pre these errors doesn't occur.

Any hints?

**Comment by leaanthony** [comment]
Looks like it's a 32 bit / 64 bit incompatibility. Did you recently update your local TDM installation and installed 64bit? What happens if you do `wails build -x windows/386`?

**Comment by nilopaim** [comment]
No updates on TDM installation. Previous version of wails worked without problems.

Result of wails build -x windows/386:

D:\sgdeveloper\sgdevui>wails build -x windows/386
Wails v1.6.0-pre3 - Building Application

Error: Unsupported platform 'windows/386' specified.
Please run `wails build -h` to see the supported platform/architecture options.


I'm using a 32bit Go installation because I need to have my software on 32 bits due to clients needs.

**Comment by leaanthony** [comment]
@tmclane - Any ideas? I don't think we've done anything around native builds in terms of bitness?

**Comment by tmclane** [comment]
The cross platform builder for 386 was not functioning when I tried it. 
That is why it is not available.

 If wails is built on a 32bit windows install then it should work I presume.

**Comment by tmclane** [comment]
The -x option means cross platform.
If you have a 32bit host I would build it natively there

**Comment by tmclane** [comment]
I see why you built it that way. My mistake

**Comment by leaanthony** [comment]
I think the issue here is that native builds appear to use the 64bit compiler, but I'm sure we didn't do anything with this?

**Comment by leaanthony** [comment]
@nilopaim Go seems to be compiling with the 64bit version of TDD. Why do you have 64bit TDD when you need 32bit?

**Comment by nilopaim** [comment]
I'm also working on softwares that are really 64 bits (and not related to wails). 

The stranger thing (using exactly the same Go and TDM installations): 1.0.3 works; 1.6.0 doesn't.

I can use 1.0.3. This is not a problem for me.

**Comment by leaanthony** [comment]
This is really curious. I'll see if I can replicate it at the weekend.

**Comment by nilopaim** [comment]
@leaanthony Thanks a lot!

**Comment by tmclane** [comment]
@leaanthony Could the `char*` -> `unsigned char*` change have caused this issue?

**Comment by leaanthony** [comment]
Surely not.

**Comment by leaanthony** [comment]
@nilopaim Out of interest, what is sgdevui? Sounds interesting :-)

**Comment by nilopaim** [comment]
@leaanthony  Systems Generator Developer UI

I'm developing a tool to automate application generation. Kind of an old software I made years ago to generate Cobol programs.

**Comment by leaanthony** [comment]
Sounds cool.

This issue you're having is really hard for us to debug. Do you know how to
use `git bisect` to determine which commit this starts happening?

**Comment by nilopaim** [comment]
@leaanthony Never used `git bisect` before. And have no idea where to start, but I can try.
