### ISSUE TITLE
Question: Do I have to use NodeJS / NPM?

### ISSUE THREAD

**Issue by prologic** [wailsapp/wails#428]
ssia

**Comment by leaanthony** [comment]
Technically no, it should work, but I haven't personally tested it. Update `project.json` with the commands you want to issue for install, build and bridge:
```
 "frontend": {
  "dir": "frontend",
  "install": "npm install",
  "build": "npm run build",
  "bridge": "src",
  "serve": "npm run serve"
 },
```
Let us know how you get on!

**Comment by prologic** [comment]
Thanks! I'll give this a try with one of my [Self-hosted Apps](https://gist.github.com/prologic/c165403fb6ac07c16dc9fd6eeb8efbd2)

**Comment by leaanthony** [comment]
Let us know if you need anything.

**Comment by tmclane** [comment]
@prologic any luck?

**Comment by prologic** [comment]
Sorry haven't had a chance yet (work/etc). I will try something tomorrow hopefully.

**Comment by leaanthony** [comment]
@prologic any luck?

**Comment by prologic** [comment]
Finally found something I _think_ I want to use with [Wails](https://github.com/wailsapp/wails)! I will attempt to build a Desktop app for [twtxt](https://github.com/prologic/twtxt) (https://twtxt.net). If I run into any issues I'll be sure to help you fix them or submit PRs to fix them myself. Sorry for the delayed response; but you know; "free time" is rather limiting when you also have to do your day job!
