### ISSUE TITLE
Build error - Wails v1.6.0-pre5 

### ISSUE THREAD

**Issue by masterdubs** [wailsapp/wails#429]
When building ( MacOS) I got the following errors with a ton of c compiling error. Any way to debug that?

    ^
In file included from ../../../../../pkg/mod/github.com/wailsapp/wails@v1.6.0-pre5/lib/renderer/webview/webview.go:26:
In file included from ./webview.h:80:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:255:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPressureConfiguration.h:39:1: error: '#pragma clang attribute pop' with no matching '#pragma clang attribute push'
API_UNAVAILABLE_END
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/os/availability.h:105:33: note: expanded from macro 'API_UNAVAILABLE_END'
    #define API_UNAVAILABLE_END _Pragma("clang attribute pop")
                                ^
<scratch space>:47:8: note: expanded from here
 clang attribute pop
       ^
666 errors generated.

Ensuring Dependencies are up to date...
Error: exit status 2

**Comment by masterdubs** [comment]
looks like a go.mod trouble

**Comment by leaanthony** [comment]
Native build or via docker?

**Comment by masterdubs** [comment]
Native build

**Comment by masterdubs** [comment]
Reset the go.mod to previous version fixed it.

**Comment by leaanthony** [comment]
Thanks for the info. Reopening as this is definately a bug. Will take a look in the next couple of days

**Comment by masterdubs** [comment]
if you just change back in go.mod to 	github.com/wailsapp/wails v1.5.0 it works, maybe doesn't find the latest version ? ( pre5 )

**Comment by leaanthony** [comment]
That's weird. Do you have any idea why this might be happening? Are you able to find via `git bisect`?
