### ISSUE TITLE
Bug in Safari

### ISSUE THREAD

**Issue by masterdubs** [wailsapp/wails#431]
there is a bug in safari : Unhandled Promise Rejection: SecurityError: IDBFactory.open() called in an invalid security context  . We can avoid them if it's not built by disabling local files restrictions. Is there a solution for that so we can do the same inside the app ?

**Comment by leaanthony** [comment]
Do you have more details on this error? It's the first time this has been brought up.

**Comment by masterdubs** [comment]
I'm using OrbitDB in the frontend part, works ok in dev with chrome.
