### ISSUE TITLE
[Question] How to pipe log to file?

### ISSUE THREAD

**Issue by chess-equality** [wailsapp/wails#434]
Hello there,

I am using logrus and lumberjack in my other projects to create a rotating log file; is this also possible  with `*wails.CustomLogger`? I have checked and `GlobalLogger` is a logrus object, however I don't know how to do it.

Thanks in advance.

**Comment by leaanthony** [comment]
Hey there. We don't have direct support for it but if you want to add a logfile option and create a PR, I'll merge it. The closest you'll get right now is to redirect stdout to a file.

**Comment by chess-equality** [comment]
> We don't have direct support for it but if you want to add a logfile option and create a PR, I'll merge it.

Ok, but might not possible for me right now.

> The closest you'll get right now is to redirect stdout to a file.

By `nohup` you mean, for example? Or can it be redirected via Go code?

**Comment by leaanthony** [comment]
Explain a bit more about your logging requirements. It's really only there for tracing/debugging. Do you have a need for production logging?

**Comment by chess-equality** [comment]
Yes, production logging.

**Comment by chess-equality** [comment]
Hi,

At the moment I have used a separate logging instance than `*wails.CustomLogger` using logrus and lumberjack that pipes to a file. Closing this.
