### ISSUE TITLE
Allow dialog file filtering by extension name

### ISSUE THREAD

**Issue by fdidron** [wailsapp/wails#436]
**Description**

Currently, when opening a file selection dialog, there is no way to specify a file extension to filter the files that can be selected.

I have an [app running on Windows, OS X and Linux](https://ergodox-ez.com/pages/wally) that uses a fork of webview to do that.

That's the only thing that's preventing me to use Wails, so if that seems like a good idea, I'm happy to work on a PR.

**Comment by leaanthony** [comment]
Hi @fdidron. That sounds awesome! Please go ahead. We work off the develop branch and then merge to ~~master~~ main for stable releases. Thanks!

**Comment by leaanthony** [comment]
NOTE TO SELF: Update the API docs.

**Comment by fdidron** [comment]
I see that the docs were updated, closing this issue now
