### ISSUE TITLE
how to  pass  hex byte  array to golang func   from   vue frontend？ 

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#440]
1、golang code

func SerialSendArray(data []byte, len int) (int, error) {
	mu.Lock()
	var n int
	var err error
	if serialState == true {
		n, err = Serialport.Write(data[:len])
	}
	mu.Unlock()
	return n, err
}

2、  bind to  frontend
app.Bind(serialportservice.SerialSendArray)

3、how to invoke  by  vue  ，then  send  byte array  data  for the first para？

**Comment by leaanthony** [comment]
Depends. How is the hex string getting into the frontend? What format is it?

I'd probably just use a hexstring and decode it to a byteslice in Go before writing:
1. https://stackoverflow.com/a/34310051
2. hex.DecodeString

Let us know how you go.

**Comment by zhuqiyun** [comment]
> Depends. How is the hex string getting into the frontend? What format is it?
> 
> I'd probably just use a hexstring and decode it to a byteslice in Go before writing:
> 
> 1. https://stackoverflow.com/a/34310051
> 2. hex.DecodeString
> 
> Let us know how you go.

vue  js   format  like this： data = [0x98,0x89,0xab,0x34],not hex string,exactly byte array.

**Comment by leaanthony** [comment]
Convert your byte array to base64 or hexstring then decode it in Go.

**Comment by leaanthony** [comment]
Closed due to inactivity
