### ISSUE TITLE
Inject compile time variable?

### ISSUE THREAD

**Issue by ljjimenez** [wailsapp/wails#443]
Is there any way I can inject compile time variable to the ldflags?

I mean, I want to set ENVIRONMENT variables for CI/CD like DEV_MODE or PROD_MODE.

**Comment by leaanthony** [comment]
The `-p" flag does this. Help us understand your use case a bit more.

**Comment by ljjimenez** [comment]
I would like to compile different versions:

 for development normally I use -ldflags="-X main.baseURL=http://127.0.0.1/", 
 for production -ldflags="-X main.baseURL=https://mysite.com/"

How can i inject those using wails build?

The -p option as the help says "Package application on successful build"

**Comment by leaanthony** [comment]
Oh I see. We don't have a pass-through option but it's relatively easy. I'll take a look :+1:

**Comment by leaanthony** [comment]
Just done a new pre-release with this fix. Update with `wails update -pre` to `v1.7.0-pre1`.
Using the vanilla template, I added the `baseURL` variable as per your example:
```
package main

import (
	"github.com/leaanthony/mewn"
	"github.com/wailsapp/wails"
)

func basic() string {
	return "Hello World!"
}

var baseURL = "not set"

func main() {

	js := mewn.String("./frontend/build/main.js")
	css := mewn.String("./frontend/build/main.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 768,
		Title:  "ldflags",
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})
	println(baseURL)
	app.Bind(basic)
	app.Run()
}
```
Building and running by default:
```
ea@corvo /tmp/ldflags $ wails build
Wails v1.6.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Awesome! Project 'ldflags' built!
lea@corvo /tmp/ldflags $ ./build/ldflags 
not set
```
Building with new `ldflags` flag:
```
lea@corvo /tmp/ldflags $ wails build -ldflags "-X main.baseURL=http://127.0.0.1/"
Wails v1.6.0 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Awesome! Project 'ldflags' built!
lea@corvo /tmp/ldflags $ ./build/ldflags 
http://127.0.0.1/
```

**Comment by ljjimenez** [comment]
Awesome, this is perfect and working as expected, thanks very much, the
best project ever. 👍
