### ISSUE TITLE
“wails” not defined

### ISSUE THREAD

**Issue by mcoo** [wailsapp/wails#446]
**Description**

I can't use it when I build. But when I use "serve" to debug. It works!

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
**Screenshots**
![QQ截图20200625175742](https://user-images.githubusercontent.com/26184088/85698831-988c2280-b70d-11ea-8aee-4dbad6e95b9c.png)
![QQ截图20200625175735](https://user-images.githubusercontent.com/26184088/85698853-9de96d00-b70d-11ea-9437-ca53dc1c5af8.png)
**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.6.0 |
| Go Version    | go1.14.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 6.14.2 |
| Node          | v14.4.0
 |

**Additional context**

**Comment by mcoo** [comment]
win10 x64 
Chrome  83.0.4103.116
Microsoft Edge 83.0.478.54

**Comment by leaanthony** [comment]
Please use the `wails issue` command

**Comment by mcoo** [comment]
`Unable to read in issue template. Are you online?` Emmm

**Comment by tmclane** [comment]
Do you need to add the `go/bin` directory where `wails` is usually installed to your PATH configuration for Windows?
I can't read your dialogs but that would be my guess.

**Comment by mcoo** [comment]
```
D:\project\mcdownload\mcdownloader>wails issue
Wails v1.6.0 - Generate Issue

Thanks for taking the time to submit an issue!

To help you in this process, we will ask for some information, add Go/Wails details automatically, then prepare the issue for your editing and submission.

Issue Title: "wails" not defined
Issue Description: I can't use it when I build. But when I use "serve" to debug. It works!

Processing template and preparing for upload.
Unable to read in issue template. Are you online?

D:\project\mcdownload\mcdownloader>
```

**Comment by leaanthony** [comment]
I don't get this issue ^^^^

**Comment by mcoo** [comment]
ok , I have finished it by VPN.

**Comment by mcoo** [comment]
My project is open source `https://github.com/super-coffee/mcdownloader/tree/ui` and I use npm dependencies:
```
  "dependencies": {
    "@wailsapp/runtime": "^1.0.10",
    "core-js": "^3.6.4",
    "element-ui": "^2.4.5",
    "node-sass": "^4.14.1",
    "regenerator-runtime": "^0.13.3",
    "sass-loader": "^8.0.2",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.2.3",
    "@vue/cli-plugin-eslint": "^4.2.3",
    "@vue/cli-plugin-router": "^4.4.6",
    "@vue/cli-service": "^4.2.3",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-vue": "^6.2.1",
    "eventsource-polyfill": "^0.9.6",
    "vue-cli-plugin-element": "^1.0.1",
    "vue-template-compiler": "^2.6.11",
    "webpack-hot-middleware": "^2.25.0"
  },
```
It may cause these problems.

**Comment by leaanthony** [comment]
@mcoo - glad you fixed it. Can this be closed now?

**Comment by mcoo** [comment]
Ok

**Comment by mcoo** [comment]
#150

**Comment by mcoo** [comment]
```
const router = new VueRouter({
  mode: 'history',
  routes
})

export default router

```
set history mode!

**Comment by leaanthony** [comment]
Thanks for this! We'll add it to the docs!

**Comment by leaanthony** [comment]
Added https://wails.app/guides/vuerouter/
Thanks @mcoo !
