### ISSUE TITLE
GLIBC_2.28 not found when running built executable

### ISSUE THREAD

**Issue by chess-equality** [wailsapp/wails#448]
**Description**

Running the built executable on an Ubuntu 18.04 LTS, got the error `/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by xxxxxxx)`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Just run the built executable on an Ubuntu 18.04 LTS desktop.

**Expected behaviour**
The app should run / launch.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.6.0 |
| Go Version    | go1.14.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 7 |
| Npm           | 6.14.5 |
| Node          | v12.18.1 |

**Additional context**
Before when using Wails v1.5.0, this error was not encountered. I am building the executable on a Zorin OS 15.2 machine.

**Comment by leaanthony** [comment]
I'm guessing Ubuntu 18.04 is too old for one of the dependencies. Maybe node? Does this help:
```
sudo apt-get update
sudo apt-get install libc6
```
