### ISSUE TITLE
./myApp serve ?

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#449]
Hello, is it possible to "serve" my application so that it can be used remotely on the network?
In a web browser on another computer

**Comment by leaanthony** [comment]
Hi. We don't officially have a server build for v1 (the focus is desktop), but @tmclane has some experience of using the binary generated by "wails serve" for this purpose.

**Comment by tmclane** [comment]
I was working on a server capable build but as of yet I have not gotten anything to a point it is worth sharing actually.
I might put in some more time on it at some point soon.
