### ISSUE TITLE
Road to V1

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#45]
The road to v1 requires:

  - Windows testing (not necessarily to fix at this point - support may have to be delayed)
    - Remove console window for binaries
    - Potentially add icon to binary
  - Tutorial covering the main concepts
    - IPC
    - Events
    - Dialogs

**Comment by leaanthony** [comment]
The Windows work is complete.

**Comment by bh90210** [comment]
should we start utilising this ticket as a dumping space for todos, reports/updates as we'r reaching v1?

**Comment by leaanthony** [comment]
I've set up a project for V1. Closing.
