### ISSUE TITLE
Feature request: Empty skeleton

### ISSUE THREAD

**Issue by stevesobol** [wailsapp/wails#450]
Hi. New Wails user. Very impressed.

I also recently started using Rekit Studio, which I love. It's an opinionated React-powered webapp framework with a built-in IDE.

I can also see some times when I may just want to create a simple HTML/CSS/JSS app without a framework.

I propose an new `wails init` template: essentially, an empty project, with just a Go module and nothing in the `frontend` directory. This template could be used if you want to use a framework other than one that is currently on the list, or if you don't want to use a framework at all.

Is this doable?

**Comment by leaanthony** [comment]
Hi @stevesobol - Thanks for the kind words. There's a vanilla template already there: 
![image](https://user-images.githubusercontent.com/1943904/86286202-67d64c80-bc29-11ea-85d6-21b37de3f229.png)
You can delete what's in the frontend and customise as you please.

Let us know how you get on!

**Comment by stevesobol** [comment]
Ugh. When creating my first project, I read option 3 as _**VanillaJS,**_ which, of course, isn't what's there. VanillaJS is [this.](http://vanilla-js.com/)

Oops. :)

Thank you.

**Comment by leaanthony** [comment]
You know what? I should change it to "Plain HTML/JS/CSS"

**Comment by leaanthony** [comment]
Also, you do know that that's a joke site advocating using plain js? 😉

**Comment by stevesobol** [comment]
HA! No, I thought it was an actual framework. I haven't had time to look at the site. But try checking any of the checkboxes on the homepage; no matter what you check, the download size remains

```
Final size: 0 bytes uncompressed, 25 bytes gzipped.
```

**Comment by stevesobol** [comment]
So... [Sharing](https://www.facebook.com/stevesobol/posts/3023673484337165) this experience so other people don't embarrass themselves like I did.   O.o

**Comment by leaanthony** [comment]
So now you've learnt 2 things! 😃 
Let us know if you need any help. Good luck!

**Comment by stevesobol** [comment]
I'm getting a Javascript error when I build a sample app and try to run it (using the vanilla template). Things run error-free using `wails serve` / `npm run serve` - I'm going to have to do a debug build and see what's happening.

**Comment by leaanthony** [comment]
Urgh, that's something I didn't actually try :facepalm: - I'll have a look today.

**Comment by leaanthony** [comment]
I just re-read your message. I absolutely did test that.

**Comment by stevesobol** [comment]
Hm. Well, I was running 1.6.0 and tried running `wails update` and discovered that I was using a rather old version. Updated to 1.7.1 and I'm going to try creating a new vanilla project.

**Comment by stevesobol** [comment]
Ahhah. Only started with Wails within the last week, not sure how I ended up with 1.6.0. But updating to 1.7.1 worked. I tried creating a new project and using `wails build -d` and it's running fine. Next step is to try a Rekit project! 😁

**Comment by leaanthony** [comment]
Nice one!

**Comment by stevesobol** [comment]
So, with [Rekit-React](http://rekit.js.org/), my app's entry point is `build\static\main.48cc335b.chunk.js` (the four-digit hex number in the middle changes, IIRC). `wails build` is expecting to find it in `build\main.js`. It would appear that I need a custom webpack config. Rekit-React normally doesn't create a `webpack.json` when you start a new project. This will be interesting...

**Comment by stevesobol** [comment]
I'm going to play around with my project. I should put my results up on a blog somewhere. Regardless, the problem I had is fixed :)

**Comment by leaanthony** [comment]
Configure the project as you need. Wails doesn't impose anything on you. The install and build commands are all it uses and they are configurable in `project.json`.
