### ISSUE TITLE
Fail to init after 1.0.7

### ISSUE THREAD

**Issue by masterdubs** [wailsapp/wails#451]
I can't init or serve a new project on MacOS, go 1.14 wails 1.0.7
this error is repeating again and again: 

`In file included from ./webview.h:80:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSGestureRecognizer.h:13:1: error: expected '('
API_UNAVAILABLE_BEGIN(ios)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/os/availability.h:104:40: note: expanded from macro 'API_UNAVAILABLE_BEGIN'
    #define API_UNAVAILABLE_BEGIN(...) _Pragma("clang attribute push") __API_UNAVAILABLE_BEGIN_GET_MACRO(__VA_ARGS__,__API_UNAVAILABLE_BEGIN7,__API_UNAVAILABLE_BEGIN6, __API_UNAVAILABLE_BEGIN5, __API_UNAVAILABLE_BEGIN4, __API_UNAVAILABLE_BEGIN3, __API_UNAVAILABLE_BEGIN2, __API_UNAVAILABLE_BEGIN1, 0)(__VA_ARGS__)
                                       ^
<scratch space>:80:22: note: expanded from here
 clang attribute push
                     ^
In file included from ../../../../../pkg/mod/github.com/wailsapp/wails@v1.7.0-pre1/lib/renderer/webview/webview.go:26:
In file included from ./webview.h:80:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSGestureRecognizer.h:13:1: error: expected 'push' or 'pop' after '#pragma clang attribute'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/os/availability.h:104:273: note: expanded from macro 'API_UNAVAILABLE_BEGIN'
    #define API_UNAVAILABLE_BEGIN(...) _Pragma("clang attribute push") __API_UNAVAILABLE_BEGIN_GET_MACRO(__VA_ARGS__,__API_UNAVAILABLE_BEGIN7,__API_UNAVAILABLE_BEGIN6, __API_UNAVAILABLE_BEGIN5, __API_UNAVAILABLE_BEGIN4, __API_UNAVAILABLE_BEGIN3, __API_UNAVAILABLE_BEGIN2, __API_UNAVAILABLE_BEGIN1, 0)(__VA_ARGS__)
                                                                                                                                                                                                  `

**Comment by leaanthony** [comment]
@masterdubs - you're having fun on 10.15 there. Did you check the [webview repo](https://github.com/webview/webview) to see if others have this issue?

**Comment by leaanthony** [comment]
Closed due to inactivity
