### ISSUE TITLE
Windows Packaging Broken

### ISSUE THREAD

**Issue by Pierre-Felber** [wailsapp/wails#452]
With the changed windows icon generation, observed by me in 1.6.0 (I've updated from 1.0.2),  packaging in windows is broken:

Icon created is now **$APPNAME.exe.ico**
Icon referenced in RC template is still **$APPNAME.ico** [see](https://github.com/wailsapp/wails/blob/aa93e5d8d2e0ae44fae778433df2444c3cdb33a3/cmd/packages/windows/wails.rc#L1)
notice the new **exe** part

This leads to a failing winres call in the resource step.

The project cleanup step after build is also still using the old $APPNAME.ico, therefore after successful build 
_(only possible with modified RC template or manually created symlink $APPNAME.ico to $APPNAME.exe.ico)_ 
the $APPNAME.exe.ico is left in the project instead of being deleted. (The symlink $APPNAME.ico gets deleted, as per old behavoir )

I am surprised this bug made it into a release. Seems there is no test for `wails build -p` on windows.

**Comment by leaanthony** [comment]
Hi. Thanks for raising this. Testing is pretty hard and a lot of it is done manually. We rely on feedback of the -pre branches for releases and this is the first time this has been raised. @dedo1911 would be the first person to be able to respond to this. I'll take a look today also.

**Comment by dedo1911** [comment]
The icon shouldn't be **$APPNAME.exe.ico** but just **$APPNAME.ico** instead.
I'll take a better look at it tomorrow.

**Comment by dedo1911** [comment]
@Pierre-Felber can you please check out your `project.json` file

I think you have:
` "binaryname": "appname.exe",`

That should be:
` "binaryname": "appname",`

**Comment by leaanthony** [comment]
There's a potential fix on develop. About to test.

**Comment by Pierre-Felber** [comment]
> @Pierre-Felber can you please check out your `project.json` file
> 
> I think you have:
> ` "binaryname": "appname.exe",`
> 
> That should be:
> ` "binaryname": "appname",`
> 
> I think we might better add some checks about it, but that might be the issue at the moment for you

Yes, you are correct: project.json has `"binaryname": "appname.exe"` 
Changing it to  `"binaryname": "appname"` resolves the issue.

Then it's a migration issue, isn't it? I did just did `wails update`, not `wails migrate`

**Comment by leaanthony** [comment]
It's on us. There was a change a while back to normalise the project name to sans .exe for new projects. The only thing that has been affected is the icon generation that uses the project name regardless of exe. I've made that fix for the develop branch and I'm just testing.

But you're right, we should absolutely add this to wails migrate, though that was really for projects <v1.

Will keep.you posted!

**Comment by leaanthony** [comment]
@Pierre-Felber - I've tested the fix on Windows 10 and made it part of `v1.7.0-pre1`. Please update using `wails update -pre` and let us know if it works. If it does, I'll release it as v1.7.1 so it's part of the stable channel.

BTW: This testing also uncovered an issue with the vanilla template so thanks for raising it! 2 bugs fixed!

**Comment by Pierre-Felber** [comment]
> @Pierre-Felber - I've tested the fix on Windows 10 and made it part of `v1.7.0-pre1`. Please update using `wails update -pre` and let us know if it works. If it does, I'll release it as v1.7.1 so it's part of the stable channel.

TX, can confirm it works with `"binaryname": "appname.exe"` in **v1.7.0-pre2**

![image](https://user-images.githubusercontent.com/19165025/86438786-83178980-bd07-11ea-8a06-5b86025a8d3c.png)

Very fast fix, thanks!!!

**Comment by leaanthony** [comment]
@Pierre-Felber - this is now in v1.7.1. Feel free to get back on the stable release channel using `wails update`.
