### ISSUE TITLE
Linux - Uncaught TypeError: window.wails is undefined

### ISSUE THREAD

**Issue by Mike97M** [wailsapp/wails#458]
**Description**

I get the error `Uncaught TypeError: window.wails is undefined` when I try to view the frontend app from firefox by using npm run serve. I've tried from another browser and I got a similar error.

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init`
2. select Vuetify2/Vuetify1.5
3. Try to server only the frontend using `npm run serve`

**Expected behaviour**
To see the same frontend I see when I build and open the app. But, I see a blank page.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.1.0 |
| Npm           | 6.14.5 |
| Node          | v14.3.0 |

**Comment by leaanthony** [comment]
I can check tonight, but perhaps @tmclane might be available before then. Unusual as this is core functionality used every day.

**Comment by Mike97M** [comment]
Hi @leaanthony,

Did you had the time to reportduce the issue yet?

**Comment by leaanthony** [comment]
Glad it was sorted!
