### ISSUE TITLE
Cross compilation using xgo does not copy local (unpublished) packages

### ISSUE THREAD

**Issue by DanielKrolopp** [wailsapp/wails#460]
**Description**

I've been trying to cross compile for windows from my Linux machine and ran into an issue. I have a go module in a different directory than the one in which my wails project is located---I import this module in a go.mod file in my wails project directory using the replace keyword. When I try to compile, I get the following message: 
```
Compiling for windows-4.0/amd64...
go: github.com/username/projectname/client@v0.0.0-00010101000000-000000000000: parsing /home/dk/go/src/github.com/username/projectname/client/go.mod: open /home/dk/go/src/github.com/username/projectname/client/go.mod: no such file or directory
```

I suspect that the output is from the Docker container, and that the necessary files are not being copied in.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import a local go module outside the immediate project directory using go modules' `replace` keyword from within the go.mod of your wails project directory.
2. Run `wails build -x windows/amd64 --verbose`. The error described above should appear.
3. Wails will claim that the project built successfully, but the build folder will be empty.

**Expected behaviour**
The cross-compilation builds a functioning windows executable.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 7.5.0 |
| Npm           | 6.14.4 |
| Node          | v12.17.0 |

**Comment by leaanthony** [comment]
The project directory is mounted for the build so if it's not in there then yes, it won't get picked up. What do you think would be a good solution to this?

**Comment by tmclane** [comment]
This is a tricky one.  If you make the go module accessible over the internet go itself will copy it into the build container.
If it is private it is a bit harder.

One thought i had would be to:
- optionally mount the GOPATH directory into the build container at `/go`.

**Comment by leaanthony** [comment]
That's not a bad idea @tmclane! We could then add it to $GOPATH. Trying to think how this works with modules.

**Comment by tmclane** [comment]
Well as long as you place the module in the GOPATH it will work fine.

Perhaps we could allow additional mount mappings to help place them appropriately inside the container.

**Comment by leaanthony** [comment]
I guess the problem is that `go.mod` can reference any arbitrary location on disk. What about doing `go mod vendor` first to pull it into the project directory? I know wails itself has an issue with that so potentially remove that directory before compiling

**Comment by tmclane** [comment]
That might work. I haven't used that feature before.

**Comment by leaanthony** [comment]
It should work fine, just need to vendor, remove wails then start docker. Wails specifically doesn't work in vendor because of the funky stuff we do with module paths.

**Comment by DanielKrolopp** [comment]
It looks like the two of you have some pretty good ideas on how to accomplish this already, but I'll add my two cent's worth. As @leaanthony mentioned, since vendoring doesn't work, for now I'm just writing a script to copy the needed modules to the build directory before compiling and using a different path with the replace directive.

**Comment by leaanthony** [comment]
We can get around the fact that wails won't vendor correctly, but your issue *is* something we need to solve so I think we'll try that approach and see where we get.

**Comment by DanielKrolopp** [comment]
Yeah, I agree. Thanks for your prompt response!

**Comment by leaanthony** [comment]
Another user reported this on slack: using `replace` in go.mod will also fail cross-compile:
```
// go.mod
require (
  ...
  ...
  github.com/Me/myproject v0.1.0
)
replace github.com/Me/myproject => ../myproject
```

**Comment by tmclane** [comment]
Yes of course that replace will fail.  That path isn't mapped into the container properly.

**Comment by tmclane** [comment]
I'll eventually have time to work on this again.

**Comment by leaanthony** [comment]
I'm not really sure how to fix the replace modules. If mod vendor pulls that in then it'll work. Otherwise....?

**Comment by leaanthony** [comment]
I think I have a solution for this. Please bear with us :-)

**Comment by tmclane** [comment]
@DanielKrolopp Would you mind checking out the feature branch `feature/goroot` I just pushed up that allows you to specify the `-goroot` flag and provide the location on your drive of the `GOROOT` environment value?

Passing that in causes the location on your host to be mounted at `/go` inside the cross-compiler container.  This should enable a `replace github.com/wailsapp/wails => github.com/DanielKrolopp/wails` style of substitution.

**Comment by DanielKrolopp** [comment]
Yeah, I tried it and it works with my local replace keywords. Thanks!

**Comment by tmclane** [comment]
Yes I guess I should rename it.

**Comment by leaanthony** [comment]
Was this solved? Do we need to merge in the fixes on the branch?

**Comment by tmclane** [comment]
> Was this solved? Do we need to merge in the fixes on the branch?

It was merged to `develop`.  I don't know if we have cut a release yet containing it.
