### ISSUE TITLE
Wails build package option not working as intended

### ISSUE THREAD

**Issue by Splode** [wailsapp/wails#463]
**Description**

On Windows 10, running `wails build` with the `-p` flag does not package application resources. Furthermore, the resource files are deleted during build. Perhaps I don't understand how the `package` option is intended to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialize Wails project with `wails init`
2. Add resource files, such as `wails.exe.manifest` and `wails.rc` to project root
3. Run `wails build -p`
4. See resource files removed. Inspect binary.

**Expected behaviour**
Expect the application properties to be written according to the resource files. Also expect the resource files to remain in place after the build command completes.

**Screenshots**

Screenshot of binary properties from a Wails project I'm working on.

![image](https://user-images.githubusercontent.com/13758438/88237101-bb8df180-cc3b-11ea-9b22-9bc9c606194a.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.3.0 |
| Npm           | 6.14.4 |
| Node          | v12.18.0
 |

**Additional context**

```sh
λ wails build -p -verbose
Wails v1.7.1 - Packaging Application

Ensuring frontend dependencies are up to date (This may take a while)
Skipped frontend dependencies (-f to force rebuild)
Building frontend...

> optimus@ build C:\Users\Christopher\code\optimus\frontend
> vue-cli-service build


/  Building for production...

 WARNING  Compiled with 3 warnings                                                                                                     4:44:57 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.css (654 KiB)
  app.js (285 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. Entrypoints:
  app (939 KiB)
      app.css
      app.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File            Size                          Gzipped

  dist\app.js     284.87 KiB                    90.86 KiB
  dist\app.css    653.90 KiB                    425.43 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

Packing + Compiling project
Command: [go build -o build\optimus.exe -ldflags -w -s -H windowsgui -X github.com/wailsapp/wails.BuildMode=prod]
> Packaging application...
Awesome! Project 'Optimus' built!
```

Can anyone point me a project that successfully uses the package feature?

**Comment by leaanthony** [comment]
You are the second person to raise this so I'm wondering if there's been some sort of regression in the latest release. I will look over it at the weekend :+1:

**Comment by leaanthony** [comment]
Regarding the resource files, we create default ones at build time then remove them at the end. The logic there was really to keep the project directory tidy and that they were unlikely to get updated by the developer. If you think it's a good idea to keep them around we can add a flag for that or potentially make it the default option.

**Comment by Splode** [comment]
> Regarding the resource files, we create default ones at build time then remove them at the end. The logic there was really to keep the project directory tidy and that they were unlikely to get updated by the developer. If you think it's a good idea to keep them around we can add a flag for that or potentially make it the default option.

I think it would be helpful to keep existing resource files intact. Perhaps the build action could check for the existence of resource files and if they don't exist, create the defaults and remove them after build completion. If the resource files do exist, use those and skip removal.

**Comment by leaanthony** [comment]
I've now added this to v1.7.2-pre2. Please try it out using `wails update -pre`. 
All files are kept and not overwritten if exist, with one caveat: The .ico file is always generated from the png. The reason is that if we didn't we'd not be able to update the ico file when there were changes to the png (current behaviour).

Let me know how you get on. 

Oh, I should also mention that `-p` doesn't really do anything on windows as the .exe will already be bundled with icons. I guess you might get a slightly smaller binary.

**Comment by Splode** [comment]
@leaanthony v.1.7.2-pre2 leaves behind the resource files after building. Thanks for looking into it!
