### ISSUE TITLE
Add support for Ubuntu 20.4 (Mint 20)

### ISSUE THREAD

**Issue by kowsoleea** [wailsapp/wails#464]
**Description**

As of yet I cannot install libwebkit2gtk-4.0-dev on mint 20. Is there a workaround?

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Mint 20
2. run : apt install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
3. result:  libwebkit2gtk-4.0-dev : Depends: libsoup2.4-dev (>= 2.40) but it is not going to be installed E: Unable to correct problems, you have held broken packages.

**Expected behaviour**
 libwebkit2gtk-4.0-dev should install normally or maybe a different (newer) package is needed

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.6.0 |
| Go Version    | go1.14.4 |
| Platform      | linux (Mint 20) |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9 |
| Npm           | 6.14.6 |
| Node          | v12.18.3 |

**Comment by leaanthony** [comment]
Hi. This is more a Mint 20 issue. What happens if you try to install libsoup too?

**Comment by kowsoleea** [comment]
Installing libsoup2.4-dev yields:

The following packages have unmet dependencies:
 libsoup2.4-dev : Depends: libpsl-dev (>= 0.20) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Installing libpsl-dev yields:
The following packages have unmet dependencies:
 libpsl-dev : Depends: libpsl5 (= 0.21.0-1ubuntu1) but 0.21.0-1.1~18.04.sav0 is to be installed
E: Unable to correct problems, you have held broken packages.

And apt install libpsl5:
libpsl5 is already the newest version (0.21.0-1.1~18.04.sav0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

So we need a newer version of libpsl5.
Strange. It used to work fine on Mint 19.3

**Comment by leaanthony** [comment]
This is best asked on a Mint forum, but please let us know what the
resolution is if it might afect others. At this point it sounds like a
local issue. Good luck!

**Comment by kowsoleea** [comment]
I tried to install the libwebkit2gtk-4.0-dev package on a Ubuntu 20.4 virtual machine. That went trough without problems. It must be something in the mint repos.

**Comment by leaanthony** [comment]
Let us know if you find an answer!

**Comment by leaanthony** [comment]
@kowsoleea Any updates?
