### ISSUE TITLE
Cannot Get runtime.Window.Fullscreen() work on raspberry pi 

### ISSUE THREAD

**Issue by ahmadfarisfs** [wailsapp/wails#465]
Raspbian Latest on raspberry pi 3B+
OS: Version:May 2020
Release date:2020-05-27
Kernel version:4.19

Fullscreen mode is not working

**Comment by leaanthony** [comment]
I can't test this so am unable to help you on this right now as I don't have a pi setup. Perhaps someone else can.

**Comment by leaanthony** [comment]
I've found an old pi. I'll try setting it up this week.

**Comment by ahmadfarisfs** [comment]
Hello, update from me, fullscreen working now. I found that windowing setting on my Pi messed up.
