### ISSUE TITLE
Runtime emit can't handle long messages

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#469]
**Description**

If the emitted message is too long it causes a javascript error. I'm converting the messages to bas64 so I don't have to hassle with escaping the strings for the js side.

**To Reproduce**
Steps to reproduce the behaviour:
 1. Emitt a long string from go to js. 

**Expected behaviour**
Get the emitted message from go.

**Screenshots**
![Screenshot from 2020-08-01 23-52-37](https://user-images.githubusercontent.com/8627125/89111259-e6562200-d453-11ea-8723-08fa1543a7a5.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.5 |
| Platform      | linux |
| Linux      | Ubuntu 20.04|
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.3.0 |
| Npm           | 6.14.7 |
| Node          | v14.7.0 |

**Additional context**
What is in the string does not matter, if you send spaces the error is the same.

`t.runtime.Events.Emit("stats", uEnc)`

This is one of my messages that ends up jumbled:
docker stats --no-stream --format "{{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\\t{{.MemPerc}}"

`W3sibmFtZSI6Im5naW54IiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMCUiLCJjcHVfcGVyYyI6IjAuMDAiLCJtZW1vcnlfdXNhZ2UiOiI1Ljk1N01pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4wNCUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMDQifSx7Im5hbWUiOiJwaHAtZnBtIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMCUiLCJjcHVfcGVyYyI6IjAuMDAiLCJtZW1vcnlfdXNhZ2UiOiIyMS4wOE1pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4xMyUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMTMifSx7Im5hbWUiOiJkb2NrZXItaW4tZG9ja2VyIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4yOSUiLCJjcHVfcGVyYyI6IjAuMjkiLCJtZW1vcnlfdXNhZ2UiOiIyMy41OU1pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4xNSUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMTUifSx7Im5hbWUiOiJteXNxbCIsImNwdV9wZXJjX3N0cmluZyI6IjAuMzQlIiwiY3B1X3BlcmMiOiIwLjM0IiwibWVtb3J5X3VzYWdlIjoiMzE0LjFNaUIgLyAxNS41OEdpQiIsIm1lbW9yeV9wZXJjZW50X3N0cmluZyI6IjEuOTclIiwibWVtb3J5X3BlcmNlbnQiOiIxLjk3In0seyJuYW1lIjoid29ya3NwYWNlIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMCUiLCJjcHVfcGVyYyI6IjAuMDAiLCJtZW1vcnlfdXNhZ2UiOiIxMS44N01pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4wNyUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMDcifV0=`

This is the code from chrome that causing the error: (VM56:1 in the printscreen)

`window.wails._.Notify('stats','["W3sibmFtZSI6Im5naW54IiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMCUiLCJjcHVfcGVyYyI6IjAuMDAiLCJtZW1vcnlfdXNhZ2UiOiI1Ljk1N01pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4wNCUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMDQifSx7Im5hbWUiOiJwaHAtZnBtIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMCUiLCJjcHVfcGVyYyI6IjAuMDAiLCJtZW1vcnlfdXNhZ2UiOiIyMS4wOE1pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4xMyUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMTMifSx7Im5hbWUiOiJkb2NrZXItaW4tZG9ja2VyIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC42MyUiLCJjcHVfcGVyYyI6IjAuNjMiLCJtZW1vcnlfdXNhZ2UiOiIyMy41NU1pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3BlcmNlbnRfc3RyaW5nIjoiMC4xNSUiLCJtZW1vcnlfcGVyY2VudCI6IjAuMTUifSx7Im5hbWUiOiJteXNxbCIsImNwdV9wZXJjX3N0cmluZyI6IjAuNDYlIiwiY3B1X3BlcmMiOiIwLjQ2IiwibWVtb3J5X3VzYWdlIjoiMzE0LjFNaUIgLyAxNS41OEdpQiIsIm1lbW9yeV9wZXJjZW50X3N0cmluZyI6IjEuOTclIiwibWVtb3J5X3BlcmNlbnQiOiIxLjk3In0seyJuYW1lIjoid29ya3NwYWNlIiwiY3B1X3BlcmNfc3RyaW5nIjoiMC4wMSUiLCJjcHVfcGVyYyI6IjAuMDEiLCJtZW1vcnlfdXNhZ2UiOiIxMS44N01pQiAvIDE1LjU4R2lCIiwibWVtb3J5X3Blcmnwindow.wails._.Notify('stats','["W3sibmFtZSI6Im5naW54IiwiY3B1X3Bl`

**Comment by leaanthony** [comment]
Thanks for opening this. Do you suspect this is a webpack issue?

**Comment by Lyimmi** [comment]
At the moment I have no idea, but I'll take a closer look at it.

**Comment by Lyimmi** [comment]
So as it turns out there is a length limit for go's fmt.sprintf() for strings and when the limit is reached it truncates, that is why the **window.wails._.Notify()** string ends up short.

wails/lib/renderer/bridge/bridge.go:160

If we change this 
`message := fmt.Sprintf("window.wails._.Notify('%s','%s')", event.Name, data)`
to this
`message := "window.wails._.Notify('" + event.Name + "','" + string(data) + "')"`
seems to solve the problem.

Not as pretty as Sprintf, but works. If this is ok, I'll make a pull request.

**Comment by leaanthony** [comment]
Hey @Lyimmi thanks for investigating this. It's quite the surprise that this limitation exists! Please feel free to PR and we'll be happy to merge :+1:
