### ISSUE TITLE
Custom Title Bar and Tray

### ISSUE THREAD

**Issue by Purple-CSGO** [wailsapp/wails#470]
Does wails support custom title bar & Tray and how to achieve that?

**Comment by leaanthony** [comment]
Hi @Purple-CSGO - Not sure what you mean by custom title bar but Tray is out of the question for V1. We looked at it for v2 but on Linux there's no guarantees you have a tray installed so it needs thinking about a bit more.

**Comment by Purple-CSGO** [comment]
![image](https://user-images.githubusercontent.com/47248616/89189341-6c987280-d5d2-11ea-8208-9f8627baf67f.png)

thx for replying! I mean: get rid of the title bar coming with the system and make my own and changes the style as I want

**Comment by leaanthony** [comment]
V2 has the option for a frameless window so that'll be possible.
