### ISSUE TITLE
Packaged app under MacOS doesnt work

### ISSUE THREAD

**Issue by WizardOfCodez** [wailsapp/wails#472]
**Description**

We were successfully able to normally build our app under MacOS Catalina. If we choose the -p flag process runs through but app starts and crashes instantly. It also seems that the problem only occurs in our project - initial project is fine. Is there any way to debug this?

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.4 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 11.0.3 |
| Npm           | 6.14.5 |
| Node          | v13.8.0 |

**Comment by brandonwkipp** [comment]
You can try building the -d flag, which shows some debugging output in a terminal.

**Comment by CrackDavid** [comment]
@brandonwkipp thanks for the tip. Problem is: building and packaging runs through without any errors. It is just that the .app file starts and crashes immediately. The linux executable on the other hand works without any problems.

Also: If I "show package contents" and execute the executable under /MacOS the app also runs.

**Comment by leaanthony** [comment]
Sorry you're experiencing this. Could you let us know what version of MacOS it is please?

**Comment by CrackDavid** [comment]
![Bildschirmfoto 2020-08-09 um 22 59 07](https://user-images.githubusercontent.com/4178312/89741721-f0030980-da93-11ea-8322-8557f75c88e5.png)
Hi @leaanthony,
I'm running on Catalina (10.15.6) - I can also give you access to the repo if you want to replicate the issue.

Cheers!

**Comment by CrackDavid** [comment]
We figured it out by ourselves. Error was because of usage of a wrong and relative path to our file storage. App crashed because of write-protected folder.

**Comment by leaanthony** [comment]
Thanks so much for letting us know about this! What steps did you take to debug this? I'd love to capture this information for the website.

**Comment by CrackDavid** [comment]
On mac you can debug an .app package by running it through the terminal like this:

``open yourapp.app`` - then you will get some error messages.
