### ISSUE TITLE
[Enhancement] Include a tutorial in React

### ISSUE THREAD

**Issue by C-likethis123** [wailsapp/wails#473]
# Issue

I have been following the Quotes generator and Todo app tutorial so far. Since I am more familiar with React than Vue, I tried to use React while going through the tutorial. 

It would be good if there was a React tutorial in the docs so I don't have to context switch. 

# Suggestion

Since I have some code on hand, I don't mind writing the tutorial in React. Feel free to comment below regarding this suggestion.

**Comment by leaanthony** [comment]
This sounds amazing! Would be very happy to accept a PR for this.

**Comment by C-likethis123** [comment]
Great! I was looking through the repositories under wailsapp, and saw docs and docsv1. Which of these do I make a PR to?

**Comment by leaanthony** [comment]
Docs v1. I should probably archive docs :+1:

**Comment by leaanthony** [comment]
This will ultimately be a PR on the `docsv1` repo so closing this. @C-likethis123 let us know if you need anything.
