### ISSUE TITLE
/.wails/wails.json: no such file or directory

### ISSUE THREAD

**Issue by chess-equality** [wailsapp/wails#477]
**Description**

I'm trying to build a (cross-platform) macOS package from LinuxLite with `wails build -f -x darwin/amd64 -p` but getting the said error.

**Screenshots**
![build-darwin_on-linux_error](https://user-images.githubusercontent.com/29477940/90644871-d9b13680-e267-11ea-8696-a504d8713d5b.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 7.5.0 |
| Npm           | 6.14.7 |
| Node          | v12.18.3 |

**Additional context**
I don't have the folder `$HOME/.wails`...?

**Comment by leaanthony** [comment]
That's interesting... When you first install Wails it asks you for some information so it can fill out details in the templates with your name etc so you don't have a bunch of files to edit. It must have been deleted somehow or not copied to a new system. It usually informs you and lets you regenerate but this must be an edge case when using docker. I guess interactively asking you to setup might be difficult . You can regenerate manually using `wails setup` but I'm not 100% sure that'll fix it as it's not obvious to me how that information gets into the container. 

We'll look into why this isn't happening :+1: 

@tmclane Thoughts?

**Comment by tmclane** [comment]
This is very odd.
That file isn't actually required.

```
k$ wails build -x darwin/amd64
Wails v1.7.0-pre1 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Pulling wailsapp/xgo:latest docker image... (may take a while)
✓ Packing + Compiling project for darwin/amd64 using docker image wailsapp/xgo:latest...
Awesome! Project 'WailsKiosk' built!
```
```
$ ls ~/.wails
ls: cannot access '/home/tmclane/.wails': No such file or directory
```

**Comment by tmclane** [comment]
FYI: I am running Ubuntu 20.04

**Comment by tmclane** [comment]
Would you mind upgrading to the most recent release and seeing if it still occurs?
Or at least `1.7.1`?

**Comment by chess-equality** [comment]
I did @leaanthony suggestion to run `wails setup` again. It created `/.wails/wails.json`, but I the following strange results:

1. I built a macOS package, the error `file not found` still persists but it doesn't name any file.
2. I built a Windows package, there were no errors but there was no package created in the `build` folder.

![wails-folder_created](https://user-images.githubusercontent.com/29477940/90726502-69042b80-e2f4-11ea-826e-7ca727a735c8.png)
![wails-cli_operations](https://user-images.githubusercontent.com/29477940/90726805-e6c83700-e2f4-11ea-95c6-74f6dbd049fe.png)

**Comment by chess-equality** [comment]
I think found something, I enabled `-verbose` and one of the libraries I'm using reported a missing file:

![wails_build-verbose-darwin](https://user-images.githubusercontent.com/29477940/90737601-bbe3e000-e300-11ea-94bc-9b8f3234ec70.png)

I'm still checking it out.

**Comment by tmclane** [comment]
Interesting!  Good find. 
Is that a something one of your imported go packages requires?

Do we need to get a library added to the docker image?

**Comment by tmclane** [comment]
I'm working on getting the docker image updated to include the `libopenssl-dev` package.  Unfortunately it would seem that the upstream repositories have changed causing difficulties with building the Docker image.

**Comment by chess-equality** [comment]
@tmclane I see, so building in this case happens on the Docker image (similar to CI/CD pipelines)?

**Comment by chess-equality** [comment]
> I'm working on getting the docker image updated to include the `libopenssl-dev` package. Unfortunately it would seem that the upstream repositories have changed causing difficulties with building the Docker image.

Sad to hear that, yes I'm using `go-sqlcipher` to encrypt our SQLite's app db, which in turn uses the OpenSSL library.

If I move to a macOS development environment, will `wails build -f -p` work in this case?

**Comment by tmclane** [comment]
Are you building a Mac application?
Yes cross-compiling requires the use of a Docker image at this time.  It would be very difficult to tell a user what packages to install on their host OS otherwise.  We felt this was the easiest way to provide a packaged build environment that will `just work`.

Of course that means we have to include every possible library that might be needed to cover all the bases.  In this case we didn't get there.  I should add the ability to substitute an alternative cross-compile image as a n optional flag to the cross-compile build so that people can extend our image and add any additional libraries they need without waiting for us to update our image.

**Comment by tmclane** [comment]
> 
> If I move to a macOS development environment, will `wails build -f -p` work in this case?


Yes building it on a mac natively should work assuming the libraries and headers you need are installed.  Presumably you know how to install them yourself in that case.

**Comment by chess-equality** [comment]
Ok I think I should use macOS natively to build it. Thanks for all the help. I'll close this shortly if I don't encounter any more issues.
