### ISSUE TITLE
macOS package switch "-p" creates ".app" folder instead of executable

### ISSUE THREAD

**Issue by chess-equality** [wailsapp/wails#479]
**Description**

I'm packaging my first macOS (Catalina) app and the docs says about`-p`: _"On OSX, it bundles your binary into a .app file with the default icon."_, but what was created was an `.app` folder instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build -f -p`.

**Expected behaviour**
The command should create a `.app` executable file, not a folder.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.15 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 12.0.0 |
| Npm           | 6.14.8 |
| Node          | v12.18.3 |

**Additional context**
#477

**Comment by chess-equality** [comment]
> Packaging an app for Mac should do exactly as you've stated: create a `.app` folder with the necessary files in it.

@leaanthony I stated that it creates an app folder instead of an app file, as the docs also says it should create an app file.

_"On OSX, it bundles your binary into a .app file with the default icon."__

Did you mean here that the app file/executable is in fact in the `Contents/MacOS directory`? I think the docs should clearly state this.

**Comment by leaanthony** [comment]
All Mac apps are packed this way. From a finder point of view, the bundle is a file. I'll change the docs to say bundle 👍
