### ISSUE TITLE
[Enhancement] Convert React template to use functional components

### ISSUE THREAD

**Issue by timkippdev** [wailsapp/wails#482]
**Description**
Currently the React template that is generated through Wails CLI uses class components. I would like to update the React template to generate functional component examples to be in sync with how the current CRA CLI tooling does. 

What are your thoughts on this request? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails init`, and choose to use the `React JS - Create React App v3 template` templating option.

**Expected behaviour**
When generating a Wails project using the React template, the generated code use be using functional components.

**Comment by leaanthony** [comment]
Happy to accept a PR for this.
