### ISSUE TITLE
Permssions denied on cgo.a when running wails serve

### ISSUE THREAD

**Issue by jaypee-f** [wailsapp/wails#485]
**Description**

Running wails serve gives permissions denied error on runtime/cgo.a.

**To Reproduce**
Steps to reproduce the behaviour:
wails init
app name "demo"
Vue2 basic type
cd demo
wails build
./demo # demo runs fine
wails serve

$ wails serve
Wails v1.7.1 - Serving Application

✓ Ensuring Dependencies are up to date...
⣯ Packing + Compiling project...go build runtime/cgo: copying /Users/**/Library/Caches/go-build/****: open /usr/local/go/pkg/darwin_amd64/runtime/cgo.a: permission denied

**Expected behaviour**
Debugger should start without needing to write the system go runtime directory

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.7 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 11.0.3 |
| Npm           | 6.14.5 |
| Node          | v13.12.0 |

**Additional context**
Go installed via .dmg file

**Comment by jaypee-f** [comment]
`sudo go build -i -o build/demo -ldflags "-w -s -X `github.com/wailsapp/wails.BuildMode=bridge"`

Solves it. But seems odd to need to install into a system directory

**Comment by leaanthony** [comment]
Looks like a permissions error in your go installation based on needing sudo.  I'm assuming removing sudo also fails?

**Comment by jaypee-f** [comment]
Yeah I wouldn't have thought wails needed to overwrite the system installed cgo. But I'm not au fait with cgo.

**Comment by jaypee-f** [comment]
sudo was required, -i installs the deps. 
GOPATH (from go env) was user writable, ~/go as are the caches ~/Library perhaps wails is unsetting these env variables? 
Seems weird that no other go package I use does this.

**Comment by spoonofpower** [comment]
I ran into the same problem. The permission error is because the `-i` flag to `go build` tells go to install any rebuilt packages. So it's trying to update $GOROOT/pkg/darwin_amd64/runtime/cgo.a. That's likely read-only, depending on how you installed go.

The code mistakenly assumes the `-i` flag is for ignoring errors:

https://github.com/wailsapp/wails/blob/master/cmd/helpers.go#L219-L222

**Comment by leaanthony** [comment]
@spoonofpower - nice catch and sorry for the hassle that caused! The latest pre-release has a fix for this. `wails update -pre` to try it out :+1:

**Comment by spoonofpower** [comment]
Great. It works as expected after running `wails update -pre`. Thanks!

**Comment by leaanthony** [comment]
@jaypee-f - Please close if this is now resolved for you.

**Comment by leaanthony** [comment]
Closing as I think it's resolved.
