### ISSUE TITLE
'Cocoa/Cocoa.h' file not found on MacOS

### ISSUE THREAD

**Issue by cxt90730** [wailsapp/wails#486]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
I cannot use wails just begin. I have installed npm and xcode-select. When I run `wails init`, it shows:

In file included from ../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.go:26:
./webview.h:80:9: fatal error: 'Cocoa/Cocoa.h' file not found
#import <Cocoa/Cocoa.h>
        ^~~~~~~~~~~~~~~
1 error generated.

**To Reproduce**
Steps to reproduce the behaviour:
run `wails init` on my Macbook

**Expected behaviour**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/11382804/91926314-92b44e00-ed09-11ea-9ad7-74d06e90188e.png)

**System Details**
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cuixiaotian/Library/Caches/go-build"
GOENV="/Users/cuixiaotian/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cuixiaotian/go/pkg/mod"
GONOPROXY="10.0.45.221"
GONOSUMDB="10.0.45.221"
GOOS="darwin"
GOPATH="/Users/cuixiaotian/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cuixiaotian/wail/my-project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kr/s0z6rws50hj5ktqdqcytk6jw0000gn/T/go-build994657416=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**
xcode-select version 2373

**Comment by leaanthony** [comment]
A quick search suggests you haven't installed the xcode tools as per the docs https://wails.app/gettingstarted/mac/#gcc-libraries

**Comment by cxt90730** [comment]
I have re-installed `xcode-select`, also install `Xcode.App`, but it still not works...the error is still occurs... :( ...so sad

My `brew config` result:
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cd6c90907bee54c409c64415163aa11ca078cf78
Core tap last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_221
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.7

**Comment by cxt90730** [comment]
![image](https://user-images.githubusercontent.com/11382804/91993569-19981380-ed68-11ea-8a28-f2eacc6595fd.png)

**Comment by leaanthony** [comment]
Feels like the homebrew route might be the reason. What happens if you install score from the app store?

**Comment by cxt90730** [comment]
Have you compiled and executed on mac OS 10.15 ? I can’t find all the .h files in my computer...

**Comment by leaanthony** [comment]
Yes. Sorry, I can't reproduce this.

![image](https://user-images.githubusercontent.com/1943904/92103119-d9499b80-ee22-11ea-8324-35f817b03b9d.png)

**Comment by cxt90730** [comment]
I can run Xcode, and build a MacOS App by using Cocoa.h...WTF...Thank for your feedback
![image](https://user-images.githubusercontent.com/11382804/92116423-6510f700-ee26-11ea-8b22-e1c86a434f75.png)

**Comment by leaanthony** [comment]
Maybe your Go installation is borked?

**Comment by cxt90730** [comment]
I can find <stdlib.h> but cannot find <Cocoa.h>.  I suddenly feel this proplem is related to cgo and Header Path in MacOS. Because I'm inspired by an article：https://medium.com/@croath/catalina-macos-10-15-%E4%B8%8B-cgo-%E4%B8%8D%E8%83%BD%E8%BF%90%E8%A1%8C%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-5b580140b45a

I will try it later.

**Comment by cxt90730** [comment]
Tell you a good news, I resolved;

Step 1 : export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
Step 2 : remove `anaconda3`

That's all... (During the period I also tried to reinstall the OSX system...but still not works...)

You can update your trouble shooing. Thank for your feedback :)

**Comment by leaanthony** [comment]
Thanks for getting back with the feedback. Glad it's sorted for you!
