### ISSUE TITLE
Support Distribution 'Ctlos'

### ISSUE THREAD

**Issue by kyoto44** [wailsapp/wails#487]
**Description**
Distribution 'ctlos' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.15.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| Distribution ID   | ctlos |
| Distribution Name   | Ctlos |
| Distribution Version   | 1.10.0_20200824 |

This distro is just customized Archlinux

**Comment by leaanthony** [comment]
This has been released. Update using `wails update -pre` :+1:
