### ISSUE TITLE
Command Fails in windows OS for folders with space in their name

### ISSUE THREAD

**Issue by omajDev** [wailsapp/wails#491]
**Description**

Hi, when try to build when with wails it fails with message of "'C:\Users\Omar' is not recognized as an internal or external command" , operable program or batch file.
since my home folder is  'C:\Users\Omar Junaibi' i assumed it is related to space.

**To Reproduce**
Steps to reproduce the behaviour:
Run 'wails build' within directory structure with folder name that has space

**Expected behaviour**
Build Application

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/5851773/92286310-b816a700-ef17-11ea-993c-152829c6e7eb.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.3 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.5 |
| Node          | v14.3.0|

**Comment by leaanthony** [comment]
Can confirm this doesn't occur on Linux:
![image](https://user-images.githubusercontent.com/1943904/92315604-3ca61a00-f02b-11ea-889f-73f7ff296154.png)

**Comment by leaanthony** [comment]
I'm unable to reproduce this. I tried in git bash, powershell and command prompt:
![image](https://user-images.githubusercontent.com/1943904/92317205-bc3ee380-f041-11ea-89e8-cb675d157b8b.png)

**Comment by leaanthony** [comment]
Thanks for reporting this info! How can we bet warn people about this? Would love to update the docs with a fix.

**Comment by tingspace** [comment]
If it were me, I'd just add a note to the [Windows Getting Started](https://github.com/wailsapp/docsv1/blob/master/content/gettingstarted/windows.md) page under the **npm** header with a link to the npx issue for clarity, there are some workarounds in the thread and linked issues that people could try.

I opted for not wanting a space in my User Profile entirely which isn't the only way around this.

**Comment by leaanthony** [comment]
I have added the suggested note to the docs as suggested 👍
