### ISSUE TITLE
When using vuerouter nested routing development ,Nested routes cannot be displayed

### ISSUE THREAD

**Issue by YLQZ** [wailsapp/wails#492]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
1. Nested routes cannot be displayed when developed with Vue and vuerouter
2. wails build and run,  wails not defined

**fix**
 During development, the Vue router nested routing mode can use hash and history. Abstract must be used when packing

**request**
I use a translator, please write the solution in regular English https://wails.app/guides/vuerouter/ thank you

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

**Comment by leaanthony** [comment]
Thanks for opening this. Is this information to add to the documentation?

**Comment by leaanthony** [comment]
Updated the docs. Thanks!

**Comment by YLQZ** [comment]
@leaanthony  在之前的文档中 只说明了 使用vuecli示例的 单个页面组件使用 ， 加上vueRouter后  使用嵌套路由 abstract  mode  开发过程 启动wails serve  ，UI  npm run dev ，在浏览器中   无法显示嵌套页面的内容 只显示App.vue。 使用 hash and history  wails build  然后 运行报错:   block/#   wails is not defined 。 我看到  有人在使用abstract  成功了，所以我试了一下。
！！ 在开发过程中  使用浏览器进行调试 只能用 hash and history   打包成exe时 需要设置成 abstract  ，打包后运行才会成功
OS：win10  
您可以试验确认一下 ，另 英语不好  请见谅，ha ha

**Comment by leaanthony** [comment]
非常感谢您为编写此报告所做的努力。我已经更新了文档。

**Comment by cosse** [comment]
@YLQZ 请问开发的时候使用hash 和 history 没有任何问题，但是打包之后使用abstract 模式，无法正在加载router呢，请问一下abstract 的正确使用方式？
