### ISSUE TITLE
There is no response when the application starts on windows

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#494]
*I'm not sure it's a bug, so I didn't use the bug template*
*这不确实是不是一个bug，因为有可能是我使用错误，所以我没有用bug issue模板*

I installed 'tdm-gcc-64' and 'nodejs' on win10 system, and created a new project with' wails init '. No error was reported when starting the application, but no application interface was displayed. Here is a screenshot of my operation interface:
我在win10系统上面安装了 `TDM-GCC-64` 和 `NodeJS` ,用`wails init`新建项目，启动应用程序没有报错，但是没有应用程序界面显示出来。下面是我的操作界面截图：
frontend:
![image](https://user-images.githubusercontent.com/28185258/92466049-171f3900-f202-11ea-921c-5de4e96d762e.png)
golang:
![image](https://user-images.githubusercontent.com/28185258/92466064-1ededd80-f202-11ea-9713-c9d7f596bbfb.png)

**Comment by Splode** [comment]
@misitebao What happens when you either navigate to `http://localhost:8080` in a browser or curl that URL?

**Comment by leaanthony** [comment]
@misitebao - You are running in `serve` mode - did you intend to do that? Does the output of `wails build -d` work for you?

**Comment by misitebao** [comment]
I think I know what's going on. The reason is that in the development mode, I could just use ‘http://localhost:8080’ to open debugging in the browser. But I used Electron before, so I thought there would be a window pop up in the development mode.I'm sorry that I used it improperly. Thank you for your reply.@Splode @leaanthony
我想我知道是怎么回事了，原因是在开发模式下是直接在浏览器使用‘http://localhost:8080’打开调试就可以的，但我之前用Electron，所以我以为开发模式会有一个窗口弹出，抱歉是我使用方法不当，感谢你们的回答。
