### ISSUE TITLE
can't running wails demo on mac

### ISSUE THREAD

**Issue by l0v1kill1r** [wailsapp/wails#496]
**Description**
wails demo created by command `wails init`
no error message using the command 'wails build'
but,if i use command `go run main.go`:
==================================================[error start]
# github.com/wailsapp/wails/lib/renderer/webview
In file included from _cgo_export.c:4:
In file included from webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:88:3: warning: 'WebView' is deprecated: first deprecated in macOS 10.14 - No longer supported; please adopt WKWebView. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/WebKit.framework/Headers/WebView.h:119:12: note: 'WebView' has been explicitly marked deprecated here
In file included from _cgo_export.c:4:
In file included from webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2082:19: warning: 'WebView' is deprecated: first deprecated in macOS 10.14 - No longer supported; please adopt WKWebView. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/WebKit.framework/Headers/WebView.h:119:12: note: 'WebView' has been explicitly marked deprecated here
In file included from _cgo_export.c:4:
In file included from webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2265:24: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2282:20: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
# github.com/wailsapp/wails/lib/renderer/webview
In file included from ../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:88:3: warning: 'WebView' is deprecated: first deprecated in macOS 10.14 - No longer supported; please adopt WKWebView. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/WebKit.framework/Headers/WebView.h:119:12: note: 'WebView' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2082:19: warning: 'WebView' is deprecated: first deprecated in macOS 10.14 - No longer supported; please adopt WKWebView. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/WebKit.framework/Headers/WebView.h:119:12: note: 'WebView' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.go:26:
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2265:24: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
../../go/pkg/mod/github.com/wailsapp/wails@v1.7.1/lib/renderer/webview/webview.h:2282:20: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]

==================================================[error end]
**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.4 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 11.0.3 |
| Npm           | 6.4.1 |
| Node          | v11.0.0 |

**Comment by leaanthony** [comment]
https://wails.app/gettingstarted/installing/#build-it
