### ISSUE TITLE
App is a black screen after building but works fine in development

### ISSUE THREAD

**Issue by artooro** [wailsapp/wails#497]
**Description**

I just built a new Wails app using the Angular template. When running in dev mode using wails serve and npx ng serve it works great. But if I build it using wails build or wails build -p it is just a black window. There is nothing in standard output and I can't find any useful troubleshooting info in the console.

**Screenshots**
![Screen Shot 2020-09-09 at 09 07 10](https://user-images.githubusercontent.com/393395/92602327-01e6f080-f27c-11ea-9f8f-0176d96fb3f2.jpg)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.15 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | 6.14.7 |
| Node          | v14.9.0 |

**Additional context**
In development the app works fine in both Safari and Chrome. If there is a way for me to see any logs from the built app, that would be great to know and be documented.

**Comment by leaanthony** [comment]
What version of MacOS? 10.15.5 works fine:

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1943904/92644502-cfde9880-f326-11ea-98cd-11ec11f87d3c.png">

**Comment by leaanthony** [comment]
v10.15.6
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/1943904/92648053-3a460780-f32c-11ea-8f7f-089bf0745bd4.png">

**Comment by leaanthony** [comment]
Can confirm `wails build -p` works too

**Comment by artooro** [comment]
@leaanthony yeah the raw template works fine, but the app I built from the template does not. I was hoping there would be some type of log from the built binary that would show me what is going on.

**Comment by leaanthony** [comment]
[667809ih[][k[]';.;llll](url)

**Comment by leaanthony** [comment]
Ah, building with -d will dump logs when run from terminal

**Comment by artooro** [comment]
Ah thanks, I missed that flag. So with the debug logs everything looks nominal so unfortunately doesn't help me resolve the actual issue. I'll have to rip out pieces of my code until it's narrowed down.

**Comment by artooro** [comment]
Spoke too soon, looks like in debug mode it's also possible to open the javascript console in the app window, where I noticed this error. "Unhandled Navigation Error".
<img width="1014" alt="Screen Shot 2020-09-09 at 17 56 56" src="https://user-images.githubusercontent.com/393395/92659205-eb658700-f2c5-11ea-880c-67de2694ec3f.png">

So would I be correct that angular routing does not work in a Wails app?

**Comment by leaanthony** [comment]
I can't really help you with an Angular issue, but what I can do is point you to how the Vue and React people do routing and perhaps there's a similar solution for Angular? https://wails.app/guides/

If you find the answer, we'll update the docs :+1:

**Comment by artooro** [comment]
@leaanthony found that enabling hash based routing fixes the problem, so I've submitted a pull request to update the template.

I now have another issue where an image asset isn't loading, but that's unrelated and probably something I'm doing wrong.
