### ISSUE TITLE
How do I implement a rimless window

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#503]
**This is not a bug, so I did not use the ‘bug template’**

 :grey_question: Hello, I want to know how to implement without borders window, I am not in the document to find corresponding solutions, I saw the website the above example (https://wails.app/showcase/optimus/) but I will prompt wrong, run the sample so I would like to know whether the good solution.

**Comment by misitebao** [comment]
When I was looking for the parameter configuration related to borderless, I found that wails.AppConfig.HTML This parameter has a default value, as shown in the following figure: |

我在找有关无边框相关的参数配置的时候，发现了wails.AppConfig.HTML这个参数，发现他有一个默认值，如图：

![image-20200910174350829](https://gitee.com/misitebao/CDN/raw/master/md/20200910174353.png)

Then I found the file and found a method called addscript, as shown in the figure: |

然后我找到了这个文件，发现里面有一个名叫 AddScript 的方法，如图：![image-20200910174525182](https://gitee.com/misitebao/CDN/raw/master/md/20200910174526.png)

So I'd like to know about this HTML file and the package generated through the 'frontend' directory index.html The difference and function between the two documents.Your answer will be very helpful to me, thank you! |

所以我想知道这个html文件和 frontend打包生成的那个index.html文件之间的区别以及作用。您的回答将会对我很优帮助，谢谢！

**Comment by leaanthony** [comment]
Chromeless windows aren't available in V1. Optimus screenshots are just cropped that way.

**Comment by misitebao** [comment]
@leaanthony 
Ok, I see. Thank you. There are also some questions:
1. Is there any support for bezel-less mode? How long, if any, will it take? After all, this feature is used a lot.
2. Will multiple Windows and child Windows be supported?
好的，我了解了，谢谢你。另外还有一些问题：
1.无边框模式有计划支持吗？如果有的话大概需要多久？毕竟这个功能使用的还是比较多的。
2.是否会支持多窗口和子窗口？

**Comment by leaanthony** [comment]
1. Will be available in V2 🤞 
2. Multiple windows, not for V2

**Comment by misitebao** [comment]
> 1. Will be available in V2 🤞
> 2. Multiple windows, not for V2

Ok, I see. Thank you!
好的，我了解了，谢谢你！
