### ISSUE TITLE
Can't Build & Pack for Mac

### ISSUE THREAD

**Issue by ilgityildirim** [wailsapp/wails#505]
**Description**

When packing for MAC it says "Error: file not found" on Packing   Compiling project for darwin/amd64 using docker image wailsapp/xgo:latest stage.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build -x darwin/amd64 -p` command
4. See error: `Error: file not found`

**Expected behaviour**
Build & pack for MAC.

**Screenshots**
![image](https://user-images.githubusercontent.com/4365245/92992374-a2dae300-f4ea-11ea-83a1-7e2ac9ad0b50.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.14.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.3.0 |
| Npm           | 6.14.6 |
| Node          | v12.18.3 |

**Additional context**
I'm experiencing the same problem on Windows 10 (dual boot)

**Comment by leaanthony** [comment]
@tmclane might be able to test this before me. Will get back to tou

**Comment by tmclane** [comment]
Would you mind running it with `-d` so that it might tell us what file is missing?
I wonder if it is the openssl header file again.

**Comment by ilgityildirim** [comment]
@tmclane looks like something else;
![image](https://user-images.githubusercontent.com/4365245/92999231-86a56900-f51f-11ea-8420-63645bfa834a.png)

**Comment by ilgityildirim** [comment]
@tmclane thank you for your response, it looks like it is something else;
![image](https://user-images.githubusercontent.com/4365245/92999275-e734a600-f51f-11ea-8a9f-1c987d562d8b.png)

**Comment by tmclane** [comment]
Library incompatibility issues?  Can your share the go.mod file?  Presumably you don't want to share your entire project.

**Comment by ilgityildirim** [comment]
@tmclane yes, unfortunately I can't share the project source code at the moment.

```
go 1.14

require (
	github.com/DATA-DOG/go-sqlmock v1.5.0 // indirect
	github.com/JamesStewy/go-mysqldump v0.2.2
	github.com/Masterminds/semver v1.5.0 // indirect
	github.com/fatih/color v1.9.0 // indirect
	github.com/go-sql-driver/mysql v1.5.0
	github.com/go-yaml/yaml v2.1.0+incompatible
	github.com/gorilla/websocket v1.4.2 // indirect
	github.com/hnakamur/go-scp v1.0.0
	github.com/jinzhu/gorm v1.9.14
	github.com/jlaffaye/ftp v0.0.0-20200812143550-39e3779af0db
	github.com/kr/pretty v0.1.0 // indirect
	github.com/leaanthony/mewn v0.10.7
	github.com/leaanthony/slicer v1.4.1 // indirect
	github.com/mattn/go-colorable v0.1.7 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/pkg/sftp v1.11.0
	github.com/sirupsen/logrus v1.6.0 // indirect
	github.com/wailsapp/wails v1.8.0
	golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
	golang.org/x/image v0.0.0-20200618115811-c13761719519 // indirect
	golang.org/x/net v0.0.0-20200707034311-ab3426394381 // indirect
	golang.org/x/text v0.3.3 // indirect
)
```

**Comment by leaanthony** [comment]
Have you tried clearing the Go cache?

**Comment by ilgityildirim** [comment]
@leaanthony yes I have, same issue.

**Comment by tmclane** [comment]
What's odd is the image is including a 10.11 OS X SDK so I am unsure where a 10.6 comes from.
