### ISSUE TITLE
The wait build - ldflags "- H windowsgui" command is invalid

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#509]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
Run the `wails build -ldflags "-H windowsgui"` command to package the application
But starting an external application will still have an extra black window |
运行`wails build -ldflags "-H windowsgui"`命令打包应用程序
但是仍然会有一个多余的黑色窗口

**To Reproduce**
Steps to reproduce the behaviour:
1. wails Init
1. wails build -ldflags "-H windowsgui"

**Expected behaviour**
When launching external applications, I don't want to have an extra window |
启动外部应用程序的时候，我不希望有一个多余的窗口

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/93042802-9ab5ab80-f682-11ea-8ab4-a6c5c9ad8bcf.png)

**System Details**
Go 1.14.4
Wails v1.8.0
OS Windows 10

**Additional context**
I think this is not an error. It should be my improper operation. However, I operate according to the method of using v1.8.0 as required in the document.

**Comment by leaanthony** [comment]
Whilst technically you should be able to do.this, I think what you are looking for is the `-p` flag. Building in debug mode will give you the console

**Comment by tmclane** [comment]
When building for Windows the `-H windowsgui` flag is already being passed in automatically.
v2/pkg/commands/build/base.go:154:

**Comment by misitebao** [comment]
@leaanthony  @tmclane Thank you for your advice, but I still have some small problems here.

I call the RunClient method in wails application. The method is as follows: |

我在wails应用中调用 RunClient方法，方法体如下：

```go
func RunClient(sessionId string, peerId string) (string, error) {

	fmt.Printf("sessionId is %v\n", sessionId)
	fmt.Printf("sessionId is %v\n", peerId)
	fmt.Println("Run client.exe")

	cmd := exec.Command("./client.exe", sessionId, peerId)
	cmd.Start()

	return "Ok", nil
}
```

Run the 'wails build' command to package the application, and then copy and paste the generated application binary file into the` client.exe `The folder where the file is located is as follows: |

运行`wails build`命令打包应用程序，然后将生成的应用程序二进制文件复制粘贴到`client.exe`文件所在文件夹，目录如下：

![image-20200915101533377](https://cdn.jsdelivr.net/gh/misitebao/CDN@master/md/20200915101616.png)

Start` cloudDesktop.exe `There will be an extra window, as shown in the figure: | 

启动`cloudDesktop.exe`会有一个多余的窗口，如图所示：

![image-20200915101946660](https://cdn.jsdelivr.net/gh/misitebao/CDN@master/md/20200915101948.png)

I want the 'redundant window' not to be displayed when I perform the previous step. So how can I package the application to meet my requirements?|

我希望执行上一步的时候，不显示`redundant window`。那么，我应该怎么打包应用程序才能实现我的需求？

**Comment by tmclane** [comment]
Is the client.exe another wails app?
What creates that binary?

**Comment by misitebao** [comment]
> When building for Windows the flag is already being passed in automatically so you shouldn't need to pass that yourself.
> Do you require the flags when building in debug mode?
> I just checked and I can see that it is not specified automatically when the application is built in debug mode.`-H windowsgui`

There's no problem building in debug mode, there's a debug window, but there won't be an extra black window like the one I've shown. thank you! | 
在调试模式下构建没有任何问题，有一个调试窗口，但是不会像我展示的图片那样出现一个多余的黑色窗口。谢谢你。

**Comment by misitebao** [comment]
> Is the client.exe another wails app?
> What creates that binary?

It's not a wails app,It can run alone, I put the wails app(desktopClient.exe) Paste it into the directory to call it,Use the following code：

![image-20200915103736666](https://cdn.jsdelivr.net/gh/misitebao/CDN@master/md/20200915103737.png)

**Comment by tmclane** [comment]
Would you mind trying branch `feature/windowsgui` and seeing how it works for you?
The change in the branch is to always specify the `-H windowsgui` if the platform is windows.

**Comment by misitebao** [comment]
You can try to use go language to call another binary program on Windows OS, and the same problem will occur. This is not only in wails, but also in Go program, which can use "go build - ldflags" - S - W - H = windowsgui " main.go `Order to solve the problem. But the wails application uses the wails command, so I don't know how to solve this problem. |

你可以尝试在windwos上用go语言调用另外一个二进制程序，会出现同样的问题，这个不是不只是存在wails中，但是go程序可以用`go build -ldflags "-s -w -H=windowsgui" main.go`命令解决这个问题。但是wails应用程序使用wails命令，所以，我不知道怎么去解决这个问题。

**Comment by leaanthony** [comment]
I don't understand why you are doing this. `wails build -d` will give you a debug version with the terminal window for debug output and `wails build -p` will give you a production build without the terminal window.

**Comment by misitebao** [comment]
> Would you mind trying branch `feature/windowsgui` and seeing how it works for you?
> The change in the branch is to always specify the `-H windowsgui` if the platform is windows.

I've just tried your scheme, but it's still the same result. However, I just tried a small demo. There will be no problem using wails packaged app to call wails packaged app. Why is this? Is it mine clien.exe Is that a problem? |
刚刚尝试了你的这个方案，很遗憾，还是一样的结果，不过我刚才尝试了一个小demo，使用wails打包的app调用wails打包的app不会有任何问题，这个是为什么，难道是我的clien.exe的问题吗？

**Comment by misitebao** [comment]
> I don't understand why you are doing this. `wails build -d` will give you a debug version with the terminal window for debug output and `wails build -p` will give you a production build without the terminal window.

We need to use wails to write a desktop client to call another binary program written by C. when calling, we need to pass parameters, similar to 'client Param1 param2'. But we found the above problem when calling. :cry:  |
我们需要用wails写一个桌面客户端，去调用另外一个由c编写的二进制程序并且调用的时候需要传递参数，类似`client param1 param2`,但是调用的时候发现了上面的问题。 :cry:

**Comment by leaanthony** [comment]
Surely that's a problem with compiling your app? I'm a little lost tbh

**Comment by tmclane** [comment]
Unsure how you compiled that program but it would seem the issue with the extra window is the program you are running.  If you run `client.exe` all by itself on the command-line does it not open a window?

**Comment by misitebao** [comment]
> Unsure how you compiled that program but it would seem the issue with the extra window is the program you are running. If you run `client.exe` all by itself on the command-line does it not open a window?

If I open the 'client.exe' program alone, there is no extra window |
如果我单独打开"client.exe"程序，是没有额外的窗口的。

**Comment by misitebao** [comment]
> Surely that's a problem with compiling your app? I'm a little lost tbh. It looks like your command.Exec is opening that window.

On the "windows" platform, use the "go" language“ exec.command ”Command to open other applications will have such a problem. Generally, the "- lgflag" parameter will be added when compiling to solve this problem. However, in the wails program, I don't know how to solve this problem. You can try to use the wails application on the windows system Starting other programs on your computer should have the same problem. |
在“windows”平台上，使用”go“语言里面的“exec.command”命令打开其他应用程序都会有这样的问题，一般会在编译的时候加上“-lgflag”参数来解决这个问题，但是在wails程序里面，我不知道怎么去解决这个问题，获取你可以尝试一下在windows系统上面，使用wails应用启动你的电脑上的其他程序，应该也会存在一样的问题。

**Comment by leaanthony** [comment]
Sorry @misitebao - this isn't a wails problem.
