### ISSUE TITLE
Multiple file select is not supported

### ISSUE THREAD

**Issue by artooro** [wailsapp/wails#512]
**Description**

If I use a file selector that defined the muiltiple attribute, when running as an app it only allow me to select a single file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a multi file selector such as `<input type="file" accept="image/jpeg" multiple="multiple" bind:files>`
2. Build and open the app
3. Click on the Select files button.
4. It will only allow you to select a single file, even though the button itself said "Select files" (plural)

**Expected behaviour**
I would have expected, and when running in dev mode with Safari it does allow multiple files to be selected.

**Screenshots**
I don't think a screenshot is helpful in this case.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.1 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | 6.14.8 |
| Node          | v14.9.0 |

**Additional context**
I'm aware of https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements replacing webview, but another issue mentioned that there was a new webview now so I don't really know where this issue lands. Perhaps it's due to a webview limitation but I don't know if it's also dependent on the replacement or not as issue #235 is closed.

**Comment by leaanthony** [comment]
It's not that it's broken, it's just not supported at this time.

**Comment by leaanthony** [comment]
What's interesting about this is what you are looking at is native to the webview. We only support opening file selectors via the runtime so we couldn't make this work even if we wanted to.

**Comment by artooro** [comment]
@leaanthony without me digging into how wails is doing file selectors, are you saying that this ability will never (foreseeable) happen, or is dependent on switching to something like DeskGap?
I'm unfortunately not going to be able to use wails for my app because of this.

**Comment by leaanthony** [comment]
We can try to backlist the multiple selection code, but it won't be magically triggered from an input box. You'll need to call the runtime function.

**Comment by leaanthony** [comment]
I should have mentioned that our new windowing library does indeed support multiple file selection. Mac is pretty much there and yes multiple file selections work great (OpenDialog now returns `[]string`). The Linux port needs tweaking with some API changes then we're onto the Windows port. What OS are you targeting?

**Comment by artooro** [comment]
I am targeting macOS primarily.

**Comment by leaanthony** [comment]
![image (5)](https://user-images.githubusercontent.com/1943904/94530555-98587180-027e-11eb-81c6-f211c61ec0eb.png)

:+1:

**Comment by leaanthony** [comment]
For v1, this won't be supported. Keep your eyes out for v2....

**Comment by artooro** [comment]
@leaanthony keep up the great work!

**Comment by leaanthony** [comment]
Thanks @artooro - it's a huge project for one person to run! I'm just thankful for the contributors!
