### ISSUE TITLE
Lazy loaded Module is not working in Angular routing

### ISSUE THREAD

**Issue by contactzen** [wailsapp/wails#513]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**
I am able to create a route using Component, and it works great. However, when I tried to use the lazy loading module. it doesn't load. 

**To Reproduce**
1. Create application `wails init`
2. create new module name test3 in frontend
3. add the following routing in `app-routing.module.ts
 ```
{ path: 'test3', loadChildren: () => import(`./test3/test3.module`).then(m => m.Test3Module) ,     data: { applyPreload: true }},
```
4. add the following tag in app.component.html before router-outlet
```
  <a [routerLink]="['/test3']">test3</a> 
```
**Expected behavior**
It should render the test module

**Screenshots**

**System Details**
Operating system: Ubuntu 18
Go: 1.14.7
wails version: v1.8.0

Thank you for building such great application.

**Comment by leaanthony** [comment]
Hi. We can't really help with Angular routing but [this PR](https://github.com/wailsapp/wails/pull/502/files) may be of interest.
It was included in `v1.8.1-pre1` which you can get using `wails update -pre`.

**Comment by kush99993s** [comment]
I already notice that and change it. It is not big deal because I can still route using components but I thought I can do using module it might nice. 

Nevertheless thank your great work on this.

**Comment by contactzen** [comment]
I have already updated my code to use the hash router. In Angular, routing works with Components but not Module. I would have liked to have module routing working. However, it is not critical for building applications. 

Thank you for your help.

**Comment by leaanthony** [comment]
If you find a way, let us know! 👍
