### ISSUE TITLE
Update to latest webview ?

### ISSUE THREAD

**Issue by ahmadfarisfs** [wailsapp/wails#515]
I see that https://github.com/webview/webview is now using Edge engine as renderer for windows, will wails support this ? thanks. Because In current 1.8.0 build , windows build still use outdated IE engine that has many limitation

**Comment by tc-hib** [comment]
This was answered in this closed issue : #454
We have to wait for v2 which wouldn't depend on the "webview" project if I understood correctly.
On the other hand, there is tauri which is based on webview and should get Go bindings some day according to their roadmap.

**Comment by leaanthony** [comment]
Updating to latest webview is not possible and yes we've tried. V2 is coming along well. Mac and Linux are usable and Windows will be next.

**Comment by leaanthony** [comment]
Just an update on this, Webview has dropped support for dialogs altogether so we are nowhere near parity with that project now. The good news is that our windowing library is coming along really well 👍
