### ISSUE TITLE
[Enhancement] Vue 3 Support

### ISSUE THREAD

**Issue by kmuchmore** [wailsapp/wails#516]
I would like to be able to develop using Vue 3 and Typescript. 

Is this just creating a new template? or would it be more involved? I am willing to help out on getting this started, I just need to be pointed in the right direction.

I'm aware that Vue 3 is still getting ironed out, and this will be a work in progress until end of Q2 (which is the suggested time for Vue 3 adoption). I just wanted to understand what is involved in adding in a new setup.

Thanks

**Comment by tmclane** [comment]
Yes you would get started just creating a new template.

Please see the Vue related templates in this directory: https://github.com/wailsapp/wails/tree/master/cmd/templates

**Comment by tmclane** [comment]
- Copy one of them to a new directory i.e. vue3
- Edit cmd/templates/vue3/template.json to ensure it has a unique configuration
- recompile the `wails` command and it should show up in the `wails init` output as a selection

Please note the naming of things.  Files with template as an extension are used as go template input.  They will be processed and the extension dropped when creating the project directory.

**Comment by leaanthony** [comment]
There's also this: https://wails.app/development/#tooling

**Comment by tmclane** [comment]
I forgot about that command!

**Comment by kmuchmore** [comment]
I'm not sure if I should make this a separate issue or not, let me know. 

I have created a wails application using Vue3, but when I launch it, all I get it a window showing up that shows

```
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta http-equiv="IE=edge" content="IE=edge"></head>
<body><div id="app"></div><script type="text/javascript"></script></body>
</html>
```
I'm not sure where it is getting this from cause when I launch it via bridged mode using wails serve and npn run serve everything shows up as expected. I'm trying to figure out where to start. Thanks

**Comment by leaanthony** [comment]
That makes no sense whatsoever! Does the standard template work ok? Perhaps open an issue with `wails issue`

**Comment by kmuchmore** [comment]
Yes, the standard template works just fine. I have make a new template for Vue3 and that is where I'm having the confusion.

**Comment by tmclane** [comment]
Would you push up your changes somewhere and provide a link? 
Extra eyes might notice the issue.

**Comment by kmuchmore** [comment]
I have pushed what I have to https://github.com/kmuchmore/wails_vue3_setup
Extra eyes would be appreciated. Thanks

**Comment by kmuchmore** [comment]
I have created an issue using `wails issue` #518

**Comment by leaanthony** [comment]
Completed by #522
