### ISSUE TITLE
Cannot package application for mac

### ISSUE THREAD

**Issue by ZSCodes** [wailsapp/wails#517]
Description
wails demo created by command wails init
no error message using the command 'wails build'
but, if i use command 'wails build -p':
==================================================[error start]
Wails v1.8.1-pre1 - Packaging Application (force rebuild)

✓ Ensuring frontend dependencies are up to date (This may take a while)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Error: unexpected end of JSON input
==================================================[error end]

I can't find out the cause of the problem. Please give me some advice

Name | Value
-- | --
Wails Version | v1.8.1-pre1
Go Version | go1.14.4
Platform | darwin
Arch | amd64
GO111MODULE | on
GCC | 11.0.3
Npm | 6.14.4
Node | v13.12.0

**Comment by leaanthony** [comment]
Sounds like your `~/.wails/wails.json` file is corrupt. Have you checked it?

**Comment by ZSCodes** [comment]
> Sounds like your `~/.wails/wails.json` file is corrupt. Have you checked it?

This file is empty, what should i fill in?

**Comment by leaanthony** [comment]
Delete the blank file and run `wails`

**Comment by ZSCodes** [comment]
> Delete the blank file and run `wails`

It works as expected after running "wails". Thanks!

**Comment by leaanthony** [comment]
@ZSCodes Any feedback? You closed this then reopened?
