### ISSUE TITLE
App only shows in bridge mode

### ISSUE THREAD

**Issue by kmuchmore** [wailsapp/wails#518]
**Description**

When I run using wails serve and npm run serve, The app shows up on localhost:8080 just fine, but when I do a wails build and run the resulting executable, I get a window with some html text but no application running.

**To Reproduce**
Steps to reproduce the behaviour:
1. clone https://github.com/kmuchmore/wails_vue3_setup
2. navigate to the frontend directory and run `npm install`
3. run `npm run serve`
4. in another terminal run `wails serve` in the wails_vue3_setup directory
5. Goto localhost:8080 see that the webpage is there
6. Run `wails build`
7. run the compiled executable, see a windows with some html text and not the webpage expected.

**Expected behaviour**
The window should show the same as what you see when running `wails serve`

**Screenshots**
This is the window that shows up when running using `wails build`:
![image](https://user-images.githubusercontent.com/5316736/94729267-a5c53880-031e-11eb-8862-788896ea3df2.png)

This is what shows up when running the same code via `wails serve` and `npm run serve` on localhost:8080
<img width="965" alt="image" src="https://user-images.githubusercontent.com/5316736/94729588-1ec49000-031f-11eb-8618-fbadc51b4d15.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 11.0.3 |
| Npm           | 6.14.8 |
| Node          | v14.12.0 |

**Additional context**

**Comment by leaanthony** [comment]
It's an issue with the router. If you change:

```
const router = createRouter({
  history: createWebHistory(),
  routes
})
```
for:
```
const router = createRouter({
  history: createMemoryHistory(),
  routes
})
```

you get this:

![image](https://user-images.githubusercontent.com/1943904/94751257-6ef92c00-03cb-11eb-9a00-cf1f64ac6f90.png)

and navigation works as expected 👍

**Comment by tmclane** [comment]
Good catch!

**Comment by kmuchmore** [comment]
Thanks! That fixed it.
