### ISSUE TITLE
Cannot select Zip file on windows

### ISSUE THREAD

**Issue by shekharkhatri** [wailsapp/wails#519]
The native file selector opened using the runtime.Dialog.SelectFile() cannot select file with .zip extension in windows. The dialog treats the zip archive as directory and enters into it. Seems to be an issue with how windows handle zip files but can we get its path by selecting the file?

**Comment by leaanthony** [comment]
That's curious. I'll check it out tomorrow.

**Comment by shekharkhatri** [comment]
@leaanthony  Did you go through the issue ?

**Comment by leaanthony** [comment]
No time yet. Will try and find time tonight.

**Comment by leaanthony** [comment]
Can confirm this is an issue. For me it just goes "into" the zip as if it were a directory. Looking at webview, it uses the options [here](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) for the dialog. I can't see anything that might prevent this as it appears to be happening at the shell level. Looks like supporting this is [insanely more difficult](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) than it should be...

**Comment by shekharkhatri** [comment]
Yes! that's exactly what is happening.

**Comment by leaanthony** [comment]
I don't think it's possible for us to fix this as it's Windows default behaviour. It totally sucks though! I can't find any way of doing it. If you do, please let us know as I'd like to get this in!

**Comment by leaanthony** [comment]
@shekharkhatri - just discovered that https://github.com/sqweek/dialog has a fix for this and you can use it with Wails. Hope that helps!
