### ISSUE TITLE
wails is not defined for events management

### ISSUE THREAD

**Issue by fedyfausto** [wailsapp/wails#520]
Hello guys| I'm trying to use wails to make a small desktop application and i'm using Vue framework. Acutally i'm going to manage an event on mounted component but the application does not work (and some time even the build!) and says that 

```
16:5  error  'wails' is not defined  no-undef
```

some help?

JS code:
```js
 mounted: function() {
    wails.events.on("message", message => {
        if (cpu_usage) {
            message.log(message);
        }
    });
```

**Comment by leaanthony** [comment]
Try wails.Events.On. Case matters in JS land 😃

**Comment by fedyfausto** [comment]
But the problem is that wails object is undefined





Il giorno 5 ott 2020, alle ore 21:16, Lea Anthony <notifications@github.com> ha scritto:

﻿

Try wails.Events.On. Case matters in JS land 😃

**Comment by leaanthony** [comment]
Maybe provide more information like a link to your project. Is this at runtime/compile time? Did you wrap your code in the `Init()` command callback? The `wails` object exists on `window`. Did you update your webpack to not allow accessing `window`?

**Comment by fedyfausto** [comment]
ah ok thanks!, resolved!
