### ISSUE TITLE
Blank white screen in win7

### ISSUE THREAD

**Issue by cshmam** [wailsapp/wails#524]
**Description**

Displays blank white screen when running application in Windows 7. Displays correctly in browser when running "wails serve" and "npm run serve" mode. Move the application on Win10  machine and run it, everything is OK. So why?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.14.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 6.9.0 |
| Node          | v10.16.3
 |

**Additional context**

**Comment by leaanthony** [comment]
Does the initial template work? What did you add to it?

**Comment by cshmam** [comment]
Yes, in order to make sure it's not the application mistake, I also verified with the initial templates both Vue and React .

**Comment by leaanthony** [comment]
All I can say is that we only verify Wails works on Windows 10 as 7 is EOL. I have no access to Win 7 so this may never be fixed.

**Comment by leaanthony** [comment]
I think Windows 7 may be IE9 only. Please read [this](https://wails.app/guides/windows) and apply it to IE9. This may help you resolve the issue.
