### ISSUE TITLE
Iframe is not supported

### ISSUE THREAD

**Issue by hashwing** [wailsapp/wails#525]
**Description**
Iframe is not supported

**To Reproduce**

```html
<iframe
    id="bdIframe"
      ref="iframe"
      frameborder="0"
      style="width:100%;height:100%;" 
      src="https://embed.diagrams.net/?embed=1&spin=1&modified=unsavedChanges&proto=json"
    ></iframe>
```

**Expected behaviour**
Support Iframe

**Screenshots**

**System Details**
System: win10
Go: 1.14.5

**Additional context**

**Comment by leaanthony** [comment]
Wails isn't really designed for using external content or iframes. What error do you see?

**Comment by hashwing** [comment]
> Wails isn't really designed for using external content or iframes. What error do you see?

After compiling, there are no errors and the page is blank. Debugging in the browser works

**Comment by leaanthony** [comment]
@hashwing please check that it's actually the iframe causing this issue. There's a ton of reason on Windows why it might be failing. I'll also have a quick look at it tonight but debugging on windows is pretty hard!

**Comment by leaanthony** [comment]
FYI I've added a `-firebug` flag that might help you debug this. I believe it's a security policy that would need to be set but haven't confirmed yet

**Comment by hashwing** [comment]
> @hashwing please check that it's actually the iframe causing this issue. There's a ton of reason on Windows why it might be failing. I'll also have a quick look at it tonight but debugging on windows is pretty hard!

Thank you. How can I debug it
