### ISSUE TITLE
Support Buefy framework (based on Bulma)

### ISSUE THREAD

**Issue by maxiride** [wailsapp/wails#529]
This is a feature request to add [Buefy ](https://github.com/buefy/buefy) (Bulma) to the wails cli available choices when creating a new project.

I honestly recognize it's a minor improvement but would add a bit of quality of life when starting new projects.

**Miss clicked and chose the Bug report instead of a blank issue, sorry for the wrong labelling**

**Comment by leaanthony** [comment]
Happy to accept a PR for this

**Comment by maxiride** [comment]
> 
> 
> Happy to accept a PR for this

Will gladly do if I can work my way around it!

Do I just need to work on a new template based on the ones [here](https://github.com/wailsapp/wails/tree/master/cmd/templates) or additional work is needed to have it incorporated in the cli?

**Comment by leaanthony** [comment]
You can do that. there's also this https://wails.app/development/#tooling

**Comment by leaanthony** [comment]
@maxiride - How's it going? We just got a [Vue 3 template](https://github.com/wailsapp/wails/pull/522) that you might like to review.

**Comment by maxiride** [comment]
> 
> 
> @maxiride - How's it going? We just got a [Vue 3 template](https://github.com/wailsapp/wails/pull/522) that you might like to review.

I've been very busy re-planning an application due to #531, me and my team are now discussing whether to delve into native desktop app development, Flutter or stick with the codebase we have and refactor it to take in account IE 11 **heavy** limitations.

Anyway I'm still interested in Wails and will add a Buefy template for personal projects later on, the Vue 3 template is a very appreciated addition!

**Comment by leaanthony** [comment]
Not including a browser has pros and cons for sure. I'll ping you when v2 is done. Good luck! 👍
