### ISSUE TITLE
HTML5 <input type="data"> becomes a normal text input after build

### ISSUE THREAD

**Issue by maxiride** [wailsapp/wails#531]
**Description**

When using `<input type="data">` the application shown in development with` wails serve` correctly presents the date input field. After building the application with `wails build` the input field is shown as a normal text input.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new basic Vue Project (wails init -> option 5)
1. Insert a date input field: `<input type="data">`
1. Run the application in development mode with `wails serve` for the backend and `npm run serve` for the frontend
1. See that the rendered application in the browser shows correctly the date input, clicking it opens the calendar
1. Run `wails build` to build the executable
1. Run executable and see that the date input field is a normal text input and no calendar is opened

**Expected behaviour**
On the built executable, when clicking the date input field I expected to be presented with a calendar to choose the date from.

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.3 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.19.0
 |

**Additional context**
I haven't tested other input types but will do.

**Comment by leaanthony** [comment]
It appears IE11 [doesn't support this](https://caniuse.com/input-datetime). I would suggest using a different solution for Windows.

**Comment by maxiride** [comment]
> 
> 
> It appears IE11 [doesn't support this](https://caniuse.com/input-datetime). I would suggest using a different solution for Windows.

Is this a webview limitation or can I change something on the computer to solve it?

**Comment by Rezrazi** [comment]
> > It appears IE11 [doesn't support this](https://caniuse.com/input-datetime). I would suggest using a different solution for Windows.
> 
> Is this a webview limitation or can I change something on the computer to solve it? E.g. use Chrome webwiew?

It is a webview limitation, you can start by looking into polyfills and shims for that feature, or a replacement, I would suggest [jQuery's Datepicker ](https://jqueryui.com/datepicker/) or any IE11-compatible datetime input

**Comment by leaanthony** [comment]
I'm adding a Windows Development Guide to the docs and will add this information.  Thanks

**Comment by leaanthony** [comment]
[Guide](https://wails.app/guide/windows) created and additional information now output to command line when running build/serve on Windows (v1.8.1-pre2). Closing this.
