### ISSUE TITLE
The default Vuetify based preset build doesn't render anything, but the serve command works in browser

### ISSUE THREAD

**Issue by aayush420** [wailsapp/wails#534]
**Description**

I tried to create a new Vuetify2 app from the wails command, but it is not working. The same works if I just run the serve command instead of build. To check if it's a problem with my desktop, I've tried the vue config and vanilla configs too and they work just fine. Only the Vuetify one doesn't.

**To Reproduce**
1. Run `wails init`.
2. Select `7` to use the vuetify config.
3. Let wails create the app.
4. Build the frontend by running `npm run build` inside the frontend folder.
5. Build the main application by running `wails build` in the root folder of the application to build the application.
6. Run the application and it won't run.

**Expected behaviour**
The default Vuetify preset application should be up and running.

**Screenshots**
![Empty image with any GUI components](https://user-images.githubusercontent.com/16898783/97082888-7efed700-162a-11eb-8e1c-57982fe0e2fb.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.2.0 |
| Npm           | 6.14.7 |
| Node          | v12.19.0 |

**Comment by leaanthony** [comment]
Thanks for this. Will investigate this regression 👍

**Comment by aayush420** [comment]
Hey, Sorry about that. It was a driver error from my end. GLX extension had some issues because of the display drivers (from Nvidia as always). Got it working after fixing the drivers. 
![Working version](https://user-images.githubusercontent.com/16898783/97100129-3db40900-16b6-11eb-9cd6-341b687cdfcc.png)

**Comment by leaanthony** [comment]
Thanks for letting us know! Glad it was sorted for you.
