### ISSUE TITLE
Windows 10 after build error

### ISSUE THREAD

**Issue by smxgit** [wailsapp/wails#540]
**Description**

Hello, 
I have a problem with my application under Wails.app.
When I start the application, I get an error: 
impossible to get the "_" property of a null or undefined reference.

I'm on windows 10 insider preview. I only have Edge Chromium.
### __I used ReactJs.__

No problem with wails serve.

**Screenshots**

![image](https://user-images.githubusercontent.com/26999116/97195781-04f65b80-17ac-11eb-8a08-08d9ce5ce327.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.3 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.2.0 |
| Npm           | 7.0.3 |
| Node          | v15.0.1
 |

**Comment by leaanthony** [comment]
Do the regular templates work?

**Comment by Olprog59** [comment]
> Do the regular templates work?

Yes. Wails serve and npm run start works correctly.

**Comment by leaanthony** [comment]
So this is an error with your application not Wails?

**Comment by Olprog59** [comment]
> So this is an error with your application not Wails?

My application compile in macOs without problems (wails build && wails build -p) but with windows I have this error.

Sorry for my English.

**Comment by Rezrazi** [comment]
This looks like a webview/IE11 compatibility issue, are you using any library or package in your React project ? If you are, you should be looking at including polyfills like [react-app-polyfill](https://www.npmjs.com/package/react-app-polyfill) or [core-js](https://www.npmjs.com/package/core-js) and ensuring the packages or libraries you're using are compatible with IE11.

To help you determine if your app is compatible, I would recommend running `wails serve` and `yarn start` and browsing your app with IE11. If your Windows build doesn't have it already, you can download it manually [here](https://www.microsoft.com/en-us/download/details.aspx?id=41628)

**Comment by Olprog59** [comment]
@Rezrazi 

> This looks like a webview/IE11 compatibility issue, are you using any library or package in your React project ? If you are, you should be looking at including polyfills like [react-app-polyfill](https://www.npmjs.com/package/react-app-polyfill) or [core-js](https://www.npmjs.com/package/core-js) and ensuring the packages or libraries you're using are compatible with IE11.
> 
> To help you determine if your app is compatible, I would recommend running `wails serve` and `yarn start` and browsing your app with IE11. If your Windows build doesn't have it already, you can download it manually [here](https://www.microsoft.com/en-us/download/details.aspx?id=41628)



I had indeed not checked on IE 11. So I adapted React JS for IE 11. 
The problem still persists.

```
...
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1603816862:9879 []}" type=event
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Processing message" 1D=0xc000098018
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1603816862:9879"
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1603816862:9879"
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Finished processing message" 1D=0xc000098018
time="2020-10-27T17:41:02+01:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1603816862:9879"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] Eval" js="window.wails._.Notify('syncjs:1603816862:9879..."
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1603816862:9879"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] Inject User CSS" css="body{font-family:-apple-system,BlinkMacSystem"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] Inject User JS" js="!function(e){var t={};function n(r){if(t[r])r"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] EvalSync" js="!function(e){var t={};function n(r){if(t[r])r..."
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1603816862:4574"
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1603816862:4574 []}" type=event
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Processing message" 1D=0xc0004ae000
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1603816862:4574"
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1603816862:4574"
time="2020-10-27T17:41:02+01:00" level=debug msg="[IPC] Finished processing message" 1D=0xc0004ae000
time="2020-10-27T17:41:02+01:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1603816862:4574"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] Eval" js="window.wails._.Notify('syncjs:1603816862:4574..."
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1603816862:4574"
time="2020-10-27T17:41:02+01:00" level=debug msg="[Events] Got Event" data="[]" name="wails:ready"
time="2020-10-27T17:41:02+01:00" level=debug msg="[WebView] Eval" js="window.wails._.Notify('wails:ready',\"null\")"
```

**Comment by Rezrazi** [comment]
This is most likely a IE11 compatibility issue still.

Does your app render in IE11 with wails serve ?

**Comment by leaanthony** [comment]
Try building with `wails build -d -firebug` to debug this.

**Comment by leaanthony** [comment]
Did you fix it?

**Comment by Olprog59** [comment]
@leaanthony 
> Did you fix it?

No. I change the solution.
