### ISSUE TITLE
Can not load modified or custom index.html

### ISSUE THREAD

**Issue by ucokfm** [wailsapp/wails#542]
**Description**

wails build always use html content from runtime/assets/default.html
even though we set HTML field in AppConfig to a modified index.html or custom html file

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init
2. select Vanilla template
3. edit frontend/src/index.html
4. edit main.go
```
	html := mewn.String("./frontend/build/index.html")
	js := mewn.String("./frontend/build/main.js")
	css := mewn.String("./frontend/build/main.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 768,
		Title:  "Hello World",
		HTML:   html,
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})
```
5. wails build

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.2.0 |
| Npm           | 6.14.7 |
| Node          | v14.12.0 |

**Comment by leaanthony** [comment]
Nice find.

**Comment by leaanthony** [comment]
Fixed by #545 
Will be in next -pre release

**Comment by leaanthony** [comment]
Re-opening - I had to revert the commit for this. Will look at addressing it ASAP.

**Comment by leaanthony** [comment]
I have pushed a fix for this in the latest -pre release. Could you please check this works for you? Install with `wails update -pre`. Thanks :+1:

**Comment by leaanthony** [comment]
Also be aware that in your example you are referencing `build/index.html` which gets overwritten each build. Reference `src/index.html` instead.

**Comment by ucokfm** [comment]
Yes, it's working perfectly now!
My use case is i need to change root element id from <div id="app"> to <div id="root"> because i use some js library (out of my control) that strictly need it. As long the build process is always copying from src/index.html to build/index.html i think it still fine to refer any one of them.
Thank you so much for this quick fix.

**Comment by leaanthony** [comment]
Perfect! I'm really glad it works!
