### ISSUE TITLE
build failed in win7-32bit

### ISSUE THREAD

**Issue by ohmydevops** [wailsapp/wails#548]
**Description**

when try to build my project in win7-32bit, i get this error:

**build**:
 GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g   wails build -d -ldflags "-H windowsgui"

**results**: 
Wails v1.9.1 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
| Ensuring Dependencies are up to date...# healthcheck-sample
c:\go\pkg\tool\windows_386\link.exe: running i686-w64-mingw32-gcc failed: exit status 1
C:\Users\AMIRBA~1\AppData\Local\Temp\go-link-859609503\000000.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Processing template and preparing for upload.
Opening browser to file issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.9.1 |
| Go Version    | go1.15.3 |
| Platform      | windows |
| Arch          | 386 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.19.0
 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by amirbagh75** [comment]
This issue was repeated twice. please delete this @leaanthony
