### ISSUE TITLE
build fail in win7-32bit

### ISSUE THREAD

**Issue by ohmydevops** [wailsapp/wails#549]
**Description**

when i try to build my project in win7-32bit, i got this error:

> Wails v1.9.1 - Building Application
> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
| Ensuring Dependencies are up to date...# healthcheck-sample
c:\go\pkg\tool\windows_386\link.exe: running i686-w64-mingw32-gcc failed: exit status 1
C:\Users\AMIRBA~1\AppData\Local\Temp\go-link-859609503\000000.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status

it's working on linux (mint 20 64bit - ubuntu 20 64bit - popOs 64bit) like a charm.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to my project dir
2. run ```GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g   wails build -d -ldflags "-H windowsgui"```
3. See error

**Expected behaviour**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.9.1 |
| Go Version    | go1.15.3 |
| Platform      | windows |
| Arch          | 386 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.19.0

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Looks like you're using a 64bit compiler

**Comment by leaanthony** [comment]
i should also mention that those environment variables aren't necessary. if you NEED them, we could look at supporting them.

**Comment by amirbagh75** [comment]
i create another project with `wail init + vue2`
then build with this commands:

```
amirbagh75@amirbagh75-PC MINGW32 ~/Desktop/my-project
$ wails build
Wails v1.9.1 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
- Ensuring Dependencies are up to date...# my-project
c:\go\pkg\tool\windows_386\link.exe: running gcc failed: exit status 1
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\AMIRBA~1\AppData\Local\Temp\go-link-035274055\000001.o: in function `snprintf':
C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdio.h:890: undefined reference to `__ms_vsnprintf'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\AMIRBA~1\AppData\Local\Temp\go-link-035274055\000001.o: in function `iid_eq':
C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:629: undefined reference to `IID_IDocHostUIHandler'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:629: undefined reference to `IID_IDocHostUIHandler'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:629: undefined reference to `IID_IDocHostUIHandler'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:629: undefined reference to `IID_IDocHostUIHandler'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\AMIRBA~1\AppData\Local\Temp\go-link-035274055\000001.o: in function `webview_dialog':
C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:1832: undefined reference to `IID_IFileSaveDialog'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:1832: undefined reference to `CLSID_FileSaveDialog'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:1815: undefined reference to `IID_IFileOpenDialog'
c:/tdm-gcc-32/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:/Users/amirbagh75/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.h:1815: undefined reference to `CLSID_FileOpenDialog'
collect2.exe: error: ld returned 1 exit status



! Ensuring Dependencies are up to date...
Error: exit status 2
```

**Comment by leaanthony** [comment]
Is this Windows 7?

**Comment by amirbagh75** [comment]
win7 32bit

**Comment by leaanthony** [comment]
I'm not sure that we can support windows 7. I certainly can't test that, but will help where I can.
