### ISSUE TITLE
Ubuntu 20.04 confirm & alert title 

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#550]
**Description**

On ubuntu 20.04 (gnome) alert and confirm dialogs have a long data:text/html as a title, I remember this worked nicely in the past and then it broke, but I don't remember on what version. (I used a modal instead.)

I tired to figure out the problem but had no luck, probably GTK wants to show the page's url and that is what it finds.

On windows the app is all kinds of broken, but the dialogs are working fine. :D

**To Reproduce**
Steps to reproduce the behaviour:
1. Init a new Vanilla template
2. Throw a confirm or an alert dialog
4. See the title

**Expected behaviour**
See  a dialog that fits in the window.

**Screenshots**
![Screenshot from 2020-11-06 00-00-53](https://user-images.githubusercontent.com/8627125/98305991-2aad0d00-1fc3-11eb-9208-36dc1b3d7438.png)

![Screenshot from 2020-11-06 00-32-48](https://user-images.githubusercontent.com/8627125/98308137-ab6e0800-1fc7-11eb-8ab8-7d3f5ba2ee72.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.9.1 |
| Go Version    | go1.15.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.3.0 |
| Npm           | 6.14.8 |
| Node          | v14.15.0 |

**Comment by leaanthony** [comment]
Apologies for the slow response on this! It appears to be a security feature of GTK to show the URL in the alert title. This is why it's showing the data-uri. This isn't something we can fix, though we could override window.alert with a custom one, but then you get into the tricky world of styling. I guess the official recommendation is just to not use it as there isn't anything we can do about it.
