### ISSUE TITLE
Is there a way to reload golang code without restarting wails serve ?

### ISSUE THREAD

**Issue by chenhl05** [wailsapp/wails#552]
After fixed golang code , I'm always frustrated while stoping "wails serve" , starting "wails serve". 

Does it has a better way to reload bankend program while file changing?

**Comment by leaanthony** [comment]
This is available for v2 but it.s not ready yet. If I get time, I'll try and backport it to v1

**Comment by chenhl05** [comment]
I'm very glad to hear that.I hope to use v2 soon.
By the way, can I debug the golang program while "wails serve"?

**Comment by leaanthony** [comment]
You should be able to. I will test and update the docs regarding debugging

**Comment by leaanthony** [comment]
@chenhl05 - Updated the docs on debugging in vscode, if that's useful to you: https://wails.app/guides/debugging/#debugging-using-visual-studio-code

**Comment by chenhl05** [comment]
Thank you very much.
