### ISSUE TITLE
feature request: http proxy

### ISSUE THREAD

**Issue by obito** [wailsapp/wails#557]
**Is your feature request related to a problem? Please describe.**
I want to create a captcha harvester, however, Google is blocking me to do captcha on localhost. I would like to setup a proxy, so I could tell Google that I'm on the website that I want to harvester for.

**Describe the solution you'd like**

Alternative at either `protocol.registerBufferProtocol` or `win.webContents.session.setProxy` in Electron.

**Describe alternatives you've considered**

Spawning Google Chrome window with the parameter --proxy-server.

**Additional context**
You can see what a Captcha Harvester is:
* https://github.com/TheLastTech/NodeJSCaptchaHarvestTime/ (registerBufferProtocol method)
* https://github.com/dzt/captcha-harvester (setProxy method)

**Comment by leaanthony** [comment]
Hi. There's no reason you couldn't do this in Go and send the results back to the frontend. That way, you could take advantage of the many proxy libraries available to you.

**Comment by obito** [comment]
> Hi. There's no reason you couldn't do this in Go and send the results back to the frontend. That way, you could take advantage of the many proxy libraries available to you.

Hi. Thanks for your response, but I don't really see how can I send the result back to the frontend as it needs rendering the ReCaptcha in JS.

**Comment by leaanthony** [comment]
I guess I don't understand the problem enough to be able to help you out. Currently there's no proxy for the JS side. I'm not even sure how that would work right now. Could you give me more info?
