### ISSUE TITLE
Support Distribution 'EndeavourOS'

### ISSUE THREAD

**Issue by turkturk2x** [wailsapp/wails#561]
**Description**
Distribution 'endeavouros' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.1 |
| Go Version    | go1.15.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | endeavouros |
| Distribution Name   | EndeavourOS |
| Distribution Version   |  |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
I believe that treating it as Arch would work?

**Comment by leaanthony** [comment]
Just pushed what I think will support EndeavourOS. Please try using version v1.10.2-pre: `wails update -pre`

**Comment by leaanthony** [comment]
This is now supported in v1.10.0. Closing.
