### ISSUE TITLE
win 10   github.com/wailsapp/wails/lib/renderer/webview

### ISSUE THREAD

**Issue by YLQZ** [wailsapp/wails#562]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
1. new  init APP，
2.use vue2 select ， 
3.editor ： goland ，
4.active： just click run button
5. wails  -v  1.9.1
    go   -v   1.15
    gcc    tdm-gcc  -v  9.2.0

# github.com/wailsapp/wails/lib/renderer/webview
In file included from webview.go:26,
                 from _cgo_export.c:4:
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h: In function 'JS_GetIDsOfNames':
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:668:9: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
  668 |     if (wcscmp(rgszNames[0], L"invoke") == 0)
      |         ^~~~~~
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h: In function 'webview_dialog':
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:1848:28: warning: implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Wimplicit-function-declaration]
 1848 |         char* filter_dup = strdup(filter);
      |                            ^~~~~~
      |                            strcmp
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:1848:28: warning: initialization of 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
# github.com/wailsapp/wails/lib/renderer/webview
In file included from E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview\webview.go:26:
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h: In function 'JS_GetIDsOfNames':
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:668:9: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
  668 |     if (wcscmp(rgszNames[0], L"invoke") == 0)
      |         ^~~~~~
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h: In function 'webview_dialog':
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:1848:28: warning: implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Wimplicit-function-declaration]
 1848 |         char* filter_dup = strdup(filter);
      |                            ^~~~~~
      |                            strcmp
E:\GoPath\pkg\mod\github.com\wailsapp\wails@v1.9.1\lib\renderer\webview/webview.h:1848:28: warning: initialization of 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
C:\Users\Administrator\AppData\Local\Temp\___go_build_dockerview.exe #gosetup

进程完成，并显示退出代码 0

**Comment by leaanthony** [comment]
Using "Run" in GoLand is not supported. The only supported way is to compile using "wails build". If GoLand supports pre-run commands then I suggest that approach.
