### ISSUE TITLE
Windows Pro (ver 2004) creating 16-bit executables

### ISSUE THREAD

**Issue by gardc** [wailsapp/wails#564]
**Description**

Processor is a x64 processor. TDM-GCC is installed and added to path. Ran `wails init` and `wails build`. The built executable is not working, where I get a message 'This app cant run on your PC. To find a version for your PC, check with the software publisher'. 
Running with PowerShell, the error is: 'Program 'testing.exe' failed to run: The specified executable is not a valid application for this OS platform'. 
Building and running with cmd.exe brings up a dialog saying it is incompatible, and is a 16-bit binary! Screenshot: https://i.imgur.com/IFMN8nk.png

**To Reproduce**
Steps to reproduce the behaviour:
1. Wails init. Select React JS preset (option 2).
2. Wails build.
3. Run produced binary.

**Expected behaviour**
The binary to work, showing react template application.

**Screenshots**
https://i.imgur.com/IFMN8nk.png

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.9.1 |
| Go Version    | go1.15.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 9.2.0 |
| Npm           | 6.14.8 |
| Node          | v14.15.1
 |

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
I'm pretty certain this isn't a Wails issue. Funnily enough I saw a thread on reddit where someone was saying the same thing about Go in general.

**Comment by leaanthony** [comment]
https://www.reddit.com/r/golang/comments/jzu9us/im_building_an_executable_for_windows_and_it_says/

**Comment by gardc** [comment]
Ok I tried to build with `go build main.go` directly, and I got this error: 
```
> go build .\main.go
# command-line-arguments
.\main.go:21:13: undefined: Counter
```
I created a directory called stuff and moved counter.go in there, added reference to it in main.go, compiled with `go build main.go` and this is the result when I run main.exe: 
https://i.imgur.com/HCwUTIz.png
An empty window, but at least it runs and isn't saying it's 16-bit. Trying again with wails build fixes nothing.

**Comment by leaanthony** [comment]
Hi. I'm glad you fixed your build issues. 

WRT the blank screen, that's covered in the docs [here](https://wails.app/guides/windows/#my-app-is-starting-but-im-just-getting-a-blank-screen).

If you have any Wails related issues, or general questions, feel free to open a new ticket. Good luck! :+1:
