### ISSUE TITLE
wails build & wails serve assume that they're being called from module root

### ISSUE THREAD

**Issue by bitterlox** [wailsapp/wails#566]
**Is your feature request related to a problem? Please describe.**
I'm working on a project where the wails app is just part of the project, the other being a server component that communicates with the GUI over gRPC. For ease of development i have everything inside a single go module/repo, with respective main.go files under cmd/

**Describe the solution you'd like**
It would be nice to tell wails where it can find all the files it needs. At the moment it seems like project.json tells wails where to find the frontend, but otherwise there are no flags to pass to `wails` for example to specify an output path (which is fixed to build/`execName`) or to specify where the module root is

**Describe alternatives you've considered**
The way that i can make it work is have a makefile target that moves main.go and project.json to the module root temporarily to build the exec or serve and then cleans up when it's done, but it seems a bit hacky.

**Additional context**
[repo](https://github.com/bitterlox/tradepanel) for context

**Comment by leaanthony** [comment]
Right now that is indeed a limitation. What do you think the ideal solution looks like? If you can provide some examples, I'd be open to adding this to v2.

**Comment by bitterlox** [comment]
I would say the easiest solution would be to add some extra config fields to project.json (a field to specify go.mod location/module root and a field for application entry point e.g main.go or a `main` package) and additionally add two flags to the wails command, one to specify the location of project.json (so you don't have to run in from the same directory), another (optional) to specify the path where the built executable should be placed.
What do you think?

**Comment by bitterlox** [comment]
I went ahead and coded it in, not sure if i used the right branch. I noticed though that with this code all the relative paths specified in project.json and main.go (like paths passed to mewn) would need to be adjusted if wails is being run with `-c` or `MainPackage` option.
let me know what you think, if it's necessary i can try to fix the paths thing as well.

**Comment by leaanthony** [comment]
Thanks for doing this! This is great! Feel free to try to fix the paths and let us know what combinations of platforms/build types you've tested. Cheers.

**Comment by leaanthony** [comment]
Don't close

**Comment by leaanthony** [comment]
stalest - schtaaap!!

**Comment by leaanthony** [comment]
@bitterlox - Just revisiting this. Daft question: Is there any reason you can't `cd <project root>; wails build; cd -`?

**Comment by bitterlox** [comment]
Since my wails app was mixed in with other go code that wouldn't have worked. Basically I thought this way you can have your code and your assets wherever inside a project and you just tell wails where to find it all and it builds it

**Comment by bitterlox** [comment]
Mixed in with other go code as in, a build had to produce multiple binaries, for example a normal go bin for a server component, and a wails bin for a client component. I realize it might be kind of a niche use-case, but i thought that the project could benefit from more customizability.

**Comment by leaanthony** [comment]
How does that approach compare to how we've done it in [xbar](https://github.com/matryer/xbar)?

**Comment by bitterlox** [comment]
In xbar you have the wails app in a subdirectory as a standalone go project, where you can just cd into it and go build, what i had was a go project directory that instead of having a main.go in the project root, have multiple main.go files under `cmd/binaryName/` that would result in different stuff being built, e.g. one was the wails frontend the other a cli meant to be run on a server

**Comment by leaanthony** [comment]
Schtaap

**Comment by leaanthony** [comment]
@bitterlox I'm going to kick this over to v2 if that's ok

**Comment by bitterlox** [comment]
Sounds good
