### ISSUE TITLE
wails init fails

### ISSUE THREAD

**Issue by hookenz** [wailsapp/wails#567]
**Description**
Installed wails for the first time on windows machine.  Ran wails init and it failed

**To Reproduce**
````
C:\Users\Matt\dev\wailstest>wails init
...
The name of the project (My Project): wailstest
Project Name: wailstest
The output binary name (wailstest):
Output binary Name: wailstest
Project directory name (wailstest):  
Project Directory: wailstest
Please select a template (* means unsupported on current platform):
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v4 template
  3: Svelte - A basic Svelte template
  4: Vanilla - A Vanilla HTML/JS template
  5: * Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
  6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 3
Template: Svelte
> Generating project...
\ Building project (this may take a while)...
Wails v1.8.1 - Building Application

> Ensuring frontend dependencies are up to date (This may take a while)
> Building frontend...
/ Ensuring Dependencies are up to date...go: github.com/wailsapp/wails@v1.8.1: reading github.com/wailsapp/wails/go.mod at revision v1.8.1: unknown revision v1.8.1


! Ensuring Dependencies are up to date...
Error: exit status 1

! exit status 1
Error: exit status 1
````

**Expected behaviour**
It should have produced a suitable starter project but didn't

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.1 |
| Go Version    | go1.15.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.9.0 |
| Node          | v10.16.3
 |

**Additional context**
None

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi. For whatever reason, the tagging of that version messed up and it looks like the cached version is corrupted. Fortunately, there's newer versions so please try `wails update`.

**Comment by hookenz** [comment]
> Hi. For whatever reason, the tagging of that version messed up and it looks like the cached version is corrupted. Fortunately, there's newer versions so please try `wails update`.

Thanks seems to have fixed it.  Why didn't it fetch the latest version at the beginning?

**Comment by leaanthony** [comment]
What do you mean? It installs the latest for me:
```
lea@192-168-1-105 /tmp % go get github.com/wailsapp/wails/cmd/wails
go: found github.com/wailsapp/wails/cmd/wails in github.com/wailsapp/wails v1.9.1
```

**Comment by hookenz** [comment]
After go get.   First time I'd ever tried it.   Might have been a go get anomaly.  Thanks for replying

**Comment by jozsefsallai** [comment]
I'd like to clarify that `go get` installed v1.8.1 for me too, however when checking the tags in the downloaded repo, v1.9.1 is also there:

```
joe@jabberwocky ~/g/s/g/w/wails (master)> git describe --tags
v1.8.0-16-g0c2c56e
joe@jabberwocky ~/g/s/g/w/wails (master)> git tag | tail -1
v1.9.1
```

Really weird, considering that https://proxy.golang.org/github.com/wailsapp/wails/@v/list also lists v1.9.1 as latest.

go get is often incredibly weird when it comes to versioning

**Comment by leaanthony** [comment]
Thanks for that insight @jozsefsallai ! There was a bug a while back with the Semver package from masterminds which messed up after a .9 minor version but I don't think that's it.
