### ISSUE TITLE
Error: open $(PWD)/../runtime/assets/bridge.js: no such file or directory

### ISSUE THREAD

**Issue by abenelazar** [wailsapp/wails#578]
**Description**

Directory open is relative toprocess, not file in `vendor/github.com/wailsapp/wails/cmd/cmd-mewn.go`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to project root
2. Run `wails build -d` or `wails serve`
3. See error

**Expected behaviour**
Wails does not successfully build

**Screenshots**
<img width="879" alt="Screen Shot 2020-12-18 at 10 27 23 AM" src="https://user-images.githubusercontent.com/4948431/102631514-d34ea080-411b-11eb-8b37-8d4c09321df7.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.10.1 |
| Go Version    | go1.14.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.0 |
| Npm           | 6.14.4 |
| Node          | v14.2.0 |

**Additional context**
I am using go mod vendor to manage dependencies.

It seems that the process is trying to open the file from the process' location, not relative to the file's location 

This is also a weird bug because the project works for a short while, then after a few starts/stops on Wails, it totally stops working.

My strategy so far has been creating a new project and moving my files over into it.

**Comment by leaanthony** [comment]
We don't support vendoring right now. Whatever the solution to this will also need to work in the docker builds too. The build system expects it to have been installed via go modules and uses paths relative to it. There's no assumptions on locations other than the build is started in the project directory.

**Comment by abenelazar** [comment]
Ok, makes sense! I was using vendoring, and now that I'm not, it works so I'm going to close this issue out.

**Comment by ldnvnbl** [comment]
I have seem issue, why don't support go mod vendor ? @leaanthony

**Comment by leaanthony** [comment]
If you make a PR, we can support it!
