### ISSUE TITLE
How to solve the wails installation

### ISSUE THREAD

**Issue by nethmiwijebandara** [wailsapp/wails#579]
I'm new to Go. I try to develop a wail app. First of all I tried to install wails using:

 `go get github.com/wailsapp/wails/cmd/wails`

But it gives the following error. 

    # cd C:\Users\...\go\src\github.com\wailsapp\wails; git pull --ff-only
    There is no tracking information for the current branch.
    Please specify which branch you want to merge with.
    See git-pull(1) for details.
    
        git pull <remote> <branch>
    
    If you wish to set tracking information for this branch you can do so with:
    
        git branch --set-upstream-to=<remote>/<branch> master
    
    package github.com/wailsapp/wails/cmd/wails: exit status 1
    
 I tried with this [solution. ][1] But the I still have this issue.
  How can I solve this matter? Need your help. Thank you in advance. 

  [1]: https://stackoverflow.com/questions/33064343/go-get-git-error-on-all-sources-but-golang-org

**Comment by leaanthony** [comment]
Hi! This looks like some sort of local issue. What version of Go are you using?

**Comment by leaanthony** [comment]
@nethmiwijebandara - do you need any further help with this?
