### ISSUE TITLE
Tutorial todo app, chrome console error: Error in callback for watcher "todos": "TypeError: Cannot read property 'Log' of undefined"

### ISSUE THREAD

**Issue by darjun** [wailsapp/wails#580]
**Description**

follow the steps in todo app tutorial. in 'Saving the Todo List', chrome console shows this error.

**To Reproduce**
Steps to reproduce the behaviour:
1. wails serve
2. cd frontend && npm run serve
3. input some text then enter
4. chrome console shows error

**Expected behaviour**
backend console appear connection info.
![image](https://user-images.githubusercontent.com/18298106/103257210-3d443100-49cb-11eb-90f2-2358c0e4d40b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/18298106/103257229-4cc37a00-49cb-11eb-9065-b8ae20d99708.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.10.1 |
| Go Version    | go1.14 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.14.8 |
| Node          | v14.15.1|

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Are you missing the line `import Wails from '@wailsapp/runtime';`?

**Comment by darjun** [comment]
> Are you missing the line `import Wails from '@wailsapp/runtime';`?

![image](https://user-images.githubusercontent.com/18298106/103327742-cf623d00-4a90-11eb-8e0c-d9214640e2c6.png)

I have import the runtime. In the todo watch function, `console.log` shows:

![image](https://user-images.githubusercontent.com/18298106/103327834-397ae200-4a91-11eb-9a44-66608ad8438b.png)

but cannot call `Info` function.

**Comment by leaanthony** [comment]
That doesn't make much sense! How are you able to print it out but it be undefined on the very net line?

**Comment by darjun** [comment]
sorry, I forget to comment out the sentances in main.js
