### ISSUE TITLE
Question: Is not possible to open file dialog to select multiple files ?

### ISSUE THREAD

**Issue by dev-drprasad** [wailsapp/wails#584]
I only see option to select directory or select single file.  `Renderer` interface also doesn't have method like selectFiles

```
type Renderer interface {
	Initialise(AppConfig, IPCManager, EventManager) error
	Run() error

	// Binding
	NewBinding(bindingName string) error

	// Events
	NotifyEvent(eventData *messages.EventData) error

	// Dialog Runtime
	SelectFile(title string, filter string) string
	SelectDirectory() string
	SelectSaveFile(title string, filter string) string

	// Window Runtime
	SetColour(string) error
	Fullscreen()
	UnFullscreen()
	SetTitle(title string)
	Close()
}
```

Is it not implemented in wails or is not implemented in webview itself ?

**Comment by leaanthony** [comment]
It's not implemented in the version of webview we use. Implemented in v2.
If you want to create a PR for the bundled webview then please do so. It
will be gladlyreceived 👍

**Comment by leaanthony** [comment]
Also, some people have successfully used this with Wails: https://github.com/sqweek/dialog - Maybe that would help?

**Comment by dev-drprasad** [comment]
I will check that out.

I have raised PR. But I haven't tested. I never wrote C++ or C# (I wrote "hello world' once in C, though). If you have everything setup already for testing in different OSes, it would be great if you test it for me. Of course, I will try to build my changes and test it in my local machine also.

**Comment by leaanthony** [comment]
Closing this as you abandoned the PR :-)
