### ISSUE TITLE
Help determining the build mode

### ISSUE THREAD

**Issue by Jab2870** [wailsapp/wails#588]
Hi,

I am pretty new to GoLang so my apologies if this is an obvious question.

How can I detect the buildmode at runtime? I have seen from previous issues that
the file selector doesn't work when in bridge mode. When this is the case (when
I'm working on a feature) I'd like to automatically return a file I use for
testing. Is this possible?

Thanks in advance

Edit:

I basically want something like:

```
func (g *GUI) ChooseFile() string {
	if buildMode == "bridged" {
		return "/a/file/to/use/for/testing"
	} else {
		selectedFile := g.runtime.Dialog.SelectFile()
		return selectedFile
	}
}
```

**Comment by leaanthony** [comment]
Hi @Jab2870! That's a good question! There's a flag here just for this: https://github.com/wailsapp/wails/blob/master/app.go#L21 - it should be accessible using `wails.BuildMode` in your code.

**Comment by Jab2870** [comment]
Thanks very much. That is exactly what I was after.
