### ISSUE TITLE
wasm feature 

### ISSUE THREAD

**Issue by mostend** [wailsapp/wails#591]
This is just a feature proposal. Can we make wasm and wails work better?

Thank you.

**Comment by leaanthony** [comment]
Hi. What are you proposing exactly?

**Comment by waini1110** [comment]
sorry for that, I think of a better way to do it. I will close it .

**Comment by gedw99** [comment]
@leaanthony 

I would like to be able to run a WASM gui inside wails.

Even better is to serer the wasm from the server, and then if local server it local. 

The semantics i am looking for is like A2HS for a PWA in a browser, where the WASM will update via the Service Worker.
