### ISSUE TITLE
Support Distribution 'Red Hat Enterprise Linux'

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#596]
**Description**
Distribution 'rhel' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.14.12 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | rhel |
| Distribution Name   | Red Hat Enterprise Linux |
| Distribution Version   | 8.3 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
Sorry for the late response to this! Is there a way i can test this locally? Is RHEL available to all these days? A dockerised version is certainly the best.

**Comment by jeffrey33704** [comment]
RHEL is free to all if one signs up for the free developer license.

**Comment by leaanthony** [comment]
Perfect. Will get on it. Though if you fancy trying your hand at it there's
a guide here: https://wails.app/guides/distro/

**Comment by jeffrey33704** [comment]
I appreciate your time, and I will also look into trying to get it to work on my end.  Thank you for the link!

**Comment by leaanthony** [comment]
Hi there. Could you please install the cli from the develop branch and see if that works? `cd cmd/wails && go install`

**Comment by leaanthony** [comment]
The code for this is now in release `v1.16.2`. Please let me know if you have any issues otherwise feel free to close this ticket 👍

**Comment by leaanthony** [comment]
Closing due to lack of feedback
