### ISSUE TITLE
After packaging, the download has no response 。

### ISSUE THREAD

**Issue by kb-8-byte** [wailsapp/wails#602]
![image](https://user-images.githubusercontent.com/18651522/106985725-e89f8d00-67a4-11eb-9719-0690fa2279fc.png)
![image](https://user-images.githubusercontent.com/18651522/106985779-053bc500-67a5-11eb-8585-611e4e8e4e77.png)

**Comment by leaanthony** [comment]
Please reopen this issue using `wails issue` and complete the details. Thanks!
