### ISSUE TITLE
"wails serve" Problem

### ISSUE THREAD

**Issue by magdev2022** [wailsapp/wails#603]
**Description**

- When use "wails serve", how to reloading automatically after changing backend code?
- How to stop "wails serve"? "ctrl+c" was not running.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.15.6 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 7.3.0 |
| Npm           | 6.14.10 |
| Node          | v14.15.4

**Comment by leaanthony** [comment]
v1 doesn't have the ability to rebuild on change for backend currently. I'm not sure why ctrl-c doesn't work for you. What terminal do you use? How can I reproduce? I just tried it now and it works fine.

**Comment by yiming1995** [comment]
Thank you for reply. I am using VS code on Windows.

**Comment by leaanthony** [comment]
Do you still have this problem?

**Comment by yiming1995** [comment]
I have no problem.
