### ISSUE TITLE
LdFlags in project.json not respected

### ISSUE THREAD

**Issue by jghiloni** [wailsapp/wails#605]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
When running `wails build`, any `LdFlags` specified in `project.json` are ignored. They're accepted from the command line just fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a project.
2. In `main.go`, add these lines around `func main()`:
    ```go
    var Version="0.0.0"
    func main() {
        fmt.Println(Version)
    ```
3. Open `project.json` and add the following value for `LdFlags`: `"-X 'main.Version=1.0.0'"`
4. Run `wails build`

**Expected behaviour**
Before the app window is created, `1.0.0` should be output to stdout. However, `0.0.0` is instead. If I pass the exact same to the `-ldflags` argument to `wails build` instead of adding it to `project.json`, it works.

**Screenshots**

**System Details**
```
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/jaygles/go/bin"
GOCACHE="/Users/jaygles/Library/Caches/go-build"
GOENV="/Users/jaygles/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jaygles/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jaygles/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.15.7_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.15.7_1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5k/htcjckbn0yj3dsg4s7__5gpm0000gn/T/go-build4013280083=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Additional context**
If I run `wails build --verbose`, I can clearly see the `LdFlags` not being inserted into the `go build` command that is called.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hey @jghiloni ! Thanks for opening this. I was initially surprised that LdFlags were in the project options at all as they were never intended there. Turns out a number of options have been added to the internal project options struct which have made their way to the project json file by virtue of having a capital first letter. That being said, technically there should be nothing wrong with updating this value. We use `-X` quite a bit internally but don't use single quotes. Have you tried that?

**Comment by jghiloni** [comment]
The biggest reason I can think of for leaving them in was for automation purposes. However, during my testing yesterday, I set the value of my `-X` flags to env vars (like `-X main.ClientID=${CLIENT_ID} -X main.ClientSecret=${CLIENT_SECRET}` and I had to actually preprocess the values to do what I was doing. I basically changed my build command from

`wails build`

to

`wails build -ldflags "(jq -r '.LdFlags' < project.json)"`

to

`wails build -ldflags "(jq -r '.LdFlags' < project.json | envsubst)"`

Now, I'm not sure if that's a function of `zsh` not parsing that output, or `go build` not parsing it. Either way, I'm fine with whichever approach you want to take; I don't see a ton of benefit either way

**Comment by leaanthony** [comment]
There might be an escaping issue with using jq like that. I'm keen to remove the saved values in project.json for 2 reasons:
  1. It currently doesn't work so there's no fallout
  2. Removes the chance that someone is getting stealth ldflags just because they used the `ldflags` flag at an earlier point

For cli flags, this is a stealth cache and I'm not keen on it!

**Comment by worapolburaphan** [comment]
![image](https://github.com/wailsapp/wails/assets/12433101/a2521d74-67d0-4750-94a5-ad02f6ddccef)

![image](https://github.com/wailsapp/wails/assets/12433101/7ef8a430-f8de-42e0-a5a9-8af7b35e110a)

I face to similar issues when using ldflags to inject some value in to my code at build time

![image](https://github.com/wailsapp/wails/assets/12433101/d369ddd3-db2e-40dd-9a9d-e5fd2640f3a1)

```
# Wails
Version | v2.8.2

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                   |
| Version      | 14.0                                                                                                                    |
| ID           | 23A344                                                                                                                  |
| Go Version   | go1.22.3                                                                                                                |
| Platform     | darwin                                                                                                                  |
| Architecture | arm64                                                                                                                   |
| CPU          | Apple M2                                                                                                                |
| GPU          | Chipset Model: Apple M2 Type: GPU Bus: Built-In Total Number of Cores: 10 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 16GB                                                                                                                    |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2399    |
| Nodejs                    | N/A          | Installed | 22.2.0  |
| npm                       | N/A          | Installed | 10.7.0  |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Available |         |
└─────────────────── * - Optional Dependency ────────────────────┘

# Diagnosis
```
