### ISSUE TITLE
Issue with angular routing module on Windows

### ISSUE THREAD

**Issue by c0m3tx** [wailsapp/wails#606]
**Description**

I have been trying to build the application in the last few hours. Building works fine, and creates a valid exe file in the build folder. However, when I open the app everything is white. I tried in IE11 with wails serve and works fine. I tried debugging using the F12 application and it seems that the angular router directive `<router-outlet>` does not get replaced with the proper template. There is no error in the console. Any idea on what I can try?

If needed I can privately provide the application source (it will show no data, but it should be possible to "see" something).

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.15.3 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.3.0 |
| Npm           | 6.14.10 |
| Node          | v14.15.4
 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by c0m3tx** [comment]
I reproduced the issue on the default test app, by adding a small component and binding its creation via router under the button.
The button tries to navigate using router.navigate, but the promise never completes and nothing appears on the console.
It works fine in IE11 with wails serve. The component gets created.

Here is the full test code:
https://github.com/c0m3tx/wails-app-angular-issue

Thanks in advance

**Comment by leaanthony** [comment]
Hi. I'm not an angular person but here's a few links on this topic:

https://github.com/wailsapp/wails/pull/502
https://github.com/wailsapp/wails/issues/236#issuecomment-532741700
https://github.com/wailsapp/wails/issues/497

Let us know if you find a solution 👍

**Comment by c0m3tx** [comment]
Hi @leaanthony , thanks for your answer.

I verified, and in both projects (the one I linked here and the one I'm working on) angular routing is set to use hashes (as suggested in your links). The strange thing is that the console does not show any error, so debugging is very difficult. It may be something missing in the embedded MSIE11?

Is there a way to tell wails to compile the application in debug mode instead of production?

If nothing else works, I think I'll remove the default routing and somehow implement it manually, by putting components side-by-side with proper if conditions 😁

**Comment by c0m3tx** [comment]
Hi @leaanthony,

I wasn't able to fix the issue, which I believe is somehow related to embedded MSIE11 (it's a blind shot, I have no idea what's happening TBH). Since I don't have much time left for this project I am working on, I implemented a small state machine using ngrx. It's not quite the same as using angular router, but works, and I think is ok for the time being.

Maybe, if you are able to reproduce the issue on your side, I suggest indicating the issue as known, I was just lucky to test it before going too deep and risking to have to rewrite a lot of the frontend.

I'll leave that test repository available for further testing, hoping that v2 will bring a better windows experience.

Thanks again!

**Comment by leaanthony** [comment]
@c0m3tx did you want to close this?

**Comment by c0m3tx** [comment]
The solution I found is working. I think we can close this, but maybe add a small note on the readme 😄

**Comment by leaanthony** [comment]
It would be amazing to have a PR on the docsv1 repo about this!

**Comment by c0m3tx** [comment]
Currently I have zero time, but I'll try to do it as soon as possible! 😉

**Comment by leaanthony** [comment]
If you just quickly paste your solution here I can update the docs

**Comment by c0m3tx** [comment]
I created a NgRx state reducer like this:

```import { createReducer, on } from '@ngrx/store';
import * as StateActions from './state.actions';

export interface State {
    area: string;
    params: any;
}

const initialState: State = {
    area: 'login', // this contains the main window, the one shown at application startup
    params: {}
};

const stateReducer = createReducer(initialState,
    on(StateActions.setState, (state, payload): State => ({ ...state, area: payload.area, params: payload.params })),
);

export function StateReducer(state, action) {
  return stateReducer(state, action);
}
```

and a state actions file (very simple):

```import { createAction, props } from '@ngrx/store';

export const setState = createAction('[State] Set state', props<{area: string, params: any}>());
```

Then I created a simple change state directive for links (which changes current state), used as `<a appChangeState='other window'>link</a>` which may also accept a parameters object:

```import { Directive, HostListener, Input } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from './store/app.reducer';

import * as StateActions from './store/state.actions';

@Directive({
  selector: '[appChangeState]'
})
export class ChangeStateDirective {
  @Input() appChangeState: string;
  @Input() appChangeParams: any;

  @HostListener('click')
  onClick() {
    this.store.dispatch(StateActions.setState({ area: this.appChangeState, params: this.appChangeParams }));
  }

  constructor(private store: Store<AppState>) { }

}
```

And a state directive which regulates if elements are shown or not based on current state

```import { Directive, Input, OnDestroy, OnInit, TemplateRef, ViewContainerRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subscription } from 'rxjs';
import { AppState } from './store/app.reducer';

@Directive({
  selector: '[appState]'
})
export class StateDirective implements OnInit, OnDestroy {
  area: string;
  areaSub: Subscription;
  appStateValue: string;

  created = false;

  @Input()
  set appState(name: string) {
    this.appStateValue = name;
  }
  constructor(private templateRef: TemplateRef<any>,
              private container: ViewContainerRef, private store: Store<AppState>) {}

  ngOnInit() {
    this.areaSub = this.store.select('state').subscribe(state => {
      this.area = state.area;
      let name = this.appStateValue;
      let create = false;
      if (name[0] === '!') {
        name = name.substring(1);
        create = this.area !== name;
      } else {
        create = this.area === name;
      }

      if (!create && this.created) {
        this.container.clear();
      } else if (create && !this.created) {
        this.container.createEmbeddedView(this.templateRef);
      }

      this.created = create;
    });
  }

  ngOnDestroy() {
    this.areaSub.unsubscribe();
  }
}
```

All directives must be also loaded in the main app module.

I understand it's a lot, and I hope I have remembered everything. Let me know if something is missing!
