### ISSUE TITLE
Feature Request: Frameless Window

### ISSUE THREAD

**Issue by Purple-CSGO** [wailsapp/wails#607]
Hello, I've tried and made some simple projects. wails does meet most of my requests, but when will wails support frameless window feature and enable custom window title bar like electron, or put it on the roadmap? Looking forward to it~

**Comment by leaanthony** [comment]
Hi! This will be part of v2 which is currently in development. I've had a few requests for a roadmap so I'm going to put something together this week. Frameless already works for Mac and Linux but is not ready for use yet. Do, yes, this is happening!
