### ISSUE TITLE
App window left unfocused selecting file

### ISSUE THREAD

**Issue by rh12503** [wailsapp/wails#608]
**Description**
On my Mac, after selecting a file through `runtime.Dialog.SelectFile()`, the main app window is left out of focus. 

**System Details**
macOS 10.15.5

Could this issue be resolved if there was a function that called `SetFocus(w->priv.hwnd);`, similarly to [https://github.com/wailsapp/wails/blob/master/lib/renderer/webview/webview.h#L1493](url)?

**Comment by leaanthony** [comment]
Hey! Yes that's quite annoying. Looks like you might have found the answer. Happy to accept a PR for this and I'm sure would be appreciated by many others too.

**Comment by RH12503** [comment]
Thanks for your quick reply! I'm not very familiar with developing frameworks of this type, but I'll try and see if I can get it working. I'll open a PR if I manage to.

**Comment by RH12503** [comment]
Got it working on my Mac by adding 
```
defer w.window.Dispatch(func() {
	w.window.Focus()
})
```
to `SelectFile()`, where `Focus()` calls a C function containing `[w->priv.window makeKeyWindow];`. Since you made the library, could there be any issues with this code?

Also, although adding support for other operating systems would be pretty simple, I'm unable to test Windows and Linux. Is there anyone who could test it out, or should I make a PR of what should work?

**Comment by leaanthony** [comment]
I thought I'd replied to this already but apparently not! If you make a PR for all the systems, I can test them 👍

**Comment by RH12503** [comment]
Seems like there could be a bit of misunderstanding on my part, but the PR I opened (#609) already covers Linux/Windows, and just needs to be tested.

**Comment by leaanthony** [comment]
Ah, my bad. Will check it out over the weekend 👍

**Comment by leaanthony** [comment]
Confirmed working on Windows

**Comment by leaanthony** [comment]
Confirmed working in Linux! Nice job!

**Comment by leaanthony** [comment]
Added to latest pre-release. Please let me know how it goes: `wails update -pre`. 👍

**Comment by RH12503** [comment]
Works perfectly, thanks for your help! Closing this issue now. :)
