### ISSUE TITLE
AppIcon doesn't work on Pop OS 20.10

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#611]
**Description**

`appicon.png` does not work on Linux. It shows up blank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place an `appicon.png` in the repository root
2. `wails build -p`
3. ./build/binary
4. Observe taskbar

**Expected behaviour**
The application in the taskbar uses `appicon.png`.

**Screenshots**
![image](https://user-images.githubusercontent.com/76528657/108671276-06ebd500-7495-11eb-8257-4a4f4e4b2734.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.15.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.18.2 |

**Additional context**
N/A

**Comment by leaanthony** [comment]
What linux is this?

**Comment by kodah** [comment]
Pop OS 20.10

**Comment by leaanthony** [comment]
It will never show up as linux doesn't embed app icons in the binaries. If you want to do this, you need to make a `.desktop` file and add a path to an icon there. That's just a limitation of linux I'm afraid.

**Comment by mrf345** [comment]
I ran into this issue recently, so I've created a package that generates and updates the `.desktop` file whenever you run the app. In case someone else needs it https://github.com/mrf345/desktop-entry
