### ISSUE TITLE
Runtime error: Script error,URL: about:/js/chunk-6847cbb6.js 运行时脚本错误

### ISSUE THREAD

**Issue by chenbont** [wailsapp/wails#613]
**Description**

Wails serve works fine, but when the build is complete, the runtime finds an error that prompts "Script Error", URL: "about:/js/chunk-6847cbb6.js". Wails 开发模式是正常的，但构建完成后，运行程序就提示"Script Error"，URL："about:/js/chunk-6847cbb6.js".

 I was developed with Vue + Antd, in which I could see the introduction of files such as /js/0.js, js/1.js, and I don't know why they were built differently?我使用的是 Vue + Antd 开发，在开发模式可以看到引用了 /js/0.js、/js/1.js 这样的文件，却不知为什么构建后就不一样了？

I suspect it has something to do with chunk, but I don't know how to do it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Excute 'wails build'
2. Run it

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.7.1 |
| Go Version    | go1.12.1 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 8.1.0 |
| Npm           | 6.14.5 |
| Node          | v12.18.3
 |

**Additional context**
win - Debug Build
-----------------
time="2021-02-26T09:21:36+08:00" level=info msg="[App] Starting"
time="2021-02-26T09:21:37+08:00" level=info msg="[WebView] Initialised"
time="2021-02-26T09:21:37+08:00" level=info msg="[Events] Starting"
time="2021-02-26T09:21:37+08:00" level=info msg="[IPC] Starting"
time="2021-02-26T09:21:37+08:00" level=info msg="[Events] Listening"
time="2021-02-26T09:21:37+08:00" level=info msg="[Bind] Starting"
time="2021-02-26T09:21:37+08:00" level=info msg="[Bind] Binding Go Functions/Methods"
time="2021-02-26T09:21:37+08:00" level=info msg="[Bind] Bound Function: main.port()"
time="2021-02-26T09:21:37+08:00" level=debug msg="[Bind] Processing struct: server.Server"
time="2021-02-26T09:21:37+08:00" level=debug msg="[server.Server.WailsInit] Input param" index=0 kind=ptr name= typ="*wails.Runtime"
time="2021-02-26T09:21:37+08:00" level=debug msg="[server.Server.WailsInit] WailsInit input type: *wails.Runtime"
time="2021-02-26T09:21:37+08:00" level=debug msg="[server.Server.WailsInit] WailsInit output type: error"
time="2021-02-26T09:21:37+08:00" level=debug msg="[Bind] Detected WailsInit function: server.Server.WailsInit"
time="2021-02-26T09:21:37+08:00" level=info msg="[WebView] Running..."
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Enabling Wails console"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="(function () {\n\n    window.wailsconsole = {};..."
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="!function(n){var e={};function t(r){if(e[r])r..."
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{wails:loaded []}" type=event
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c88620
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="wails:loaded"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing event" name="wails:loaded"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c88620
time="2021-02-26T09:21:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="wails:loaded"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('wails:loaded','[]')"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] EvalSync" js="window.wails._.NewBinding('main.port');"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1614302497:7943"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1614302497:7943 []}" type=event
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c88a00
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1614302497:7943"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1614302497:7943"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c88a00
time="2021-02-26T09:21:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1614302497:7943"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('syncjs:1614302497:7943','[]')"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1614302497:7943"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Inject User CSS" css="#app{font-family:Avenir,Helvetica,Arial,sans-"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Inject User JS" js="(function(e){function t(t){for(var n,r,a=t[0]"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] EvalSync" js="(function(e){function t(t){for(var n,r,a=t[0]..."
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1614302497:9879"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1614302497:9879 []}" type=event
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c885f0
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1614302497:9879"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1614302497:9879"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c885f0
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error **** Caught Unhandled Error ****}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1614302497:9879"
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('syncjs:1614302497:9879','[]')"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Message: Script error.}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c887c8
time="2021-02-26T09:21:37+08:00" level=error msg="**** Caught Unhandled Error ****"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c887c8
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1614302497:9879"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13d8e010
time="2021-02-26T09:21:37+08:00" level=error msg="Message: Script error."
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13d8e010
time="2021-02-26T09:21:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="wails:ready"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error URL: about:/js/chunk-6847cbb6.js}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('wails:ready','null')"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x14116288
time="2021-02-26T09:21:37+08:00" level=error msg="URL: about:/js/chunk-6847cbb6.js"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x14116288
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Line No: 0}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13d8e020
time="2021-02-26T09:21:37+08:00" level=error msg="Line No: 0"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13d8e020
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Column No: 0}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c88bb8
time="2021-02-26T09:21:37+08:00" level=error msg="Column No: 0"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c88bb8
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Message received" payload="&{error error: undefined}" type=log
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13d8e150
time="2021-02-26T09:21:37+08:00" level=error msg="error: undefined"
time="2021-02-26T09:21:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13d8e150

frontend/package.json
------------------------
```js
  "browserslist": {
    "production": [
      "last 2 versions",
      ">0.2%",
      "not dead",
      "not op_mini all",
      "not ie <= 8",
      "ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  }
```

frontend/vue.config.js
-----------------
```js
configureWebpack: {
    output: {
      filename: "[name].js"
    },
    optimization: {
      splitChunks: false
    }
  },
```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi. I can't vomment on your project, but this sounds like an IE11 compatibility error.

**Comment by chenbont** [comment]
> Hi. I can't comment on your project, but this sounds like an IE11 compatibility error.

IE debugging found that the error occurred in the "init.js" file :
```js
function Init(callback) {
	window.wails._.Init(callback);
}
```

Unable to get undefined or null-referenced property ''_'
eval code (4051) (18,2)

**Comment by leaanthony** [comment]
Sounds like you haven't wrapped your entrypoint in the `Init` command

**Comment by leaanthony** [comment]
Check this for an example: https://github.com/wailsapp/wails/blob/master/cmd/templates/vuebasic/frontend/src/main.js#L11-L15

**Comment by chenbont** [comment]
> Sounds like you haven't wrapped your entrypoint in the `Init` command

wails serve，debugging in chrome was successful

**Comment by chenbont** [comment]
main.js
--------------
```js
import 'core-js/stable';
import 'regenerator-runtime/runtime';

import Vue from 'vue';
import App from './App.vue';

const Antd = require('ant-design-vue')
import 'ant-design-vue/dist/antd.css'
Vue.use(Antd)


const moment = require('moment')
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
import './assets/iconfont/iconfont.css'
import './assets/css/main.css'


// Vue.config.productionTip = false;
// Vue.config.devtools = true;

import VueI18n from 'vue-i18n'

Vue.use(VueI18n)


import store from './store'

import i18nSetting from './i18n/index'
const i18n = new VueI18n({
	locale: store.state.i18n.locale, // 设置地区
	fallbackLocale: 'cn', //当不存在时，退回到指定语言
	messages:i18nSetting, // 设置地区信息
	sync: false,
})


import VueRouter from 'vue-router';
import appRouter from './router';
Vue.use(VueRouter)
const router = new VueRouter(appRouter)
router.beforeEach((to,from,next)=>{
	console.log("当前路由",to)
	let path = to.path
	if (path === '/login') {
		next()
		return
	}
	//需求登录判断
	if(store.state.login.token){
		next();//跳转到目标页面
	}else{
		next({
			path:'/login'
		});//跳转到登录页面
	}
})

import * as Wails from '@wailsapp/runtime';

Wails.Init(() => {
	new Vue({
		router:router,
		i18n,
		store:store,
		render: h => h(App),
		mounted() {
			this.$router.replace('/login')
		},
	}).$mount('#app');
});

```

**Comment by leaanthony** [comment]
Have you opened it in IE11, as suggested in the docs?

**Comment by chenbont** [comment]
Yes, it ran successfully in IE11, but after "wails build -d" the execution application was mistimed and the console had output:

win - Debug Build
-----------------
time="2021-02-26T14:33:36+08:00" level=info msg="[App] Starting"
time="2021-02-26T14:33:37+08:00" level=info msg="[WebView] Initialised"
time="2021-02-26T14:33:37+08:00" level=info msg="[Events] Starting"
time="2021-02-26T14:33:37+08:00" level=info msg="[IPC] Starting"
time="2021-02-26T14:33:37+08:00" level=info msg="[Bind] Starting"
time="2021-02-26T14:33:37+08:00" level=info msg="[Bind] Binding Go Functions/Methods"
time="2021-02-26T14:33:37+08:00" level=info msg="[Events] Listening"
time="2021-02-26T14:33:37+08:00" level=info msg="[Bind] Bound Function: main.port()"
time="2021-02-26T14:33:37+08:00" level=debug msg="[Bind] Processing struct: server.Server"
time="2021-02-26T14:33:37+08:00" level=info msg="[Bind] Bound Method: server.Server.Test()"
time="2021-02-26T14:33:37+08:00" level=debug msg="[server.Server.WailsInit] Input param" index=0 kind=ptr name= typ="*wails.Runtime"
time="2021-02-26T14:33:37+08:00" level=debug msg="[server.Server.WailsInit] WailsInit input type: *wails.Runtime"
time="2021-02-26T14:33:37+08:00" level=debug msg="[server.Server.WailsInit] WailsInit output type: error"
time="2021-02-26T14:33:37+08:00" level=debug msg="[Bind] Detected WailsInit function: server.Server.WailsInit"
time="2021-02-26T14:33:37+08:00" level=info msg="[WebView] Running..."
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Enabling Wails console"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="(function () {\n\n    window.wailsconsole = {};..."
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="!function(n){var e={};function t(r){if(e[r])r..."
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{wails:loaded []}" type=event
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c06808
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="wails:loaded"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing event" name="wails:loaded"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c06808
time="2021-02-26T14:33:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="wails:loaded"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('wails:loaded','[]')"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] EvalSync" js="window.wails._.NewBinding('main.port');"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1614321217:7943"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1614321217:7943 []}" type=event
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x1413e4c0
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1614321217:7943"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1614321217:7943"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x1413e4c0
time="2021-02-26T14:33:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1614321217:7943"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('syncjs:1614321217:7943','[]')"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1614321217:7943"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] EvalSync" js="window.wails._.NewBinding('server.Server.Test..."
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1614321217:9879"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1614321217:9879 []}" type=event
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x1413e730
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1614321217:9879"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1614321217:9879"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x1413e730
time="2021-02-26T14:33:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1614321217:9879"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('syncjs:1614321217:9879','[]')"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1614321217:9879"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Inject User CSS" css="#app{font-family:Avenir,Helvetica,Arial,sans-"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Inject User JS" js="(function(e){function t(t){for(var n,r,a=t[0]"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] EvalSync" js="(function(e){function t(t){for(var n,r,a=t[0]..."
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: sending with ID = syncjs:1614321217:4574"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{syncjs:1614321217:4574 []}" type=event
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x14206010
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing event" data="[]" name="syncjs:1614321217:4574"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing event" name="syncjs:1614321217:4574"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x14206010
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error **** Caught Unhandled Error ****}" type=log
time="2021-02-26T14:33:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="syncjs:1614321217:4574"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('syncjs:1614321217:4574','[]')"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13dde020
time="2021-02-26T14:33:37+08:00" level=error msg="**** Caught Unhandled Error ****"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13dde020
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Message: Script error.}" type=log
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] SyncJS: Got callback ID = syncjs:1614321217:4574"
time="2021-02-26T14:33:37+08:00" level=debug msg="[Events] Got Event" data="[]" name="wails:ready"
time="2021-02-26T14:33:37+08:00" level=debug msg="[WebView] Eval" js="wails._.Notify('wails:ready','null')"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x13c06608
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error URL: about:/js/chunk-639d253c.js}" type=log
time="2021-02-26T14:33:37+08:00" level=error msg="Message: Script error."
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x13c06608
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x14186128
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Line No: 0}" type=log
time="2021-02-26T14:33:37+08:00" level=error msg="URL: about:/js/chunk-639d253c.js"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x14186128
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x142063e0
time="2021-02-26T14:33:37+08:00" level=error msg="Line No: 0"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error Column No: 0}" type=log
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x142063e0
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x14186218
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Message received" payload="&{error error: undefined}" type=log
time="2021-02-26T14:33:37+08:00" level=error msg="Column No: 0"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x14186218
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Processing message" 1D=0x14206530
time="2021-02-26T14:33:37+08:00" level=error msg="error: undefined"
time="2021-02-26T14:33:37+08:00" level=debug msg="[IPC] Finished processing message" 1D=0x14206530

**Comment by leaanthony** [comment]
Is the repo publicly available?

**Comment by leaanthony** [comment]
Closing due to lack of feedback
