### ISSUE TITLE
Crash after save dialog on Mac

### ISSUE THREAD

**Issue by rh12503** [wailsapp/wails#614]
**Description**
After opening a save dialog with a filter, not interacting with the dialog, and overwriting a file, the app crashes. 

**To Reproduce**
Using the _.svg_ extension as an example:
1. Save a file _Untitled.svg_ in your default save location. (the location which the save dialog opens to)
2. Open a save dialog using a filter `c.r.Dialog.SelectSaveFile("", "*.svg")`
2. Don't interact with any part of the save dialog 
3. Press the save button, and select replace when prompted 

**System Details**
macOS 10.15.5

**Additional context**
The error
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ROSP: sandbox extension failure: nil result or wrong class type ((null)) for finalURL`
suggests that the default filename is blank, despite appearing as _Untitled.extension_ to the user.

Pretty sure this could be fixed by adding `[panel setNameFieldStringValue:defaultName];`, although it's weird that the dialog recognizes that there is a duplicate file.

**Comment by leaanthony** [comment]
Thanks for reporting this! Did you try the `setNameFieldStringValue` fix? If so, would be happy to merge it!

**Comment by leaanthony** [comment]
@RH12503 -Did you get anywhere with the `setNameFieldStringValue` fix?

**Comment by leaanthony** [comment]
I'm not able to reproduce this in Big Sur

**Comment by RH12503** [comment]
Sorry - completely forgot about this issue! I'll see if `setNameFieldStringValue` fixes this.

**Comment by leaanthony** [comment]
Cool. What version of MacOS are you using? Can't reproduce

**Comment by RH12503** [comment]
I'm on macOS 1.15, and it seems for sandboxed apps before Big Sur, if the default filename is Untitled the save dialog crashes. 

The only way to fix this might be to change the default name to something besides "Untitled", but I'm not sure if you want to do that. 

Related post: [https://stackoverflow.com/q/21039088/15283541](https://stackoverflow.com/q/21039088/15283541)

**Comment by leaanthony** [comment]
I've got a Mojave machine. Will see if I can reproduce on that.

**Comment by leaanthony** [comment]
@RH12503 did `setNameFieldStringValue` fix this for you locally?

**Comment by RH12503** [comment]
So sorry, I've been busy lately and completely forgot about this! Using `setNameFieldStringValue` works, but the default name can't be set to "Untitled" for some reason. 

I suppose another name could be used (I used "output" for my app), or there could be a parameter in `SelectSaveFile` to set the name. I'd be happy to add that functionality across Windows and Linux too if necessary, but the "Untitled" limitation would need to be handled somehow.

**Comment by RH12503** [comment]
Never mind, I've experimented a bit and it seems like if you use `setNameFieldStringValue` twice (once to anything not "Untitled" and then once back to "Untitled"), it works fine. I'll open a PR now!

**Comment by RH12503** [comment]
Added a PR, this was a weird issue (and hopefully the last for v1)!
