### ISSUE TITLE
Is it possible to consider using `Go embed` instead of `github.com/leaanthony/mewn`?

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#616]
Is it possible to consider using `Go embed` instead of `github.com/leaanthony/mewn`?

**Comment by leaanthony** [comment]
There's nothing stopping you do this for your main assets in main.go 😃

**Comment by leaanthony** [comment]
@misitebao did you do this? Interested to hear your results

**Comment by homburg** [comment]
I've tried this in a local app. Worked perfectly

```go
package main

import (
  "github.com/wailsapp/wails"
  _ "embed"
)

func basic() string {
  return "World!"
}

//go:embed frontend/dist/hello-wails-react.es.js
var js string

//go:embed frontend/src/main.css
var css string

func main() {

  // js := mewn.String("")
  // css := mewn.String(".")

  app := wails.CreateApp(&wails.AppConfig{
    Width:  1024,
    Height: 768,
    Title:  "",
    JS:     js,
    CSS:    css,
    Colour: "#4158d0",
    Resizable: true,
  })
  app.Bind(basic)
  app.Run()
}
```

**Comment by leaanthony** [comment]
Thanks, am closing this. FYI, v2 uses embed for the CLI, however the majority of asset bundling during compilation is done via generating C for maximum startup speed. And it's pretty fast 😉
