### ISSUE TITLE
angular setup error using "wails init"

### ISSUE THREAD

**Issue by akshayprasad** [wailsapp/wails#618]
**Description**

Unable to setup angular project with wails and rest of the frameworks functions quite well

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init
2. Select 1 for angular and error is seen
3. please find the attached screenshot

**Expected behaviour**
It should setup the angular application.

**Screenshots**
<img width="717" alt="Screenshot 2021-03-15 at 8 29 04 PM" src="https://user-images.githubusercontent.com/18460224/111210128-29bd6500-85cd-11eb-8e67-e621cd8f5095.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.16.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 12.0.0 |
| Npm           | 7.6.3 |
| Node          | v14.16.0 |

**Additional context**
Currently I am using macOS and able to get the error for angular. Kindly, help me with the same.
Looking forward to hearing from you.

**Comment by leaanthony** [comment]
I am unable to reproduce. Perhaps there's some transient npm error?
```
Wails v1.11.0 - Initialising project

The name of the project (My Project): t
Project Name: t
The output binary name (t): 
Output binary Name: t
Project directory name (t): 
Project Directory: t
Please select a template (* means unsupported on current platform):
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v4 template
  3: Svelte - A basic Svelte template
  4: Vanilla - A Vanilla HTML/JS template
  5: Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
  6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 
Template: Angular
✓ Generating project...
✓ Building project (this may take a while)...
Project 't' built in directory 't'!
```

**Comment by akshayprasad** [comment]
> I am unable to reproduce. Perhaps there's some transient npm error?
> 
> ```
> Wails v1.11.0 - Initialising project
> 
> The name of the project (My Project): t
> Project Name: t
> The output binary name (t): 
> Output binary Name: t
> Project directory name (t): 
> Project Directory: t
> Please select a template (* means unsupported on current platform):
>   1: Angular - Angular 8 template (Requires node 10.8+)
>   2: React JS - Create React App v4 template
>   3: Svelte - A basic Svelte template
>   4: Vanilla - A Vanilla HTML/JS template
>   5: Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
>   6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
>   7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
>   8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
> Please choose an option [1]: 
> Template: Angular
> ✓ Generating project...
> ✓ Building project (this may take a while)...
> Project 't' built in directory 't'!
> ```

I tried yet again and still facing the same issue.
I am able to run Vue, react successfully but not angular explicitly.

Any idea what I can do with this now?

**Comment by akshayprasad** [comment]
> I am unable to reproduce. Perhaps there's some transient npm error?
> 
> ```
> Wails v1.11.0 - Initialising project
> 
> The name of the project (My Project): t
> Project Name: t
> The output binary name (t): 
> Output binary Name: t
> Project directory name (t): 
> Project Directory: t
> Please select a template (* means unsupported on current platform):
>   1: Angular - Angular 8 template (Requires node 10.8+)
>   2: React JS - Create React App v4 template
>   3: Svelte - A basic Svelte template
>   4: Vanilla - A Vanilla HTML/JS template
>   5: Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
>   6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
>   7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
>   8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
> Please choose an option [1]: 
> Template: Angular
> ✓ Generating project...
> ✓ Building project (this may take a while)...
> Project 't' built in directory 't'!
> ```

I can even create ng <app> and run ng serve with npm it works fine. Only with Wails I am unable to work with angular.

**Comment by akshayprasad** [comment]
Since wails use angular 8 template, we have to downgrade the node version to 12.x to work.
I figured now.
With the latest node it doesn't work.

**Comment by leaanthony** [comment]
Ah, thanks for working this out. What do you think would be a good solution to this problem? Just mandate node 12?

**Comment by akshayprasad** [comment]
> Ah, thanks for working this out. What do you think would be a good solution to this problem? Just mandate node 12?

Yeah, mandating node 12 is the best possible solution for now I feel.

**Comment by leaanthony** [comment]
I just installed node 14 and it worked as expected:
![image](https://user-images.githubusercontent.com/1943904/111918170-f6e90480-8ad7-11eb-855c-994b5e74f00e.png)

I'm going to put this down to transient network issues. Feel free to open if you can reproduce.

**Comment by akshayprasad** [comment]
> I just installed node 14 and it worked as expected:
> ![image](https://user-images.githubusercontent.com/1943904/111918170-f6e90480-8ad7-11eb-855c-994b5e74f00e.png)
> 
> I'm going to put this down to transient network issues. Feel free to open if you can reproduce.

Cool, thanks for the assistance.
