### ISSUE TITLE
Animated PNG issue under Windows

### ISSUE THREAD

**Issue by jk14** [wailsapp/wails#619]
**Description**
I'm using such code in frontend, in some .vue file, inside \<template\> section: \<img src="../assets/img/logo.png"\>
Logo.png is animated PNG (96x96 resolution) - and under Linux is working properly, but under Windows only initial frame is displayed, and there is lack of motion.

**To Reproduce**
Use some animated PNG with: \<img src="../assets/img/logo.png"\>

**Expected behaviour**
Animation is working under Windows, too.

**Screenshots**
-

**System Details**
Ubuntu 20.04.1 LTS, go 1.14.3, Wails v1.10.1

**Additional context**
-

**Comment by jk14** [comment]
I made a simple test yet, converting animated png into animated gif. And it works, for both: Linux and Windows. So the problem is only with APNG under Windows. But preferred logo format is APNG, because animated gif is well known of poor quality. And I can confirm it, unfortunately.

**Comment by leaanthony** [comment]
APNG might not be supported by IE11

**Comment by jk14** [comment]
Ok, thank you for clarification and hint.

**Comment by leaanthony** [comment]
Work will begin shortly on moving to webview2. We all want it! 😃
