### ISSUE TITLE
[V2] Windows Port mega issue

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#622]
Because opening a ton of issues isn't helpful!

- [x] Init
- [ ] Build
  - [x] Standard build
  - [x] Production Flag
  - [ ] Cross Compilation
  - [x] Package
- [x] Generate
- [x] Update
- [x] Dev
- [x] Debug
- [x] Doctor
  - [x] OS Details
  - [x] Dependencies
- [ ] Runtime
    - [x] NewApplication
    - [x] SetMinWindowSize
    - [x] SetMaxWindowSize
    - [x] Run
    - [x] DestroyApplication
    - [x] SetDebug
    - [x] SetBindings
    - [x] ExecJS
    - [x] Hide
    - [x] Show
    - [x] Center
    - [x] Maximise
    - [x] Unmaximise
    - [x] ToggleMaximise
    - [x] Minimise
    - [x] Unminimise
    - [x] ToggleMinimise
    - [x] SetSize
    - [x] SetPosition
    - [x] Quit
    - [x] SetTitle
    - [x] Fullscreen
    - [x] UnFullscreen
    - [x] DisableFrame
    - [x] SaveDialog
    - [x] OpenDialog
        - [x] Filters
        - [x] Default directory
        - [x] Default filename
    - [x] StartHidden
    - [x] Transparent Webview
    - [x] Graceful Shutdown
    - [x] Menus
        - [x] Text
        - [x] Checkbox
        - [x] Separator
        - [x] Radio
        - [x] Submenus
        - [x] Hidden
        - [x] Disabled
        - [x] Accelerators
        - [x] Update
- [x] Application Menu
    - [x] Set 
    - [x] Update

**Comment by Dexus** [comment]
reopen?
