### ISSUE TITLE
[V2] Linux Port mega issue

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#623]
Because opening a ton of issues isn't helpful!

TODO: Update this with actual progress on the v2-linux branch.

- [x] Init
- [ ] Build
  - [ ] Standard build
  - [ ] Production Flag
  - [ ] Cross Compilation
  - [ ] Package
  - [ ] Server
  - [ ] Hybrid
- [ ] Generate
- [ ] Update
- [ ] Dev
- [ ] Debug
- [x] Doctor
  - [x] OS Details
  - [x] Dependencies
- [ ] Runtime
    - [ ] NewApplication
    - [ ] SetMinWindowSize
    - [ ] SetMaxWindowSize
    - [ ] Run
    - [ ] DestroyApplication
    - [ ] SetDebug
    - [ ] SetBindings
    - [ ] ExecJS
    - [ ] Hide
    - [ ] Show
    - [ ] Center
    - [ ] Maximise
    - [ ] Unmaximise
    - [ ] ToggleMaximise
    - [ ] Minimise
    - [ ] Unminimise
    - [ ] ToggleMinimise
    - [ ] SetSize
    - [ ] SetPosition
    - [ ] Quit
    - [ ] SetTitle
    - [ ] Fullscreen
    - [ ] UnFullscreen
    - [ ] ToggleFullscreen
    - [ ] SetColour
    - [ ] DisableFrame
    - [ ] SaveDialog
    - [ ] OpenDialog
        - [ ] Filters
        - [ ] Default directory
        - [ ] Default filename
    - [ ] StartHidden
    - [ ] Vibrancies
    - [ ] Appearance
    - [ ] Transparent Webview
    - [ ] Graceful Shutdown
    - [ ] Menus
        - [ ] Text
        - [ ] Checkbox
        - [ ] Separator
        - [ ] Radio
        - [ ] Submenus
        - [ ] Hidden
        - [ ] Disabled
        - [ ] Accelerators
        - [ ] Update

**Comment by hi019** [comment]
Doing great, stalebot

**Comment by leaanthony** [comment]
....
