### ISSUE TITLE
CLI: make name prompt default value based on git name

### ISSUE THREAD

**Issue by hi019** [wailsapp/wails#628]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the `wails setup` name prompt, if no existing wails config is found, we can make the default value the `name` field from `~/.gitconfig`. 

**Describe alternatives you've considered**
Alternatively we can use the currently logged in user's name. No additional libraries would be required as this functionality is [part of os/user](https://golang.org/pkg/os/user/#Current). I have an implementation of this [here](https://github.com/hi019/wails/commit/0a434e140aeecc9dfa09ccace2a6226f3e180e44) but can also make a PR for the other option above.

**Additional context**

**Comment by leaanthony** [comment]
Hi. Great suggestion! I think the first option would probably be best as some people prefer aliases to real names :-) Would love to get a PR for this!

**Comment by hi019** [comment]
Sure, will make one later today
