### ISSUE TITLE
init/build: Error: exit status 2

### ISSUE THREAD

**Issue by cristianadrielbraun** [wailsapp/wails#636]
**Description**

Hi! Fresh installed wails, and using both "wails init" and "wails build", it returns a "Error: exit status 2" message. More detailed, it says this: 

⡿ Ensuring Dependencies are up to date...# github.com/wailsapp/wails/lib/renderer/webview
In file included from /home/cristian/go/pkg/mod/github.com/wailsapp/wails@v1.12.0/lib/renderer/webview/webview.go:26:
./webview.h: In function 'webview_focus':
./webview.h:402:51: error: expected ';' before '}' token
     gtk_window_present(GTK_WINDOW(w->priv.window))
                                                   ^
                                                   ;
   }
   ~                                                

✗ Ensuring Dependencies are up to date...
Error: exit status 2

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init any project (tested with all of them)

**Expected behaviour**

Well... the project to be initialized 😄 

**Screenshots**
I think is unnecesary but, just in case, the screenshot:
<details>
  <summary>Image Spoiler</summary>
<img src="https://user-images.githubusercontent.com/31445936/112711217-6f1f4380-8ea5-11eb-9f89-d44c83e38508.png">
</details>

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.12.0 |
| Go Version    | go1.16.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 8.4.0 |
| Npm           | 6.14.11 |
| Node          | v14.16.0 |

**Comment by leaanthony** [comment]
Gah! Can't believe this slipped through the net. Issuing fix now.

**Comment by leaanthony** [comment]
Turns out, the sheer number of releases (tags) for the v2 stuff broke the update mechanism too. Please run `go get github.com/wailsapp/wails/cmd/wails@v1.12.3` and this will pull in the update fix. From that point `wails update` will work again

**Comment by yomono** [comment]
Like a charm! Thanks! Closing, then
