### ISSUE TITLE
mewn doesn't embed files if called without variable

### ISSUE THREAD

**Issue by igogrek** [wailsapp/wails#641]
As far as I understand there seem to be a bug with mewn embedding assets if it's not used with variables like in all examples: 
```
	js := mewn.String("./frontend/dist/app.js")
	css := mewn.String("./frontend/dist/app.css")
```
If I leave this as is - everything works fine, but if variables aren't used for js and css - window is just empty and it seems assets aren't embedded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Write main.go like this without creating variables for embedded JS and CSS:
```
	app := wails.CreateApp(&wails.AppConfig{
		...
		JS:        mewn.String("./frontend/dist/app.js"),
		CSS:       mewn.String("./frontend/dist/app.css"),
	})
```
2. Build app
3. Open app
4. See "empty" window

**Expected behaviour**
Window shops the proper frontend app

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.12.3 |
| Go Version    | go1.16 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.0 |
| Npm           | 7.0.3 |
| Node          | v15.0.1 |

**Additional context**
I understand that it might be my configuration issue or I'm just misunderstanding how mewn should work. And since it's already planned to replace it https://github.com/wailsapp/wails/issues/640 it might not be very revelant issue. Still it was very strange behaviour for me and I spent some time to find what's wrong as the serve command was working just fine.

**Comment by leaanthony** [comment]
Yeah that's a restriction on the Go parser of mewn. I'd normally say open a ticket on that [project](https://github.com/leaanthony/mewn) but we're just about to replace mewn with embed so I'm likely to archive that shortly.
