### ISSUE TITLE
Wails app randomly crashing on Windows - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vertiond** [wailsapp/wails#648]
https://github.com/vertcoin-project/one-click-miner-vnext/ 
The Vertcoin One-Click Miner is essentially a wrapper for running VerthashMiner, a command line mining program. 

Windows users of the OCM are repeatedly finding the OCM (vertcoin-ocm.exe) having closed and exited out while the underlying VerthashMiner.exe process is still running.  This seems to be related to the WebKit renderer on Windows.  

Debugging shows the error begins with `runtime error: invalid memory address or nil pointer dereference` and the full error message is documented here: https://github.com/vertcoin-project/one-click-miner-vnext/issues/141#issue-803417765

If you have any insight, it would be much appreciated.

**System Details**
Ubuntu 18.04
go1.15.6 linux/amd64
wails v1.11.0

- [ x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi. I see you're using wails@v1.9.1. That's really old. Have you confirmed this is still an issue on the latest version? The only other advice (as it's impossible to tell you why this is happening with no context) is to run it through gdb and get a stack trace.

**Comment by leaanthony** [comment]
What was the fix?

**Comment by vertiond** [comment]
No fix.  I think this means we are using Wails@1.11.0 and the problem persists.  https://github.com/vertcoin-project/one-click-miner-vnext/blob/master/go.mod#L30
I was going to close until more information was gathered such as running it through gdb and getting a C stack trace.
