### ISSUE TITLE
Cross compilation isn't working with v1.16.0

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#649]
The xgo build needs updating

**Comment by codenoid** [comment]
../../go/packages/pkg/mod/github.com/wailsapp/wails@v1.16.0/runtime/assets.go:3:8: package embed is not in GOROOT

**Comment by leaanthony** [comment]
@codenoid can you please provide more context with this comment

**Comment by codenoid** [comment]
error when I do 

```sh
go get -u github.com/wailsapp/wails/cmd/wails
```

**Comment by codenoid** [comment]
omg, I think I need to update my Go version, It's still go1.15.3

**Comment by leaanthony** [comment]
Here's a matrix of cross compilation tests done so far. @RH12503 which configurations did you try?

```
             Linux    Windows     MacOs
Linux
Windows
MacOS
```

**Comment by leaanthony** [comment]
https://github.com/wailsapp/wails/issues/670#issuecomment-817657064

**Comment by charlie-haley** [comment]
I'll also add that it doesn't work using Ubuntu 20.04 on Github Actions.

**Comment by leaanthony** [comment]
@charlie-haley v.1.16.4-pre1 released to test linux & windows. 

Have tested on Fedora 34:
![Screenshot from 2021-04-17 08-52-59](https://user-images.githubusercontent.com/1943904/115091610-4ac1fe80-9f5b-11eb-9d49-4afd2f3d83a2.png)

**Comment by leaanthony** [comment]
Windows 10 tests for `v1.16.4-pre1`:

1. wails build
2. wails build -x linux/amd64
3. wails build -x windows/amd64

![image (10)](https://user-images.githubusercontent.com/1943904/115100946-b61fc680-9f83-11eb-893b-60387a9695eb.png)

**Comment by leaanthony** [comment]
Can also confirm the binaries work as intended on each other's platform

**Comment by leaanthony** [comment]
MacOS/Intel tests:

<img width="559" alt="Screen Shot 2021-04-16 at 9 46 55 pm" src="https://user-images.githubusercontent.com/1943904/115102118-52e66200-9f8c-11eb-93d0-36b08599094d.png">

**Comment by leaanthony** [comment]
The only configuration left to work is having darwin/amd64 as a TARGET. Opened a ticket here: https://github.com/crazy-max/xgo/issues/28

**Comment by charlie-haley** [comment]
> @charlie-haley v.1.16.4-pre1 released to test linux & windows.
> 
> Have tested on Fedora 34:
> ![Screenshot from 2021-04-17 08-52-59](https://user-images.githubusercontent.com/1943904/115091610-4ac1fe80-9f5b-11eb-9d49-4afd2f3d83a2.png)

Is there a way to fetch this using `go get` or do I need to build from source?

**Comment by leaanthony** [comment]
`wails update -pre`

**Comment by leaanthony** [comment]
Also consider using the `-verbose` flag

**Comment by charlie-haley** [comment]
Tested on Arch and that's working correctly, I'll test my WSL2 build later. 

My GH Actions build is still failing with an interesting error (Ubuntu 20.04)
![image](https://user-images.githubusercontent.com/27928201/115241521-d7fe8200-a118-11eb-8b02-46370b8c196d.png)

**Comment by leaanthony** [comment]
Ah I know what that is. I was sure I pushed that as a fix but it might have been for v2 only.

**Comment by leaanthony** [comment]
Latest pre-release has the fix backported. `wails update -pre` 👍

**Comment by charlie-haley** [comment]
Same error on `v1.16.4-pre2` for me, still seems to be using `xgo:1.16.3` is that intentional?

**Comment by leaanthony** [comment]
Yeah. The fix is to use go mod tidy instead of go get which doesn't update package.sum as of 1.16

**Comment by charlie-haley** [comment]
> Is the repo public, where you have the action running?

Yep, here's the output from the latest build https://github.com/charlie-haley/flowcontrol/runs/2381121128#step:9:195

**Comment by leaanthony** [comment]
I suspect it's not using the latest -pre CLI

**Comment by charlie-haley** [comment]
Just ran another build and it's definitely using `v1.16.4-pre2`, [same error ](https://github.com/charlie-haley/flowcontrol/runs/2389149474#step:9:202)

**Comment by leaanthony** [comment]
Just downloaded the workflow file and currently running locally using [act](https://github.com/nektos/act). 20G download but it'll be useful when it's done. Just wondering if there's something different in `wails build` when it's run in docker. Just checking 👍

**Comment by charlie-haley** [comment]
> Just downloaded the workflow file and currently running locally using [act](https://github.com/nektos/act). 20G download but it'll be useful when it's done. Just wondering if there's something different in `wails build` when it's run in docker. Just checking 👍

The workflow behaves slightly different with act as I don't use cross-compilation as there's a Docker in Docker requirement that didn't end up working for me. [There's some conditional logic around act in the workflow](https://github.com/charlie-haley/flowcontrol/blob/main/.github/workflows/release.yml#L42)

**Comment by leaanthony** [comment]
Ok. Well, the reason it is giving that error is because the whole compilation process, including sorting out the modules, is handed to the docker instance and that doesn't have `go mod tidy` in it. We were handling modules differently before so I'm hoping this will fix it. In true docker style, I've added in 12 bytes and it's resulted in a 510M update.

**Comment by leaanthony** [comment]
Ok, new image pushed. Try re-running pipelines.

**Comment by charlie-haley** [comment]
> Ok, new image pushed. Try re-running pipelines.

[Hmm still no luck, same output](https://github.com/charlie-haley/flowcontrol/runs/2389540817?check_suite_focus=true#step:9:195) with `xgo:1.16.3`, `v1.16.4-pre2`

**Comment by leaanthony** [comment]
Gah, my bad. I'd tagged it with 1.16.4. Try now.

**Comment by leaanthony** [comment]
I really need to get an `exit 1` for when the docker build errors. Not sure quite why an error isn't getting returned there.

**Comment by charlie-haley** [comment]
🎉 that worked, thanks for the help! 

Also, [here's a PR to return an exit code upon compilation failure](https://github.com/wailsapp/xgo/pull/1), I'll try and give it a test later today. I still get `/build.sh: line 376: /deps: Is a directory` even though it runs successfully so that might cause some issues with using `||`

**Comment by leaanthony** [comment]
@charlie-haley I've just discovered that my tests may be tainted by the fact I'm using Apple Silicon. Is there a chance you could try targeting `darwin/amd64`with your known working setup and let us know what is output?

**Comment by charlie-haley** [comment]
> @charlie-haley I've just discovered that my tests may be tainted by the fact I'm using Apple Silicon. Is there a chance you could try targeting `darwin/amd64`with your known working setup and let us know what is output?

[Here's a link to the verbose output](https://github.com/charlie-haley/flowcontrol/runs/2408610166#step:21:94), it's failing to building `darwin/amd64` with `/build.sh: line 406: [: 1.16.2: integer expression expected`

I can test a windows => darwin build later, I'll also add `linux/arm-7` to my amd64 pipeline

**Comment by leaanthony** [comment]
Thanks for that. Unusual error 🧐

**Comment by tmclane** [comment]
Hopefully I'll have a chance to look at this sometime soon.  Presumably it is still broken?

**Comment by leaanthony** [comment]
Thanks @tmclane . Situation is it works for everything apart from a Mac target in docker. There's a branch in our xgo repo that has some updates to make it work so far. I've opened a ticket on the crazy-Max xgo repo but had nothing back for weeks. Am thinking we might need to fork it. Thoughts?

**Comment by tmclane** [comment]
I was wanting to fork it anyhow.  I have some thoughts on rebuilding the project using Alpine as well to trim down the fat.

**Comment by leaanthony** [comment]
I've had no response to the issue so seems like a good plan!

**Comment by leaanthony** [comment]
It would also give us an opportunity to simplify it and only support the archs we need. Might also be nice to implement the build.sh logic using Go, maybe using https://github.com/bitfield/script

**Comment by leaanthony** [comment]
No

**Comment by svengreb** [comment]
Is there any reason why this useless and progress damaging bot is even enabled for this repository? 🤭
