### ISSUE TITLE
Bound function is undefined on the frontend

### ISSUE THREAD

**Issue by sithembiso** [wailsapp/wails#654]
**Description**

When I bind Go function to the frontend, I don't get any errors, but it's undefined on the frontend.

**To Reproduce**
I don't know what caused the error. It works fine on the example, but not on my code. I'm suspecting that it has to do with my application structure? Here are the logs I see:
```
INFO[0000] [App] Starting                               
Control
INFO[0000] [WebView] Initialised                        
INFO[0000] [Events] Starting                            
INFO[0000] [IPC] Starting                               
INFO[0000] [Bind] Starting                              
INFO[0000] [Bind] Binding Go Functions/Methods          
INFO[0000] [Bind] Bound Function: github.com/lepsta/lepsta/cmd.login() 
INFO[0000] [WebView] Running...                         
DEBU[0000] [WebView] Injecting wails JS runtime 
```
My application structure looks like this:
<img width="222" alt="Screenshot 2021-04-05 at 23 03 03" src="https://user-images.githubusercontent.com/6559905/113626965-1731cb00-9663-11eb-95b7-44cc388300de.png">
The code that creates the Wails app is in `cmd/login.go`. The function I'm trying to bind `func login() string` is also in the same file.

**Expected behaviour**
I expect to be able to call the function from the frontend.

**Screenshots**
<img width="1005" alt="Screenshot 2021-04-05 at 23 05 14" src="https://user-images.githubusercontent.com/6559905/113627160-64ae3800-9663-11eb-9be2-cfc7e12b62cc.png">

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.0 |
| Go Version    | go1.16.3 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.0 |
| Npm           | 6.14.10 |
| Node          | v14.15.4 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by sithembiso** [comment]
**Update:**
I'm still getting acquinted with the codebase, but from what I see, there is an assumption being made about only expecting to bind functions from the `main` package. I think this is evident here:
[https://github.com/wailsapp/wails/blob/94bed2a093562510a885f90e9fc4f78446c2a04a/lib/binding/manager.go#L164](https://github.com/wailsapp/wails/blob/94bed2a093562510a885f90e9fc4f78446c2a04a/lib/binding/manager.go#L164)
Still digging though.

**Comment by sithembiso** [comment]
While my comment above may be valid, what was really causing the issue was someplace else, so I made a PR:
https://github.com/wailsapp/wails/pull/655
Please let me know if you have questions. I'll close this when it's merged.

**Comment by leaanthony** [comment]
Thanks for digging into this. Will test the PR and get back to you 👍

**Comment by leaanthony** [comment]
Hey there! Have you tried binding structs from a different package? Do they exhibit the same behaviour?

**Comment by sithembiso** [comment]
I haven't tried binding structs yet. I'll check and update the PR if necessary.

**Comment by leaanthony** [comment]
Hi. Where did we get with this?

**Comment by leaanthony** [comment]
I believe this was fixed?

**Comment by leaanthony** [comment]
@sithembiso you happy this is resolved?

**Comment by sithembiso** [comment]
Yes. We can mark this as resolved. Thank you. Sorry I forgot to close it. I wanted to test it first, which I only got to do today.
