### ISSUE TITLE
QUESTION: How can we get involved in accelerating V2 / testing it

### ISSUE THREAD

**Issue by sithembiso** [wailsapp/wails#657]
I'm using Wails on Windows for the first time and while everything works great, the UI part is giving me a headache. I've noticed that there seems to be a lot of improvements coming with V2 and I was wondering how I and others can contribute. 
I was hoping to be able to install the Alpha and start playing with it, but I couldn't install it. I'm not sure if this is intentional:
```
go get -u github.com/wailsapp/wails/cmd/wails@v2.0.0-alpha.63
go get github.com/wailsapp/wails/cmd/wails@v2.0.0-alpha.63: github.com/wailsapp/wails@v2.0.0-alpha.63: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
Please let us know if there's anything we can help with (I hope I'm speaking on behalf of the community :-D )

**Comment by sithembiso** [comment]
Also, what is `mshtml` used for? I couldn't locate it anywhere on the code. So, I'm having difficulty understanding why Wails uses IE11 instead of Edge for example? Probably because I don't actually know what `mshtml` actually does 🤔 .
![wails-compatibility](https://user-images.githubusercontent.com/6559905/113986951-1c06a280-984e-11eb-9e09-c88e5640c5a4.PNG)

**Comment by leaanthony** [comment]
Thanks for your interest in v2. I'm going to pin an issue with this information this week. Really looking for people to help with either C/C++ and testing

**Comment by lnquy** [comment]
I was inspired by [xbar](https://github.com/matryer/xbar) and noticed that xbar is using [Wails v2-alpha](https://github.com/matryer/xbar/blob/main/app/go.mod#L15) so I want to try it out too.

Currently I'm having the same issue when installing Wails 2 on Windows.

```
$ wails update --version v2.0.0-alpha.63
Wails v1.16.1-pre2 - Checking for updates...

> Checking for updates...

    Current Version : v1.16.1-pre2
    Desired Version : v2.0.0-alpha.63

- Installing Wails v2.0.0-alpha.63go get github.com/wailsapp/wails/cmd/wails@v2.0.0-alpha.63: github.com/wailsapp/wails@v2.0.0-alpha.63: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2


! exit status 1
Error: exit status 1
```

If I try to build the code directly from `v2.0.0-alpha.63` branch then it's success but the binary file says Wails version is 1.11, and no `dev` command.
```
$ git checkout v2.0.0-alpha.63
HEAD is now at 2e01710 v2.0.0-alpha.63
$ cd cmd/wails
$ go build
$ .\wails.exe
 _       __      _ __
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v1.11.0
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps...
```

Would be nice if you have some quick docs or notes to setup/install v2 @leaanthony . 
Thanks for a wonderful project too :)

**Comment by leaanthony** [comment]
@Inquy - That's a novel way to try and install it 😄 Due to Go v2 path requirements, it can't work like that. More information on how to get involved to come...

V2 is currently Mac only. I've created an [FAQ](https://github.com/wailsapp/wails/issues/661) that addresses this. I will be building out [this page](https://github.com/wailsapp/wails/wiki/Helping-with-V2) over the coming week as we're now close to the point of being able to make the Mac version a public beta (there are just some slight adjustments that are needed).

**Comment by leaanthony** [comment]
I have now updated the wiki page: https://github.com/wailsapp/wails/wiki/Helping-with-V2

**Comment by sithembiso** [comment]
> From Wikipedia:
> 
> > Trident (also known as MSHTML) is a proprietary browser engine for the Microsoft Windows version of Internet Explorer, developed by Microsoft.
> 
> Wails does not talk to the system webview directly, instead it uses an older version (that doesn't support Edge) of https://github.com/webview/webview to do that. That code is vendored [here](https://github.com/wailsapp/wails/blob/9c91a207c8c337083c64046a7925f59641b13d83/lib/renderer/webview/webview.h), you can see an mshtml reference.

Thank you for the details. @leaanthony was there any specific reason to pin the older version of Webview? What would it take to make it compatible with the latest version of that library? I took a look at the renderer package where `webview` is being used. This is probably not as trivial as it seems but, could we not just modify that to make it work with the latest version? Or are there other things to consider, like missing features?

**Comment by leaanthony** [comment]
That information is in the wiki page.
