### ISSUE TITLE
Wails apps not displaying gui

### ISSUE THREAD

**Issue by chrisfair** [wailsapp/wails#658]
**Description**

As of yesterday morning I am no longer able to see any wails guis this is the case with my own app and also the Wally app for my keyboard

**To Reproduce**
Attempt to run the application you will be presented with a black screen 

If run from command line I get this message
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Control

**Expected behaviour**
I expect to see the gui

**Screenshots**
This is a screen shot of wally running which ran just fine the other day
![wally](https://user-images.githubusercontent.com/4054917/114038683-4f8e0080-983f-11eb-95eb-6f53b77d9b94.png)

If running from cli you will see this message

Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Control

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.0 |
| Go Version    | go1.16.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Set) |
| GCC           | 10.2.0 |
| Npm           | 7.8.0 |
| Node          | v15.14.0 |
| Distro         |Manjaro 21.0.1 |
|Kernel         |5.10.28|
|Shell            |Fish 3.2.0-60|
|Windows Manager | I3 |
|Processor    |Ryzen 7 x1700|
|Memory    |DDR 4 32GB 2400MHz|

**Additional context**
Pretty straight forward "It don't work" it is possible that it is a problem with webkit.

**Comment by leaanthony** [comment]
Wow, that's super weird. Are you saying that new builds don't work or any apps don't work?

**Comment by fdidron** [comment]
Hi @chrisfair,

Can you give me the result of the following command: pacman -Qs webkit2gtk

Also, while I'm looking into this, there's a cli version of wally available here if that helps: https://github.com/zsa/wally-cli/releases

**Comment by fdidron** [comment]
@leaanthony FYI I got similar reports from users on Arch / Ubuntu with the webkit2gtk version 2.32.0-1 .

**Comment by leaanthony** [comment]
It sounds like WebKit has been removed/upgraded and now the app can't find it? I wonder if there's something we can do in terms of warning about that. This is the first time I've heard of this.

**Comment by leaanthony** [comment]
@fdidron thanks for your help in diagnosing this 👍

**Comment by fdidron** [comment]
@leaanthony Just finished installing Arch with latest gnome, webkit2gtk version 2.32.0-1 I can reproduce the issue.

It works with my Manjaro distro with a older version of the lib, so maybe the lib update broke something with the webview renderer, going to look into the webkitgtk changelog for deprecated stuff

**Comment by leaanthony** [comment]
@fdidron i'm seeing nothing on the webview forums so it's likely a deprecated api

**Comment by fdidron** [comment]
@leaanthony @chrisfair  Here's a PR that seems to fix the issue on my side: #659

**Comment by leaanthony** [comment]
Wails v1.16.2 should fix this now. Thanks @fdidron!

**Comment by fdidron** [comment]
@leaanthony Great thanks for the quick release !

**Comment by leaanthony** [comment]
Please let us know if it fixes the issue!

**Comment by fdidron** [comment]
@chrisfair There's a new wally version :) https://github.com/zsa/wally/releases/tag/2.1.1-linux

@leaanthony works great with the newest or older versions of webkit2gtk

**Comment by chrisfair** [comment]
@fidron I updated to the newest wails do I need to do anything else in source to make it work?   I am one of the package managers for wally so I will update it for arch but my private program (latin-catholic-prayers) still displays blank screen

**Comment by chrisfair** [comment]
@fidron but wally works fine will look through your hard work here in the notes to see if I can figure out how to fix my own app

**Comment by chrisfair** [comment]
> pacman -Qs webkit2gtk

local/webkit2gtk 2.32.0-1
    Web content engine for GTK

**Comment by leaanthony** [comment]
@chrisfair if Wally works, your app should too. Does it work in serve mode? What errors are in the dev tools?

**Comment by chrisfair** [comment]
@leaanthony I agree it should.    It works perfectly in serve mode.   I do not have any errors in dev tools I do have some warnings, but the program fires up and works correctly in serve mode.

**Comment by leaanthony** [comment]
@fdidron - did you build with the latest release or your fork? I'm wondering if the PR included everything? Can't understand why @chrisfair has the same issue. 

@chrisfair - you did update Wails right? `wails update`?

**Comment by fdidron** [comment]
@leaanthony I built against the latest release.

@chrisfair, One idea, I skipped a few versions of Wails with Wally. To make it work with v1.16, I had to migrate from mewn to embed to include the assets in the production build. That would explain things working in serve mode but not in build mode.

https://github.com/zsa/wally/commit/af7f115cb8248b43a5eb99ee891c7fc7dbf218a5#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R9

**Comment by chrisfair** [comment]
@leanthony I saw what @fdidron did I did the same thing I am not using mewn anymore I am using embed as well.     

Here is my screenshot....


![FailedDisplay](https://user-images.githubusercontent.com/4054917/114290582-d90b2180-9a3d-11eb-9113-545513fa9e4d.png)

**Comment by chrisfair** [comment]
Here is where I setup embedding the wails app now....

![Screenshot from 2021-04-10 20-52-50](https://user-images.githubusercontent.com/4054917/114290720-d4933880-9a3e-11eb-8d9c-d16845767704.png)

**Comment by leaanthony** [comment]
@chrisfair - is the repo publicly available so I can try it out?

**Comment by chrisfair** [comment]
@leeanthony https://gitlab.com/chrisfair/latin-catholic-prayers I must say you guys go above and beyond, this is basically just a little toy project of mine but I certainly appreciate the help :)   Thanks a ton.    I think it is public.

**Comment by leaanthony** [comment]
@chrisfair got a blank screen on Mac too which means the issue wasn't related to GTK. Looks like you fell into the same trap I tweeted about recently regarding `go:embed` syntax: you have a gap between `//` and `go:embed`. 

![Screenshot 2021-04-11 at 8 37 20 pm](https://user-images.githubusercontent.com/1943904/114301036-39fe2c80-9b06-11eb-8a3b-c0cdb1cde14b.png)

Fixing that then made Go complain about the import paths being invalid:

![Screenshot 2021-04-11 at 8 39 50 pm](https://user-images.githubusercontent.com/1943904/114301047-47b3b200-9b06-11eb-9b69-03173acc9e6c.png)

Fixing those made the app work:

![image](https://user-images.githubusercontent.com/1943904/114301058-5a2deb80-9b06-11eb-85c4-d5b07af38ca4.png)

**Comment by chrisfair** [comment]
Perfect!!!! Works for me now thanks for working through it.    I would never have looked at the space between the comment marker and the go:embed deal.    I can honestly say this is the best customer service I have ever received from open source or closed source you guys rock!    I do not know if you have ever checked out Fyne (the GUI lib) the one thing that they do that is very appealing is their packaging commands for mobile, windows, mac, and Linux.    If Wails had something like that it would be beyond awesome.   I only wanted to bring your attention to it but for windows, mac and Linux the way you set up wails is actually better for me the web tech makes it easier to coerce the interface to be the way you want it.

**Comment by chrisfair** [comment]
So yeah you can close this one for sure....sorry I did not realize what I needed to do on my own but you sure were helpful.

**Comment by leaanthony** [comment]
No problem.

**Comment by Innsmouth-trip** [comment]
I have a similar problem on gentoo linux(wails v1.16.6 / react 17.0.2), wails serve works (my project works perfect in the browser), wails build works, but when you run the build, it gives an error

[![error](https://i.imgur.com/0yhI3Wm.png)](https://i.imgur.com/0yhI3Wm.png)

webkit-gtk installed.
in main.go i rewrote the paths, because react creates files differently
//go:embed frontend/build/static/js/main.*.*.js
var js string
//go:embed frontend/build/static/css/main.*.*.css
var css string
[![error2](https://i.imgur.com/iDgrsIC.png)](https://i.imgur.com/iDgrsIC.png)

**Comment by leaanthony** [comment]
Are you sure your single `main.js` file is complete? There's a ton of chunks in your file list. What does the console say?

**Comment by Innsmouth-trip** [comment]
> Are you sure your single `main.js` file is complete? There's a ton of chunks in your file list. What does the console say?

➜  test ls frontend/build/static/js/main.*.js
frontend/build/static/js/main.515ed5a8.chunk.js

**Comment by mhalano** [comment]
Please reopen this  bug. I'm having this problem with 2.1.3, but didn't happen with 2.1.2.

**Comment by leaanthony** [comment]
If you can provide more details we can look at reopening it.

**Comment by mhalano** [comment]
There is not too much to say about it. I downloaded the version 2.1.3 from GitHub and got the same gray screen. I tried with 2.1.2 also from GitHub and worked fine. What information do you need? I can say I'm using Ubuntu 21.04 with i3 wm.

**Comment by leaanthony** [comment]
What's 2.1.3?

**Comment by mhalano** [comment]
Never mind. I'm posting in the  repo of the framework,  I should post in the repo of the software. Thanks anyway.

**Comment by awsomegui-capstone** [comment]
I just got the same error, although I can see my screen. I am doing front end authentication with AWS Cognito in React with amazon-cognito-identity-js library. In the web browser I am able to sign in and navigate through protected files, when I build it will not allow me to sign in and sends the same error

**Comment by leaanthony** [comment]
@awsomegui-capstone - I think this is a different scenario. If you think it's a Wails bug, please open with clear reproducible steps 👍
