### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#661]
### This project is great. How can I support it?
Testing, improving the [Documentation](https://github.com/wailsapp/docsv1), [Bugfixing](https://github.com/wailsapp/wails/issues), PRs or if you're feeling generous, [Sponsoring](https://github.com/sponsors/leaanthony) the project.

### Is Webview2 supported on Windows?
Not yet. 

### When do you plan on supporting Webview2 on Windows?
It is the next feature on the list for v2.

### What is the roadmap for Wails?
We are working hard on v2 of the project. Mac is 99.9% done and is [being used in production](https://xbarapp.com). The Windows port is up next and is being tracked in the [Windows port mega issue](https://github.com/wailsapp/wails/issues/622). Then the Linux port will be addressed (a lot of Linux code has already been done but is being prioritised behind Windows due to demand). The Linux port is being tracked in the [Linux port mega issue](https://github.com/wailsapp/wails/issues/623). Timescales are hard due as this is a volunteer effort, but realistically, both both ports should take about 10-12 weeks each, with help.

### How can I help with v2?
Please see [Helping with v2](https://github.com/wailsapp/wails/wiki/Helping-with-V2).

### My app is starting but I’m just getting a blank screen
Most likely, your application is using a non-IE11 compatible HTML or Javascript construct. Other causes can be the use of “browser APIs” that are not available in the mshtml webview, such as localstorage. Try running `wails serve` and opening up the application in IE11. Check the dev console for more details.

### My app has no dev console - I’m flying blind!
Check out the [Debugging Guide](https://wails.app/guides/debugging/#windows) for Windows.

### My app is using custom HTML and I’m getting a script error!
On Windows, you cannot reference external scripts in your HTML, EG: `<script src="main.js"></script>`.

### My app works with `wails serve` but not `wails build`. Why?
Most likely, your application is using a non-IE11 compatible HTML or Javascript construct. Other causes can be the use of “browser APIs” that are not available in the mshtml webview, such as localstorage.

When running the `<project>.exe` a script error window pops up. Why?
This is similar to the previous issue, make sure to run `wails serve` with devtools open to check that your app renders correctly. If the app renders in IE11 and does not after building, it is possible that you are using a browser feature that exists in IE11 and not in mshtml (ie. localstorage)

**Comment by TechplexEngineer** [comment]
@leaanthony Seems like this should not have been closed

**Comment by leaanthony** [comment]
Indeed

**Comment by hi019** [comment]
No Stalebot, thank YOU for your contributions
