### ISSUE TITLE
[v2] API Audit

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#665]
Whilst the aim of Wails v2 is feature parity with the Go and JS APIs, it's probably not practical. Some of the newer APIs have left the JS runtime behind. The aim of this ticket is to document what has been done so far, what the gap is and what gap we're happy with.

**Comment by akhudek** [comment]
It appears that events are not sent from Go to Javascript in V2 because the javascript side doesn't register any listener on the go side.

**Comment by akhudek** [comment]
Are there plans to support NotifyEvent in bridge mode?

**Comment by akhudek** [comment]
Unrelated to the above, for the typescript generation code, the switch away from `CreateApp` to `Run` means that the generate code can no longer find any bindings as it still looks for a `foo.Bind(...)` pattern. I'm assuming it was never updated to look inside the `Run` option map for bindings.

**Comment by leaanthony** [comment]
There's actually 2 TS generation modules. The one you're using is an interim solution and generates at runtime. It's **OK**, but you lose the names of the variables as Go doesn't retain those. The second is a static analyser that scans your project ahead of time. This is available via `wails generate`. I got stuck with it a while back so it hasn't been updated for a while. There is someone who has shown a real interest in that so I'm hoping it can get some love. The interim solution is kinda ok for now but i'd rather replace it with the static analyser

**Comment by akhudek** [comment]
Thought I'd move the vite feedback here. Two snags I've run into. One, by default vite adds file hashes to the built filenames. This is easily fixed with the following vite config:

```
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [reactRefresh()],
  build: {
    rollupOptions: {
      output: {
        entryFileNames: `assets/[name].js`,
        chunkFileNames: `assets/[name].js`,
        assetFileNames: `assets/[name].[ext]`
      }
    }
  }
})
```

The one I haven't fixed yet is that vite creates an `index.js` and a `vendor.js`. I haven't found a way to get it to add vendor to index. Alternately, if wails could take multiple js files in it's config that would also solve this.

**Comment by akhudek** [comment]
Actually, I take it back. I didn't realize the bundler inspects the html files and grabs everything it needs. Suffice to say a simple hello world using react + typescript with vite works fine in dev mode, but doesn't work in production mode. The production app just sits there doing nothing and doesn't pop up a window. Trying to debug but I'm at a bit of a loss without some sort of error message.

**Comment by leaanthony** [comment]
I'd like to try and tackle this but maybe using a different ticket? Really keen to get Vite working!

**Comment by akhudek** [comment]
Are you open to V2 pull requests? I implemented the notify support in the bridge since it was annoying without it, happy to throw it into a PR for you. It seemed pretty simple to implement, though maybe I'm missing something.

**Comment by leaanthony** [comment]
Absolutely !

**Comment by leaanthony** [comment]
No

**Comment by leaanthony** [comment]
Keep open
