### ISSUE TITLE
Mac computer build GOOS=windows GOARCH=amd64 error

### ISSUE THREAD

**Issue by zhujohnle** [wailsapp/wails#666]
when I build the test project with Mac computer
> go env -w CGO_ENABLED=0 GOOS=windows GOARCH=amd64 && go build -o out_binary main.go

the error occurred :

package command-line-arguments
	imports github.com/wailsapp/wails
	imports github.com/wailsapp/wails/lib/renderer
	imports github.com/wailsapp/wails/lib/renderer/webview: build constraints exclude all Go files in /Users/zhujiule/go/pkg/mod/github.com/wailsapp/wails@v1.16.2/lib/renderer/webview

**Comment by leaanthony** [comment]
Please read the documentation on how to build Wails apps. Thanks.
