### ISSUE TITLE
Windows builds fail to run after recent window.external change

### ISSUE THREAD

**Issue by aschey** [wailsapp/wails#668]
**Description**

With the recent change to fix webkit2gtk, the `window.external` variable gets assigned to every time the app starts up. When this happens in IE, it throws an error that "assignment to read-only properties is not allowed in strict mode".

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build` on Windows and open the app.

**Expected behaviour**
The UI will load.

**Screenshots**
![image](https://user-images.githubusercontent.com/5882266/114314043-c127b200-9abe-11eb-9158-805514c771d1.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.2 |
| Go Version    | go1.16.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.11 |
| Node          | v14.16.0
 |

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Fix merged and released. Awesome job!

**Comment by aschey** [comment]
Looks good, thanks for the quick release!
