### ISSUE TITLE
Package flag not ouputting files when compiling for Windows

### ISSUE THREAD

**Issue by charlie-haley** [wailsapp/wails#670]
**Description**

When compiling for Windows, using `wails build -p -x windows/amd64` no files are outputted into the `build` directory, however it works when I just use `wails build` on a Windows machine.

When the command finishes running it says `Awesome! Project 'flowcontrol' built!` but there's nothing in the `build` directory, if I delete the folder it creates it again but still no files created.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails build -p -x windows/amd64`'
2. Check `build` directory for packaged files

**Expected behaviour**
The files to be output upon packaging. 

![image](https://user-images.githubusercontent.com/27928201/114316318-f18d4180-9afa-11eb-9536-41fe8a696794.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.0 |
| Go Version    | go1.16 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.9.0 |
| Node          | v10.16.0|

**Additional context**
I'm currently running this command in WSL2, but I don't see why that would have an effect. `wails build -p` also works fine and outputs a binary for Linux.

Here's some details from WSL2 that I manually compiled as I can't raise `wails issue` inside WSL.
| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.2 |
| Go Version    | go1.16 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.2.0 |
| Npm           | 7.9.0 |
| Node          | v15.14.0|

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi. Thanks for the report. We were having some issues upgrading xgo to use go 1.16. There's already a ticket for that. I'll set up a matrix for platforms tested and add this info to it.

**Comment by charlie-haley** [comment]
> Hi. Thanks for the report. We were having some issues upgrading xgo to use go 1.16. There's already a ticket for that. I'll set up a matrix for platforms tested and add this info to it.

Awesome, thank you, looking forward to this working so I can use it in a CI pipeline

**Comment by leaanthony** [comment]
Hey there. Just an update, I recently got windows builds working from Linux. I may do a pre release to get that out. Would that interest you?

**Comment by charlie-haley** [comment]
> Hey there. Just an update, I recently got windows builds working from Linux. I may do a pre release to get that out. Would that interest you?

Yes please, more than happy to help test that out

**Comment by leaanthony** [comment]
Nice one. I'm looking to do that this weekend. Will let you know 👍

**Comment by leaanthony** [comment]
Closing this in favour of #649
