### ISSUE TITLE
wails init error

### ISSUE THREAD

**Issue by zhujohnle** [wailsapp/wails#671]
when i build my first wails project ,the error like this

tkone imports
	github.com/wailsapp/wails imports
	github.com/wailsapp/wails/lib/renderer imports
	github.com/wailsapp/wails/lib/renderer/webview: no Go source files
package tkone
	imports github.com/wailsapp/wails
	imports github.com/wailsapp/wails/lib/renderer
	imports github.com/wailsapp/wails/lib/renderer/webview: build constraints exclude all Go files in /Users/zhujiule/go/pkg/mod/github.com/wailsapp/wails@v1.16.3/lib/renderer/webview

**Comment by leaanthony** [comment]
https://wails.app/reference/cli/#build
