### ISSUE TITLE
error and no can fix for long time

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#672]
getting this error after run go get -u github.com/wailsapp/wails/cmd/wails
go: found github.com/wailsapp/wails/cmd/wails in github.com/wailsapp/wails v1.16.3
go: downloading github.com/pkg/browser v0.0.0-20180916011732-0a3d74bf9ce4
go: downloading github.com/Masterminds/semver v1.4.2
go: downloading gopkg.in/AlecAivazis/survey.v1 v1.8.4
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/fatih/color v1.7.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20190709130402-674ba3eaed22
go: downloading github.com/leaanthony/slicer v1.4.0
go: downloading golang.org/x/image v0.0.0-20200430140353-33d19683fad8
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/sirupsen/logrus v1.4.1
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/fatih/color upgrade => v1.10.0
go: github.com/sirupsen/logrus upgrade => v1.8.1
go: github.com/mgutz/ansi upgrade => v0.0.0-20200706080929-d51e80ef957d
go: golang.org/x/net upgrade => v0.0.0-20210410081132-afb366fc7cd1
go: github.com/Masterminds/semver upgrade => v1.5.0
go: gopkg.in/AlecAivazis/survey.v1 upgrade => v1.8.8
go: golang.org/x/sys upgrade => v0.0.0-20210403161142-5e06dd20ab57
go: github.com/pkg/browser upgrade => v0.0.0-20210115035449-ce105d075bb4
go: gopkg.in/yaml.v3 upgrade => v3.0.0-20210107192922-496545a6307b
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: golang.org/x/image upgrade => v0.0.0-20210220032944-ac19c3e999fb
go: golang.org/x/text upgrade => v0.3.6
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/leaanthony/slicer upgrade => v1.5.0
**/root/go/pkg/mod/github.com/wailsapp/wails@v1.16.3/runtime/assets.go:3:8: package embed is not in GOROOT (/usr/src/embed)**

When i go try run wails update, is show:
Command 'wails' not found, did you mean:
  command 'rails' from deb ruby-railties
Try: apt install <deb name>

**Comment by renozion** [comment]
im noob and bad english, im sorry almost giving up on this. just wanted to try mine vertcoin from my cpu.

**Comment by leaanthony** [comment]
Go 1.16 required. `~/go/bin` needs to be on your path. If this is still a problem please open an issue with `wails issue`.
