### ISSUE TITLE
How to build a single process in windows

### ISSUE THREAD

**Issue by c0618** [wailsapp/wails#674]
How to build a single process in windows

**Comment by leaanthony** [comment]
?

**Comment by tmclane** [comment]
What do you mean by single process?

**Comment by c0618** [comment]
> What do you mean by single process?

Yes

**Comment by c0618** [comment]
> 您所说的单一过程是什么意思？

windows platform *.exe can only be run once

**Comment by leaanthony** [comment]
This is a Go issue, not related to Wails. Good luck!
