### ISSUE TITLE
build win32 error

### ISSUE THREAD

**Issue by asd1235813** [wailsapp/wails#677]
**Description**

build window32 error

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.11.0 |
| Go Version    | go1.14.4 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.19.0
 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Please answer the questions in the template

**Comment by leaanthony** [comment]
Please reopen if you have any more feedback.
