### ISSUE TITLE
I upgraded from 1.16.0 to 1.16.3 and packaged under mac to start a black screen

### ISSUE THREAD

**Issue by kb-8-byte** [wailsapp/wails#678]
I upgraded from 1.16.0 to 1.16.3 and packaged under mac to start a black screen

golang  version  go version go1.16 darwin/amd64 

osx 
![image](https://user-images.githubusercontent.com/18651522/114898229-7f8f6200-9e44-11eb-9854-d56d3d9ea858.png)

![image](https://user-images.githubusercontent.com/18651522/114898229-7f8f6200-9e44-11eb-9854-d56d3d9ea858.png)

**Comment by leaanthony** [comment]
Please reopen this using `wails issue` and fill in the questions. Thanks.
