### ISSUE TITLE
I upgraded from 1.16.0 to 1.16.3 and packaged under mac to start a black screen

### ISSUE THREAD

**Issue by kb-8-byte** [wailsapp/wails#680]
I upgraded from 1.16.0 to 1.16.3 and packaged under mac to start a black screen

golang version go version go1.16 darwin/amd64
osx version  11.2.3

![image](https://user-images.githubusercontent.com/18651522/114958354-65ca3b00-9e95-11eb-96af-2d0a486e6421.png)

**Comment by leaanthony** [comment]
1.16.x onwards shouldn't be an issue, but just double check that you've updated your project to use go:embed . Details here: https://wails.app/releases/v1.16.0/

**Comment by leaanthony** [comment]
Please reopen if you have any more feedback.
