### ISSUE TITLE
Input problem under mac

### ISSUE THREAD

**Issue by kb-8-byte** [wailsapp/wails#681]
Input problem under mac 

![image](https://user-images.githubusercontent.com/18651522/115000256-2cb1bb00-9ed5-11eb-88ae-e800afb75596.png)

**Comment by simlelcf** [comment]
When I input English quotation marks, it is always automatically converted to Chinese quotation marks.

**Comment by leaanthony** [comment]
Yeah, I saw that for v2 and there is a way to disable it in Cocoa. I'll look to backport the fix 👍

**Comment by simlelcf** [comment]
want to know which version I should use to fix this problem

**Comment by leaanthony** [comment]
The one when it gets fixed 😃 I'll let you know here.

**Comment by simlelcf** [comment]
> 固定的那一个 😃 我会在这里告诉你。
think you

**Comment by leaanthony** [comment]
`v1.16.4-pre3` fixes this. If you want to try it: `wails update -pre`

**Comment by leaanthony** [comment]
@simlelcf any feedback?

**Comment by leaanthony** [comment]
Closing due to lack of feedback.
