### ISSUE TITLE
Vue3 vue-router@4 issue

### ISSUE THREAD

**Issue by milchinskiy** [wailsapp/wails#682]
**Description**

vue-router@4 has no mode field. Now it has history field. and the abstract option is no longer available now. Instead, there is createMemoryHistory, which is for SSR. But it doesn't work with it, just an empty window after the build.

**To Reproduce**
Steps to reproduce the behaviour:
1. Just run wails build -p -f with Vue@3 + vue-router@4 (typescript)

**Expected behaviour**
vue-router@4 works properly with wails

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.3 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.0 |
| Npm           | 7.9.0 |
| Node          | v14.15.5 |

_Note:_ wails serve wroks as expected

**Comment by milchinskiy** [comment]
I was wrong, the problem is not with vue-router. Wails is unfortunately not friendly with dynamically imported components. close this issue.

**Comment by leaanthony** [comment]
Some technologies are just built for the browser unfortunately. Most people get around the issue. There's a number of guides on the website.
