### ISSUE TITLE
[v2] A function with no return produces a Promise without a type.

### ISSUE THREAD

**Issue by akhudek** [wailsapp/wails#684]
**Description**
I have a function with no return value like this:
```
func (a *App) CloseProject() {
...
}
```

In `frontend/src/backend/index.js` it generates:

```
const backend = {
  main: {
    App: {
      /**
       * CloseProject
       * @returns {Promise}
       */
      CloseProject: () => {
        return window.backend.main.App.CloseProject();
      },
...
```
Curiously, even though the above Promise is in a comment, it causes typescript to generate an error and fail to compile.

**Expected behaviour**
I would expect it to generate `Promise<void>` for no return value.

**System Details**
Please provide your platform, GO version and variables, etc

`go version go1.16.2 darwin/amd64`

**Comment by leaanthony** [comment]
Hey, thanks for trying v2!! Nice catch. Easy fix 👍

**Comment by leaanthony** [comment]
What's the exact command you are using to generate this?

**Comment by akhudek** [comment]
Just `wails dev` with a struct member function that has no return value.

**Comment by leaanthony** [comment]
It's fixed on the `v2-alpha` branch. Will fix #685 before tagging

**Comment by leaanthony** [comment]
Also noticed that the location of the backend.js is still hardcoded so I need to add that to `wails.json`

**Comment by leaanthony** [comment]
`v2.0.0-alpha.65` should fix this @akhudek

**Comment by akhudek** [comment]
FWIW This looks like works now!

**Comment by leaanthony** [comment]
Thanks for getting this over the line!
