### ISSUE TITLE
[v2] @wails/runtime mixes import and module.exports =

### ISSUE THREAD

**Issue by akhudek** [wailsapp/wails#685]
**Description**
Using @wails/runtime v1.3.12 with webpack fails to build because `init.js` in the javascript runtime uses `import` but also `module.exports = ` which isn't allowed in webpack. 

**To Reproduce**
Import @wails/runtime as part of a webpack frontend.

**Expected behaviour**
`init.js` should either not use import or use `export default ...` instead of` module.exports = ...`.

**Comment by leaanthony** [comment]
Hadn't got to webpack yet so thanks for testing. Do you have an example before and after? I'll get both typescript fixes in.

**Comment by akhudek** [comment]
I just switched to vite so I don't have the old code anymore. Seems vite doesn't use webpack. That said, I fixed it by changing this line:

https://github.com/wailsapp/wails/blob/v2-alpha/v2/internal/runtime/js/runtime/init.js#L12

to:

```
const bridge = require('./bridge');
```

**Comment by leaanthony** [comment]
I'm wanting Vite to be the standard for serving frontend in `wails dev` so would love your input on that!

**Comment by akhudek** [comment]
Oh, I also had to add `ready` to the typescript definitions: 

https://github.com/wailsapp/wails/blob/v2-alpha/v2/internal/runtime/js/runtime/runtime.d.ts 

to get it fully working.

**Comment by leaanthony** [comment]
Ah nice catch. Ready was added relatively recently.

**Comment by akhudek** [comment]
So vite is interesting. It seems to work well so far, but obviously the default react typescript project skeleton it creates is not doing some type checks that were taking place with the create-react-app skeleton. For example, in VSCode I still get a type warning on ready, but vite still compiles and runs fine.

**Comment by leaanthony** [comment]
Finally got round to publishing `@wails/runtime v1.3.14` which includes the `init.js` change. Let me know how you get on! If it works for you, please feel free to close this issue.

**Comment by akhudek** [comment]
Everything seems to be working for me with 1.3.14. Thanks!
