### ISSUE TITLE
GCC + Libraries Download Offline

### ISSUE THREAD

**Issue by gazzer82** [wailsapp/wails#686]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
The linked download location for GCC + Libraries for windows is offline

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to link at http://tdm-gcc.tdragon.net/download
2. Page not found error

**Expected behaviour**
To be able to download the GCC + Libraries

- [X] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
This isn't a wails issue. Not sure what's going on with their site!

**Comment by gazzer82** [comment]
Yes agreed this isn't a Wails issue, sorry I just couldn't open a documentation issue, just bug or feature request.

Wasn't sure if this was a permanent/long term issue and if the docs needed updating therefor.

**Comment by leaanthony** [comment]
Looks like https://jmeubank.github.io/tdm-gcc/ might be the new home?

**Comment by leaanthony** [comment]
Updated the docs. Thanks for the heads up.
