### ISSUE TITLE
Custom tags in frontend index.html don't get transpiled.

### ISSUE THREAD

**Issue by hhhapz** [wailsapp/wails#687]
**Description**
Fonts specified using <link> tag are present during dev builds, but now when running `wails build`.

**To Reproduce**
Steps to reproduce the behaviour:

1. Add this to your index.html:
```
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
```
2. Run wails serve and npm run serve for dev build
3. See fonts being loaded
4. Run wails build with debug mode
5. See no <link> tag present (and font not loadd)

**Expected behaviour**
I would expect those styles to be present in the release version :(. Not sure how I should get my custom fonts to work otherwise.

**Screenshots**
Dev Version:
![image](https://user-images.githubusercontent.com/29532600/115270989-1458cf00-a167-11eb-8343-d73896aa9c70.png)

Release version:
![image](https://user-images.githubusercontent.com/29532600/115271161-41a57d00-a167-11eb-8933-e57da32938f1.png)

**System Details**
Not totally relevant I don't think but:
Arch Linux
Go 1.16.3
Wails v1.16.3

**Additional context**
I'm using the svelte template with nothing fancy modified

**Comment by hhhapz** [comment]
Not sure if this is a bug, or if there is an alternative method to achieve this functionality. Couldn't find anything in the docs :(

**Comment by leaanthony** [comment]
Hi. The only guaranteed way of getting any external asset to be part of your app is to bundle it. All decent packers support this and there are examples of this in the standard templates. Interesting that there was nothing in the docs that sprung out to you. Where would you expect to see this information? We can update the docs. I'm sure it's in there but might be able to extract that out as a guide.

**Comment by hhhapz** [comment]
Hey! Thanks for the prompt reply. I will look in to doing it with rollup. Not sure if I missed the page (however I admit I did not go over the tutorials very closely) however apart from really good explanations on how bridging communications worked (exposing, events) I admit I was a bit lost and just went with the flow with the svelte template provided. I come to wails after attempting to use electron and subsequently failing, so your tooling is 1000% more straight forward than electron for me at least. 

I will have to look into the other templates for sure then :). 

PS. I wonder, I was never able to find an API for creating child windows to the main process. Is this potentially on the road for wails? Or a limitation of the API.

**Comment by leaanthony** [comment]
Thanks for your kind words! The site *is* a little bit of a brain dump and it's pretty hard to maintain as there's just so much information. It absolutely needs to be redone for v2, so maybe we can start that early.

Multi-window was originally a limitation of the underlying webview library and I was hoping for v2 we could get multi window working. I'm absolutely *for* the idea but there have been other priorities.

**Comment by hhhapz** [comment]
That makes sense. One thing I really liked was having a concepts page. To be honest, just extending more and talking about how it works internally could be really helpful for those who want to dig deeper can get more configuration.  Maybe something that could be considered for v2

**Comment by leaanthony** [comment]
Sure will. There's just **so much to do** 👍
