### ISSUE TITLE
Provide a way to close the window

### ISSUE THREAD

**Issue by Naatan** [wailsapp/wails#693]
**Is your feature request related to a problem? Please describe.**

On Windows when calling `window.close()` a prompt is given;

![image](https://user-images.githubusercontent.com/278649/116308778-c6425d80-a75c-11eb-8a52-8c44a18663ad.png)

Far as I can tell there's no way to bypass this client-side.

**Describe the solution you'd like**

I should be able to terminate wails through Go code at the very least. Though it would be nice if wails provided the means to do this via the client through its runtime package.

**Describe alternatives you've considered**

I'm open to anything so long as the user experience is unaffected by the implementation.

**Comment by leaanthony** [comment]
Try using `runtime.Quit()` instead. I'm assuming you're trying to quit?

**Comment by Naatan** [comment]
Sorry, where do I find this? I scanned through both the Go and JS runtime packages and can't find any "Quit" method.

**Comment by leaanthony** [comment]
Ah, apologies, I meant `runtime.Window.Close()`. Your initial post was about using the JS method `window.Close()` right?

**Comment by Naatan** [comment]
Ah I see. That would work but the runtime is not exposed on the `App` struct: https://github.com/wailsapp/wails/blob/master/app.go#L45

**Comment by leaanthony** [comment]
You can call it either from Go or JS. It is given to you via any bound struct.
https://wails.app/reference/runtime/

**Comment by Naatan** [comment]
Ahh I see, I'll give that a go - thanks!

This is subjective of course but personally I would favour self documenting code. The reflection magic is much harder to understand without substantial documentation.

**Comment by leaanthony** [comment]
Happy to accept PRs! Please reopen if you still have issues. Cheers.
