### ISSUE TITLE
[v2] Vite + React + Typescript won't work in production mode

### ISSUE THREAD

**Issue by akhudek** [wailsapp/wails#694]
**Description**
If you create a new vite project using react and typescript and use it as the frontend build, dev mode works perfectly, but production mode doesn't. The application starts but then hangs and no window is ever popped up.

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init` A new v2 project.
2. `yarn create @vitejs/app` and select react and typescript.
3. In the new project `yarn install`.
3. Delete `frontend` and replace it with the new vite project (assuming renamed back to frontend).
4. In `wails.json` add `"frontend:build": "yarn build",` and change `html` to `frontend/dist/index.html`.
5. Build the project via `wails build` and try running it.

**Expected behaviour**
The hello world react page to show in the window.

**System Details**
go version go1.16.2 darwin/amd64
wails v2.0.0-alpha.65

**Comment by akhudek** [comment]
I dug into this one a bit. Aside from two unrelated bugs in the latest v2-alpha branch which I'll submit PRs for, the main problem appears to be that vitejs requires javascript module support. On starting the application I get the following error:
```
SyntaxError: Unexpected token '{'. import call expects exactly one argument.
``` 
I'm rather surprised by this, as I thought wkwebview used the same webkit and javascript engines as safari, but I suppose not? Vitejs does have legacy browser support via a JS module polyfill, but I haven't gotten it to work yet because of what I think is an error in the asset packaging triggered by the polyfill code.

**Comment by akhudek** [comment]
Ok, so the vite legacy support is designed only to engage for browsers that don't support ESM. But I think wkwebview does, so it ignores it. I'm at a loss why it's giving this error at this point. Very strange. The JS is included in a script tag that has type "module" which seems correct.

**Comment by leaanthony** [comment]
Thanks for your continued effort on this! Linking #630 as it's relevant.

**Comment by akhudek** [comment]
Ok, I've got this working. I swear I've tried this numerous times, but maybe I was importing things wrong in the html, dunno. In any case using library mode with *umd* format works, then you just need a production html that imports the umd files as a normal text/javascript.

**Comment by akhudek** [comment]
Another question, linked css files don't seem to be injected right. From my reading of the code they are just concatenated together with the JS and injected as a a single user script. To make it work I think the css needs to be wrapped in some JS code that injects it into the dom as inline CSS. 

Is this the right approach? Want to make sure I'm not missing something before implementing this.

**Comment by leaanthony** [comment]
Great work! CSS is injected using JS: when the assets are read up from the HTML, it is loaded, escaped and encapsulated with a JS call. That code is then encoded to the `assets.h` file. Turns out you can't search branches on the github webui so that may be working against you. The details are in this file: https://github.com/wailsapp/wails/blob/v2-alpha/v2/internal/html/asset.go

**Comment by akhudek** [comment]
Ok figured out why the css wasn't being pulled in. Created a fix in https://github.com/wailsapp/wails/pull/715.

**Comment by leaanthony** [comment]
Nice edge cases there. Thanks for getting.into the weeds and making test cases - it's a huge contribution! Will be looking at this today

**Comment by leaanthony** [comment]
Moving Vite related discussion to here: https://github.com/wailsapp/wails/discussions/717

**Comment by akhudek** [comment]
I have things working now, so closing this issue. I've explained my setup in #717
