### ISSUE TITLE
How do I add a Terminal

### ISSUE THREAD

**Issue by owlreddy** [wailsapp/wails#695]
I'm currently using wails to build an Application with Vue JS 3 and Go lang and I think adding a Terminal to my project would be a great addition. But I've never built anything terminal related in front-end and with wails no less. So, it would be great if someone could suggest How do I go about building a Terminal in a Wails application, which connects to local terminal and has same functionality as a local terminal.

**Comment by bh90210** [comment]
hello @csor-dev 
glad to help but can you please specify what is it exactly that you are after, cause it was not apparent to me at least from your above description?
Are you after building a terminal simulator using wails
or how to write a CLI of some sort?

**Comment by csor-dev** [comment]
Thanks @bh90210 
I'm looking to implement something like a terminal in VS Code within my Wails application.

**Comment by leaanthony** [comment]
Term.js might work

**Comment by csor-dev** [comment]
@leaanthony that project seems to be outdated and no longer maintained. But it seems to be forked from Xterm JS. Will check that out. Thank You :+1:
