### ISSUE TITLE
[v2] How navigate to another page when click traymenu?

### ISSUE THREAD

**Issue by cxfksword** [wailsapp/wails#696]
**Is your feature request related to a problem? Please describe.**
I'm working on a project, i want to when user click `settings` traymenu,  app can show settings page window directly. Now wails  can't find a way to navigate page use Go.

**Describe the solution you'd like**
wails can communicate with page js, then i can use `vue-router` to switch

**Describe alternatives you've considered**
Like electron's `BrowserWindow`, support create multiple windows.

**Additional context**

**Comment by cxfksword** [comment]
I found frontend can use `window.wails.Events` to communicate😂.

**Comment by leaanthony** [comment]
Multiple windows will not initially be supported for v2
