### ISSUE TITLE
tell Wails which gcc installation should be used (windows 64-bit, cc1.exe error)

### ISSUE THREAD

**Issue by Sculas** [wailsapp/wails#697]
**Description**

I have a 64 bit Windows 10 installation and it seems that I have a 32-bit version of MinGW installed because I am getting the error: "cc1.exe: sorry, unimplemented: 64-bit mode not compiled in" when running `wails init`. Is it possible for me to set which GCC installation Wails should use so I can tell it should use my 64-bit TDM-GCC installation instead of my 32 bit MinGW installation?

**To Reproduce**
1. Install MinGW32 on a 64-bit system
2. Install Wails and run `wails setup`. It should choose the 32-bit MinGW installation (GCC)
3. Create a new (react) project using `wails init`
4. Get an error after some time that says: "cc1.exe: sorry, unimplemented: 64-bit mode not compiled in" 

**Expected behavior**
This error is normal and should appear. But I want to be able to choose which GCC installation should be used, instead of Wails picking the wrong one.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 7.11.1 |
| Node          | v14.15.4 |

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by Lucaskyy** [comment]
As you can see, the default GCC installation is 32-bit.
```
C:\Users\User\go>gcc -print-prog-name=cc1
c:/mingw/bin/../libexec/gcc/mingw32/9.2.0/cc1.exe
```

**Comment by Lucaskyy** [comment]
I think my best bet is to put TDM-GCC higher in my PATH and see if that works.

**Comment by Lucaskyy** [comment]
Alright yeah, this fixes it. Would be nice to have this as a feature though.

**Comment by leaanthony** [comment]
Agree. Not sure how to indicate to Go which one to use.
