### ISSUE TITLE
Initialization fails

### ISSUE THREAD

**Issue by sagunkho** [wailsapp/wails#706]
**Description**

I'm trying to initialize a project but it fails with the following - 'C:\Users\Sagun' is not recognized as an internal or external command,

**To Reproduce**
```
C:\go-wails>wails init
Wails v1.16.3 - Initialising project

The name of the project (My Project):
Project Name: My Project
The output binary name (my-project):
Output binary Name: my-project
Project directory name (my-project):
Project Directory: my-project
Please select a template (* means unsupported on current platform):
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v4 template
  3: Svelte - A basic Svelte template
  4: Vanilla - A Vanilla HTML/JS template
  5: * Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
  6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 2
Template: React JS
> Generating project...
- Building project (this may take a while)...
Wails v1.16.3 - Building Application

> Ensuring frontend dependencies are up to date (This may take a while)
> Building frontend...
> Ensuring Dependencies are up to date...
'C:\Users\Sagun' is not recognized as an internal or external command,
operable program or batch file.


Error: exit status 1

! exit status 1
Error: exit status 1
```

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.3 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.12 |
| Node          | v14.16.1
 |

**Comment by leaanthony** [comment]
Looks like you might have a space in your path. 
Previous issue: https://github.com/wailsapp/wails/issues/491  
npx issue: https://github.com/npm/npx/issues/14

**Comment by captv89** [comment]
**Description**
Initialization fails in OSX

**To Reproduce**
wails init
Selected Option 5 = Vue 3 for Frontend

**Tail Error**
```
npm ERR! In file included from ../src/binding.cpp:1:
npm ERR! In file included from ../../nan/nan.h:56:
npm ERR! In file included from /Users/Scorpion/.node-gyp/16.2.0/include/node/node.h:63:
npm ERR! In file included from /Users/Scorpion/.node-gyp/16.2.0/include/node/v8.h:30:
npm ERR! /Users/Scorpion/.node-gyp/16.2.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/Scorpion/go-Projects/deskApp/calc/frontend/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.4.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.2.0/bin/node" "/Users/Scorpion/go-Projects/deskApp/calc/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/Scorpion/go-Projects/deskApp/calc/frontend/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Scorpion/.npm/_logs/2021-05-23T13_41_14_510Z-debug.log


✗ Ensuring frontend dependencies are up to date (This may take a while)
Error: exit status 1

✗ exit status 1
Error: exit status 1
```

**Full Debug Log File:**
[2021-05-23T13_41_14_510Z-debug.log](https://github.com/wailsapp/wails/files/6528179/2021-05-23T13_41_14_510Z-debug.log)

**Additional Info:**
- Tried with Other Frontend option like Angular as well. The Intialisation fails.
- Have ensured `xcode-select --install` is correct

**Comment by leaanthony** [comment]
Looks likethere's some incompatibility with latest node? Have you tried with node 12?

**Comment by captv89** [comment]
@leaanthony Yes i do believe Vue3 and Angular fronted fails to initialize in latest node versions (16.x). However I tried with React frontend in the latest node 16.x and it initializes without any problem.

I downgraded to node 12.22.1 and tried to initialize with Vue3, it runs without any problems. Thank you!

**Comment by leaanthony** [comment]
@captv89 - does #729 fix this for you?

**Comment by captv89** [comment]
@leaanthony I tried out in the node stable version 14.x it builds without any errors, I am working with this. 
However In the latest version of node 16.x  the `wails init` fails.
Front-end used for both these cases were `Vue3`
Log file attached for your reference.

[2021-06-06T16_17_05_584Z-debug.log](https://github.com/wailsapp/wails/files/6604492/2021-06-06T16_17_05_584Z-debug.log)

**Comment by leaanthony** [comment]
Feels like we need to keep track of which versions of npm are compatible with which templates? If we can decide on what that looks like I think I can squeeze it into v2
