### ISSUE TITLE
Failing to generate a Wails / Full VueJS 3 project

### ISSUE THREAD

**Issue by loloof64** [wailsapp/wails#707]
**Description**

I've just setup my Fedora 34 for Wails development, then tried to generate a new project. But it fails.

**To Reproduce**

Cannot be reproduced, may be specific to my environment.

**Expected behaviour**

The new project is generated.

[2021-05-05T17_19_17_534Z-debug.log](https://github.com/wailsapp/wails/files/6429059/2021-05-05T17_19_17_534Z-debug.log)

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.3 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 11.1.1 |
| Npm           | 7.10.0 |
| Node          | v16.0.0 |

**Additional context**

I am using Fedora 34 64 bits. And my NodeJS has been installed with [NVM](https://github.com/nvm-sh/nvm).

**Comment by leaanthony** [comment]
Hi. The error is coming from building the libsass library. Have you tried installing using stock node.js rather than nvm?

**Comment by loloof64** [comment]
Thank you for your answer. I'm removing nvm setup, and installing node from my host package manager instead :)

**Comment by loloof64** [comment]
I confirm it was a problem with the NVM version of NodeJS.

**Comment by leaanthony** [comment]
Glad it was sorted 👍
