### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by elie-g** [wailsapp/wails#710]
**Is your feature request related to a problem? Please describe.**
I can't read command line arguments for my program. I tried using [cobra](/spf13/cobra) to read arguments but I get a `no such flag` error when I try to run `wails serve`.

**Describe the solution you'd like**
First of all, it would be nice if wails wouldn't crash whenever there's a flag set that it doesn't recognize.

Secondly, I suggest to use `--` as a separator between wails options and the application options to be able to specify command line arguments for the application (not wails).

**Additional context**
![image](https://user-images.githubusercontent.com/14944216/117559724-b9274780-b055-11eb-935a-827f8a831504.png)

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.3 |
| Platform      | linux |
| Arch          | amd64 |
| GCC           | 10.2.0 |
| Npm           | 7.11.2 |
| Node          | v16.1.0 |

**Comment by leaanthony** [comment]
Hi. You are correct. This is a good candidate for an enhancement. Will add it to the list!

**Comment by leaanthony** [comment]
Pushed a fix for this on the `develop` branch. It will pass through any args after the `wails serve` command. EG: `wails serve hello world` will call your app with `[hello world]` args.

**Comment by DrunkenPoney** [comment]
I tried using the develop branch of wails. I can build with custom arguments defined but I still can't serve with custom arguments.

<details>
<summary>Custo arguments with `wails serve`</summary>

![image](https://user-images.githubusercontent.com/14944216/118749313-43786400-b82b-11eb-94c2-7d2fe5946bb2.png)

</details>

<details>
<summary>Custom arguments with built program</summary>

_**Note:** for some reason, the help message and the error are printed twice._

![image](https://user-images.githubusercontent.com/14944216/118749461-8afef000-b82b-11eb-87ac-664251f47f2a.png)

</details>

**Comment by leaanthony** [comment]
Hey haven't forgotten about this, just been slammed! This is on my todo for the weekend!

**Comment by leaanthony** [comment]
@DrunkenPoney - I've pushed a new update to `develop` that should work by passing through any args after a `--` parameter. I've not had chance to test but it should work. Please let me know how you get on!
