### ISSUE TITLE
Close window without crashing

### ISSUE THREAD

**Issue by adaml881** [wailsapp/wails#711]
**Is your feature request related to a problem? Please describe.**
I have a background application which requires a GUI for login only. Once logged in, I'd like to close the window and the application to continue running it's other functions. When I run `runtime.Window.Close()` the window stays in a "Not Responding" state (in windows)

**Describe the solution you'd like**
I'd like to just be able to open and close windows when required.

**Describe alternatives you've considered**
I'm thinking of making the application restart itself once the login through GUI is complete.

**Comment by leaanthony** [comment]
If your app is mainly a service that only needs a gui for login, I don't think Wails is a good fit. I'd personally just spawn a browser window to do the login and get that to post back to your background service. If you close the window in v1, it's the equivalent of exiting. I just tried `runtime.Window.Close()` on a basic application and it worked as expected. If you are able to post code that reproduces the close issue then feel free to reopen this ticket. Good luck.
