### ISSUE TITLE
How to start app maximized?

### ISSUE THREAD

**Issue by nilopaim** [wailsapp/wails#719]
I know how to enter app in fullscreen mode, but I want only the app maximized. 

Is there any way to do this?

Maybe could we have a parameter to wails.CreateApp? Like "Maximized: true"?

I'm using Wails v1.16.3, Windows 10, 64 bits.

**Comment by nilopaim** [comment]
I did a simple hack...

On installed wails, file webview.h, change SW_SHOWDEFAULT by SW_SHOWMAXIMIZED on line 1588.

I know, it's ugly,but solves temporarily my problem.

As I said, the ideal solution would be a parameter in wails.CreateApp. I think it would be nice have a runtime method either.

**Comment by leaanthony** [comment]
That's a great suggestion and one I haven't thought of. It feels like it would conflict with `fullscreen` so maybe something like `initialWindowState`: Normal | Max | Fullscreen. That being said, there IS a Maximise() method in v2 that you could use to do this during startup.

**Comment by nilopaim** [comment]
Is v2 ready for production on Windows?

**Comment by leaanthony** [comment]
No

**Comment by leaanthony** [comment]
@nilopaim - are you desperate for this in v1?
