### ISSUE TITLE
Chromium Support for Windows

### ISSUE THREAD

**Issue by HerbertHe** [wailsapp/wails#724]
**Is your feature request related to a problem? Please describe.**
With the development of frontend technology, Microsoft also tends to use chromium as browser core instead of IE. 

And the author of Vue, Even You, also said that would not support ie11 anymore in Vue3. It's a good news for all frontend developers, due to the bugs of IE. 

So I hope the great project can support chromium instead of IE. Whatever the Microsoft Edge or Chrome, they both use chromium as core, the wonderful V8 engine provides perfect support for JavaScript! This is the future! 

**Describe the solution you'd like**
I hope the project can support chromium in Windows! 

**Describe alternatives you've considered**

**Additional context**

**Comment by hi019** [comment]
Have you seen Wails v2? It supports the new Edge which is based on Chromium.

**Comment by leaanthony** [comment]
Hi @HerbertHe - it is part of v2 (still in Alpha right now). We are all very much looking forward to it 😄

**Comment by HerbertHe** [comment]
> Hi @HerbertHe - it is part of v2 (still in Alpha right now). We are all very much looking forward to it 😄 

😂 sorry I just saw the official document, it said only support IE~

**Comment by HerbertHe** [comment]
> Have you seen Wails v2? It supports the new Edge which is based on Chromium. 

@hi019 sorry, I just saw the official document about Windows

**Comment by leaanthony** [comment]
Yes current version only supprts IE11
