### ISSUE TITLE
feat: html use http protocol

### ISSUE THREAD

**Issue by d1y** [wailsapp/wails#725]
I want to use `http://baidu.com` load(just like)

How do i solve it now

```go
app := wails.CreateApp(&wails.AppConfig{
		Width:            1024,
		Height:           768,
		HTML:             `<script type="text/javascript">window.location.href='http://127.0.0.1:3000'</script>`,
		DisableInspector: false,
	})
```

This solution seems silly!

How to achieve it

thank you

**Comment by leaanthony** [comment]
If you want to wrap an external website, it's better to use https://github.com/webview/webview. Wails isn't for this use case.
