### ISSUE TITLE
wails init NPM failure Angular template

### ISSUE THREAD

**Issue by Snider** [wailsapp/wails#728]
**Description**

When you run wails init name you get a npm error, --legacy-peer-deps needs adding to the npm install for my version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new project `wails init app`
2. Pick Defaults & Angular
3. See error

**Expected behaviour**
to install the shell of an app without error

**Screenshots**
![image](https://user-images.githubusercontent.com/631881/120329877-2ee4a300-c2e4-11eb-8ae0-1926e288013d.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.2 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.3.0 |
| Npm           | 7.14.0 |
| Node          | v12.21.0 |

**Additional context**
The fix for me was editing the created project.json
```
  "install": "npm install",
```
to this
```
  "install": "npm install --legacy-peer-deps",
```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hey there, thanks for raising this. Am I right in thinking that `--legacy-peer-deps` was introduced in npm 7? I've just tried the flag with npm 6.14.13 and it appears to not error out, which is good. Just wondering what the implications are for people using npm < 7

**Comment by snider** [comment]
Hiya,

I did some more digging into it as I'm having issues getting images to load. it wasn't this. 
but `--legacy-peer-deps` would have no effect on people using v6 and older if the cli doesn't error out. 

The change introduced in v7 is it now resolves the peer dependencies, it never used to do that so most packages didn't know about versioning issues.

* to save you a search. Peer Dependencies: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major.html

**Comment by leaanthony** [comment]
Images need to be bundled using rollup/webpack or base64 encoded
