### ISSUE TITLE
Add flag to disable elastic scroll on Mac?

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#73]
Versions prior to the beta release has scrolling disabled by default to prevent elastic scroll but it was a fairly heavy-handed approach to stop it as it disabled all scrolling. Would anyone be interested in this as a config option or should this be dealt with in [css](https://gist.github.com/Subash/fe82b0c1ba53347a2399#gistcomment-2262895) only?

**Comment by luizfonseca** [comment]
Hey @leaanthony, 
To be honest with you, an option to disable `scrollBounce` would be nice, since even with CSS it might not work sometimes (it'd also affects other elements I guess)

**Comment by leaanthony** [comment]
The only Objective-C code I was able to get working related to this was to disable scrolling of the webview component itself. Maybe a combination of this plus `overflow: scroll` may do it. If you want to experiment, I can give you the details on how to enable it.

**Comment by leaanthony** [comment]
Hi @apelican! You're just the person we've been waiting for :-) 

The line that we used to have to disable scrolling is [here](https://github.com/wailsapp/wails/blob/develop/lib/renderer/webview/webview.h#L1997). I commented it out as it disabled all scrolling, not just elastic scrolling. After a lot of research I read that it was probably better to do it in CSS, but I left it on the back burner. The longer term strategy is to have feature flags that may be passed into your app to toggle platform specific stuff that would get ignored on incompatible platforms.

Regarding Objective-C, we have an issue with the latest WebView not working correctly. Our local ticket is [here](https://github.com/wailsapp/wails/issues/33). I closed it because WebView is pretty much unsupported so we were looking at alternatives, potentially helping [this project](https://github.com/patr0nus/DeskGap) with moving out their windowing library (which has way better support for native WebViews than the WebView project does. Is this something you feel like you could help with?

**Comment by apelican** [comment]
While CSS is edging close to template stuff I'd prefer not to rustle, maybe we can quickly document the correct directives to use for now while we plan platform option flags out.

As for webview, I'm sorry to hear that, but happy to hear there are projects you feel meet the need for Wails to operate with some work. Is the thinking a golang wrapper around some refactor of their windowing API, or something else?

**Comment by leaanthony** [comment]
My proposal would be to pass a flags into the constructor:
```
app := wails.CreateApp(&wails.AppConfig{
    Width:  1024,
    Height: 768,
    Title:  "Quotes",
    JS:     js,
    CSS:    css,
    Colour: "#131313",
    Flags: wails.Flags{ "elasticScroll": false },
  })
```
Regarding Webview, the version we use has deprecated APIs so we are trying to work out why the latest (6 months old!) doesn't work. If we can work that out then it'd give us some breathing space to look at porting Deskgap by adding a thin Go wrapper. Thoughts?

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Comment by filipviz** [comment]
Is this available in v2? Not seeing any mention on the docs.

**Comment by leaanthony** [comment]
That's the recommended approach 👍

**Comment by michalrus** [comment]
But this approach breaks both in the entire webapp:
- scroll chaining,
- elastic over-scroll of other scrollable elements inside the non-scrollable `body`/`html`

Also the [link above is to `develop`](https://github.com/wailsapp/wails/blob/develop/lib/renderer/webview/webview.h#L1997) instead of a specific commit, so obviously broken after 6 years.

Also, the recommended approach above (`overscroll-behavior: none`) is not in line with [the one in the docs (`overflow: hidden`)](https://wails.io/docs/next/guides/overscroll).
