### ISSUE TITLE
runtime.Dialog.SelectFile("Select a file") is error in mac

### ISSUE THREAD

**Issue by kb-8-byte** [wailsapp/wails#732]
1. macos 11.4
2. Wails v1.16.4-pre3 

log 

![image](https://user-images.githubusercontent.com/18651522/121130005-58f81100-c860-11eb-9ee8-f69da771f290.png)

**Comment by leaanthony** [comment]
It says it is expecting a pointer receiver so I think the error is in how you are using it. What's your code?

**Comment by simlelcf** [comment]
![image](https://user-images.githubusercontent.com/18651522/121144619-bc8a3a80-c870-11eb-83e0-6ee5bea2d2c7.png)

**Comment by leaanthony** [comment]
![image](https://user-images.githubusercontent.com/1943904/121167232-169cf700-c895-11eb-89dd-7cdb3dd7d7a1.png)
