### ISSUE TITLE
React, Webpack integration, embedding static assets

### ISSUE THREAD

**Issue by amlwwalker** [wailsapp/wails#733]
**Description**

I have been through the issues on github and came across a response saying to embed assets such as fonts into the binary you need to use webpack. I noticed you had done this with Vue, and I also noticed someone else saying they were trying with React.

I am using react and so far everything is great, but I can't figure out from these clues in Issues as to what I need to do. My guess is its reasonably straight forward, however my understanding is you have modified React scripts for Wails and as a result Im not sure if you have a solution already to assets in React.
In my frontend/ directory I have another directory: 

![image](https://user-images.githubusercontent.com/2920180/121334278-6de0ad00-c911-11eb-9ac8-27eb99ebbdc2.png)

The scss is working fine, however the scss is calling font assets such as 

```
@font-face {
 font-family: 'AvertaStdPERegular';
 src: url('/assets/fonts/AvertaStdPERegular/font.woff2') format('woff2'), url('/assets/fonts/AvertaStdPERegular/font.woff') format('woff');
}
```

however I cant work out what I need to change for these fonts to be embedded in. I was thinking perhaps I could use the go embed command on the directory however that will give me a filesystem and I don't think I can use that from frontend.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.4-pre3 |
| Go Version    | go1.16.2 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.0 |
| Npm           | 6.14.9 |
| Node          | v14.15.3 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi @amlwwalker - The templates are just examples - you can use whatever you like in the frontend directory. The only thing you need to do is wrap your main "mounting" code with `Wails.Init()` and make sure that your `project.json` has the correct npm commands. 

With that said, your specific issue is a bundling one, not a react one. The react template was a contribution so I'm not 100% across it, but essentially what I'd be doing is looking at the webpack configuration of Vue and including the image bundling parts. This may also be of help: https://masteringjs.io/tutorials/webpack/url-loader

**Comment by amlwwalker** [comment]
Hey, thanks so much for this. Will have a look. I've always deployed with create-react-app so never had to worry about webpack, I guess now is the time for me to learn 😄 

OK, I'll try to get my head around the Vue webpack - this is the Todo list app right thats bundling assets in webpack? 

Re v2 

a) any rough timelines on this. Will be a game changer
b) have you considered whether it can be compiled for a phone? That would be sweet


Thanks re got-qt. I'm generally very interest Golang UIs and got-qt was a goal to try and build android/phone apps with just Go. Would be cool to replace Qt with Wails for the frontend if you ever have considered it

**Comment by leaanthony** [comment]
You aren't restricted to webpack. You're not even restricted to the templates. I really need to update the docs on this as it's a common conversation. The only thing that you need to worry about is that [these](https://github.com/wailsapp/wails/blob/master/cmd/templates/vuebasic/template.json#L7-L10) settings are correct and that whatever those scripts do, they dump out a javascript and css file containing everything in them. The names of those files don't matter, you just set them in your `main.go`.

v2 timelines - "this year". The reality is that it won't be a big bang event immediately. It's close to feature parity for v1 right now.
Regarding phone targets - there has been some interest but it won't be in scope until v3.

**Comment by amlwwalker** [comment]
Hmm, so what would be interesting... If I use go embed to embed some static files (fonts, images) how could I link to them from frontend/react allowing me to avoid webpack?
Be good if could do a go embed filesystem.... I assume this is what you mean by not being restricted to webpack, but not sure how to reference those files from front end? Unless I serve them as base64 and a JavaScript function calls a function from the binding that responds with the b64 and set it as the image source? What are your thoughts?

**Comment by leaanthony** [comment]
The url-loader plugin i mentioned above will embed fonts and images like you want. Mixing frontend assets like fonts and `go:embed` will end in tears 😄

**Comment by amlwwalker** [comment]
Hey, So I've been fiddling with my understanding of Wails and my understanding of Webpack (in react). In a straight up react app, I'm having no trouble, but I seem to be struggling with webpack and wails as I think there is some auto magic Im not getting with the wails-react scripts potentially.

To be clear, I have:

- `src/App.js` which imports `import './assets/dashboard.scss';`

which in turn contains
```
// Myfonts.com - use the 'Webfont Kit Download' configuration
@import url("//hello.myfonts.net/count/3e7d84");

@font-face {
    font-family: 'AvertaStdPERegular';
    src: url('/assets/fonts/AvertaStdPERegular/font.woff2') format('woff2'), url('/assets/fonts/AvertaStdPERegular/font.woff') format('woff');
}
@font-face {
    font-family: 'AvertaStdPESemibold';
    src: url('/assets/fonts/AvertaStdPESemibold/font.woff2') format('woff2'), url('/assets/fonts/AvertaStdPESemibold/font.woff') format('woff');
}
@font-face {
    font-family: 'AvertaStdPEBold';
    src: url('/assets/fonts/AvertaStdPEBold/font.woff2') format('woff2'), url('/assets/fonts/AvertaStdPEBold/font.woff') format('woff');
}
```

I have then put in the root of the `frontend` directory the following webpack configuration

```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
    plugins: [
        new HtmlWebpackPlugin({
            title: "Encrypt Easy",
        }),
    ],
    entry: {
        main: path.resolve(__dirname, "./src/app.js"),
    },
    output: {
        filename: "[name].bundle.js",
        path: path.resolve(__dirname, "deploy"),
    },
    optimization: {
        minimize: false,
    },
    module: {
        rules: [
            {
                test: /\.(png|jpg|gif)$/i,
                use: [
                    {
                        loader: "url-loader",
                        options: {
                            limit: 8192,
                            mimetype: "image/png",
                            encoding: true,
                        },
                    },
                ],
            },
            {
                test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                            outputPath: 'assets/fonts/'
                        }
                    }
                ]
            }
        ],
    },
};
```

When I run the app with `wails serve` etc, I get the fonts in the browser (realise this is a dev mode) however on `wails build -p -d` I do not get the fonts in the compiled app

Where I am confused is whether or not webpack is even running at this stage when wails builds the app and if so, how i can do some tests/checks to understand why the above could be failing - its all very graceful during building, nothing to suggest there was any frontend error.

P.S i tried doing an `yard add webpack` to the frontend, but that causes an error as it seems wails is indeed importing webpack somewhere along the line and that then causes a conflict. Any tips advice appreciated, i am fully aware you are not here to necessarily debug react apps/webpack, however I feel there is something I am msissing in terms of building the wails app correctly

**Comment by leaanthony** [comment]
@bh90210

**Comment by bh90210** [comment]
hello @amlwwalker 
I have to say I very much regret not documenting better what I did.

I'd assume the reason `serve` works but `build` not is related to how react-scripts handle the different sictuations
```json
    "serve": "react-scripts start",
    "build": "react-scripts build",
```

looking at the commits I found this https://github.com/wailsapp/wails-react-scripts/blob/75f92220c9843df8be47515283bc1eb1eec7517d/config/webpack.config.js#L347
so `name: 'static/media/[name].[ext]',` should be reachable? 

is the code in question public so I can take a look and give a couple of tries as after two years I really can not remember what was that I changed.

**Comment by amlwwalker** [comment]
Hey @bh90210  thanks so much for your help. I have added you to the project (too embarrassed to make public!) You should have an email invite (I might have added you to the wrong repo to start with so it will be the latest eail). In the frontend directory there is 

```
│   │   ├── assets
│   │   │   ├── dashboard.scss
│   │   │   ├── encrypteasy.scss
│   │   │   └── fonts
│   │   │       ├── AvertaStdPEBold
│   │   │       │   ├── font.woff
│   │   │       │   └── font.woff2
│   │   │       ├── AvertaStdPERegular
│   │   │       │   ├── font.woff
│   │   │       │   └── font.woff2
│   │   │       └── AvertaStdPESemibold
│   │   │           ├── font.woff
│   │   │           └── font.woff2
```

so those are the fonts Im trying to add to the project referenced from the scss files. Any help greatly appreciated! Thanks

**Comment by bh90210** [comment]
yes saw it and accepted it, cloned and tried to default run things and I get errors, I am giving it a second look on my own BUT if we could move this convo to slack (#wails channel) it would be fantastic as it feels it will speed things up

**Comment by amlwwalker** [comment]
amazing thank you - yes will find you on slack - much better. Probably tomorrow now, but would love to know what build errors you got as I tried it prior to pushing and it built fine
