### ISSUE TITLE
unrecognized import path "embed"

### ISSUE THREAD

**Issue by aaqeel87** [wailsapp/wails#734]
Hi, 
- am using go latest 1.15.6 windows/amd64
- vs code
- installed all the pre-request
when running 'go get -u github.com/wailsapp/wails/cmd/wails' 
I get this error 
-----------------------------------------
package embed: unrecognized import path "embed": import path does not begin with hostname
-----------------------------------------
tried both Windows and Ubuntu just in case some bash issues with Windows. 
Appreciate your help

**Comment by leaanthony** [comment]
Go 1.16+ required 👍
