### ISSUE TITLE
Wails doesn't work on Windows vsCode

### ISSUE THREAD

**Issue by aaqeel87** [wailsapp/wails#737]
having issue installing Wails on Windows: 

---------- pre-request info -----------
[GO] go version go1.16.5 windows/amd64
[GCC] gcc version 10.3.0 (tdm64-1) 
[NPM] 6.14.13

$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\devo\AppData\Local\go-build
set GOENV=C:\Users\devo\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\devo\Desktop\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\devo\Desktop\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\devo\AppData\Local\Temp\go-build554072029=/tmp/go-build -gno-record-gcc-switches

--------------- end of requirement ------------

ISSUE
using _Git-bash_ instead of _vsCode terminal_ to get Wails
after that
[error] bash: wails: command not found
-----------------------------------
Thanks in advance

**Comment by leaanthony** [comment]
You GOBIN is not set.

**Comment by aaqeel87** [comment]
Thanks @leaanthony for quick response. 
I've tried setting GOBIN by 

export GOBIN=[WorkspacePath]\\bin

set GOBIN=C:\Users\devo\Desktop\go\bin

but still got same issue
