### ISSUE TITLE
Support Distribution 'Garuda Linux'

### ISSUE THREAD

**Issue by ashis0013** [wailsapp/wails#738]
**Description**
Distribution 'garuda' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | garuda |
| Distribution Name   | Garuda Linux |
| Distribution Version   |  |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
As Garuda is based on arch, you should be able to easily add support following this guide: https://wails.app/guides/distro/
Please create a PR and I'll get it in the next release 👍
