### ISSUE TITLE
trying to install with latest  garuda-xfce-linux-lts-210507 iso  and it hangs at the step of a start job is running for Livemedia MWHD script

### ISSUE THREAD

**Issue by gvogts** [wailsapp/wails#739]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)
![garuda boot issue 19 06 2021](https://user-images.githubusercontent.com/86157454/122652296-5dfd7000-d13e-11eb-8726-2ffd5aea0569.jpg)

**Comment by leaanthony** [comment]
Hi. Looks like you opened this on the wrong project. If you have any issues with Wails, please open a new ticket answering the questions in the template. Good luck.
