### ISSUE TITLE
Svelte   Windows

### ISSUE THREAD

**Issue by countnazgul** [wailsapp/wails#742]
**Description**

Im trying to run an Svelte app under Windows. Starting the backend and frontend is without an issue but when open the app in the browser im getting an error `_export is not a function`. Checked the documentation about developing in Windows and added the `browserlist` section to package.json but no luck. Tried messing with the rollup config file but this did not resolved it. Any guidance how to run Svelte under Windows?

**To Reproduce**
Steps to reproduce the behaviour:
1. Be on Windows
2. run `wails init`
3. start the backend and the frontend
4. open the frontend in the browser

**Expected behaviour**
See the default page

**Screenshots**
![image](https://user-images.githubusercontent.com/22850/123435990-135c7780-d5c6-11eb-8cda-8170dab5ee9d.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.11 |
| Node          | v14.16.0
 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi there. Can you confirm if this is an issue with the included template?

**Comment by countnazgul** [comment]
I do think its an issue with the template yes.

**Comment by leaanthony** [comment]
It's working for me here:
![image](https://user-images.githubusercontent.com/1943904/123506409-593d3c80-d6a7-11eb-8264-c21ff4f94c43.png)

`npm -version`: 6.14.6

**Comment by countnazgul** [comment]
Odd. It must be something with my system then.
btw If i comment the `babel` section in `rollup.config.js` then its working fine (at least in Chrome/FF)

**Comment by leaanthony** [comment]
It might be your node version. What do you have?

**Comment by countnazgul** [comment]
v14.16.0

**Comment by leaanthony** [comment]
Sorry I meant npm!

**Comment by countnazgul** [comment]
not a problem
v6.14.11

**Comment by DaviPolita** [comment]
Same error here.
node v12.22.3
npm 6.14.13

**Comment by leaanthony** [comment]
I'll check this weekend.

**Comment by DaviPolita** [comment]
Just did some tests and got the same error on diferent platforms.

Windows 7 - Svelte Template
Windows 10 - Svelte Template
WSL Ubuntu 20.04 - Svelte Template
WSL Ubuntu 20.04 - React Template

**Comment by countnazgul** [comment]
@leaanthony by any chance did you had the time to look into this?

**Comment by leaanthony** [comment]
Hey, I didn't. Hold on a week or so 😉

**Comment by misitebao** [comment]
@leaanthony 
Has this problem been solved yet?

**Comment by leaanthony** [comment]
Technically yes? :-)
I genuinely can't reproduce this with v1.
@countnazgul - I got delayed by one week so eyes peeled for this weekend :-)

**Comment by misitebao** [comment]
@leaanthony 
I know what the problem is, it seems that webview2 does not support esmodule. I also encountered this problem when I was going to use vite.

**Comment by leaanthony** [comment]
Finally I can suggesting using the v2 beta 😃

**Comment by countnazgul** [comment]
Yep. v2 beta works fine for me! 🥳🥳🥳
