### ISSUE TITLE
[v2] windows - Dialog.OpenFile() fails on selection & cancel

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#743]
**Description**
On windows runtome.Dialog.OpenFile() throws an error both when a file is selected and when the dialog is cancelled, than the whole process hangs, wont respond to ctrl+c, or alt+f4, you have to kill the process.

What I can see is on windows the dialog always returns an array of file paths. An array with one item to be exact, if you cancel the dialog its an empty string. 

If I change the **data** variable from string to []string in internal\ffenestri\ffenestri_client_windows.go:35 the issue goes away and everything works as expected. As I can see the Linux side of things is a bit behind and I can't test it on a Mac, so I don't know if it a good solution or not.

Tried to figure out the hanging part of the issue as well, but could't find the cause.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project.
2. Open a file dialog via Dialog.OpenFile().
3. Cancel the dialog or open a file.
4. See error => "ERROR | Message Dispatcher | json: cannot unmarshal array into Go value of type string"

**Expected behaviour**
Get the path to the selected file.

**Screenshots**

internal\ffenestri\ffenestri_client_windows.go:171

![image](https://user-images.githubusercontent.com/8627125/123497110-03777e80-d62c-11eb-924a-6ad2c66b2281.png)

error with some dump:

![image](https://user-images.githubusercontent.com/8627125/123497090-e3e05600-d62b-11eb-9d81-2e0cf4f17446.png)

possible fix, change string => []string
internal\ffenestri\ffenestri_client_windows.go:35

![image](https://user-images.githubusercontent.com/8627125/123497181-6406bb80-d62c-11eb-8ef7-059fb3946d36.png)

**System Details**
App Type:               desktop
Platform:               windows 10
Arch:                   amd64
Compiler:               go
Compress:               false
Build Mode:             debug
Package:                false
Clean Build Dir:        false
KeepAssets:             false
LDFlags:                ""
Tags:                   []
Go version:        1.16.5

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by Lyimmi** [comment]
As a side not, I think the project is turning out to be great. :)

**Comment by leaanthony** [comment]
Hey, thanks for the report. This part is currently being worked on. Should get a fix out this weekend.

**Comment by leaanthony** [comment]
Just to give more context, OpenFile should just return a single string: It's for a single file. Multiple file selection has moved to OpenMultipleFiles and that returns a slice of strings.

The odd thing about your report is that i'd tested this pretty heavily before committing. I'll check again this weekend.

**Comment by leaanthony** [comment]
Nice pickup. Looks like it was a bad commit on my side. Fixed in v2.0.0-alpha.68.

**Comment by Lyimmi** [comment]
Indeed, it works now.
