### ISSUE TITLE
[v2] windows - build ignores production mode when -ldflags are present

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#746]
**Description**
This might be the intended behavior, but its a bit confusing.
The build command ignores production mode when ldflags are passed. (Ignores all ldflags set by wails.)

As you can see below this produces two sets of ldflas, I think the user provided flags should be added to the existing ldflags, without duplicating them. Gather all flags in a slice, then add them to the command once. Or use a map with the flags as keys, than create the slice from that. :\

pkg\commands\build\base.go: 233 - 259

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project.
2. Build with: $ wails build -production -upx -ldflags="-s -w"
3. Start the program
4. See that a the program starts in debug mode.

**Expected behaviour**
I expected that ldflags set by me would be merged with the flags set by wails.

**System Details**
go: 1.16.5
Wails CLI v2.0.0-alpha.68
App Type:               desktop
Platform:               windows 10
Arch:                   amd64
Compiler:               go
Compress:               true
Build Mode:             production
Package:                false
Clean Build Dir:        false
KeepAssets:             false
LDFlags:                "-s -w"
Tags:                   []

**Additional context**

pkg\commands\build\base.go:270  commands.AsSlice() without ldflags:
```
([]string) (len=8 cap=8) {
 (string) (len=5) "build",
 (string) (len=2) "-a",
 (string) (len=5) "-tags",
 (string) (len=7) "desktop",
 (string) (len=8) "-ldflags",
 (string) (len=19) "-w -s -H windowsgui",
 (string) (len=2) "-o",
 (string) (len=54) "C:\\Users\\Lyimmi\\projects\\jsonedi\\build\\bin\\jsonedi.exe"
}
```

pkg\commands\build\base.go:270  commands.AsSlice() with ldflags:
```
([]string) (len=10 cap=16) {
 (string) (len=5) "build",
 (string) (len=2) "-a",
 (string) (len=5) "-tags",
 (string) (len=7) "desktop",
 (string) (len=8) "-ldflags",
 (string) (len=19) "-w -s -H windowsgui",
 (string) (len=8) "-ldflags",
 (string) (len=5) "-s -w",
 (string) (len=2) "-o",
 (string) (len=54) "C:\\Users\\Lyimmi\\projects\\jsonedi\\build\\bin\\jsonedi.exe"
}
```

**Comment by leaanthony** [comment]
Great catch. Agree with your assessment.will fix tomorrow

**Comment by leaanthony** [comment]
`v2-alpha` has a fix

**Comment by Lyimmi** [comment]
It works nicely.
