### ISSUE TITLE
It is possible to develop wails on Linux?

### ISSUE THREAD

**Issue by sandrwich** [wailsapp/wails#75]
**Description**

I tried to use wails on linux and init command generates files but I cannot figure out how to run it. I only found issue #2, but this does not clarify if I can use this on Linux.

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init`
2. `wails serve`

**Expected behaviour**
Default generated code should be working.

**Command Line**
```bash
$ wails serve
Wails v0.11.9 - Serving Application

✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Awesome! Project 'HelloWails' built!
Serving Application: /media/dawid/Workspace/GoLandProjects/go/src/hello-wails/hello-wails
Error: fork/exec /media/dawid/Workspace/GoLandProjects/go/src/hello-wails/hello-wails: exec format error
```

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.11.9 |
| Go Version    | go1.10.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by PinkLolicorn** [comment]
Ok, I just removed binary by hand and executed `wails serve` again, it's working now.

**Comment by leaanthony** [comment]
Linux is absolutely supported! Getting an exec error is pretty interesting
and feels more like a platform mismatch when compiling. Did you have GOOS
set to something in your environment? It could be that it could interfere
and to that end, it should be fixed. Let me know if you can reproduce.
