### ISSUE TITLE
request for  resize ,move  window  and no menubar 

### ISSUE THREAD

**Issue by dwdcth** [wailsapp/wails#750]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1.  Add function  resizeTo,resizeBy,moveTo,moveBy   to Runtime.Window,  so that can dynamic change window size and position.
Because browser disable these functions.
2.  Add no menubar config to  wails.AppConfig . just like this 
![image](https://user-images.githubusercontent.com/1883728/124090182-2ae4a600-da87-11eb-8440-3946de46c382.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by leaanthony** [comment]
This won't be in v1 but is part of v2. Feel free to check the `v2-alpha` branch. Docs will be updated for early adopters soon

**Comment by dwdcth** [comment]
ok

**Comment by leaanthony** [comment]
This is currently working on `master` for Windows v2
