### ISSUE TITLE
Vue 3 Support for Windows

### ISSUE THREAD

**Issue by mikolertesx** [wailsapp/wails#751]
I know there are a lot of intricacies that I can't understand about why Vue 3 is not supported but Vue 2 is, and I've wondered, since I don't even have the skills to even fathom the reason why one is supported and the other not. (I've seen some people talk about Dynamic imports not being liked by windows, and I wonder if that's the reason).

**The solution I'd like?**
Being able to create Vue-3 Apps, it's not that important, but I want to hear what's the current consensus regarding this.

If anything, I'm grateful for providing the great framework that wails is, I'm sorry if this is something I shouldn't be asking, and I hope my English is good enough to describe what I'm trying to say.

**Comment by leaanthony** [comment]
Hi. Vue 3 doesn't support IE11 so cannot be supported by Wails (windows). V2 uses WebKit so will support it no problem.

**Comment by mikolertesx** [comment]
I guess that makes a lot of sense hahaha.
