### ISSUE TITLE
Allow log level for "wails serve"

### ISSUE THREAD

**Issue by Mokto** [wailsapp/wails#752]
**Is your feature request related to a problem? Please describe.**
Hi, right now we can set log level for builds but not for wails serve.

**Describe the solution you'd like**
Adding -loglevel to wails serve

Thanks!

**Comment by leaanthony** [comment]
Yeah, not a bad idea. I'll add this to V2.

**Comment by Mokto** [comment]
Thanks!

**Comment by Mokto** [comment]
not stale
