### ISSUE TITLE
[V2] Unable to run `go get` on Windows 10

### ISSUE THREAD

**Issue by nickarellano** [wailsapp/wails#753]
**Description**
I am currently unable to run the follow command on a fresh installation of Windows
`go get -u github.com/wailsapp/wails/v2/cmd/wails`

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh installation of the most current Go version
2. Wails v1 fully installed and everything works
3. Run `go get -u github.com/wailsapp/wails/v2/cmd/wails`
4. Returns error `system.go:114:12: undefined: syscall.Sysctl`

**System Details**
Windows 10
go version go1.16.5 windows/amd64

**Comment by leaanthony** [comment]
Hey thanks for bringing this up. I'm not sure you can install like this until it's merged with master. In the meantime please try `go get -u github.com/wailsapp/wails/v2/cmd/wails@v2-alpha`

**Comment by nickarellano** [comment]
Thanks for the quick response! So this was able to generate the binary but I'm getting an exit code 1 on build. I'll check on my other machine tomorrow.

**Comment by leaanthony** [comment]
I noticed @tmclane has pushed what looks like a fix. Could you try again?

**Comment by leaanthony** [comment]
Hey, thanks for the sponsorship @nickarellano. I can't find any way of contacting you other than here, so thank you!

**Comment by tmclane** [comment]
Ha I fixed it because it prevented compilation on a Mac.
Didn't realize it impacted any other platforms.

**Comment by nickarellano** [comment]
I really appreciate the work you are doing, so I'm happy to sponsor you.

Just ran a fresh go get attempted to run wails build:

```
Installing frontend dependencies: Done.
Compiling frontend: Done.
Building assets: Done.
Compiling application:

ERROR: exit status 1
```

**Comment by leaanthony** [comment]
I'll fix this as a priority today

**Comment by leaanthony** [comment]
You can get more information passing `-v 2" to the command. I mean it should be outputting the error so that's another thing I'll look at

**Comment by nickarellano** [comment]
I'll re run a build shortly with that option to see what I get. Everything works great on macOS, no build issues or anything. It's just my windows machine I'm testing on.

**Comment by leaanthony** [comment]
Oh! I thought this was Mac. I'm developing Windows right now so it's a bit unstable. That said, it should still work. Appreciate your time testing this!

**Comment by nickarellano** [comment]
Just tested on my Windows laptop and everything works well, so I just have to troubleshoot what is going on with my Windows VM.

Wails is so exciting lol one day I'll be able to stop using Electron :D

**Comment by leaanthony** [comment]
That's great news! Be aware that projects get generated with a replace line in `go.mod` for development reasons. You may wish to check this. The v2 docs are really sparse right now and I'll look at getting something up in the next couple of weeks as the API gets stable. Good luck!

**Comment by nickarellano** [comment]
Yeah that was something I just ran into and figured out before I checked the response you sent :) thanks for everything!
