### ISSUE TITLE
Front end error in IE11 console

### ISSUE THREAD

**Issue by drognisep** [wailsapp/wails#754]
**Description**

Using the supported Vuetify template, running it results in a console error 'ReferenceError: 'ShadowRoot' is undefined'. This seems to relate to the side menu panel, because opening it and clicking outside of the menu results in another error ''ShadowRoot' is undefined' and 'Unable to get property 'lastMousedownWasOutside' of undefined or null reference'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project with `wails init`. Choose the Windows supported Vuetify template (change package.json).
2. Once everything is setup, run `wails serve` in the project root directory, and `npm run serve` in the front end directory.
3. Open the frontend URL in IE11, and launch dev tools by pressing F12 (may need to refresh the page to catch the error shown above).
4. Next, open the side menu and click outside of the menu, the second error will be shown.

**Expected behaviour**
No errors with template. Side menu should close when clicking outside of it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8890988/125177535-3bd99980-e1a2-11eb-8ade-0d108df58d66.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.5 |
| Go Version    | go1.16 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.13 |
| Node          | v14.17.3
 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)
- Core js is included in main.js in the template, and I updated browserlist in package.json.

**Comment by drognisep** [comment]
This seems isolated to IE11/mshtml, as Chrome doesn't show this problem.

I tried running `wails build` to confirm this is a problem in mshtml, and it looks like it's still an issue there.
![image](https://user-images.githubusercontent.com/8890988/125177884-15692d80-e1a5-11eb-89fa-8ed6be31da84.png)

**Comment by leaanthony** [comment]
Hi. Thanks for reporting this. Seems like a vue/ie11 bug. I'll be honest, I'm not going to spend time looking at this as V2 is a priority and all this goes away with that. If you're adventurous you could try V2 :-) Docs are a bit thin right now but I'll be pushing more this week. If you can find the solution, I'd be very happy to accept a PR.

**Comment by drognisep** [comment]
Well, at least you're honest @leaanthony. 😋
I'm definitely looking forward to v2 for Windows. I'll try it out and see what I can do with it.
