### ISSUE TITLE
WebView2 Question: HTML Tooltip on Links

### ISSUE THREAD

**Issue by nickarellano** [wailsapp/wails#759]
**Description**

On Windows, anytime I hover over any link to a page, there is a tooltip that shows a bunch of HTML as pictured below. Does anyone know how to prevent this?

<img width="1069" alt="Screen Shot 2021-07-16 at 10 31 13 AM" src="https://user-images.githubusercontent.com/13930605/125972407-fb070ba4-c9e3-433e-a657-2a5501c5ec2c.png">

**Comment by leaanthony** [comment]
Have you tried using a different tag to "a" and adding an onclick handler?

**Comment by nickarellano** [comment]
It would be nice to be able to use Vue Router vanilla

**Comment by nickarellano** [comment]
I was able to successfully remove the href with Vue Router and still keep the route matching functionality. So as of right now everything is absolutely golden. I have 0 more issues now. All the quirks are accounted for and the Windows and macOS builds have full parity :)

**Comment by leaanthony** [comment]
Awesome work! These questions come up often. Would you be up for contributing a sample project to the examples repo?

**Comment by nickarellano** [comment]
@leaanthony I would be more than happy to!
