### ISSUE TITLE
Need cross-compile support

### ISSUE THREAD

**Issue by sandrwich** [wailsapp/wails#76]
Currently, it looks like you can create bundle for Windows only on Windows. I like to be able do this on Linux as well.

https://github.com/karalabe/xgo looks good for this purpose.

**Comment by PinkLolicorn** [comment]
I think this should be labeled as `linux`, `enhancement` but I overlooked option to open normal issue. Cannot change that.

**Comment by leaanthony** [comment]
This is definitely something we need to look at. It's currently in the [roadmap](https://wails.app/project_status.html#roadmap) for post v1.0.0 as there's a bit of research to do. There have been a [number of issues](https://github.com/zserge/webview/issues?utf8=%E2%9C%93&q=is%3Aissue+xgo+) raised on the Webview issue tracker about xgo. I think it's possible, but something that will need time to look at. If you make any headway with it, please keep us informed. Thanks.

**Comment by leaanthony** [comment]
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page
