### ISSUE TITLE
"wails" not defined

### ISSUE THREAD

**Issue by jaroteko18** [wailsapp/wails#760]
**Description**

I can't use it when I build. But when I use "serve" to debug. It works!

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.5 |
| Go Version    | go1.16.6 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.3.0 |
| Npm           | 7.19.1 |
| Node          | v14.17.3
 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Please provide steps to reproduce
