### ISSUE TITLE
`wails build -p` fails on darwin when go.mod uses a replace directive

### ISSUE THREAD

**Issue by tinyzimmer** [wailsapp/wails#761]
**Description**

I think the title sums it up. Basically, I am writing a wails app that is rooted in a subdirectory of a larger app. It uses go packages from the other app. Build works fine for linux amd64 and arm, but darwin always fails when it gets to trying to pull down go modules. It can't find the `go.mod` at `/go.mod` in the `xgo` container. 

**To Reproduce**
Steps to reproduce the behaviour:

In your go.mod add a line like this:

```gomod
replace github.com/my/awesome-app => ../
```

Try to run:

```sh
wails build -p -x darwin/amd64 --verbose
```

**Expected behaviour**

It should build, or perhaps the CLI should have a way for me to mount additional volumes in the `xgo` container?

**System Details**

Reproduced on:

```sh
go version go1.16.6 linux/amd64
go version go1.16.6 darwin/amd64
```

**Comment by leaanthony** [comment]
Hey there. Darwin and the xgo container currently don't talk to each other so that might be part of the problem. If you fancy looking at that, I'll help as much as I can. Does the project work with a native build?

**Comment by tinyzimmer** [comment]
Yea it does work with a a native build actually. I started poking around the xgo issue but didn't have time to dig too deep.
