### ISSUE TITLE
Unchanged template - cross compile, build for windows error

### ISSUE THREAD

**Issue by ahmadissa** [wailsapp/wails#763]
**Description**

I tried building the initial template using wails build -x windows/amd64, its giving error cc1: fatal error: /build/my-project.rc: Permission denied, I can see that it did create my-project.rc file in my project root directory

**To Reproduce**
Steps to reproduce the behaviour:

wails init (followed the cmd steps to create vuetify2 template)

then run:
wails build -x windows/amd64

results

```
Wails v1.16.5 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Pulling wailsapp/xgo:1.16.3 docker image... (may take a while)
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
cc1: fatal error: /build/my-project.rc: Permission denied
compilation terminated.
/usr/bin/x86_64-w64-mingw32-windres: preprocessing failed.


Error: exit status 1
```

ls on the root directory of the project:
```
appicon.png  build  frontend  go.mod  go.sum  main.go  my-project.exe.manifest  my-project.ico  my-project.rc  project.json
```

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.5 |
| Go Version    | go1.16.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.3.1 |
| Npm           | 6.12.0 |
| Node          | v12.13.0 |

**Additional context**

Building os Fedora 33

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi. That sounds like a docker mounting problem. What's that docker warning as I've never seen that before. Does it work with previous versions of docker?

**Comment by ahmadissa** [comment]
Hi @leaanthony, thanks for your reply, I tried on Fedora 33 and Debian 10, same results

I have followed the steps in the below link:

https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

Basiclly I run the below before the build command

```
su -c "setenforce 0"
```

I got the below:

```
wails build -x windows/amd64
Wails v1.16.5 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Pulling wailsapp/xgo:1.16.3 docker image... (may take a while)
✓ Packing + Compiling project for windows/amd64 using docker image wailsapp/xgo:1.16.3...
*** Please note: Windows builds use mshtml which is only compatible with IE11. For more information, please read https://wails.app/guides/windows/ ***
Awesome! Project 'My Project' built!

```

However I didnt get any exe file, not sure if I am doing anything wrong

**Comment by fcwoknhenuxdfiyv** [comment]
I got the same result using Docker in rootless mode. Running the build with `-verbose` showed permissions errors.

From previous experiments with Podman, I found success with permissions problems by mounting with the `,Z` flag. It would be great if we could use Podman to reduce the gaping security hole of using Docker in root mode.

**Comment by fcwoknhenuxdfiyv** [comment]
Oops @ahmadissa! I just read your change to the source code and you use the `Z` option. Weird because that normally solved the problems with Podman for me.

**Comment by leaanthony** [comment]
Can this be closed now?
