### ISSUE TITLE
Windows platform prompts an error

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#764]
**Description**
The packaged application failed to run.

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init -n demo-wails-v2-vanilla
2. wails build
3. run the exe file generated in the build/bin directory

**Expected behaviour**
I hope to display a window whose content is the default template

**Screenshots**
![](https://cdn.jsdelivr.net/gh/misitebao/CDN@main/md/20210726093247.png)

**System Details**
Name | Value
-- | --
Wails Version | Wails CLI v2.0.0-alpha.73
Go Version | go version go1.16.3 windows/amd64
Platform | windows
Arch | amd64
GO111MODULE | (Not Set)
GCC | gcc version 9.2.0 (tdm64-1)
Npm | 6.14.13
Node | v14.17.1

**Additional context**
Because there is no v2 document yet, I don't know what special processing needs to be done in windows.

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by misitebao** [comment]
Perhaps this problem and the problem mentioned in (#756)  are the same, but I did not find a suitable solution.

**Comment by leaanthony** [comment]
I can't reproduce.
![image](https://user-images.githubusercontent.com/1943904/127476805-08962b57-d23e-4859-b9a5-5ac965530cc8.png)
