### ISSUE TITLE
Have a CI friendly output when building

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#768]
**Is your feature request related to a problem? Please describe.**
I am running Wails in a CI (Github Actions) and the output is:
```sh
⣷ Building frontend...
⣾ Building frontend...
⣽ Building frontend...
⣻ Building frontend...
⢿ Building frontend...
⡿ Building frontend...
⣟ Building frontend...
⣯ Building frontend...

✓ Building frontend...
25h25l
⣾ Ensuring Dependencies are up to date...
⣽ Ensuring Dependencies are up to date...
⣻ Ensuring Dependencies are up to date...
⢿ Ensuring Dependencies are up to date...
```

It's a lot of noise and could be more concise.

**Describe the solution you'd like**
I think we could introduce a non-interactive mode that is CI friendly. 

**Describe alternatives you've considered**
None.

**Additional context**

<img width="925" alt="Screenshot 2021-07-30 at 14 00 47" src="https://user-images.githubusercontent.com/4662842/127649943-6c4af8b2-16b4-4719-bca8-1cd9bd4ec20f.png">

**Comment by leaanthony** [comment]
This is handled by v2 `-q` flag. v1 is semi feature freeze right now.

**Comment by ValentinTrinque** [comment]
I am ok with this :)
