### ISSUE TITLE
Have a non-interactive setup command

### ISSUE THREAD

**Issue by ValentinTrinque** [wailsapp/wails#769]
**Is your feature request related to a problem? Please describe.**
I would like to leverage the verification done by `wails setup` in the CI so it's crystal clear that wails finds the dependencies it needs to work.

**Describe the solution you'd like**
Add a `--name` and `--email` flags to the `wails setup` command. That could make the command play nicely with non-interactive shell, such as CI.

**Describe alternatives you've considered**
Not executing it, but that's a shame to not leverage this command when setting up wails.

**Additional context**
None.

**Comment by leaanthony** [comment]
This will be handled by v2. v1 is semi feature freeze right now.

**Comment by ValentinTrinque** [comment]
I am ok with this :)
