### ISSUE TITLE
Give users more choice for front-end development

### ISSUE THREAD

**Issue by HerbertHe** [wailsapp/wails#770]
**Is your feature request related to a problem? Please describe.**
I'm a front-end developer, thanks too much for this wonderful project. When I initialized a Wails project, I found that it's very slow and no response for me. 

Then, I checked for the directory structure of the template. I think it would be better that allow the developer to choose install front-end packages later and the package manager!

Sometimes, it's **slow** and **inconvenient** to install packages from `npm.js`. We would use our own package manager instead of `npm`, and install private packages which are not from `npm.js`. So I suggest that provide a choice for the developer to install packages later by themselves. `yarn` and `pnpm` are also good choices, users need choose the package manager by themselves.

**Describe the solution you'd like**
In my opinion, the feature can be added as followed:

- provide a flag `--fast` to skip the packages installing process
- Or, give a question and get answer from users

**Comment by HerbertHe** [comment]
@leaanthony Thanks for replying, but still I want to skip the install process in initial. Or, I need to remove the node_modules, lock file and reinstall again. For example, the package manager `pnpm` uses different way to store packages info by `pnpm-lock.yaml` instead of `package-lock.json`. What's more, `pnpm` uses symlink to store packages and it's incompatible with `npm`, so I think this is meaningful!

> - provide a flag `--fast` to skip the packages installing process
> - Or, give a question and get answer from users

**Comment by leaanthony** [comment]
You can use whatever you like for the frontend, there's no constraints for templates. Just delete the frontend directory and update your project.json

**Comment by HerbertHe** [comment]
Ah, I just want to improve first time speed☹️

**Comment by leaanthony** [comment]
Ah we can do that. I'll add a `-nobuild` flag.

**Comment by HerbertHe** [comment]
Thanks!

**Comment by leaanthony** [comment]
I've changed the default behaviour to "no build". If you want to build then you can use `wails init -build`. Please update using `wails update` and close the ticket if this works for you 👍

**Comment by HerbertHe** [comment]
Thanks a lot, I would try it later~

Could you please consider providing no template choice? I have checked all templates, empty template just need to include example config as advanced use~ I would try to adapt other frameworks to Wails, it would be a good idea.

**Comment by leaanthony** [comment]
Just delete the frontend directory and update project.json with whatever you replace it with

**Comment by HerbertHe** [comment]
I know how to do that🌚 but still think it would be a nice idea for improving developing experience～

**Comment by leaanthony** [comment]
Noted. Closing as your original concern was addressed.
