### ISSUE TITLE
Whether the window program can be configured to run with administrator privileges by default?

### ISSUE THREAD

**Issue by binary4cat** [wailsapp/wails#774]
I wonder if it can be configured at build time. By default, the generated window program requires administrator privileges to run?
Or how it needs to be done, which I’m not familiar with, and I’m sorry to bother you.

**Comment by leaanthony** [comment]
I think privileges like this are at the application level.

**Comment by YiXuTa** [comment]
A workaround.

Edit  this file  ./build/windows/installer/project.nsi

add following two lines 
```
 WriteRegStr HKCU "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$INSTDIR\${PRODUCT_EXECUTABLE}" "RUNASADMIN"
 WriteRegStr HKCU "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$DESKTOP\${INFO_PRODUCTNAME}.lnk" "RUNASADMIN"
```
after 
```
CreateShortCut "$DESKTOP\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"
```

then run `wails build -nsis`  again to build the installer
