### ISSUE TITLE
Making my Wails app full screen/maximised

### ISSUE THREAD

**Issue by lleonard609** [wailsapp/wails#782]
Hey,

I'm making an application with wails and was wondering if there was any way to start my app maximised?

(I know this isn't a big but I don't really know where to ask this kind of question)

**Comment by marcio199226** [comment]
I you missed it will be available from [v2](https://github.com/wailsapp/wails/blob/v2-alpha2/v2/pkg/options/options.go#L17)
I don't know if you could achieve this with v1

**Comment by leaanthony** [comment]
@HiddenIpex what OS are you targetting?

**Comment by HiddenIpex** [comment]
I'm mainly targetting macOS and Windows.

**Comment by leaanthony** [comment]
This work is in v2. Please feel free to try it out. Mac port should be available by end of month (but no guarantees!)
