### ISSUE TITLE
How can put these chunk-xxx.js  and chunk-xxx.css into wails.app

### ISSUE THREAD

**Issue by longit123** [wailsapp/wails#783]
I have download a Vue+ElementUI admin UI，and it is a very large, then  it generate a lot of chunk-xxx.js and chunk-xxx.css files in dist directory

I follow the official document ，the normal usage is set app.js and app.css in main.go file

when i build the wails.app, it build success, but when i running the app, it shows blank,  i inspect the app, it show chunk-xxx.js file is not found（because the vue generate app.js include these chunk-xxx.js）

how can i use these chunk-xxx files in main.go？？？

**Comment by chenyang351** [comment]
![image](https://user-images.githubusercontent.com/30063958/130736934-3bb9b52b-050f-4bc7-876b-2bc66dfdc5ce.png)

**Comment by leaanthony** [comment]
There's no explicit support for that scenario in v1. It's expecting bundles. v2 is different, but it's not ready yet.

**Comment by misitebao** [comment]
@longit123 
If you use v1, you can try to change the webpack configuration to pack the script file and the css file into separate files.

**Comment by leaanthony** [comment]
If you are targeting Windows, I suggest you try migrating to v2: https://wails.io/blog/wails-v2-beta-for-windows

**Comment by leaanthony** [comment]
Let us know if you need more help.
