### ISSUE TITLE
Getting an error when running wails build

### ISSUE THREAD

**Issue by lleonard609** [wailsapp/wails#784]
**Description**

Whenever I run wails build, I get some sort of Script Error, saying "Unable to get property '_' of undefined or null reference". It tells me the Code is 0, the line is 1, and the char is 13. (I don't know if that's useful so I put it in just to be sure)

I read over the Windows documentation and it says I'm using a **non-IE11 HTML or JavaScript construct** because it worked with ``wails serve`` and not ``wails build``, but I'm just using a **HashRouter** from React-Router-Dom.

**Screenshots**
![Script Error](https://user-images.githubusercontent.com/68133615/130755238-64cb2ddf-b762-421c-8272-709389e3a942.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.6 |
| Go Version    | go1.16.7 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.3.0 |
| Npm           | 7.19.1 |
| Node          | v15.8.0
 |

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Did you wrap your JS in the `Wails.Init()` method? https://github.com/wailsapp/wails/blob/master/cmd/templates/create-react-app/frontend/src/index.js#L10-L17

**Comment by HiddenIpex** [comment]
> Did you wrap your JS in the `Wails.Init()` method? https://github.com/wailsapp/wails/blob/master/cmd/templates/create-react-app/frontend/src/index.js#L10-L17

How do I do that?

**Comment by leaanthony** [comment]
Have you tried running this on another platform to see if there's a JS error somewhere?

**Comment by leaanthony** [comment]
I feel your pain on the Windows front. There's some big news just on the horizon that makes all this go away ;-)

**Comment by HiddenIpex** [comment]
> Have you tried running this on another platform to see if there's a JS error somewhere?

I haven't, I'll give it a go later.

> I feel your pain on the Windows front. There's some big news just on the horizon that makes all this go away ;-)

That's great! I can't wait.

**Comment by KoduIsGreat** [comment]
Just chiming in here, one of my collegues has a similar issue where it says Cannot read property 'send' of undefined anytime they attempt to run the compiled form, but seems to work with wails serve. they are on windows as well. the odd bit is that I am also on windows, and with the exact same code I do not see this problem.

**Comment by leaanthony** [comment]
Ah, the mystery of Windows... 😃 yeah, but that's really odd. I'll have a fix available this weekend!

**Comment by KoduIsGreat** [comment]
FWIW my issue was caused by differing js dependencies, not particularly an issues with wails, although that being said i cant wait for v2!

**Comment by leaanthony** [comment]
v2 Beta is now out. Please try it out as it supports your use case! https://wails.io
