### ISSUE TITLE
How can i get a exist store from backend use javascript

### ISSUE THREAD

**Issue by Virgil-N** [wailsapp/wails#785]
I want to create a store in backend and then in frontend i want to send a event or call a function to backend to update store.

1. I create a store in backend.
2. I create a function like ` func (s *SomeStore) SetStore(str string) { s.store.Set(str) } ` to update store.
3. I bind SomeStore use ` app.Bind(NewSomeStore()) `.
4. I call ` window.backend.SomeStore.SetStore("new value") `, but failed.

So, I mean store can be modified only by backend and is only saved in backend, frontend can only call backend function to modify store. There is no store copied in frontend.
And there is a problem: how can i get store in frontend?

Can u provide  a sample cod for me?
Thanks!

**Comment by leaanthony** [comment]
Use an event, but make sure your store can be jsonified:
`runtime.Event.Emit("storeupdate", store)`
and use `runtime.Event.On("storeupdate", (store) => {} )` in JS
