### ISSUE TITLE
Support Distribution 'NixOS'

### ISSUE THREAD

**Issue by diogox** [wailsapp/wails#786]
**Description**
Distribution 'nixos' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.6 |
| Go Version    | go1.16.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | nixos |
| Distribution Name   | NixOS |
| Distribution Version   | 21.05.20210820.f5c2a9a |

**Comment by leaanthony** [comment]
Hey there! I don't have nixos, but supporting it should be pretty easy. Please follow [this guide](https://wails.app/guides/distro/) and feel free to raise a PR

**Comment by leaanthony** [comment]
I should also mention that in v2, we use automatic discovery to determine the dependencies. The nix package manager isn't currently on that list so your PR would help me add it. Thanks!

**Comment by diogox** [comment]
I have made an PR, please lmk what you think :)

NixOS is a somewhat different linux distro, so this PR will allow wails to support NixOS, but on NixOS's side I still need to package wails so that it'll work. I'll try to do that next, but that shouldn't impact this repo whatsoever :+1:

**Comment by leaanthony** [comment]
I've merged the PR and this is released as part of v1.16.7. Please close if you think it's complete.

**Comment by diogox** [comment]
I've managed to get this working on NixOS. I'm not 100% with the package I made for it so I'll keep trying to improve it, but this is all set on this end :+1:
