### ISSUE TITLE
Nest Event not work

### ISSUE THREAD

**Issue by Virgil-N** [wailsapp/wails#787]
**Description**
An event inside other event is not work.

**To Reproduce**
Code is here: 
```
func (appStore *AppStore) WailsInit(runtime *wails.Runtime) error {
	appStore.r = runtime
	appStore.store = runtime.Store.New("appStore", "123")

	appStore.store.Set("456")

	appStore.store.Subscribe(func(data string) {
		println("New Value:", data)
	})
        // here
	runtime.Events.On("getStore", func(...interface{}) {
		runtime.Events.Emit("sendStore", appStore.store) // not work
	})

	return nil
}
```

**Expected behaviour**
Nest event work well.

**System Details**
Go: 1.16.3 darwin/arm64

**Comment by leaanthony** [comment]
There's no reason why that shouldn't work (I have similar code). If you add a `runtime.Events.On("sendStore"....` in Go does it trigger?

**Comment by Virgil-N** [comment]
No, no thing captured.

**Comment by Virgil-N** [comment]
> There's no reason why that shouldn't work (I have similar code). If you add a `runtime.Events.On("sendStore"....` in Go does it trigger?

No, no thing captured.

**Comment by Virgil-N** [comment]
code's here:
```
runtime.Events.On("sendStore", func(s ...interface{}) {
		fmt.Println("send: ", s)
	})
	runtime.Events.On("getStore", func(...interface{}) {
		runtime.Events.Emit("sendStore", appStore.store)
	})
```
