### ISSUE TITLE
[V2]runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#792]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
Run the build command and the doctor command will prompt an error

**To Reproduce**
Steps to reproduce the behaviour:
1. run `wails init -n demo-wails`
2. run `wails build` 
3. ERROR: exit status 2
3. run `wails doctor` 
4. panic: runtime error: invalid memory address or nil pointer dereference

**Expected behaviour**
Hope it can be built successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/132151447-ab884cd0-6529-4c90-adb5-53400f65c845.png)
![image](https://user-images.githubusercontent.com/28185258/132151465-c8edaa07-9773-468c-85da-8b13741a9f45.png)

**System Details**
System version: windows 10 20H2
Go version: go version go1.17 windows/amd64
Wails version: Wails CLI v2.0.0-alpha.73

**Additional context**
The project generated using wails init -n xxxx should be the default directory structure layout. According to normal conditions, there should be no bugs, which is very difficult to understand.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Nice catch. Fix pushed.

**Comment by misitebao** [comment]
@leaanthony 
The webview2 dependency has been installed on this machine, and the error code will still be displayed when you run the `wails build` command.The feedback is shown below：
![image](https://user-images.githubusercontent.com/28185258/132184402-57212ca6-4b6e-4389-9a82-2a6f3e3e9117.png)

**Comment by leaanthony** [comment]
OK, this isn't really ready for testing yet 😃
