### ISSUE TITLE
Wails packing and compiling failing on Pop!_OS with wails build

### ISSUE THREAD

**Issue by brittonhayes** [wailsapp/wails#793]
**Description**

Cannot build or serve a wails application on linux due to undefined reference to `__divmodti4@GCC_7.0.0` from libwebkit2gtk-4.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Use a Linux device
2. Create the wails svelte template
3. Run wails build or wails serve

```
✓ Ensuring Dependencies are up to date...
⣾ Packing + Compiling project...# github.com/wailsapp/wails/lib/renderer/webview
/usr/bin/ld: /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/usr/bin/ld: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so: undefined reference to `__divmodti4@GCC_7.0.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/usr/bin/ld: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so: undefined reference to `std::_Sp_make_shared_tag::_S_eq(std::type_info const&)@GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
```

**Expected behaviour**

The application to package and compile after using the `wails build` command or to serve after using the `wails serve` command.

**Screenshots**

![image](https://user-images.githubusercontent.com/46035482/132255576-9f5c52fa-ac37-4b0b-8dbc-88b7f23febe5.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.7 |
| Go Version    | go1.16.6 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 10.3.0 |
| Npm           | 7.21.0 |
| Node          | v16.8.0 |

**Additional context**
I've tried re-installing all pre-requisite Linux packages multiple times, editing my `PKG_CONFIG_PATH` to ensure it can find the new packages, and none of my my attempts helped.

I run linuxbrew as my preferred package manager on PopOS but I tried using all of the system versions of pkg-config for this situation and it still didn't help. I've used wails on OSX in the past and had none of these issues so if there's something I need to do in my dev environment to fix this, let me know! :slightly_smiling_face: 

At a bit of a loss on how to solve this one.

**Comment by leaanthony** [comment]
This is 100% an environmental issue. Here's a thread related to GCC issues (same error).

**Comment by brittonhayes** [comment]
Thank you for the super fast response here! Sorry for opening an issue that isn't directly related to the build process. I didn't even realize. 😅 

I'll see if I can fix my environment by following some of those recommendations. Feel free to close this issue! And thanks again.

**Comment by leaanthony** [comment]
No problem! If you find out what the problem is, please let us know then we can put it in the troubleshooting guide.

**Comment by brittonhayes** [comment]
Fixed it! The `CC` variable in my `go env` was set to `gcc-5` which is obviously not the latest version :sweat_smile:.

This applied a persistent change to the build environment and found all the necessary dependencies! 

Also linuxbrew will very commonly install `pkg-config` for some very popular tools such as awscli, python, rust etc. and that leads to a bunch of conflicts with the system level `pkg-config` when trying to build a wails application.

So the fix was this :tada: 

```shell
# Remove the brew pkg-config
brew remove --ignore-dependencies pkg-config

# Update CC and CXX env vars with persistence
go env -w "CC=gcc-10"
go env -w "CXX=g++-10"
```
---

```shell
# Trying it again

wails build
Wails v1.16.7 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Awesome! Project 'pod' built!
```

**Comment by leaanthony** [comment]
Hey that's awesome! Glad you got it running 👍
