### ISSUE TITLE
Update WinAPI for Webview (mshtml) to Webview2

### ISSUE THREAD

**Issue by Dexus** [wailsapp/wails#794]
**Is your feature request related to a problem? Please describe.**
Have a more up2date webview on windows would nice, now we have already there the webview that is more like the chrome webview.

I have problems to get the same App looking "similar" on all systems, because windows always have an old webview...

Please update the webview for Windows! Thank you!

**Comment by leaanthony** [comment]
Hey there. It's coming in v2, which, for Windows, should be in Beta shortly 👍
