### ISSUE TITLE
How to open new Windows?

### ISSUE THREAD

**Issue by Dexus** [wailsapp/wails#795]
**Description**

I would like to open a second Window but via CreateApp this will crash the App. So how can I do this?

**To Reproduce**
Steps to reproduce the behaviour:
1. Create App, Bind your Code and open a new APP in a Go Routine
2. Build 
3. Run APP

**Expected behaviour**
Create new Windows or "Apps" without crash.

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.7 |
| Go Version    | go1.17 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.3.0 |
| Npm           | 6.14.15 |
| Node          | v12.22.6 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Not supported. Sorry.
