### ISSUE TITLE
[v2]After initializing the project, it cannot be started because the definition is missing in the main function

### ISSUE THREAD

**Issue by Baiyuetribe** [wailsapp/wails#797]
Wails CLI v2.0.0-alpha.73
![image](https://user-images.githubusercontent.com/43716063/132969574-6cd1e6b5-5ce8-4b78-99ac-cfdbc4d942cd.png)
When I use the `walis init -n demo` command, the project lacks three definitions.

![image](https://user-images.githubusercontent.com/43716063/132969636-1e00d497-f478-435f-b7bb-d1347e677dcd.png)

**Comment by leaanthony** [comment]
Hi. I'm not accepting bug reports on v2 until it hits beta, as it changes daily. Thanks for your patience.
