### ISSUE TITLE
Wails symlink not working on Linux

### ISSUE THREAD

**Issue by intelwalk-zz** [wailsapp/wails#80]
**Description**
When attempting to run wails setup or wails init no sym links were created

**To Reproduce**
1. Follow installation instructions for ubuntu 18.04
2. Type wails setup and receive the following error:
dw@walkarcpop:~$ wails setup

Command 'wails' not found, did you mean:

  command 'rails' from deb ruby-railties (2:5.2.2+dfsg-6ubuntu1)

Try: sudo apt install <deb name>

3. I can run go run go/src/github.com/wailsapp/wails/cmd/wails/main.go and recieve the following prompt  but I am unable to initiate setup or init.  I have tried adding flags to the end of the command but does not affect behavior
 _       __      _ __    
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v0.12.3
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

Flags:

  -help
    	Get help on the 'wails' command.

**Expected behaviour**
wails setup and wails init behaving like the windows one does after following the instructions

**System Details**
OS: Ubuntu 18.04(also tested popos 18.04 and 19.04)
go version go1.11.5 linux/amd64

**Comment by leaanthony** [comment]
Thanks for this. The only way I could replicate this is when `~/go/bin` isn't in my $PATH. Can you confirm what's in `~/go/bin`?

**Comment by leaanthony** [comment]
Just noticed that `wails init` isn't working as expected on Linux as a follow on to this. Checking it out now.

**Comment by leaanthony** [comment]
Just pushed a bug fix that reports if any missing prerequisites aren't found (they weren't being logged). Tested a full run from install to build on Linux. Feel free to pull branch v0.13.0-pre and give it a spin. Instructions for testing branches has been added to the pinned issue `Beta Testing`. Look forward to your feedback!

![image](https://user-images.githubusercontent.com/1943904/57444566-c7d69a80-7293-11e9-9063-4b8684c4ac73.png)

**Comment by leaanthony** [comment]
@intelwalk Based on your docs PR, I'm guessing this can be closed?
