### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by rockmelodies** [wailsapp/wails#803]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)
![image](https://user-images.githubusercontent.com/24653177/133095574-17bcddbe-1e8b-4cb4-8891-cd6b63504429.png)

**Comment by leaanthony** [comment]
`go run` isn't supported.
