### ISSUE TITLE
Odd Box Shadow on OSX and Vuetify

### ISSUE THREAD

**Issue by meatherly** [wailsapp/wails#805]
**Description**
When running the application using vuetify there seems to be an odd issue with the box shadow. This only happens when you build the application and run it. When using bridge mode in the browser this isn't an issue. It seems to be the top left of the box shadow that's causing an issue. 

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init`
2. `select: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template`
3. Change the theme `dark: false` for Vuetify in `main.js`
3. `wails serve` No weird box shadow.
4. `wails build` Run the app. See image below for context

**Expected behaviour**
Clear box shadows on components

**Screenshots**
![image](https://user-images.githubusercontent.com/1327960/133313964-ca981a88-a35e-4a00-95d1-664f21d3a435.png)

**System Details**
* vuetify: "^2.3.15"
* Wails: v1.16.5
* OSX: 11.5.2
* Go: go1.16.2 darwin/amd64

**Comment by meatherly** [comment]
It seems like the problem is related to the web view cause chrome and other browsers handle it fine in Bridge mode.

**Comment by meatherly** [comment]
Just for sanity check. it's any type of back shadow causes this problem. I just tried using tailwind and it has the same issue

**Comment by leaanthony** [comment]
Ah, if this is a webview issue then there's not much we can do. v1 uses a deprecated webview mind, and v2 is using wkwebkit so hopefully that will fix it (once it's released). Please reopen if you think we can do something to mitigate this (update docs?).
