### ISSUE TITLE
wails App can not open Mac OSX 10.14.6

### ISSUE THREAD

**Issue by ixiao** [wailsapp/wails#806]
<img width="415" alt="981631617618_ pic" src="https://user-images.githubusercontent.com/8543192/133367635-bfcac135-c686-46ab-8f31-756802bcac2c.png">
`**app can not use on this macOS** 
your use version is macOS %@. this app request  macOS %@ or more high version.`

Now our wails App can use on  mac osx 11.2.3 version

**Comment by leaanthony** [comment]
Try the Go environment variable "CGO_LDFLAGS": 
EG: `CGO_LDFLAGS=-mmacosx-version-min=10.13 wails build......`

**Comment by ixiao** [comment]
**go env -w CGO_LDFLAGS=-mmacosx-version-min=10.13**
This is the final answer.
Thans ~
