### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#81]
Hi all!
During the Beta phase it may be necessary to test branch releases and I haven't figured a good way of doing that via go get so the steps to do this manually are:

1. `git clone git@github.com:wailsapp/wails.git`
2. `git checkout <branch>`
3. `cd cmd/wails`
4. `go install`

If there's demand, I can build in a `wails betatest <branch>` command to auto do this but that will take away time from bug fixes and features. Let me know your thoughts!

**Comment by intelwalk** [comment]
git clone git@github.com:wailsapp/wails.git
Cloning into 'wails'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by intelwalk** [comment]
After following the instructions and checking out v0.13.0-pre from a fresh install it still shows as v0.12.3 in the default project.

_       __      _ __    
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v0.12.3
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

**Comment by leaanthony** [comment]
As part of v0.13.3, there's significant improvements to the `wails update` command. Rather than going through the headaches of the instructions in the original comment, It's now possible to simply type `wails update` to get the latest 'stable' release or `wails update -pre` to get the latest pre releases. You can also use `-version` to install a specific version. This should significantly aid in getting fixes out without the worry of harming the main branches

**Comment by leaanthony** [comment]
To make things a bit easier for PRs, as of today the project is moving to a gitflow style workflow. This specifically means:

- All development will be on the `develop` branch
- As features are added, the `develop` branch will get tagged with semantic version `-pre` tags
- When a group of features are ready, they will be merged to master and tagged with a non `-pre` tag 

I think this will simplify things as having a bunch of semantic release named branches is hard to track.

**Comment by bh90210** [comment]
I am a bit confused. `go get` can actually get the branch like this
go get wails @ branch-to-test

for example:
`env GO111MODULE=on go get github.com/wailsapp/wails/cmd/wails@92-build-on-first-init`

but it will actually overwrite everything, right? (unlike for example `git checkout 92-build-on-first-init` from within wails dir)

**Comment by leaanthony** [comment]
I believe you are right. I didn't realise it matched branches, I thought only tags. Did you mean to comment on this ticket? :-)

**Comment by bh90210** [comment]
this isn't strictly related to beta but https://github.com/bh90210/wails-linux-scirpts
simple script for testing specific branches against specific os without messing with local wails setup or manually `git cloning` etc :+1:

**Comment by leaanthony** [comment]
This is out of date. Closing.
