### ISSUE TITLE
github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2345:75

### ISSUE THREAD

**Issue by zhaiyujin** [wailsapp/wails#811]
docker:
crazymax/xgo:1.16.4 

root@6e119f9df0fc:/home/wailsdemo# xgo --targets=darwin/amd64 . 
INFO: Starting xgo/0.7.3
DBG: config: &{Repository:. Package: Prefix: Remote: Branch: Dependencies: Arguments: Targets:[darwin/amd64]}
DBG: flags: &{Verbose:false Steps:false Race:false Tags: LdFlags: Mode:default}
INFO: Cross compiling . package...
Building locally ....
Compiling for darwin-10.12/amd64...
 github.com/wailsapp/wails/lib/renderer/webview
In file included from _cgo_export.c:4:
In file included from webview.go:26:
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2345:75: warning: expression which evaluates to zero treated as a null pointer constant of type 'id _Nullable' [-Wnon-literal-null-conversion]
/osxcross/target/bin/../SDK/MacOSX11.1.sdk/usr/include/objc/objc.h:90:13: note: expanded from macro 'NO'
In file included from _cgo_export.c:4:
In file included from webview.go:26:
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2411:24: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2428:20: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
 github.com/wailsapp/wails/lib/renderer/webview
In file included from /go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.go:26:
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2345:75: warning: expression which evaluates to zero treated as a null pointer constant of type 'id _Nullable' [-Wnon-literal-null-conversion]
/osxcross/target/bin/../SDK/MacOSX11.1.sdk/usr/include/objc/objc.h:90:13: note: expanded from macro 'NO'
In file included from /go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.go:26:
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2411:24: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
/go/pkg/mod/github.com/wailsapp/wails@v1.16.7/lib/renderer/webview/webview.h:2428:20: warning: comparison between pointer and integer ('char' and 'void *') [-Wpointer-integer-compare]
Cleaning up build environment...
INFO: Completed!

cross compiler  faile

**Comment by leaanthony** [comment]
Duplicate. @tmclane may have some more info

**Comment by tmclane** [comment]
It would appear from your command line that you ran Xgo directly. That is not exactly how the cross compilation works￼￼ with Wails. 

Either way I need to address some bitrot before it works properly most likely.

Hoping to find time to address this soon￼

**Comment by zhaiyujin** [comment]
Duplicate. @tmclane  Thank you for your answer, because https://proxy.golang.org It's not accessible in our country. I lack some knowledge, so I finally want to use XGO to compile directly

**Comment by leaanthony** [comment]
Tracking xgo issues here: https://github.com/wailsapp/wails/issues/815
