### ISSUE TITLE
Wails build fails if apps is part of a larger module

### ISSUE THREAD

**Issue by realrunner** [wailsapp/wails#812]
**Description**

If the wails app is a package of a larger module, and go.mod is not in the wails application directory but a parent directory, the build fails because it cannot find go.mod

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a wails app as a package inside an existing module 
```
mymodule/
    go.mod
    go.sum
    lib/
    app/
        mywailsapp/
            appicon.png
            bridge
            build
            frontend
            info.plist
            main.go
            project.json
```
2. run `wails build` in the mywailsapp directory
3. You'll see:
```
Wails v1.16.5 - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
✓ Building frontend...
✓ Ensuring Dependencies are up to date...
Error: Unable to load go.mod
```

**Expected behaviour**
Project builds successfully

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.5 |
| Go Version    | go1.16.4 |
| Platform      | darwin |
| Arch          | arm64 |
| GO111MODULE   | (Not Set) |
| GCC           | 12.0.5 |
| Npm           | 7.13.0 |
| Node          | v16.2.0 |

I implemented a quick fix here:
https://github.com/wailsapp/wails/compare/master...realrunner:master

**Comment by leaanthony** [comment]
Hi. This isn't a supported setup, but it *is* possible (see https://github.com/matryer/xbar). Is there any reason you wouldn't use a go.mod in the `mywailsapp` directory?

**Comment by realrunner** [comment]
xbar is using the replace hack for local development

https://github.com/matryer/xbar/blob/main/xbarapp.com/go.mod

It works but it's annoying. My change in the description above is all that is required to support the scenario. Would such a PR be accepted?

**Comment by leaanthony** [comment]
I think the link may be stale

**Comment by realrunner** [comment]
So it is. Sorry! https://github.com/wailsapp/wails/compare/master...realrunner:feature/go-mod-parents

**Comment by leaanthony** [comment]
Thanks for that. Github mobile cuts half the code off. Does it follow the parent path to find go.mod?

**Comment by realrunner** [comment]
Yes

**Comment by leaanthony** [comment]
I'll look at this tonight. I feel the docs need updating too if we merge. I'll also port this to v2
