### ISSUE TITLE
Support Distribution 'Garuda Linux'

### ISSUE THREAD

**Issue by lucannez64** [wailsapp/wails#823]
**Description**
Distribution 'garuda' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.7 |
| Go Version    | go1.17.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | garuda |
| Distribution Name   | Garuda Linux |
| Distribution Version   |  |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
https://github.com/wailsapp/wails/issues/767#issuecomment-888988360
