### ISSUE TITLE
v2 Beta for Windows

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#829]
The first release of v2 Beta for Windows is out. 
- [Announcement](https://wails.io/blog/wails-v2-beta-for-windows)
- [Feedback](https://github.com/wailsapp/wails/discussions/828)

**Comment by drognisep** [comment]
@leaanthony Will Wails v2 support the same project template options as v1? Vue3 on Windows with all the goodies would be fantastic. :)

**Comment by leaanthony** [comment]
V2 supports community templates and vue3 on windows has already been done https://wails.io/docs/community/templates
