### ISSUE TITLE
v2 beta build error

### ISSUE THREAD

**Issue by dwdcth** [wailsapp/wails#831]
**Description**
wails build  error, msg is:

No Build command. Skipping.
Generating bundle assets: Done.
Compiling application: C:\Users\th\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.1\wails.go:6:2: //go:build comment without // +build comment
C:\Users\th\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.1\internal\appng\app_production.go:10:2: //go:build comment without // +build comment
C:\Users\th\go\pkg\mod\github.com\wailsapp\wails\v2@v2.0.0-beta.1\internal\appng\app_production.go:12:2: //go:build comment without // +build comment

**To Reproduce**
Steps to reproduce the behaviour:
1. get the v2 beta wails cli
2. wails init -n demo
3. cd demo   and  wails build

**Screenshots**
![image](https://user-images.githubusercontent.com/1883728/135029840-567bb668-4154-4fe7-87b6-183c7c947e73.png)

**System Details**
windows 10  amd64, go1.16.4

**Additional context**

**Comment by leaanthony** [comment]
Go 1.17+ required: https://wails.io/docs/gettingstarted/installation#dependencies
