### ISSUE TITLE
[V2] Svelte router issues

### ISSUE THREAD

**Issue by Gaz492** [wailsapp/wails#834]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
When using svelte-navigator to add routes/different pages the built app will try and load a file on the route instead of using the route.
E.g I have a route named about which is accessed by clicking on a button that links to /about, instead of loading the route it tries to load a file at /about

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an app using the svelte template
2. Install and setup svelte-navigator routes
3. Build app and run it
4. Click on a router link

**Expected behaviour**
Should load the router link and not try and load a file

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc
go version go1.17.1 windows/amd64
Wails v2 beta 3

**Additional context**
While playing around with the alpha version of v2 I did not run into this issue

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
That's sounds like a svelte-router issue: if it issues a navigate request then it's going to try and load a page. Let me know if you have more information.
