### ISSUE TITLE
When mouse move out the gui, it stop render

### ISSUE THREAD

**Issue by marktohark** [wailsapp/wails#836]
**Description**
I use golang emit event to frontend. 
When mouse move out the gui, it stop render. 
And move in gui, it will render all.
https://youtu.be/AAPKNg61S8M
the video show that bug.

**Expected behaviour**
js receive text immediately, no matter if the mouse moves in or out.

**Screenshots**
https://youtu.be/AAPKNg61S8M

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.6 |
| Go Version    | go1.17 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 8.1.0 |
| Npm           | 6.14.14 |
| Node          | v14.17.5
 |

- [ V ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
That looks like a webview issue. I don't think MS will fix that as it's IE11. I highly recommend you port your app to v2 beta: https://wails.io

**Comment by luoshengheng** [comment]
I met a similar issue with wails@2.4. When the wails window is minimized for a while, and gui will stop data rendering. If maximize the window, it will stuck for a while and then renders all data. How to resolve it?

**Comment by luoshengheng** [comment]
> That looks like a webview issue. I don't think MS will fix that as it's IE11. I highly recommend you port your app to v2 beta: https://wails.io

I met a similar issue with wails@2.4. When the wails window is minimized for a while, and gui will stop data rendering. If maximize the window, it will stuck for a while and then renders all data. How to resolve it?

**Comment by luoshengheng** [comment]
by the way, wails is run on MacOS 11.3.1
