### ISSUE TITLE
windows: start the dev webserver on localhost

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#837]
On Windows, if you start a webserver on, say, `:8080`, it binds to all network interfaces which causes Windows Defender Firewall to show a scary warning dialog.

If you start a webserver explicitly on `localhost:8080` or `127.0.0.1:8080`, it only binds to localhost, no scary warning dialog.

This only seems to happen with `wails dev` and the error was about `foo-dev.exe`. The .exe generated with `wails build` doesn't have this problem.

**Comment by leaanthony** [comment]
Hmmm....I thought it was to localhost. Will change!

**Comment by kjk** [comment]
This is with beta2

**Comment by kjk** [comment]
Interestingly, the log says:
```
 [DevWebServer] Serving application at http://localhost:34115
```

But it does happen:

![image](https://user-images.githubusercontent.com/7935/135353747-42c16a2c-ece2-4368-ae54-2300fcc508f4.png)

Also, it's on Windows 11 beta.

**Comment by leaanthony** [comment]
Fixed on master - thanks for reporting
