### ISSUE TITLE
move build\bin to it's own top-level directory

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#838]
This is minor and feel free to disregard, but I wanted to delete the generated exe and deleted the whole `build` directory thinking that it only has generated files.

Then when I ran `wails dev` or `wails build` it failed without a decent error message.

Fixed with `git reset --hard` when I realized that `build` directory contains necessary files.

Maybe it would be better to have `bin` directory be sibling of `build` directory and not a child.

Somewhat related: a template generated with `wails init` could include `.gitignore` that instructs to ignore `bin` directory and others like that.

For example, I don't know if I should checkin `frontend/wailsjs` directory into my repo or `.gitignore` it?

**Comment by leaanthony** [comment]
For me, binaries are built and therefore part of a build directory. I've seen other compilers use this convention and I'm good with it. By default `build/bin` should be in `.gitignore` (if it isn't it needs to be) so I don't see any reason to change this right now. You can always use `-o` to dump binaries in other places. 

Thanks for bringing this up! 👍

**Comment by leaanthony** [comment]
Fixed on master 👍
