### ISSUE TITLE
[V2] MacOS unable to start application

### ISSUE THREAD

**Issue by cxfksword** [wailsapp/wails#841]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
I want to run a test demo use `v2.0.0-beta.3`, when run `wails dev`, i get following error:
```
Wails CLI v2.0.0-beta.3


Building application for development...
No Install command. Skipping.
No Build command. Skipping.
Compiling application: Done.
Packaging application: Done.

FATAL: Unable to start application: fork/exec /Users/cxf/dev/wails-test/build/bin/wails-test-dev-darwin-amd64: no such file or directory
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails init -n wails-test`
2. Run `cd wails-test/`
3. Run `wails dev`

**Expected behaviour**
Run app success

**System Details**
```
Wails CLI v2.0.0-beta.3


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	11.5.2
ID:		199506
Go Version:	go1.17.1
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2384
npm 				N/A		Installed	6.14.14
*upx 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
```

**Additional context**
Can't find `wails-test-dev-darwin-amd64` name app in build directory

```
.
├── README.md
├── app.go
├── appicon.png
├── build
│   ├── README.md
│   ├── appicon.png
│   ├── bin
│   │   └── wails-test.app
```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
v2 isn't released for MacOS, but look out for an announcement hopefully end of the month.
