### ISSUE TITLE
wails dev: html file not updated after change

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#842]
Testing with the template generated with `wails init`.

Changing `frontend\src\index.html` doesn't update the page when running in `wails dev`. Re-starting `wails dev` shows the changes.

I can see in the log that the changes are detected and `main.css` and `main.js` are re-loaded from the logs, but `index.html` doesn't show as reloaded. The logs:
```
Added new directory to watcher: C:\Users\kjk\src\apps\fastfilefinder2\frontend\wailsjs\go
DEB | [DesktopAssetServer] Loading assets from: C:\Users\kjk\src\apps\fastfilefinder2\frontend\src
DEB | [DevWebServer] Serving assets from: C:\Users\kjk\src\apps\fastfilefinder2\frontend\src
DEB | [DevWebServer] Serving application at http://localhost:34115
DEB | [DesktopAssetServer] Loading file from disk: /main.css
DEB | [DesktopAssetServer] Loading file from disk: /main.js
DEB | [DesktopAssetServer] Loading file from disk: /assets/fonts/nunito-v16-latin-regular.woff2
DEB | [DesktopAssetServer] Loading file from disk: /main.css
DEB | [DesktopAssetServer] Loading file from disk: /main.js
```

Changes to `main.js` correctly cause re-load.

Seems like `index.html` is cached in memory? Possibly this:
```
func (a *DesktopAssetServer) Load(filename string) ([]byte, string, error) {
	var content []byte
	var err error
	switch filename {
	case "/":
		content = a.indexFile
```

Also looking at injection of runtime in `DesktopAssetServer.init`: does it mean that wails only supports single-page apps in `index.html`? i.e. if I create multiple .html pages, will they get the interop with go backend?

`wails doctor`:
```
wails doctor
Wails CLI v2.0.0-beta.3


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.1
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       94.0.992.31
npm             N/A             Installed       7.19.0
*upx            N/A             Available
```

**Comment by leaanthony** [comment]
Thanks for raising this. Yeah, it's cached and thst's a bug.

WRT loading scripts, you're right. Perhaps we should make the fetching of those explicit in the HTML, ie, put the onus on the developer to ensure they load them. Would that be acceptable?

**Comment by kjk** [comment]
Yes, explicit loading of runtime makes sense to me. Explicit better than implicit, and all that.

Also, maybe I'm mis-remembering but I think webview2 has an api to inject javascript programmatically at the right time, so maybe that would be better than injecting into html?

**Comment by leaanthony** [comment]
I'm thinking of adding a meta tag to disable injection, rather than break existing projects. Do you think that's acceptable?

Regarding injection of js, perhaps the solution is to dump the bindings and runtime code that's normally injected into the `wailsjs` directory and let the developer deal with loading them?

**Comment by kjk** [comment]
> I'm thinking of adding a meta tag to disable injection, rather than break existing projects. Do you think that's acceptable?

Sounds reasonable.

> Regarding injection of js, perhaps the solution is to dump the bindings and runtime code that's normally injected into the wailsjs directory and let the developer deal with loading them?

Not enough experience using wails to have an opinion.

**Comment by leaanthony** [comment]
Need to think about options, because i'd hate to add overhead by parsing the HTML each load. A bit hacky but maybe it'd be fine to simply look for the string "wails-noautoinject" in the HTML, then people can add it wherever.

Regarding injection, i'm saying maybe instead of adding `src` tags, you could simply `import` the code in your own bundler.

**Comment by kjk** [comment]
> Need to think about options, because i'd hate to add overhead by parsing the HTML each load. A bit hacky but maybe it'd be fine to simply look for the string "data-wails-noautoinject" in the HTML, then people can add it wherever.

I think for `wails dev` mode it's fine to inject every time.

In `wails build` mode, the server could cache injected html in memory, under the assumption that in production build the HTML doesn't change.

Alternatively, inject HTML during build process and have injected HTML be bundled into .exe.

**Comment by leaanthony** [comment]
This should be fixed in latest. `wails update -pre`

**Comment by kjk** [comment]
Confirmed fixed, thanks.

Had to update `go.mod` to `v2.0.0-beta.4`, which at this point is expected.

**Comment by leaanthony** [comment]
From this version there's explicit details on doing that after an update
