### ISSUE TITLE
Invalid Semantic Version

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#844]
**Description**

when i do wails update i get error: Error: Invalid Semantic Version
Terminal:
```
PS C:\Users\Filip\go\src> wails update
Wails v1.16.5 - Checking for updates...

! Invalid Semantic Version
Error: Invalid Semantic Version
```

**To Reproduce**
Steps to reproduce the behaviour:
1. go to any folder
2. do wails update
3. Get error

**Expected behaviour**
To update or something

**Screenshots**
No need, all the things is in the description.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.5 |
| Go Version    | go1.17.1 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | Auto |
| GCC           | 10.3.0 |
| Npm           | 7.20.3 |
| Node          | v16.7.0

**Comment by leaanthony** [comment]
Thanks for raising this. Looks like you're on the latest (and probably last) version of v1 for Windows so it can probably be ignored.

**Comment by Failip420** [comment]
unfortunately not:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Filip> wails update -version v1.16.7
Wails v1.16.5 - Checking for updates...

! Invalid Semantic Version
Error: Invalid Semantic Version
PS C:\Users\Filip>

```

**Comment by Failip420** [comment]
i tried with -pre too it does not work either:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Filip> wails update -pre
Wails v1.16.5 - Checking for updates...

! Invalid Semantic Version
Error: Invalid Semantic Version
PS C:\Users\Filip>
```

**Comment by leaanthony** [comment]
Not even the project folder?
You could just use go install to install 1.16.7 for now

**Comment by Failip420** [comment]
I downloaded the latest release source code and did go install
I can use it now :)

**Comment by leaanthony** [comment]
Glad you got it fixed. How strange.

**Comment by Pritep** [comment]
> I downloaded the latest release source code and did go install I can use it now :)

how did you install it
