### ISSUE TITLE
Can I keep using your Webview code?

### ISSUE THREAD

**Issue by marcomq** [wailsapp/wails#847]
Hi! 

**Is your feature request related to a problem? Please describe.**

I'm currently developing a similar library for Nim / Python / C / C++.
https://github.com/marcomq/nimview
I started it before I found "Wails" but I guess it can be considered as "Wails clone" as a lot of the contained functionality is similar.

As the current Webview code changed a lot, I tried to find some old C / header-only version that still contains fixes for the latest GTK versions and found yours. 
Currently, I just copied the Webview Code from your repository folder https://github.com/wailsapp/wails/tree/master/lib/renderer/webview with it is containing license, as I couldn't find the same code on the original Webview repository.

**Describe the solution you'd like**

Can I just keep copying that Webview version and update it if you perform fixes? According to MIT license, this might not be a big issue as long as I still make the license file available etc... But I still wanted to ask. 
I'm not copying any GO code from Wails.

I'm also interested in copying the Webview2 version. The current versioning scheme of Webview is a mess and I have no idea which version of Webview is stable and actually usable. But if you are using it, I guess the webview version can be considered stable as you have much more users and much more contributors ;) I guess it was a lot of work for you to test the Webview2 code which I wouldn't have to do anymore.

I added a link to your repo in the webview readme 
https://github.com/marcomq/nimview/tree/main/src/nimview/webview/webview
and also mentioned your library in the general readme.

Let me know if I need to make the contribution more transparent.
I really like the your project and how this turns out - I'm just not good in "Go" code and still prefer my "old" languages.

**Comment by leaanthony** [comment]
Hey @marcomq! I'm a big fan of Nim and really happy if this project helps the Nim community in any way. I'm not sure you need to ask permission, but you've got it anyway and I also appreciate it. Webview2 has been pretty tough to get right so feel free to ask Qs and I'll do what I can to help.

**Comment by leaanthony** [comment]
Of course, i'd love to borrow your android code 😃

**Comment by marcomq** [comment]
> Of course, i'd love to borrow your android code 😃

😄 Go ahead. I'm not an Android expert but I got it working.
It is just using the Android Webview and calling a dispatch function via JNI.
