### ISSUE TITLE
Calling a Go function with JSON string triggers a file load... why that?

### ISSUE THREAD

**Issue by Robert-M-Muench** [wailsapp/wails#858]
### Discussed in https://github.com/wailsapp/wails/discussions/857

<div type='discussions-op-text'>

<sup>Originally posted by **Robert-M-Muench** October  5, 2021</sup>
I have an HTML form where the submit function collects all inputs into a JSON string which I use as a parameter to my Go function. As soon as the Go function gets called, the console shows:

```
 [DesktopAssetServer] Loading file from disk: /?user_company=company&user_division=divisi...
```
Which of course fails because such a file doesn't exist. Why is this triggering a file load at all?</div>

JS code which gets called:

```Javascript
  window.go.main.App.register(js).then(() => {
   console.log("The user input is: " + js);
  })
```

Go code which gets called:

```Go
func (app *App) register(ud string) {
	log.Print(ud)
	runtime.LogPrint(app.ctx, ud)
}
```

Payload:
```
string {"user_company":"company","user_division":"division","user_surname":"surname","user_name":"name","user_email":"user@company.com"}
```

**Comment by leaanthony** [comment]
Hey. This is covered in https://wails.io/docs/howdoesitwork#calling-bound-go-methods. Do you think that could be made more clearer? How would you change the docs to make this clearer?
For 2. I'm not sure how I'd do that as you're just calling a JS function that doesn't exist. How would you approach this problem?
