### ISSUE TITLE
data-wails-drag prevents dragging a scrollbar

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#864]
This is windows with beta10.

This might not be fixable but `data-wails-drag` prevents dragging of a scrollbar.

I modified the default template to have enough items to show vertical scrollbar. `data-wails-drag` on `body` element prevents dragging the scrollbar.

Removing `data-wails-drag` restores draggability of the scrollbar.

**Comment by leaanthony** [comment]
Ooh that's a tricky one. I could add a "pass-through" flag but not sure it's a good solution? 
Maybe `data-wails-drag="passthrough"`? or `data-wails-drag-passthrough`? Does mouse wheel work in this scenario?

**Comment by kjk** [comment]
I've created a test at https://github.com/kjk/wailstest
This is newly generated template with beta12, added my sutff, tested with `wails dev`.

This is on Windows 11 (even though `wails doctor` says windows 10:
```
> wails doctor
Wails CLI v2.0.0-beta.12

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.2
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       94.0.992.38
npm             N/A             Installed       7.20.5
*upx            N/A             Available
```

**Comment by kjk** [comment]
Thanks. Can confirm that `window.wails.flags.disableScrollbarDrag = true` fixes the issue.
