### ISSUE TITLE
V2 / Failed to unregister class Chrome_WidgetWin_0

### ISSUE THREAD

**Issue by Robert-M-Muench** [wailsapp/wails#866]
When closing my app while running it via `wails dev` I get:

```
[1011/114703.205:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

And I can't CTRL+C to PowerShell. Need to close it.

**Comment by leaanthony** [comment]
I've fixed the output of the message. I don't believe that will solve your shutdown issue but at least you'll know it's not that 👍

**Comment by KillerKiwiJuice** [comment]
I'm having this issue when using `wails dev`. It will reload the app and cause it to crash. Anyway to disable auto reload?
```[0403/200505.577:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
Error during refresh: Get "http://localhost:34115/wails/reload": dial tcp [::1]:34115: connectex: No connection could be made because the target machine actively refused it.```

**Comment by leaanthony** [comment]
If you have reproducible steps, please open it's own ticket 👍
