### ISSUE TITLE
adding <!DOCTYPE html> messes up layout

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#870]
Start with test at https://github.com/kjk/wailstest

Add this to the top of `index.html`:
```html
<!DOCTYPE html>
```

This shouldn't have any effect but it adds extra scrollbars:

Before:

![image](https://user-images.githubusercontent.com/7935/136873850-7ce971e2-19e1-44c5-aa7e-857c09e76523.png)

After:

![image](https://user-images.githubusercontent.com/7935/136873767-52711913-6071-41a0-b194-f69792b752cb.png)

**Comment by leaanthony** [comment]
We don't do anything with the html tag so I expect the same result for Edge/Chromium. Is there a reason for doing this?
