### ISSUE TITLE
Can't install Wails on Ubuntu 20.04 because "installing executables with 'go get' in module mode is deprecated"

### ISSUE THREAD

**Issue by thoni56** [wailsapp/wails#882]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
I was keen on trying out Wails on Ubuntu 20.04 with Go1.17.2 but install as per instruction using

    go get -u github.com/wailsapp/wails/cmd/wails

fails with 
```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow install instructions on https://wails.app/gettingstarted/linux/
2. `go install` fails

**Expected behaviour**
Install process terminate ok, and Wails command installed.

**Screenshots**

**System Details**
Ubuntu 20.04, go1.17.2

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
The first response from go told you what you needed to do. I'll update the docs to make it explicit.
