### ISSUE TITLE
V2: https://wails.io/docs/reference/runtime/events / EventsEmit signatures are wrong

### ISSUE THREAD

**Issue by Robert-M-Muench** [wailsapp/wails#884]
See: https://wails.io/docs/reference/runtime/events

The signatures for Go and Js are wrong. Reads: `Events`should Read: `EventsEmit`

**Comment by leaanthony** [comment]
Thanks for spotting that. Feel free to press"edit page" at the bottom if you'd like to contribute a change 👍

**Comment by Robert-M-Muench** [comment]
The thing is, I need to fork the project and then somehow do a PR... As I'm not that fluently with these GH features, faster to open an issue ;-)

**Comment by leaanthony** [comment]
Hmm...the link should do all that for you.
