### ISSUE TITLE
[v2] `wails dev` is executing `frontend:build` command

### ISSUE THREAD

**Issue by TAINCER** [wailsapp/wails#889]
**Description**
When running the `wails dev` command, the `frontend:build` command gets run alongside `frontend:dev`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change `frontend:build` to something obvious. For example `mkdir buildcommand`, which is going to create a folder in the `frontend` folder. (Echo commands didn't work for me)
2. Run `wails dev`

**Expected behaviour**
`wails dev` should run `frontend:install`, then `frontend:dev`.

**System Details**
Windows 10 Pro - Version 21H1 (Build 19043.1288)
Go: go1.17.2 windows/amd64
Wails: Wails CLI v2.0.0-beta.14

**Comment by leaanthony** [comment]
@TAINCER any feedback?

**Comment by leaanthony** [comment]
Closing due to age. Feel free to reopen.
