### ISSUE TITLE
wails init unable to check libraries on distribution 'ManjaroLinux'

### ISSUE THREAD

**Issue by Froglich** [wailsapp/wails#89]
**Description**

'wails init' exists with error "Error: unable to check libraries on distribution 'ManjaroLinux'. Please ensure that the 'libgtk-3-dev' equivalent is installed" and does not allow me to continue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Manjaro Linux
2. Run in terminal: "sudo pacman -S go webkit2gtk gtk3"
3. Run in terminal: "export PATH=$PATH:/home/user/go/bin"
4. Run in terminal: "go get github.com/wailsapp/wails/cmd/wails"
5. Run in terminal: "wails install"
6. Run in terminal: "wails init"

**Expected behaviour**
Wails should create a new project

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.13.3 |
| Go Version    | go1.12.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment]
Hi! Manjaro isn't supported currently. You may be able to get IR to work by editing cmd/linux.go and adding Manjaro to the arch Linux check. Let us know if it works and we'll add it. Thanks

**Comment by Froglich** [comment]
Thank you, I added 
`case "ManjaroLinux":
	result.Distribution = Arch`

to the "Distrubutor ID" field check in lsb-release. Everything works fine and I could build/execute the template application.
![Screenshot from 2019-05-16 12-28-43](https://user-images.githubusercontent.com/6320500/57847345-8c2d5a80-77d6-11e9-918a-b133f6f4be7f.png)
