### ISSUE TITLE
[v2]There is a problem with the wails dev command

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#902]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
After using the latest version of the cli tool and creating a new project based on the default svelte template, after running `wails dev`, the window cannot display the front-end content normally.

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init -n Svelte-Demo -t svelte
2. cd Svelte-Demo/
3. wails dev

**Expected behaviour**
Hope that the window can display the built front-end interface normally instead of the placeholder file in the template.

**Screenshots**
![image](https://user-images.githubusercontent.com/28185258/139559500-8aae646d-b59c-45d5-8efd-db229c8b4807.png)
![image](https://user-images.githubusercontent.com/28185258/139559607-00d0cfa4-30fa-4266-9bdf-1df835d923bc.png)

**System Details**
![image](https://user-images.githubusercontent.com/28185258/139559511-b091fef8-c91f-4b7f-a000-edeaa801b15a.png)

**Additional context**
This is because after using the project to create a new template, the go program that is run directly without being built by the front-end project uses the placeholder `index.html` file in the template, so problems will occur.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by misitebao** [comment]
I think it is unnecessary to add a placeholder file to the template to prevent "go:embed" errors. If the template has a "frontend:*" field, you should execute the frontend resource generation before running the go program.

**Comment by leaanthony** [comment]
The reason we need to do this is to generate the bindings that the frontend needs so until we have a way of doing that through parsing, we will need to provide a default `index.html` to get around the fact that Go needs that file to even compile when using embed.

**Comment by misitebao** [comment]
@leaanthony 
Why not build the front end first, and then run Go?

**Comment by leaanthony** [comment]
Because the frontend ends up needing `bindings.js` and the other autogenerated files that are created....when the go program is first run :-) Honestly, the easiest way out of this is to add a dummy html file.

**Comment by misitebao** [comment]
Isn’t it okay to build the front-end first and then process the binding in the previous way?

**Comment by leaanthony** [comment]
No, because the frontend will have `import "bindings"`

**Comment by misitebao** [comment]
Okay, I know what to do.
