### ISSUE TITLE
[v2] State changes not working in Windows (Svelte Navigator, Petite-vue)

### ISSUE THREAD

**Issue by Redid** [wailsapp/wails#908]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
I've tried using [Svelte navigator](https://github.com/mefechoel/svelte-navigator) in Wails, but without luck. It works from any web browser, but not from wails when using `wails dev` command. The same issue is with e.g. [petite-vue](https://github.com/vuejs/petite-vue) when trying to use their `@click` directive. Example is based on petite-vue as it is much simpler.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create simple html file that includes `petite-vue`
```
<script src="https://unpkg.com/petite-vue" defer init></script>

<div v-scope="{ count: 0 }">
  {{ count }}
  <button @click="count++">inc</button>
</div>
```
2. Run `wails dev`
3. Click `inc` button

**Expected behaviour**
It works like in web browser or there is note in manual how to make it work like in web browser (Svelte router 

**Screenshots**
Wails after few clicks
![image](https://user-images.githubusercontent.com/9056579/139715534-b5109d26-da6d-46e2-b1cd-e52bd463cb49.png)

Browser after few clicks
![image](https://user-images.githubusercontent.com/9056579/139715586-5c172e77-f1b1-4039-8bdc-135d20ea25dc.png)

**System Details**
- go 1.17.2
- Wails CLI v2.0.0-beta.15
- windows 10
- WebView2 Version: 95.0.1020.40

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Let's move this to this discussion: https://github.com/wailsapp/wails/discussions/839
