### ISSUE TITLE
[V2] Options.App adds the default window maximize option

### ISSUE THREAD

**Issue by OneSeven** [wailsapp/wails#913]
**Is your feature request related to a problem? Please describe.**
Options.App adds the default window maximize option
In some scenarios, you need to always keep the maximized interface

**Describe the solution you'd like**
The window is maximized when the program starts

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by leaanthony** [comment]
Let's do this after Mac and Linux port. Probably a config called "InitialWindow" which can be, Normal, Maximisimed, Fullscreen?

**Comment by OneSeven** [comment]
> Let's do this after Mac and Linux port. Probably a config called "InitialWindow" which can be, Normal, Maximisimed, Fullscreen?

I think it can, but it’s a pity to wait until next year。

**Comment by leaanthony** [comment]
I can't do more features with parity across all 3 platforms right now but am happy to accept PRs for it.

**Comment by leaanthony** [comment]
Check `master` 😉

**Comment by OneSeven** [comment]
> Check `master` 😉

Good!
