### ISSUE TITLE
[V2] Window Toolbar can be customized

### ISSUE THREAD

**Issue by OneSeven** [wailsapp/wails#914]
**Is your feature request related to a problem? Please describe.**
Window Toolbar can be customized

**Describe the solution you'd like**
Window Toolbar can be customized

**Describe alternatives you've considered**
No

**Additional context**
![qwe](https://user-images.githubusercontent.com/17974392/139851991-7d5d69c0-7042-4d2c-bfb9-5466c311db3d.png)

**Comment by leaanthony** [comment]
We'll need to look at this after Linux and Mac ports
