### ISSUE TITLE
No cgo webview

### ISSUE THREAD

**Issue by gedw99** [wailsapp/wails#915]
This one works for me 

https://github.com/Inkeliz/gowebview

It’s makes windows less painful .

**Comment by leaanthony** [comment]
Thanks for this. V2 already has no CGO for windows 👍

**Comment by gedw99** [comment]
Hey @leaanthony 

It also support Mobile btw. Have been using it with gio.  

Just because it is used with gio does not mean that wails cant also use it though. Its just a webview.

IOS and MAC support is not quite there yet, but android, windows works great

**Comment by leaanthony** [comment]
Thanks for letting us know
