### ISSUE TITLE
error for `wails build`

### ISSUE THREAD

**Issue by zhixuan2333** [wailsapp/wails#919]
**Description**

I init the project with `https://wails.app/gettingstarted/installing/`. When i use `wails build` wails give me this. How can I fix it?

```
Wails v1.16.8 - Building Application

/ Ensuring frontend dependencies are up to date (This may take a while)npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/core@8.0.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~8.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"8.2.14" from @angular/animations@8.2.14
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^8.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jinzh\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jinzh\AppData\Local\npm-cache\_logs\2021-11-05T06_49_28_995Z-debug.log


! Ensuring frontend dependencies are up to date (This may take a while)
Error: exit status 1
```

[eresolve-report.txt](https://github.com/wailsapp/wails/files/7481172/eresolve-report.txt)
[2021-11-05T06_49_28_995Z-debug.log](https://github.com/wailsapp/wails/files/7481176/2021-11-05T06_49_28_995Z-debug.log)

**To Reproduce**

Follow with https://wails.app/gettingstarted/installing/

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.8 |
| Go Version    | go1.17.1 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 8.1.2 |
| Node          | v14.18.0 |

**Additional context**

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by TAINCER** [comment]
This is due to Angular package versions not being compatible with each other. Also, they are not supported anymore (By the angular team), so you may want to update them with `ng update` (If you have Angular CLI installed.)

An easy fix for this is to change the `install` value in your `project.json` from `npm install` to `npm install --force`. This disables the Protections by npm. The packages should work fine.

**Comment by zhixuan2333** [comment]
Thx, fix it.

**Comment by leaanthony** [comment]
Do you think it's worth updating the base template?

**Comment by zhixuan2333** [comment]
yes, please.

**Comment by leaanthony** [comment]
Awesome, thanks.
