### ISSUE TITLE
DesktopIPC undefined

### ISSUE THREAD

**Issue by ZTaboo** [wailsapp/wails#924]
![8MTZ2Y`HAL9GTCD~4%5W1JJ](https://user-images.githubusercontent.com/70752260/140842931-6293ef81-8713-4a5d-aaa2-fb4daf02a24c.jpg)

> In the test, I used the wails V2 version and successfully installed it on the AMD CPU, but failed to install it on the i5-8300 CPU. I don't know the specific reason. The desktopipc variable also exists in the runtime package

**Comment by leaanthony** [comment]
Wow, that's weird. So you're saying it installs on AMD but not Intel? What OS?

**Comment by ZTaboo** [comment]
![image](https://user-images.githubusercontent.com/70752260/140912570-027c9257-bd2b-46a8-b3d0-ec04f6d3276f.png)
![image](https://user-images.githubusercontent.com/70752260/140912602-b1abbe7a-533b-4146-89ad-08502ee015e6.png)

Windows10 20h1 professional edition, maybe I'm thinking of reinstalling the system...

**Comment by leaanthony** [comment]
Well that's weird as I installed .20 tonight on win10. Is it a Go build tags issue?

**Comment by OmgImAlexis** [comment]
Getting the same issue here while trying to install this on Windows 10 with WSL2 with Ubuntu.

The install command is throwing this.
```
go install github.com/wailsapp/wails/v2/cmd/wails@v2.0.0-beta.20
```

```
# github.com/wailsapp/wails/v2/pkg/commands/build
/home/xo/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.20/pkg/commands/build/base.go:395:61: undefined: "github.com/wailsapp/wails/v2/internal/frontend/runtime".DesktopIPC
```

**Comment by OmgImAlexis** [comment]
So it's definitely the variable being undefined as it installs fine if you just change it to `RuntimeDesktopJS` on that line. Granted it doesn't output the right file now but hopefully that helps find the issue.

**Comment by OmgImAlexis** [comment]
Checking the go file vs code is throwing this.

```
DesktopIPC not declared by package runtimecompilerUndeclaredImportedName
```

**Comment by OmgImAlexis** [comment]
Okay I don't use go but I think the fix is in these two files https://github.com/wailsapp/wails/blob/master/v2/internal/frontend/runtime/runtime_dev_desktop.go and https://github.com/wailsapp/wails/blob/master/v2/internal/frontend/runtime/runtime_prod_desktop.go add `var DesktopIPC []byte` to the end.

**Comment by leaanthony** [comment]
WSL isn't supported (it's going to be seen as Linux). This file explains it: https://github.com/wailsapp/wails/blob/master/v2/internal/frontend/runtime/ipc.go

If you want to use on windows, then install as a regular windows project.

**Comment by OmgImAlexis** [comment]
@leaanthony yes I know but it should still install. The fix I suggested above allows the cli to install and run which then shows the not supported message.

**Comment by leaanthony** [comment]
That's a fair point!

**Comment by leaanthony** [comment]
Fixed on `master`. Will be out next release. Thanks!

**Comment by OmgImAlexis** [comment]
@leaanthony it helps if you link the commit https://github.com/wailsapp/wails/commit/008a5c70b98fdc836e2d80e8d67fff7c4387c338
