### ISSUE TITLE
[v2] runtime.Quit on windows not working

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#926]
Hey, I've been playing around with v2 really liking it so far!
I noticed that I cannot close the app with `runtime.Quit(ctx)` on Windows for some reason. However, I tested in on Mac and it seems to work fine. 
Tested on fresh project as well, steps:
`wails init -n test`
add couple of lines in startup
```
time.Sleep(5 * time.Second)
runtime.Quit(ctx)
```
wails build and execute the binary, window stays open. Do you have any insight? 
I was actually looking for a way to restart the app, do you think that would be a useful addition to the project?
Thanks : )

_Originally posted by @stefpap in https://github.com/wailsapp/wails/discussions/828#discussioncomment-1610516_

**Comment by leaanthony** [comment]
If you try and kill it in startup, it won't quit properly because a number of things are in flight.
It does seem to work as expected - add a Quit to the button callback and see it in action.

```go
// Greet returns a greeting for the given name
func (b *App) Greet(name string) string {
	runtime.Quit(b.ctx)
	return fmt.Sprintf("Hello %s, It's show time!", name)
}
```

**Comment by stefpap** [comment]
Thanks for the fast reply and sorry for wasting your time Lea

**Comment by leaanthony** [comment]
No worries, you found a gap in the docs. Will update 👍

**Comment by leaanthony** [comment]
Updated docs 👍
