### ISSUE TITLE
Cross compilation not showing binary

### ISSUE THREAD

**Issue by obikay200** [wailsapp/wails#928]
**Description**
When trying to cross compile on either linux or mac-intel to arm the binary doesnt appear in build or any go path.
you can see from the output that the build is completing, apparently, but no binary found.

**To Reproduce**
Steps to reproduce the behaviour:
1. install golang 1.16 ( rolled back to try older version from 1.17 ) same behaviour
2. install wails v1.16.8
3. wail init test-app - select 3 for svelte template
4. wails build -p -x linux/arm-7 -verbose

**Expected behaviour**
to output the binary in the build folder in arm format

**System Details**
linux mint 20/ mac-intel both same behaviour
golang 1.16 ( rolled back to try older version from 1.17 ) same behaviour
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
wails v1.16.8

**Additional context - build output**
buildroot@buildroot-virtual-machine:~/test-app$ wails build -p -x linux/arm-7 -verbose
Wails v1.16.8 - Packaging Application

Ensuring frontend dependencies are up to date (This may take a while)
npm WARN test-app@ No repository field.
npm WARN test-app@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 242 packages in 3.169s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Building frontend...

> test-app@ build /home/buildroot/test-app/frontend
> rollup -c

src/main.js → public/build/bundle.js...
lol(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@webcomponents/webcomponentsjs (imported by src/main.js)
created public/build/bundle.js in 4.8s
Pulling wailsapp/xgo:1.16.3 docker image... (may take a while)
1.16.3: Pulling from wailsapp/xgo
bd8f6a7501cc: Pull complete 
0795ee27d2f5: Pull complete 
57d08bde264b: Pull complete 
1fbdc4542f04: Pull complete 
add33bec9fea: Pull complete 
54151b3135ad: Pull complete 
786f77f7a7cf: Pull complete 
6b692cbf03b2: Pull complete 
0d394402d308: Pull complete 
25356377c6e3: Pull complete 
9ab9d31ccccb: Pull complete 
be287c46ed7d: Pull complete 
5d1db92966f8: Pull complete 
92387ff37cf4: Pull complete 
40942f4e2890: Pull complete 
d5ce8aef9c86: Pull complete 
1707f7779440: Pull complete 
9df44ec2a167: Pull complete 
5c192db2f727: Pull complete 
Digest: sha256:0ce614b7bb1dc45fd23ff7bf655640924f92aefcbf2d2018a9ce9b4fcc278be3
Status: Downloaded newer image for wailsapp/xgo:1.16.3
docker.io/wailsapp/xgo:1.16.3
Packing + Compiling project for linux/arm-7 using docker image wailsapp/xgo:1.16.3
chown: cannot access '/go/bin': No such file or directory
Building /source/go.mod...
go: downloading github.com/wailsapp/wails v1.16.8
go: downloading github.com/syossan27/tebata v0.0.0-20180602121909-b283fe4bc5ba
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/go-playground/colors v1.2.0
go: downloading github.com/abadojack/whatlanggo v1.0.1
go: downloading github.com/pkg/browser v0.0.0-20180916011732-0a3d74bf9ce4
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/Masterminds/semver v1.4.2
go: downloading github.com/jackmordaunt/icns v1.0.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/kennygrant/sanitize v1.2.4
go: downloading github.com/leaanthony/slicer v1.4.0
go: downloading github.com/leaanthony/spinner v0.5.3
go: downloading golang.org/x/image v0.0.0-20200430140353-33d19683fad8
go: downloading golang.org/x/sys v0.0.0-20211025201205-69cdffdb9359
go: downloading gopkg.in/yaml.v3 v3.0.0-20190709130402-674ba3eaed22
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading github.com/pkg/errors v0.8.1
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/leaanthony/synx v0.1.0
go: downloading github.com/leaanthony/wincursor v0.1.0
go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
Cleaning up build environment...
✓ Packaging application...
Awesome! Project 'test-app' built!
buildroot@buildroot-virtual-machine:~/test-app$ ll build/
total 8
drwx------ 2 buildroot buildroot 4096 Nov  9 09:28 ./
drwx------ 4 buildroot buildroot 4096 Nov  9 09:28 ../
buildroot@buildroot-virtual-machine:~/test-app$ ll go/bin
ls: cannot access 'go/bin': No such file or directory
buildroot@buildroot-virtual-machine:~/test-app$ ll ../go/bin/
total 11068
drwxrwxr-x 2 buildroot buildroot     4096 Nov  9 08:59 ./
drwxrwxr-x 4 buildroot buildroot     4096 Nov  9 08:59 ../
-rwxrwxr-x 1 buildroot buildroot 11322850 Nov  9 08:59 wails*
buildroot@buildroot-virtual-machine:~/test-app$ wails update -pre
Wails v1.16.8 - Checking for updates...

✗ Invalid Semantic Version
Error: Invalid Semantic Version

**Comment by leaanthony** [comment]
Linux/arm doesn't work unfortunately. Cross compiling is a big issue right now that needs someone to look at it. Either that or just compile in VMs or wait for v2!

**Comment by obikay200** [comment]
I was looking at v2 and playing with the windows version and it looks really good!

From your time line linux is due to drop now, have you got any time line for when it will be available? as im using it to build an embedded system prototyping on raspberrypi, hence the need for arm.

**Comment by leaanthony** [comment]
Thanks for your kind words! If you do a search in the issues, someone recently got xgo working with v1. The reason it's an issue is that our upstream xgo project had broken 1.16 support. That's fixed now, but it.s still broken on our side.

V2 Linux. I'm running late and it's starting now, however based on the new architecture and previous work (there was a lot of it!), the estimate is probably not far off, maybe Jan....

**Comment by obikay200** [comment]
awsome thanks

**Comment by leaanthony** [comment]
@obikay200 - let us know how you get on

**Comment by obikay200** [comment]
so didnt have much joy trying to cross compile, i ended up having a go building on the rpi its self and had some errors when the window loaded which meant it was very slow when it did eventually load. 

with v2 are you planning to do the cross compile so it can run on things like rpi 0 / 2/ 3/ 4 ?

I will keep playing in the meanwhile to see if i can get to the bottom of it

**Comment by leaanthony** [comment]
Absolutely. There are much better solutions for cross compiling now. We'll get this in before v2 launch.

**Comment by leaanthony** [comment]
V1 now in feature/bug freeze. Please migrate to v2 👍
