### ISSUE TITLE
Cursor disappears while dragging

### ISSUE THREAD

**Issue by egoist** [wailsapp/wails#929]
**Description**
Cursor disappears while dragging

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the bare minimal app generated by `wails init -n hello`
2. Drag the window

**Expected behavior**

Cursor does not disappear.

**Screenshots**

![CleanShot 2021-11-09 at 19 45 08](https://user-images.githubusercontent.com/8784712/140918531-ff7a1d34-4416-4721-86d6-60ec7d5cc843.gif)

**System Details**
Please provide your platform, GO version and variables, etc

- go version go1.17.3 darwin/amd64
- wails 2.0.0-beta.20

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
That's how the feature was designed. What's the benefit of showing the cursor?

**Comment by egoist** [comment]
I just find it weird since every other app still shows the cursor while dragging. 🤔

**Comment by leaanthony** [comment]
Wanna make a PR to add some config that works on Windows and Mac?

**Comment by leaanthony** [comment]
Fix on master 😄

**Comment by egoist** [comment]
Brilliant 😇

Lea Anthony ***@***.***>于2021年11月23日 周二下午6:08写道：
