### ISSUE TITLE
Problem installing wails on Windows

### ISSUE THREAD

**Issue by yosefbenshimon** [wailsapp/wails#93]
**Description**
Error initial compiling

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'CMD window'
2. Click on 'go get github.com/wailsapp/wails/cmd/wails'

3. See error:
```
# github.com/wailsapp/wails/cmd
C:\Users\u\go\src\github.com\wailsapp\wails\cmd\templates.go:50:18: too many arguments in call to entries.AddSlice
        have ([]string, error)
        want ([]string)
C:\Users\u\go\src\github.com\wailsapp\wails\cmd\templates.go:105:28: too many arguments in call to templateFilenames.AddSlice
        have ([]string, error)
        want ([]string)
```

**Expected behaviour**
Successful compiling
![download](https://user-images.githubusercontent.com/45950828/57975210-a8471c80-79cd-11e9-84a1-6b25fbfcf03e.png)

**System Details**
Windows 10 64 bit

**Comment by k4ml** [comment]
Having this same issue on osx 10.11.6:-

```
go get github.com/wailsapp/wails/cmd/wails
# github.com/wailsapp/wails/cmd
go/src/github.com/wailsapp/wails/cmd/templates.go:50:18: too many arguments in call to entries.AddSlice
	have ([]string, error)
	want ([]string)
go/src/github.com/wailsapp/wails/cmd/templates.go:105:28: too many arguments in call to templateFilenames.AddSlice
	have ([]string, error)
	want ([]string)
11:09:33 ~$ go version
go version go1.11.1 darwin/amd64
```

**Comment by leaanthony** [comment]
I had another report of this happening when GO111MODULE environment variable wasn't set to 'on'. Could you please recheck. I will investigate also.

**Comment by yosefbenshimon** [comment]
I added
```SET GO111MODULE=on```
And works perfect for me
Thank you!

**Comment by k4ml** [comment]
That strange as if I added `GO111MODULE=on` I will bump into [this issue](https://stackoverflow.com/questions/53368187/go-modules-installing-go-tools) and the recommendation there is to turn off `GO111MODULE=on`.

```
11:09:33 ~$ go version
go version go1.11.1 darwin/amd64
05:00:37 ~$ export GO111MODULE=on
05:00:42 ~$ go get github.com/wailsapp/wails/cmd/wails
go: cannot find main module; see 'go help modules'
```

**Comment by leaanthony** [comment]
Interesting. You could just use go 1.12. That being said, the issue above *should* be fixed now. Let me know!
