### ISSUE TITLE
build frontend error

### ISSUE THREAD

**Issue by uuxii** [wailsapp/wails#933]
code:

<template>
	<div class="about">
		<el-upload class="upload-demo" drag action="https://jsonplaceholder.typicode.com/posts/" multiple>
			<el-icon class="el-icon--upload">
				<upload-filled />
			</el-icon>
			<div class="el-upload__text">
				Drop file here or <em>click to upload</em>
			</div>
			<template #tip>
				<div class="el-upload__tip">
					jpg/png files with a size less than 500kb
				</div>
			</template>
		</el-upload>
		<el-button type="success" @click="getStr()">测试go方法</el-button>
	</div>
</template>
<script setup lang="ts">
	import {
		UploadFilled
	} from '@element-plus/icons'

	function getStr() {
		let str = 'afasdhfjhdf';
		window.go.main.App.Str(str).then(result => {
			console.log(result);
		});
		//window.runtime.Quit();
	}
</script>
<style>

</style>

The following errors occurred:

![1636598634(1)](https://user-images.githubusercontent.com/32015739/141228124-3e76cadc-5008-4d3c-8523-11c1d1474324.png)

I can`t build it . What to do deal with it? thanks.

**Comment by tomyjwu** [comment]
This is typescript type checking error. Nothing to do with Wails. 

Quick hack is using 
// @ts-ignore

before the line having the warning.

Full solution is depending on your team's Typescript coding rule. Here is a good blog on this
https://mariusschulz.com/blog/declaring-global-variables-in-typescript

**Comment by uuxii** [comment]
@tomyjwu thanks ,emm... https://github.com/codydbentley/wails-vite-vue-the-works/blob/main/frontend/src/components/Home.vue , the file,line 25, not used **// @ts-ignore** ,and not uesd some special settings .if I can`t understand it ,the project (wails-vite-vue-the-works) is as template...🤣🤣🤣🤣🤣🤣🤣
