### ISSUE TITLE
[Question]: Can I use wails to develop a status bar application on macos?

### ISSUE THREAD

**Issue by yeqown** [wailsapp/wails#934]
I wonder whether wails support to running in status bar on macos?

**Comment by leaanthony** [comment]
There is an alpha version that can do this - xbar uses it. I intend to port this functionality into the main branch for v2.2

**Comment by ethanchancc18** [comment]
May I ask if this feature is currently supported?

**Comment by leaanthony** [comment]
It will be officially supported in v3 👍
