### ISSUE TITLE
[v2] Mac OS

### ISSUE THREAD

**Issue by e8panse** [wailsapp/wails#939]
"wails dev" dies after "Executing: wails generate module"  on mac OS 11.5.2 (20G95) Intel CPU

**Description**

#bash#mytestproject % /Users/xxx/go/bin/wails dev
Wails CLI v2.0.0-beta.20

Executing: go mod tidy
Executing: wails generate module

#bash#mytestproject

After this nothing happens. Tested on Windows - works perfectly. But on Mac it just doesn't work

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init -n test -d mytestproject
2. cd to this folder
3. wails dev

**Expected behaviour**
Running project, but nothing happens

**System Details**

mac OS 11.5.2 (20G95) Intel CPU
Wails CLI v2.0.0-beta.20

tried
go version go1.17.1 darwin/amd64
go version go1.17.3 darwin/amd64

**Comment by leaanthony** [comment]
Strange nobody else has reported this. I'll pull out the old intel mac to test.

**Comment by e8panse** [comment]
It's worth to mention that "wails build" for the same project on the same Mac works perfect

**Comment by leaanthony** [comment]
What does `wails dev -v 2` do?

**Comment by e8panse** [comment]
The same output:

(base) x@Mac-mini-x mytestproject % /Users/x/go/bin/wails dev -v 2
Wails CLI v2.0.0-beta.20


Executing: go mod tidy
Executing: wails generate module

(base) dk@Mac-mini-x mytestproject %

**Comment by e8panse** [comment]
The same problem on mac OS 11.2.3 MAC1 CPU

**Comment by antimatter96** [comment]
Replicable on 
mac OS 11.4 (20F71) Intel CPU

```txt
OS:		MacOS
Version: 	11.4
ID:		199506
Go Version:	go1.17.2
Platform:	darwin
Architecture:	amd64

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode    	        N/A		       Installed	2384
npm 				N/A		       Installed	6.14.15
*upx 				N/A		       Available

**Comment by antimatter96** [comment]
@e8panse try adding ~/go/bin to your PATH and use `wails dev` directly

**Comment by leaanthony** [comment]
Glad you fixed it 👍
