### ISSUE TITLE
ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Virgil-N** [wailsapp/wails#940]
App build and when open it, shows "ERR_FILE_NOT_FOUND"

Vue 3.2.16
vite 2.6.4
vue-router 4.0.12
wails v2.0.0-beta.20

**Comment by leaanthony** [comment]
Not enough information, sorry.

**Comment by phoenix147** [comment]
@Virgil-N 

Just a wild guess, i had similar errors when navigating an app with vue and vue-router
The problem was the history mode of vue router, see https://next.router.vuejs.org/guide/essentials/history-mode.html

I'm using this in my index.js:

```
const router = createRouter({
  history: createWebHashHistory(),
  routes,
});

export default router;
```

**Comment by Goopil** [comment]
Ah interesting.
I had a similar problem and was forced to use

```javascript
import {createRouter, createWebHistory} from 'vue-router';
import {routes} from './routes'

const router = createRouter({
    history: createWebHistory(),
    routes,
})

export default router
```

the hash history dosen't seems to be supporter. You can see the call on the wails part.
`/#` fail not found. Resulting in a ui freeze.

**Comment by leaanthony** [comment]
Yeah the file not found issue was addressed recently on `master`. It would be awesome if you could retest the broken way :-)

**Comment by Goopil** [comment]
I will give a try in a little. 

I have found another thing. (should I open a new ticket ?)

it concern the setup i mentioned above. When using the `createWebHistory`, on a hot reload on a another route.
it seems that the same problem arise `/my-custom-route` note found.

I suppose you try to look at a file on the app side and try to serve it. But if the routing is done with a framework. This won't work :)

I suppose i should use the hash bang logic to work properly. (all the more needed to test your fix)

**Comment by leaanthony** [comment]
I recommend you use a hash based router: https://wails.io/docs/guides/routing
