### ISSUE TITLE
Support Distribution 'uos'

### ISSUE THREAD

**Issue by jibenliu** [wailsapp/wails#942]
**Description**
Distribution 'uos' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.8 |
| Go Version    | go1.16 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | uos |
| Distribution Name   | uos |
| Distribution Version   | 20 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by leaanthony** [comment]
Duplicate of https://github.com/wailsapp/wails/issues/888
