### ISSUE TITLE
Models  are not generated in Models.ts for output types

### ISSUE THREAD

**Issue by felixbecker** [wailsapp/wails#945]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
As discussed on the discussion board here: https://github.com/wailsapp/wails/discussions/828#discussioncomment-1643354 
it looks like the models are not generated for output types. 
Also if one access a list of objects via JavaScript it just returns plain objects. Methods on the JavaScript Objects will not be returned. Also shown in the discussion above.

**To Reproduce**
Steps to reproduce the behaviour:
https://github.com/wailsapp/wails/discussions/828#discussioncomment-1643354

**Expected behaviour**
Models should be generated. And Methods on the Models should also be available by JavaScript.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/wailsapp/wails/discussions/828#discussioncomment-1643354)

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Getting the models generated isn't too hard but getting the Go methods in Javascript will be a lot harder. What would that even look like? Do you have an example?

**Comment by leaanthony** [comment]
@felixbecker I've pushed an update to master that supports return params, but also slices of structs too :-)

**Comment by felixbecker** [comment]
Hi @leaanthony: thanks for your quick response. 
Unfortunately it is not generating the models for me.
Here is what I did. 

- I cloned the current master
- cd' in the v2 folder and `go build cmd/wails/main.go``
- with this binary I created the following project https://github.com/felixbecker/wailsmodelgenerationtest
- I added a `dataservice.go` file which contains a a method that returns all todo types 

Model.ts is still empty. In case I do something wrong ... let me know.

**Comment by leaanthony** [comment]
Make sure your project's `go.mod` has the replace line pointing to the code you checked out 👍

**Comment by leaanthony** [comment]
@felixbecker - how did you get on?

**Comment by felixbecker** [comment]
I am not able to get it running. I uncommented the replace statement in the `go.mod`-file.
When I build or try to run it ... I get the following error:
```
Installing frontend dependencies: Done.
Compiling frontend: Done.
Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin
WailsContext.m:502:21: error: use of undeclared identifier 'UTType'
WailsContext.m:502:29: error: use of undeclared identifier 't'
WailsContext.m:502:34: error: use of undeclared identifier 'UTType'
WailsContext.m:503:45: error: use of undeclared identifier 't'
WailsContext.m:505:25: warning: instance method '-setAllowedContentTypes:' not found (return type defaults to 'id') [-Wobjc-method-access]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenPanel.h:16:12: note: receiver is instance of class declared here
```
Do you have a hint what to do?

**Comment by leaanthony** [comment]
Ah that's an OS compatibility issue. What version of MacOS do you have?

**Comment by leaanthony** [comment]
@felixbecker - Could you please show me your `wails doctor` output and I'll try fixing your issue. Thanks.

**Comment by felixbecker** [comment]
Sorry, was busy the last days.  These are my `wails doctor` results.

```

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        10.14.6
ID:             199506
Go Version:     go1.17.2
Platform:       darwin
Architecture:   amd64

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2354
npm                             N/A             Installed       7.24.1
*upx                            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/

```

**Comment by leaanthony** [comment]
Apologies for the delay @felixbecker - Please pull latest master and try it. If I get chance today I'll see if I can test on 10.14

**Comment by felixbecker** [comment]
After I pulled in the last changes from the master ... models were created! So models.ts looks like this for my examples...

```
/* Do not change, this code is generated from Golang structs */

export {};

export class Todo {
    description: string;

    static createFrom(source: any = {}) {
        return new Todo(source);
    }

    constructor(source: any = {}) {
        if ('string' === typeof source) source = JSON.parse(source);
        this.description = source["description"];
    }
}
```

I guess we are missing an `import` when I look at `bindings.d.ts` (which uses the Todo class).
There should be something like `import {Todo} from './models'`

**Comment by leaanthony** [comment]
Sorry for letting this fall through the cracks. Do you think and `import * from './models'` would suffice?

**Comment by adalessa** [comment]
I have tested this my self and to make it works I added `import * as models from './models'` and need to add that prefix to the models name on the default of the switch of the function `goTypeToJSDocType`
```
	default:
		if strings.ContainsRune(input, '.') {
			return "models." + strings.Split(input, ".")[1]
		}
		return "any"
	}
```
Hope this helps, I can help with the PR if you agree with the solution.
Thanks.

**Comment by leaanthony** [comment]
That would be great! Thanks!

**Comment by leaanthony** [comment]
@felixbecker - this should solve your problem. Please feel free to reopen if it doesn't 👍

**Comment by leaanthony** [comment]
@felixbecker @adalessa - I've just pushed a commit to master that takes a slightly different approach to the typescript generation and would love your feedback. The bindings are generated into their own logical packages with their own `.d.ts` files. The original approach just wouldn't work for me (it was non-obvious how to make it work). This approach appears to work for me and seems more natural from a dev perspective (apart from a weird "models doesn't export XYZ" issue which appears to be untrue). Would love your feedback on it.

**Comment by adalessa** [comment]
@leaanthony I have taken a look. It's a great change, but I found a bug when testing on my current project, when you have methods returning the same structure it duplicates the imports. I have created a PR #1307 which solves it please take a look.

**Comment by leaanthony** [comment]
Ah, of course! Nice catch! Thanks for making the PR, will check 👍

**Comment by leaanthony** [comment]
So is the TS valid for you? The next thing I'd like to do is bring the models into the package too to ensure no collisions

**Comment by adalessa** [comment]
>The next thing I'd like to do is bring the models into the package too to ensure no collisions

What structure do you have in mind for this ?

> So is the TS valid for you?

Looks valid, I have some linter complaining that about the `models.ts` that exports multiples clases when the maximum should be 1. But is just the linter, does not fail on compilation nor execution.

**Comment by leaanthony** [comment]
I was thinking a local models.ts but if it's complaining about multiple classes being exported then...

**Comment by adalessa** [comment]
It could generate a folder `models` inside of the namepsace folder for example `main`  and have the import on the definitions like
```
import { MyModel } from './Models/MyModel'
```
instead of 
```
import { MyModel } from '../models'
```

What do you think ?

**Comment by leaanthony** [comment]
I've pushed a different approach to master. I realised that moving the models to their own packages will create import issues when types depend on types so the approach I'm taking is this:
1. All models are placed in `models.ts` at the top level. Each package is represented as a namespace:
2. Function declarations use fully qualified types and the package is imported from `models.ts`

Given the following structs are bound in `App.go`:
```go
type Person struct {
    Name string `json:"name"`
}

type Avatar struct {
    Name string `json:"name"`
}
```
The following structure will be generated:
![image](https://user-images.githubusercontent.com/1943904/161532182-f7de64b7-1b86-4797-a639-ac7aeaba3b7e.png)

`App.d.ts`:
```ts
import {main} from '../models';

export function Greet(arg1:main.Person):Promise<main.Avatar>;
```
`models.ts`:
```ts
export namespace main {
	
	export class Person {
	    name: string;
	
	    static createFrom(source: any = {}) {
	        return new Person(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.name = source["name"];
	    }
	}
	export class Avatar {
	    name: string;
	
	    static createFrom(source: any = {}) {
	        return new Avatar(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.name = source["name"];
	    }
	}

}
```

Thoughts?

**Comment by adalessa** [comment]
@leaanthony Like that looks good but I am currently testing it and for my current project am I getting duplicated classes generated on models.ts and I have a collision on the namespace I have in my code on the package `main` and in a package `models` but only one file is generated `models.ts` with only the namespace `main` . Also on the `App.d.ts` is imported one 
```
import {models} from '../models';
```
I think it necessary to polish this idea with this cases. Looks like for a simple case works good.
I need time to check on my project and try to look for a solution to suggest.

**Comment by leaanthony** [comment]
That sounds like I haven't pushed everything because you shouldn't ever get that import. Will check

**Comment by adalessa** [comment]
Something that I have (maybe is not the intended) on my app.go file I have a method that returns from other path 
```
func (a *App) FolderGet() models.Folder {
	folder, err := a.folderScanService.Get()
	if err != nil {
		// a.error("error getting folder", err)
	}

	return folder
}

```

where models I have related to some gorm models I have created.

Something that I notice here https://github.com/wailsapp/wails/blob/master/v2/internal/binding/reflect.go#L145 is that is set that the package name is not set on the returned structure instead is set by the package of the binded element if I am not mistaken.

Related to the import I have debuged this part of the code 
```
				for count, input := range methodDetails.Inputs {
					arg := fmt.Sprintf("arg%d", count+1)
					args.Add(arg + ":" + goTypeToTypescriptType(input.TypeName))
					if strings.ContainsRune(input.TypeName, '.') {
						importNamespaces.Add(strings.Split(input.TypeName, ".")[0])
					}
				}
```
The code to add the namespace is only for the input params not for the return so the return params never get the package name read.
So I think is necessary to add similar code for the output parameters.
```
				if methodDetails.OutputCount() > 0 {
					firstType := goTypeToTypescriptType(methodDetails.Outputs[0].TypeName)
					returnType += "<" + firstType
					if methodDetails.OutputCount() == 2 {
						secondType := goTypeToTypescriptType(methodDetails.Outputs[1].TypeName)
						returnType += "|" + secondType
					}
					returnType += ">"
				} else {
					returnType = "Promise<void>"
				}

```
Also notice that getting the namespace in this way if the input is an array will try to import as 
```
import {[]main} from '../models';
```
This will need  to be removed if detected.

**Comment by leaanthony** [comment]
I've pushed a fix. The only thing I can see as still being an issue is nested struct references, EG: struct A.AA has a field of type B.BB

**Comment by adalessa** [comment]
Cool that fixed several things, I notice that is duplicating classes on the `models.ts` if you have two structures that have a property of the same type (another structure) this second structure is generated so many times as it is use. I think when generating the file need to filter by the structure name 
I checked this piece of code 
```
	for packageName, structsToGenerate := range b.structsToGenerateTS {
		thisPackageCode := ""
		for _, structInterface := range structsToGenerate {
			w := typescriptify.New()
			w.WithBackupDir("")
			w.Add(structInterface)
			str, err := w.Convert(nil)
			if err != nil {
				return err
			}
			thisPackageCode += str
		}
		models[packageName] = thisPackageCode
	}
```
This is the expected return objects that we have which is correct and being a map does not duplicate the elements. But when calling the `w.Add` the structure is analyzed to be converted and generate the structures for the internal elements which duplicates the code

Here is the output of the build when converting the objects for my project
```
Converting type main.ProductInfo
- simple field ProductInfo.Id
- simple field ProductInfo.Name
- struct slice ProductInfo.VariantInfo ([]main.VariantInfo)
   Converting type main.VariantInfo
   - simple field VariantInfo.Id
   - simple field VariantInfo.Image
   - simple field VariantInfo.ImageSrc
   - simple field VariantInfo.Value1
   - simple field VariantInfo.Value2
   - simple field VariantInfo.Value3
   - simple field VariantInfo.SubVariantCount
Converting type main.IProductType
- simple field IProductType.ID
- struct IProductType.CreatedAt (time.Time)
   Converting type time.Time
- struct IProductType.UpdatedAt (time.Time)
- simple field IProductType.Name
- simple field IProductType.Path
- struct slice IProductType.Variants ([]models.Variant)
   Converting type models.Variant
   - simple field Variant.ID
   - struct Variant.CreatedAt (time.Time)
   - struct Variant.UpdatedAt (time.Time)
   - simple field Variant.Number
   - simple field Variant.Name
   - simple field Variant.Values
   - simple field Variant.ProductTypeId
- simple field IProductType.Categories
- struct slice IProductType.VariantValues ([]models.VariantValue)
   Converting type models.VariantValue
   - simple field VariantValue.ID
   - struct VariantValue.CreatedAt (time.Time)
   - struct VariantValue.UpdatedAt (time.Time)
   - simple field VariantValue.ProductTypeId
   - simple field VariantValue.Variant1Value
   - simple field VariantValue.Variant2Value
   - simple field VariantValue.Variant3Value
   - simple field VariantValue.Price
   - simple field VariantValue.Weight
   - simple field VariantValue.Depth
   - simple field VariantValue.Width
   - simple field VariantValue.Height
   - simple field VariantValue.PromotionalPrice
- struct slice IProductType.Products ([]models.Product)
   Converting type models.Product
   - simple field Product.ID
   - struct Product.CreatedAt (time.Time)
   - struct Product.UpdatedAt (time.Time)
   - simple field Product.Name
   - simple field Product.ProductTypeId
   - struct Product.ProductType (models.ProductType)
      Converting type models.ProductType
      - simple field ProductType.ID
      - struct ProductType.CreatedAt (time.Time)
      - struct ProductType.UpdatedAt (time.Time)
      - simple field ProductType.Name
      - simple field ProductType.Path
      - struct slice ProductType.Variants ([]models.Variant)
      - simple field ProductType.Categories
      - struct slice ProductType.VariantValues ([]models.VariantValue)
      - struct slice ProductType.Products ([]models.Product)
      - simple field ProductType.Description
      - struct ProductType.Folder (models.Folder)
         Converting type models.Folder
         - simple field Folder.ID
         - struct Folder.CreatedAt (time.Time)
         - struct Folder.UpdatedAt (time.Time)
         - simple field Folder.Path
         - struct Folder.LastSyncAt (time.Time)
         - struct slice Folder.ProductTypes ([]models.ProductType)
      - simple field ProductType.FolderId
   - simple field Product.TiendaNubeId
   - struct slice Product.Variants ([]models.ProductVariant)
      Converting type models.ProductVariant
      - simple field ProductVariant.ID
      - struct ProductVariant.CreatedAt (time.Time)
      - struct ProductVariant.UpdatedAt (time.Time)
      - struct ProductVariant.Product (models.Product)
      - simple field ProductVariant.ProductId
      - struct ProductVariant.Image (models.Image)
         Converting type models.Image
         - simple field Image.ID
         - struct Image.CreatedAt (time.Time)
         - struct Image.UpdatedAt (time.Time)
         - simple field Image.Path
         - simple field Image.ProductVariantID
         - simple field Image.TiendaNubeId
         - struct Image.LastSyncAt (sql.NullTime)
            Converting type sql.NullTime
      - simple field ProductVariant.Variant1Value
      - simple field ProductVariant.Variant2Value
      - simple field ProductVariant.Variant3Value
   - struct Product.LastSyncAt (sql.NullTime)
- simple field IProductType.Description
- struct IProductType.Folder (models.Folder)
- simple field IProductType.FolderId
- simple field IProductType.ProductAmount
Converting type response.Category
- simple field Category.Id
- struct Category.Name (response.MultiLang)
   Converting type response.MultiLang
   - simple field MultiLang.Es
   - simple field MultiLang.En
   - simple field MultiLang.Pt
- struct Category.Description (response.MultiLang)
- struct Category.Handle (response.MultiLang)
- simple field Category.Parent
- slice field Category.SubCategories
Converting type models.Folder
- simple field Folder.ID
- struct Folder.CreatedAt (time.Time)
   Converting type time.Time
- struct Folder.UpdatedAt (time.Time)
- simple field Folder.Path
- struct Folder.LastSyncAt (time.Time)
- struct slice Folder.ProductTypes ([]models.ProductType)
   Converting type models.ProductType
   - simple field ProductType.ID
   - struct ProductType.CreatedAt (time.Time)
   - struct ProductType.UpdatedAt (time.Time)
   - simple field ProductType.Name
   - simple field ProductType.Path
   - struct slice ProductType.Variants ([]models.Variant)
      Converting type models.Variant
      - simple field Variant.ID
      - struct Variant.CreatedAt (time.Time)
      - struct Variant.UpdatedAt (time.Time)
      - simple field Variant.Number
      - simple field Variant.Name
      - simple field Variant.Values
      - simple field Variant.ProductTypeId
   - simple field ProductType.Categories
   - struct slice ProductType.VariantValues ([]models.VariantValue)
      Converting type models.VariantValue
      - simple field VariantValue.ID
      - struct VariantValue.CreatedAt (time.Time)
      - struct VariantValue.UpdatedAt (time.Time)
      - simple field VariantValue.ProductTypeId
      - simple field VariantValue.Variant1Value
      - simple field VariantValue.Variant2Value
      - simple field VariantValue.Variant3Value
      - simple field VariantValue.Price
      - simple field VariantValue.Weight
      - simple field VariantValue.Depth
Watching (sub)/directory: /home/alpha/code/go/src/github.com/adalessa/tn-desktop/dev      - simple field VariantValue.Width

      - simple field VariantValue.Height
      - simple field VariantValue.PromotionalPrice
Using DevServer URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
   - struct slice ProductType.Products ([]models.Product)
      Converting type models.Product
      - simple field Product.ID
      - struct Product.CreatedAt (time.Time)
      - struct Product.UpdatedAt (time.Time)
      - simple field Product.Name
      - simple field Product.ProductTypeId
      - struct Product.ProductType (models.ProductType)
      - simple field Product.TiendaNubeId
      - struct slice Product.Variants ([]models.ProductVariant)
         Converting type models.ProductVariant
         - simple field ProductVariant.ID
         - struct ProductVariant.CreatedAt (time.Time)
         - struct ProductVariant.UpdatedAt (time.Time)
         - struct ProductVariant.Product (models.Product)
         - simple field ProductVariant.ProductId
         - struct ProductVariant.Image (models.Image)
            Converting type models.Image
            - simple field Image.ID
            - struct Image.CreatedAt (time.Time)
            - struct Image.UpdatedAt (time.Time)
            - simple field Image.Path
            - simple field Image.ProductVariantID
            - simple field Image.TiendaNubeId
            - struct Image.LastSyncAt (sql.NullTime)
               Converting type sql.NullTime
         - simple field ProductVariant.Variant1Value
         - simple field ProductVariant.Variant2Value
         - simple field ProductVariant.Variant3Value
      - struct Product.LastSyncAt (sql.NullTime)
   - simple field ProductType.Description
   - struct ProductType.Folder (models.Folder)
   - simple field ProductType.FolderId
Converting type models.VariantValue
- simple field VariantValue.ID
- struct VariantValue.CreatedAt (time.Time)
   Converting type time.Time
- struct VariantValue.UpdatedAt (time.Time)
- simple field VariantValue.ProductTypeId
- simple field VariantValue.Variant1Value
- simple field VariantValue.Variant2Value
- simple field VariantValue.Variant3Value
- simple field VariantValue.Price
- simple field VariantValue.Weight
- simple field VariantValue.Depth
- simple field VariantValue.Width
- simple field VariantValue.Height
- simple field VariantValue.PromotionalPrice
Converting type models.Store
- simple field Store.ID
- struct Store.CreatedAt (time.Time)
   Converting type time.Time
- struct Store.UpdatedAt (time.Time)
- simple field Store.Token
- simple field Store.TokenType
- simple field Store.Scope
- simple field Store.UserId
Converting type models.ProductType
- simple field ProductType.ID
- struct ProductType.CreatedAt (time.Time)
   Converting type time.Time
- struct ProductType.UpdatedAt (time.Time)
- simple field ProductType.Name
- simple field ProductType.Path
- struct slice ProductType.Variants ([]models.Variant)
   Converting type models.Variant
   - simple field Variant.ID
   - struct Variant.CreatedAt (time.Time)
   - struct Variant.UpdatedAt (time.Time)
   - simple field Variant.Number
   - simple field Variant.Name
   - simple field Variant.Values
   - simple field Variant.ProductTypeId
- simple field ProductType.Categories
- struct slice ProductType.VariantValues ([]models.VariantValue)
   Converting type models.VariantValue
   - simple field VariantValue.ID
   - struct VariantValue.CreatedAt (time.Time)
   - struct VariantValue.UpdatedAt (time.Time)
   - simple field VariantValue.ProductTypeId
   - simple field VariantValue.Variant1Value
   - simple field VariantValue.Variant2Value
   - simple field VariantValue.Variant3Value
   - simple field VariantValue.Price
   - simple field VariantValue.Weight
   - simple field VariantValue.Depth
   - simple field VariantValue.Width
   - simple field VariantValue.Height
   - simple field VariantValue.PromotionalPrice
- struct slice ProductType.Products ([]models.Product)
   Converting type models.Product
   - simple field Product.ID
   - struct Product.CreatedAt (time.Time)
   - struct Product.UpdatedAt (time.Time)
   - simple field Product.Name
   - simple field Product.ProductTypeId
   - struct Product.ProductType (models.ProductType)
   - simple field Product.TiendaNubeId
   - struct slice Product.Variants ([]models.ProductVariant)
      Converting type models.ProductVariant
      - simple field ProductVariant.ID
      - struct ProductVariant.CreatedAt (time.Time)
      - struct ProductVariant.UpdatedAt (time.Time)
      - struct ProductVariant.Product (models.Product)
      - simple field ProductVariant.ProductId
      - struct ProductVariant.Image (models.Image)
         Converting type models.Image
         - simple field Image.ID
         - struct Image.CreatedAt (time.Time)
         - struct Image.UpdatedAt (time.Time)
         - simple field Image.Path
         - simple field Image.ProductVariantID
         - simple field Image.TiendaNubeId
         - struct Image.LastSyncAt (sql.NullTime)
            Converting type sql.NullTime
      - simple field ProductVariant.Variant1Value
      - simple field ProductVariant.Variant2Value
      - simple field ProductVariant.Variant3Value
   - struct Product.LastSyncAt (sql.NullTime)
- simple field ProductType.Description
- struct ProductType.Folder (models.Folder)
   Converting type models.Folder
   - simple field Folder.ID
   - struct Folder.CreatedAt (time.Time)
   - struct Folder.UpdatedAt (time.Time)
   - simple field Folder.Path
   - struct Folder.LastSyncAt (time.Time)
   - struct slice Folder.ProductTypes ([]models.ProductType)
- simple field ProductType.FolderId
```
I know is long but if you nee for example the `models.Image` is converted 3 times and for so it written on the file 3 times breaking the file due having duplicate classes names.

A possible solution that I tested that works is  to not create a new typescript per structure, create one per package
```
	for packageName, structsToGenerate := range b.structsToGenerateTS {
		thisPackageCode := ""
		w := typescriptify.New()
		w.WithBackupDir("")
		for _, structInterface := range structsToGenerate {
			w.Add(structInterface)
		}
		str, err := w.Convert(nil)
		if err != nil {
			return err
		}
		thisPackageCode += str
		models[packageName] = thisPackageCode
	}
```
temporary variable `thisPackageCode` is no longer necessary but I just leave it  to show the switch with minimum change of code.

**Comment by adalessa** [comment]
I have another question. Before there was this file `bindings.d.ts` like mine
```
import * as models from './models';

export interface go {
  "main": {
    "App": {
		FolderGet():Promise<models.Folder>
		...
    }
  }

}

declare global {
	interface Window {
		go: go;
	}
}
```
Importing this file allow in the code to call the methods from js like 
`window.go.main.App.....`

I fix that to switch to import directly from the generated like 
```
import {
  FolderGet, FolderScan, FolderSelection, StoreGet, StoreSave,
} from './wailsjs/go/main/App';
```
Is that the intended way ? 
I like it because removed the need of the whole path `window.go.main.App`
It will be necessary update the docs for this change at lease for TS. Not sure if has any impact on normal js projects.

**Comment by leaanthony** [comment]
Yes this is the intended way. I just pushed support for recursive and cross-package references. Let me know how you get on 👍

**Comment by leaanthony** [comment]
Just pushed a small fix for duplicate model generation and updated the docs [here](https://wails.io/docs/next/howdoesitwork#the-frontend). Please let me know if you think anything could be improved 👍

**Comment by adalessa** [comment]
@leaanthony  Thanks for the hard work. I checked out. I have some problems but looks like more on my code, I have tried to replicate them on a new project and I am not able so I think the change is good.
I have a doubt how to handle `time.Time` properties on the struct. I have tested and I see that generates the classes but has empty fields example
```
type Test struct {
	Name string    `json:"name"`
	Time time.Time `json:"time"`
}

func (a *App) Greet2(name string) Test {
	return Test{
		Name: name,
		Time: time.Now(),
	}
}
```
when builded generates this 
```
export namespace main {
	
	export class Test {
	    name: string;
	    time: time.Time;
	
	    static createFrom(source: any = {}) {
	        return new Test(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.name = source["name"];
	        this.time = this.convertValues(source["time"], time.Time);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
		    if (!a) {
		        return a;
		    }
		    if (a.slice) {
		        return (a as any[]).map(elem => this.convertValues(elem, classs));
		    } else if ("object" === typeof a) {
		        if (asMap) {
		            for (const key of Object.keys(a)) {
		                a[key] = new classs(a[key]);
		            }
		            return a;
		        }
		        return new classs(a);
		    }
		    return a;
		}
	}

}

export namespace time {
	
	export class Time {
	
	
	    static createFrom(source: any = {}) {
	        return new Time(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	
	    }
	}
	export class Location {
	
	
	    static createFrom(source: any = {}) {
	        return new Location(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	
	    }
	}
	export class zone {
	
	
	    static createFrom(source: any = {}) {
	        return new zone(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	
	    }
	}

}

```

Is this something that should be handle on the generator and treat as an special case ?

**Comment by leaanthony** [comment]
Hey @adalessa - thanks for the awesome feedback. I've made a few quick fixes that should improve things:
  - If a struct has no fields with json tags, it's not generated
  - If a namespace has no structs, it's not generated
  - If a struct has a field with an unknown struct type (eg time.Time), it's given an `any` type with a comment indicating the original struct type in Go

I'm sure there's some edge cases but this should improve things. Thanks for your continued testing 🙏

**Comment by ilgityildirim** [comment]
@leaanthony `If a struct has no fields with json tags, it's not generated` this saved me a headache now! Thank you for this.

**Comment by pbnjay** [comment]
Oh man `If a struct has no fields with json tags, it's not generated` I wish this was documented somewhere more obvious, I've been banging my head trying to figure this out for a while!

Go's default is for JSON w/o an explicit tag is to use the exported Go field names! I think this feature would be much more intuitive if it used `json:"-"` instead of missing tags to decide on exclusion.

**Comment by leaanthony** [comment]
Happy to accept a PR for this! 🙏
