### ISSUE TITLE
There is a bit confusing of the wails.json

### ISSUE THREAD

**Issue by jincandev** [wailsapp/wails#947]
The `devserverurl` item in `wails.json` is a bit confusing. If you use a third packaging scheme such as `vite`, there is no need for wails to listen to the port. You only need to access the port. However, now that `devserverurl` is configured, wails directly serves as a service, which is not very useful for integration packaging, does it?

**Comment by leaanthony** [comment]
`devserverurl` makes your dev app forward all requests to the url.

**Comment by jcindex** [comment]
@leaanthony However, The command `wails dev` can only load the static files built by the third-party packaging tool for UI display. As you said, `devserverurl` is used to forward the requests sent by the application, so the requests can only access the static file. This seems to have no meaning, When I use the Chrome browser to access the host configured by the `devserverurl`, the browser displays the built static page UI, so I'm confused.

**Comment by leaanthony** [comment]
I guess i'm not really sure what you're trying to do. There's plenty of discussion on this in the discussions board. devserverurl is experimental right now and it's not a dev solution quite yet
