### ISSUE TITLE
can not install wails

### ISSUE THREAD

**Issue by huayun321** [wailsapp/wails#95]
~ go get -u -v github.com/wailsapp/wails/cmd/wails
github.com/wailsapp/wails (download)
github.com/leaanthony/spinner (download)
github.com/fatih/color (download)
github.com/leaanthony/synx (download)
github.com/mattn/go-isatty (download)
github.com/mitchellh/go-homedir (download)
github.com/pkg/browser (download)
github.com/jackmordaunt/icns (download)
github.com/nfnt/resize (download)
github.com/pkg/errors (download)
github.com/leaanthony/mewn (download)
github.com/leaanthony/slicer (download)
github.com/masterminds/semver (download)
github.com/wailsapp/wails/cmd
# github.com/wailsapp/wails/cmd
go-work/src/github.com/wailsapp/wails/cmd/templates.go:50:18: too many arguments in call to entries.AddSlice
	have ([]string, error)
	want ([]string)
go-work/src/github.com/wailsapp/wails/cmd/templates.go:105:28: too many arguments in call to templateFilenames.AddSlice
	have ([]string, error)
	want ([]string)

**Comment by leaanthony** [comment]
Hi. As [per the docs](https://wails.app/home.html#installation), enable Go modules and it will install correctly :-)

**Comment by leaanthony** [comment]
@huayun321 please let me know if you have any further issues or close. Thanks :-)

**Comment by leaanthony** [comment]
I just noticed, you used `-u` in the go get. That would create a bad install.

**Comment by leaanthony** [comment]
@huayun321 please try again. Please note that it is recommended to use Go 1.12. Your issue should be fixed.

**Comment by leaanthony** [comment]
@huayun321 could you please confirm if this is now working for you? I close issues after 7 days inactivity.

**Comment by leaanthony** [comment]
Closed due to inactivity.
