### ISSUE TITLE
[v2] macOS background color is not correct

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#953]
**Description**
Setting the BackgroundColor in RGBA on the AppOptions is not correct for macOS if values other than 0 or 255 are used. The problem is located in the in WailsContext.m in [SetRGBA](https://github.com/wailsapp/wails/blob/d569e37b81775d033444002625e91b287246fc82/v2/internal/frontend/desktop/darwin/WailsContext.m#L302-L305), where the channels are not scaled with a float.

**To Reproduce**
Create a new v2 template and set the RGBA on the options to e.g. `RGBA:   &options.RGBA{R: 0x9a, G: 0x4e, B: 0xaa, A: 0xff}`

**Expected behaviour**
The correct color is used for the background.

**System Details**
MacOS Version:  12.0.1
Go Version:     go1.17.2

**Comment by leaanthony** [comment]
Nice catch, and thanks!

**Comment by stffabi** [comment]
You're welcome, and thanks for the very fast merge of the PR.
