### ISSUE TITLE
[v2]Front-end resources using the esmodule function have errors in browser debugging in dev mode

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#963]
#####################################################
     **If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
When the front-end uses the esmodule solution, the `wails dev` mode will have an error in the browser, but this does not affect the `wails build`. The specific cause of the problem has been identified, as shown in the following figure:

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails init -n Wails-Vue -t https://github.com/misitebao/wails-template-vue` (This can be any front-end project that uses esmodule)
2. Run `cd Wails-Vue`
3. Run `wails dev`

**Expected behaviour**
The esmodule function is the development trend of the front-end. As a library that strongly relies on front-end resources, wails should adapt to and keep up with the development of the front-end, so I think this problem should be considered and solved so that wails can be as advertised - **support any front-end project**.

**Screenshots**
This is the browser console in `wails dev` mode:
![image](https://user-images.githubusercontent.com/28185258/143020143-b0d24cad-72d2-49c2-b251-20b6973c1e65.png)
This is the browser console to open the front-end project normally:
![image](https://user-images.githubusercontent.com/28185258/143020284-46fa65a1-39d2-4a20-9903-efe7ed7ba075.png)

The reason for the problem is that when using `esmodule`, the `import {xxx}from xxx` statement must be at the outermost level of the file. In the `wails dev` mode, it is nested in a function callback. This is not a problem in non-`esmodule` projects, but in `esmodule` projects, this is a syntax error.

**Suggested solution:** You can try to put only the js code behind `import {xxx}from xxx` into the callback function, so that you can solve the problem of grammatical errors.

**System Details**
![image](https://user-images.githubusercontent.com/28185258/143019268-344c2c0e-c54e-4276-83f6-39637ff363f7.png)

**Additional context**
No.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
I've implemented a much better way of handling this that will fix this issue. Please test :-)

**Comment by misitebao** [comment]
@leaanthony 
Great, it has passed the test.😎
