### ISSUE TITLE
[v2] Windows: Backend callbacks get lost when moving window

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#969]
**Description**
Callbacks get not triggered on MainThread, when the windows is getting moved or when one clicks on the title bar and keeps pressing the mouse button.

**To Reproduce**
1. Create a new v2 template and adjust main.js with the following code
```js
let nameElement = document.getElementById("name");
nameElement.focus();

let counter = 0;
window.greet = function () {
  let name = nameElement.value;
  counter++;
  window.go.main.App.Greet(name + " " + counter).then((result) => {
    document.getElementById("result").innerText = result;
    setTimeout(greet, 1000);
  });
};

nameElement.onkeydown = function (e) {
  console.log(e)
  if (e.keyCode == 13) {
    window.greet()
  }
}
```
2. Compile for windows and run the app on windows.
3. Click on the greet button and see that the counter gets increased every second.
4. Click on the title bar of the window and keep pressing, the counter suddenly stops and the callback is not triggered.

**Expected behaviour**
Callbacks should be called regardless of clicking on the title bar or moving the window.

**System Details**
Wails Version: v2.0.0-beta.21
MacOS Version: 12.0.1
Go Version: go1.17.2
Windows Version: Windows 10 20H2

**Additional context**
The problem seems to be caused by using PostThreadMessage to change into the main thread for executing the callback here: https://github.com/wailsapp/wails/blob/9735bd1b0192cbbc0ce48808d422b7ac726a9211/v2/internal/frontend/desktop/windows/window.go#L116

According to this [Thread messages are eaten by modal loops](https://devblogs.microsoft.com/oldnewthing/20050426-18/?p=35783) a nested modal loop might just catch the message but it will never reach the root message loop here:

https://github.com/wailsapp/wails/blob/9735bd1b0192cbbc0ce48808d422b7ac726a9211/v2/internal/frontend/desktop/windows/window.go#L88-L100

Another devblog post from MS [Why are my posted messages getting lost when the user drags my window around?
](https://devblogs.microsoft.com/oldnewthing/20130905-00/?p=3313) suggest to use PostMessage instead of PostThreadMessage and to use a WNDPROC message.

I've added a new `Invoke` method to winc in order to address this issue, I'll provide a PR on winc in order to discuss it. As soon as this `Invoke` method exists, we could use it in wails to change to the GUI thread.

**Comment by leaanthony** [comment]
This is incredible!
