### ISSUE TITLE
v2) support window close event control

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#978]
### Discussed in https://github.com/wailsapp/wails/discussions/977

<div type='discussions-op-text'>

<sup>Originally posted by **Ironpark** November 26, 2021</sup>
# Proposal
Name: OnCloseBefore or OnBeforeClose

Type: func(ctx context.Context) (prevent bool)

This callback is Called when the window close button is pressed, just before the application close. It provides the application context and if the return value is true , ignores the close event and does not close the application.

## Why
If we can control the close event fires or not
"There is work in progress. Are you sure you want to quit?" or "Are you sure you want to exit?" UX scenarios that prevent user mistakes, such as popping up a dialog like this, become possible.

## Example

```go
 func OnCloseBefore(ctx context.Context) (prevent bool){
    selection, _ := runtime.MessageDialog(b.ctx, runtime.MessageDialogOptions{
        Type:              runtime.WarningDialog,
        Title:               "There is work in progress!",
        Message:       "Are you sure you want to exit?",
        Buttons:       []string{"Yes", "No"},
        DefaultButton: "Yes",
        CancelButton:  "No",
    })
    return selection == "No"
 }
```</div>

**Comment by leaanthony** [comment]
Thanks for raising this! Agree it's a good idea and we should talk about it more. Some thoughts:

- Do you a think a single hook would suffice? 
- Would that be in the config or a runtime setting?
- Would this also work when using `Quit` in the menu?
- What about calling it `OnBeforeClose`?

**Comment by Ironpark** [comment]
- Do you a think a single hook would suffice?
Yes, I think hooks like `OnWindowMinimiseBefore`, `OnWindowMaximiseBefore` are also possible, but I think the case where this is needed is a very unique case. If you need to control all these window events, I think it's better to write a separate hook like `OnBeforeWindowControlEvent(event runtime.WindowCrtEvent, ctx context.Context, cancel func())` 

- Would that be in the config or a runtime setting?
This proposal was written with the intention of being added inside `options.App{}`,but if there is a better way, it's ok to change!  😃 

- Would this also work when using `Quit` in the menu?
Yes!

- What about calling it OnBeforeClose?
Yep! agree 👌

**Comment by leaanthony** [comment]
Are you willing to try to implement this?

**Comment by Ironpark** [comment]
> Are you willing to try to implement this?

For a while, I spent some time examining whether it could be implemented with my skills and knowledge line.

In the case of Mac, I thought that it would be possible to implement using `windowShouldClose`. However, in the current version `v2.0.0-beta.21`, `HideWindowOnClose` did not work as expected, so I doubt that `windowShouldClose` in desktop/darwin/WindowDelegate.m` is being called properly.

```
System Info
- OS: MacOS Big Sur (11.5.2)
- Wails : v2.0.0-beta.21
```
Unfortunately, I currently don't have enough knowledge to solve this.

**Comment by leaanthony** [comment]
Hey @Ironpark, haven't forgotten about this. I was thinking that perhaps the best option would be to add the logic to the frontend "Quit" method. All quit methods (runtime + close window) will start here.  Might be easier for you to have a go?

**Comment by stffabi** [comment]
I would also be very interested in this feature, so if you @Ironpark need any help or have questions I would be happy to try to assist you.

**Comment by marcio199226** [comment]
Me too, in case I will take a look for this how can it be implemented on front-end side.

**Comment by Ironpark** [comment]
@leaanthony @stffabi @marcio199226 
Today I created and tested a simple implementation of this idea.
https://github.com/Ironpark/wails/commit/fda3323386c38400de1a00ba4542c6fb766d8d8d

``` go
type App struct {
        // .....
	OnBeforeClose     func(ctx context.Context) (prevent bool) `json:"-"`
}
```
``` go
// -- wails/v2/internal/frontend/desktop/{}/frontend.go
func (f *Frontend) Quit() {
	if f.frontendOptions.OnBeforeClose != nil && f.frontendOptions.OnBeforeClose(f.ctx) {
		return
	}
	f.mainWindow.Quit()
}
```
But there's a little bit of a problem.
1. In the case of Quit through the menu bar (it works)
2. When the close button on the title bar is pressed (does not work)

**Comment by leaanthony** [comment]
For Mac, I think you'll have to return False in the close delegate method if that hook is set

**Comment by Ironpark** [comment]
> For Mac, I think you'll have to return False in the close delegate method if that hook is set

I modified the windowShouldClose delegate method a bit, and it seems to be working fine.

https://github.com/wailsapp/wails/pull/1007
```obj-c
@implementation WindowDelegate
- (BOOL)windowShouldClose:(WailsWindow *)sender {
    if( self.hideOnClose ) {
        [NSApp hide:nil];
        return false;
    }
    processMessage("Q");
    return false;
}
```
