### ISSUE TITLE
[v2] runtime.Log cause the program to crash on compiled binary

### ISSUE THREAD

**Issue by MadeBaruna** [wailsapp/wails#983]
**Description**
When calling runtime.Log (eg LogInfo, LogError) the app will crash on compiled bin, works fine on dev.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project
2. Create a function that call runtime.Log
```go
func (b *App) Greet(name string) string {
	runtime.LogInfo(b.ctx, "Test")
	return fmt.Sprintf("Hello %s, It's show time!", name)
}
```

3. Call the function
```js
window.go.main.App.Greet(name).then((result) => {
    // Update result with data back from App.Greet()
    document.getElementById("result").innerText = result;
});
```

4. Build the app `wails build`
5. Run the compiled bin, the app will crash when the function is called

**Expected behaviour**
The app not crash

**Screenshots**

**System Details**
```
PS C:\Users\Baruna\Project\test> wails doctor
Wails CLI v2.0.0-beta.21
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.17.3
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       96.0.1054.34
npm             N/A             Installed       8.1.0
*upx            N/A             Installed       upx 3.96

* - Optional Dependency

---------
Your system is ready for Wails development!
```

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Nice pick up! The only way to debug this was to build a project with `-ide goland`, remove the `-w -s` flags from the build and debug the "(production)" build 🚀
