### ISSUE TITLE
runtime.Quit() is not valid

### ISSUE THREAD

**Issue by tmlaes** [wailsapp/wails#985]
runtime.Quit() call in js is not valid when framless=true is set

**Comment by leaanthony** [comment]
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). Thanks

**Comment by wangzezheng1991** [comment]
go：
	err := wails.Run(&options.App{
		Title:             "wialsDemo",
		Width:             720,
		Height:            570,
		DisableResize:     false,
		Fullscreen:        false,
		Frameless:         true,
		StartHidden:       false,
		HideWindowOnClose: false,
		//RGBA:              &options.RGBA{R: 33, G: 37, B: 43, A: 255},
		Assets:            assets,
		LogLevel:          logger.DEBUG,
		OnStartup:         app.startup,
		OnDomReady:        app.domReady,
		OnShutdown:        app.shutdown,
		Bind: []interface{}{
			app,
		},
		// Windows platform specific options
		Windows: &windows.Options{
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
			DisableWindowIcon:    true,
		},
	})
html:
<a  onclick="javascript:runtime.Quit()"></a>

**Comment by wangzezheng1991** [comment]
"<aonclick="javascript:runtime.Quit()">1111</a>"

**Comment by wangzezheng1991** [comment]
I know why，the close button is too close to the edge, causing the button click event not to fire.Thanks

**Comment by leaanthony** [comment]
Glad you got it sorted 👍
