### ISSUE TITLE
[v2] Windows: A long running backend call blocks the main thread

### ISSUE THREAD

**Issue by stffabi** [wailsapp/wails#986]
**Description**
Having a backend call in go which takes a long time, e.g. executing an external program, leads to a completely blocked main thread and therefore the WebView is also blocked.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new v2 template
2. Add a sleep to the Greet method.
3. Click on the button.
4. Window is completely blocked.

**Expected behaviour**
The window should not block and the WebView should still be responsive, e.g. for scrolling etc.

**System Details**
Wails Version: v2.0.0-beta.21
MacOS Version: 12.0.1
Go Version: go1.17.2
Windows Version: Windows 10 20H2

**Additional context**
I also checked how Darwin behaves in this case. It's slightly different, at least the Window is not blocked because `ProcessingMessages` is decoupled and send to another Go-Routine through a channel. So the window is responsive, but other backend calls are also get blocked until the first is done.

@leaanthony what's your opinion on this? We should at least fix the blocking of the main thread on windows, but what do you think about concurrent backend calls?
I advocate for not blocking backend calls if another backend call is still running, at least up to some degree, e.g. allow up to 10 concurrent calls?

**Comment by leaanthony** [comment]
Nice pick up. I just checked and yeah I can see how that would happen. I haven't got time to look at it tonight, but I'm wondering if this could be run in a go routine: https://github.com/wailsapp/wails/blob/master/v2/internal/frontend/desktop/windows/frontend.go#L401-L417

**Comment by stffabi** [comment]
Yes, I've tried to run that in a go routine. That seemed to work just fine. But I'm unsure if we should just unrestrictedly spawning new go routines.

**Comment by stffabi** [comment]
I could provide a PR if we agree on how we should go forward.

**Comment by leaanthony** [comment]
I think its fine 😀

**Comment by stffabi** [comment]
Great I'll provide a PR.
