### ISSUE TITLE
Update docs: App runtime emit - passing context

### ISSUE THREAD

**Issue by e8panse** [wailsapp/wails#997]
It is not clear how to work with context, runtime, and emit events.

For example we have go package inside app. This package needs to emit some messages to frontend (installing libraries on golang side, emit log messages to frontend side)

in main.go we bind this package to use installing functions.
in app.go we have domReady where we get context which is required to Emit messages.

How correctly to pass context?

app.go
```

func (b *App) domReady(ctx context.Context) {
//how to pass ctx from here to instance of this package???
}
```

main.go

```
somepackage := somepackage.NewPackage()
//then bind this
```

package code:

```
//how get this context here???
func NewPackage(ctx context.Context) *Package {
    return &Package{
      processLogCh: make(chan processLog),
      ctx: ctx,
    }
}

func (i *Package) Emit() {
	go func() {
		for {
			logMessage := <-i.processLogCh
			runtime.EventsEmit(i.ctx, "logs", logMessage)
		}
	}()
}

func (i *Package) Install() {
       //install action
	i.processLogCh <- "some log message"
}
.......
```

frontend:

```
function log(log:any){
      console.log(log)
}

window.runtime.EventsOn("somepackage", log);

function runInstall(){

window.go.somepackage.Install();

}
```

**Comment by leaanthony** [comment]
I'd have an Init method on your package that's called from your OnStartup or OnDomReady method

**Comment by e8panse** [comment]
Do you mean instead of to return pointer:



> 

It works perfectly, thank you!

**Comment by newillusions** [comment]
could you share a sample of what this ended up looking like?
I'm trying to do the same thing at the moment...
